---
sidebar: sidebar 
permalink: ontap-security-hardening/autosupport.html 
keywords: tr-4569, ontap hardening guide, security, proactively monitor, NetApp Digital Advisor, logs, context-sensitive data, configuration and status data, performance data, use https 
summary: 使用ONTAP的AutoSupport功能、您可以主动监控系统的运行状况。 
---
= NetApp AutoSupport
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media


[role="lead"]
通过ONTAP的AutoSupport功能、您可以主动监控系统的运行状况、并自动向NetApp技术支持、组织的内部支持团队或支持合作伙伴发送消息和详细信息。默认情况下、首次配置存储系统时、系统会启用向NetApp技术支持发送的AutoSupport消息。此外、AutoSupport在启用后24小时开始向NetApp技术支持发送消息。此24小时时间段是可配置的。要利用与组织内部支持团队的通信、必须完成邮件主机配置。

只有集群管理员才能执行AutoSupport管理(配置)。SVM 管理员没有 AutoSupport 访问权限。可以禁用 AutoSupport 功能。但是、NetApp建议启用此功能、因为AutoSupport有助于在存储系统出现问题时加快问题识别和解决速度。默认情况下、即使禁用AutoSupport、系统也会收集AutoSupport信息并将其存储在本地。

有关AutoSupport消息的更多详细信息、包括各种消息中包含的内容以及不同类型的消息的发送位置、请参见文档。 link:https://activeiq.netapp.com/custom-dashboard/search["NetApp数字顾问"^]

AutoSupport消息包含敏感数据、包括但不限于以下各项：

* 日志文件
* 有关特定子系统的上下文相关数据
* 配置和状态数据
* 性能数据


对于传输协议， AutoSupport 支持 HTTPS ， HTTP 和 SMTP 。由于 AutoSupport 消息的敏感性， NetApp 强烈建议使用 HTTPS 作为向 NetApp 支持部门发送 AutoSupport 消息的默认传输协议。

此外、您还应利用 `system node autosupport modify` 命令指定AutoSupport数据的目标(例如、NetApp技术支持、组织的内部运营或合作伙伴)。此命令还允许您指定要发送的特定AutoSupport详细信息(例如性能数据、日志文件等)。

要完全禁用AutoSupport、请使用 `system node autosupport modify -state disable` 命令。
