---
sidebar: sidebar 
permalink: ontap-security-hardening/create-fpolicy.html 
keywords: tr-4569, ontap hardening guide, security, native, external server, file policy, take actions, synchronous, asynchronous, storage workload security 
summary: 为了提供文件可见性和访问控制、ONTAP解决方案使用NetApp FPolicy功能。 
---
= 创建并使用NetApp FPolicy
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media


[role="lead"]
您可以创建和使用FPolicy、这是ONTAP解决方案的基础架构组件、支持合作伙伴应用程序监控和设置文件访问权限。更强大的应用程序之一是存储工作负载安全性、这是一款NetApp SaaS应用程序、可集中查看和控制混合云环境中的所有企业数据访问、以确保满足安全性和合规性目标。

访问控制是一个关键的安全概念。可见性以及对文件访问和文件操作的响应能力对于维护您的安全防护至关重要。为了提供文件可见性和访问控制、ONTAP解决方案使用NetApp FPolicy功能。

可以根据文件类型设置文件策略。FPolicy用于确定存储系统如何处理来自各个客户端系统的操作请求、例如创建、打开、重命名和删除。从ONTAP 9开始、FPolicy文件访问通知框架得到了增强、具有筛选控件和短时网络中断故障恢复能力。

.步骤
. 要利用FPolicy功能、必须先使用命令创建FPolicy策略 `vserver fpolicy policy create` 。
+

NOTE: 此外、如果使用FPolicy查看和收集事件、请使用 `-events` 参数。通过ONTAP提供的额外粒度、可以筛选和访问用户名级别的控制。要使用用户名控制权限和访问、请指定 `-privilege-user-name` 参数。

+
以下文本提供了创建FPolicy的示例：

+
[listing]
----
cluster1::> vserver fpolicy policy create -vserver vs1.example.com -policy-name vs1_pol -events cserver_evt,v1e1 -engine native -is-mandatory true -allow-privileged-access no -is-passthrough-read-enabled false
----
. 创建FPolicy策略后、必须使用命令启用它 `vserver fpolicy enable` 。此命令还会设置FPolicy条目的优先级或顺序。
+

NOTE: FPolicy顺序非常重要、因为如果多个策略订阅了同一个文件访问事件、则该顺序指示授予或拒绝访问的顺序。

+
以下文本提供了用于启用FPolicy策略并使用命令验证配置的示例配置 `vserver fpolicy show` ：

+
[listing]
----
cluster1::> vserver fpolicy enable -vserver vs2.example.com -policy-name vs2_pol -sequence-number 5

cluster1::> vserver fpolicy show
Vserver                 Policy Name                    Sequence  Status   Engine
----------------------- ------------------------------ --------  -------  -------
vs1.example.com         vs1_pol
vs2.example.com         vs2_pol
 external
2 entries were displayed.
----




== FPolicy增强功能

ONTAP 9包括以下各节所述的FPolicy增强功能。



=== 筛选控件

新筛选器可用于 `SetAttr` 和删除有关目录活动的通知。



=== 异步故障恢复能力

如果在异步模式下运行的 FPolicy 服务器发生网络中断，则在中断期间生成的 FPolicy 通知将存储在存储节点上。当 FPolicy 服务器恢复联机时，它会收到存储的通知警报，并可从存储节点提取这些通知。在中断期间可以存储通知的时间长度可配置为长达 10 分钟。
