---
sidebar: sidebar 
permalink: ontap-security-hardening/multi-admin-verify.html 
keywords: tr-4569, ontap hardening guide, security, MAV, multi admin verify, multi-admin verification 
summary: 通过要求验证其他管理员来限制单个管理员对关键ONTAP命令的访问。 
---
= 多管理员验证
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
从ONTAP 9.11.1开始、您可以使用多管理员验证(MAV)来执行某些操作、例如删除卷或Snapshot副本、但这些操作必须经过指定管理员的批准。这样可以防止受到影响的管理员、恶意管理员或经验不足的管理员进行不希望的更改或删除数据。

配置MAV包括以下内容：

* link:../multi-admin-verify/manage-groups-task.html["创建一个或多个管理员批准组。"]
* link:../multi-admin-verify/enable-disable-task.html["启用多管理员验证功能。"]
* link:../multi-admin-verify/manage-rules-task.html["添加或修改规则。"]


完成初始配置后、只有MAV批准组中的管理员(MAV管理员)才能修改这些元素。

启用MAV后、完成每个受保护操作需要三个步骤：

. 当用户启动操作时、将显示 link:../multi-admin-verify/request-operation-task.html["已生成请求。"]
. 在执行之前、需要指定的数量 link:../multi-admin-verify/manage-requests-task.html["MAV管理员必须批准。"]
. 批准后、用户完成操作。


MAV不适用于涉及大量自动化的卷或工作流、因为每个自动化任务都需要经过批准才能完成操作。如果要同时使用自动化和MAV、NetApp建议您对特定MAV操作使用查询。例如、您只能将MAV规则应用 `volume delete` 于不涉及自动化的卷、并且可以使用特定的命名方案来指定这些卷。

有关MAV的更多详细信息，请参见 link:../multi-admin-verify/index.html["ONTAP多管理员验证文档"]。
