---
sidebar: sidebar 
permalink: ransomware-solutions/ransomware-snaplock-tamperproof-snapshots.html 
keywords: tr-4572, technical report, ransomware, protect, protection, netapp ransomware protection, netapp tr, ontap tr 
summary: NetApp的勒索软件保护包括SnapLock、事实证明、它在防范勒索软件威胁方面非常有效。 
---
= SnapLock和防篡改Snapshot副本、用于勒索软件保护
:allow-uri-read: 


[role="lead"]
SnapLock是NetApp Snap Arvanson中的一项重要武器、经验证、它在防范勒索软件威胁方面非常有效。通过防止未经授权的数据删除、SnapLock提供了额外的安全保护层、确保即使发生恶意攻击、关键数据也能保持完好并可访问。



== SnapLock 合规性

SnapLock Compliance (SLC)可为您的数据提供不可替代的保护。即使管理员尝试重新初始化阵列、SLC也禁止删除数据。与其他竞争产品不同、SnapLock Compliance不容易通过这些产品的支持团队遭受社会工程黑客攻击。受SnapLock Compliance卷保护的数据在达到其到期日期之前是可恢复的。

要启用SnapLock、link:../system-admin/manage-licenses-concept.html["ONTAP One"]需要许可证。

.了解更多信息。
* link:../snaplock/index.html["SnapLock文档"]




== 防篡改Snapshot副本

防篡改Snapshot (TPS)副本提供了一种便捷快速的方法来保护数据免受恶意行为的影响。与SnapLock Compliance不同、TPS通常在主系统上使用、在主系统中、用户可以在确定的时间内保护数据、并将数据留在本地进行快速恢复、或者无需将数据复制出主系统。TPS使用SnapLock技术来防止主Snapshot副本被使用相同SnapLock保留期限的ONTAP管理员删除。即使卷未启用SnapLock、也会阻止删除Snapshot副本、尽管快照与SnapLock Compliance卷的不可删除性质不同。

要使Snapshot副本不经过篡改、link:../system-admin/manage-licenses-concept.html["ONTAP One"]需要许可证。

.了解更多信息。
* link:../snaplock/snapshot-lock-concept.html["锁定Snapshot副本、防止勒索软件攻击"](英文)

