---
permalink: s3-config/create-data-lifs-task.html 
sidebar: sidebar 
keywords: tr-4814, create, data, lifs 
summary: 如果创建了新的 SVM ，则为 S3 访问创建的专用 LIF 应为数据 LIF 。 
---
= 为ONTAP S3创建数据LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果创建了新的 SVM ，则为 S3 访问创建的专用 LIF 应为数据 LIF 。

.开始之前
* 底层物理或逻辑网络端口必须已配置为管理 `up`状态。有关的详细信息 `up`，请参见link:https://docs.netapp.com/us-en/ontap-cli/up.html["ONTAP 命令参考"^]。
* 如果您计划使用子网名称为 LIF 分配 IP 地址和网络掩码值，则此子网必须已存在。
+
子网包含属于同一第 3 层子网的 IP 地址池。它们是使用创建的 `network subnet create` 命令：

* LIF 服务策略必须已存在。
* 作为最佳实践、用于数据访问的LIF(data-s3-server-server)和用于管理操作的LIF(management -https)应分开。不应在同一个LIF上同时启用这两个服务。
* DNS记录只能包含与data-s3-server关联的LUN的IP地址。如果在DNS记录中指定了其他LIF的IP地址、则其他服务器可能会处理ONTAP S3请求、从而导致意外响应或数据丢失。


.关于此任务
* 您可以在同一网络端口上创建 IPv4 和 IPv6 LIF 。
* 如果集群中有大量LIF、则可以使用验证集群上支持的LIF容量 `network interface capacity show` 命令以及每个节点上支持的LIF容量 `network interface capacity details show` 命令(在高级权限级别)。
* 如果要启用远程 FabricPool 容量（云）分层，则还必须配置集群间 LIF 。


.步骤
. 创建 LIF ：
+
`network interface create -vserver _svm_name_ -lif _lif_name_ -service-policy _service_policy_names_ -home-node _node_name_ -home-port _port_name_ {-address _IP_address_ -netmask _IP_address_ | -subnet-name _subnet_name_} -firewall-policy data -auto-revert {true|false}`

+
** `-home-node` 是LIF返回到的节点 `network interface revert` 命令将在LIF上运行。
+
您还可以使用指定LIF是否应自动还原到主节点和主端口 `-auto-revert` 选项

** `-home-port` 是LIF返回到的物理或逻辑端口 `network interface revert` 命令将在LIF上运行。
** 您可以使用指定IP地址 `-address` 和 `-netmask` 选项、或者使用启用从子网分配 `-subnet_name` 选项
** 使用子网提供 IP 地址和网络掩码时，如果使用网关定义了子网，则在使用该子网创建 LIF 时，系统会自动向 SVM 添加指向该网关的默认路由。
** 如果您手动分配 IP 地址（而不使用子网），则在其他 IP 子网上存在客户端或域控制器时，可能需要配置指向网关的默认路由。有关在SVM中创建静态路由的详细信息 `network route create`，请参见link:https://docs.netapp.com/us-en/ontap-cli/network-route-create.html["ONTAP 命令参考"^]。
** 。 `-firewall-policy` 选项中、使用相同的默认值 `data` 作为LIF角色。
+
如果需要，您可以稍后创建和添加自定义防火墙策略。

+

NOTE: 从ONTAP 9.10.1开始、防火墙策略已弃用、并完全替换为LIF服务策略。有关详细信息，请参见 link:../networking/configure_firewall_policies_for_lifs.html["为 LIF 配置防火墙策略"]。

** `-auto-revert` 用于指定在启动、更改管理数据库状态或建立网络连接等情况下、数据LIF是否自动还原到其主节点。默认设置为 `false`，但您可以将其设置为 `false` 具体取决于您环境中的网络管理策略。
** 。 `-service-policy` 选项用于指定您创建的数据和管理服务策略以及所需的任何其他策略。


. 如果要在中分配IPv6地址 `-address` 选项：
+
.. 使用 `network ndp prefix show` 命令以查看在各种接口上获取的RA前缀列表。
+
。 `network ndp prefix show` 命令可在高级权限级别下使用。

.. 使用格式 `prefix:id` 手动构建IPv6地址。
+
`prefix` 是在各种接口上获取的前缀。

+
用于派生 `id`下，选择一个随机的64位十六进制数。



. 使用验证是否已成功创建LIF `network interface show` 命令：
. 验证配置的 IP 地址是否可访问：
+
[cols="2*"]
|===
| 要验证 ... | 使用 ... 


 a| 
IPv4 地址
 a| 
`network ping`



 a| 
IPv6地址
 a| 
`network ping6`

|===


.示例
以下命令显示如何创建分配给的S3数据LIF `my-S3-policy` 服务策略：

[listing]
----
network interface create -vserver svm1.example.com -lif lif2 -home-node node2 -homeport e0d -service-policy my-S3-policy -subnet-name ipspace1
----
以下命令显示 cluster-1 中的所有 LIF 。数据 LIF datalif1 和 datalif3 配置了 IPv4 地址，而 datalif4 配置了 IPv6 地址：

[listing]
----
cluster-1::> network interface show

            Logical    Status     Network          Current      Current Is
Vserver     Interface  Admin/Oper Address/Mask     Node         Port    Home
----------- ---------- ---------- ---------------- ------------ ------- ----
cluster-1
            cluster_mgmt up/up    192.0.2.3/24     node-1       e1a     true
node-1
            clus1        up/up    192.0.2.12/24    node-1       e0a     true
            clus2        up/up    192.0.2.13/24    node-1       e0b     true
            mgmt1        up/up    192.0.2.68/24    node-1       e1a     true
node-2
            clus1        up/up    192.0.2.14/24    node-2       e0a     true
            clus2        up/up    192.0.2.15/24    node-2       e0b     true
            mgmt1        up/up    192.0.2.69/24    node-2       e1a     true
vs1.example.com
            datalif1     up/down  192.0.2.145/30   node-1       e1c     true
vs3.example.com
            datalif3     up/up    192.0.2.146/30   node-2       e0c     true
            datalif4     up/up    2001::2/64       node-2       e0c     true
5 entries were displayed.
----