---
permalink: s3-config/create-s3-object-store-server-task.html 
sidebar: sidebar 
keywords: create, s3 object, store, server 
summary: ONTAP 对象存储服务器将数据作为 S3 对象进行管理，而不是由 ONTAP NAS 和 SAN 服务器提供的文件或块存储。 
---
= 创建 S3 对象存储服务器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 对象存储服务器将数据作为 S3 对象进行管理，而不是由 ONTAP NAS 和 SAN 服务器提供的文件或块存储。

您应具有自签名 CA 证书（在先前步骤中创建）或由外部 CA 供应商签名的证书。在本地分层使用情形中， IP 流量仅通过集群 LIF 时，不需要 CA 证书。

创建对象存储服务器时，将创建 UID 为 0 的 root 用户。不会为此 root 用户生成访问密钥或机密密钥。ONTAP 管理员必须运行 `object-store-server users er生成 密钥` 命令来为此用户设置访问密钥和机密密钥。

[NOTE]
====
作为 NetApp 最佳实践，请勿使用此 root 用户。使用 root 用户的访问密钥或机密密钥的任何客户端应用程序都可以完全访问对象存储中的所有分段和对象。

====
有关其他配置和显示选项，请参见 `vserver object-store-server` 手册页。

.步骤
. 创建 S3 服务器：
+
`vserver object-store-server create -vserver svm_name -object-store-server s3_server_name -certificate-name ca_ct_name -comment text [additional _options]`

+
您可以在创建 S3 服务器时或以后任何时间指定其他选项。

+
** 如果要配置本地分层， SVM 名称可以是数据 SVM 或 `Cluster` （系统 SVM 名称）。
** 默认情况下， HTTPS 在端口 443 上处于启用状态。您可以使用 ` -secure listener-port` 选项更改端口号。
+
启用 HTTPS 后，要与 SSL/TLS 正确集成，需要 CA 证书。

** 默认情况下， HTTP 处于禁用状态；启用后，服务器将侦听端口 80 。您可以使用 ` -is-http-enabled` 选项启用此端口，也可以使用 ` -listener-port` 选项更改端口号。
+
启用 HTTP 后，所有请求和响应都将通过网络以明文形式发送。



. 验证是否已根据需要配置 S3 ：
+
`vserver object-store-server show`



以下命令将验证所有对象存储服务器的配置值：

[listing]
----
cluster1::> vserver object-store-server show

            Vserver: vs1

                      Object Store Server Name: s3.example.com
                          Administrative State: up
                        Listener Port For HTTP: 80
                Secure Listener Port For HTTPS: 443
                                  HTTP Enabled: false
                                 HTTPS Enabled: true
             Certificate for HTTPS Connections: svm1_ca
                                       Comment: Server comment
----