---
permalink: s3-config/create-intercluster-lifs-remote-fabricpool-tiering-task.html 
sidebar: sidebar 
keywords: create, intercluster, lifs, remote fabricpool, tiering 
summary: 如果要使用 ONTAP S3 启用远程 FabricPool 容量（云）分层，则必须配置集群间 LIF 。您可以在与数据网络共享的端口上配置集群间 LIF 。这样可以减少集群间网络连接所需的端口数量。 
---
= 为远程 FabricPool 分层创建集群间 LIF
:icons: font
:imagesdir: ../media/


[role="lead"]
如果要使用 ONTAP S3 启用远程 FabricPool 容量（云）分层，则必须配置集群间 LIF 。您可以在与数据网络共享的端口上配置集群间 LIF 。这样可以减少集群间网络连接所需的端口数量。

.您需要什么？ #8217 ；将需要什么
* 底层物理或逻辑网络端口必须已配置为管理 `up` 状态。
* LIF 服务策略必须已存在。


本地 Fabric Pool 分层或提供外部 S3 应用程序不需要集群间 LIF 。

.步骤
. 列出集群中的端口：
+
`network port show`

+
以下示例显示了 `cluster01` 中的网络端口：

+
[listing]
----

cluster01::> network port show
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
cluster01-01
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
cluster01-02
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
----
. 在系统 SVM 上创建集群间 LIF ：
+
`network interface create -vserver cluster -lif LIF_name -service-policy default-intercluster -home-node node -home-port port -address port_ip -netmask netmask`

+
以下示例将创建集群间 LIF `cluster01_icl01` 和 `cluster01_icl02` ：

+
[listing]
----

cluster01::> network interface create -vserver Cluster -lif cluster01_icl01 -service-
policy default-intercluster -home-node cluster01-01 -home-port e0c -address 192.168.1.201
-netmask 255.255.255.0

cluster01::> network interface create -vserver Cluster -lif cluster01_icl02 -service-
policy default-intercluster -home-node cluster01-02 -home-port e0c -address 192.168.1.202
-netmask 255.255.255.0
----
. 验证是否已创建集群间 LIF ：
+
`network interface show -service-policy default-intercluster`

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
cluster01
            cluster01_icl01
                       up/up      192.168.1.201/24   cluster01-01  e0c     true
            cluster01_icl02
                       up/up      192.168.1.202/24   cluster01-02  e0c     true
----
. 验证集群间 LIF 是否冗余：
+
`network interface show – service-policy default-intercluster -failover`

+
以下示例显示 `e0c` 端口上的集群间 LIF `cluster01_icl01` 和 `cluster01_icl02` 将故障转移到 `e0d` 端口。

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster –failover
         Logical         Home                  Failover        Failover
Vserver  Interface       Node:Port             Policy          Group
-------- --------------- --------------------- --------------- --------
cluster01
         cluster01_icl01 cluster01-01:e0c   local-only      192.168.1.201/24
                            Failover Targets: cluster01-01:e0c,
                                              cluster01-01:e0d
         cluster01_icl02 cluster01-02:e0c   local-only      192.168.1.201/24
                            Failover Targets: cluster01-02:e0c,
                                              cluster01-02:e0d
----

