---
permalink: s3-config/create-bucket-task.html 
sidebar: sidebar 
keywords: s3, bucket, system manager, 
summary: S3对象保留在_bep桶_中。它们不会作为文件嵌套在其他目录的目录中。 
---
= 创建ONTAP S3存储分段
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3对象保留在_bep桶_中。它们不会作为文件嵌套在其他目录的目录中。

.开始之前
包含S3服务器的Storage VM必须已存在。

.关于此任务
* 从ONTAP 9.14.1开始、在S3 FlexGroup卷上创建存储分段时、已启用自动调整大小功能。这样可以避免在现有和新FlexGroup卷上创建存储分段期间分配过多的容量。根据以下准则、FlexGroup卷的大小将调整为所需的最小大小。所需的最小大小为FlexGroup卷中所有S3分段的总大小。
+
** 从ONTAP 9.14.1开始、如果在创建新存储分段时创建了S3 FlexGroup卷、则会使用所需的最小大小创建FlexGroup卷。
** 如果S3 FlexGroup卷是在ONTAP 9.14.1之前创建的、则在ONTAP 9.14.1之后创建或删除的第一个分段会将FlexGroup卷大小调整为所需的最小大小。
** 如果S3 FlexGroup卷是在ONTAP 9.14.1之前创建的、并且已达到所需的最小大小、则在ONTAP 9.14.1之后创建或删除存储分段时、S3 FlexGroup卷的大小将保持不变。


* 存储服务级别是预定义的自适应服务质量（ QoS ）策略组，具有 _value_ ， _performage_ 和 _Extreme 默认级别。您还可以定义自定义 QoS 策略组并将其应用于存储分段，而不是默认存储服务级别之一。有关存储服务定义的详细信息，请参见link:storage-service-definitions-reference.html["存储服务定义"]。有关性能管理的详细信息，请参见link:../performance-admin/index.html["性能管理"]。从 ONTAP 9.8 开始，在配置存储时，默认情况下会启用 QoS 。您可以在配置过程中或稍后禁用QoS或选择自定义QoS策略。


* 如果要配置本地容量分层、则需要在数据Storage VM中创建存储分段和用户、而不是在S3服务器所在的系统Storage VM中创建存储分段和用户。
* 要进行远程客户端访问，您必须在启用了 S3 的 Storage VM 中配置存储分段。如果在未启用 S3 的 Storage VM 中创建存储分段，则此分段仅可用于本地分层。
* 从ONTAP 9.14.1开始、您可以执行此操作 link:create-bucket-mcc-task.html["在MetroCluster配置中的镜像或未镜像聚合上创建分段"]。
* 对于CLI、在创建存储分段时、您有两个配置选项：
+
** Let ONTAP Select the underlying aggregates and FlexGroup components （默认）
+
*** ONTAP 会通过自动选择聚合来为第一个存储分段创建和配置 FlexGroup 卷。它将自动选择可用于您的平台的最高服务级别，或者您也可以指定存储服务级别。稍后在Storage VM中添加的任何其他分段都将具有相同的底层FlexGroup卷。
*** 或者，您也可以指定存储分层是否会使用存储分段，在这种情况下， ONTAP 会尝试选择低成本介质，以便为分层数据提供最佳性能。


** 您可以选择底层聚合和FlexGroup组件(需要高级权限命令选项)：您可以选择手动选择必须创建存储分段和所属FlexGroup卷的聚合、然后指定每个聚合上的成分卷数。添加其他分段时：
+
*** 如果为新存储分段指定聚合和成分卷，则会为新存储分段创建新的 FlexGroup 。
*** 如果不为新存储分段指定聚合和成分卷，则新存储分段将添加到现有 FlexGroup 中。
请参见 xref:../flexgroup/index.html[FlexGroup 卷管理] 有关详细信息 ...
+
在创建存储分段时指定聚合和成分卷时，不会应用任何 QoS 策略组，默认或自定义。您可以稍后使用执行此操作 `vserver object-store-server bucket modify` 命令：

+
有关链接：https://docs．．NetApp ONTAP－CLI/vserver-object-store-server-show.html命令的更多信息，请[`vserver object-store-server bucket modify`参阅ONTAP命令参考。

+
*注意：*如果您正在从Cloud Volumes ONTAP 提供存储分段、则应使用命令行界面操作步骤。强烈建议您手动选择底层聚合、以确保它们仅使用一个节点。使用这两个节点的聚合可能会影响性能、因为这些节点将位于不同地理位置的可用性区域中、因此容易受到延迟问题的影响。









== 使用ONTAP命令行界面创建S3存储分段

. 如果您计划自己选择聚合和FlexGroup组件、请将权限级别设置为高级(否则、管理权限级别就足够了)： `set -privilege advanced`
. 创建存储分段：
+
`vserver object-store-server bucket create -vserver _svm_name_ -bucket _bucket_name_ [-size integer[KB|MB|GB|TB|PB]] [-comment text] [additional_options]`

+
Storage VM名称可以是数据Storage VM或 `Cluster` (系统Storage VM名称)。

+
如果未指定任何选项、ONTAP将创建一个800 GB的分段、并将服务级别设置为系统可用的最高级别。

+
如果您希望 ONTAP 根据性能或使用情况创建存储分段，请使用以下选项之一：

+
** 服务级别
+
包括 `-storage-service-level` 具有以下值之一的选项： `value`， `performance`或 `extreme`。

** 分层
+
包括 `-used-as-capacity-tier true` 选项



+
如果要指定用于创建底层 FlexGroup 卷的聚合，请使用以下选项：

+
** 。 `-aggr-list` 参数用于指定要用于FlexGroup卷成分卷的聚合列表。
+
列表中的每个条目都会在指定聚合上创建一个成分卷。您可以多次指定一个聚合，以便在该聚合上创建多个成分卷。

+
为了在整个 FlexGroup 卷中保持性能一致，所有聚合都必须使用相同的磁盘类型和 RAID 组配置。

** 。 `-aggr-list-multiplier` 参数用于指定迭代随一起列出的聚合的次数 `-aggr-list` 参数FlexGroup。
+
的默认值 `-aggr-list-multiplier` 参数为4。



. 根据需要添加 QoS 策略组：
+
`vserver object-store-server bucket modify -bucket _bucket_name_ -qos-policy-group _qos_policy_group_`

. 验证存储分段创建：
+
`vserver object-store-server bucket show [-instance]`



.示例
以下示例将为Storage VM创建存储分段 `vs1` 大小 `1TB` 并指定聚合：

有关此过程中所述命令的更多信息，请参见link:https://docs.netapp.com/us-en/ontap-cli/["ONTAP 命令参考"^]。

[listing]
----
cluster-1::*> vserver object-store-server bucket create -vserver svm1.example.com -bucket testbucket -aggr-list aggr1 -size 1TB
----


== 使用System Manager创建S3存储分段

. 在启用了 S3 的 Storage VM 上添加新存储分段。
+
.. 单击 * 存储 > 分段 * ，然后单击 * 添加 * 。
.. 输入名称，选择 Storage VM 并输入大小。
+
*** 如果此时单击 * 保存 * ，则会使用以下默认设置创建一个存储分段：
+
**** 除非任何组策略已生效，否则不会向任何用户授予对存储分段的访问权限。
+

NOTE: 您不应使用 S3 root 用户管理 ONTAP 对象存储并共享其权限，因为它对对象存储具有无限制的访问权限。而是使用您分配的管理权限创建一个用户或组。

**** 系统可用性最高的服务质量（性能）级别。


*** 单击*Save*以使用这些默认值创建分段。








=== 配置其他权限和限制

您可以在配置存储分段时单击*More Options (*更多选项*)来配置对象锁定、用户权限和性能级别设置，也可以稍后修改这些设置。

如果要使用 S3 对象存储进行 FabricPool 分层，请考虑选择 * 用于分层 * （使用低成本介质，为分层数据提供最佳性能），而不是性能服务级别。

如果要为对象启用版本控制以便稍后恢复，请选择*Enable Versioning*。如果要在存储分段上启用对象锁定、则默认情况下会启用版本控制。有关对象版本控制的信息、请参见 https://docs.aws.amazon.com/AmazonS3/latest/userguide/Versioning.html["在适用于Amazon的S3存储分段中使用版本控制"]。

从9.14.1开始、S3存储分段支持对象锁定。S3对象锁定需要标准SnapLock许可证。此许可证包含在中link:../system-admin/manage-licenses-concept.html["ONTAP One"]。在ONTAP One之前、SnapLock许可证包含在"安全性和合规性"包中。安全与合规性包不再提供、但仍然有效。虽然目前并不需要，但现有客户可以选择 https://docs.netapp.com/us-en/ontap/system-admin/download-nlf-task.html["升级到ONTAP One"]。如果要在存储分段上启用对象锁定，则应 https://docs.netapp.com/us-en/ontap/system-admin/manage-license-task.html["验证是否已安装SnapLock许可证"]。如果未安装SnapLock许可证、则必须 https://docs.netapp.com/us-en/ontap/system-admin/install-license-task.html["安装"]先安装该许可证、然后才能启用对象锁定。确认已安装SnapLock许可证后，要防止存储分段中的对象被删除或覆盖，请选择*Enable object locking*。锁定可以在所有或特定版本的对象上启用、并且只能在为集群节点初始化SnapLock Compliance时钟时才启用。请按照以下步骤操作：

. 如果未在集群的任何节点上初始化SnapLock Compliance时钟，则会显示*初 始化SnapLock Compliance Clock*按钮。单击*初始化SnapLock Compliance Clock*以初始化集群节点上的SnapLock Compliance时钟。
. 选择*监管*模式可激活基于时间的锁定，该锁定允许对对象具有_Write Once, Read M众多(WORM)_权限。即使在_监管_模式下、具有特定权限的管理员用户也可以删除这些对象。
. 如果要对对象指定更严格的删除和更新规则，请选择*Compliance模式。在此对象锁定模式下、对象只能在指定保留期限结束后过期。除非指定保留期限、否则对象将无限期保持锁定状态。
. 如果希望锁定在特定时间段内有效、请指定锁定的保留期限(以天或年为单位)。
+

NOTE: 锁定适用于分版本和非分版本S3分段。对象锁定不适用于NAS对象。



您可以为存储分段配置保护和权限设置以及性能服务级别。


NOTE: 在配置权限之前、您必须已创建用户和组。

有关信息，请参见 link:../s3-snapmirror/create-remote-mirror-new-bucket-task.html["为新存储分段创建镜像"]。



=== 验证对存储分段的访问

在S3客户端应用程序(无论是ONTAP S3还是外部第三方应用程序)上、您可以输入以下命令来验证您对新创建存储分段的访问权限：

* S3 服务器 CA 证书。
* 用户的访问密钥和机密密钥。
* S3 服务器 FQDN 名称和存储分段名称。

