---
permalink: s3-config/index.html 
sidebar: sidebar 
keywords: decide, s3, configuration, client, access, configure, object, bucket, svm 
summary: 从 ONTAP 9.8 开始，您可以在 ONTAP 集群中启用 ONTAP 简单存储服务（ S3 ）对象存储服务器。 
---
= S3配置概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
从ONTAP 9.8开始、您可以在ONTAP集群中启用ONTAP简单存储服务(S3)对象存储服务器、使用ONTAP System Manager等熟悉的易管理性工具快速为ONTAP中的开发和操作配置高性能对象存储、并利用ONTAP的存储效率和安全性。

ONTAP中S3的主要用例包括：

* 使用FabricPool将非活动数据分层到ONTAP中的存储分段、从而实现ONTAP到ONTAP的分层。同时支持分层到中的存储分段 link:enable-ontap-s3-access-local-fabricpool-task.html["本地集群"] 或分层到上的存储分段 link:enable-ontap-s3-access-remote-fabricpool-task.html["远程集群"] 。通过分层到ONTAP S3、您可以使用成本更低的ONTAP系统来存储非活动数据、并节省新闪存容量的资金、而无需额外的FabricPool许可证或新技术进行管理。
* 从ONTAP 9.12.1开始、还可以在已预先配置为使用NAS协议的中启用S3 link:../s3-multiprotocol/index.html["多协议NAS卷"] 协议。如果在多协议NAS卷中启用了S3协议、则客户端应用程序可以使用S3、NFS和SMB读写数据、这就打开了各种其他使用情形。最常见的使用情形之一是NAS客户端向卷写入数据、而S3客户端读取相同的数据并执行分析、业务智能、机器学习和光学字符识别等专业任务。



NOTE: 如果您希望在现有ONTAP集群上启用S3功能而无需额外的硬件和管理、则可以使用ONTAP S3。NetApp StorageGRID是NetApp的旗舰级对象存储解决方案。对于本机S3应用程序、如果需要利用所有S3操作、高级ILM功能或基于ONTAP的系统无法实现的功能、建议使用StorageGRID。有关详细信息，请参见 link:https://docs.netapp.com/us-en/storagegrid-118/index.html["StorageGRID 文档"^]。



== 使用System Manager和ONTAP 命令行界面进行S3配置

您可以使用System Manager和ONTAP 命令行界面配置和管理ONTAP S3。启用S3并使用System Manager创建存储分段时、ONTAP 会选择最佳实践默认值以简化配置。如果需要指定配置参数、则可能需要使用ONTAP 命令行界面。  如果您从CLI配置S3服务器和存储分段、则仍可根据需要使用System Manager对其进行管理、反之亦然。

使用 System Manager 创建 S3 存储分段时， ONTAP 会配置系统上可用性最高的默认性能服务级别。例如，在 AFF 系统上，默认设置为 * 至尊 * 。性能服务级别是预定义的自适应服务质量（ QoS ）策略组。您可以指定自定义 QoS 策略组，也可以不指定策略组，而不指定默认服务级别之一。

预定义的自适应 QoS 策略组包括：

* * 至尊 * ：用于预期延迟最低且性能最高的应用程序。
* * 性能 * ：用于性能需求和延迟适中的应用程序。
* * 值 * ：用于吞吐量和容量比延迟更重要的应用程序。
* * 自定义 * ：指定自定义 QoS 策略或不指定 QoS 策略。


如果选择 * 用于分层 * ，则不会选择任何性能服务级别，系统会尝试为分层数据选择具有最佳性能的低成本介质。

另请参见： link:../performance-admin/adaptive-qos-policy-groups-task.html["使用自适应 QoS 策略组"]。

ONTAP 会尝试在磁盘最合适的本地层上配置此存储分段，以满足所选的服务级别。但是，如果需要指定要包含在存储分段中的磁盘，请考虑通过指定本地层（聚合）从 CLI 配置 S3 对象存储。如果您通过 CLI 配置 S3 服务器，则仍可根据需要使用 System Manager 对其进行管理。

如果您希望能够指定用于存储分段的聚合，则只能使用命令行界面来执行此操作。



== 在Cloud Volumes ONTAP 上配置S3存储分段

如果要从Cloud Volumes ONTAP 提供存储分段、强烈建议您手动选择底层聚合、以确保它们仅使用一个节点。使用这两个节点的聚合可能会影响性能、因为这些节点将位于不同地理位置的可用性区域中、因此容易受到延迟问题的影响。因此、在Cloud Volumes ONTAP 环境中、您应该执行此操作 xref:create-bucket-task.html[从CLI配置S3存储分段]。

否则、Cloud Volumes ONTAP 上的S3服务器在Cloud Volumes ONTAP 中的配置和维护与在内部环境中相同。
