---
permalink: snaplock/create-snaplock-volume-task.html 
sidebar: sidebar 
keywords: snaplock, volume, shanpshot, copy, create, complianceclock, file, worm, compliance, enterprise 
summary: '您必须为要提交到WORM状态的文件或快照创建SnapLock卷。从 ONTAP 9.10.1 开始，无论聚合类型如何，您创建的任何卷都会默认创建为非 SnapLock 卷。您必须使用 `-snaplock-type`选项通过指定"Compliance (合规性)"或"Enterprise (企业)"作为SnapLock类型来显式创建SnapLock卷。默认情况下，SnapLock类型设置为 `non-snaplock`。' 
---
= 创建并挂载ONTAP SnapLock卷
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须为要提交到WORM状态的文件或快照创建SnapLock卷。从 ONTAP 9.10.1 开始，无论聚合类型如何，您创建的任何卷都会默认创建为非 SnapLock 卷。您必须使用 `-snaplock-type`选项通过指定"Compliance (合规性)"或"Enterprise (企业)"作为SnapLock类型来显式创建SnapLock卷。默认情况下，SnapLock类型设置为 `non-snaplock`。

.开始之前
* SnapLock 聚合必须处于联机状态。
* 您应该link:../system-admin/manage-license-task.html["验证是否已安装SnapLock许可证"]。如果节点上未安装SnapLock许可证、则必须安装link:../system-admin/install-license-task.html["安装"]该许可证。此许可证包含在中link:../system-admin/manage-licenses-concept.html["ONTAP One"]。在ONTAP One之前、SnapLock许可证包含在"安全性和合规性"包中。安全与合规性包不再提供、但仍然有效。虽然目前并不需要，但现有客户可以选择link:../system-admin/download-nlf-task.html["升级到ONTAP One"]。
* link:../snaplock/initialize-complianceclock-task.html["必须初始化节点上的Compliance时钟"](英文)


.关于此任务
使用适当的 SnapLock 权限，您可以随时销毁或重命名企业卷。在保留期限结束之前，不能销毁 Compliance 卷。您不能重命名 Compliance 卷。

您可以克隆 SnapLock 卷，但不能克隆 SnapLock 卷上的文件。克隆卷的 SnapLock 类型与父卷相同。

[NOTE]
====
SnapLock卷不支持LUN。只有当在非SnapLock卷上创建的快照传输到SnapLock卷以在SnapLock存储关系中进行保护时、SnapLock卷才支持LUN。读/写SnapLock卷不支持LUN。但是、包含LUN的SnapMirror源卷和目标卷均支持防篡改快照。

====
使用ONTAP 系统管理器或ONTAP 命令行界面执行此任务。

[role="tabbed-block"]
====
.System Manager
--
从ONTAP 9.12.1开始、您可以使用System Manager创建SnapLock 卷。

.步骤
. 导航到*存储>卷*、然后单击*添加*。
. 在*添加卷*窗口中、单击*更多选项*。
. 输入新卷的信息、包括卷的名称和大小。
. 选择*启用SnapLock *、然后选择SnapLock 类型：合规性或企业。
. 在*自动提交文件*部分中、选择*已修改*并输入文件在自动提交之前应保持不变的时间量。最小值为 5 分钟，最大值为 10 年。
. 在*数据保留*部分中、选择最短和最长保留期限。
. 选择默认保留期限。
. 单击 * 保存 * 。
. 在*卷*页面中选择新卷以验证SnapLock 设置。


--
.命令行界面
--
. 创建 SnapLock 卷：
+
[source, cli]
----
volume create -vserver <SVM_name> -volume <volume_name> -aggregate <aggregate_name> -snaplock-type <compliance|enterprise>
----
+
有关的详细信息 `volume create`，请参见link:https://docs.netapp.com/us-en/ontap-cli/volume-create.html["ONTAP 命令参考"^]。以下选项不适用于SnapLock卷： `-nvfail`、、 `-atime-update` `-is-autobalance-eligible`、 `-space-mgmt-try-first`和 `vmalign`。

+
以下命令将创建SnapLock `Compliance` 名为的卷 `vol1` 开启 `aggr1` 开启 `vs1`：

+
[listing]
----
cluster1::> volume create -vserver vs1 -volume vol1 -aggregate aggr1 -snaplock-type compliance
----


--
====


== 挂载 SnapLock 卷

您可以将 SnapLock 卷挂载到 SVM 命名空间中的接合路径以供 NAS 客户端访问。

.开始之前
SnapLock 卷必须处于联机状态。

.关于此任务
* 您只能将 SnapLock 卷挂载到 SVM 的根目录下。
* 不能将常规卷挂载到 SnapLock 卷下。


.步骤
. 挂载 SnapLock 卷：
+
`*volume mount -vserver _SVM_name_ -volume _volume_name_ -junction-path _path_*`

+
有关的详细信息 `volume mount`，请参见link:https://docs.netapp.com/us-en/ontap-cli/volume-mount.html["ONTAP 命令参考"^]。

+
以下命令会挂载名为的SnapLock卷 `vol1` 连接到接合路径 `/sales` 在中 `vs1` 命名空间：

+
[listing]
----
cluster1::> volume mount -vserver vs1 -volume vol1 -junction-path /sales
----

