---
permalink: snaplock/create-snaplock-aggregate-task.html 
sidebar: sidebar 
keywords: create, snaplock, aggregate, compliance, enterprise, mode, volumes 
summary: '使用卷 `-snaplock-type` 用于指定Compliance或Enterprise SnapLock卷类型的选项。对于 ONTAP 9.10.1 之前的版本，必须创建单独的 SnapLock 聚合。从 ONTAP 9.10.1 开始， SnapLock 卷和非 SnapLock 卷可以位于同一聚合上；因此，如果使用的是 ONTAP 9.10.1 ，则不再需要创建单独的 SnapLock 聚合。' 
---
= 创建 SnapLock 聚合
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用卷 `-snaplock-type` 用于指定Compliance或Enterprise SnapLock卷类型的选项。对于 ONTAP 9.10.1 之前的版本，必须创建单独的 SnapLock 聚合。从 ONTAP 9.10.1 开始， SnapLock 卷和非 SnapLock 卷可以位于同一聚合上；因此，如果使用的是 ONTAP 9.10.1 ，则不再需要创建单独的 SnapLock 聚合。

.开始之前
* 您必须是集群管理员才能执行此任务。
* link:../system-admin/install-license-task.html["必须安装许可证"]节点上的SnapLock。中包含此许可证link:../system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP One"]。
* link:../snaplock/initialize-complianceclock-task.html["必须初始化节点上的Compliance时钟"](英文)
* 如果已将磁盘分区为 "`root` " ， " `data1` " 和 " `data2` " ，则必须确保备用磁盘可用。


.升级注意事项
升级到 ONTAP 9.10.1 时，系统会升级现有的 SnapLock 聚合和非 SnapLock 聚合，以支持 SnapLock 卷和非 SnapLock 卷的存在；但是，不会自动更新现有的 SnapLock 卷属性。例如，数据缩减，跨卷重复数据删除和跨卷后台重复数据删除字段保持不变。在现有聚合上创建的新 SnapLock 卷与非 SnapLock 卷具有相同的默认值，新卷和聚合的默认值取决于平台。

.还原注意事项
如果需要还原到 9.10.1 之前的 ONTAP 版本，则必须将所有 SnapLock Compliance ， SnapLock Enterprise 和 SnapLock 卷移动到其自己的 SnapLock 聚合。

.关于此任务
* 您不能为 FlexArray LUN 创建合规性聚合，但 FlexArray LUN 支持 SnapLock 合规性聚合。
* 您不能使用 SyncMirror 选项创建合规性聚合。
* 只有当 MetroCluster 配置中的镜像合规性聚合用于托管 SnapLock 审核日志卷时，才能在该聚合中创建。
+
[NOTE]
====
在 MetroCluster 配置中，镜像聚合和未镜像聚合支持 SnapLock Enterprise 。只有未镜像聚合才支持 SnapLock 合规性。

====


.步骤
. 创建 SnapLock 聚合：
+
[source, cli]
----
storage aggregate create -aggregate <aggregate_name> -node <node_name> -diskcount <number_of_disks> -snaplock-type <compliance|enterprise>
----
+
有关的详细信息 `storage aggregate create`，请参见link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-create.html["ONTAP 命令参考"^]。

+
以下命令将创建SnapLock `Compliance` 名为的聚合 `aggr1` 启用三个磁盘 `node1`：

+
[listing]
----
cluster1::> storage aggregate create -aggregate aggr1 -node node1 -diskcount 3 -snaplock-type compliance
----

