---
permalink: snaplock/create-snaplock-volume-task.html 
sidebar: sidebar 
keywords: snaplock, volume, shanpshot, copy, create, complianceclock, file, worm, compliance, enterprise 
summary: '您必须为要提交到 WORM 状态的文件或 Snapshot 副本创建 SnapLock 卷。从 ONTAP 9.10.1 开始，无论聚合类型如何，您创建的任何卷都会默认创建为非 SnapLock 卷。您必须使用 ` -SnapLock-type` 选项通过指定 Compliance 或 Enterprise 作为 SnapLock 类型来显式创建 SnapLock 卷。默认情况下， SnapLock 类型设置为 `non-SnapLock` 。' 
---
= 创建并挂载SnapLock 卷
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须为要提交到 WORM 状态的文件或 Snapshot 副本创建 SnapLock 卷。从 ONTAP 9.10.1 开始，无论聚合类型如何，您创建的任何卷都会默认创建为非 SnapLock 卷。您必须使用 ` -SnapLock-type` 选项通过指定 Compliance 或 Enterprise 作为 SnapLock 类型来显式创建 SnapLock 卷。默认情况下， SnapLock 类型设置为 `non-SnapLock` 。

.您需要的内容
* SnapLock 聚合必须处于联机状态。
* 节点上必须安装 SnapLock 许可证。
* 必须初始化节点上的 ComplianceClock 。


.关于此任务
使用适当的 SnapLock 权限，您可以随时销毁或重命名企业卷。在保留期限结束之前，不能销毁 Compliance 卷。您不能重命名 Compliance 卷。

您可以克隆 SnapLock 卷，但不能克隆 SnapLock 卷上的文件。克隆卷的 SnapLock 类型与父卷相同。

[NOTE]
====
SnapLock 卷不支持 LUN 。虽然可以使用传统技术将 LUN 移动到 SnapLock 卷上，但这不是受支持的操作，也不是涉及 SnapLock 卷上 LUN 的任何其他操作。

====
使用ONTAP 系统管理器或ONTAP 命令行界面执行此任务。

[role="tabbed-block"]
====
.System Manager
--
从ONTAP 9.12.1开始、您可以使用System Manager创建SnapLock 卷。

.步骤
. 导航到*存储>卷*、然后单击*添加*。
. 在*添加卷*窗口中、单击*更多选项*。
. 输入新卷的信息、包括卷的名称和大小。
. 选择*启用SnapLock *、然后选择SnapLock 类型：合规性或企业。
. 在*自动提交文件*部分中、选择*已修改*并输入文件在自动提交之前应保持不变的时间量。最小值为 5 分钟，最大值为 10 年。
. 在*数据保留*部分中、选择最短和最长保留期限。
. 选择默认保留期限。
. 单击 * 保存 * 。
. 在*卷*页面中选择新卷以验证SnapLock 设置。


--
.命令行界面
--
. 创建 SnapLock 卷：
+
` * volume create -vserver _svm_name_ -volume _volume_name_ -aggregate _aggregate_name_* -SnapLock-type compliancy| 企业`

+
有关完整的选项列表，请参见命令手册页。以下选项不适用于 SnapLock 卷： ` -nvfail` ， ` -atime-update` ， ` -is-autobalance-eligible` ， ` -space-mgmt-try-first` 和 `vmalign` 。

+
以下命令将在 `vs1` 上创建一个名为 `vol1` on `aggr1` on` vs1 `的 SnapLock Compliance 卷：

+
[listing]
----
cluster1::> volume create -vserver vs1 -volume vol1 -aggregate aggr1 -snaplock-type compliance
----


--
====


== 挂载 SnapLock 卷

您可以将 SnapLock 卷挂载到 SVM 命名空间中的接合路径以供 NAS 客户端访问。

.您需要的内容
SnapLock 卷必须处于联机状态。

.关于此任务
* 您只能将 SnapLock 卷挂载到 SVM 的根目录下。
* 不能将常规卷挂载到 SnapLock 卷下。


.步骤
. 挂载 SnapLock 卷：
+
` * volume mount -vserver _svm_name_ -volume _volume_name_ -junction-path _path_*`

+
有关完整的选项列表，请参见命令手册页。

+
以下命令会将名为 `vol1` 的 SnapLock 卷挂载到 `vs1` 命名空间中的接合路径 ` /sales` ：

+
[listing]
----
cluster1::> volume mount -vserver vs1 -volume vol1 -junction-path /sales
----

