---
permalink: snaplock/initialize-complianceclock-task.html 
sidebar: sidebar 
keywords: snaplock, complianceclock, compliance clock, initialize, worm, retention, period, node, ntp, reset, resynchronize 
summary: SnapLock ComplianceClock 可确保不会发生可能更改 WORM 文件保留期限的篡改。您必须在托管SnapLock聚合的每个节点上初始化系统合规时钟。  
---
= 初始化Compliance时钟
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapLock使用_volume Compliance Clock_来确保防止可能会更改WORM文件保留期限的篡改。您必须先在托管SnapLock聚合的每个节点上初始化_system CompletianceClock_。

从ONTAP 9.14.1开始、如果没有SnapLock卷或没有启用了快照锁定的卷、则可以初始化或重新初始化系统合规性时钟。通过重新初始化功能、系统管理员可以在系统Compliance时钟初始化可能不正确的情况下重置该时钟、或者更正系统上的时钟漂移。在ONTAP 9.13.1及更早版本中、一旦初始化节点上的Compliance时钟、您将无法再次初始化它。

.开始之前
重新初始化Compliance时钟：

* 集群中的所有节点都必须处于运行状况良好的状态。
* 所有卷都必须联机。
* 恢复队列中不能存在任何卷。
* 不能存在任何SnapLock卷。
* 不能存在已启用快照锁定的卷。


初始化Compliance时钟的一般要求：

* 您必须是集群管理员才能执行此任务。
* link:../system-admin/install-license-task.html["必须在此节点上安装SnapLock许可证"](英文)


.关于此任务
_volume Compliance Clock_继承了系统Compliance时钟上的时间、后者控制卷上WORM文件的保留期限。创建新SnapLock卷时、系统会自动初始化卷Compliance时钟。

[NOTE]
====
系统Compliance时钟的初始设置基于当前硬件系统时钟。因此、在初始化每个节点上的系统Compliance时钟之前、您应验证系统时间和时区是否正确。初始化节点上的系统合规时钟后、如果存在已启用锁定的SnapLock卷、则无法再次初始化该时钟。

====
.步骤
您可以使用ONTAP命令行界面初始化Compliance时钟、或者从ONTAP 9.12.1开始、您可以使用System Manager初始化Compliance时钟。

[role="tabbed-block"]
====
.System Manager
--
. 导航到*集群>概述*。
. 在*节点*部分中、单击*初始化SnapLock 合规性时钟*。
. 要显示*Compliance Clock*列并验证Compliance时钟是否已初始化，请在*Cluster > Overview > N节点*部分中单击*Show/Hide*并选择SnapLock Compliance Clock*。


--
--
.命令行界面
. 初始化系统Compliance时钟：
+
`snaplock compliance-clock initialize -node _node_name_`

+
以下命令将在上初始化系统Compliance时钟 `node1`：

+
[listing]
----
cluster1::> snaplock compliance-clock initialize -node node1
----
+
有关的详细信息 `snaplock compliance-clock initialize`，请参见link:https://docs.netapp.com/us-en/ontap-cli/snaplock-compliance-clock-initialize.html["ONTAP 命令参考"^]。

. 出现提示时、确认系统时钟是否正确、以及是否要初始化Compliance时钟：
+
[listing]
----
Warning: You are about to initialize the secure ComplianceClock of
the node "node1" to the current value of the node's system clock.
This procedure can be performed only once on a given node, so you
should ensure that the system time is set correctly before proceeding.

The current node's system clock is: Mon Apr 25 06:04:10 GMT 2016

Do you want to continue? (y|n): y
----
. 对托管 SnapLock 聚合的每个节点重复此操作步骤。


--
====


== 为配置了NTP的系统启用Compliance时钟重新同步

配置NTP服务器后、您可以启用SnapLock合规性时钟时间同步功能。

.开始之前
* 此功能仅在高级权限级别可用。
* 您必须是集群管理员才能执行此任务。
* link:../system-admin/install-license-task.html["必须在此节点上安装SnapLock许可证"](英文)
* 此功能仅适用于 Cloud Volumes ONTAP ， ONTAP Select 和 VSIM 平台。


.关于此任务
当SnapLock安全时钟守护进程检测到偏差超过阈值时、ONTAP将使用系统时间重置系统和卷合规性时钟。偏差阈值设置为 24 小时。这意味着、只有当偏差超过一天时、系统Compliance时钟才会与系统时钟同步。

SnapLock安全时钟守护进程检测到偏差并将Compliance时钟更改为系统时间。任何修改系统时间以强制Compliance时钟与系统时间同步的尝试都将失败、因为只有在系统时间与NTP时间同步时、Compliance时钟才会与系统时间同步。

.步骤
. 配置NTP服务器后、启用SnapLock合规性时钟时间同步功能：
+
`snaplock compliance-clock ntp`

+
以下命令将启用系统Compliance时钟时间同步功能：

+
[listing]
----
cluster1::*> snaplock compliance-clock ntp modify -is-sync-enabled true
----
+
有关的详细信息 `snaplock compliance-clock ntp modify`，请参见link:https://docs.netapp.com/us-en/ontap-cli/snaplock-compliance-clock-ntp-modify.html["ONTAP 命令参考"^]。

. 出现提示时，确认已配置的 NTP 服务器是可信的，并且通信通道是安全的，以启用此功能：
. 检查是否已启用此功能：
+
`snaplock compliance-clock ntp show`

+
以下命令将检查是否已启用系统Compliance时钟时间同步功能：

+
[listing]
----
cluster1::*> snaplock compliance-clock ntp show

Enable clock sync to NTP system time: true
----
+
有关的详细信息 `snaplock compliance-clock ntp show`，请参见link:https://docs.netapp.com/us-en/ontap-cli/snaplock-compliance-clock-ntp-show.html["ONTAP 命令参考"^]。


