---
permalink: snaplock/move-snaplock-volume-concept.html 
sidebar: sidebar 
keywords: move, snaplock, volume, aggregate, security, role, enterprise, compliance, create, administrator, support, user, cluster, destination, command 
summary: 从 ONTAP 9.8 开始，您可以将 SnapLock 卷移动到类型相同的目标聚合，可以是企业到企业，也可以是合规性。要移动 SnapLock 卷，必须为您分配 SnapLock 安全角色。 
---
= 移动 SnapLock 卷
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
从 ONTAP 9.8 开始，您可以将 SnapLock 卷移动到类型相同的目标聚合，可以是企业到企业，也可以是合规性。要移动 SnapLock 卷，必须为您分配 SnapLock 安全角色。



== 创建 SnapLock 安全管理员帐户

要执行 SnapLock 卷移动，您必须具有 SnapLock 安全管理员权限。此特权是通过 SnapLock ONTAP 9.8 中引入的 _SRA_ 角色授予给您的。如果尚未分配此角色，您可以要求集群管理员创建具有此 SnapLock 安全角色的 SnapLock 安全用户。

.开始之前
* 您必须是集群管理员才能执行此任务。
* 您必须已通过安全连接（ SSH ，控制台或 ZAPI ）登录。


.关于此任务
SnapLock 角色与管理 SVM 关联，而 vsadmin-SnapLock 角色则与数据 SVM 关联。

.步骤
. 创建具有 SnapLock 管理员角色的 SVM 管理员帐户：
+
`*security login create -vserver _SVM_name_ -user-or-group-name _user_or_group_name_ -application _application_ -authmethod _authentication_method_ -role _role_ -comment _comment_*`

+
以下命令将启用SVM管理员帐户 `SnapLockAdmin` 和预定义的 `snaplock` 用于访问管理SVM的角色 `cluster1` 使用密码：

+
[listing]
----
cluster1::> security login create -vserver cluster1 -user-or-group-name SnapLockAdmin -application ssh -authmethod password -role snaplock
----




== 移动 SnapLock 卷

您可以使用 `volume move` 命令将SnapLock卷移动到目标聚合。

.开始之前
* 在执行 SnapLock 卷移动之前，您必须已创建受 SnapLock 保护的审核日志。
+
link:create-audit-log-task.html["创建审核日志"]。

* 如果您使用的 ONTAP 版本早于 ONTAP 9.10.1 ，则目标聚合必须与要移动的 SnapLock 卷具有相同的 SnapLock 类型；可以是合规性，也可以是企业到企业。从 ONTAP 9.10.1 开始，此限制将被删除，聚合可以同时包含 Compliance 卷和 Enterprise SnapLock 卷以及非 SnapLock 卷。
* 您必须是具有 SnapLock 安全角色的用户。


.步骤
. 使用安全连接登录到 ONTAP 集群管理 LIF ：
+
`*ssh snaplock_user@cluster_mgmt_ip*`

. 移动 SnapLock 卷：
+
`*volume move start -vserver _SVM_name_ -volume _SnapLock_volume_name_ -destination-aggregate _destination_aggregate_name_*`

. 检查卷移动操作的状态：
+
`*volume move show -volume _SnapLock_volume_name_ -vserver _SVM_name_ -fields volume,phase,vserver*`


