---
permalink: nfs-trunking/index.html 
sidebar: sidebar 
keywords: NFSv4.1, trunking, Linux, VMware, FlexGroup, volumes, multipathing, AI/ML, rdma, data lake 
summary: 从ONTAP 9.14.1开始、运行v4.1或更高版本的NFS客户端可以利用会话中继功能打开与NFS服务器的多个连接、从而提高数据传输速度并通过多路径提供故障恢复能力 
---
= NFS中继概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
从ONTAP 9.14.1开始、NFSv4.1客户端可以利用会话中继打开与NFS服务器上不同的LUN的多个连接、从而提高数据传输速度并通过多路径提供故障恢复能力。

对于将FlexVol卷导出到具有中继功能的客户端(尤其是VMware和Linux客户端)、或者对于基于RDMA、TCP或pNFS的NFS、中继非常有用。

在ONTAP 9.14.1中、中继仅限于单个节点上的LUN；中继不能跨多个节点的LUN。

中继支持FlexGroup卷。虽然这样可以提高性能、但只能在单个节点上配置对FlexGroup卷的多路径访问。

此版本中的多路径仅支持会话中继。



== 如何使用中继

要利用中继提供的多路径优势、您需要一组与包含已启用中继的NFS服务器的SVM关联的LF (称为_TRUNKING group_)。中继组中的LUN必须在集群的同一节点上具有主端口、并且它们必须驻留在这些主端口上。最佳实践是、一个中继组中的所有LUN都属于同一个故障转移组。

ONTAP支持从给定客户端为每个节点建立多达16个中继连接。

当客户端挂载启用了中继的服务器中的导出时、它们会为中继组中的LID指定多个IP地址。客户端连接到第一个LIF后、只有在符合中继组要求的情况下、才会向NFSv4.1会话添加其他LIF并将其用于中继。然后、客户端会根据自己的算法(例如轮循)在多个连接上分布NFS操作。

为了获得最佳性能、您应在专用于提供多路径导出的SVM中配置中继、而不是单路径导出。也就是说、您只能在SVM中的NFS服务器上启用中继、而此SVM的导出仅提供给已启用中继的客户端。



== 支持的客户端

ONTAP NFSv4.1服务器支持与任何支持NFSv4.1会话中继的客户端进行中继。

以下客户端已通过ONTAP 9.14.1的测试：

* VMware—ESXi 7.0U3及更高版本
* Linux—Red Hat Enterprise Linux (RHEL) 8.8和9.3



NOTE: 在NFS服务器上启用中继后、在不支持中继的NFS客户端上访问导出共享的用户可能会看到性能下降。这是因为多个SVM数据SVM挂载只使用一个TCP连接。



== NFS中继与nconnect之间的区别

从 ONTAP 9.8 开始，如果启用了 NFSv4.1 ，则默认情况下可以使用 nconnect 功能。在支持nconnect的客户端上、一个NFS挂载可以通过一个LIF建立多个TCP连接(最多16个)。

相比之下、中继是_multiPathing_功能、可通过多个LIFs提供多个TCP连接。如果您能够在环境中使用其他NIC、则中继可以提供比nconnect更出色的并行处理能力和性能。

了解更多信息 link:../nfs-admin/ontap-support-nfsv41-concept.html["n连接。"]
