---
permalink: nfs-trunking/prepare-network-task.html 
sidebar: sidebar 
keywords: NFS, servers, network, prepare, NFS trunking, LIF, trunking group, NIC 
summary: 要利用NFSv4.1中继、中继组中的LUN必须位于同一节点上、并且主端口位于同一节点上。 
---
= 为ONTAP NFS中继准备网络
:allow-uri-read: 


[role="lead"]
要利用NFSv4.1中继、中继组中的LUN必须位于同一节点上、并且主端口位于同一节点上。应在同一节点上的故障转移组中配置这些LUN。

.关于此任务
LIS和NIC的一对一映射可获得最大的性能提升、但不需要启用中继。至少安装两个NIC可以提高性能、但这并不是必需的。

中继组中的所有LUN都应属于同一个故障转移组。请注意、如果在同一节点上的故障转移组中配置了这些LUN、则该节点上的控制器故障转移可能会导致这些LUN脱机。如果未在同一节点上的故障转移组中配置这些LUN并故障转移到另一节点、则中继将不再起作用。

在故障转移组中添加或删除连接(和底层NIC)时、您应随时调整中继故障转移组。

.开始之前
* 要创建故障转移组、您必须知道与NIC关联的端口名称。
* 这些端口必须都位于同一节点上。


.步骤
. 验证您计划使用的网络端口的名称和状态：
+
[source, cli]
----
network port show
----
. 创建故障转移组：
+
`network interface failover-groups create -vserver <svm_name> -failover-group <failover_group_name> -targets <ports_list>`

+

NOTE: 虽然不要求具有故障转移组、但强烈建议这样做。

+
** `<svm_name>`是包含NFS服务器的SVM的名称。
** `<ports_list>`是要添加到故障转移组的端口列表。
+
以格式添加端口 `<node_name>:<port_number>`，例如： `node1:e0c`。

+
以下命令将为SVM VS1创建故障转移组fg3并添加三个端口：

+
`network interface failover-groups create -vserver vs1 -failover-group fg3 -targets cluster1-01:e0c,cluster1-01:e0d,cluster1-01:e0e`

+
了解更多信息 link:../networking/configure_failover_groups_and_policies_for_lifs_overview.html["故障转移组。"]

+
有关的详细信息 `network interface failover-groups create`，请参见link:https://docs.netapp.com/us-en/ontap-cli/network-interface-failover-groups-create.html["ONTAP 命令参考"^]。



. 如果需要、为中继组的成员创建LUN：
+
`network interface create -vserver <svm_name> -lif <lif_name> -home-node <node_name> -home-port <port_name> -address <IP_address> -netmask <IP_address> [-service-policy <policy>] [-auto-revert <true|false>]`

+
** `-home-node` -在对LIF运行network interface还原命令时、LIF返回到的节点。
+
您还可以使用指定LIF是否应自动还原到主节点和主端口 `-auto-revert` 选项

** `-home-port` 是对LIF运行network interface还原命令时LIF返回到的物理或逻辑端口。
** 您可以使用指定IP地址 `-address` 和 `-netmask` 选项、而不是使用 `-subnet` 选项
** 分配IP地址时、如果不同IP子网上有客户端或域控制器、则可能需要配置网关的默认路由。有关在SVM中创建静态路由的详细信息 `network route create`，请参见link:https://docs.netapp.com/us-en/ontap-cli/network-route-create.html["ONTAP 命令参考"^]。
** `-service-policy` - LIF的服务策略。如果未指定策略、则会自动分配默认策略。使用 `network interface service-policy show` 命令以查看可用的服务策略。
** `-auto-revert` 指定在启动、更改管理数据库状态或建立网络连接等情况下、数据LIF是否自动还原到其主节点。默认设置为false、但您可以根据环境中的网络管理策略将其设置为true。
+
对中继组中的每个LIF重复此步骤。

+
以下命令将创建 `lif-A` 对于SVM `vs1`，在端口上 `e0c` 节点的 `cluster1_01`：

+
`network interface create -vserver vs1 -lif lif-A -service-policy default-intercluster -home-node cluster1_01 -home-port e0c -address 192.0.2.0`

+
了解更多信息 link:../networking/create_lifs.html["创建LIF。"]



. 验证是否已创建这些生命周期：
+
[source, cli]
----
network interface show
----
. 验证配置的IP地址是否可访问：
+
[cols="25,75"]
|===
| 要验证 ... | 使用 ... 


| IPv4 地址 | `network ping` 


| IPv6地址 | `network ping6` 
|===


.相关信息
* link:https://docs.netapp.com/us-en/ontap-cli/network-ping.html["网络 ping"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+interface["网络接口"^]
* link:https://docs.netapp.com/us-en/ontap-cli/network-port-show.html["network port show"^]

