---
permalink: cloud/fabricpool-concept.html 
sidebar: sidebar 
keywords: netapp storage grid, fabricpool 
summary: 许多 NetApp 客户都存储了大量很少访问的数据。我们称之为冷数据。客户还可以经常访问数据，我们将这些数据称为热数据。理想情况下，您希望将热数据保存在速度最快的存储上，以获得最佳性能。只要冷数据在需要时立即可用，它就可以移至速度较慢的存储。但是，您如何知道数据中哪些部分是热的，哪些部分是冷的？ 
---
= FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
许多 NetApp 客户都存储了大量很少访问的数据。我们称之为 _cold_ 数据。客户还可以经常访问数据，我们将这些数据称为 _hot_ data 。理想情况下，您希望将热数据保存在速度最快的存储上，以获得最佳性能。只要冷数据在需要时立即可用，它就可以移至速度较慢的存储。但是，您如何知道数据中哪些部分是热的，哪些部分是冷的？

FabricPool 是一项 ONTAP 功能，可根据访问模式在高性能本地层（聚合）和云层之间自动移动数据。分层可将昂贵的本地存储释放出来用于存储热数据，同时使冷数据随时可从云中的低成本对象存储中访问。FabricPool 会持续监控数据访问并在层之间移动数据，以获得最佳性能并最大程度地节省空间。

使用 FabricPool 将冷数据分层到云是提高云效率和创建混合云配置的最简单方法之一。FabricPool 可在存储块级别运行，因此可同时处理文件和 LUN 数据。

但是， FabricPool 不仅仅是将内部数据分层到云。许多客户使用 Cloud Volumes ONTAP 中的 FabricPool 将冷数据从昂贵的云存储分层到云提供商中成本较低的对象存储。从 ONTAP 9.8 开始，您可以使用捕获启用了 FabricPool 的卷上的分析 link:../concept_nas_file_system_analytics_overview.html["文件系统分析"] 或 link:../volumes/enable-temperature-sensitive-efficiency-concept.html["对温度敏感的存储效率"]。

使用数据的应用程序不知道数据是分层的，因此不需要对应用程序进行更改。分层是完全自动的，因此无需持续管理。

您可以将冷数据存储在主要云提供商之一的对象存储中。或者，选择 NetApp StorageGRID 将冷数据保存在您自己的私有云中，以获得最高性能并全面控制您的数据。

https://docs.netapp.com/us-en/ontap/concept_cloud_overview.html["FabricPool 系统管理器文档"]

https://cloud.netapp.com/cloud-tiering["云分层服务"]

https://www.youtube.com/playlist?list=PLdXI3bZJEw7mcD3RnEcdqZckqKkttoUpS["NetApp TechComm TV 上的 FabricPool 播放列表"]
