---
permalink: flexcache/create-volume-task.html 
sidebar: sidebar 
keywords: creating, flexcache, volume, flex cache, performance, remote cluster, data access, tls encryption, peer permission, 
summary: 您可以在同一集群中创建 FlexCache 卷，以提高访问热对象时的性能。如果数据中心位于不同位置，则可以在远程集群上创建 FlexCache 卷，以加快数据访问速度。 
---
= 创建 FlexCache 卷
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在同一集群中创建 FlexCache 卷，以提高访问热对象时的性能。如果数据中心位于不同位置，则可以在远程集群上创建 FlexCache 卷，以加快数据访问速度。

FlexCache 卷始终是 FlexGroup 卷，而不是 FlexVol 卷。

从 ONTAP 9.7 开始， FlexGroup 卷在 FlexCache 关系的初始位置也受支持。

.步骤
. 如果要创建的 FlexCache 卷位于其他集群中，请创建集群对等关系：
+
.. 在目标集群上，创建与数据保护源集群的对等关系： + `cluster peer create -generate-passphrase -offer-expiration MM/DD/YYYY HH ： MM ： SS|1...7days|1...168 小时 -peer-addrs peer_LIF_ips -initial-allowed-vserver-peers SVM_name ， ..._IPSpace`
+
从 ONTAP 9.6 开始，默认情况下，在创建集群对等关系时会启用 TLS 加密。支持使用 TLS 加密在初始卷和 FlexCache 卷之间进行集群间通信。如果需要，您还可以为集群对等关系禁用 TLS 加密。

+
[listing]
----
cluster02::> cluster peer create -generate-passphrase -offer-expiration 2days -initial-allowed-vserver-peers *

                     Passphrase: UCa+6lRVICXeL/gq1WrK7ShR
                Expiration Time: 6/7/2017 08:16:10 EST
  Initial Allowed Vserver Peers: *
            Intercluster LIF IP: 192.140.112.101
              Peer Cluster Name: Clus_7ShR (temporary generated)

Warning: make a note of the passphrase - it cannot be displayed again.
----
.. 在源集群上，向目标集群验证源集群的身份： + `cluster peer create -peer-addrs peer_LIF_ips -ipspace ipspace`
+
[listing]
----
cluster01::> cluster peer create -peer-addrs 192.140.112.101,192.140.112.102

Notice: Use a generated passphrase or choose a passphrase of 8 or more characters.
        To ensure the authenticity of the peering relationship, use a phrase or sequence of characters that would be hard to guess.

Enter the passphrase:
Confirm the passphrase:

Clusters cluster02 and cluster01 are peered.
----


. 如果 FlexCache 卷与原始卷位于不同的 SVM 中，请使用 `FlexCache` 作为应用程序创建 SVM 对等关系：
+
.. 如果 SVM 位于其他集群中，请为对等 SVM 创建 SVM 权限： + `vserver peer permission create -peer-cluster cluster_name -vserver SVM-name -applications FlexCache`
+
以下示例说明了如何创建适用于所有本地 SVM 的 SVM 对等权限：

+
[listing]
----
cluster1::> vserver peer permission create -peer-cluster cluster2 -vserver "*" -applications flexcache

Warning: This Vserver peer permission applies to all local Vservers. After that no explict
"vserver peer accept" command required for Vserver peer relationship creation request
from peer cluster "cluster2" with any of the local Vservers. Do you want to continue? {y|n}: y
----
.. 创建 SVM 对等关系： + `vserver peer create -vserver local_sVM -peer-vserver remote_sVM -peer cluster cluster_name -applications FlexCache`


. 创建 FlexCache 卷：
+
`volume FlexCache create -vserver cache_svm -volume cache_vol_name -auto-provision-as FlexGroup -size vol_size -original-vserver original_svm -original-volume origin_vol_name`

+
以下示例将创建一个 FlexCache 卷并自动选择要配置的现有聚合：

+
[listing]
----
cluster1::> volume flexcache create -vserver vs_1 -volume fc1 -auto-provision-as flexgroup -origin-volume vol_1 -size 160MB -origin-vserver vs_1
[Job 443] Job succeeded: Successful
----
+
以下示例将创建一个 FlexCache 卷并设置接合路径：

+
[listing]
----
cluster1::> flexcache create -vserver vs34 -volume fc4 -aggr-list aggr34,aggr43 -origin-volume origin1 -size 400m -junction-path /fc4
[Job 903] Job succeeded: Successful
----
. 验证 FlexCache 卷和原始卷的 FlexCache 关系。
+
.. 查看集群中的 FlexCache 关系： + `volume FlexCache show`
+
[listing]
----
cluster1::> volume flexcache show
Vserver Volume      Size       Origin-Vserver Origin-Volume Origin-Cluster
------- ----------- ---------- -------------- ------------- --------------
vs_1    fc1         160MB      vs_1           vol_1           cluster1
----
.. 查看原始集群中的所有 FlexCache 关系： + `volume FlexCache origin show-Cache`
+
[listing]
----
cluster::> volume flexcache origin show-caches
Origin-Vserver Origin-Volume   Cache-Vserver    Cache-Volume   Cache-Cluster
-------------- --------------- ---------------  -------------- ---------------
vs0            ovol1           vs1              cfg1           clusA
vs0            ovol1           vs2              cfg2           clusB
vs_1           vol_1           vs_1             fc1            cluster1
----






== 结果

已成功创建 FlexCache 卷。客户端可以使用 FlexCache 卷的接合路径挂载卷。

link:../peering/index.html["集群和 SVM 对等"]

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9 命令"]
