---
permalink: flexcache/enable-file-access-time-updates-task.html 
sidebar: sidebar 
keywords: atime, atime-update, flexcache, flex cache, access time 
summary: '您可以启用 `-atime-update` 字段FlexCache、以允许更新文件访问时间。您还可以使用设置访问时间更新期限 `-atime-update-period` 属性。atime-update-period用于控制发生atime更新的频率以及何时可以将这些更新传播到原始卷。' 
---
= 在ONTAP FlexCache卷上启用文件访问时间更新
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
从ONTAP 9.11.1开始、您可以启用 `-atime-update` 字段FlexCache、以允许更新文件访问时间。您还可以使用设置访问时间更新期限 `-atime-update-period` 属性。。 `-atime-update-period` 属性控制访问时间更新的频率以及更新传播到初始卷的时间。



== 概述

ONTAP提供了一个名为的卷级字段 `-atime-update`，管理使用Read、readlink和READDIR读取的文件和目录的访问时间更新。atime用于为不常访问的文件和目录制定数据生命周期决策。不常访问的文件最终会迁移到归档存储、并且以后通常会移动到磁带。

默认情况下、现有和新创建的FlexCache 卷上的atime-update字段处于禁用状态。如果您将FlexCache卷与9.11.1之前的ONTAP版本结合使用、则应禁用"ATI-UPDATe"字段、以便在对初始卷执行读取操作时不会不必要地逐出缓存。但是、对于大型FlexCache 缓存、管理员会使用专用工具来管理数据、并帮助确保热数据保留在缓存中、冷数据也会被清除。禁用atime-update时无法执行此操作。但是、从ONTAP 9.11.1开始、您可以启用 `-atime-update`和 `-atime-update-period,`、并使用管理缓存数据所需的工具。



== 开始之前

* 所有FlexCache 卷都必须运行ONTAP 9.11.1或更高版本。
* 您必须使用 `advanced`权限模式。




== 关于此任务

正在设置 ... `-atime-update-period` 到86400秒后、无论对文件执行的类似读取操作数如何、每个24小时时间段的访问时间更新都不超过一次。

设置 `-atime-update-period` 设置为0时、会针对每个读取访问向源站发送消息。然后、原始卷会通知每个FlexCache 卷、atime已过时、这会影响性能。

.步骤
. 将权限模式设置为 `advanced`：
+
`set -privilege advanced`

. 启用文件访问时间更新并设置更新频率：
+
`volume modify -volume vol_name -vserver <SVM name> -atime-update true -atime-update-period <seconds>`

+
以下示例将启用 `-atime-update` 和设置 `-atime-update-period` 至86400秒或24小时：

+
[listing]
----
c1: volume modify -volume origin1 vs1_c1 -atime-update true -atime-update-period 86400
----
. 请验证 `-atime-update` 已启用：
+
`volume show -volume _vol_name_ -fields atime-update,atime-update-period`

+
[listing]
----
c1::*> volume show -volume cache1_origin1 -fields atime-update,atime-update-period
vserver volume         atime-update atime-update-period
------- -------------- ------------ -------------------
vs2_c1  cache1_origin1 true         86400
----
. 启用后 `-atime-update`、您可以指定是否可以自动擦除FlexCache卷上的文件以及擦洗间隔：
+
`volume flexcache config modify -vserver <SVM name> -volume <volume_name> -is-atime-scrub-enabled <true|false> -atime-scrub-period <integer>`



有关参数的详细信息 `-is-atime-scrub-enabled`，请参见link:https://docs.netapp.com/us-en/ontap-cli/volume-flexcache-config-modify.html#parameters["ONTAP 命令参考"^]。
