---
permalink: flexcache/typical-deployments-concept.html 
sidebar: sidebar 
keywords: typical, flexcache, deployments, performance, acceleration, hot volumes, cross-cluster, data, distribution 
summary: 'FlexCache 卷通常用于读取密集型工作负载。您可以在同一集群中使用 FlexCache 卷来提高经常访问的数据或 " 热对象 " 的性能。您还可以使用 FlexCache 卷在多个集群之间分布数据，以减少 WAN 延迟。' 
---
= 典型的 FlexCache 部署
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexCache 卷通常用于读取密集型工作负载。您可以在同一集群中使用 FlexCache 卷来提高经常访问的数据或 "`热对象` " 的性能。您还可以使用 FlexCache 卷在多个集群之间分布数据，以减少 WAN 延迟。

您可以在 AFF ， FAS 或 ONTAP Select 系统上部署 FlexCache 。从 ONTAP 9.6 开始， Cloud Volumes ONTAP 还支持 FlexCache 部署。



== 提高热卷的性能

在 LAN 部署中， FlexCache 卷与原始集群位于同一集群中。FlexCache 卷可以位于与原始卷相同的 SVM 中，也可以位于与原始卷不同的 SVM 中。

FlexCache 卷用于处理 CPU 密集型工作负载，以便从繁忙的文件服务器卸载工作负载并释放系统资源。您可以使用与不同 FlexCache 卷对应的多个挂载点来减少网络延迟，因为数据访问负载在所有缓存系统之间共享。这种类型的 LAN 部署可减少过载存储系统的工作负载。



== 跨集群数据分布

在 WAN 部署中， FlexCache 卷与数据中心处于远程位置，并且与原始卷位于不同的集群中。当客户端请求数据时， FlexCache 卷会缓存常见数据，从而使最终用户能够更快地访问信息。这种类型的 WAN 部署可减少远程客户端的平均访问时间。

FlexCache 卷将尽可能靠近远程办公室。然后，客户端请求会显式定向到 FlexCache 卷。如果缓存中存在有效数据，则这些数据将直接提供给客户端。如果数据不在缓存中，则会从原始系统通过 WAN 检索数据，并将其缓存在 FlexCache 卷中，然后将其提供给客户端。
