---
permalink: volumes/change-maximum-number-files-allowed-concept.html 
sidebar: sidebar 
keywords: considerations, changing, maximum number of files, allowed, flexvol volume 
summary: FlexVol 卷可以包含的文件数量上限。您可以更改卷的最大文件数，但在更改之前，您应了解此更改对卷的影响。 
---
= 更改 FlexVol 卷上允许的最大文件数的注意事项
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexVol 卷可以包含的文件数量上限。您可以更改卷的最大文件数，但在更改之前，您应了解此更改对卷的影响。

如果数据需要大量文件或非常大的目录，则可以扩展 ONTAP 文件或目录容量。但是，在继续操作之前，您应了解此操作的限制和注意事项。

卷可以包含的文件数取决于其包含的索引节点数。_inode_ 是一种数据结构，其中包含有关文件的信息。卷同时具有专用索引节点和公有索引节点。公有索引节点用于用户可见的文件；专用索引节点用于 ONTAP 内部使用的文件。您只能更改卷的最大公有索引节点数。您不能影响专用索引节点的数量。

ONTAP 会根据卷大小自动为新创建的卷设置最大公有索引节点数：每 32 KB 卷大小 1 个索引节点。当卷大小增加时，无论是直接由管理员增加还是由 ONTAP 通过自动调整大小功能自动增加， ONTAP 也会根据需要增加最大公有索引节点数，以便每 32 KB 卷大小至少有 1 个索引节点。 直到卷大小达到大约 680 GB 为止。

在9.13.1之前的ONTAP版本中、将卷大小增长到680 GB以上不会自动生成更多的节点、因为ONTAP不会自动创建超过22、369、621个的节点。如果所需的文件数超过任何大小的卷的默认数量，则可以使用 volume modify 命令增加卷的最大索引节点数。

从ONTAP 9.13.1开始、最大节点数将继续增长、因此、即使卷大于680 GB、每32 KB卷空间也有一个节点。这种增长会持续、直到卷达到最大节点2、147、483、332为止。

您还可以减少公有索引节点的最大数量。减少公共索引节点数不会更改分配给索引节点的空间量、但会降低公共索引节点文件可以占用的最大空间量。为各个iNode分配了空间后、该空间永远不会返回到卷中。因此、将最大节点数降至当前分配的节点数以下不会返回已分配的节点所使用的空间。

.更多信息
* xref:display-file-inode-usage-task.html[显示文件或索引节点使用情况]

