---
permalink: volumes/change-maximum-number-files-allowed-concept.html 
sidebar: sidebar 
keywords: considerations, changing, maximum number of files, allowed, flexvol volume, maximum, files, file 
summary: FlexVol 卷可以包含的文件数量上限。您可以更改此最大值、但请注意这会对卷产生何种影响。 
---
= ONTAP中FlexVol卷允许的默认文件数和最大文件数
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexVol卷具有其可以包含的默认文件数和最大文件数。如果您的数据需要大量文件，您可以将卷上允许的用户可见文件的数量增加到最大值。在继续之前您应该了解限制和注意事项。

卷可以包含的用户可见文件的数量由该卷的可用 inode 容量决定。  inode 是一种包含有关文件信息的数据结构。

ONTAP会根据新创建的卷的大小自动设置其默认和最大可用 inode 数，如下所示。

[cols="2,2"]
|===
| 默认 inode 数量 | 最大 inode 数量 


| 每 32 KB 卷大小 1 个 | 每 4 KB 卷大小 1 个 
|===
当卷的大小增加时（无论是由管理员手动增加还是由 ONTAP 的自动调整大小功能自动增加）， ONTAP还会增加（如有必要）可用的 inode 数量，以便每 32 KB 卷大小至少有 1 个 inode，直到卷大小达到约 680 GB。

在ONTAP 9.12.1 及更早版本中，创建新卷或调整现有卷的大小（大于 680 GB）不会自动产生额外的 inode 容量。如果您需要的文件数量超过任何大小卷的默认数量，则可以使用 `volume modify`命令将卷的可用 inode 数量增加到最大值。

从ONTAP 9.13.1 开始，创建新卷或调整现有卷的大小时，即使卷大于 680 GB，可用 inode 的默认数量也会设置为每 32 KB 卷空间 1 个 inode。此比率将持续存在，直到卷达到绝对 inode 最大值 2,040,109,451。

您还可以减少可用的 inode 数量。这不会改变分配给 inode 的空间量，但会降低公共 inode 文件可以消耗的最大空间量。为 inode 分配空间后，该空间将永远不会返回到卷。因此，不可能将最大 inode 数量降低到低于当前分配的 inode 数量。

.更多信息
* xref:display-file-inode-usage-task.html[确定卷的文件和索引节点使用情况]
* link:++https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/FAQ_-_ONTAP_default_and_maximum_number_of_files_(inodes)++["NetApp知识库：常见问题解答 - ONTAP默认和最大文件数（inode）"^]

