---
permalink: volumes/commands-manage-quota-rules-policies-reference.html 
sidebar: sidebar 
keywords: commands to, manage, quota rules, quota policies, command, commands, quota, quotas, policy, policies 
summary: ' `volume quota policy rule`命令用于配置配额规则、 `volume quota policy`命令和某些 `vserver`命令用于配置配额策略。' 
---
= 用于管理配额规则和配额策略的命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
 `volume quota policy rule`命令用于配置配额规则、 `volume quota policy`命令和某些 `vserver`命令用于配置配额策略。根据您需要执行的操作、使用以下命令管理配额规则和配额策略：


NOTE: 以下命令只能在 FlexVol 卷上运行。



== 用于管理配额规则的命令

[cols="2*"]
|===
| 如果您要 ... | 使用此命令 ... 


 a| 
创建新的配额规则
 a| 
`volume quota policy rule create`



 a| 
删除现有配额规则
 a| 
`volume quota policy rule delete`



 a| 
修改现有配额规则
 a| 
`volume quota policy rule modify`



 a| 
显示有关已配置配额规则的信息
 a| 
`volume quota policy rule show`

|===


== 用于管理配额策略的命令

[cols="2*"]
|===
| 如果您要 ... | 使用此命令 ... 


 a| 
复制配额策略及其包含的配额规则
 a| 
`volume quota policy copy`



 a| 
创建新的空配额策略
 a| 
`volume quota policy create`



 a| 
删除当前未分配给 Storage Virtual Machine （ SVM ）的现有配额策略
 a| 
`volume quota policy delete`



 a| 
重命名配额策略
 a| 
`volume quota policy rename`



 a| 
显示有关配额策略的信息
 a| 
`volume quota policy show`



 a| 
将配额策略分配给SVM
 a| 
`vserver modify -quota-policy _policy_name_`



 a| 
显示分配给SVM的配额策略的名称
 a| 
`vserver show`

|===
请参见 link:https://docs.netapp.com/us-en/ontap-cli["ONTAP 命令参考"^] 有关详细信息、请参见每个命令。
