---
permalink: volumes/commands-display-quotas-reference.html 
sidebar: sidebar 
keywords: commands for, display, displaying, information about, quotas 
summary: 您可以使用命令显示包含强制实施的配额和资源使用情况的配额报告，显示有关配额状态和错误或配额策略和配额规则的信息。 
---
= 用于显示有关配额信息的 ONTAP 命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用命令显示包含强制实施的配额和资源使用情况的配额报告，显示有关配额状态和错误或配额策略和配额规则的信息。

以下命令只能在 FlexVol 卷上运行。

[cols="2*"]
|===
| 如果您要 ... | 使用此命令 ... 


 a| 
查看有关强制实施的配额的信息
 a| 
`volume quota report`



 a| 
查看配额目标的资源使用情况（磁盘空间和文件数）
 a| 
`volume quota report`



 a| 
确定允许写入文件时受影响的配额限制
 a| 
`volume quota report` 使用 `-path` 参数



 a| 
显示配额状态、例如 `on`， `off`，和 `initializing`
 a| 
`volume quota show`



 a| 
查看有关配额消息日志记录的信息
 a| 
`volume quota show` 使用 `-logmsg` 参数



 a| 
查看配额初始化和调整大小期间发生的错误
 a| 
`volume quota show` 使用 `-instance` 参数



 a| 
查看有关配额策略的信息
 a| 
`volume quota policy show`



 a| 
查看有关配额规则的信息
 a| 
`volume quota policy rule show`



 a| 
查看分配给 Storage Virtual Machine （ SVM ，以前称为 Vserver ）的配额策略的名称
 a| 
`vserver show` 使用 `-instance` 参数

|===
有关的详细信息 `volume quota`，请参见link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=volume+quota["ONTAP 命令参考"^]。



== 何时使用 ONTAP volume quota policy rule show 和 volume quota report 命令

虽然这两个命令都显示有关配额的信息、但 `volume quota policy rule show` 在中快速显示已配置的配额规则 `volume quota report` 命令会占用更多的时间和资源、它会显示强制实施的配额和资源使用情况。

。 `volume quota policy rule show` 命令可用于以下用途：

* 激活配额规则之前，请先检查其配置
+
无论配额是否已初始化或调整大小，此命令都会显示所有已配置的配额规则。

* 在不影响系统资源的情况下快速查看配额规则
+
由于此命令不会显示磁盘和文件使用量，因此不像配额报告那样占用大量资源。

* 显示未分配给 SVM 的配额策略中的配额规则。


有关的详细信息 `volume quota policy rule show`，请参见link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-policy-rule-show.html["ONTAP 命令参考"^]。

。 `volume quota report` 命令可用于以下用途：

* 查看强制实施的配额，包括派生配额
* 查看每个有效配额使用的磁盘空间和文件数，包括受派生配额影响的目标
+
（对于默认配额，使用量显示为 "0" ，因为使用量是根据生成的派生配额进行跟踪的。）

* 确定哪些配额限制会影响何时允许写入文件
+
添加 `-path` 参数 `volume quota report` 命令：



[NOTE]
====
配额报告是一种资源密集型操作。如果在集群中的许多 FlexVol 卷上运行此命令，可能需要很长时间才能完成。更高效的方法是查看 SVM 中特定卷的配额报告。

====
有关的详细信息 `volume quota report`，请参见link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-report.html["ONTAP 命令参考"^]。
