---
permalink: volumes/configure-volume-provision-options-task.html 
sidebar: sidebar 
keywords: configure, volume, provisioning, options 
summary: 您可以为卷配置精简配置，厚配置或半厚配置。 
---
= 配置卷配置选项
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以为卷配置精简配置，厚配置或半厚配置。

.关于此任务
设置 `-space-slo` 选项 `thick` 确保满足以下要求：

* 整个卷会在聚合中预先分配。您不能使用 `volume create` 或 `volume modify` 命令以配置卷的 `-space-guarantee` 选项
* 覆盖所需空间的 100% 为预留空间。您不能使用 `volume modify` 命令以配置卷的 `-fractional-reserve` 选项


设置 `-space-slo` 选项 `semi-thick` 确保满足以下要求：

* 整个卷会在聚合中预先分配。您不能使用 `volume create` 或 `volume modify` 命令以配置卷的 `-space-guarantee` 选项
* 不会为覆盖预留任何空间。您可以使用 `volume modify` 命令以配置卷的 `-fractional-reserve` 选项
* 已启用 Snapshot 副本自动删除。


.步骤
. 配置卷配置选项：
+
`volume create -vserver _vserver_name_ -volume _volume_name_ -aggregate _aggregate_name_ -space-slo none|thick|semi-thick -space-guarantee none|volume`

+
。 `-space-guarantee` 选项默认为 `none` 适用于AFF系统和非AFDP卷。否则、默认为 `volume`。对于现有FlexVol卷、请使用 `volume modify` 命令以配置配置选项。

+
以下命令将在 SVM vs1 上配置 vol1 以进行精简配置：

+
[listing]
----
cluster1::> volume create –vserver vs1 -volume vol1 -space-guarantee none
----
+
以下命令将在 SVM vs1 上配置 vol1 以进行厚配置：

+
[listing]
----
cluster1::> volume create –vserver vs1 -volume vol1 -space-slo thick
----
+
以下命令将在 SVM vs1 上配置 vol1 以进行半厚配置：

+
[listing]
----
cluster1::> volume create –vserver vs1 -volume vol1 -space-slo semi-thick
----

