---
permalink: volumes/control-io-performance-qos-task.html 
sidebar: sidebar 
keywords: control, monitor, i/o performance, flexvol volumes, using storage qos, qos, performance, throttle, flexvol, policy, policy group 
summary: '您可以使用存储服务质量(QoS)策略组来管理工作负载、从而控制FlexVol卷的I/O性能。' 
---
= 利用存储服务质量(QoS)控制和监控FlexVol volume I/O性能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以通过将卷分配给存储服务质量策略组来控制 FlexVol 卷的输入 / 输出（ I/O ）性能。您可以控制 I/O 性能，以确保工作负载实现特定的性能目标，或者限制对其他工作负载产生负面影响的工作负载。

.关于此任务
策略组强制执行最大吞吐量限制（例如，100 MB/s）。您可以在不指定最大吞吐量的情况下创建策略组，这使您可以在控制工作负载之前监视性能。您还可以指定可选的最低吞吐量限制。

您还可以将 SVM ， LUN 和文件分配给策略组。

在将卷分配给策略组时，请注意以下要求：

* 卷必须包含在策略组所属的 SVM 中。
+
您可以在创建策略组时指定 SVM 。

* 从 ONTAP 9.18.1 开始，您可以将 QoS 策略分配给具有 QoS 策略的 SVM 中包含的卷。当您使用嵌套 QoS 策略时，将应用最严格的策略。
* 从 ONTAP 9.14.0 开始，您可以将策略分配给具有 QoS 策略的卷中包含的 qtree。


有关如何使用存储 QoS 的详细信息，请参见 link:../system-admin/index.html["《系统管理参考》"]。

.步骤
. 使用 `qos policy-group create` 命令以创建策略组。
. 使用 `volume create` 命令或 `volume modify` 命令 `-qos-policy-group` 用于将卷分配给策略组的参数。
. 使用 `qos statistics` 用于查看性能数据的命令。
. 如有必要、请使用 `qos policy-group modify` 命令以调整策略组的最大吞吐量限制。


.相关信息
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=qos+policy-group["QoS策略组"^]
* 链接： https://docs.netapp.com/us-en/ontap-cli/qos-policy-group-create.html ://docs.netapp.com/us-en/ontap-cli/qos-policy-group-create.html [qos policy-group create]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-create.html["卷创建"^]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-modify.html["卷修改"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=qos+statistics["QoS统计信息"^]

