---
permalink: volumes/create-volume-task.html 
sidebar: sidebar 
keywords: create, volume 
summary: 您可以使用 volume create 命令创建卷并指定其接合点和其他属性。 
---
= 创建卷
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用创建卷并指定其接合点和其他属性 `volume create` 命令：

.关于此任务
卷必须包含 _junction path_ ，才能使其数据可供客户端使用。您可以在创建新卷时指定接合路径。如果在创建卷时未指定接合路径、则必须使用_mount_在SVM命名空间中挂载此卷 `volume mount` 命令：

.开始之前
* 新卷的 SVM 以及将为该卷提供存储的聚合必须已存在。
* 如果 SVM 包含关联聚合列表，则必须将该聚合包含在此列表中。
* 从ONTAP 9.13.1开始、您可以创建启用了容量分析和活动跟踪的卷。要启用容量或活动跟踪、请问题描述 `volume create` 命令 `-analytics-state` 或 `-activity-tracking-state` 设置为 `on`。
+
要了解有关容量分析和活动跟踪的更多信息，请参见 https://docs.netapp.com/us-en/ontap/task_nas_file_system_analytics_enable.html["启用文件系统分析"]。



.步骤
. 创建卷
+
`volume create -vserver _svm_name_ -volume _volume_name_ -aggregate _aggregate_name_ -size {integer[KB|MB|GB|TB|PB]} -security-style {ntfs|unix|mixed} -user _user_name_or_number_ -group _group_name_or_number_ -junction-path _junction_path_ [-policy _export_policy_name_]`

+
。 `-security style`， `-user`， `-group`， `-junction-path`，和 `-policy` 选项仅适用于NAS卷。

+
的选项 `-junction-path` 包括：

+
** 直接位于root下、例如、 `/new_vol`
+
您可以创建一个新卷并指定将其直接挂载到 SVM 根卷。

** 在现有目录下、例如、 `/existing_dir/new_vol`
+
您可以创建一个新卷并指定将其挂载到现有层次结构中的现有卷，以目录的形式表示。



+
例如、如果要在新目录(在新卷下的新层次结构中)中创建卷、 `/new_dir/new_vol`然后，必须先创建一个与SVM根卷连接的新父卷。然后，您将在新父卷的接合路径（新目录）中创建新的子卷。

. 验证是否已使用所需的接合点创建卷：
+
`volume show -vserver _svm_name_ -volume _volume_name_ -junction`



.示例
以下命令将在SVM上创建一个名为users1的新卷 `vs1.example.com` 和聚合 `aggr1`。新卷可通过访问 `/users`。此卷的大小为 750 GB ，其卷保证类型为 volume （默认值）。

[listing]
----
cluster1::> volume create -vserver vs1.example.com -volume users1 -aggregate aggr1 -size 750g -junction-path /users
[Job 1642] Job succeeded: Successful

cluster1::> volume show -vserver vs1.example.com -volume users1 -junction
                          Junction                 Junction
Vserver           Volume  Active   Junction Path   Path Source
----------------- ------- -------- --------------- -----------
vs1.example.com   users1  true     /users          RW_volume
----
以下命令会在 SVM"`vs1.example.com`" 和聚合 "`aggr1` " 上创建一个名为 "`home4` " 的新卷。目录 `/eng/` 已位于VS1 SVM的命名空间中、新卷可通过访问 `/eng/home`，将成为的主目录 `/eng/` 命名空间。此卷的大小为750 GB、其卷保证类型为 `volume` (默认情况下)。

[listing]
----
cluster1::> volume create -vserver vs1.example.com -volume home4 -aggregate aggr1 -size 750g -junction-path /eng/home
[Job 1642] Job succeeded: Successful

cluster1::> volume show -vserver vs1.example.com -volume home4 -junction
                         Junction                 Junction
Vserver          Volume  Active   Junction Path   Path Source
---------------- ------- -------- --------------- -----------
vs1.example.com  home4   true     /eng/home       RW_volume
----