---
permalink: volumes/create-flexclone-file-flexclone-lun-task.html 
sidebar: sidebar 
keywords: create, flexclone file, flexclone lun 
summary: 您可以使用 volume file clone create 命令为 FlexVol 卷或 FlexClone 卷中的文件和 LUN 创建节省空间和时间的克隆。 
---
= 创建 FlexClone 文件或 FlexClone LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用为FlexVol卷或FlexClone卷中的文件和LUN创建节省空间和时间的克隆 `volume file clone create` 命令：

.您需要的内容
* 集群上必须安装 FlexClone 许可证。此许可证包含在中 link:https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP One"]。
* 如果使用多个块范围进行子 LUN 克隆或子文件克隆，则块编号不能重叠。
* 如果要在启用了自适应数据压缩的卷上创建子 LUN 或子文件，则块范围不得错位。
+
这意味着源起始块编号和目标起始块编号必须均匀对齐或奇对齐。



.关于此任务
根据集群管理员分配的权限， SVM 管理员可以创建 FlexClone 文件和 FlexClone LUN 。

您可以在创建和修改克隆时为 FlexClone 文件和 FlexClone LUN 指定自动删除设置。默认情况下，自动删除设置处于禁用状态。

您可以在使用创建克隆时覆盖现有FlexClone文件或FlexClone LUN `volume file clone create` 命令 `-overwrite-destination` 参数。

当节点达到其最大分摊负载时、该节点会暂时停止接受创建FlexClone文件和FlexClone LUN的请求、并发出 `EBUSY` 错误消息。当节点的分摊负载降至最大值以下时，该节点将再次接受创建 FlexClone 文件和 FlexClone LUN 的请求。您应等待节点具有创建克隆的容量，然后再重试创建请求。

.步骤
. 使用创建FlexClone文件或FlexClone LUN `volume file clone create` 命令：
+
以下示例显示了如何为卷 vol1 中的父文件 file1_source 创建 FlexClone 文件 file1_clone ：

+
[listing]
----
cluster1::> volume file clone create -vserver vs0 -volume vol1 -source-path /file1_source -destination-path /file1_clone
----
+
有关使用此命令的详细信息，请参见手册页。



.相关信息
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9命令"^]
