---
permalink: volumes/default-quotas-concept.html 
sidebar: sidebar 
keywords: default quotas, quotas, quota, default 
summary: 您可以使用默认配额将配额应用于给定配额类型的所有实例。使用默认配额还可以轻松修改配额。 
---
= 默认配额的工作原理
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用默认配额将配额应用于给定配额类型的所有实例。例如，默认用户配额会影响系统上指定 FlexVol 卷或 qtree 的所有用户。此外，您还可以通过默认配额轻松修改配额。

您可以使用默认配额自动对一组大型配额目标应用限制，而无需为每个目标创建单独的配额。例如，如果要将大多数用户的磁盘空间限制为 10 GB ，则可以指定一个 10 GB 磁盘空间的默认用户配额，而不是为每个用户创建一个配额。如果您要对特定用户应用不同的限制，则可以为这些用户创建显式配额。（显式配额—包含特定目标或目标列表的配额—覆盖默认配额。）

此外，通过默认配额，您可以在希望配额更改生效时使用调整大小，而不是重新初始化。例如，如果向已具有默认用户配额的卷添加显式用户配额，则可以通过调整大小来激活新配额。

默认配额可以应用于所有三种类型的配额目标（用户，组和 qtree ）。

默认配额不一定具有指定的限制；默认配额可以是跟踪配额。

配额由空字符串（ "" ）或星号（ * ）的目标指示，具体取决于上下文：

* 使用创建配额时 `volume quota policy rule create` 命令、设置 `-target` 参数添加到空字符串("")将创建默认配额。
+
有关的详细信息 `volume quota policy rule create`，请参见link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-policy-rule-create.html["ONTAP 命令参考"^]。

* 在中 `volume quota policy rule create` 命令、 `-qtree` 参数用于指定配额规则应用到的qtree的名称。此参数不适用于树类型规则。对于卷级别的用户或组类型规则，此参数应包含 "" 。
* 在的输出中 `volume quota policy rule show` 命令时、系统将显示一个默认配额、其目标为空字符串("")。
+
有关的详细信息 `volume quota policy rule show`，请参见link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-policy-rule-show.html["ONTAP 命令参考"^]。

* 在的输出中 `volume quota report` 命令时、默认配额显示时带有星号(*)作为ID和配额说明符。
+
有关的详细信息 `volume quota report`，请参见link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-report.html["ONTAP 命令参考"^]。





== 默认用户配额示例

以下配额规则使用默认用户配额对vol1的每个用户应用50 MB的限制：

[listing]
----
cluster1::> volume quota policy rule create -vserver vs0 -volume vol1 -policy-name default -type user -target "" -qtree "" -disk-limit 50m

cluster1::> volume quota policy rule show -vserver vs0 -volume vol1

Vserver: vs0               Policy: default           Volume: vol1
                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
user   ""        ""      off          50MB        -       -        -          -
----
如果系统上的任何用户输入的命令会发生原因该用户的数据在 vol1 中占用超过 50 MB 的空间（例如，从编辑器写入文件），则该命令将失败。
