---
permalink: volumes/delete-snapshot-copies-automatic-task.html 
sidebar: sidebar 
keywords: delete, snapshot, copies, automatically, flexclone luns, automatic, lun, luns 
summary: 您可以定义自动删除快照和FlexClone LUN的策略、以帮助管理空间利用率。 
---
= 启用自动快照和LUN删除以管理空间
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以定义并启用自动删除快照和FlexClone LUN的策略。自动删除快照和FlexClone LUN有助于管理空间利用率。

.关于此任务
您可以自动从读写卷中删除快照、并从读写父卷中删除FlexClone LUN。您不能设置自动删除只读卷(例如SnapMirror目标卷)中的快照。

.步骤
. 使用命令定义并启用用于自动删除快照的策略 `volume snapshot autodelete modify`。
+
要了解有关和定义满足您需求的策略的更多信息 `volume snapshot autodelete modify`，请参见link:https://docs.netapp.com/us-en/ontap-cli/volume-snapshot-autodelete-modify.html["ONTAP 命令参考"^]。

+
以下命令将为vs0.example.com Storage Virtual Machine (SVM)中的vol3卷启用快照自动删除并将触发器设置为 `snap_reserve`：

+
[listing]
----
cluster1::> volume snapshot autodelete modify -vserver vs0.example.com
-volume vol3 -enabled true -trigger snap_reserve
----
+
以下命令将为vs0.example.com Storage Virtual Machine (SVM)中的vol3卷启用快照和标记为自动删除的FlexClone LUN的自动删除：

+
[listing]
----
cluster1::> volume snapshot autodelete modify -vserver vs0.example.com
-volume vol3 -enabled true -trigger volume -commitment try -delete-order
oldest_first -destroy-list lun_clone,file_clone
----
+
[NOTE]
====
聚合级快照的工作原理与卷级快照不同、它由ONTAP自动管理。删除聚合快照的选项始终处于启用状态、并有助于管理空间利用率。

如果聚合的触发器参数设置为 `snap_reserve`、则会一直保留快照、直到预留空间超过阈值容量为止。因此，即使未将触发器参数设置为，命令中快照使用的空间也 `snap_reserve`将列为，因为这些快照会被 `0`自动删除。此外、聚合中快照使用的空间会被视为可用空间、并包含在命令的可用空间参数中。

====

