---
permalink: volumes/df-command-file-size-concept.html 
sidebar: sidebar 
keywords: df, command, file, size, reporting, reports, space, usage, qtree, quota 
summary: 在df命令中报告空间使用量的方式取决于配额配置。 
---
= df 命令如何计算文件大小
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
中的方式 `df` 命令报告空间使用量取决于两个条件：为包含qtree的卷启用还是禁用配额、以及是否跟踪qtree内的配额使用量。

为包含qtree的卷启用配额后、如果跟踪qtree中的配额使用量、则会报告空间使用量 `df` 命令等于配额报告指定的值。在这种情况下，配额使用量不包括目录， ACL ，流目录和元文件使用的块。

如果卷上未启用配额，或者 qtree 未配置配额规则，则报告的空间使用量包括整个卷（包括卷中的其他 qtree ）的目录， ACL ，流目录和元文件使用的块。在这种情况下、是指报告的空间使用量 `df` 命令大于跟踪配额时报告的预期值。

运行时 `df` 命令在跟踪其配额使用量的qtree的挂载点、命令输出显示的空间使用量与配额报告指定的值相同。在大多数情况下、如果树配额规则具有硬盘限制、则为报告的总大小 `df` 命令等于磁盘限制、而可用空间等于配额磁盘限制与配额使用量之差。

但是、在某些情况下、会报告可用空间 `df` 命令可能等于整个卷中的可用空间。如果没有为 qtree 配置硬盘限制，则可能会发生这种情况。从 ONTAP 9.1.1 开始，当卷整体中的可用空间小于剩余的树配额空间时，也可能发生这种情况。如果出现上述任一情况、则为报告的总大小 `df` command是一个经过相应处理的数字、该数字等于qtree中使用的配额加上FlexVol卷中的可用空间。

[NOTE]
====
此总大小既不是 qtree 磁盘限制，也不是卷配置的大小。它也可能因您在其他 qtree 中的写入活动或您的后台存储效率活动而异。

====
.计算的空间使用量示例 `df` 命令和配额报告
以下配额报告显示了 qtree 爱丽斯的磁盘限制为 1 GB ， qtree bob 的磁盘限制为 2 GB ， qtree 项目 1 的磁盘限制为无：

[listing]
----
C1_vsim1::> quota report -vserver vs0
Vserver: vs0
                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
vol2     alice     tree    1
                                  502.0MB    1GB       2       -   alice
vol2     bob       tree    2
                                   1003MB    2GB       2       -   bob
vol2     project1  tree    3
                                  200.8MB      -       2       -   project1
vol2               tree    *           0B      -       0       -   *
4 entries were displayed.
----
在以下示例中、是的输出 `df` qtrees上的命令Alice和bob报告的已用空间与配额报告相同、总大小(以1M块为单位)与磁盘限制相同。这是因为 qtree a丽 斯和 bob 的配额规则定义了磁盘限制，并且卷可用空间（ 1211 MB ）大于 qtree a丽 斯（ 523 MB ）和 qtree bob （ 1045 MB ）的剩余树配额空间。

[listing]
----
linux-client1 [~]$ df -m /mnt/vol2/alice
Filesystem          1M-blocks  Used Available Use% Mounted on
172.21.76.153:/vol2      1024   502       523  50% /mnt/vol2

linux-client1 [~]$ df -m /mnt/vol2/bob
Filesystem          1M-blocks  Used Available Use% Mounted on
172.21.76.153:/vol2      2048  1004      1045  50% /mnt/vol2
----
在以下示例中、是的输出 `df` qtree项目1上的命令报告的已用空间与配额报告相同、但总大小是通过将整个卷中的可用空间(1211 MB)与qtree项目1的配额使用量(201 MB)进行加起来得到的、即总共1412 MB。这是因为 qtree project1 的配额规则没有磁盘限制。

[listing]
----
linux-client1 [~]$ df -m /mnt/vol2/project1
Filesystem          1M-blocks  Used Available Use% Mounted on
172.21.76.153:/vol2      1412   201      1211  15% /mnt/vol2
----
[NOTE]
====
以下示例显示了的输出 `df` 命令报告的可用空间与整个卷上的"space"(可用空间)相同。

[listing]
----
linux-client1 [~]$ df -m /mnt/vol2
Filesystem          1M-blocks  Used Available Use% Mounted on
172.21.76.153:/vol2      2919  1709      1211  59% /mnt/vol2
----
====