---
permalink: volumes/enable-temperature-sensitive-efficiency-concept.html 
sidebar: sidebar 
keywords: enable, temperature, sensitive, storage, efficiency, sequential packing 
summary: 'ONTAP 9.8 引入了对温度敏感的存储效率，并在新创建的精简配置 AFF 卷上自动启用。从ONTAP 9.10.1开始、默认情况下会创建新的AFF 卷、并在卷上进行8 k自适应数据压缩(默认模式)。如果需要对温度敏感的存储效率、则必须明确将其设置为在卷上启用自动自适应数据压缩和实时重复数据删除、跨卷实时重复数据删除和跨卷后台重复数据删除(高效模式)。' 
---
= 温度敏感型存储效率概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 通过评估卷数据的访问频率并将该频率映射到应用于该数据的压缩程度、可提供对温度敏感的存储效率优势。对于不常访问的冷数据、将压缩较大的数据块；对于频繁访问且覆盖频率更高的热数据、将压缩较小的数据块、从而提高流程效率。

ONTAP 9.8引入了对温度敏感的存储效率功能、并在新创建的精简配置AFF 卷上自动启用。

从ONTAP 9.10.1开始、仅为AFF 系统引入了两种卷级存储效率模式、即_default_和_高效_。这两种模式提供了两种选择：文件压缩(默认)(创建新AFF 卷时的默认模式)或温度敏感型存储效率(高效)(启用温度敏感型存储效率)。对于ONTAP 9.10.1、必须明确设置对温度敏感的存储效率、以启用自动自适应数据压缩。但是、默认情况下、AFF 平台会在默认和高效模式下启用数据缩减、自动重复数据删除计划、实时重复数据删除、跨卷实时重复数据删除和跨卷后台重复数据删除等其他存储效率功能。

启用了FabricPoool的聚合以及所有分层策略类型均支持这两种存储效率模式(默认和高效)。

从ONTAP 9.13.1开始、对温度敏感的存储效率功能可添加连续物理块的顺序打包功能、从而进一步提高存储效率。将系统升级到ONTAP 9.13.1后、启用了对温度敏感的存储效率的卷会自动启用顺序打包。启用顺序打包后、您必须执行此操作 link:https://docs.netapp.com/us-en/ontap/volumes/run-efficiency-operations-manual-task.html["手动重新打包现有数据"]。



== 升级注意事项

升级到ONTAP 9.10.1及更高版本时、系统会根据现有卷上当前启用的压缩类型为这些卷分配存储效率模式。在升级期间，启用了数据压缩的卷将分配默认模式，启用了温度敏感型存储效率的卷将分配高效模式。如果未启用数据压缩，存储效率模式将保持空白。
