---
permalink: volumes/enable-temperature-sensitive-efficiency-concept.html 
sidebar: sidebar 
keywords: enable, temperature, sensitive, storage, efficiency, sequential packing 
summary: 在ONTAP 9。8中推出、某些AFF卷会自动启用对温度敏感的存储效率、而现有卷则会手动启用此效率。 
---
= 温度敏感型存储效率概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP可通过评估卷数据的访问频率并将该频率映射到应用于该数据的压缩程度来提供对温度敏感的存储效率优势。对于不常访问的冷数据、将压缩较大的数据块；对于频繁访问且覆盖频率更高的热数据、将压缩较小的数据块、从而提高流程效率。

ONTAP 9.8中引入了温度敏感型存储效率(TSSE)、此功能会在新创建的精简配置AFF卷上自动启用。您可以在现有AFF卷和精简配置的非Af DP卷上启用对温度敏感的存储效率。


NOTE: AFF A70、AFF A90和AFF A1K平台不会应用对温度敏感的存储效率。数据压缩不是基于这些平台上的热数据或冷数据、因此数据压缩开始时无需等待数据变冷。

.引入"默认"和"高效"模式
从ONTAP 9 10.1开始、仅为AFF系统引入了_default_和_高效_卷级存储效率模式。这两种模式提供了两种选择：文件压缩(默认)(创建新AFF卷时的默认模式)或温度敏感型存储效率(高效)(使用自动自适应数据压缩对不常访问的冷数据进行更多的数据压缩节省量)。

使用ONTAP 9 10.1link:../volumes/set-efficiency-mode-task.html["必须明确设置对温度敏感的存储效率"]启用自动自适应数据压缩。但是、默认情况下、AFF 平台会在默认和高效模式下启用数据缩减、自动重复数据删除计划、实时重复数据删除、跨卷实时重复数据删除和跨卷后台重复数据删除等其他存储效率功能。

启用了FabricPoool的聚合以及所有分层策略类型均支持这两种存储效率模式(默认和高效)。

.在C系列平台上启用对温度敏感的存储效率
默认情况下、在AFF C系列平台上、以及使用卷移动或SnapMirror将卷从非TSSE平台迁移到启用了TSSE的C系列平台时、如果目标上安装了以下版本、则会启用对温度敏感的存储效率：

* ONTAP 9.12.1P4及更高版本
* ONTAP 9.13.1及更高版本


有关详细信息，请参见 link:../volumes/storage-efficiency-behavior-snapmirror-reference.html["卷移动和SnapMirror操作的存储效率行为"]。

对于现有卷、不会自动启用对温度敏感的存储效率；但是、您可以link:../volumes/change-efficiency-mode-task.html["修改存储效率模式"]手动更改为高效模式。


NOTE: 将存储效率模式更改为高效后、您将无法再更改回该模式。

.通过连续打包连续物理数据块提高存储效率
从ONTAP 9.13.1开始、对温度敏感的存储效率功能可添加连续物理块的顺序打包功能、从而进一步提高存储效率。将系统升级到ONTAP 9.13.1后、启用了对温度敏感的存储效率的卷会自动启用顺序打包。启用顺序打包后，您必须link:../volumes/run-efficiency-operations-manual-task.html["手动重新打包现有数据"]。



== 升级注意事项

升级到ONTAP 9.10.1及更高版本时、系统会根据现有卷上当前启用的压缩类型为这些卷分配存储效率模式。在升级期间，启用了数据压缩的卷将分配默认模式，启用了温度敏感型存储效率的卷将分配高效模式。如果未启用数据压缩，存储效率模式将保持空白。
