---
permalink: volumes/enable-deduplication-volume-task.html 
sidebar: sidebar 
keywords: enable, deduplication, volume, FlexVol, postprocess, inline 
summary: '在FlexVol volume上启用重复数据删除(后处理或实时)以提高存储效率。' 
---
= 在卷上启用重复数据删除
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在 FlexVol 卷上启用重复数据删除以提高存储效率。您可以在所有卷上启用后处理重复数据删除，并在 AFF 或 Flash Pool 聚合上的卷上启用实时重复数据删除。

如果要在其他类型的卷上启用实时重复数据删除、请参见知识库文章 link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_enable_volume_inline_deduplication_on_Non-AFF_(All_Flash_FAS)_aggregates["如何在非AFF (全闪存FAS)聚合上启用卷实时重复数据删除"^]。

.开始之前
对于 FlexVol 卷，您必须已验证卷和聚合中是否存在足够的可用空间来容纳重复数据删除元数据。重复数据删除元数据需要聚合中的最小可用空间量。此数量等于聚合中所有经过重复数据删除的 FlexVol 卷或数据成分卷的物理数据量总量的 3% 。每个 FlexVol 卷或数据成分卷应拥有相当于物理数据总可用空间量的 4% ，总可用空间为 7% 。

[NOTE]
====
AFF系统默认启用内联重复数据删除。

====
.选项
* 使用 `volume efficiency on`命令启用后处理重复数据删除。有关的详细信息 `volume efficiency on`，请参见link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-on.html["ONTAP 命令参考"^]。
+
以下命令将在卷 VolA 上启用后处理重复数据删除：

+
`volume efficiency on -vserver vs1 -volume VolA`

* 依次使用 `volume efficiency on`命令和 `volume efficiency modify`命令并 `-inline-deduplication`将选项设置为、 `true`以启用后处理重复数据删除和实时重复数据删除。有关的详细信息 `volume efficiency modify`，请参见link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-modify.html["ONTAP 命令参考"^]。
+
以下命令会在卷 VolA 上同时启用后处理重复数据删除和实时重复数据删除：

+
`volume efficiency on -vserver vs1 -volume VolA`

+
`volume efficiency modify -vserver vs1 -volume VolA -inline-dedupe true`

* 使用 `volume efficiency on` 命令、然后是 `volume efficiency modify` 命令 `-inline-deduplication` 选项设置为 `true` 和 `-policy` 选项设置为 `inline-only` 仅启用实时重复数据删除。
+
以下命令仅对卷 VolA 启用实时重复数据删除：

+
`volume efficiency on -vserver vs1 -volume VolA`

+
`volume efficiency modify -vserver vs1 -volume VolA -policy inline-only -inline-dedupe true`



.完成后
通过查看卷效率设置来验证设置是否已更改：
`volume efficiency show -instance`

有关的详细信息 `volume efficiency show -instance`，请参见link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-show.html["ONTAP 命令参考"^]。
