---
permalink: volumes/enable-storage-efficiency-visualization-concept.html 
sidebar: sidebar 
keywords: storage, efficiency, visualization, storage aggregate 
summary: 显示系统中所有聚合的存储效率的不同视图。 
---
= 存储效率可视化
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用 `storage aggregate show-efficiency`命令显示有关系统中所有聚合的存储效率的信息。有关的详细信息 `storage aggregate show-efficiency`，请参见link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show-efficiency.html["ONTAP 命令参考"^]。

。 `storage aggregate show-efficiency` command具有三个不同的视图、可通过传递命令选项来调用这些视图。



== 默认视图

默认视图显示每个聚合的总体比率。

`cluster1::> storage aggregate show-efficiency`



== 详细视图

使用调用详细视图 `-details` 命令选项。此视图显示以下内容：

* 每个聚合的总体效率比率。
* 不使用快照时的总体比率。
* 以下效率技术的比率拆分：卷重复数据删除、卷压缩、快照、克隆、数据缩减和聚合实时重复数据删除。


`cluster1::> storage aggregate show-efficiency -details`



== 高级视图

高级视图与详细视图类似、可同时显示已用逻辑和已用物理空间的详细信息。

您必须在高级权限级别运行此命令。使用切换到高级权限 `set -privilege advanced` 命令：

命令提示符将更改为 `cluster::*>`。

`cluster1::> set -privilege advanced`

使用调用高级视图 `-advanced` 命令选项。

`cluster1::*> storage aggregate show-efficiency -advanced`

要查看单个聚合的比率、请单独调用 `-aggregate _aggregate_name_` 命令：此命令既可以在管理员级别运行，也可以在高级权限级别运行。

`cluster1::> storage aggregate show-efficiency -aggregate aggr1`

有关的详细信息 `set -privilege advanced`，请参见link:https://docs.netapp.com/us-en/ontap-cli/set.html["ONTAP 命令参考"^]。
