---
permalink: volumes/enable-logical-space-reporting-enforcement-task.html 
sidebar: sidebar 
keywords: enable, logical, space, reporting, enforcement 
summary: 从ONTAP 9．4开始，启用逻辑空间报告。从9.5开始、启用逻辑空间强制实施或同时启用报告和强制实施。 
---
= 启用逻辑空间报告和强制实施
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
从 ONTAP 9.4 开始，您可以启用逻辑空间报告。从 9.5 开始，您可以同时启用逻辑空间强制实施，也可以同时启用报告和强制实施。

.关于此任务
除了在单个卷级别启用逻辑空间报告和强制实施之外，您还可以在 SVM 级别为支持此功能的每个卷启用这些功能。如果为整个 SVM 启用逻辑空间功能，则还可以为各个卷禁用这些功能。

从ONTAP 9.8开始、如果在SnapMirror源卷上启用逻辑空间报告、则会在传输后自动在目标卷上启用该报告。

从ONTAP 9.13.1开始、如果在SnapMirror源卷上启用了强制实施选项、则目标将报告逻辑空间消耗并执行其强制实施、从而可以更好地进行容量规划。


NOTE: 如果您运行的ONTAP 版本早于ONTAP 9.13.1、则应了解、虽然强制实施设置会传输到SnapMirror目标卷、但目标卷不支持强制实施。因此、目标将报告逻辑空间消耗、但不会执行此操作。

了解更多信息 link:https://docs.netapp.com/us-en/ontap/volumes/logical-space-reporting-enforcement-concept.html["ONTAP 版本支持逻辑空间报告"]。

.步骤
启用以下一项或多项：

* 为卷启用逻辑空间报告：
+
`volume modify -vserver _svm_name_ -volume _volume_name_ -size _volume_size_ -is-space-reporting-logical true`

* 为卷启用逻辑空间强制：
+
`volume modify -vserver _svm_name_ -volume _volume_name_ -size _volume_size_ -is-space-enforcement-logical true`

* 同时为卷启用逻辑空间报告和强制实施：
+
`volume modify -vserver _svm_name_ -volume _volume_name_ -size _volume_size_ -is-space-reporting-logical true -is-space-enforcement-logical true`

* 为新 SVM 启用逻辑空间报告或强制实施：
+
`+vserver create -vserver _svm_name_ -rootvolume root-_volume_name_ -rootvolume-security-style unix -data-services {desired-data-services} [-is-space-reporting-logical true] [-is-space-enforcement-logical true]+`

* 为现有 SVM 启用逻辑空间报告或强制实施：
+
`+vserver modify -vserver _svm_name_ {desired-data-services} [-is-space-reporting-logical true] [-is-space-enforcement-logical true]+`


