---
permalink: volumes/examples-quota-config-concept.html 
sidebar: sidebar 
keywords: examples, quota, configuration, volume quota policy 
summary: 以下示例可帮助您了解如何配置配额和读取配额报告。 
---
= 配额配置示例
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
以下示例可帮助您了解如何配置配额和读取配额报告。

.关于这些示例
在以下示例中，假设您的存储系统包含 `vs1`一个SVM，其中包含一个卷 `vol1`。

. 要开始设置配额、请为此SVM创建一个新的配额策略：
+
[listing]
----
cluster1::>volume quota policy create -vserver vs1 -policy-name quota_policy_vs1_1
----
. 由于此配额策略是新策略、因此应将其分配给SVM：
+
[listing]
----
cluster1::>vserver modify -vserver vs1 -quota-policy quota_policy_vs1_1
----


.示例1：默认用户配额
. 您决定对中的每个用户强制实施50 MB的硬限制 `vol1`：
+
[listing]
----
cluster1::>volume quota policy rule create -vserver vs1 -policy-name quota_policy_vs1_1 -volume vol1 -type user -target "" -disk-limit 50MB -qtree ""
----
. 要激活新规则，请初始化卷上的配额：
+
[listing]
----
cluster1::>volume quota on -vserver vs1 -volume vol1 -foreground
----
. 您可以查看配额报告：
+
[listing]
----
cluster1::>volume quota report
----


生成的配额报告类似于以下报告：

[listing]
----
Vserver: vs1
                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
vol1               user    *           0B   50MB       0       -   *
vol1               user    jsmith    49MB   50MB      37       -   *
vol1               user    root        0B      -       1       -
----
第一行显示您创建的默认用户配额，包括磁盘限制。与所有默认配额一样，此默认用户配额不会显示有关磁盘或文件使用情况的信息。除了已创建的配额之外、还会显示另外两个配额。当前拥有上的文件的每个用户有一个配额 `vol1`。这些附加配额是自动从默认用户配额派生的用户配额。此用户的派生用户配额 `jsmith`与默认用户配额具有相同的50 MB磁盘限制。root 用户的派生用户配额是一个跟踪配额（无限制）。

如果系统上的任何用户(root用户除外)尝试执行的操作将使用超过50 MB的空间 `vol1`(例如、从编辑器写入文件)、该操作将失败。

.示例2：显式用户配额覆盖默认用户配额
. 如果需要在卷中 `vol1`为用户提供更多空间 `jsmith`，请输入以下命令：
+
[listing]
----
cluster1::>volume quota policy rule create -vserver vs1 -policy-name quota_policy_vs1_1 -volume vol1 -type user -target jsmith -disk-limit 80MB -qtree ""
----
+
这是一个显式用户配额，因为该用户已明确列为配额规则的目标。

+
这是对现有配额限制的更改、因为它会更改 `jsmith`卷上用户的派生用户配额的磁盘限制。因此，您无需重新初始化卷上的配额即可激活更改。

. 调整配额大小：
+
[listing]
----
cluster1::>volume quota resize -vserver vs1 -volume vol1 -foreground
----
+
调整大小时，配额仍然有效，而调整大小过程很短。



生成的配额报告类似于以下报告：

[listing]
----
cluster1::> volume quota report
Vserver: vs1
                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
vol1               user    *           0B   50MB       0       -   *
vol1               user    jsmith    50MB   80MB      37       -   jsmith
vol1               user    root        0B      -       1       -
3 entries were displayed.
----
现在，第二行显示磁盘限制 `80MB`和配额说明符 `jsmith`。

因此、 `jsmith` `vol1`即使所有其他用户仍限制为50 MB、也可以在上使用多达80 MB的空间。

.示例3：阈值
假设您希望在用户达到其磁盘限制的 5 MB 以内时收到通知。

. 要为所有用户创建45 MB的阈值，并为创建75 MB的阈值 `jsmith`，请更改现有的配额规则：
+
[listing]
----
cluster1::>volume quota policy rule modify -vserver vs1 -policy quota_policy_vs1_1 -volume vol1 -type user -target "" -qtree "" -threshold 45MB
cluster1::>volume quota policy rule modify -vserver vs1 -policy quota_policy_vs1_1 -volume vol1 -type user -target jsmith -qtree "" -threshold 75MB
----
+
由于现有规则的大小发生更改、因此您需要调整卷上的配额大小以激活更改。请等待调整大小过程完成。

. 要查看包含阈值的配额报告、请添加 `-thresholds` 参数 `volume quota report` 命令：
+
[listing]
----
cluster1::>volume quota report -thresholds
Vserver: vs1
                                    ----Disk----  ----Files-----
Volume   Tree      Type    ID        Used  Limit   Used    Limit  Quota
                                          (Thold)                 Specifier
-------  --------  ------  -------  -----  -----  ------  ------  ---------
vol1               user    *           0B   50MB       0       -  *
                                           (45MB)
vol1               user    jsmith    59MB   80MB      55       -  jsmith
                                           (75MB)
vol1               user    root        0B      -       1       -
                                           ( -)
3 entries were displayed.
----
+
阈值显示在磁盘限制列的圆括号中。



.示例4：qtree上的配额
假设您需要对两个项目的部分空间进行分区。您可以创建两个名为 `proj1`和 `proj2`的qtrees，以便在中容纳这些项目 `vol1`。

目前，用户可以使用为整个卷分配的 qtree 空间（前提是他们不会通过使用根或另一个 qtree 中的空间超过卷的限制）。此外，每个 qtree 都可以增长以占用整个卷。

. 如果要确保两个 qtree 的大小均不超过 20 GB ，则可以在卷上创建默认树配额：
+
[listing]
----
cluster1:>>volume quota policy rule create -vserver vs1 -policy-name quota_policy_vs1_1 -volume vol1 -type tree -target "" -disk-limit 20GB
----
+

NOTE: 正确的类型是_tree_、而不是qtree。

. 由于这是一个新配额，因此无法通过调整大小来激活它。重新初始化卷上的配额：
+
[listing]
----
cluster1:>>volume quota off -vserver vs1 -volume vol1
cluster1:>>volume quota on -vserver vs1 -volume vol1 -foreground
----


[NOTE]
====
重新激活每个受影响卷上的配额之前、您必须确保等待大约五分钟、因为在运行后几乎会立即尝试激活这些配额 `volume quota off` 命令可能会导致错误。或者，您也可以运行命令，从包含特定卷的节点重新初始化卷的配额。

====
重新初始化过程中不会强制实施配额，而重新初始化过程所需时间比调整大小过程长。

显示配额报告时、该报告包含多个新行。某些行用于树配额、某些行用于派生用户配额。

以下新行用于树配额：

[listing]
----

                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
...
vol1               tree    *           0B   20GB       0       -   *
vol1     proj1     tree    1           0B   20GB       1       -   proj1
vol1     proj2     tree    2           0B   20GB       1       -   proj2
...
----
创建的默认树配额将显示在第一个新行中，其中 ID 列中有一个星号（ * ）。为了响应卷上的默认树配额， ONTAP 会自动为卷中的每个 qtree 创建派生树配额。它们显示在 `proj1` `proj2` `Tree`列中和所在的行中。

以下新行用于派生用户配额：

[listing]
----

                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
...
vol1     proj1     user    *           0B   50MB       0       -
vol1     proj1     user    root        0B      -       1       -
vol1     proj2     user    *           0B   50MB       0       -
vol1     proj2     user    root        0B      -       1       -
...
----
如果为 qtree 启用了配额，则卷上的默认用户配额会自动继承该卷包含的所有 qtree 的默认用户配额。添加第一个 qtree 配额时，您在 qtree 上启用了配额。因此，系统会为每个 qtree 创建派生的默认用户配额。这些 ID 显示在 ID 为星号（ * ）的行中。

由于 root 用户是文件的所有者，因此在为每个 qtree 创建默认用户配额时，也会为每个 qtree 上的 root 用户创建特殊的跟踪配额。这些 ID 显示在 ID 为 root 的行中。

.示例5：qtree上的用户配额
. 您决定限制用户在 `proj1`qtree中使用的空间少于在整个卷中获得的空间。您希望使其在 `proj1`qtree中的使用量不超过10 MB。因此，您可以为 qtree 创建默认用户配额：
+
[listing]
----
cluster1::>volume quota policy rule create -vserver vs1 -policy-name quota_policy_vs1_1 -volume vol1 -type user -target "" -disk-limit 10MB -qtree proj1
----
+
这是对现有配额的更改，因为它会更改 proj1 qtree 的默认用户配额，该配额是从卷上的默认用户配额派生的。因此，您可以通过调整配额大小来激活更改。调整大小过程完成后，您可以查看配额报告。

+
配额报告中将显示以下新行，其中显示了 qtree 的新显式用户配额：

+
[listing]
----

                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
vol1     proj1     user    *           0B   10MB       0       -   *
----
+
但是、 `jsmith`由于您为覆盖默认用户配额(以提供更多空间)而创建的配额位于卷上、因此用户无法向proj1 qtree写入更多数据。在 `proj1`qtree上添加默认用户配额后，将应用该配额，并限制该qtree中所有用户的空间，包括 `jsmith`。

. 要为用户提供更多空间 `jsmith`，请为qtree添加一个磁盘限制为80 MB的显式用户配额规则，以覆盖qtree的默认用户配额规则：
+
[listing]
----
cluster1::>volume quota policy rule create -vserver vs1 -policy-name quota_policy_vs1_1 -volume vol1 -type user -target jsmith -disk-limit 80MB -qtree proj1
----
+
由于这是已存在默认配额的显式配额、因此您可以通过调整配额大小来激活更改。调整大小过程完成后，您将显示配额报告。



配额报告中将显示以下新行：

[listing]
----

                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
vol1     proj1     user    jsmith    61MB   80MB      57       -   jsmith
----
最终配额报告类似于以下报告：

[listing]
----
cluster1::>volume quota report
Vserver: vs1
                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
vol1               tree    *           0B   20GB       0       -   *
vol1               user    *           0B   50MB       0       -   *
vol1               user    jsmith    70MB   80MB      65       -   jsmith
vol1     proj1     tree    1           0B   20GB       1       -   proj1
vol1     proj1     user    *           0B   10MB       0       -   *
vol1     proj1     user    root        0B      -       1       -
vol1     proj2     tree    2           0B   20GB       1       -   proj2
vol1     proj2     user    *           0B   50MB       0       -
vol1     proj2     user    root        0B      -       1       -
vol1               user    root        0B      -       3       -
vol1     proj1     user    jsmith    61MB   80MB      57       -   jsmith
11 entries were displayed.
----
用户 `jsmith`必须满足以下配额限制才能写入中的文件 `proj1`：

.  `proj1`qtree的树配额。
.  `proj1`qtree上的用户配额。
. 卷上的用户配额。

