---
permalink: volumes/explicit-quotas-concept.html 
sidebar: sidebar 
keywords: how to, use, explicit, quotas 
summary: 您可以使用显式配额为特定配额目标指定配额，或者覆盖特定目标的默认配额。 
---
= 如何使用显式配额
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用显式配额为特定配额目标指定配额，或者覆盖特定目标的默认配额。

显式配额用于指定特定用户，组或 qtree 的限制。显式配额将替换同一目标的任何默认配额。

为具有派生用户配额的用户添加显式用户配额时，必须使用与默认用户配额相同的用户映射设置。否则，在调整配额大小时，显式用户配额将被拒绝，因为它被视为新配额。

显式配额只会影响同一级别（卷或 qtree ）的默认配额。例如， qtree 的显式用户配额不会影响包含该 qtree 的卷的默认用户配额。但是， qtree 的显式用户配额会覆盖（替换由定义的限制）该 qtree 的默认用户配额。

.显式配额示例
以下配额规则定义了一个默认用户配额、该配额会将vol1中的所有用户限制为50 MB的空间。但是、由于显式配额(以粗体显示)、用户jsmith可以获得80 MB的空间：

[listing]
----
cluster1::> volume quota policy rule create -vserver vs0 -volume vol1 -policy-name default -type user -target "" -qtree "" -disk-limit 50m

cluster1::> volume quota policy rule create -vserver vs0 -volume vol1 -policy-name default -type user -target "jsmith" -qtree "" -disk-limit 80m

cluster1::> volume quota policy rule show -vserver vs0 -volume vol1

Vserver: vs0               Policy: default           Volume: vol1
                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
user   ""        ""      off          50MB        -       -        -          -
user   jsmith    ""      off          80MB        -       -        -          -
----
以下配额规则会将指定用户(由四个ID表示)限制为vol1卷中的550 MB磁盘空间和10、000个文件：

[listing]
----
cluster1::> volume quota policy rule create -vserver vs0 -volume vol1 -policy-name default -type user -target " jsmith,corp\jsmith,engineering\john smith,S-1-5-32-544" -qtree "" -disk-limit 550m -file-limit 10000

cluster1::> volume quota policy rule show -vserver vs0 -volume vol1

Vserver: vs0               Policy: default           Volume: vol1
                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
user   "jsmith,corp\jsmith,engineering\john smith,S-1-5-32-544"
                 ""      off         550MB        -   10000        -          -
----
以下配额规则将eng1组的磁盘空间限制为150 MB、并且proj1 qtree中的文件数不限：

[listing]
----
cluster1::> volume quota policy rule create -vserver vs0 -volume vol2 -policy-name default -type group -target "eng1" -qtree "proj1" -disk-limit 150m

cluster1::> volume quota policy rule show -vserver vs0 -volume vol2

Vserver: vs0               Policy: default           Volume: vol2
                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
group  eng1      proj1   off         150MB        -       -        -          -
----
以下配额规则将卷vol2中的proj1 qtree限制为750 MB磁盘空间和75、000个文件：

[listing]
----
cluster1::> volume quota policy rule create -vserver vs0 -volume vol2 -policy-name default -type tree -target "proj1" -disk-limit 750m -file-limit 75000

cluster1::> volume quota policy rule show -vserver vs0 -volume vol2

Vserver: vs0               Policy: default           Volume: vol2
                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
tree   proj1     ""      -           750MB        -   75000        -          -
----