---
permalink: volumes/quota-notifications-concept.html 
sidebar: sidebar 
keywords: understanding, quota, notifications 
summary: 配额通知是发送到事件管理系统（ EMS ）的消息，也配置为 SNMP 陷阱。 
---
= 关于配额通知
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
配额通知是发送到事件管理系统（ EMS ）的消息，也配置为 SNMP 陷阱。

系统会针对以下事件发送通知：

* 达到硬配额；换言之，尝试超过该配额
* 已超过软配额
* 不再超过软配额


阈值与其他软配额略有不同。阈值仅在超过阈值时触发通知，而不是在不再超过阈值时触发通知。

硬配额通知可通过使用 volume quota modify 命令进行配置。您可以完全关闭它们，也可以更改其频率，例如，以防止发送冗余消息。

软配额通知不可配置，因为它们不太可能生成冗余消息，其唯一目的是通知。

下表列出了配额发送到 EMS 系统的事件：

[cols="2*"]
|===
| 发生这种情况的时间 | 此事件将发送到 EMS... 


 a| 
已达到树配额中的硬限制
 a| 
`wafl.quota.qtree.exceeded`



 a| 
已达到卷上用户配额的硬限制
 a| 
`wafl.quota.user.exceeded` (对于UNIX用户)
`wafl.quota.user.exceeded.win` (对于Windows用户)



 a| 
已达到 qtree 上用户配额的硬限制
 a| 
`wafl.quota.userQtree.exceeded` (对于UNIX用户)
`wafl.quota.userQtree.exceeded.win` (对于Windows用户)



 a| 
已达到卷上组配额的硬限制
 a| 
`wafl.quota.group.exceeded`



 a| 
已达到 qtree 上组配额的硬限制
 a| 
`wafl.quota.groupQtree.exceeded`



 a| 
已超过软限制，包括阈值
 a| 
`quota.softlimit.exceeded`



 a| 
不再超过软限制
 a| 
`quota.softlimit.normal`

|===
下表列出了配额生成的 SNMP 陷阱：

[cols="2*"]
|===
| 发生这种情况的时间 | 已发送此 SNMP 陷阱 ... 


 a| 
已达到硬限制
 a| 
quotaExceeded



 a| 
已超过软限制，包括阈值
 a| 
quotaExceeded 和 softQuotaExceeded



 a| 
不再超过软限制
 a| 
quotaNormal 和 softQuotaNormal

|===
[NOTE]
====
通知包含 qtree ID 号，而不是 qtree 名称。您可以使用将qtree名称与ID编号相关联 `volume qtree show -id` 命令：

====