---
permalink: volumes/resume-efficiency-operation-checkpoint-task.html 
sidebar: sidebar 
keywords: resume, halted, efficiency, operation 
summary: 如果系统暂停了效率操作、您可以在同一时刻恢复该效率操作。 
---
= 恢复暂停的效率操作
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果效率操作因系统暂停、系统中断或重新启动而暂停、则可以从暂停的同一时间点恢复该效率操作。这有助于节省时间和资源、因为无需从头开始重新启动操作。

.关于此任务
如果在卷上仅启用了重复数据删除，则会对数据运行重复数据删除。如果在卷上同时启用了重复数据删除和数据压缩，则先运行数据压缩，然后运行重复数据删除。

您可以使用命令查看卷的检查点详细信息 `volume efficiency show`。有关的详细信息 `volume efficiency show`，请参见link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-show.html["ONTAP 命令参考"^]。

默认情况下，效率操作会从检查点恢复。但是、如果检查点对应于上次效率操作(当 `volume efficiency start``scan-old-data`命令运行)超过24小时、则效率操作不会自动从上一个检查点恢复。在这种情况下，效率操作将从头开始。但是、如果您知道自上次扫描以来卷中未发生重大更改、则可以使用强制从上一个检查点继续 `-use-checkpoint` 选项

.步骤
. 使用 `volume efficiency start` 命令 `-use-checkpoint` 用于恢复效率操作的选项。
+
使用以下命令可以对卷 VolA 上的新数据恢复效率操作：

+
`volume efficiency start -vserver vs1 -volume VolA -use-checkpoint true`

+
使用以下命令可以对卷 VolA 上的现有数据恢复效率操作：

+
`volume efficiency start -vserver vs1 -volume VolA -scan-old-data true -use-checkpoint true`

+
有关的详细信息 `volume efficiency start`，请参见link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-start.html["ONTAP 命令参考"^]。


