---
permalink: volumes/set-fractional-reserve-concept.html 
sidebar: sidebar 
keywords: considerations, setting, fractional, reserve 
summary: 百分比预留也称为 LUN 覆盖预留，用于为 FlexVol 卷中预留了空间的 LUN 和文件禁用覆盖预留。这有助于最大限度地提高存储利用率，但如果您的环境因空间不足导致写入操作失败而受到负面影响，则必须了解此配置所具有的要求。 
---
= 设置预留百分比的注意事项
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
预留百分比也称为 _lun overwrite reserve ，用于为 FlexVol 卷中预留了空间的 LUN 和文件禁用覆盖预留。这有助于最大限度地提高存储利用率，但如果您的环境因空间不足导致写入操作失败而受到负面影响，则必须了解此配置所具有的要求。

预留百分比设置以百分比表示；唯一有效的值为 `0` 和 `100` 百分比。预留百分比设置是卷的一个属性。

将预留百分比设置为 `0` 提高存储利用率。但是、如果卷的可用空间不足、则访问卷中数据的应用程序可能会发生数据中断、即使卷保证设置为也是如此 `volume`。但是，通过正确配置和使用卷，您可以最大限度地减少写入失败的可能性。ONTAP为预留百分比设置为的卷提供"`尽力确保最佳结果`"写入保证 `0` 满足_all_以下要求时：

* 未使用重复数据删除
* 未使用数据压缩
* 未使用 FlexClone 子文件
* 所有 FlexClone 文件和 FlexClone LUN 均已启用自动删除
+
这不是默认设置。您必须在创建时或创建 FlexClone 文件或 FlexClone LUN 后通过修改来显式启用自动删除。

* 未使用 ODX 和 FlexClone 副本卸载
* 卷保证设置为 `volume`
* 文件或LUN空间预留为 `enabled`
* 卷Snapshot预留设置为 `0`
* 卷Snapshot副本自动删除为 `enabled` 承诺级别为 `destroy`的销毁列表 `lun_clone,vol_clone,cifs_share,file_clone,sfsr`和触发器 `volume`
+
此设置还可确保在必要时删除 FlexClone 文件和 FlexClone LUN 。



[NOTE]
====
* 如果满足上述所有要求、但更改率较高、则在极少数情况下、Snapshot副本自动删除可能会落后、从而导致卷空间不足。
* 如果满足上述所有要求、并且未使用Snapshot副本、则可以保证卷写入不会用尽空间。


====
此外，您还可以选择使用卷自动增长功能来降低需要自动删除卷 Snapshot 副本的可能性。如果启用自动增长功能，则必须监控关联聚合中的可用空间。如果聚合已满，无法增加卷，则随着卷中的可用空间耗尽，可能会删除更多 Snapshot 副本。

如果无法满足上述所有配置要求、并且需要确保卷不会用尽空间、则必须将卷的预留百分比设置为 `100`。这需要预先准备更多的可用空间，但可以保证即使使用上述技术，数据修改操作也会成功。

预留百分比设置的默认值和允许值取决于卷的保证：

[cols="3*"]
|===
| 卷保证 | 默认预留百分比 | 允许的值 


 a| 
Volume
 a| 
100
 a| 
0、100



 a| 
无
 a| 
0
 a| 
0、100

|===