---
permalink: volumes/space-display-quota-report-unix-client-concept.html 
sidebar: sidebar 
keywords: difference, space usage, displayed, quota report, unix client 
summary: FlexVol volume或qtree的配额报告中显示的已用磁盘空间值可能与UNIX客户端为同一个卷或qtree显示的值不同。 
---
= 配额报告显示的空间使用量与UNIX客户端显示的空间使用量之间的差异概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexVol volume或qtree的配额报告中显示的已用磁盘空间值可能与UNIX客户端为同一个卷或qtree显示的值不同。这些值之所以存在差异、是因为配额报告和UNIX命令在计算卷或qtree中的数据块时所遵循的方法不同。

例如，如果卷包含包含包含空数据块（未向其写入数据）的文件，则该卷的配额报告在报告空间使用情况时不会计算空数据块。但是、当卷挂载到UNIX客户端上且文件显示为的输出时 `ls` 命令中、空数据块也会计入空间使用量。因此、 `ls` 命令显示的文件大小比配额报告显示的空间使用量更大。

同样、配额报告中显示的空间使用量值也可能与UNIX命令(如)显示的值不同 `df` 和 `du`。



== 配额报告如何计算磁盘空间和文件使用量

FlexVol 卷或 qtree 的配额报告中指定的已用文件数和磁盘空间量取决于卷或 qtree 中每个索引节点对应的已用数据块数。

块计数包括用于常规文件和流文件的直接块和间接块。配额报告不会考虑用于目录，访问控制列表（ ACL ），流目录和元文件的块。对于 UNIX 稀疏文件，配额报告不会包含空数据块。

配额子系统的设计目的是考虑并仅包括文件系统中用户可控制的方面。目录、ACL和快照空间都是配额计算中排除的空间示例。配额用于强制实施限制、而不是保证、它们仅在活动文件系统上运行。配额核算不会计入某些文件系统结构、也不会计入存储效率(例如数据压缩或重复数据删除)。

有关此过程中所述命令的更多信息，请参见link:https://docs.netapp.com/us-en/ontap-cli/["ONTAP 命令参考"^]。
