---
permalink: volumes/split-flexclone-from-parent-task.html 
sidebar: sidebar 
keywords: split, flexclone, volume, parent, volume, clone 
summary: 您可以将FlexClone卷从其父卷中拆分出来、使克隆成为普通FlexVol卷。 
---
= 将 FlexClone 卷从其父卷拆分
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以将FlexClone卷从其父卷中拆分出来、使克隆成为普通FlexVol卷。

克隆拆分操作在后台进行。拆分期间、可以访问克隆和父级上的数据。从ONTAP 9.4开始、可保留空间效率。拆分过程仅更新元数据、并且所需的IO极少。不会复制任何数据块。

.关于此任务
* 在拆分操作期间、无法创建FlexClone卷的新Snapshot副本。
* 如果FlexClone卷属于数据保护关系或属于负载共享镜像、则不能将其从父卷中拆分。
* 如果在拆分过程中将FlexClone卷脱机、则拆分操作将暂停；将FlexClone卷恢复联机后、拆分操作将恢复。
* 拆分后、父FlexVol卷和克隆都需要分配由其卷保证确定的完整空间。
* 从父卷拆分FlexClone卷后、这两个卷将无法重新加入。
* 从 ONTAP 9.4 开始，对于 AFF 系统上的非保证卷， FlexClone 卷的拆分操作会共享物理块，而不会复制数据。因此、在ONTAP 9.4及更高版本中、在AFF系统上拆分FlexClone卷比在其他FAS系统上拆分FlexClone卷更快。在 AFF 系统上改进的 FlexClone 拆分操作具有以下优势：
+
** 从父级拆分克隆后，存储效率会保留下来。
** 不会删除现有 Snapshot 副本。
** 操作速度更快。
** FlexClone 卷可以从克隆层次结构中的任意位置拆分。




.开始之前
* 您必须是集群管理员。
* 拆分操作开始时、FlexClone卷必须处于联机状态。
* 要成功拆分父卷、此父卷必须联机。


.步骤
. 确定完成拆分操作所需的可用空间量：
+
`volume clone show -estimate -vserver _vserver_name_ -flexclone _clone_volume_name_ -parent-volume _parent_vol_name_`

+
以下示例提供了有关将FlexClone卷"`clone1`"从其父卷"`vol1`"拆分所需可用空间的信息：

+
[listing]
----
cluster1::> volume clone show -estimate -vserver vs1 -flexclone clone1 -parent-volume volume1
                             Split
Vserver   FlexClone       Estimate
--------- ------------- ----------
vs1       clone1           40.73MB
----
. 验证包含 FlexClone 卷及其父卷的聚合是否具有足够的空间：
+
.. 确定包含 FlexClone 卷及其父卷的聚合中的可用空间量：
+
`storage aggregate show`

.. 如果所属聚合没有足够的可用空间，请向该聚合添加存储：
+
`storage aggregate add-disks`



. 启动拆分操作：
+
`volume clone split start -vserver _vserver_name_ -flexclone _clone_volume_name_`

+
以下示例显示了如何启动从父卷"`vol1`"拆分FlexClone卷"`clone1`"的过程：

+
[listing]
----
cluster1::> volume clone split start -vserver vs1 -flexclone clone1

Warning: Are you sure you want to split clone volume clone1 in Vserver vs1 ?
{y|n}: y
[Job 1617] Job is queued: Split clone1.
----
. 监控 FlexClone 拆分操作的状态：
+
`volume clone split show -vserver _vserver_name_ -flexclone _clone_volume_name_`

+
以下示例显示了 AFF 系统上的 FlexClone 拆分操作状态：

+
[listing]
----
cluster1::> volume clone split show -vserver vs1 -flexclone clone1
                                              Inodes                   Blocks
                                     ---------------------    ---------------------
Vserver   FlexClone    Processed Total    Scanned  Updated      % Inode   % Block
                                                                 Complete  Complete
vs1       clone1        0         0       411247   153600         0        37
----
. 验证拆分的卷是否不再是 FlexClone 卷：
+
`volume show -volume _volume_name_ -fields clone-volume`

+
的值 `clone-volume` 对于非FlexClone卷、选项为"`false`"。

+
以下示例显示了如何验证从其父卷拆分的卷"`clone1`"是否不是FlexClone卷。

+
[listing]
----
cluster1::> volume show -volume clone1 -fields clone-volume
vserver volume **clone-volume**
------- ------ **------------**
vs1     clone1 **false**
----

