---
permalink: volumes/tree-quotas-concept.html 
sidebar: sidebar 
keywords: how, tree, quotas, work 
summary: 您可以创建以 qtree 作为目标的配额，以限制目标 qtree 的大小。这些配额也称为树配额。 
---
= 了解 ONTAP 树配额
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以创建以 qtree 作为目标的配额，以限制目标 qtree 的大小。这些配额也称为 _tree quotas_ 。


NOTE: 您还可以为特定 qtree 创建用户和组配额。此外， FlexVol 卷的配额有时会由该卷包含的 qtree 继承。

将配额应用于 qtree 时，结果与磁盘分区类似，只是您可以随时通过更改配额来更改 qtree 的最大大小。应用树配额时， ONTAP 会限制 qtree 中的磁盘空间和文件数量，而不管这些文件的所有者是谁。如果写入操作导致超过树配额，则任何用户（包括 root 用户和 BUILTIN\Administrators 组的成员）都无法向 qtree 写入数据。

配额大小并不保证有任何特定的可用空间量。配额大小可以大于 qtree 可用空间量。您可以使用 `volume quota report` 命令以确定qtree中的实际可用空间量。

有关的详细信息 `volume quota report`，请参见link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-report.html["ONTAP 命令参考"^]。



== 了解 ONTAP 用户和组配额如何与 qtree 配合使用

树配额限制了 qtree 的总大小。要防止单个用户或组使用整个 qtree ，请为此 qtree 指定用户或组配额。

.qtree中的用户配额示例
[%collapsible]
====
假设您具有以下配额规则：

[listing]
----
cluster1::> volume quota policy rule show -vserver vs0 -volume vol1

Vserver: vs0               Policy: default           Volume: vol1
                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
user   ""        ""      off          50MB        -       -        -       45MB
user   jsmith    ""      off          80MB        -       -        -       75MB
----
您注意到某个用户kjones占用了关键qtree proj1中的太多空间、该qtree位于vol1中。您可以通过添加以下配额规则来限制此用户的空间：

[listing]
----
cluster1::> volume quota policy rule create -vserver vs0 -volume vol1 -policy-name default -type user -target "kjones" -qtree "proj1" -disk-limit 20m -threshold 15m

cluster1::> volume quota policy rule show -vserver vs0 -volume vol1

Vserver: vs0               Policy: default           Volume: vol1
                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
user   ""        ""      off          50MB        -       -        -       45MB
user   jsmith    ""      off          80MB        -       -        -       75MB
user   kjones    proj1   off          20MB        -       -        -       15MB
----
====


== 了解 ONTAP FlexVol 卷上的默认树配额如何创建派生树配额

在 FlexVol 卷上创建默认树配额时，系统会自动为该卷中的每个 qtree 创建相应的派生树配额。

这些派生树配额与默认树配额具有相同的限制。如果不存在其他配额，这些限制将产生以下影响：

* 用户可以使用为整个卷分配的 qtree 空间（前提是他们不会通过使用根或另一个 qtree 中的空间超过卷的限制）。
* 每个 qtree 都可以增长以占用整个卷。


卷上存在默认树配额仍会影响添加到卷中的所有新 qtree 。每次创建新 qtree 时，还会创建派生树配额。

与所有派生配额一样，派生树配额也会显示以下行为：

* 仅当目标尚未具有显式配额时才会创建。
* 显示在配额报告中、但在使用命令显示配额规则时不会显示 `volume quota policy rule show`。有关的详细信息 `volume quota policy rule show`，请参见link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-policy-rule-show.html["ONTAP 命令参考"^]。


.派生树配额示例
[%collapsible]
====
您的卷包含三个 qtree （ proj1 ， proj2 和 proj3 ），唯一的树配额是 proj1 qtree 上的显式配额，该配额将磁盘大小限制为 10 GB 。如果在卷上创建默认树配额并重新初始化卷上的配额，则配额报告现在包含四个树配额：

[listing]
----
                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
vol1     proj1     tree    1           0B   10GB       1       -   proj1
vol1               tree    *           0B   20GB       0       -   *
vol1     proj2     tree    2           0B   20GB       1       -   proj2
vol1     proj3     tree    3           0B   20GB       1       -   proj3
...
----
第一行显示了 proj1 qtree 上的原始显式配额。此配额保持不变。

第二行显示了卷上的新默认树配额。星号（ * ）配额说明符表示此配额为默认配额。此配额是您创建的配额规则的结果。

最后两行显示了 proj2 和 proj3 qtree 的新派生树配额。ONTAP 会根据卷上的默认树配额自动创建这些配额。这些派生树配额与卷上的默认树配额具有相同的 20 GB 磁盘限制。ONTAP 未为 proj1 qtree 创建派生树配额，因为 proj1 qtree 已具有显式配额。

====


== 了解 ONTAP FlexVol 卷上的默认用户配额如何影响 qtree 的配额

如果为 FlexVol 卷定义了默认用户配额，则系统会自动为该卷中存在显式或派生树配额的每个 qtree 创建默认用户配额。

如果 qtree 上已存在默认用户配额，则在卷上创建默认用户配额时，该配额不会受到影响。

在 qtree 上自动创建的默认用户配额与为卷创建的默认用户配额具有相同的限制。

qtree 的显式用户配额将覆盖自动创建的默认用户配额（替换应用的限制），与覆盖管理员在该 qtree 上创建的默认用户配额的方式相同。
