---
permalink: encryption-at-rest/assign-fips-140-2-authentication-key-task.html 
sidebar: sidebar 
keywords: assigning, fips 140-2, authentication key, fips drive 
summary: 您可以使用带有 -fips-key-id 选项的 storage encryption disk modify 命令将 FIPS 140-2 身份验证密钥分配给 FIPS 驱动器。集群节点将此密钥用于数据访问以外的驱动器操作，例如防止驱动器受到拒绝服务攻击。 
---
= 将 FIPS 140-2 身份验证密钥分配给 FIPS 驱动器
:allow-uri-read: 


[role="lead"]
您可以使用 `storage encryption disk modify` 命令和 ` -fips-key-id` 选项将 FIPS 140-2 身份验证密钥分配给 FIPS 驱动器。集群节点将此密钥用于数据访问以外的驱动器操作，例如防止驱动器受到拒绝服务攻击。

.关于此任务
您的安全设置可能要求您使用不同的密钥进行数据身份验证和 FIPS 140-2 身份验证。否则，您可以使用与数据访问相同的身份验证密钥来满足 FIPS 合规性要求。

此操作步骤 不会造成中断。

.开始之前
驱动器固件必须支持 FIPS 140-2 合规性。。 link:https://mysupport.netapp.com/matrix["NetApp 互操作性表工具"^] 包含有关支持的驱动器固件版本的信息。

.步骤
. 您必须首先确保已分配数据身份验证密钥。可以使用来完成此操作 xref:assign-authentication-keys-seds-external-task.html[外部密钥管理器] 或 xref:assign-authentication-keys-seds-onboard-task.html[板载密钥管理器]。使用命令 `storage encryption disk show` 确认已分配密钥。
. 将 FIPS 140-2 身份验证密钥分配给 SED ：
+
`storage encryption disk modify -disk _disk_id_ -fips-key-id _fips_authentication_key_id_`

+
您可以使用 `security key-manager query` 命令查看密钥 ID 。

+
[source]
----
cluster1::> storage encryption disk modify -disk 2.10.* -fips-key-id 6A1E21D80000000001000000000000005A1FB4EE8F62FD6D8AE6754C9019F35A

Info: Starting modify on 14 disks.
      View the status of the operation by using the
      storage encryption disk show-status command.
----
. 验证是否已分配身份验证密钥：
+
`s存储加密磁盘 show -fips`

+
有关完整的命令语法，请参见手册页。

+
[listing]
----
cluster1::> storage encryption disk show -fips
Disk    Mode FIPS-Compliance Key ID
------  ---- ----------------------------------------------------------------
2.10.0  full 6A1E21D80000000001000000000000005A1FB4EE8F62FD6D8AE6754C9019F35A
2.10.1  full 6A1E21D80000000001000000000000005A1FB4EE8F62FD6D8AE6754C9019F35A
[...]
----

