---
permalink: encryption-at-rest/data-seds-inaccessible-concept.html 
sidebar: sidebar 
keywords: sanitize, fips, drive, sed, inaccessible, destroy, psid, physical secure ID, nrd plus, emergency, shred,  drive, sed,  encrypt, destroy 
summary: 如果要使 FIPS 驱动器或 SED 上的数据永久不可访问，但要使驱动器的未用空间可用于存储新数据，您可以对磁盘进行清理。如果要使数据永久不可访问且无需重复使用驱动器，可以将其销毁。 
---
= 使 FIPS 驱动器或 SED 上的数据无法访问概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果要使 FIPS 驱动器或 SED 上的数据永久不可访问，但要为新数据保留驱动器的未用空间，则可以对磁盘进行清理。如果要使数据永久不可访问且无需重复使用驱动器，可以将其销毁。

* 磁盘清理
+
清理自加密驱动器时，系统会将磁盘加密密钥更改为新的随机值，将开机锁定状态重置为 false ，并将密钥 ID 设置为默认值，即制造商安全 ID 0x0 （ SAS 驱动器）或空密钥（ NVMe 驱动器）。这样做会使磁盘上的数据无法访问且无法检索。您可以将已清理的磁盘重复用作未置零的备用磁盘。

* 磁盘销毁
+
销毁 FIPS 驱动器或 SED 后，系统会将磁盘加密密钥设置为未知的随机值，并永久锁定磁盘。这样做会使磁盘永久不可用，并且磁盘上的数据永久不可访问。



您可以清理或销毁节点的单个自加密驱动器或所有自加密驱动器。



== 清理 FIPS 驱动器或 SED

如果要使FIPS驱动器或SED上的数据永久不可访问、并使用该驱动器存储新数据、则可以使用 `storage encryption disk sanitize` 命令以对驱动器进行磁盘管理。

.您需要的内容
您必须是集群管理员才能执行此任务。

.关于此任务
清理自加密驱动器时，系统会将磁盘加密密钥更改为新的随机值，将开机锁定状态重置为 false ，并将密钥 ID 设置为默认值，即制造商安全 ID 0x0 （ SAS 驱动器）或空密钥（ NVMe 驱动器）。这样做会使磁盘上的数据无法访问且无法检索。您可以将已清理的磁盘重复用作未置零的备用磁盘。

.步骤
. 将需要保留的所有数据迁移到另一个磁盘上的聚合。
. 删除要清理的 FIPS 驱动器或 SED 上的聚合：
+
`storage aggregate delete -aggregate _aggregate_name_`

+
有关完整的命令语法，请参见手册页。

+
[listing]
----
cluster1::> storage aggregate delete -aggregate aggr1
----
. 确定要清理的 FIPS 驱动器或 SED 的磁盘 ID ：
+
`storage encryption disk show -fields data-key-id,fips-key-id,owner`

+
有关完整的命令语法，请参见手册页。

+
[listing]
----
cluster1::> storage encryption disk show
Disk    Mode Data Key ID
-----   ---- ----------------------------------------------------------------
0.0.0   data F1CB30AFF1CB30B00101000000000000A68B167F92DD54196297159B5968923C
0.0.1   data F1CB30AFF1CB30B00101000000000000A68B167F92DD54196297159B5968923C
1.10.2  data F1CB30AFF1CB30B00101000000000000CF0EFD81EA9F6324EA97B369351C56AC
[...]
----
. 如果 FIPS 驱动器以 FIPS 兼容模式运行，请将节点的 FIPS 身份验证密钥 ID 设置回默认 MSID 0x0 ：
+
`storage encryption disk modify -disk _disk_id_ -fips-key-id 0x0`

+
您可以使用 `security key-manager query` 用于查看密钥ID的命令。

+
[listing]
----
cluster1::> storage encryption disk modify -disk 1.10.2 -fips-key-id 0x0

Info: Starting modify on 1 disk.
      View the status of the operation by using the
      storage encryption disk show-status command.
----
. 清理驱动器：
+
`storage encryption disk sanitize -disk _disk_id_`

+
您只能使用此命令清理热备用磁盘或损坏的磁盘。要清理所有磁盘、而不管其类型如何、请使用 `-force-all-state` 选项有关完整的命令语法，请参见手册页。

+
[NOTE]
====
系统将提示您输入确认短语，然后再继续。输入屏幕上所示的短语。

====
+
[listing]
----
cluster1::> storage encryption disk sanitize -disk 1.10.2

Warning: This operation will cryptographically sanitize 1 spare or broken self-encrypting disk on 1 node.
         To continue, enter sanitize disk: sanitize disk

Info: Starting sanitize on 1 disk.
      View the status of the operation using the
      storage encryption disk show-status command.
----




== 销毁 FIPS 驱动器或 SED

如果要使FIPS驱动器或SED上的数据永久不可访问、并且不需要重复使用该驱动器、则可以使用 `storage encryption disk destroy` 命令销毁磁盘。

.您需要的内容
您必须是集群管理员才能执行此任务。

.关于此任务
销毁 FIPS 驱动器或 SED 后，系统会将磁盘加密密钥设置为未知的随机值，并永久锁定该驱动器。这样做会使磁盘几乎不可用，并且磁盘上的数据永远不可访问。但是，您可以使用磁盘标签上印有的物理安全 ID （ PSID ）将磁盘重置为出厂配置的设置。有关详细信息，请参见 link:return-self-encrypting-disks-keys-not-available-task.html["丢失身份验证密钥后，使 FIPS 驱动器或 SED 恢复正常运行"]。

[NOTE]
====
除非您拥有不可退回的磁盘加载服务（ NRD Plus ），否则不应销毁 FIPS 驱动器或 SED 。销毁磁盘将使其保修失效。

====
.步骤
. 将需要保留的所有数据迁移到另一个磁盘上的聚合。
. 删除要销毁的 FIPS 驱动器或 SED 上的聚合：
+
`storage aggregate delete -aggregate aggregate_name`

+
有关完整的命令语法，请参见手册页。

+
[listing]
----
cluster1::> storage aggregate delete -aggregate aggr1
----
. 确定要销毁的 FIPS 驱动器或 SED 的磁盘 ID ：
+
`storage encryption disk show`

+
有关完整的命令语法，请参见手册页。

+
[listing]
----
cluster1::> storage encryption disk show
Disk    Mode Data Key ID
-----   ---- ----------------------------------------------------------------
0.0.0   data F1CB30AFF1CB30B00101000000000000A68B167F92DD54196297159B5968923C
0.0.1   data F1CB30AFF1CB30B00101000000000000A68B167F92DD54196297159B5968923C
1.10.2  data F1CB30AFF1CB30B00101000000000000CF0EFD81EA9F6324EA97B369351C56AC
[...]
----
. 销毁磁盘：
+
`storage encryption disk destroy -disk disk_id`

+
有关完整的命令语法，请参见手册页。

+
[NOTE]
====
系统将提示您输入确认短语，然后再继续。输入屏幕上所示的短语。

====
+
[listing]
----
cluster1::> storage encryption disk destroy -disk 1.10.2

Warning: This operation will cryptographically destroy 1 spare or broken
         self-encrypting disks on 1 node.
         You cannot reuse destroyed disks unless you revert
         them to their original state using the PSID value.
         To continue, enter
          destroy disk
         :destroy disk

Info: Starting destroy on 1 disk.
      View the status of the operation by using the
      "storage encryption disk show-status" command.
----




== 对 FIPS 驱动器或 SED 上的数据进行紧急粉碎

在发生安全紧急情况时，您可以立即阻止访问 FIPS 驱动器或 SED ，即使存储系统或 KMIP 服务器没有电源也是如此。

.您需要的内容
* 如果您使用的 KMIP 服务器没有电源，则必须为 KMIP 服务器配置一个易于销毁的身份验证项（例如，智能卡或 USB 驱动器）。
* 您必须是集群管理员才能执行此任务。


.步骤
. 对 FIPS 驱动器或 SED 上的数据执行紧急粉碎：
+
|===


| 条件 2+| 那么 ... 


 a| 
存储系统已通电，您有时间使存储系统正常脱机
 a| 
.. 如果存储系统配置为 HA 对，请禁用接管。
.. 使所有聚合脱机并将其删除。
.. 将权限级别设置为高级：
 +
`set -privilege advanced`
.. 如果驱动器处于 FIPS 兼容模式，请将节点的 FIPS 身份验证密钥 ID 重新设置为默认 MSID ：
 +
`storage encryption disk modify -disk * -fips-key-id 0x0`
.. 暂停存储系统。
.. 启动至维护模式：
.. 清理或销毁磁盘：
+
*** 如果要使磁盘上的数据无法访问、并且仍然能够重复使用这些磁盘、请清理这些磁盘：
 +
`disk encrypt sanitize -all`
*** 如果要使磁盘上的数据无法访问、并且不需要保存磁盘、请销毁磁盘：
 +
`disk encrypt destroy disk_id1 disk_id2 …`


+
[NOTE]
====
。 `disk encrypt sanitize` 和 `disk encrypt destroy` 命令仅保留用于维护模式。这些命令必须在每个 HA 节点上运行，并且不适用于损坏的磁盘。

====
.. 对配对节点重复上述步骤。
这会使存储系统处于永久禁用状态，并擦除所有数据。要再次使用系统，必须重新配置它。




 a| 
存储系统已通电，您必须立即粉碎数据
 a| 
.. * 如果要使磁盘上的数据无法访问且仍能重复使用这些磁盘，请清理磁盘： *
.. 如果存储系统配置为 HA 对，请禁用接管。
.. 将权限级别设置为高级：
+
`set -privilege advanced`

.. 如果驱动器处于 FIPS 兼容模式，请将节点的 FIPS 身份验证密钥 ID 重新设置为默认 MSID ：
+
`storage encryption disk modify -disk * -fips-key-id 0x0`

.. 清理磁盘：
+
`storage encryption disk sanitize -disk * -force-all-states true`


 a| 
.. * 如果要使磁盘上的数据无法访问，并且不需要保存磁盘，请销毁磁盘： *
.. 如果存储系统配置为 HA 对，请禁用接管。
.. 将权限级别设置为高级：
+
`set -privilege advanced`

.. 销毁磁盘：
`storage encryption disk destroy -disk * -force-all-states true`




 a| 
存储系统崩溃，使系统处于永久禁用状态，并擦除所有数据。要再次使用系统，必须重新配置它。



 a| 
KMIP 服务器可以通电，但存储系统不能通电
 a| 
.. 登录到KMIP服务器。
.. 销毁与包含要阻止访问的数据的 FIPS 驱动器或 SED 关联的所有密钥。
这样会阻止存储系统访问磁盘加密密钥。




 a| 
KMIP 服务器或存储系统不能通电
 a| 
销毁 KMIP 服务器的身份验证项（例如智能卡）。这样会阻止存储系统访问磁盘加密密钥。

|===
+
有关完整的命令语法，请参见手册页。


