---
permalink: encryption-at-rest/destroy-nse-disks-task.html 
sidebar: sidebar 
keywords: fips, drive, sed, inaccessible, destroy, psid, physical secure ID, nrd plus, encrypt, 
summary: '如果要使FIPS驱动器或SED上的数据永久不可访问、并且不需要重复使用该驱动器、则可以使用 `storage encryption disk destroy` 命令销毁磁盘。' 
---
= 销毁ONTAP中的FIPS驱动器或SED
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果要使FIPS驱动器或SED上的数据永久不可访问、并且不需要重复使用该驱动器、则可以使用 `storage encryption disk destroy` 命令销毁磁盘。

.关于此任务
销毁 FIPS 驱动器或 SED 后，系统会将磁盘加密密钥设置为未知的随机值，并永久锁定该驱动器。这样做会使磁盘几乎不可用，并且磁盘上的数据永远不可访问。但是，您可以使用磁盘标签上印有的物理安全 ID （ PSID ）将磁盘重置为出厂配置的设置。有关详细信息，请参见 link:return-self-encrypting-disks-keys-not-available-task.html["丢失身份验证密钥后，使 FIPS 驱动器或 SED 恢复正常运行"]。


NOTE: 除非您拥有不可退回的磁盘加载服务（ NRD Plus ），否则不应销毁 FIPS 驱动器或 SED 。销毁磁盘将使其保修失效。

.开始之前
您必须是集群管理员才能执行此任务。

.步骤
. 将需要保留的所有数据迁移到另一个磁盘上的聚合。
. 删除要销毁的 FIPS 驱动器或 SED 上的聚合：
+
`storage aggregate delete -aggregate aggregate_name`

+
[listing]
----
cluster1::> storage aggregate delete -aggregate aggr1
----
+
有关的详细信息 `storage aggregate delete`，请参见link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-delete.html["ONTAP 命令参考"^]。

. 确定要销毁的 FIPS 驱动器或 SED 的磁盘 ID ：
+
`storage encryption disk show`

+
有关的详细信息 `storage encryption disk show`，请参见link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-show.html["ONTAP 命令参考"^]。

+
[listing]
----
cluster1::> storage encryption disk show
Disk    Mode Data Key ID
-----   ---- ----------------------------------------------------------------
0.0.0   data <id_value>
0.0.1   data <id_value>
1.10.2  data <id_value>
[...]
----
. 销毁磁盘：
+
`storage encryption disk destroy -disk disk_id`

+
有关的详细信息 `storage encryption disk destroy`，请参见link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-destroy.html["ONTAP 命令参考"^]。

+
[NOTE]
====
系统将提示您输入确认短语，然后再继续。输入屏幕上所示的短语。

====
+
[listing]
----
cluster1::> storage encryption disk destroy -disk 1.10.2

Warning: This operation will cryptographically destroy 1 spare or broken
         self-encrypting disks on 1 node.
         You cannot reuse destroyed disks unless you revert
         them to their original state using the PSID value.
         To continue, enter
          destroy disk
         :destroy disk

Info: Starting destroy on 1 disk.
      View the status of the operation by using the
      "storage encryption disk show-status" command.
----

