---
permalink: encryption-at-rest/emergency-shred-data-disks-storage-encryption-task.html 
sidebar: sidebar 
keywords: emergency, shred, data, fips, drive, sed, disk encrypt sanitize, disk encrypt destroy 
summary: 在发生安全紧急情况时，您可以立即阻止访问 FIPS 驱动器或 SED ，即使存储系统或 KMIP 服务器没有电源也是如此。 
---
= 对 FIPS 驱动器或 SED 上的数据进行紧急粉碎
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在发生安全紧急情况时，您可以立即阻止访问 FIPS 驱动器或 SED ，即使存储系统或 KMIP 服务器没有电源也是如此。

.您需要什么？ #8217 ；将需要什么
* 如果您使用的 KMIP 服务器没有电源，则必须为 KMIP 服务器配置一个易于销毁的身份验证项（例如，智能卡或 USB 驱动器）。
* 您必须是集群管理员才能执行此任务。


.步骤
. 对 FIPS 驱动器或 SED 上的数据执行紧急粉碎：
+
|===


| 条件 2+| 那么 ... 


 a| 
存储系统已通电，您有时间使存储系统正常脱机
 a| 
.. 如果存储系统配置为 HA 对，请禁用接管。
.. 使所有聚合脱机并将其删除。
.. 将权限级别设置为 advanced ： + `set -privilege advanced`
.. 如果驱动器处于 FIPS 兼容模式，请将节点的 FIPS 身份验证密钥 ID 重新设置为默认 MSID ： + `s存储加密磁盘修改 -disk * -fips-key-id 0x0`
.. 暂停存储系统。
.. 启动至维护模式：
.. 清理或销毁磁盘：
+
*** 如果要使磁盘上的数据无法访问且仍能重复使用这些磁盘，请清理磁盘： + `disk encrypt sanitize -all`
*** 如果您要使磁盘上的数据无法访问，并且不需要保存磁盘，请销毁磁盘： + `disk encrypt destroy disk_ID1 disk_ID2 …`


+
[NOTE]
====
`dencrypt sanitize` 和 `disk encrypt destroy` 命令仅保留用于维护模式。这些命令必须在每个 HA 节点上运行，并且不适用于损坏的磁盘。

====
.. 对配对节点重复上述步骤。这会使存储系统处于永久禁用状态，并擦除所有数据。要再次使用系统，必须重新配置它。




 a| 
存储系统已通电，您必须立即粉碎数据
 a| 
.. * 如果要使磁盘上的数据无法访问且仍能重复使用这些磁盘，请清理磁盘： *
.. 如果存储系统配置为 HA 对，请禁用接管。
.. 将权限级别设置为高级：
+
`set -privilege advanced`

.. 如果驱动器处于 FIPS 兼容模式，请将节点的 FIPS 身份验证密钥 ID 重新设置为默认 MSID ：
+
`storage encryption disk modify -disk * -fips-key-id 0x0`

.. 清理磁盘：
+
`s存储加密磁盘清理 -disk * -force-all-states true`


 a| 
.. * 如果要使磁盘上的数据无法访问，并且不需要保存磁盘，请销毁磁盘： *
.. 如果存储系统配置为 HA 对，请禁用接管。
.. 将权限级别设置为高级：
+
`set -privilege advanced`

.. 销毁磁盘： `s存储加密磁盘销毁 -disk * -force-all-states true`




 a| 
存储系统崩溃，使系统处于永久禁用状态，并擦除所有数据。要再次使用系统，必须重新配置它。



 a| 
KMIP 服务器可以通电，但存储系统不能通电
 a| 
.. 登录到 KMIP 服务器。
.. 销毁与包含要阻止访问的数据的 FIPS 驱动器或 SED 关联的所有密钥。这样会阻止存储系统访问磁盘加密密钥。




 a| 
KMIP 服务器或存储系统不能通电
 a| 
销毁 KMIP 服务器的身份验证项（例如智能卡）。这样会阻止存储系统访问磁盘加密密钥。

|===
+
有关完整的命令语法，请参见手册页。


