---
permalink: encryption-at-rest/enable-exernal-key-management-95-earlier-hw-task.html 
sidebar: sidebar 
keywords: enabling, external key management, ontap 9.5, earlier 
summary: 您可以使用一个或多个 KMIP 服务器来保护集群用于访问加密数据的密钥。最多可以将四个 KMIP 服务器连接到一个节点。建议至少使用两台服务器来实现冗余和灾难恢复。 
---
= 在ONTAP 9 5及更早版本中启用外部密钥管理(基于硬件)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用一个或多个 KMIP 服务器来保护集群用于访问加密数据的密钥。最多可以将四个 KMIP 服务器连接到一个节点。建议至少使用两台服务器来实现冗余和灾难恢复。

.关于此任务
ONTAP 为集群中的所有节点配置 KMIP 服务器连接。

.开始之前
* 必须已安装 KMIP SSL 客户端和服务器证书。
* 您必须是集群管理员才能执行此任务。
* 在配置外部密钥管理器之前，您必须配置 MetroCluster 环境。
* 在MetroCluster环境中、您必须在两个集群上安装相同的KMIP SSL证书。


.步骤
. 为集群节点配置密钥管理器连接：
+
`security key-manager setup`

+
此时将启动密钥管理器设置。

+

NOTE: 在MetroCluster 环境中、必须在两个集群上运行此命令。

. 在每个提示符处输入相应的响应。
. 添加 KMIP 服务器：
+
`security key-manager add -address key_management_server_ipaddress`

+
[listing]
----
clusterl::> security key-manager add -address 20.1.1.1
----
+

NOTE: 在MetroCluster 环境中、必须在两个集群上运行此命令。

. 添加额外的 KMIP 服务器以实现冗余：
+
`security key-manager add -address key_management_server_ipaddress`

+
[listing]
----
clusterl::> security key-manager add -address 20.1.1.2
----
+

NOTE: 在MetroCluster 环境中、必须在两个集群上运行此命令。

. 验证所有已配置的 KMIP 服务器是否均已连接：
+
`security key-manager show -status`

+
有关此过程中所述命令的更多信息，请参见link:https://docs.netapp.com/us-en/ontap-cli/["ONTAP 命令参考"^]。

+
[listing]
----
cluster1::> security key-manager show -status

Node            Port      Registered Key Manager  Status
--------------  ----      ----------------------  ---------------
cluster1-01     5696      20.1.1.1                available
cluster1-01     5696      20.1.1.2                available
cluster1-02     5696      20.1.1.1                available
cluster1-02     5696      20.1.1.2                available
----
. (可选)将纯文本卷转换为加密卷。
+
`volume encryption conversion start`

+
转换卷之前、必须完全配置外部密钥管理器。在MetroCluster环境中、必须同时在两个站点上配置外部密钥管理器。


