---
permalink: encryption-at-rest/enable-encryption-new-volume-task.html 
sidebar: sidebar 
keywords: encryption, new volume, NAE, NVE, volume create 
summary: 您可以使用 volume create 命令对新卷启用加密。 
---
= 在新卷上启用加密
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `volume create` 命令以对新卷启用加密。

.关于此任务
您可以使用NetApp卷加密(NVE)对卷进行加密、从ONTAP 9.6开始、还可以使用NetApp聚合加密(NAE)对卷进行加密。要了解有关NAE和NVE的更多信息、请参见 xref:configure-netapp-volume-encryption-concept.html[卷加密概述]。

在ONTAP 中为新卷启用加密的操作步骤 会根据您使用的ONTAP 版本和特定配置而有所不同：

* 从ONTAP 9.4开始、如果您启用了 `cc-mode` 设置板载密钥管理器时、您使用创建的卷 `volume create` 无论是否指定、命令都会自动加密 `-encrypt true`。
* 在ONTAP 9.6及更早版本中、您必须使用 `-encrypt true` 使用 `volume create` 用于启用加密的命令(前提是您未启用 `cc-mode`）。
* 如果要在ONTAP 9.6中创建NAE卷、则必须在聚合级别启用NAE。请参见 xref:enable-aggregate-level-encryption-nve-license-task.html[使用VE许可证启用聚合级别加密] 了解有关此任务的更多详细信息。
* 从ONTAP 9.7开始、如果具有、则新创建的卷会默认进行加密 link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/install-license-task.html["VE许可证"] 以及板载或外部密钥管理。默认情况下、在NAE聚合中创建的新卷的类型为NAE、而不是NVE。
+
** 在ONTAP 9.7及更高版本中、如果您添加了 `-encrypt true` 到 `volume create` 命令要在NAE聚合中创建卷、此卷将采用NVE加密、而不是NAE加密。NAE聚合中的所有卷都必须使用NVE或NAE进行加密。





NOTE: NAE 聚合不支持纯文本卷。

.步骤
. 创建新卷并指定是否在卷上启用加密。如果新卷位于NAE聚合中、则默认情况下、此卷将为NAE卷：
+
[cols="25,75"]
|===


| 要创建 ... | 使用此命令 ... 


 a| 
NAE卷
 a| 
`volume create -vserver _SVM_name_ -volume _volume_name_ -aggregate _aggregate_name_`



 a| 
NVE卷
 a| 
`volume create -vserver _SVM_name_ -volume _volume_name_ -aggregate _aggregate_name_ -encrypt true` +


NOTE: 在不支持NAE的ONTAP 9.6及更早版本中、 `-encrypt true` 指定应使用NVE对卷进行加密。在ONTAP 9.7及更高版本中、如果在NAE聚合中创建卷、 `-encrypt true` 覆盖默认的NAE加密类型以创建NVE卷。



 a| 
纯文本卷
 a| 
`volume create -vserver _SVM_name_ -volume _volume_name_ -aggregate _aggregate_name_ -encrypt false`

|===
+
有关完整的命令语法、请参见命令参考页面上的链接：https://docs.netapp.com/us-en/ontap-cli/volume-create.html[`volume create`^。

. 验证是否已为卷启用加密：
+
`volume show -is-encrypted true`

+
有关完整的命令语法，请参见 link:https://docs.netapp.com/us-en/ontap-cli/volume-show.html["ONTAP 命令参考"^]。



.结果
如果使用KMIP服务器存储节点的加密密钥、则在对卷进行加密时、ONTAP 会自动将加密密钥"推送"到服务器。
