---
permalink: encryption-at-rest/enable-cluster-fips-compliant-mode-task.html 
sidebar: sidebar 
keywords: enabling, cluster-wide, fips-compliant mode, kmip, server, connections 
summary: 您可以将 security config modify 命令与 -is-fips-enabled 选项结合使用，以便为传输中的数据启用集群范围 FIPS 兼容模式。这样做会强制集群在连接到 KMIP 服务器时在 FIPS 模式下使用 OpenSSL 。 
---
= 为 KMIP 服务器连接启用集群范围 FIPS 兼容模式
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `security config modify` 命令和 -`is-fips-enabled` 选项为传输中的数据启用集群范围 FIPS 兼容模式。这样做会强制集群在连接到 KMIP 服务器时在 FIPS 模式下使用 OpenSSL 。

.开始之前
* 存储控制器必须配置为 FIPS 兼容模式。
* 所有 KMIP 服务器都必须支持 TLSv1.2 。启用集群范围 FIPS 兼容模式后，系统需要使用 TLSv1.2 完成与 KMIP 服务器的连接。


启用集群范围 FIPS 兼容模式后，集群将仅自动使用 TLS1.2 和 FIPS 验证的密码套件。默认情况下，集群范围 FIPS 兼容模式处于禁用状态。

修改集群范围的安全配置后，您必须手动重新启动集群节点。



== ONTAP 9.11.1RC1注意事项

由于ONTAP 9.11.1RC1的更改、FIPS 140-2合规性管理模式不再使用经过FIPS 140-2验证的软件模块。

ONTAP 9.11.1RC1升级了用于HTTPS管理和控制平面连接的OpenSSL版本。此版本的OpenSSL (OpenSSL 3.x FIPS提供程序)尚未完成FIPS 140-2加密模块验证计划(CMVP)验证过程。

启用FIPS兼容模式后、用于HTTPS连接的加密算法与加密算法验证计划(CAVP)证书A1938中发布的OpenSSL Project OpenSSL 3.x FIPS提供程序算法相同。*此更改仅影响在FIPS兼容模式下配置的ONTAP 系统。*

一旦ONTAP 9.11.1RC1中已升级的OpenSSL模块通过NIST完成FIPS 140-2验证、此问题描述 将得到修复。如果您的环境要求使用已通过FIPS 140-2 CMVP验证的模块运行ONTAP 集群管理控制平面、则建议不要升级到9.11.1RC1。

这不会影响NSE、NVE和NAE等NetApp空闲加密技术、因为这些功能使用的加密模块与ONTAP 中的OpenSSL提供的加密模块不同。

有关详细信息，请参见 link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Upgrading_to_ONTAP_9.11.1RC1_results_in_FIPS_140-2_compliance_management_configuration_that_is_not_validated["升级到ONTAP 9.11.1RC1会导致FIPS 140-2合规性管理配置未经过验证"^]

.步骤
. 将权限级别设置为高级：
+
`set -privilege advanced`

. 验证是否支持 TLSv1.2 ：
+
`ssecurityconfig show -supported protocols`

+
有关完整的命令语法，请参见手册页。

+
[listing]
----
cluster1::> security config show
          Cluster                                              Cluster Security
Interface FIPS Mode  Supported Protocols     Supported Ciphers Config Ready
--------- ---------- ----------------------- ----------------- ----------------
SSL       false      TLSv1.2, TLSv1.1, TLSv1 ALL:!LOW:         yes
                                             !aNULL:!EXP:
                                             !eNULL
----
. 启用集群范围 FIPS 兼容模式：
+
`security config modify -is-fips-enabled true -interface ssl`

+
有关完整的命令语法，请参见手册页。

. 手动重新启动集群节点。
. 验证是否已启用集群范围 FIPS 兼容模式：
+
`s安全性配置显示`

+
[listing]
----
cluster1::> security config show
          Cluster                                              Cluster Security
Interface FIPS Mode  Supported Protocols     Supported Ciphers Config Ready
--------- ---------- ----------------------- ----------------- ----------------
SSL       true       TLSv1.2, TLSv1.1        ALL:!LOW:         yes
                                             !aNULL:!EXP:
                                             !eNULL:!RC4
----

