---
permalink: encryption-at-rest/install-ssl-certificates-task.html 
sidebar: sidebar 
keywords: install, ssl, certificates, cluster 
summary: 集群和 KMIP 服务器使用 KMIP SSL 证书来验证彼此的身份并建立 SSL 连接。在配置与 KMIP 服务器的 SSL 连接之前，必须为集群安装 KMIP 客户端 SSL 证书，并为 KMIP 服务器的根证书颁发机构（ CA ）安装 SSL 公有证书。 
---
= 在集群上安装 SSL 证书
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
集群和 KMIP 服务器使用 KMIP SSL 证书来验证彼此的身份并建立 SSL 连接。在配置与 KMIP 服务器的 SSL 连接之前，必须为集群安装 KMIP 客户端 SSL 证书，并为 KMIP 服务器的根证书颁发机构（ CA ）安装 SSL 公有证书。

.您需要的内容
* 创建证书的服务器， KMIP 服务器和集群上的时间必须同步。
* 您必须已获取集群的公有 SSL KMIP 客户端证书。
* 您必须已获取与集群的 SSL KMIP 客户端证书关联的专用密钥。
+
SSL KMIP 客户端证书不能受密码保护。

* 您必须已为 KMIP 服务器的根证书颁发机构（ CA ）获取 SSL 公有证书。
* 在MetroCluster 环境中、必须在两个集群上安装KMIP SSL证书。


[NOTE]
====
在集群上安装客户端和服务器证书之前或之后，您可以在 KMIP 服务器上安装这些证书。

====
.关于此任务
在 HA 对中，两个节点必须使用相同的公有和专用 KMIP SSL 证书。如果将多个 HA 对连接到同一个 KMIP 服务器，则 HA 对中的所有节点都必须使用相同的公有和专用 KMIP SSL 证书。

.步骤
. 为集群安装 SSL KMIP 客户端证书：
+
`security certificate install -vserver admin_svm_name -type client`

+
系统将提示您输入 SSL KMIP 公有和专用证书。

+
`cluster1 ：：： > security certificate install -vserver cluster1 -type client`

. 为 KMIP 服务器的根证书颁发机构（ CA ）安装 SSL 公有证书：
+
`security certificate install -vserver admin_svm_name -type server-ca`

+
`cluster1 ：：： > security certificate install -vserver cluster1 -type server-ca`


