---
permalink: encryption-at-rest/manage-keys-azure-google-task.html 
sidebar: sidebar 
keywords: Azure, AKV, key vault, NVE keys, third-party, GCP, google cloud, Cloud KMS, AWS, amazon 
summary: 使用Azure、Google Cloud或AWS密钥管理器简化对ONTAP加密密钥的保护。 
---
= 通过云提供商管理ONTAP数据 SVM 的 NVE 密钥
:allow-uri-read: 


[role="lead"]
从ONTAP 9.10.1开始、您可以在云托管应用程序中使用link:https://docs.microsoft.com/en-us/azure/key-vault/general/basic-concepts["Azure 密钥存储（ AKV ）"^]和link:https://cloud.google.com/kms/docs["Google Cloud Platform 的密钥管理服务（ Cloud KMS ）"^]保护ONTAP加密密钥。从ONTAP 9.12.0开始，您还可以使用保护NVE密钥link:https://docs.aws.amazon.com/kms/latest/developerguide/overview.html["AWS的KMS"^]。

AWS KMS、AKV和Cloud KMS可用于保护 link:configure-netapp-volume-encryption-concept.html["NetApp 卷加密（ NVE ）密钥"] 仅适用于数据SVM。

.关于此任务
可以使用命令行界面或ONTAP REST API启用云提供程序的密钥管理。

在使用云提供商保护密钥时、请注意、默认情况下、数据SVM LIF用于与云密钥管理端点进行通信。节点管理网络用于与云提供商的身份验证服务进行通信（适用于 Azure 的 login.microsoftonline.com ；适用于 Cloud KMS 的 oauth2.googleapis.com ）。如果集群网络配置不正确、集群将无法正确使用密钥管理服务。

在使用云提供商密钥管理服务时、您应注意以下限制：

* 云提供商密钥管理不适用于NetApp存储加密(NSE)和NetApp聚合加密(NAE)。 link:enable-external-key-management-96-later-nve-task.html["外部 KMIP"] 可以改为使用。
* 云提供商密钥管理不适用于MetroCluster配置。
* 只能在数据SVM上配置云提供程序密钥管理。


.开始之前
* 您必须已在相应的云提供程序上配置KMS。
* ONTAP集群的节点必须支持NVE。
* link:../encryption-at-rest/install-license-task.html["您必须已安装卷加密(VE)和多租户加密密钥管理(MTEKM)许可证"](英文)这些许可证包含在中link:../system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP One"]。
* 您必须是集群或SVM管理员。
* 数据SVM不能包含任何加密卷、也不能使用密钥管理器。如果数据SVM包含加密卷、则必须先迁移这些卷、然后再配置KMS。




== 启用外部密钥管理

启用外部密钥管理取决于您使用的特定密钥管理器。选择相应密钥管理器和环境的选项卡。

[role="tabbed-block"]
====
.AWS
--
.开始之前
* 您必须为管理加密的IAM角色要使用的AWS KMS密钥创建授权。IAM角色必须包含一个允许执行以下操作的策略：
+
** `DescribeKey`
** `Encrypt`
** `Decrypt`
+
有关详细信息、请参见的AWS文档 link:https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html#grant["赠款"^]。




.在ONTAP SVM上启用AWS KMV
. 开始之前、请从AWS KMS获取访问密钥ID和机密密钥。
. 将权限级别设置为高级：
`set -priv advanced`
. 启用AWS KMS：
`security key-manager external aws enable -vserver _svm_name_ -region _AWS_region_ -key-id _key_ID_ -encryption-context _encryption_context_`
. 出现提示时、输入机密密钥。
. 确认已正确配置AWS KMS：
`security key-manager external aws show -vserver _svm_name_`
+
有关的详细信息 `security key-manager external aws`，请参见link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+key-manager+external+aws["ONTAP 命令参考"^]。



--
.Azure 酒店
--
.在ONTAP SVM上启用Azure密钥存储
. 开始之前，您需要从 Azure 帐户获取适当的身份验证凭据，即客户端密钥或证书。此外，还必须确保集群中的所有节点运行状况良好。您可以使用命令来检查此情况 `cluster show`。有关的详细信息 `cluster show`，请参见link:https://docs.netapp.com/us-en/ontap-cli/cluster-show.html["ONTAP 命令参考"^]。
. 将权限级别设置为高级
`set -priv advanced`
. 在SVM上启用AKV
`security key-manager external azure enable -client-id _client_id_ -tenant-id _tenant_id_ -name -key-id _key_id_ -authentication-method {certificate|client-secret}`
出现提示时，输入 Azure 帐户的客户端证书或客户端密钥。
. 验证是否已正确启用AKV：
`security key-manager external azure show vserver _svm_name_`
如果服务可访问性不正常、请通过数据SVM LIF建立与AKV密钥管理服务的连接。
+
有关的详细信息 `security key-manager external azure`，请参见link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+key-manager+external+azure["ONTAP 命令参考"^]。



--
.Google Cloud
--
.在ONTAP SVM上启用云KMS
. 开始之前、请以JSON格式获取Google Cloud KMS帐户密钥文件的专用密钥。您可以在 GCP 帐户中找到此信息。此外，还必须确保集群中的所有节点运行状况良好。您可以使用命令来检查此情况 `cluster show`。有关的详细信息 `cluster show`，请参见link:https://docs.netapp.com/us-en/ontap-cli/cluster-show.html["ONTAP 命令参考"^]。
. 将权限级别设置为高级：
`set -priv advanced`
. 在SVM上启用Cloud KMS
`security key-manager external gcp enable -vserver _svm_name_ -project-id _project_id_-key-ring-name _key_ring_name_ -key-ring-location _key_ring_location_ -key-name _key_name_`
出现提示时，使用服务帐户专用密钥输入 JSON 文件的内容
. 验证Cloud KMS是否配置了正确的参数：
`security key-manager external gcp show vserver _svm_name_`
的状态 `kms_wrapped_key_status` 将是 `“UNKNOWN”` 如果尚未创建加密卷。
如果服务可访问性不正常、请通过数据SVM LIF与GCP密钥管理服务建立连接。
+
有关的详细信息 `security key-manager external gcp`，请参见link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+key-manager+external+gcp["ONTAP 命令参考"^]。



--
====
如果已为数据SVM配置一个或多个加密卷、并且相应的NVE密钥由管理SVM板载密钥管理器管理、则这些密钥应迁移到外部密钥管理服务。要使用命令行界面执行此操作、请运行以下命令：
`security key-manager key migrate -from-Vserver _admin_SVM_ -to-Vserver _data_SVM_`
只有在成功迁移数据SVM的所有NVE密钥之后、才能为租户的数据SVM创建新的加密卷。

.相关信息
* link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-encrypting-volumes.html["使用适用于Cloud Volumes ONTAP的NetApp加密解决方案加密卷"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+key-manager+external+["安全密钥管理器外部"^]

