---
permalink: encryption-at-rest/modify-external-key-server-96-later-task.html 
sidebar: sidebar 
keywords: modifying, external key management, server, properties 
summary: 从 ONTAP 9.6 开始，您可以使用 security key-manager external modify-server 命令更改外部密钥管理服务器的 I/O 超时和用户名。 
---
= 修改ONTAP外部密钥管理服务器属性
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
从ONTAP 9.6开始、您可以使用 `security key-manager external modify-server` 用于更改外部密钥管理服务器的I/O超时和用户名的命令。

.开始之前
* 要执行此任务，您必须是集群或 SVM 管理员。
* 此任务需要高级权限。
* 在MetroCluster 环境中、必须对管理SVM的两个集群重复这些步骤。


.步骤
. 在存储系统上，更改为高级权限级别：
+
`set -privilege advanced`

. 修改集群的外部密钥管理器服务器属性：
+
`security key-manager external modify-server -vserver admin_SVM -key-server host_name|IP_address:port,... -timeout 1...60 -username user_name`

+
[NOTE]
====
超时值以秒为单位。如果您修改了用户名，系统将提示您输入新密码。    如果在集群登录提示符处运行命令、 `_admin_SVM_` 默认为当前集群的管理SVM。您必须是集群管理员才能修改外部密钥管理器服务器属性。

====
+
以下命令会将的超时值更改为45秒 `cluster1` 侦听默认端口5696的外部密钥管理服务器：

+
[listing]
----
clusterl::> security key-manager external modify-server -vserver cluster1 -key-server ks1.local -timeout 45
----
. 修改 SVM 的外部密钥管理器服务器属性（仅限 NVE ）：
+
`security key-manager external modify-server -vserver SVM -key-server host_name|IP_address:port,... -timeout 1...60 -username user_name`

+
[NOTE]
====
超时值以秒为单位。如果您修改了用户名，系统将提示您输入新密码。    如果在SVM登录提示符处运行命令、 `_SVM_` 默认为当前SVM。您必须是集群或 SVM 管理员才能修改外部密钥管理器服务器属性。

====
+
以下命令将更改的用户名和密码 `svm1` 侦听默认端口5696的外部密钥管理服务器：

+
[listing]
----
svml::> security key-manager external modify-server -vserver svm11 -key-server ks1.local -username svm1user
Enter the password:
Reenter the password:
----
. 对任何其他 SVM 重复最后一步。


.相关信息
* link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-external-modify-server.html["security key-manager外部modify-server"^]

