---
permalink: encryption-at-rest/purge-data-encrypted-volume-synchronous-snapmirror-task.html 
sidebar: sidebar 
keywords: secure, purge, scrub, data, encrypted, volume, nve, netapp, volume encryption, snapmirror, synchronous 
summary: '从 ONTAP 9.8 开始，您可以使用安全清除功能在具有同步 SnapMirror 关系且已启用 NVE 的卷上无中断地 " 擦除 " 数据。' 
---
= 擦除具有同步 SnapMirror 关系的加密卷上的数据
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
从 ONTAP 9.8 开始，您可以使用安全清除功能在具有同步 SnapMirror 关系且已启用 NVE 的卷上无中断地传输 " `scrub` " 数据。

.您需要的内容
* 您必须是集群管理员才能执行此任务。
* 此任务需要高级权限。


.关于此任务
安全清除可能需要几分钟到几小时才能完成，具体取决于已删除文件中的数据量。您可以使用 `volume encryption secure-purge show` 命令以查看操作状态。您可以使用 `volume encryption secure-purge abort` 命令以终止操作。

[NOTE]
====
要在 SAN 主机上执行安全清除，您必须删除包含要清除的文件的整个 LUN ，或者您必须能够在 LUN 中为属于要清除的文件的块打孔。如果无法删除 LUN ，或者主机操作系统不支持 LUN 中的打孔，则无法执行安全清除。

====
.步骤
. 在存储系统上，更改为高级权限级别：
+
`set -privilege advanced`

. 删除要安全清除的文件或 LUN 。
+
** 在 NAS 客户端上，删除要安全清除的文件。
** 在 SAN 主机上，删除要安全清除的 LUN ，或者为要清除的文件中的块打孔。


. 准备异步关系中要安全清除的目标卷：
+
`volume encryption secure-purge start -vserver SVM_name -volume volume_name -prepare true`

+
对同步 SnapMirror 关系中的另一个卷重复此步骤。

. 如果要安全清除的文件位于 Snapshot 副本中，请删除 Snapshot 副本：
+
`snapshot delete -vserver SVM_name -volume vol_A -snapshot snapshot`

. 如果安全清除文件位于基本 Snapshot 副本或通用 Snapshot 副本中，请更新 SnapMirror 以将通用 Snapshot 副本前移：
+
`snapmirror update -source-snapshot snapshot_name -destination-path destination_path`

+
有两个通用 Snapshot 副本，因此必须发出此命令两次。

. 如果安全清除文件位于应用程序一致的 Snapshot 副本中，请删除同步 SnapMirror 关系中两个卷上的 Snapshot 副本：
+
`snapshot delete -vserver SVM_name -volume vol_name -snapshot snapshot`

+
对两个卷执行此步骤。

. 安全清除已删除的文件：
+
`volume encryption secure-purge start -vserver SVM_name -volume volume_name`

+
对同步 SnapMirror 关系中的每个卷重复此步骤。

+
以下命令可安全清除 SMV"`vs1` " 上 "`vol1` " 上已删除的文件。

+
[listing]
----
cluster1::> volume encryption secure-purge start -vserver vs1 -volume vol1
----
. 验证安全清除操作的状态：
+
`volume encryption secure-purge show`


