---
permalink: encryption-at-rest/purge-data-encrypted-volume-without-snapmirror-task.html 
sidebar: sidebar 
keywords: secure, purge, scrub, data, encrypted, volume, nve, netapp, volume, encryption, snapmirror 
summary: '从 ONTAP 9.4 开始，您可以使用安全清除功能在启用了 NVE 的卷上无中断地 " 擦除 " 数据。' 
---
= 安全地清除加密卷上的数据，而不存在 SnapMirror 关系
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
从 ONTAP 9.4 开始，您可以使用安全清除功能在启用了 NVE 的卷上无中断地生成 " `scrub` " 数据。

.您需要什么？ #8217 ；将需要什么
* 您必须是集群管理员才能执行此任务。
* 此任务需要高级权限。


完成安全清除可能需要几分钟到数小时，具体取决于已删除文件中的数据量。您可以使用 `volume encryption secure — purge show` 命令查看操作状态。您可以使用 `volume encryption secure — purge abort` 命令终止此操作。

[NOTE]
====
要在 SAN 主机上执行安全清除，您必须删除包含要清除的文件的整个 LUN ，或者您必须能够在 LUN 中为属于要清除的文件的块打孔。如果无法删除 LUN ，或者主机操作系统不支持 LUN 中的打孔，则无法执行安全清除。

====
.步骤
. 删除要安全清除的文件或 LUN 。
+
** 在 NAS 客户端上，删除要安全清除的文件。
** 在 SAN 主机上，删除要安全清除的 LUN ，或者为要清除的文件中的块打孔。


. 在存储系统上，更改为高级权限级别：
+
`set -privilege advanced`

. 如果要安全清除的文件位于快照中，请删除这些快照：
+
`snapshot delete -vserver svm_name -volume vol_name -snapshot`

. 安全清除已删除的文件：
+
`volume encryption sure-purge start -vserver svm_name -volume volume_name`

+
以下命令可安全清除 SVM``vs1`` 上的 `vol1` 上的已删除文件：

+
[listing]
----
cluster1::> volume encryption secure-purge start -vserver vs1 -volume vol1
----
. 验证安全清除操作的状态：
+
`volume encryption secure — purge show`


