---
permalink: encryption-at-rest/purge-data-encrypted-asynchronous-snapmirror-task.html 
sidebar: sidebar 
keywords: securely, purging, scrub, data, encrypted, volume, nve, netapp, volume encryption, snapmirror, asynchronous 
summary: '从NVE.8开始、您可以使用安全清除功能在具有SnapMirror异步关系且已启用ONTAP 9的卷上无故障"擦除"数据。' 
---
= 从具有SnapMirror异步关系的加密ONTAP卷中清理数据
:allow-uri-read: 


[role="lead"]
从NVE.8开始、您可以对具有SnapMirror异步关系且已启用ONTAP 9的卷上无故障的"`scrub`"数据使用安全清除。

.开始之前
* 您必须是集群管理员才能执行此任务。
* 此任务需要高级权限。


.关于此任务
完成安全清除可能需要几分钟到数小时，具体取决于已删除文件中的数据量。您可以使用 `volume encryption secure-purge show` 命令以查看操作状态。您可以使用 `volume encryption secure-purge abort` 命令以终止操作。


NOTE: 要在 SAN 主机上执行安全清除，您必须删除包含要清除的文件的整个 LUN ，或者您必须能够在 LUN 中为属于要清除的文件的块打孔。如果无法删除 LUN ，或者主机操作系统不支持 LUN 中的打孔，则无法执行安全清除。

.步骤
. 在存储系统上、切换到高级权限级别：
+
`set -privilege advanced`

. 删除要安全清除的文件或 LUN 。
+
** 在 NAS 客户端上，删除要安全清除的文件。
** 在 SAN 主机上，删除要安全清除的 LUN ，或者为要清除的文件中的块打孔。


. 准备异步关系中要安全清除的目标卷：
+
`volume encryption secure-purge start -vserver _SVM_name_ -volume _volume_name_ -prepare true`

+
对SnapMirror异步关系中的每个卷重复此步骤。

. 如果要安全清除的文件位于快照中，请删除这些快照：
+
`snapshot delete -vserver _SVM_name_ -volume _volume_name_ -snapshot`

. 如果要安全清除的文件位于基本快照中，请执行以下操作：
+
.. 在SnapMirror异步关系中的目标卷上创建快照：
+
`volume snapshot create -snapshot snapshot_name -vserver _SVM_name_ -volume _volume_name_`

.. 更新SnapMirror以向前移动基本快照：
+
`snapmirror update -source-snapshot _snapshot_name_ -destination-path _destination_path_`

+
对SnapMirror异步关系中的每个卷重复此步骤。

.. 重复步骤（ a ）和（ b ），使其等于基本快照数加 1 。
+
例如，如果您有两个基本快照，则应重复步骤（ a ）和（ b ）三次。

.. 验证是否存在基本快照：+
`snapshot show -vserver _SVM_name_ -volume _volume_name_`
.. 删除基本快照：+
`snapshot delete -vserver _svm_name_ -volume _volume_name_ -snapshot snapshot`


. 安全清除已删除的文件：
+
`volume encryption secure-purge start -vserver _svm_name_ -volume _volume_name_`

+
对SnapMirror异步关系中的每个卷重复此步骤。

+
以下命令可安全清除 SVM "`vs1` " 上 "`vol1` " 上的已删除文件：

+
[listing]
----
cluster1::> volume encryption secure-purge start -vserver vs1 -volume vol1
----
. 验证安全清除操作的状态：
+
`volume encryption secure-purge show`


