---
permalink: encryption-at-rest/purge-data-encrypted-volume-synchronous-snapmirror-task.html 
sidebar: sidebar 
keywords: secure, purge, scrub, data, encrypted, volume, nve, netapp, volume encryption, snapmirror, synchronous 
summary: 从ONTAP 9.8 开始，您可以使用安全清除功能以无中断方式清理具有SnapMirror同步关系的启用 NVE 的卷上的数据。 
---
= 从具有SnapMirror同步关系的加密ONTAP卷中清理数据
:allow-uri-read: 


[role="lead"]
从NVE.8开始、您可以使用安全清除功能无故障"擦除"已启用ONTAP 9且具有SnapMirror同步关系的卷上的数据。

.关于此任务
安全清除可能需要几分钟到几小时才能完成，具体取决于已删除文件中的数据量。您可以使用 `volume encryption secure-purge show` 命令以查看操作状态。您可以使用 `volume encryption secure-purge abort` 命令以终止操作。


NOTE: 要在 SAN 主机上执行安全清除，您必须删除包含要清除的文件的整个 LUN ，或者您必须能够在 LUN 中为属于要清除的文件的块打孔。如果无法删除 LUN ，或者主机操作系统不支持 LUN 中的打孔，则无法执行安全清除。

.开始之前
* 您必须是集群管理员才能执行此任务。
* 此任务需要高级权限。


.步骤
. 在存储系统上，更改为高级权限级别：
+
`set -privilege advanced`

. 删除要安全清除的文件或 LUN 。
+
** 在 NAS 客户端上，删除要安全清除的文件。
** 在 SAN 主机上，删除要安全清除的 LUN ，或者为要清除的文件中的块打孔。


. 准备异步关系中要安全清除的目标卷：
+
`volume encryption secure-purge start -vserver <SVM_name> -volume <volume_name> -prepare true`

+
对SnapMirror同步关系中的另一个卷重复此步骤。

. 如果要安全清除的文件位于快照中，请删除这些快照：
+
`snapshot delete -vserver <SVM_name> -volume <volume_name> -snapshot <snapshot>`

. 如果安全清除文件位于基本快照或通用快照中，请更新 SnapMirror 以将通用快照前移：
+
`snapmirror update -source-snapshot <snapshot_name> -destination-path <destination_path>`

+
有两个常见快照，因此必须发出此命令两次。

. 如果安全清除文件位于应用程序一致的快照中、请删除SnapMirror同步关系中两个卷上的快照：
+
`snapshot delete -vserver <SVM_name> -volume <volume_name> -snapshot <snapshot>`

+
对两个卷执行此步骤。

. 安全清除已删除的文件：
+
`volume encryption secure-purge start -vserver <SVM_name> -volume <volume_name>`

+
对SnapMirror同步关系中的每个卷重复此步骤。

+
以下命令可安全清除SVM"`VS1`"上的"` vol1`"上已删除的文件。

+
[listing]
----
cluster1::> volume encryption secure-purge start -vserver vs1 -volume vol1
----
. 验证安全清除操作的状态：
+
`volume encryption secure-purge show`



.相关信息
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-update.html["snapmirror update"^]

