---
permalink: encryption-at-rest/rekey-encrypted-volume-task.html 
sidebar: sidebar 
keywords: changing, encryption key, volume encryption rekey start, command 
summary: 安全最佳做法是定期更改卷的加密密钥。从 ONTAP 9.3 开始，您可以使用 volume encryption rekey start 命令更改加密密钥。 
---
= 在ONTAP中使用volume Encryption rekey start命令更改卷的加密密钥
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
安全最佳做法是定期更改卷的加密密钥。从ONTAP 9.3开始、您可以使用 `volume encryption rekey start` 命令以更改加密密钥。

.关于此任务
启动重新设置密钥操作后，该操作必须完成。不会返回到旧密钥。如果您在操作期间遇到性能问题描述、则可以运行 `volume encryption rekey pause` 命令以暂停操作、以及 `volume encryption rekey resume` 命令以恢复操作。

在重新设置密钥操作完成之前，卷将具有两个密钥。新写入及其相应读取将使用新密钥。否则，读取将使用旧密钥。

[NOTE]
====
您不能使用 `volume encryption rekey start` 重新设置SnapLock卷密钥。

====
.步骤
. 更改加密密钥：
+
`volume encryption rekey start -vserver SVM_name -volume volume_name`

+
以下命令将更改的加密密钥 `vol1` 在SVM上``vs1``：

+
[listing]
----
cluster1::> volume encryption rekey start -vserver vs1 -volume vol1
----
. 验证重新设置密钥操作的状态：
+
`volume encryption rekey show`

+
有关的详细信息 `volume encryption rekey show`，请参见link:https://docs.netapp.com/us-en/ontap-cli/volume-encryption-rekey-show.html["ONTAP 命令参考"^]。

+
以下命令显示重新设置密钥操作的状态：

+
[listing]
----
cluster1::> volume encryption rekey show

Vserver   Volume   Start Time           Status
-------   ------   ------------------   ---------------------------
vs1       vol1     9/18/2017 17:51:41   Phase 2 of 2 is in progress.
----
. 重新设置密钥操作完成后，验证卷是否已启用加密：
+
`volume show -is-encrypted true`

+
有关的详细信息 `volume show`，请参见link:https://docs.netapp.com/us-en/ontap-cli/volume-show.html["ONTAP 命令参考"^]。

+
以下命令将显示上的加密卷 `cluster1`：

+
[listing]
----
cluster1::> volume show -is-encrypted true

Vserver  Volume  Aggregate  State  Type  Size  Available  Used
-------  ------  ---------  -----  ----  -----  --------- ----
vs1      vol1    aggr2     online    RW  200GB    160.0GB  20%
----

