---
permalink: encryption-at-rest/restore-onboard-key-management-encryption-keys-task.html 
sidebar: sidebar 
keywords: restoring, onboard, key management encryption 
summary: 有时，您可能需要还原板载密钥管理加密密钥。确认需要还原密钥后，您可以设置板载密钥管理器以还原此密钥。 
---
= 还原板载密钥管理加密密钥
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果需要还原板载密钥管理加密密钥，请先验证是否需要还原密钥，然后设置板载密钥管理器以还原密钥。

用于还原加密密钥的操作步骤取决于您的配置。遵循相应的工作流。

.开始之前
* 如果将 NSE 与外部密钥管理（ KMIP ）服务器结合使用，则必须已删除外部密钥管理器数据库。有关详细信息，请参见 link:delete-key-management-database-task.html["从外部密钥管理过渡到板载密钥管理"]
* 您必须是集群管理员才能执行此任务。




== 适用于 ONTAP 9.6 及更高版本的步骤

. 验证是否需要还原密钥：+
`security key-manager key query -node _node_`
. 如果您运行的是 ONTAP 9.8 及更高版本，并且根卷已加密，请完成 <<root_volume_encrypted>>。
+
如果您运行的是 ONTAP 9.6 或 9.7 ，或者运行的是 ONTAP 9.8 或更高版本，并且根卷未加密，请跳过此步骤。

. 还原密钥：+
`security key-manager onboard sync`
+
有关完整的命令语法，请参见手册页。

+
以下 ONTAP 9.6 命令可同步板载密钥层次结构中的密钥：

+
[listing]
----
cluster1::> security key-manager onboard sync

Enter the cluster-wide passphrase for onboard key management in Vserver "cluster1"::    <32..256 ASCII characters long text>
----
. 在密码短语提示符处，输入集群的板载密钥管理密码短语。




== 适用于 ONTAP 9.5 及更早版本的步骤

. 验证是否需要还原密钥：+
`security key-manager key show`
. 如果您运行的是 ONTAP 9.8 及更高版本，并且根卷已加密，请完成以下步骤：
+
如果您运行的是 ONTAP 9.6 或 9.7 ，或者运行的是 ONTAP 9.8 或更高版本，并且根卷未加密，请跳过此步骤。

. 还原密钥：+
`security key-manager setup -node _node_`
+
有关完整的命令语法，请参见手册页。

. 在密码短语提示符处，输入集群的板载密钥管理密码短语。




== 适用于ONTAP 9.8及更高版本的步骤(如果根卷已加密)

如果您运行的是 ONTAP 9.8 及更高版本，并且根卷已加密，则必须在启动菜单中设置板载密钥管理恢复密码短语。如果要更换启动介质、也需要执行此过程。

. 将节点启动至启动菜单、然后选择选项 `(10) Set onboard key management recovery secrets`。
. 输入 ... `y` 以使用此选项。
. 在提示符处，输入集群的板载密钥管理密码短语。
. 在提示符处，输入备份密钥数据。
+
节点将返回到启动菜单。

. 从启动菜单中、选择选项 `(1) Normal Boot`。

