---
permalink: encryption-at-rest/restore-external-encryption-keys-93-later-task.html 
sidebar: sidebar 
keywords: restoring, external key management, encryption keys 
summary: '您可以手动还原外部密钥管理加密密钥，并将其 " 推送 " 到其他节点。如果要重新启动在为集群创建密钥时临时关闭的节点，则可能需要执行此操作。' 
---
= 还原外部密钥管理加密密钥
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以手动还原外部密钥管理加密密钥并将其推送到其他节点。如果要重新启动在为集群创建密钥时临时关闭的节点，则可能需要执行此操作。

.关于此任务
在ONTAP 9.6及更高版本中、您可以使用 `security key-manager key query -node node_name` 命令以验证是否需要还原密钥。

在ONTAP 9.5及更早版本中、您可以使用 `security key-manager key show` 命令以验证是否需要还原密钥。


NOTE: 如果在具有Flash Cache模块的系统上使用NSE、则还应启用NVE或NAE。NSE不会对驻留在Flash Cache模块上的数据进行加密。

.开始之前
要执行此任务，您必须是集群或 SVM 管理员。

.步骤
. 如果您运行的是 ONTAP 9.8 或更高版本，并且根卷已加密，请执行以下操作：
+
如果您运行的是 ONTAP 9.7 或更早版本，或者运行的是 ONTAP 9.8 或更高版本，并且根卷未加密，请跳过此步骤。

+
.. 设置Bootargs：
 +
`setenv kmip.init.ipaddr <ip-address>`
 +
`setenv kmip.init.netmask <netmask>`
 +
`setenv kmip.init.gateway <gateway>`
 +
`setenv kmip.init.interface e0M`
 +
`boot_ontap`
.. 将节点启动至启动菜单、然后选择选项 `(11) Configure node for external key management`。
.. 按照提示输入管理证书。
+
输入所有管理证书信息后，系统将返回到启动菜单。

.. 从启动菜单中、选择选项 `(1) Normal Boot`。


. 还原密钥：
+
[cols="35,65"]
|===


| 对于此 ONTAP 版本 ... | 使用此命令 ... 


 a| 
ONTAP 9.6 及更高版本
 a| 
`security key-manager external restore -vserver SVM -node node -key-server host_name|IP_address:port -key-id key_id -key-tag key_tag`



 a| 
ONTAP 9.5 及更早版本
 a| 
`security key-manager restore -node node -address IP_address -key-id key_id -key-tag key_tag`

|===
+
[NOTE]
====
`node` 默认为所有节点。有关完整的命令语法，请参见手册页。启用板载密钥管理后，不支持此命令。

====
+
以下ONTAP 9.6命令可将外部密钥管理身份验证密钥还原到中的所有节点 `cluster1`：

+
[listing]
----
clusterl::> security key-manager external restore
----

