---
permalink: encryption-at-rest/restore-onboard-key-management-encryption-keys-task.html 
sidebar: sidebar 
keywords: restoring, onboard, key management encryption 
summary: 有时，您可能需要还原板载密钥管理加密密钥。确认需要还原密钥后，您可以设置板载密钥管理器以还原此密钥。 
---
= 在ONTAP中还原板载密钥管理加密密钥
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
有时，您可能需要恢复板载密钥管理加密密钥。确认需要恢复密钥后，您可以设置板载密钥管理器来恢复密钥。恢复板载密钥管理加密密钥所遵循的步骤因ONTAP版本的不同而不同。

.开始之前
* 如果您将 NSE 与外部 KMIP 服务器一起使用，请删除外部密钥管理器数据库。有关详细信息，请参阅link:delete-key-management-database-task.html["从外部密钥管理过渡到ONTAP板载密钥管理"]。
* 您必须是集群管理员才能执行此任务。



NOTE: 如果在具有Flash Cache模块的系统上使用NSE、则还应启用NVE或NAE。NSE不会对驻留在Flash Cache模块上的数据进行加密。



== ONTAP 9.6 及更高版本


IMPORTANT: 如果您运行的是ONTAP 9.8或更高版本，并且根卷已加密，请按照中的过程进行操作 <<ontap-9-8>>。

. 验证是否需要还原密钥：+
`security key-manager key query -node _node_`
+
有关的详细信息 `security key-manager key query`，请参见link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-key-query.html["ONTAP 命令参考"^]。

. 还原密钥：+
`security key-manager onboard sync`
+
有关的详细信息 `security key-manager onboard sync`，请参见link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-onboard-sync.html["ONTAP 命令参考"^]。

. 在密码短语提示符处，输入集群的板载密钥管理密码短语。




== 使用加密根卷的ONTAP 9.8或更高版本

如果您运行的是 ONTAP 9.8 及更高版本，并且根卷已加密，则必须在启动菜单中设置板载密钥管理恢复密码短语。如果要更换启动介质、也需要执行此过程。

. 将节点启动至启动菜单、然后选择选项 `(10) Set onboard key management recovery secrets`。
. 输入 ... `y` 以使用此选项。
. 在提示符处，输入集群的板载密钥管理密码短语。
. 在提示符处，输入备份密钥数据。
+
输入备份密钥数据后，节点返回启动菜单。

. 从启动菜单中、选择选项 `(1) Normal Boot`。




== ONTAP 9.5 及更早版本

. 验证是否需要还原密钥：+
`security key-manager key show`
. 还原密钥：+
`security key-manager setup -node _node_`
+
详细了解 `security key-manager setup`在link:https://docs.netapp.com/us-en/ontap-cli-9161/security-key-manager-setup.html["ONTAP 命令参考"^]。

. 在密码短语提示符处，输入集群的板载密钥管理密码短语。

