---
sidebar: sidebar 
permalink: s3-snapshots/index.html 
keywords: s3 snapshots, S3 Snapshot copy overview, what is S3 snapshot, can you create S3 snapshots 
summary: 使用S3快照技术为S3存储分段创建时间点备份。 
---
= 了解ONTAP S3快照
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
从ONTAP 9。16.1开始、您可以使用ONTAP快照技术生成ONTAP S3存储分段的只读时间点映像。

使用S3快照功能、您可以手动创建快照、也可以通过快照策略自动生成快照。S3快照会作为S3存储分段提供给S3客户端。您可以通过S3客户端从快照浏览和还原内容。

在ONTAP 9 16.1中、S3快照仅捕获S3存储分段中对象的当前版本。非最新版本的分版本存储分段不会捕获到S3快照中。此外、如果在创建快照后修改了对象标记、则不会在快照中捕获时间点对象标记。


TIP: S3快照取决于集群时间。您应在集群中配置NTP服务器以同步时间。有关详细信息，请参阅 link:../system-admin/manage-cluster-time-concept.html["管理集群时间"]。

.配额和空间使用量
配额用于跟踪S3存储分段中使用的对象数量和逻辑大小。创建S3快照后、S3快照中捕获的对象将计入已用存储分段对象计数和大小、直到快照从文件系统中删除为止。

.多部分对象
对于多部分对象、只会在快照中捕获最终对象。多部分对象的部分上传不会在快照中捕获。



== 分版本和非分版本分段上的快照

您可以在版本分段和非版本分段上创建快照。快照一次仅包含捕获快照时的当前对象版本。

.分版本分段和快照
在启用了对象版本控制的存储分段中、快照会保留在创建快照后的最新对象版本的内容。它不包括存储分段中的非当前版本。

请考虑以下示例：在启用了对象版本控制的存储分段中、对象的 `obj1`版本为v1、v2、v3、v4、v5。您已从 `obj1`v3 (捕获时的最新版本)创建快照 `snap1`。浏览时 `snap1`， `obj1`将显示为一个对象，其中包含在v3时创建的内容。不会返回先前版本的内容。


NOTE: 非最新版本将保留在文件系统中、直到删除快照为止。

.非版本分段和快照
在非版本分段中、S3快照会保留创建快照之前最新提交的内容。

请考虑以下示例：在对象版本控制不可用的存储分段中、对象 `obj1`已在(T1、T2、T3、T4和T4)处被覆盖多次。您在T3和T4之间的某个时间创建了一个S3快照 `snap1`。浏览时 `snap1`， `obj1`将显示在T3上创建的内容。



== 对象到期时间和快照

ONTAP S3对象到期时间和S3快照功能相互独立。ONTAP对象到期功能会根据为S3存储分段定义的生命周期管理规则使对象版本到期。S3快照是指在创建快照时分段对象的静态副本。

如果在某个存储分段中启用了对象版本控制、则在因为该存储分段定义的到期规则而删除某个对象的特定版本时、如果该版本已在一个或多个S3快照中捕获为当前版本、则该过期对象版本的内容仍会保留在文件系统中。只有在删除该快照后、该对象版本才会在文件系统中消失。

同样、在禁用了版本控制的存储分段中、如果根据到期规则删除了某个对象、但该对象仍在某些现有S3快照中捕获、则该对象将保留在文件系统中。删除捕获对象的快照后、该对象将从文件系统中永久删除。

有关S3对象到期和生命周期管理的信息，请参见link:../s3-config/create-bucket-lifecycle-rule-task.html["创建存储分段生命周期管理规则"]。



== S3快照的限制

请注意ONTAP 9 16.1中的以下功能排除项和方案：

* 一个S3存储分段最多可以生成1023个快照。
* 在将集群还原到ONTAP 9 16.1之前的ONTAP版本之前、必须先删除集群中所有存储分段中的所有S3快照和元数据。
* 如果需要删除包含具有快照的对象的S3存储分段、请确保已删除该存储分段中所有对象的所有相应快照。
* 以下配置不支持S3快照：
+
** SnapMirror关系中的存储分段
** 在启用了对象锁定的存储分段上
** 在NetApp BlueXP  上
** 在System Manager上
** 在ONTAP MetroCluster配置中



