---
permalink: s3-multiprotocol/create-nas-bucket-task.html 
sidebar: sidebar 
keywords: s3, svm, bucket, object, server, versioning, protocol, filesystems, nas, directories 
summary: S3 NAS存储分段是S3存储分段名称和NAS路径之间的映射。  
---
= 创建ONTAP S3 NAS 存储桶
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 NAS 存储桶是 S3 存储桶名称和 NAS 路径之间的映射。S3NAS 存储桶允许您提供对具有现有卷和目录结构的 SVM 命名空间的任何部分的 S3 访问权限。

.开始之前
* 在包含NAS数据的SVM中配置了S3对象服务器。
* NAS数据符合 link:nas-data-requirements-client-access-reference.html["S3客户端访问的要求"]。


.关于此任务
您可以配置S3 NAS存储分段以指定SVM根目录中的任何一组文件和目录。

您还可以设置分段策略、以便根据以下参数的任意组合允许或禁止访问NAS数据：

* 文件和目录
* 用户和组权限
* S3操作


例如、您可能希望使用单独的存储分段策略、为一组用户授予只读数据访问权限、并使用另一个存储分段策略、允许受限组对该数据的一部分执行操作。

从ONTAP 9.17.1 开始，您可以直接将 S3 NAS 存储桶链接到卷，而无需通过连接路径。默认情况下，NAS 卷上的 S3 存储桶与连接路径关联， ONTAP管理员可以随时更改该连接路径。这些更改可能会中断 S3 存储桶的运行。从ONTAP 9.17.1 开始，您可以使用 `-is-nas-path-mutable false`选项 `vserver object-store-server bucket create`命令用于启用 S3 NAS 存储桶与卷的链接。默认情况下，  `-is-nas-path-mutable`设置为 `true` 。

由于 S3 NAS“存储桶”是映射而不是 S3 存储桶，因此标准 S3 存储桶的以下属性不适用于 S3 NAS 存储桶。

* *aggr-list \ aggr-list-multi倍 频\ storage-service-level \ volume \ size \ exex懦-aggr-list \ QoS-policy-group*+
配置S3 NAS分段时、不会创建任何卷或qtree。
* *role \ is -protected \ is -protected-on-ontap \ is -protected-on-cloud* + S3 NAS 存储桶不受SnapMirror S3 保护或镜像，而是使用卷粒度上可用的常规SnapMirror保护。
* *版本控制状态*+ NAS卷通常采用快照技术来保存不同的版本。但是、S3 NAS存储分段当前不支持版本控制。
* *逻辑使用\ object-count *+
可通过volume命令为NAS卷提供等效统计信息。
* *多部分对象* + 从ONTAP 9.16.1 开始，当 S3 NAS 存储桶支持多部分对象时link:../flexgroup/enable-adv-capacity-flexgroup-task.html["高级容量平衡"]在底层FlexGroup卷上启用。高级容量平衡只能在FlexGroup卷上启用。无法在FlexVol卷上启用。


.步骤
您可以使用 System Manager 或ONTAP CLI 创建 NAS 存储桶。

[role="tabbed-block"]
====
.System Manager
--
在启用了NAS的Storage VM上添加新的S3 NAS存储分段。

. 单击 * 存储 > 分段 * ，然后单击 * 添加 * 。
. 输入S3 NAS存储分段的名称并选择Storage VM、不要输入大小、然后单击*更多选项*。
. 输入有效的路径名称或单击浏览以从有效路径名称列表中进行选择。+
输入有效的路径名后、与S3 NAS配置无关的选项将被隐藏。
. 如果已将S3用户映射到NAS用户并创建了组、则可以配置其权限、然后单击*保存*。+
在此步骤中配置权限之前、您必须已将S3用户映射到NAS用户。


否则、请单击*保存*以完成S3 NAS存储分段配置。

--
.命令行界面
--
. 在包含 NAS 文件系统的 SVM 中创建 S3 NAS 存储桶。+ 
`vserver object-store-server bucket create -vserver <svm_name> -bucket <bucket_name> -type nas -nas-path <junction_path> -is-nas-path-mutable true|false [-comment <text>]`
+
示例 1：创建 S3 NAS 存储桶

+
`cluster1::> vserver object-store-server bucket create -bucket testbucket -type nas -path /vol1`

+
示例 2：创建 S3 NAS 存储桶并将存储桶链接到卷

+
`vserver object-store-server bucket create -vserver vs1 -bucket nasbucket1 -type nas -nas-path /pathA/dir1 -is-nas-path-mutable false`



--
====