---
permalink: s3-multiprotocol/nas-data-requirements-client-access-reference.html 
sidebar: sidebar 
keywords: s3, mapping, directory, access, configuration, object, nas, bucket 
summary: 请务必了解、映射用于S3访问的NAS文件和目录会改变某些标准NAS行为。 
---
= S3客户端访问的NAS数据要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
请务必了解、在映射NAS文件和目录以进行S3访问时、存在一些固有的不兼容性。在使用S3 NAS分段提供NAS文件层次结构之前、可能需要对其进行调整。

通过使用S3存储分段语法映射NAS目录、S3 NAS分段可提供对该目录的S3访问、并且目录树中的文件将被视为对象。对象名称是相对于S3存储分段配置中指定的目录的文件的斜杠分隔路径名。

如果使用S3 NAS分段提供文件和目录、则此映射会产生一些要求：

* S3名称限制为1024字节、因此使用S3无法访问路径名较长的文件。
* 文件和目录名称不得超过255个字符、因此对象名称的连续非斜杠(‘/')字符不能超过255个
* 使用反斜杠(‘\')字符分隔的SMB路径名将在S3中显示为包含正斜杠(‘/')字符的对象名称。
* 某些合法S3对象名称对不能同时位于映射的NAS目录树中。例如、合法S3对象名称"part1/part2"和"part1/part2/part3"映射到NAS目录树中不能同时存在的文件、因为"part1/part2"是第一个名称中的文件、而另一个名称中的目录。
+
** 如果"part1/part2"是现有文件、则在S3上创建"part1/part2/part3"将失败。
** 如果"part1/part2/part3"是现有文件、则S3创建或删除"part1/part2"将失败。
** 创建与现有对象名称匹配的S3对象将替换已存在的对象(位于未版本控制的分段中)；该对象保留在NAS中、但需要完全匹配。上述示例不会通过发生原因 删除现有对象、因为名称发生冲突时不匹配。




虽然对象存储可支持大量任意名称、但如果将大量名称放置在一个目录中、则NAS目录结构可能会遇到性能问题。特别是、其中没有斜杠(‘/')字符的名称将全部放置在NAS映射的根目录中。如果应用程序大量使用不是"不适合NAS的"名称、则最好托管在实际对象存储分段上、而不是NAS映射上。
