---
permalink: ndmp/configure-backup-user-cluster-task.html 
sidebar: sidebar 
keywords: configure, backup, user, cluster 
summary: 要从备份应用程序对SVM范围的NDMP进行身份验证、必须有一个具有足够权限和NDMP密码的管理用户。 
---
= 为备份用户启用NDMP身份验证
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
要从备份应用程序对SVM范围的NDMP进行身份验证、必须有一个具有足够权限和NDMP密码的管理用户。

.关于此任务
您必须为备份管理员用户生成NDMP密码。您可以在集群或SVM级别启用备份管理员用户、如有必要、您可以创建新用户。默认情况下、具有以下角色的用户可以对NDMP备份进行身份验证：

* 集群范围： `admin` 或 `backup`
* 单个SVM： `vsadmin` 或 `vsadmin-backup`


如果使用的是NIS或LDAP用户、则该用户必须位于相应的服务器上。您不能使用 Active Directory 用户。

.步骤
. 显示当前管理员用户和权限：
+
`security login show`

. 如果需要、使用创建新的NDMP备份用户 `security login create` 命令以及集群范围或单个SVM特权的相应角色。
+
您可以为指定本地备份用户名或NIS或LDAP用户名 `-user-or-group-name` 参数。

+
以下命令将创建备份用户 `backup_admin1` 使用 `backup` 整个集群的角色：

+
`cluster1::> security login create -user-or-group-name backup_admin1 -application ssh -authmethod password -role backup`

+
以下命令将创建备份用户 `vsbackup_admin1` 使用 `vsadmin-backup` 单个SVM的角色：

+
`cluster1::> security login create -user-or-group-name vsbackup_admin1 -application ssh -authmethod password -role vsadmin-backup`

+
输入新用户的密码并确认。

. 使用为管理SVM生成密码 `vserver services ndmp generate password` 命令：
+
生成的密码必须用于对备份应用程序的 NDMP 连接进行身份验证。

+
[listing]
----
cluster1::> vserver services ndmp generate-password -vserver cluster1 -user backup_admin1

 Vserver: cluster1
    User: backup_admin1
Password: qG5CqQHYxw7tE57g
----

