---
permalink: consistency-groups/configure-task.html 
sidebar: sidebar 
keywords: consistency groups, consistency group, application protection, parent, child, configure 
summary: 创建一个一致性组，用于应用程序工作负载管理和数据保护。 
---
= 配置一个一致性组
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
可以使用现有卷或新卷创建一致性组。一旦某个卷与某个一致性组关联、则无法将其添加到另一个一致性组中。

在ONTAP 9.10.1至9.11.1中、您不能修改一致性组的成分卷。从ONTAP 9.12.1开始、您可以在创建一致性组后将_existent_卷添加或删除到一致性组中。有关此过程的详细信息、请参见 xref:modify-task.html[修改一致性组]。



== 使用新卷创建一致性组

.步骤
. 选择 * 存储 > 一致性组 * 。
. 选择 * + 添加 * ，然后选择 * 使用新 LUN* 。
. 为一致性组命名。指定每个 LUN 的 LUN 数量和容量。
+
.. **应用程序类型*：如果使用的是ONTAP 9.12.1或更高版本、请选择应用程序类型。如果未选择任何值、则默认情况下会为一致性组分配类型为"*其他"*。了解有关标记一致性的更多信息 xref:index.html#application-and-component-tags[应用程序和组件标记]。如果您计划创建SM-BC关系、则必须使用*其他*。


. 选择主机操作系统和 LUN 格式。输入主机启动程序信息。
. 要配置保护策略，添加子一致性组或显示有关主机启动程序的更多选项，请选择 * 更多选项 *
. 选择 * 保存 * 。
. 返回到一致性组主菜单以确认已创建一致性组，该菜单将在 ONTAP 作业完成后显示。如果您设置了保护策略，请查看相应策略（远程或本地）下的相应策略，该策略应显示一个带复选标记的绿色屏蔽。




== 使用现有卷创建一致性组

.步骤
. 选择 * 存储 > 一致性组 * 。
. 选择 * + 添加 * ，然后选择 * 使用现有卷 * 。
. 为一致性组命名并选择 Storage VM 。
+
.. **应用程序类型*：如果使用的是ONTAP 9.12.1或更高版本、请选择应用程序类型。如果未选择任何值、则默认情况下会为一致性组分配类型为"*其他"*。了解有关标记一致性的更多信息 xref:index.html#application-and-component-tags[应用程序和组件标记]。如果一致性组具有SM-BC关系、则必须使用*其他*。


. 选择要包括的现有卷。只有尚未加入一致性组的卷才可供选择。
+

NOTE: 如果使用现有卷创建一致性组、则此一致性组支持FlexVol 卷。具有异步或同步 SnapMirror 关系的卷可以添加到一致性组，但它们不能识别一致性组。一致性组不支持具有SVMDR关系的S3存储分段、MetroCluster 或Storage VM。

. 选择 * 保存 * 。
. 返回到一致性组主菜单以确认已创建一致性组，该菜单将在 ONTAP 作业完成后显示。如果您选择了保护策略，请从菜单中选择一致性组以确认其设置正确。如果您设置了保护策略，请查看相应策略（远程或本地）下的相应策略，该策略应显示一个带复选标记的绿色屏蔽。


.后续步骤
* xref:protect-task.html[保护一致性组]
* xref:modify-task.html[修改一致性组]
* xref:clone-task.html[克隆一致性组]

