---
permalink: consistency-groups/configure-hierarchy-task.html 
sidebar: sidebar 
keywords: consistency groups, application protection, parent, child, hierarchy 
summary: 创建一个分层一致性组，用于管理大型应用程序工作负载和保护数据。 
---
= 配置分层ONTAP一致性组
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过分层一致性组、您可以管理跨越多个卷的大型工作负载、从而创建一个父一致性组、用作子一致性组的保护。

分层一致性组具有一个父级，最多可包含五个单独的一致性组。分层一致性组可以支持跨一致性组或单个卷的不同本地Snapshot策略。如果您使用的是远程保护策略、则该策略将适用于整个分层一致性组(父级和子级)。

从ONTAP 9.13.1.开始、您可以执行此操作 xref:modify-geometry-task.html[修改一致性组的几何结构] 和 xref:modify-task.html[在子一致性组之间移动卷]。

有关一致性组的对象限制，请参见 xref:limits.html[一致性组的对象限制]。



== 使用新的LUN或卷创建分层一致性组

创建分层一致性组时、您可以使用新的LUN填充该组。从ONTAP 9.13.1开始、您还可以使用新的NVMe命名空间和NAS卷。

[role="tabbed-block"]
====
.System Manager
--
.步骤
. 选择 * 存储 > 一致性组 * 。
. 选择*+Add*，然后选择存储对象的协议。
+
在ONTAP 9.10.1到9.12.1中，新存储对象的唯一选项是**使用新LUNS**。从ONTAP 9.13.1开始、System Manager支持使用新的NVMe命名空间和NAS卷创建一致性组。

. 为一致性组命名。指定卷或LUN的数量以及每个卷或LUN的容量。
+
.. **应用程序类型*：如果使用的是ONTAP 9.12.1或更高版本、请选择应用程序类型。如果未选择任何值、则默认情况下会为一致性组分配类型为"*其他"*。了解有关标记一致性的更多信息 xref:modify-tags-task.html[应用程序和组件标记]。如果您计划使用远程保护策略，则必须选择*OTHE*。


. 选择主机操作系统和 LUN 格式。输入主机启动程序信息。
+
.. 对于**新LUNS**：选择主机操作系统和LUN格式。输入主机启动程序信息。
.. 对于**新NAS卷**：根据SVM的NAS配置选择适当的导出选项(NFS或SMB/CCIFS)。
.. 对于**新NVMe命名区**：选择主机操作系统和NVMe子系统。


. 要添加子一致性组、请选择*更多选项*、然后选择*+添加子一致性组*。
. 选择性能级别、LUN或卷数量以及每个LUN或卷的容量。根据您使用的协议指定适当的导出配置或操作系统信息。
. (可选)选择本地快照策略并设置访问权限。
. 对最多五个子一致性组重复此操作。
. 选择 * 保存 * 。
. 返回到一致性组主菜单以确认已创建一致性组，该菜单将在 ONTAP 作业完成后显示。如果您设置了保护策略，请查看相应策略（远程或本地）下的内容，该策略应显示一个绿色屏蔽并带有复选标记。


--
.命令行界面
--
.开始之前
* 要执行此任务、您必须具有管理员权限级别。
* 从ONTAP 9.15.1 开始，任何具有管理员权限级别的用户都可以执行此任务。在ONTAP 9.14.1 中，您必须是集群或 SVM 管理员才能执行此任务。


在CLI中使用新卷创建分层一致性组时、必须单独创建每个子一致性组。

.步骤
. 使用创建新一致性组 `consistency-group create` 命令：
+
`consistency-group create -vserver <SVM_name> -consistency-group <consistency_group_name> -parent-consistency-group <parent_consistency_group_name> -volume-prefix <volume_prefix> -volume-count <number_of_volumes> -size <size>`

. 在命令行界面提示时、确认要创建新的父一致性组。输入。 `y`
. (可选)重复步骤1以创建更多子一致性组。
+
有关的详细信息 `consistency-group create`，请参见link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=consistency-group+create["ONTAP 命令参考"^]。



--
====


== 使用现有卷创建分层一致性组

您可以将现有卷组织为分层一致性组。

[role="tabbed-block"]
====
.System Manager
--
.步骤
. 选择 * 存储 > 一致性组 * 。
. 选择*+添加*、然后选择*使用现有卷*。
. 选择 Storage VM 。
. 选择要包括的现有卷。只有尚未加入一致性组的卷才可供选择。
. 要添加子一致性组，请选择 * + 添加子一致性组 * 。创建必要的一致性组，该组将自动命名。
+
.. "*组件类型"*：如果使用的是ONTAP 9.12.1或更高版本、请选择组件类型"data"、"logs"或"other"。如果未选择任何值、则默认情况下会为一致性组分配类型为"*其他"*。了解有关标记一致性的更多信息 xref:modify-tags-task.html[应用程序和组件标记]。如果您计划使用远程保护策略，则必须使用*OTE*。


. 将现有卷分配给每个一致性组。
. (可选)选择本地快照策略。
. 对最多五个子一致性组重复此操作。
. 选择 * 保存 * 。
. 返回到一致性组主菜单以确认已创建一致性组，该菜单将在 ONTAP 作业完成后显示。如果您选择了保护策略、请从菜单中选择一致性组以确认其设置正确；在相应的策略类型下、您将看到一个绿色屏蔽、其中带有复选标记。


--
.命令行界面
--
从ONTAP 9.14.1开始、您可以使用命令行界面创建分层一致性组。

.开始之前
* 要执行此任务、您必须具有管理员权限级别。
* 从ONTAP 9.15.1 开始，任何具有管理员权限级别的用户都可以执行此任务。在ONTAP 9.14.1 中，您必须是集群或 SVM 管理员才能执行此任务。


.步骤
. 配置新的父一致性组并将卷分配给新的子一致性组：
+
`consistency-group create -vserver <svm_name> -consistency-group <child_consistency_group_name> -parent-consistency-group <parent_consistency_group_name> -volumes <volume_names>`

. 输入 ... `y` 确认要创建新的父一致性组和子一致性组。
+
有关的详细信息 `consistency-group create`，请参见link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=consistency-group+create["ONTAP 命令参考"^]。



--
====
.后续步骤
* xref:xref:modify-geometry-task.html[修改一致性组的几何结构]
* xref:modify-task.html[修改一致性组]
* xref:protect-task.html[保护一致性组]

