---
permalink: consistency-groups/configure-task.html 
sidebar: sidebar 
keywords: consistency groups, consistency group, application protection, parent, child, configure 
summary: 创建一个一致性组，用于应用程序工作负载管理和数据保护。 
---
= 配置一个一致性组
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
可以使用现有卷或新的LUN或卷创建一致性组(具体取决于ONTAP的版本)。一个卷或LUN一次只能与一个一致性组相关联。

.关于此任务
* 在ONTAP 9.10.1到9.11.1中、不支持在创建一致性组后修改其成员卷。
+
从ONTAP 9.12.1开始、您可以修改一致性组的成员卷。有关此过程的详细信息、请参见 xref:modify-task.html[修改一致性组]。





== 使用新的LUN或卷创建一致性组

在ONTAP 9.10.1到9.12.1中、您可以使用新的LUN创建一致性组。从ONTAP 9.13.1开始、System Manager还支持使用新的NVMe命名空间或新的NAS卷创建一致性组。(从ONTAP 9.12.1开始、ONTAP REST API也支持此功能。)

[role="tabbed-block"]
====
.System Manager
--
.步骤
. 选择 * 存储 > 一致性组 * 。
. 选择*+Add*，然后选择存储对象的协议。
+
在ONTAP 9.10.1到9.12.1中，新存储对象的唯一选项是**使用新LUNS**。从ONTAP 9.13.1开始、System Manager支持使用新的NVMe命名空间和NAS卷创建一致性组。

. 为一致性组命名。指定卷或LUN的数量以及每个卷或LUN的容量。
+
.. **应用程序类型*：如果使用的是ONTAP 9.12.1或更高版本、请选择应用程序类型。如果未选择任何值、则默认情况下会为一致性组分配类型为"*其他"*。了解有关标记一致性的更多信息 xref:modify-tags-task.html[应用程序和组件标记]。如果您计划使用远程保护策略创建一致性组、则必须使用*其他*。
.. 对于**新LUNS**：选择主机操作系统和LUN格式。输入主机启动程序信息。
.. 对于**新NAS卷**：根据SVM的NAS配置选择适当的导出选项(NFS或SMB/CCIFS)。
.. 对于**新NVMe命名区**：选择主机操作系统和NVMe子系统。


. 要配置保护策略、添加子一致性组或访问权限，请选择*更多选项*。
. 选择 * 保存 * 。
. 返回到一致性组主菜单以确认已创建一致性组、该菜单将在作业完成后显示。如果您设置了保护策略、则在相应策略"远程"或"本地"下看到绿色屏蔽时、您将知道该策略已应用。


--
.命令行界面
--
从ONTAP 9.14.1开始、您可以使用ONTAP命令行界面创建包含新卷的新一致性组。具体参数取决于卷是SAN、NVMe还是NFS。

.使用NFS卷创建一致性组
. 创建一致性组：
+
`consistency-group create -vserver _SVM_name_ -consistency-group _consistency-group-name_ -volume _volume-prefix_ -volume-count _number_ -size _size_ -export-policy _policy_name_`



.使用SAN卷创建一致性组
. 创建一致性组：
+
`consistency-group create -vserver _SVM_name_ -consistency-group _consistency-group-name_ -lun _lun_name_ -size _size_ -lun-count _number_ -igroup _igroup_name_`



.使用NVMe命名卷创建一致性组
. 创建一致性组：
+
`consistency-group create -vserver _SVM_name_ -consistency-group _consistency_group_name_ -namespace _namespace_name_ -volume-count _number_ -namespace-count _number_ -size _size_ -subsystem _subsystem_name_`



.完成后
. 确认已使用创建一致性组 `consistency-group show` 命令：


--
====


== 使用现有卷创建一致性组

您可以使用现有卷创建一致性组。

[role="tabbed-block"]
====
.System Manager
--
.步骤
. 选择 * 存储 > 一致性组 * 。
. 选择*+添加*、然后选择*使用现有卷*。
. 为一致性组命名并选择 Storage VM 。
+
.. **应用程序类型*：如果使用的是ONTAP 9.12.1或更高版本、请选择应用程序类型。如果未选择任何值、则默认情况下会为一致性组分配类型为"*其他"*。了解有关标记一致性的更多信息 xref:modify-tags-task.html[应用程序和组件标记]。如果一致性组具有SM-BC关系、则必须使用*其他*。


. 选择要包括的现有卷。只有尚未加入一致性组的卷才可供选择。
+

NOTE: 如果使用现有卷创建一致性组、则此一致性组支持FlexVol 卷。具有异步或同步 SnapMirror 关系的卷可以添加到一致性组，但它们不能识别一致性组。一致性组不支持S3存储分段或具有SVMDR关系的Storage VM。

. 选择 * 保存 * 。
. 返回到一致性组主菜单以确认已创建一致性组，该菜单将在 ONTAP 作业完成后显示。如果您选择了保护策略，请从菜单中选择一致性组以确认其设置正确。如果您设置了保护策略、则在相应策略"远程"或"本地"下看到绿色屏蔽时、您将知道该策略已应用。


--
.命令行界面
--
从ONTAP 9.14.1开始、您可以使用ONTAP命令行界面创建包含现有卷的一致性组。

.步骤
. 问题描述 `consistency-group create` 命令：。 `-volumes` 参数接受以逗号分隔的卷名称列表。
+
`consistency-group create -vserver _SVM_name_ -consistency-group _consistency-group-name_ -volume _volumes_`

. 使用查看一致性组 `consistency-group show` 命令：


--
====
.后续步骤
* xref:protect-task.html[保护一致性组]
* xref:modify-task.html[修改一致性组]
* xref:clone-task.html[克隆一致性组]

