---
sidebar: sidebar 
permalink: consistency-groups/modify-geometry-task.html 
keywords: consistency group geometry, promote consistency group, demote, add consistency group 
summary: 从ONTAP 9.13.1开始、您可以在中断IO操作的情况下修改一致性组的几何结构。 
---
= 修改一致性组几何结构
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
从ONTAP 9.13.1开始、您可以修改一致性组的几何结构。通过修改一致性组的几何结构、您可以在不中断正在进行的IO操作的情况下更改子一致性组或父一致性组的配置。

修改一致性组几何结构将对现有Snapshot副本产生影响。


NOTE: 您不能修改使用远程保护策略配置的一致性组的几何结构。您必须先中断保护关系、修改几何结构、然后再还原远程保护。



== 添加新的子一致性组

从ONTAP 9.13.1开始、您可以向现有父一致性组添加新的子一致性组。

.开始之前
* 一个父一致性组最多可以包含五个子一致性组。请参见 xref:limits.html[一致性组限制] 其他限制。
* 您不能将子一致性组添加到单个一致性组中。您必须先执行此操作 <<提升>> 然后、您可以添加子一致性组。
* 在扩展操作之前捕获的一致性组的现有Snapshot副本将视为部分副本。基于该Snapshot副本的任何还原操作都将反映Snapshot副本时间点的一致性组。


.步骤
[role="tabbed-block"]
====
.System Manager
--
从ONTAP 9.13.1开始、您可以使用System Manager执行此操作。

. 选择 * 存储 > 一致性组 * 。
. 选择要添加子一致性组的父一致性组。
. 在父一致性组的名称旁边，选择**更多**，然后选择**添加新的子一致性组**。
. 输入一致性组的名称。
. 选择要添加新卷还是现有卷。
+
.. 如果要添加现有卷，请选择**现有卷**，然后从下拉菜单中选择卷。
.. 如果要添加新卷，请选择**新建卷**，然后指定卷的数量及其大小。


. 选择**添加**。


--
.命令行界面
--
从ONTAP 9.14.1开始、您可以使用ONTAP命令行界面添加子一致性组。

.添加包含新卷的子一致性组
. 创建新一致性组。提供一致性组名称、卷前缀、卷数量、卷大小、存储服务、 和导出策略名称：
+
`consistency-group create -vserver _SVM_name_ -consistency-group _consistency_group_ -parent-consistency-group _parent_consistency_group_ -volume-prefix _prefix_ -volume-count _number_ -size _size_ -storage-service _service_ -export-policy _policy_name_`



.添加包含现有卷的子一致性组
. 创建新一致性组。。 `volumes` 参数接受以逗号分隔的卷名称列表。
+
`consistency-group create -vserver _SVM_name_ -consistency-group _new_consistency_group_ -parent-consistency-group _parent_consistency_group_ -volumes _volume_`



--
====


== 断开子一致性组

从ONTAP 9.13.1开始、您可以从父一致性组中删除子一致性组、从而将其转换为单个一致性组。

.开始之前
* 断开子一致性组会导致父一致性组的快照无效且无法访问。卷粒度快照仍然有效。
* 单个一致性组的现有Snapshot副本仍然有效。
* 如果现有单个一致性组与要断开的子一致性组同名、则此操作将失败。如果遇到这种情况、则必须在断开一致性组时对其进行重命名。


.步骤
[role="tabbed-block"]
====
.System Manager
--
从ONTAP 9.13.1开始、您可以使用System Manager执行此操作。

. 选择 * 存储 > 一致性组 * 。
. 选择包含要断开的子项的父一致性组。
. 在要断开的子一致性组旁边，选择**更多**，然后选择**从父级断开**。
. (可选)重命名一致性组并选择应用程序类型。
. 选择**断开**。


--
.命令行界面
--
从ONTAP 9.14.1开始、您可以使用ONTAP命令行界面断开子一致性组。

. 断开一致性组。(可选)使用重命名断开的一致性组 `-new-name` 参数。
+
`consistency-group detach -vserver _SVM_name_ -consistency-group _child_consistency_group_ -parent-consistency-group _parent_consistency_group_ [-new-name _new_name_]`



--
====


== 将现有的单个一致性组移动到父一致性组下

从ONTAP 9.13.1开始、您可以将现有的单个一致性组转换为子一致性组。您可以将一致性组移动到现有父一致性组下、也可以在移动操作期间创建新的父一致性组。

.开始之前
* 父一致性组必须包含四个或更少的子级。一个父一致性组最多可以包含五个子一致性组。请参见 xref:limits.html[一致性组限制] 其他限制。
* 在此操作之前捕获的_parent一致性组的现有Snapshot副本将视为部分副本。基于其中一个Snapshot副本的任何还原操作都将反映Snapshot副本时间点的一致性组。
* 此一致性组的现有一致性组快照仍有效。


.步骤
[role="tabbed-block"]
====
.System Manager
--
从ONTAP 9.13.1开始、您可以使用System Manager执行此操作。

. 选择 * 存储 > 一致性组 * 。
. 选择要转换的一致性组。
. 选择**更多**，然后选择**移动到不同的一致性组**。
. (可选)为一致性组输入新名称并选择组件类型。默认情况下、组件类型为"其他"。
. 选择是要迁移到现有父一致性组还是创建新的父一致性组：
+
.. 要迁移到现有父一致性组、请选择**现有一致性组**、然后从下拉菜单中选择一致性组。
.. 要创建新的父一致性组，请选择**新建一致性组**，然后为新一致性组提供一个名称。


. 选择**移动**。


--
.命令行界面
--
从ONTAP 9.14.1开始、您可以使用ONTAP命令行界面将单个一致性组移动到父一致性组下。

.将一致性组移动到新的父一致性组下
. 创建新的父一致性组。。 `-consistency-groups` 参数会将任何现有一致性组迁移到新的父级。
+
`consistency-group attach -vserver _svm_name_ -consistency-group _parent_consistency_group_ -consistency-groups _child_consistency_group_`



.将一致性组移动到现有一致性组下
. 移动一致性组：
+
`consistency-group add -vserver _SVM_name_ -consistency-group _consistency_group_ -parent-consistency-group _parent_consistency_group_`



--
====


== 提升子一致性组

从ONTAP 9.13.1开始、您可以将单个一致性组提升为父一致性组。在将单个一致性组提升为父一致性组时、您还会创建一个新的子一致性组、该组会继承原始单个一致性组中的所有卷。

.开始之前
* 如果要将子一致性组转换为父一致性组、则必须先执行此操作 <<detach>> 然后、子一致性组将遵循此操作步骤。
* 提升一致性组后、该一致性组的现有Snapshot副本仍有效。


.步骤
[role="tabbed-block"]
====
.System Manager
--
从ONTAP 9.13.1开始、您可以使用System Manager执行此操作。

. 选择 * 存储 > 一致性组 * 。
. 选择要提升的一致性组。
. 选择**更多**，然后选择**提升到父一致性组**。
. 输入**名称**并为子一致性组选择**组件类型**。
. 选择**提升**。


--
.命令行界面
--
从ONTAP 9.14.1开始、您可以使用ONTAP命令行界面将单个一致性组移动到父一致性组下。

. 提升一致性组。此命令将创建一个父一致性组和一个子一致性组。
+
`consistency-group promote -vserver _SVM_name_ -consistency-group _existing_consistency_group_ -new-name _new_child_consistency_group_`



--
====


== 将父级迁移到单个一致性组

从ONTAP 9.13.1开始、您可以将父一致性组迁移为单个一致性组。对父级进行分层会使一致性组的层次结构趋于一致、从而删除所有关联的子一致性组。此一致性组中的所有卷都将保留在新的单个一致性组下。

.开始之前
* 在将父一致性组的现有Snapshot副本迁移到单个一致性之后、此一致性组的现有Snapshot副本仍有效。该父级的任何关联子一致性组的现有Snapshot副本将无效、但其中的单个卷快照仍可作为卷粒度快照进行访问。


.步骤
[role="tabbed-block"]
====
.System Manager
--
从ONTAP 9.13.1开始、您可以使用System Manager执行此操作。

. 选择 * 存储 > 一致性组 * 。
. 选择要删除的父一致性组。
. 选择**更多**，然后**降级到单个一致性组**。
. 此时将显示一条警告、告知您所有关联的子一致性组都将被删除、并且其卷将移至新的单个一致性组下。选择**降级**以确认您了解其影响。


--
.命令行界面
--
从ONTAP 9.14.1开始、您可以使用ONTAP命令行界面来将一致性组降至较小的位置。

. 将此一致性组的成员进行分组。使用可选 `-new-name` 用于重命名一致性组的参数。
+
`consistency-group demote -vserver _SVM_name_ -consistency-group _parent_consistency_group_ [-new-name _new_consistency_group_name_]`



--
====