---
sidebar: sidebar 
permalink: concept_administration_overview.html 
keywords: netapp, ontap, administration, overview, cluster, node, local tier, aggregate, svm, storage vm, service level, volume, qtree, LUN, automatic aggregate selection, vserver, protocol, quota, disk, HA pair, dashboard, subnet, domain, interface, mirroring, vaulting, storage 
summary: 使用 System Manager ，您可以通过 Web 浏览器管理存储系统和存储对象，并执行与存储系统相关的常见管理任务。 
---
= System Manager 管理概述
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
System Manager 是一个图形管理界面，可用于使用 Web 浏览器管理存储系统和存储对象（例如磁盘，卷和存储层）以及执行与存储系统相关的常见管理任务。

本节中的过程可帮助您在 ONTAP 9.7 及更高版本中使用 System Manager 管理集群。

[NOTE]
====
* 从 ONTAP 9.8 开始， System Manager 不再以可执行文件的形式提供，并作为 Web 服务随 ONTAP 软件提供，默认情况下处于启用状态，可通过浏览器访问。
* System Manager 的名称已从 ONTAP 9.6 开始更改。在 ONTAP 9.5 及更早版本中，它称为 OnCommand 系统管理器。从 ONTAP 9.6 及更高版本开始，它称为 System Manager 。
* 如果您使用的是经典 System Manager （仅适用于 ONTAP 9.7 及更早版本），请参见  https://["System Manager 经典版（ ONTAP 9.0 到 9.7 ）"^]


====
使用 System Manager 信息板，您可以查看有关重要警报和通知，存储层和卷的效率和容量，集群中可用的节点， HA 对中节点的状态，最活跃的应用程序和对象， 以及集群或节点的性能指标。

使用 System Manager ，您可以执行许多常见任务，例如：

* 创建集群，配置网络并设置集群的支持详细信息。
* 配置和管理存储对象，例如磁盘，本地层，卷， qtree ， 和配额。
* 配置协议，例如 SMB 和 NFS ，并配置文件共享。
* 配置 FC ， FCoE ， NVMe 和 iSCSI 等协议以进行块访问。
* 创建和配置网络组件，例如子网，广播域，数据和管理接口以及接口组。
* 设置和管理镜像和存储关系。
* 执行集群管理，存储节点管理和 Storage Virtual Machine （ Storage VM ）管理操作。
* 创建和配置 Storage VM ，管理与 Storage VM 关联的存储对象以及管理 Storage VM 服务。
* 监控和管理集群中的高可用性（ HA ）配置。
* 配置服务处理器以远程登录，管理，监控和管理节点，而不管节点的状态如何。




== System Manager 术语

对于某些 ONTAP 密钥功能， System Manager 使用的术语与命令行界面不同。

* * 本地层 * —存储数据的一组物理固态驱动器或硬盘驱动器。您可能知道这些是聚合。实际上，如果使用 ONTAP 命令行界面，您仍会看到用于表示本地层的术语 _aggregate_ 。
* * 云层 * —当您出于多种原因之一希望将某些数据置于外部时， ONTAP 所使用的云中存储。如果您考虑的是 FabricPool 的云部分，您已经了解到了。如果您使用的是 StorageGRID 系统，则您的云可能根本不在内部环境中。（在内部环境中享受类似于云的体验称为 _private cloud _ 。）
* * Storage VM* —在 ONTAP 中运行的虚拟机，可为客户端提供存储和数据服务。您可能会将其识别为 _svm_ 或 _vserver_ 。
* * 网络接口 * —分配给物理网络端口的地址和属性。您可能会将此接口称为 _logical interface （ LIF ） _ 。
* * 暂停 * —暂停操作的操作。在 ONTAP 9.8 之前，您可能已经在其他版本的 System Manager 中引用了 _quiesce.

