---
sidebar: sidebar 
permalink: concept_key_ontap.html 
keywords: netapp, ontap, cluster, node, local tier, cloud tier, aggregate, SVM, storage VM, service level, volume, qtree, LUN, automatic aggregate selection, tier selection, vserver, ONTAP concepts, terms, Snapshot copy, data protection, mirroring, HA pair, storage efficiency, compression, deduplication, compaction, multifactor authentication, client, LUN, NVMe, quiesce, quiescing, pause, namespace, flash storage 
summary: ONTAP 简介以及当前客户的一些术语变更 
---
= 关键概念
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
NetApp ONTAP 是 NetApp 经验证的数据管理软件。您可以在数据中心中使用 NetApp 设计的硬件，商用硬件或任何主要公有云运行 ONTAP 。



== 关于 System Manager

System Manager （以前称为 OnCommand System Manager ）是一款简单而多功能的产品，可帮助您轻松配置和管理 ONTAP 集群。System Manager 可简化常见存储任务，例如创建卷， LUN ， qtree ，共享和导出， 这样可以节省时间并防止出现错误。

从 ONTAP 9.7 开始，全新设计的 System Manager 通过直观的图形用户界面简化了 ONTAP 管理，该界面可提供：

* 快速，简单的配置
+
简化了 ONTAP 设置和管理常见任务的工作流。

* SMART 默认值
+
使您能够基于经验证的部署创建最佳实践配置。

* 丰富的管理功能
+
为文件共享，应用程序和数据库工作负载轻松配置和配置存储。

* 集成管理 System Manager 与 ONTAP 9 平台捆绑在一起，无需单独安装。一个新信息板，可在一个屏幕上显示关键集群状态和性能。


System Manager 可让您清晰地查看集群状态，并指导您找到实现存储目标的最佳方式。

如果您熟悉 ONTAP 的早期版本，您将感到像在家里一样。您应注意 System Manager 的一些术语更改。

* * 本地层 * —存储数据的一组物理固态驱动器或硬盘驱动器。您可能知道这些是聚合。实际上，如果使用 ONTAP 命令行界面，您仍会看到用于表示本地层的术语 _aggregate_ 。
* * 云层 * —当您出于多种原因之一希望将某些数据置于外部时， ONTAP 所使用的云中存储。如果您考虑的是 FabricPool 的云部分，您已经了解到了。如果您使用的是 StorageGRID 系统，则您的云可能根本不在内部环境中。（在内部环境中享受类似于云的体验称为 _private cloud _ 。）
* * Storage VM* —在 ONTAP 中运行的虚拟机，可为客户端提供存储和数据服务。您可能会将其识别为 _svm_ 或 _vserver_ 。
* * 网络接口 * —分配给物理网络端口的地址和属性。您可能会将此接口称为 _logical interface （ LIF ） _ 。
* * 暂停 * —暂停操作的操作。在 ONTAP 9.8 之前，您可能已经在其他版本的 System Manager 中引用了 _quiesce.


如果您是 ONTAP 的新用户，还可以通过以下几个概念快速掌握相关信息。

* * 集群 * —这是一个大图。一个集群由一个或多个节点组成。将节点视为专门从事数据管理和存储的计算机。您可以根据需要增加向集群添加节点，也可以将较小的节点替换为较大的节点。当然，这一切都不会中断对数据的访问。
* * Snapshot 副本 * —这些副本是数据的即时副本，您可以使用它们来撤消错误，移动或备份到云，镜像到另一个集群，甚至复制到磁带。而不会中断客户端。谁能承受停机？
* * 数据保护 * —您使用的保护功能取决于您需要防范的内容以及出现问题时需要等待多长时间才能恢复。ONTAP 提供同步和异步镜像等功能。
* * 高可用性对 * —谈到避免停机，高可用性对是 ONTAP 集群的基本单元。它由两个配对节点组成，它们可以相互接管。假设您希望升级到最新版本的 ONTAP ，以获得一项出色的新数据管理功能。只需让配对节点接管节点的客户端负载，升级该客户端，然后交还负载即可。对配对节点重复上述步骤，您刚刚升级，没有任何中断。
* * 存储效率 * —磁盘成本高昂（实际成本！），但存储效率可让您在更少的空间中存储更多数据。这样可以节省实际资金，让您成为数据英雄。您可以使用 ONTAP 的任何或所有数据压缩，重复数据删除和数据缩减功能。我们相信您已经知道什么是数据压缩。重复数据删除可识别同一数据的多个副本，并使用指向单个副本的指针替换重复的副本。数据缩减会将多个小文件放入一个存储块中，从而填充原本会浪费的空间。
* * 安全性 * —安全性是 ONTAP 数据管理软件不可或缺的组成部分。ONTAP 可通过多种方式帮助您解决问题，例如，对管理员使用多因素身份验证，对磁盘上和传输中的数据进行加密以及使用防病毒工具保护 Windows 文件。
* * 卷 * —正是您所认为的卷。它们是用于存储文件的容器。您可以将卷导出到 Linux 客户端，与 Windows 客户端共享卷，甚至可以同时使用相同的文件同时执行这两者。
* * LUN * — SAN 的基本单元。这就是光纤通道和 iSCSI 。在 SAN 环境中， ONTAP 为客户端提供虚拟磁盘，而不是文件。数据库管理员通常需要能够在较低级别管理或应用专用文件系统的虚拟磁盘。许多 ONTAP 系统（但并非所有系统）都可以为 SAN 客户端提供数据。
* * NVMe 命名空间 * —闪存存储的未来。NVMe 协议针对基于 SSD 的存储进行了优化，速度非常快。NVMe 是 SAN 的一种模式，但基本存储单元称为 _namespacage_ ，而不是 LUN 。


现在，您已了解 ONTAP 的基础知识，并且已准备好开始工作。请阅读以下各节，了解如何使用 System Manager 设置和管理集群。

如果您想了解更多信息，请查看 ONTAP link:link:../concepts/index.html["概念指南"]。加入 NetApp 社区。只需单击四周即可查看其他内容。



== System Manager 用例视频

video::PrpfVnN3dyk[youtube, width=848,height=480]