---
settings:
  name: ONTAP 9
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  search: ontap, ontap-metrocluster, ontap-sm-classic, ontap-fli, ontap-flexarray,
    ontap-automation, ontap-cli-9111, ontap-ems-9111
  langs: zh-cn,us-en,ja-jp,zh-tw,ko-kr
sidebar:
  entries:
  - title: ONTAP 文档
    url: "/index.html"
  - title: 发行说明
    url: "/release-notes.html"
  - section: introduction-concepts
  - section: setup-upgrade
  - section: cluster-admin
  - section: volume-admin
  - section: network-management
  - section: nas-management
  - section: san-management
  - section: object-storage-management
  - section: security-encryption
  - section: data-protection-disaster-recovery
  - section: event-performance-monitoring
  - title: ONTAP 手册页
    url: "/concepts/manual-pages.html"
  - title: 法律声明
    url: "/reference_legal_notices.html"
