---
sidebar:
  entries:
  - title: ONTAP 主页
    url: "/index.html"
  - title: ONTAP 的主要概念
    url: "/concept_key_ontap.html"
  - section: software_setup
  - section: upgrade
  - section: revert
  - section: networking
  - section: high-availability
  - section: smbc
  - title: 配置 SAN 存储
    url: "/concept_san_provision_overview.html"
    entries:
    - title: VMware 数据存储库
      url: "/task_san_provision_vmware.html"
    - title: Linux 服务器
      url: "/task_san_provision_linux.html"
    - title: Windows 服务器
      url: "/task_san_provision_windows.html"
    - title: 创建嵌套的 igroup
      url: "/task_san_create_nested_igroup.html"
    - title: 将 igroup 映射到多个 LUN
      url: "/task_san_map_igroups_to_multiple_luns.html"
    - title: SnapMirror 业务连续性概述
      url: "/concept_san_smbc_overview.html"
      entries:
      - title: 配置调解器
        url: "/task_san_configure_mediator.html"
      - title: 配置业务连续性保护
        url: "/task_san_configure_protection_for_business_continuity.html"
      - title: 在计划外故障转移后重新建立原始保护关系
        url: "/task_san_reestablish_original_relationship_after_unplanned_failover.html"
  - title: 配置 NVMe 存储
    url: "/concept_nvme_provision_overview.html"
    entries:
    - title: SUSE Linux
      url: "/task_nvme_provision_suse_linux.html"
  - title: 配置 NAS 存储
    url: "/concept_nas_provision_overview.html"
    entries:
    - title: VMware 数据存储库
      url: "/task_nas_provision_vmware.html"
    - title: 主目录
      url: "/task_nas_provision_home_directories.html"
    - title: Linux 服务器
      url: "/task_nas_provision_linux_nfs.html"
    - title: 导出策略
      url: "/task_nas_provision_export_policies.html"
    - title: Windows 服务器
      url: "/task_nas_provision_windows_smb.html"
    - title: Windows 和 Linux
      url: "/task_nas_provision_nfs_and_smb.html"
    - title: 使用 Kerberos 确保客户端访问安全
      url: "/task_nas_secure_client_access_with_kerberos.html"
    - title: 使用名称服务提供客户端访问
      url: "/task_nas_provide_client_access_with_name_services.html"
    - title: 使用 FlexGroup 的大型文件系统
      url: "/task_nas_provision_flexgroup.html"
    - title: 管理目录和文件
      url: "/task_nas_manage_directories_files.html"
    - title: 使用 ONTAP 文件系统分析监控卷使用情况
      entries:
      - title: 文件系统分析概述
        url: "/concept_nas_file_system_analytics_overview.html"
      - title: 启用文件系统分析
        url: "/task_nas_file_system_analytics_enable.html"
      - title: 查看文件系统活动
        url: "/task_nas_file_system_analytics_view.html"
      - title: 根据分析结果采取更正操作
        url: "/task_nas_file_system_analytics_take_corrective_action.html"
    - title: 监控 NFS 活动客户端
      url: "/task_nas_monitor_nfs_active_clients.html"
    - title: 提高多个客户端的性能
      url: "/task_nas_flexcache.html"
    - title: 启用 NAS 存储
      entries:
      - title: 启用 Linux 服务器
        url: "/task_nas_enable_linux_nfs.html"
      - title: 启用 Windows 服务器
        url: "/task_nas_enable_windows_smb.html"
      - title: 同时启用 Windows 和 Linux
        url: "/task_nas_enable_nfs_and_smb.html"
  - title: 配置对象存储
    url: "/concept_object_provision_overview.html"
    entries:
    - title: 启用 S3 服务器
      url: "/task_object_provision_enable_s3_server.html"
    - title: 配置存储分段
      url: "/task_object_provision_buckets.html"
    - title: 添加 S3 用户和组
      url: "/task_object_provision_add_s3_users_groups.html"
    - title: 管理存储分段访问
      url: "/task_object_provision_manage_bucket_access.html"
    - title: 管理 Storage VM 访问
      url: "/task_object_provision_manage_svm_access.html"
  - title: 使用配额管理资源
    url: "/concept_quotas_overview.html"
    entries:
    - title: 限制资源使用
      url: "/task_quotas_to_limit_resources.html"
  - title: 最大限度地提高安全性
    url: "/concept_security_overview.html"
    entries:
    - title: 多因素身份验证
      url: "/task_security_mfa_setup.html"
    - title: 控制管理员访问
      url: "/task_security_administrator_access.html"
    - title: 加密存储的数据（软件）
      url: "/task_security_encrypt_stored_data_sw.html"
    - title: 加密存储的数据（硬件）
      url: "/task_security_encrypt_stored_data_hw.html"
    - title: 诊断并更正文件访问问题
      url: "/task_security_file_access_issues.html"
  - title: 保护数据
    url: "/concept_dp_overview.html"
    entries:
    - title: 创建自定义数据保护策略
      url: "/task_dp_create_custom_data_protection_policies.html"
    - title: 配置 Snapshot 副本
      url: "/task_dp_configure_snapshot.html"
    - title: 从 Snapshot 副本恢复
      url: "/task_dp_recover_snapshot.html"
    - title: 准备镜像和存储
      url: "/task_dp_prepare_mirror.html"
    - title: 配置镜像和存储
      url: "/task_dp_configure_mirror.html"
    - title: 配置 Storage VM 灾难恢复
      url: "/task_dp_configure_storage_vm_dr.html"
    - title: 从目标提供数据
      url: "/task_dp_serve_data_from_destination.html"
    - title: 重新同步保护关系
      url: "/task_dp_restore_from_destination.html"
    - title: 从早期的 Snapshot 副本还原卷
      url: "/task_dp_restore_from_vault.html"
    - title: 还原到新卷
      url: "/task_dp_restore_to_new_volume.html"
    - title: 反向重新同步保护关系
      url: "/task_dp_reverse_resynch_a_destination_vm.html"
    - title: 重新激活源 Storage VM
      url: "/task_dp_reactivate_storage_vm.html"
    - title: 重新同步目标 Storage VM
      url: "/task_dp_resynch_a_destination_vm.html"
    - title: 备份到云
      url: "/task_dp_back_up_to_cloud.html"
  - title: 扩展到云
    url: "/concept_cloud_overview.html"
    entries:
    - title: 添加到云的连接
      url: "/task_add_connection_to_cloud.html"
    - title: 将数据分层到云
      url: "/task_cloud_tier_data.html"
    - title: 将数据分层到本地存储分段
      url: "/task_cloud_local_bucket_tier_data.html"
    - title: 创建分层对象标记
      url: "/task_cloud_create_tiering_object_tags.html"
    - title: 启用非活动数据报告
      url: "/task_cloud_enable_inactive_data_reporting.html"
    - title: 使用 Cloud Backup Service 备份数据
      url: "/task_cloud_backup_data_using_cbs.html"
    - title: 管理与 Cloud Backup Service 的连接
      url: "/task_cloud_manage_connection_to_cbs.html"
  - title: 查看集群性能
    url: "/concept_cluster_performance_overview.html"
    entries:
    - title: 信息板导览
      url: "/task_cp_dashboard_tour.html"
    - title: 识别热对象
      url: "/task_cp_id_hot_objects.html"
    - title: 使用 System Manager 监控集群性能
      url: "/task_cp_monitor_cluster_performance_sm.html"
    - title: 使用 Unified Manager 监控集群性能
      url: "/task_cp_monitor_cluster_performance_um.html"
    - title: 使用 Cloud Insights 监控集群性能
      url: "/task_cp_monitor_cluster_performance_ci.html"
  - title: 日常管理
    url: "/concept_administration_overview.html"
    entries:
    - title: 搜索，筛选和排序
      url: "/task_admin_search_filter_sort.html"
    - title: 启用新功能
      url: "/task_admin_enable_new_features.html"
    - title: 管理节点
      url: "/task_admin_manage_nodes.html"
    - title: 查看硬件配置并确定问题
      url: "/task_admin_troubleshoot_hardware_problems.html"
    - title: 查看并提交支持案例
      url: "/task_admin_view_submit_support_cases.html"
    - title: 监控风险
      url: "/task_admin_monitor_risks.html"
    - title: 管理 MetroCluster 站点
      url: "/concept_metrocluster_manage_nodes.html"
      entries:
      - title: 设置 MetroCluster 站点
        url: "/task_metrocluster_setup.html"
      - title: 设置 MetroCluster 对等
        url: "/task_metrocluster_peering.html"
      - title: 配置 MetroCluster 站点
        url: "/task_metrocluster_configure.html"
      - title: 执行 MetroCluster 切换和切回
        url: "/task_metrocluster_switchover_switchback.html"
      - title: 对 MetroCluster 问题进行故障排除
        url: "/task_metrocluster_troubleshooting.html"
    - title: 克隆数据
      url: "/task_admin_clone_data.html"
    - title: 修改 QoS
      url: "/task_admin_modify_qos.html"
    - title: 更新固件
      url: "/task_admin_update_firmware.html"
    - title: 管理存储
      entries:
      - title: 容量测量
        url: "/concept_capacity_measurements_in_sm.html"
      - title: 添加卷
        url: "/task_admin_add_a_volume.html"
      - title: 添加 LUN
        url: "/task_admin_add_luns.html"
      - title: 扩展存储
        url: "/task_admin_expand_storage.html"
        entries:
        - title: 磁盘
          url: "/task_admin_add_disks_to_local_tier.html"
        - title: 节点
          url: "/task_admin_add_nodes_to_cluster.html"
      - title: 管理存储效率策略
        url: "/task_admin_manage_storage_efficiency_policies.html"
      - title: 恢复已删除的卷
        url: "/task_admin_recover_deleted_volumes.html"
      - title: 节省存储空间
        url: "/task_admin_save_storage_space.html"
      - title: 通过移动 LUN 平衡负载
        url: "/task_admin_balance_load_by_moving_luns.html"
      - title: 通过将卷移动到另一层来平衡负载
        url: "/task_admin_balance_load_by_moving_volumes.html"
      - title: 使用 Ansible 攻略手册添加或编辑卷或 LUN
        url: "/task_admin_use_ansible_playbooks_add_edit_volumes_luns.html"
  - title: REST API
    entries:
    - title: REST 日志概述
      url: "/concept_rest_overview.html"
    - title: 访问 REST API 日志
      url: "/task_rest_access_log.html"
  - title: 获取更多信息
    url: "/concept_get_more_information.html"
  - title: 通知
    url: "/reference_legal_notices.html"
