---
sidebar: sidebar 
permalink: sysmgr-integration-bluexp-concept.html 
keywords: netapp, ontap, system manager, experience, integrate, integration, bluexp, hybrid, cloud, dashboard, multicloud 
summary: 从ONTAP 9.12.1开始、System Manager与BlueXP完全集成。  借助BlueXP、您可以从一个控制平台管理混合多云基础架构、同时保留熟悉的System Manager信息板。 
---
= System Manager与BlueXP集成
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
从ONTAP 9.12.1开始、System Manager与BlueXP完全集成。  借助BlueXP、您可以从一个控制平台管理混合多云基础架构、同时保留熟悉的System Manager信息板。



== 集成概述

在运行ONTAP 9.12.1或更高版本并连接到BlueXP服务的内部ONTAP 集群上访问System Manager时、系统将提示您直接从BlueXP管理此集群。从BlueXP中、您可以访问您习惯使用的System Manager界面、并可访问BlueXP功能。

借助BlueXP、您可以创建和管理云存储(例如Cloud Volumes ONTAP)、使用NetApp的数据服务(例如Cloud Backup)以及控制许多内部和边缘存储设备。



== 从BlueXP管理ONTAP 集群

当您准备好从BlueXP管理ONTAP 集群时、您可以单击尝试访问System Manager时显示的链接、也可以直接转到BlueXP。如果您希望使用BlueXP的数据服务来备份数据、扫描数据并对其进行分类等、直接使用BlueXP就可以获得优势。



=== 使用System Manager中的链接

当您从Web浏览器连接到集群管理网络接口时、系统将提示您在BlueXP中使用System Manager或随ONTAP系统安装的System Manager版本管理集群。

要在BlueXP中使用System Manager、请执行以下步骤：

.步骤
. 打开Web浏览器并输入集群管理网络接口的IP地址。
+
如果集群已连接到BlueXP、则会显示登录提示。

. 单击*继续到BlueXp *以访问BlueXP链接。
+

NOTE: 如果您的系统设置已阻止外部网络、您将无法访问BlueXP。  要使用BlueXP访问System Manager、必须确保您的系统可以访问地址"`cloudmanager.cloud.netapp.com`"。  否则、您可以在提示符处选择使用随ONTAP系统安装的System Manager版本。

. 在BlueXP登录页面上、选择*使用您的NetApp 支持站点 凭据登录*并输入您的凭据。
+
如果您已经使用了BlueXP并使用了电子邮件和密码进行了登录、则需要继续使用该登录选项。

+
https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-logging-in.html["了解有关登录到BlueXP的更多信息"^]。

. 如果出现提示、请输入新BlueXP帐户的名称。
+
在大多数情况下、BlueXP会根据集群中的数据自动为您创建一个帐户。

. 输入集群的集群管理员凭据。


.结果
此时将显示System Manager、您现在可以从BlueXP管理集群。



=== 直接从BlueXP发现集群

BlueXP提供了两种发现和管理集群的方法：

* 直接发现、以便通过System Manager进行管理
+
此发现选项与上一节中所述的相同、您可以使用此选项执行重定向。

* 通过Connector进行发现
+
Connector是安装在您环境中的软件、可用于通过System Manager访问管理功能、还可访问提供数据复制、备份和恢复、数据分类、数据分层等功能的BlueXP云服务。



转至 https://docs.netapp.com/us-en/cloud-manager-family/index.html["BlueXP文档"^] 了解有关这些发现和管理选项的更多信息。



== 了解有关BlueXP的更多信息

* https://docs.netapp.com/us-en/cloud-manager-family/concept-overview.html["BlueXP概述"^]
* https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/index.html["通过BlueXP管理您的NetApp AFF 和FAS 系统"^]

