---
sidebar: sidebar 
permalink: task_nas_file_system_analytics_view.html 
keywords: explorer, file system analytics, inactive data, capacity analytics, active data, historical data 
summary: 启用文件系统分析后，您可以通过资源管理器屏幕查看容量分析，设置非活动数据时间段以及浏览有关文件系统的其他数据。 
---
= 在ONTAP中查看文件系统活动
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
启用文件系统分析(File System Analytics、FSA)后、您可以按每个子树中使用的空间排序、查看选定卷的根目录内容。

选择任何文件系统对象以浏览文件系统并显示有关目录中每个对象的详细信息。有关目录的信息也可以以图形方式显示。随着时间的推移，会显示每个子树的历史数据。如果目录数超过 3000 个，则不会对已用空间进行排序。



== 资源管理器

文件系统分析 * 资源管理器 * 屏幕包含三个区域：

* 目录和子目录的树视图；显示名称，大小，修改历史记录和访问历史记录的可扩展列表。
* 文件；显示目录列表中选定对象的名称，大小和访问时间。
* 目录列表中选定对象的活动和非活动数据比较。
+
从 ONTAP 9.1.1 开始，您可以自定义要报告的范围。默认值为一年。根据这些自定义设置，您可以采取更正操作，例如移动卷和修改分层策略。



默认情况下，会显示访问时间。但是、如果已通过命令行界面(通过设置 `-atime-update` 选项 `false` 使用 `volume modify` 命令)、则仅显示上次修改时间。例如：

* 树视图不会显示 * 访问历史记录 * 。
* 文件视图将被更改。
* 活动/非活动数据视图将基于修改后的时间 (`mtime`）。


使用这些显示，您可以检查以下内容：

* 文件系统位置占用的空间最多
* 有关目录树的详细信息，包括目录和子目录中的文件和子目录计数
* 包含旧数据的文件系统位置（例如， Scratch ， temp 或日志树）


解释 FSA 输出时，请记住以下几点：

* FSA 将显示数据在何处以及何时使用，而不是显示正在处理的数据量。例如，最近访问或修改的文件占用的空间较大并不一定表示系统处理负载较高。
* * 卷资源管理器 * 选项卡计算 FSA 空间消耗的方式可能与其他工具不同。特别是，如果卷启用了存储效率功能，则与 * 卷概述 * 中报告的使用量可能会有显著差异。这是因为 * 卷资源管理器 * 选项卡不包括效率节省。
* 由于目录显示中的空间限制，无法在 _List View_ 中查看超过 8 个级别的目录深度。要查看深度超过 8 个级别的目录，必须切换到 _Graphical View_ ，找到所需的目录，然后切换回 _List View_ 。这样可以在显示中留出更多的屏幕空间。


.步骤
. 查看选定卷的根目录内容：
+
[cols="2"]
|===
| 在 ONTAP 9.8 和 9.9.1 中 | 从ONTAP 9.10.1开始 


| 单击 * 存储 > 卷 * ，选择所需的卷，然后单击 * 资源管理器 * 。 | 选择 * 存储 > 卷 * ，然后选择所需的卷。从单个卷菜单中，选择 * 文件系统 > 资源管理器 * 。 
|===

