---
sidebar: sidebar 
permalink: task_admin_monitor_capacity_in_sm.html 
keywords: used storage, digital advisor, local tier capacity, aggregate capacity, add capacity, used capacity, available, total capacity, inactive data, overprovision, overflows, snapshot copy reserves, reserves, clone, maximum capacity limit, storage VM, allocate 
summary: 您可以使用System Manager监控集群、本地层或Storage VM已使用的存储容量以及仍可用的存储容量。 
---
= 在ONTAP系统管理器中监控集群、层和SVM容量
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用System Manager监控集群、本地层或Storage VM已使用的存储容量以及仍可用的存储容量。

对于每个版本的ONTAP 、System Manager均可提供更强大的容量监控信息：

* 从ONTAP 9.13.1开始、您可以为Storage VM启用最大容量限制、并设置一个阈值、以便在已用存储达到最大容量的特定百分比时触发警报。
* 从ONTAP 9.12.1开始、System Manager将显示本地层的已提交容量。
* 从ONTAP 9.10.1开始、您可以通过System Manager查看有关集群容量的历史数据、以及有关未来将使用或可用容量的预测。您还可以监控本地层和卷的容量。



NOTE: 根据您的ONTAP 版本、已用容量测量值的显示方式会有所不同。要了解更多信息，请访问link:./concepts/capacity-measurements-in-sm-concept.html["System Manager 中的容量测量"]。



== 查看集群的容量

您可以在System Manager的信息板上查看集群的容量测量结果。

.开始之前
要查看与云中容量相关的数据、您必须在Digital Advisor中拥有一个帐户并保持连接。

.步骤
. 在 System Manager 中，单击 * 信息板 * 。
. 在 * 容量 * 部分中，您可以查看以下内容：
+
--
** 集群的已用总容量
** 集群的总可用容量
** 已用容量和可用容量的百分比。
** 数据精简比率。
** 云中使用的容量。
** 容量使用历史记录。
** 容量使用量预测


--
+

NOTE: 在 System Manager 中，容量表示不考虑根存储层（聚合）容量。

. 单击图表可查看有关集群容量的更多详细信息。
+
容量测量结果显示在两个条形图中：

+
--
** 顶部图表显示物理容量：已用物理空间、预留空间和可用空间的大小。
** 底部图表显示逻辑容量：客户端数据、快照和克隆的大小以及总逻辑已用空间。


--
+
条形图下方是数据精简的测量值：

+
--
** 仅客户端数据的数据精简率(不包括快照和克隆)。
** 整体数据精简率。


--


有关详细信息，请参见 link:./concepts/capacity-measurements-in-sm-concept.html["System Manager 中的容量测量"]。



== 查看本地层的容量

您可以查看本地层容量的详细信息。从ONTAP 9.12.1 开始，“容量”视图还包含本地层的已提交容量，以便您确定是否需要向本地层添加容量以容纳已提交的容量并避免可用空间耗尽。

.步骤
. 单击 * 存储 > 层 * 。
. 选择本地层的名称。
. 在*概述*页面的*容量*部分中、容量显示在一个条形图中、其中包含三个测量值：
+
** 已用容量和预留容量
** Available capacity
** 已提交容量(从ONTAP 9.12.1开始)


. 单击图表可查看有关本地层容量的详细信息。
+
容量测量结果显示在两个条形图中：

+
--
** 顶部条形图显示物理容量：已用物理空间、预留空间和可用空间的大小。
** 底部条形图显示逻辑容量：客户端数据、快照和克隆的大小以及已用逻辑空间总量。


--
+
条形图下方是数据精简的测量比率：

+
--
** 仅客户端数据的数据精简率(不包括快照和克隆)。
** 整体数据精简率。


--


有关详细信息，请参见 link:./concepts/capacity-measurements-in-sm-concept.html["System Manager 中的容量测量"]。

.可选操作
* 如果已提交容量大于本地层的容量、您可以考虑在本地层的可用空间不足之前向其添加容量。  请参见 link:./disks-aggregates/add-disks-local-tier-aggr-task.html["向本地层添加容量(向聚合添加磁盘)"]。
* 您还可以通过选择*卷*选项卡来查看特定卷在本地层中使用的存储。




== 查看Storage VM中卷的容量

您可以查看Storage VM中的卷已使用的存储容量以及仍然可用的容量。已用存储和可用存储的总体衡量指标称为"卷间容量"。

.步骤
. 选择*存储*>*存储VM*。
. 单击Storage VM的名称。
. 滚动到*Capacity (*容量*)部分，该部分将显示一个包含以下测量值的条形图：
+
--
** *已用物理空间*：此Storage VM中所有卷的已用物理空间之和。
** *可用*：此Storage VM中所有卷的可用容量之和。
** *逻辑使用量*：此Storage VM中所有卷的已用逻辑存储之和。


--


有关测量的更多详细信息、请参见 link:./concepts/capacity-measurements-in-sm-concept.html["System Manager 中的容量测量"]。



== 查看Storage VM的最大容量限制

从ONTAP 9.13.1开始、您可以查看Storage VM的最大容量限制。

.开始之前
您必须 link:manage-max-cap-limit-svm-in-sm-task.html["启用Storage VM的最大容量限制"] 才能查看。

.步骤
. 选择*存储*>*存储VM*。
+
您可以通过两种方式查看最大容量测量值：

+
--
** 在Storage VM对应的行中、查看*最大容量*列、其中包含一个条形图、用于显示已用容量、可用容量和最大容量。
** 单击Storage VM的名称。在*Overview*选项卡上，滚动以在左列中查看最大容量、已分配容量和容量警报阈值。


--


.相关信息
* link:manage-max-cap-limit-svm-in-sm-task.html#edit-max-cap-limit-svm["编辑Storage VM的最大容量限制"]
* link:./concepts/capacity-measurements-in-sm-concept.html["System Manager 中的容量测量"]

