---
sidebar: sidebar 
permalink: task_metrocluster_troubleshooting.html 
keywords: troubleshoot, error, event, problem, metrocluster, maintenance, fix, correction, health, check 
summary: 您可以从一个 MetroCluster 站点切换到另一个站点，以执行维护或从问题描述恢复。 
---
= 对 IP MetroCluster 配置问题进行故障排除
:toc: macro
:hardbreaks:
:toclevels: 1
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
从 ONTAP 9.8 开始， System Manager 可监控 IP MetroCluster 配置的运行状况，并帮助您确定和更正可能发生的问题。



== MetroCluster 运行状况检查概述

System Manager 会定期检查 IP MetroCluster 配置的运行状况。在信息板中查看 MetroCluster 部分时，通常会显示消息 MetroCluster systems are healthy 。

但是，发生问题时，此消息将显示事件数量。您可以单击该消息并查看以下组件的运行状况检查结果：

* 节点
* 网络接口
* 层（存储）
* 集群
* 连接
* 卷
* 配置复制


"* 状态 * " 列用于标识存在问题的组件， "* 详细信息 * " 列用于建议如何更正问题。



== MetroCluster 故障排除

.步骤
. 在 System Manager 中，选择 * 信息板 * 。
. 在 * MetroCluster * 部分中，请注意此消息。
+
.. 如果此消息指示您的 MetroCluster 配置运行状况良好，并且集群与 ONTAP 调解器之间的连接运行状况良好（显示时带有复选标记），则表示您没有问题需要更正。
.. 如果消息列出了事件数量，或者连接已断开（显示为 "X" ），则继续执行下一步。


. 单击显示事件数量的消息。
+
此时将显示 MetroCluster 运行状况报告。

. 使用 * 详细信息 * 列中的建议对报告中显示的问题进行故障排除。
. 更正完所有问题后，单击 * 检查 MetroCluster 运行状况 * 。
+

NOTE: MetroCluster 运行状况检查会占用大量资源，因此建议您在运行检查之前执行所有故障排除任务。

+
MetroCluster 运行状况检查在后台运行。您可以在等待其他任务完成的同时处理这些任务。


