---
sidebar: sidebar 
permalink: task_admin_monitor_risks.html 
keywords: system manager, monitor, risk, risks, suggestion, suggestions, mitigate, digital advisor, active iq, category, categories, mitigation, impact, impacts, corrections, corrective action, corrective actions, acknowledge risk, dismiss, undismiss, restore, unacknowledge 
summary: 将System Manager与ONTAP 9．10．0或更高版本结合使用，您可以监控由数字顾问报告的风险。 
---
= 监控风险
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
从SystemManager.10.0开始、您可以使用ONTAP 9监控Active IQ数字顾问(也称为数字顾问)报告的风险。从 ONTAP 9.10.1 开始，您还可以使用 System Manager 确认风险。

NetApp数字顾问报告了降低风险并提高存储环境性能和效率的机会。借助System Manager、您可以了解由Digital Advisor报告的风险、并获得可指导行动的智能信息、帮助您管理存储、实现更高的可用性、更高的安全性和更好的存储性能。



== 链接到您的Digital Advisor帐户

要从Digital Advisor接收有关风险的信息、您应首先从System Manager链接到您的Digital Advisor帐户。

.步骤
. 在 System Manager 中，单击 * 集群 > 设置 * 。
. 在 * 注册 Active IQ * 下，单击 * 注册 * 。
. 输入您的Digital Advisor凭据。
. 凭据通过身份验证后，单击 * 确认以将 Active IQ 与 System Manager* 链接起来。




== 查看风险数量

从ONTAP 9 10.0开始、您可以从System Manager中的信息板查看由数字顾问报告的风险数。

.开始之前
您必须建立从System Manager到Digital Advisor帐户的连接。请参阅 <<link_active_iq,链接到您的Digital Advisor帐户>>。

.步骤
. 在 System Manager 中，单击 * 信息板 * 。
. 在 * 运行状况 * 部分中，查看报告的风险数量。
+

NOTE: 您可以通过单击显示风险数量的消息来查看有关每个风险的更多详细信息。  请参见 <<view_risk_details,查看风险详细信息>>。





== 查看风险详细信息

从ONTAP 9。10.0开始、您可以从System Manager中查看数字顾问报告的风险如何按影响区域进行分类。此外，您还可以查看有关每个已报告风险，其对系统的潜在影响以及可以采取的更正操作的详细信息。

.开始之前
您必须建立从System Manager到Digital Advisor帐户的连接。请参阅 <<link_active_iq,链接到您的Digital Advisor帐户>>。

.步骤
. 单击 * 事件 > 所有事件 * 。
. 在 * 概述 * 部分的 * Active IQ 建议 * 下，查看每个影响区域类别中的风险数量。风险类别包括：
+
** 性能和效率
** 可用性和保护
** Capacity
** Configuration
** 安全性


. 单击 * Active IQ suggestions * 选项卡可查看有关每个风险的信息，包括以下信息：
+
** 对系统的影响级别
** 风险的类别
** 受影响的节点
** 所需的缓解类型
** 您可以采取的更正操作






== 确认风险

从 ONTAP 9.10.1 开始，您可以使用 System Manager 确认任何未结风险。

.步骤
. 在 System Manager 中，通过在中执行操作步骤来显示风险列表 <<view_risk_details,查看风险详细信息>>。
. 单击要确认的未结风险的风险名称。
. 在以下字段中输入信息：
+
** 提醒（日期）
** 理由
** 注释


. 单击 * 确认 * 。
+

NOTE: 确认风险后、需要几分钟时间、此更改才会反映在Digital Advisor建议列表中。





== 取消确认风险

从 ONTAP 9.10.1 开始，您可以使用 System Manager 取消确认先前确认的任何风险。

.步骤
. 在 System Manager 中，通过在中执行操作步骤来显示风险列表 <<view_risk_details,查看风险详细信息>>。
. 单击要取消确认的已确认风险的风险名称。
. 在以下字段中输入信息：
+
** 理由
** 注释


. 单击 * 取消确认 * 。
+

NOTE: 取消确认风险后、需要几分钟时间、此更改才会反映在Digital Advisor建议列表中。


