---
sidebar: sidebar 
permalink: task_metrocluster_peering.html 
keywords: metrocluster, peer, peering, pair, pairing, configuration, config, mcc, HA 
summary: 从 ONTAP 9.8 开始，您可以使用 System Manager 管理 IP MetroCluster 站点操作。设置两个集群后，您可以在它们之间建立对等关系。 
---
= 设置 IP MetroCluster 对等
:toc: macro
:hardbreaks:
:toclevels: 1
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
从 ONTAP 9.8 开始，您可以使用 System Manager 管理 MetroCluster 操作的 IP 配置。设置两个集群后，您可以在它们之间建立对等关系。

要设置两个集群，您应已完成以下操作步骤：

* link:task_metrocluster_setup.html["设置 IP MetroCluster 站点"]


此过程的某些步骤由位于每个集群的地理站点的不同系统管理员执行。为了解释此过程，这些集群称为 " 站点 A 集群 " 和 " 站点 B 集群 " 。



== 从站点 A 执行对等过程

此过程由站点 A 的系统管理员执行

.步骤
. 登录到站点 A 集群。
. 在 System Manager 中，从左侧导航列中选择 * 信息板 * 以显示集群概述。
+
信息板显示此集群（站点 A ）的详细信息。在 * MetroCluster 站点 A 集群 * 部分中，站点 A 集群显示在左侧。

. 单击 * 附加配对集群 * 。
. 输入允许站点 A 集群中的节点与站点 B 集群中的节点进行通信的网络接口的详细信息。
. 单击 * 保存并继续 * 。
. 在 * 附加合作伙伴集群 * 窗口中，选择 * 我没有密码短语 * ，可用于生成密码短语。
. 复制生成的密码短语并与站点 B 的系统管理员共享
. 选择 * 关闭 * 。




== 从站点 B 执行对等过程

此过程由站点 B 的系统管理员执行

.步骤
. 登录到站点 B 集群。
. 在 System Manager 中，选择 * 信息板 * 以显示集群概述。
+
信息板显示此集群（站点 B ）的详细信息。在 MetroCluster 部分中，站点 B 集群显示在左侧。

. 单击 * 附加配对集群 * 以启动对等过程。
. 输入允许站点 B 集群中的节点与站点 A 集群中的节点进行通信的网络接口的详细信息。
. 单击 * 保存并继续 * 。
. 在 * 附加配对集群 * 窗口中，选择 * 我有密码短语 * ，可用于输入从站点 A 的系统管理员处收到的密码短语
. 选择 * 对等 * 以完成对等过程。


成功完成对等过程后，您可以配置集群。请参见 link:task_metrocluster_configure.html["配置 IP MetroCluster 站点"]。
