---
sidebar: sidebar 
permalink: task_cp_monitor_cluster_performance_ci.html 
keywords: netapp, ontap, cluster, performance, monitor, monitoring, headroom, cpu, cpus, data infrastructure insights, troubleshoot, optimize, private data center, Kafka, MongoDB, Nginx, Active IQ Unified Manager, cluster performance, monitor performance 
summary: 借助数据基础设施洞察，您可以监控、排除故障并优化所有资源，包括公共云和私有数据中心。 
---
= 使用 ONTAP 数据基础架构洞察监控集群性能
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp 数据基础架构洞察是一款监控工具，可让您深入了解整个基础架构。借助数据基础架构洞察，您可以监控、排除故障并优化所有资源，包括公有云和私有数据中心。



== 监控，故障排除和优化所有资源

数据基础设施洞察可帮助您显著减少解决问题的时间并防止问题影响最终用户。它还可以帮助您降低云基础架构成本。通过利用可操作的智能来保护数据，可以减少您遭受内部威胁的风险。

数据基础设施洞察让您可以在一个地方查看整个混合基础设施 - 从公共云到数据中心。您可以即时创建相关信息板，以便根据您的特定需求进行自定义。此外，您还可以创建特定于您的组织需求并与之相关的有针对性和条件警报。

高级异常检测功能可帮助您在问题出现之前主动修复问题。  您可以自动查看资源争用和降级情况，以快速还原受影响的工作负载。  通过堆栈中不同组件之间自动构建的关系层次结构，故障排除速度更快。

您可以确定整个环境中未使用或已废弃的资源，从而帮助您发现调整基础架构规模并优化整个支出的机会。

数据基础设施洞察可视化您的系统拓扑，以了解您的 Kubernetes 架构。您可以监控 Kubernetes 集群的运行状况，包括出现故障的节点，并在发现问题时放大。

数据基础设施洞察通过先进的机器学习和异常检测为您提供有关内部威胁的可操作情报，帮助您保护组织数据免遭恶意或受感染用户的滥用。

数据基础设施洞察可帮助您可视化 Kubernetes 指标，以便您可以充分了解 pod、节点和集群之间的关系。您可以评估集群或工作 Pod 的运行状况及其当前正在处理的负载，从而对 K8S 集群执行命令并控制部署的运行状况和成本。

.相关链接
* link:https://docs.netapp.com/us-en/cloudinsights/task_cloud_insights_onboarding_1.html["开始使用数据基础设施洞察"^]

