---
sidebar: sidebar 
permalink: task_admin_view_submit_support_cases.html 
keywords: support, case, view, submit, active iq, telemetry, log, logging 
summary: 从 ONTAP 9.1.1 开始，您可以从 Active IQ 查看与集群关联的支持案例，并查看提交新支持案例所需的信息。从ONTAP 9.10.1开始、您可以启用遥测日志记录、这有助于支持人员排除问题。 
---
= 查看并提交支持案例
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
从 ONTAP 9.1.1 开始，您可以从与集群关联的 Active IQ 查看支持案例。您还可以复制在 NetApp 支持站点上提交新支持案例所需的集群详细信息。
从ONTAP 9.10.1开始、您可以启用遥测日志记录、这有助于支持人员排除问题。


NOTE: 要接收有关固件更新的警报、您必须向Active IQ Unified Manager 注册。请参见 link:https://netapp.com/support-and-training/documentation/active-iq-unified-manager["Active IQ Unified Manager 文档资源"^]。

.步骤
. 在 System Manager 中，选择 * 支持 * 。
+
此时将显示与此集群关联的已打开支持案例列表。

. 单击以下链接可执行相关过程：
+
** * 案例编号 * ：查看案例详细信息。
** *转至 NetApp 支持站点*：导航到 NetApp 支持站点上的 *我的 AutoSupport* 页面可查看知识库文章或提交新的支持案例。
** *查看我的案例*：导航到 NetApp 支持站点上的 *我的案例* 页面。
** * 查看集群详细信息 * ：查看和复制提交新案例时需要的信息。






== 启用遥测日志记录

从ONTAP 9.10.1开始、您可以使用System Manager启用遥测日志记录。  如果允许进行遥测日志记录、则System Manager记录的消息会获得一个特定的遥测标识符、用于指示触发该消息的确切过程。  与该进程相关的所有消息都具有相同的标识符、其中包括操作工作流的名称和一个数字(例如"add-volume-1941290")。

如果您遇到性能问题、可以启用遥测日志记录、这样支持人员就可以更轻松地确定发出消息的特定过程。  在消息中添加遥测标识符后、日志文件仅会略微放大。

.步骤
. 在System Manager中、选择*集群>设置*。
. 在*用户界面设置*部分中、单击*允许遥测日志记录*复选框。

