---
sidebar: sidebar 
permalink: task_nas_flexcache.html 
keywords: netapp, ontap, flexcache, flexcache volume, offload traffic, work load, workload, access speed 
summary: 您可以使用 FlexCache 卷加快数据访问速度，或者从访问量较多的卷卸载流量。FlexCache 卷非常适合读取密集型工作负载，尤其是客户端需要重复访问相同数据的工作负载。 
---
= 使用 FlexCache 提高多个客户端的性能
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
您可以使用 FlexCache 卷加快数据访问速度，或者从访问量较多的卷卸载流量。FlexCache 卷非常适合读取密集型工作负载，尤其是客户端需要重复访问相同数据的工作负载。

本节中的主题介绍如何在 ONTAP 9.7 及更高版本中使用 System Manager 管理 FlexCache 卷。如果您使用的是经典 System Manager （仅适用于 ONTAP 9.7 及更早版本），请参见以下主题：

* https://docs.netapp.com/us-en/ontap-sm-classic/online-help-96-97/task_creating_flexcache_volumes.html["创建 FlexCache 卷"^]


FlexCache 卷可以与远程卷位于同一集群中，也可以位于不同集群中。如果远程卷位于其他集群上，则需要已为集群和 Storage VM 建立对等关系。


NOTE: HA 对使用时 xref:../encryption-at-rest/support-storage-encryption-concept.html[加密 SAS 或 NVMe 驱动器（ SED ， NSE ， FIPS ）]，您必须按照主题中的说明进行操作 xref:../encryption-at-rest/return-seds-unprotected-mode-task.html[将 FIPS 驱动器或 SED 恢复到未受保护的模式] 初始化系统之前 HA 对中的所有驱动器（启动选项 4 或 9 ）。如果不这样做，则在重新利用驱动器时，可能会导致未来数据丢失。

.步骤
. 单击 * 存储 > 卷 * 。
. 单击 * 添加 * 。
. 单击 * 更多选项 * ，然后选择 * 添加为远程卷的缓存 * 。
+
.. 如果您运行的是 ONTAP 9.8 或更高版本，并且要禁用 QoS 或选择自定义 QoS 策略，请单击 * 更多选项 * ，然后在 * 存储和优化 * 下选择 * 性能服务级别 * 。




对于任何新的数据请求， FlexCache 卷会从远程卷请求数据并将其存储。之后，对数据的所有后续读取请求都会直接从 FlexCache 卷提供。



== 视频



=== FlexCache 如何降低全局数据的 WAN 延迟和读取时间

video::rbbH0l74RWc[youtube, width=848,height=480]


=== 了解 ONTAP FlexCache 的性能优势！

video::bWi1-8Ydkpg[youtube, width=848,height=480]