---
permalink: element-replication/create-custom-replication-policy-concept.html 
sidebar: sidebar 
keywords: create, custom, replication, policy 
summary: 如果关系的默认策略不适用，您可以创建自定义复制策略。例如，您可能希望在网络传输中压缩数据，或者修改 SnapMirror 尝试传输 Snapshot 副本的次数。 
---
= 创建自定义复制策略
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在创建复制关系时使用默认策略或自定义策略。对于自定义统一复制策略，您必须定义一个或多个 _rules_ 来确定初始化和更新期间传输的 Snapshot 副本。

如果关系的默认策略不适用，您可以创建自定义复制策略。例如，您可能希望在网络传输中压缩数据，或者修改 SnapMirror 尝试传输 Snapshot 副本的次数。

复制策略的 _policy type_ 决定了它支持的关系类型。下表显示了可用的策略类型。

[cols="2*"]
|===
| Policy type | 关系类型 


 a| 
异步镜像
 a| 
SnapMirror 灾难恢复



 a| 
镜像存储
 a| 
统一复制

|===
.步骤
. 创建自定义复制策略：
+
`snapmirror policy create -vserver _svm_ -policy policy -type async-mirror_mirror-vault -comment _compression_ -tr尝试 _transfer_try_-transfer-priority low_normal -is-network-compression-enabled true_false`

+
有关完整的命令语法，请参见手册页。

+
从 ONTAP 9.5 开始，您可以使用 ` -common-snapshot-schedule` 参数指定为 SnapMirror 同步关系创建通用 Snapshot 副本计划的计划。默认情况下， SnapMirror 同步关系的通用 Snapshot 副本计划为一小时。您可以为 SnapMirror 同步关系的 Snapshot 副本计划指定一个介于 30 分钟到两小时之间的值。

+
以下示例将为 SnapMirror 灾难恢复创建一个自定义复制策略，以便为数据传输启用网络压缩：

+
[listing]
----
cluster_dst::> snapmirror policy create -vserver svm1 -policy DR_compressed -type async-mirror -comment “DR with network compression enabled” -is-network-compression-enabled true
----
+
以下示例将为统一复制创建自定义复制策略：

+
[listing]
----
cluster_dst::> snapmirror policy create -vserver svm1 -policy my_unified -type mirror-vault
----


对于 " `mirror-vault` " 策略类型，您必须定义规则来确定初始化和更新期间传输的 Snapshot 副本。

使用 `snapmirror policy show` 命令验证是否已创建 SnapMirror 策略。有关完整的命令语法，请参见手册页。
