---
permalink: element-replication/create-relationship-element-destination-task.html 
sidebar: sidebar 
keywords: create, relationship, ontap, source, element, destination 
summary: 从 ONTAP 9.4 开始，您可以使用 SnapMirror 将在 ONTAP 源上创建的 LUN 的 Snapshot 副本复制回 Element 目标。您可能正在使用 LUN 将数据从 ONTAP 迁移到 Element 软件。 
---
= 创建从 ONTAP 源到 Element 目标的关系
:icons: font
:imagesdir: ../media/


[role="lead"]
从 ONTAP 9.4 开始，您可以使用 SnapMirror 将在 ONTAP 源上创建的 LUN 的 Snapshot 副本复制回 Element 目标。您可能正在使用 LUN 将数据从 ONTAP 迁移到 Element 软件。

.开始之前
* Element 目标节点必须可供 ONTAP 访问。
* 必须已为 Element 卷启用 SnapMirror 复制。


您必须以 ` _hostip ： //lun/_name_` 的形式指定元素目标路径，其中 "`lun` " 是实际字符串 "`lun` " ， `name` 是 Element 卷的名称。

复制规则如下：

* 复制关系的策略类型必须为 "`async-mirror` " 。
+
您可以使用默认策略或自定义策略。

* 仅支持 iSCSI LUN 。
* 不能将多个 LUN 从 ONTAP 卷复制到 Element 卷。
* 您不能将 LUN 从 ONTAP 卷复制到多个 Element 卷。


.步骤
. 创建从 ONTAP 源到 Element 目标的复制关系：
+
`snapmirror create -source-path _SVM ： volume___cluster ： //svm/volume_-destination-path _hostip ： //lun/_name_ -type XDP -schedule schedule -policy _policy_`

+
有关完整的命令语法，请参见手册页。

+
以下示例将使用默认的 `MirrorLatest` 策略创建 SnapMirror 灾难恢复关系：

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm_1:volA_dst -destination-path 10.0.0.11:/lun/0005 -type XDP -schedule my_daily -policy MirrorLatest
----
+
以下示例将使用自定义 `my_mirror` 策略创建 SnapMirror DR 关系：

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm_1:volA_dst -destination-path 10.0.0.11:/lun/0005 -type XDP -schedule my_daily -policy my_mirror
----


使用 `snapmirror show` 命令验证是否已创建 SnapMirror 关系。有关完整的命令语法，请参见手册页。
