---
permalink: element-replication/index.html 
sidebar: sidebar 
keywords: decide, replication, netapp element software, ontap, business continuity, element, system, snapmirror, replicate, snapshot, copies, volume 
summary: 此内容介绍如何使用 SnapMirror 将 Element 卷的 Snapshot 副本复制到 ONTAP 目标，以确保 Element 系统上的业务连续性。 
---
= NetApp Element 软件和 ONTAP 之间的复制概述
:icons: font
:imagesdir: ../media/


[role="lead"]
此内容介绍如何使用 SnapMirror 将 Element 卷的 Snapshot 副本复制到 ONTAP 目标，以确保 Element 系统上的业务连续性。如果 Element 站点发生灾难，您可以从 ONTAP 系统向客户端提供数据，然后在服务还原后重新激活 Element 系统。

从 ONTAP 9.4 开始，您可以将在 ONTAP 节点上创建的 LUN 的 Snapshot 副本复制回 Element 系统。您可能已在 Element 站点发生中断期间创建 LUN ，也可能正在使用 LUN 将数据从 ONTAP 迁移到 Element 软件。

如果要按以下方式使用 Element 到 ONTAP 备份，应使用此内容：

* 您希望使用最佳实践，而不是浏览每个可用选项。
* 您不想阅读大量概念背景信息。
* 您希望使用 ONTAP 命令行界面（ CLI ），而不是 ONTAP 系统管理器或自动脚本编写工具。
* 您正在使用 iSCSI 向客户端提供数据。


如果您需要其他配置或概念信息，请参见以下文档：

* 元素配置
+
https://docs.netapp.com/us-en/element-software/index.html["NetApp Element 软件文档"^]

* SnapMirror 概念和配置
+
link:../data-protection/index.html["数据保护概述"]





== 关于 Element 和 ONTAP 之间的复制

从 ONTAP 9.3 开始，您可以使用 SnapMirror 将 Element 卷的 Snapshot 副本复制到 ONTAP 目标。如果 Element 站点发生灾难，您可以从 ONTAP 系统向客户端提供数据，然后在服务还原后重新激活 Element 源卷。

从 ONTAP 9.4 开始，您可以将在 ONTAP 节点上创建的 LUN 的 Snapshot 副本复制回 Element 系统。您可能已在 Element 站点发生中断期间创建 LUN ，也可能正在使用 LUN 将数据从 ONTAP 迁移到 Element 软件。



=== 数据保护关系的类型

SnapMirror 提供两种类型的数据保护关系。对于每种类型， SnapMirror 都会在初始化或更新关系之前为 Element 源卷创建一个 Snapshot 副本：

* 在 _disaster recovery （ DR ） _ 数据保护关系中，目标卷仅包含由 SnapMirror 创建的 Snapshot 副本，在主站点发生灾难时，您可以从该副本继续提供数据。
* 在 _Long-Term Retretention_ 数据保护关系中，目标卷包含由 Element 软件创建的时间点 Snapshot 副本以及由 SnapMirror 创建的 Snapshot 副本。例如，您可能希望保留在 20 年期限内创建的每月 Snapshot 副本。




=== 默认策略

首次调用 SnapMirror 时，它会执行从源卷到目标卷的 _baseline transfer_ 。_snapmirror policy_ 用于定义基线内容以及任何更新。

您可以在创建数据保护关系时使用默认策略或自定义策略。策略类型 _ 可确定要包含的 Snapshot 副本以及要保留的副本数。

下表显示了默认策略。使用 `MirrorLatest` 策略创建传统 DR 关系。使用 `MirrorAndVault` 或 `Unified7year` 策略创建统一复制关系，在此关系中，在同一目标卷上配置 DR 和长期保留。

[cols="25,25,50"]
|===
| 策略 | Policy type | 更新行为 


 a| 
MirrorLatest
 a| 
异步镜像
 a| 
传输 SnapMirror 创建的 Snapshot 副本。



 a| 
MirrorAndVault
 a| 
镜像存储
 a| 
传输由 SnapMirror 创建的 Snapshot 副本以及自上次更新以来创建的任何较晚 Snapshot 副本，前提是它们具有 SnapMirror 标签 " `daily` " 或 "`weekly` " 。



 a| 
未指定 7 年
 a| 
镜像存储
 a| 
传输由 SnapMirror 创建的 Snapshot 副本以及自上次更新以来创建的任何较晚 Snapshot 副本，前提是它们具有 SnapMirror 标签 " `daily` " ， "`weekly` " 或 " `mweekly` " 。

|===
[NOTE]
====
有关 SnapMirror 策略的完整背景信息，包括要使用的策略的指导，请参见 link:../data-protection/index.html["数据保护"]。

====


=== 了解 SnapMirror 标签

每个策略类型为 `mirror-vault` 的策略都必须具有一条规则，用于指定要复制的 Snapshot 副本。例如，规则 " `daily` " 表示只应复制分配了 SnapMirror 标签 " `daily` " 的 Snapshot 副本。您可以在配置 Element Snapshot 副本时分配 SnapMirror 标签。



=== 从 Element 源集群复制到 ONTAP 目标集群

您可以使用 SnapMirror 将 Element 卷的 Snapshot 副本复制到 ONTAP 目标系统。如果 Element 站点发生灾难，您可以从 ONTAP 系统向客户端提供数据，然后在服务还原后重新激活 Element 源卷。

Element 卷大致相当于 ONTAP LUN 。初始化 Element 软件和 ONTAP 之间的数据保护关系后， SnapMirror 将使用 Element 卷的名称创建一个 LUN 。如果 LUN 满足 Element 到 ONTAP 复制的要求， SnapMirror 会将数据复制到现有 LUN 。

复制规则如下：

* ONTAP 卷只能包含一个 Element 卷中的数据。
* 您不能将数据从一个 ONTAP 卷复制到多个 Element 卷。




=== 从 ONTAP 源集群复制到 Element 目标集群

从 ONTAP 9.4 开始，您可以将在 ONTAP 系统上创建的 LUN 的 Snapshot 副本复制回 Element 卷：

* 如果 Element 源和 ONTAP 目标之间已存在 SnapMirror 关系，则在从目标提供数据时创建的 LUN 会在重新激活源后自动复制。
* 否则，您必须在 ONTAP 源集群和 Element 目标集群之间创建和初始化 SnapMirror 关系。


复制规则如下：

* 复制关系的策略类型必须为 "`async-mirror` " 。
+
不支持类型为 `mirror-vault` 的策略。

* 仅支持 iSCSI LUN 。
* 不能将多个 LUN 从 ONTAP 卷复制到 Element 卷。
* 您不能将 LUN 从 ONTAP 卷复制到多个 Element 卷。




=== 前提条件

在 Element 和 ONTAP 之间配置数据保护关系之前，您必须已完成以下任务：

* Element 集群必须运行 NetApp Element 软件 10.1 或更高版本。
* ONTAP 集群必须运行 ONTAP 9.3 或更高版本。
* SnapMirror 必须已在 ONTAP 集群上获得许可。
* 您必须已在 Element 和 ONTAP 集群上配置足够大的卷以处理预期的数据传输。
* 如果您使用的是 `mirror-vault` 策略类型，则必须已为要复制的 Element Snapshot 副本配置 SnapMirror 标签。
+
[NOTE]
====
您只能在 Element 软件 Web UI 中执行此任务。有关详细信息，请参见 link:https://docs.netapp.com/us-en/element-software/index.html["NetApp Element 软件文档"]

====
* 您必须确保端口 5010 可用。
* 如果您预计可能需要移动目标卷，则必须确保源卷和目标卷之间存在全网状连接。Element 源集群上的每个节点都必须能够与 ONTAP 目标集群上的每个节点进行通信。




=== 支持详细信息

下表显示了 Element 到 ONTAP 备份的支持详细信息。

[cols="25,75"]
|===
| 资源或功能 | 支持详细信息 


 a| 
SnapMirror
 a| 
* 不支持 SnapMirror 还原功能。
* 不支持 `MirrorAllSnapshots` 和 `XDPDefault` 策略。
* 不支持 "`vault` " 策略类型。
* 不支持系统定义的规则 "`all_source_snapshots` " 。
* 只有在从 Element 软件复制到 ONTAP 时，才支持使用 `mirror-vault` 策略类型。使用 "`async-mirror` " 从 ONTAP 复制到 Element 软件。
* 不支持 `snapmirror policy add-rule` 的 ` schedule` 和 ` 前缀` 选项。
* 不支持 ` napmirror resync` 的` -preserve ` 和` -quast-resync `s选项。
* 不会保留存储效率。
* 不支持扇出和级联数据保护部署。




 a| 
ONTAP
 a| 
* 从 ONTAP 9.4 和 Element 10.3 开始，支持 ONTAP Select 。
* 从 ONTAP 9.5 和 Element 11.0 开始，支持 Cloud Volumes ONTAP 。




 a| 
Element
 a| 
* 卷大小限制为 8 TiB 。
* 卷块大小必须为 512 字节。不支持 4 k 字节块大小。
* 卷大小必须是 1 MiB 的倍数。
* 不会保留卷属性。
* 要复制的最大 Snapshot 副本数为 30 。




 a| 
网络
 a| 
* 每次传输都允许使用一个 TCP 连接。
* 必须将 Element 节点指定为 IP 地址。不支持 DNS 主机名查找。
* 不支持 IP 空间。




 a| 
SnapLock
 a| 
不支持 SnapLock 卷。



 a| 
FlexGroup
 a| 
不支持 FlexGroup 卷。



 a| 
SVM 灾难恢复
 a| 
不支持 SVM DR 配置中的 ONTAP 卷。



 a| 
MetroCluster
 a| 
不支持 MetroCluster 配置中的 ONTAP 卷。

|===