---
permalink: tape-backup/assign-tape-aliases-concept.html 
sidebar: sidebar 
keywords: aliasing, ppn, physical, path, name, sn, serial, number, medium, changer, alias, name 
summary: 别名设置可简化设备标识过程。别名功能会将磁带或介质更换器的物理路径名称（ PPN ）或序列号（ SN ）绑定到一个可修改的持久别名。 
---
= 磁带别名概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
别名设置可简化设备标识过程。别名功能会将磁带或介质更换器的物理路径名称（ PPN ）或序列号（ SN ）绑定到一个可修改的持久别名。

下表介绍了如何通过磁带别名来确保磁带驱动器（或磁带库或介质更换器）始终与单个别名相关联：

|===
| 场景 | 重新分配别名 


 a| 
系统重新启动时
 a| 
磁带驱动器将自动重新分配其先前的别名。



 a| 
磁带设备移动到另一端口时
 a| 
可以调整别名以指向新地址。



 a| 
多个系统使用特定磁带设备时
 a| 
用户可以将所有系统的别名设置为相同。

|===
[NOTE]
====
从 Data ONTAP 8.1.x 升级到 Data ONTAP 8.2.x 时， Data ONTAP 8.2.x 的磁带别名功能会修改现有磁带别名。在这种情况下，您可能需要更新备份应用程序中的磁带别名。

====
分配磁带别名可在备份设备的逻辑名称（例如 st0 或 mc1 ）与永久分配给端口，磁带驱动器或介质更换器的名称之间建立对应关系。

[NOTE]
====
st0 和 st00 是不同的逻辑名称。

====
[NOTE]
====
逻辑名称和序列号仅用于访问设备。访问设备后，它会使用物理路径名称返回所有错误消息。

====
别名有两种类型的名称：物理路径名称和序列号。



== 了解物理路径名

物理路径名称（ PPN ）是 ONTAP 根据连接到存储系统的 SCSI-2/3 适配器或交换机（特定位置）为磁带驱动器和磁带库分配的数字地址序列。PPN 也称为电气名称。

直连设备的PPN使用以下格式： `host_adapter`。 `device_id_lun`

[NOTE]
====
只有LUN值不为零的磁带和介质更换器设备才会显示LUN值；也就是说、如果LUN值为零、则会显示 `lun` 不会显示PPN的一部分。

====
例如， PPN 8.6 表示主机适配器号为 8 ，设备 ID 为 6 ，逻辑单元号（ LUN ）为 0 。

SAS 磁带设备也是直连设备。例如， PPN 5c.4 表示在存储系统中， SAS HBA 连接在插槽 5 中， SAS 磁带连接到 SAS HBA 的端口 C ，设备 ID 为 4 。

光纤通道交换机连接设备的PPN使用以下格式： `switch:port_id`。 `device_id_lun`

例如， PPN my_switch ： 5.3L2 表示连接到名为 my_switch 的交换机端口 5 的磁带驱动器设置了设备 ID 3 ，并具有 LUN 2 。

LUN （逻辑单元号）由驱动器决定。光纤通道， SCSI 磁带驱动器和库以及磁盘都具有 PPN 。

除非交换机名称发生更改，磁带驱动器或库发生移动或磁带驱动器或库重新配置，否则磁带驱动器和库的 PPN 不会发生更改。重新启动后， PPN 保持不变。例如，如果删除了名为 my_switch ： 5.3L2 的磁带驱动器，并且将具有相同设备 ID 和 LUN 的新磁带驱动器连接到交换机 my_switch 的端口 5 ，则可以使用 my_switch ： 5.3L2 访问新的磁带驱动器。



== 了解序列号

序列号（ SN ）是磁带驱动器或介质更换器的唯一标识符。ONTAP 会根据 SN 而非 WWN 生成别名。

由于 SN 是磁带驱动器或介质更换器的唯一标识符，因此无论磁带驱动器或介质更换器的多个连接路径如何，别名都保持不变。这有助于存储系统在磁带库配置中跟踪同一个磁带驱动器或介质更换器。

即使重命名了磁带驱动器或介质更换器所连接的光纤通道交换机，磁带驱动器或介质更换器的 SN 也不会更改。但是，在磁带库中，如果将现有磁带驱动器替换为新磁带驱动器，则 ONTAP 会生成新的别名，因为磁带驱动器的 SN 会发生更改。此外，如果将现有磁带驱动器移动到磁带库中的新插槽或重新映射磁带驱动器的 LUN ， ONTAP 将为此磁带驱动器生成一个新别名。

[NOTE]
====
您必须使用新生成的别名更新备份应用程序。

====
磁带设备的SN使用以下格式： `SN[xxxxxxxxxx]L[X]`

`x` 是字母数字字符和L``X`` 是磁带设备的LUN。如果LUN为0、则L``X`` 不会显示部分字符串。

每个 SN 最多包含 32 个字符； SN 的格式不区分大小写。
