---
permalink: tape-backup/commands-manage-drives-media-changers-reference.html 
sidebar: sidebar 
keywords: manage, tape, drive, media, changer, operation, cluster, cartridge, position, online, offline, reset, clear 
summary: 您可以使用以下命令查看集群中磁带驱动器和介质更换器的相关信息，使磁带驱动器联机并脱机，修改磁带驱动器盒的位置，设置和清除磁带驱动器别名以及重置磁带驱动器。您还可以查看和重置磁带驱动器统计信息。 
---
= 用于管理磁带驱动器，介质更换器和磁带驱动器操作的命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用以下命令查看集群中磁带驱动器和介质更换器的相关信息，使磁带驱动器联机并脱机，修改磁带驱动器盒的位置，设置和清除磁带驱动器别名以及重置磁带驱动器。您还可以查看和重置磁带驱动器统计信息。

|===
| 如果您要 ... | 使用此命令 ... 


 a| 
使磁带驱动器联机
 a| 
`s在线存储磁带`



 a| 
清除磁带驱动器或介质更换器的别名
 a| 
`s存储磁带别名 clear`



 a| 
启用或禁用磁带驱动器的磁带跟踪操作
 a| 
`s存储磁带跟踪`



 a| 
修改磁带驱动器盒的位置
 a| 
`s存储磁带位置`



 a| 
重置磁带驱动器
 a| 
`s存储磁带重置`

[NOTE]
====
此命令仅在高级权限级别可用。

====


 a| 
设置磁带驱动器或介质更换器的别名
 a| 
`s存储磁带别名集`



 a| 
使磁带驱动器脱机
 a| 
`s存储磁带脱机`



 a| 
查看有关所有磁带驱动器和介质更换器的信息
 a| 
`s存储磁带显示`



 a| 
查看有关连接到集群的磁带驱动器的信息
 a| 
* `s存储磁带 show-tape-drive`
* `s系统节点硬件磁带驱动器 show`




 a| 
查看有关连接到集群的介质更换器的信息
 a| 
`s存储磁带 show-media-changer`



 a| 
查看有关连接到集群的磁带驱动器的错误信息
 a| 
`s存储磁带显示错误`



 a| 
查看连接到集群中每个节点的所有 ONTAP 合格且受支持的磁带驱动器
 a| 
`storage tape show-supported-status`



 a| 
查看连接到集群中每个节点的所有磁带驱动器和介质更换器的别名
 a| 
`s存储磁带别名显示`



 a| 
将磁带驱动器的统计信息读数重置为零
 a| 
`storage stats tape zero` `tape_name`

您必须在 nodeshell 中使用此命令。



 a| 
查看 ONTAP 支持的磁带驱动器
 a| 
`storage show tape supported （支持的存储显示磁带） "-v"`

您必须在 nodeshell 中使用此命令。您可以使用 ` -v` 选项查看有关每个磁带驱动器的更多详细信息。



 a| 
查看磁带设备统计信息以了解磁带性能并检查使用模式
 a| 
`s存储统计数据磁带` `tape_name`

您必须在 nodeshell 中使用此命令。

|===
有关这些命令的详细信息，请参见手册页。
