---
permalink: tape-backup/commands-manage-drives-media-changers-reference.html 
sidebar: sidebar 
keywords: manage, tape, drive, media, changer, operation, cluster, cartridge, position, online, offline, reset, clear 
summary: 您可以使用以下命令查看集群中磁带驱动器和介质更换器的相关信息，使磁带驱动器联机并脱机，修改磁带驱动器盒的位置，设置和清除磁带驱动器别名以及重置磁带驱动器。您还可以查看和重置磁带驱动器统计信息。 
---
= 用于在ONTAP中管理磁带驱动器、介质更换器和磁带驱动器操作的命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用以下命令查看集群中磁带驱动器和介质更换器的相关信息，使磁带驱动器联机并脱机，修改磁带驱动器盒的位置，设置和清除磁带驱动器别名以及重置磁带驱动器。您还可以查看和重置磁带驱动器统计信息。

|===
| 如果您要 ... | 使用此命令 ... 


 a| 
使磁带驱动器联机
 a| 
`storage tape online`



 a| 
清除磁带驱动器或介质更换器的别名
 a| 
`storage tape alias clear`



 a| 
启用或禁用磁带驱动器的磁带跟踪操作
 a| 
`storage tape trace`



 a| 
修改磁带驱动器盒的位置
 a| 
`storage tape position`



 a| 
重置磁带驱动器
 a| 
`storage tape reset`

[NOTE]
====
此命令仅在高级权限级别可用。

====


 a| 
设置磁带驱动器或介质更换器的别名
 a| 
`storage tape alias set`



 a| 
使磁带驱动器脱机
 a| 
`storage tape offline`



 a| 
查看有关所有磁带驱动器和介质更换器的信息
 a| 
`storage tape show`



 a| 
查看有关连接到集群的磁带驱动器的信息
 a| 
* `storage tape show-tape-drive`
* `system node hardware tape drive show`




 a| 
查看有关连接到集群的介质更换器的信息
 a| 
`storage tape show-media-changer`



 a| 
查看有关连接到集群的磁带驱动器的错误信息
 a| 
`storage tape show-errors`



 a| 
查看连接到集群中每个节点的所有 ONTAP 合格且受支持的磁带驱动器
 a| 
`storage tape show-supported-status`



 a| 
查看连接到集群中每个节点的所有磁带驱动器和介质更换器的别名
 a| 
`storage tape alias show`



 a| 
将磁带驱动器的统计信息读数重置为零
 a| 
`storage stats tape zero` `tape_name`

您必须在 nodeshell 中使用此命令。



 a| 
查看 ONTAP 支持的磁带驱动器
 a| 
`storage show tape supported [-v]`

您必须在 nodeshell 中使用此命令。您可以使用 `-v` 选项以查看有关每个磁带驱动器的更多详细信息。



 a| 
查看磁带设备统计信息以了解磁带性能并检查使用模式
 a| 
`storage stats tape` `tape_name`

您必须在 nodeshell 中使用此命令。

|===
.相关信息
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=storage+tape["存储磁带"^]

