---
permalink: tape-backup/commands-manage-svm-scoped-ndmp-reference.html 
sidebar: sidebar 
keywords: commands, manage, svm, scoped, ndmp, mode, vserver, storage, virtual, machine 
summary: 您可以使用 vserver services ndmp 命令管理每个 Storage Virtual Machine （ SVM ，以前称为 Vserver ）上的 NDMP 。 
---
= 用于在ONTAP中管理SVM范围的NDMP模式的命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `vserver services ndmp` 用于在每个Storage Virtual Machine (SVM、以前称为Vserver)上管理NDMP的命令。

|===
| 如果您要 ... | 使用此命令 ... 


 a| 
启用 NDMP 服务
 a| 
`vserver services ndmp on`

[NOTE]
====
必须始终在集群中的所有节点上启用 NDMP 服务。您可以使用在节点上启用NDMP服务 `system services ndmp on` 命令：默认情况下，节点上始终启用 NDMP 服务。

====


 a| 
禁用 NDMP 服务
 a| 
`vserver services ndmp off`



 a| 
显示NDMP配置
 a| 
`vserver services ndmp show`



 a| 
修改NDMP配置
 a| 
`vserver services ndmp modify`



 a| 
显示默认 NDMP 版本
 a| 
`vserver services ndmp version`



 a| 
显示所有 NDMP 会话
 a| 
`vserver services ndmp status`



 a| 
显示有关所有 NDMP 会话的详细信息
 a| 
`vserver services ndmp probe`



 a| 
终止指定的 NDMP 会话
 a| 
`vserver services ndmp kill`



 a| 
终止所有 NDMP 会话
 a| 
`vserver services ndmp kill-all`



 a| 
生成 NDMP 密码
 a| 
`vserver services ndmp generate-password`



 a| 
显示 NDMP 扩展状态
 a| 
`vserver services ndmp extensions show`

此命令可在高级权限级别下使用。



 a| 
修改（启用或禁用） NDMP 扩展状态
 a| 
`vserver services ndmp extensions modify`

此命令可在高级权限级别下使用。



 a| 
启动对指定 NDMP 会话的日志记录
 a| 
`vserver services ndmp log start`

此命令可在高级权限级别下使用。



 a| 
停止对指定 NDMP 会话的日志记录
 a| 
`vserver services ndmp log stop`

此命令可在高级权限级别下使用。

|===
有关的详细信息 `vserver services ndmp`，请参见link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+services+ndmp["ONTAP 命令参考"^]。
