---
permalink: tape-backup/dump-restore-concept.html 
sidebar: sidebar 
keywords: dump, restore, file, write, system, data, disk 
summary: 转储还原会使用预定义的过程将文件系统数据从磁带写入磁盘。 
---
= 转储还原如何与ONTAP NDMP 配合使用
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
转储还原会使用预定义的过程将文件系统数据从磁带写入磁盘。

下表中的过程显示了转储还原的工作原理：

[cols="1,4"]
|===
| 阶段 | Action 


 a| 
1.
 a| 
ONTAP 对需要从磁带中提取的文件进行编目。



 a| 
2.
 a| 
ONTAP 会创建目录和空文件。



 a| 
3.
 a| 
ONTAP 从磁带读取文件，将其写入磁盘并设置其权限（包括 ACL ）。



 a| 
4.
 a| 
ONTAP 会重复第 2 和第 3 阶段，直到从磁带复制所有指定文件为止。

|===


== 转储引擎还原的数据类型

发生灾难或控制器中断时，转储引擎可通过多种方法将备份的所有数据从单个文件恢复到文件属性，再恢复到整个目录。了解转储引擎可以还原的数据类型以及何时使用哪种恢复方法有助于最大限度地减少停机时间。

您可以将数据还原到联机映射的 LUN 。但是，在还原操作完成之前，主机应用程序无法访问此 LUN 。还原操作完成后，应刷新 LUN 数据的主机缓存，以便与还原的数据保持一致。

转储引擎可以恢复以下数据：

* 文件和目录的内容
* UNIX 文件权限
* ACL
+
如果将仅具有 UNIX 文件权限的文件还原到 NTFS qtree 或卷，则该文件不具有 Windows NT ACL 。在该文件上创建 Windows NT ACL 之前，存储系统仅使用此文件的 UNIX 文件权限。

+
[NOTE]
====
如果将从运行 Data ONTAP 8.2 的存储系统备份的 ACL 还原到运行 Data ONTAP 8.1.x 及更早版本且 ACE 限制低于 1 ， 024 的存储系统，则会还原默认 ACL 。

====
* qtree 信息
+
只有当 qtree 还原到卷的根目录时，才会使用 qtree 信息。如果将qtree还原到较低的目录(例如)、则不会使用qtree信息 `/vs1/vol1/subdir/lowerdir`而不再是qtree。

* 所有其他文件和目录属性
* Windows NT 流
* LUN
+
** LUN 必须还原到卷级别或 qtree 级别，才能保持为 LUN 。
+
如果将其还原到目录，则会将其还原为文件，因为它不包含任何有效的元数据。

** 7- 模式 LUN 将还原为 ONTAP 卷上的 LUN 。


* 可以将 7- 模式卷还原到 ONTAP 卷。
* 还原到目标卷的 VM 对齐文件将继承目标卷的 VM 对齐属性。
* 还原操作的目标卷可能包含具有强制锁定或建议锁定的文件。
+
在对此类目标卷执行还原操作时，转储引擎会忽略这些锁定。


