---
permalink: tape-backup/environment-variables-supported-concept.html 
sidebar: sidebar 
keywords: environment, variables, ontap, ndmp, restore, operation, backup, default, value, dump, smtape 
summary: 环境变量用于在启用了 NDMP 的备份应用程序和存储系统之间传达有关备份或还原操作的信息。ONTAP 支持具有关联默认值的环境变量。但是，您可以手动修改这些默认值。 
---
= ONTAP 支持的环境变量
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
环境变量用于在启用了 NDMP 的备份应用程序和存储系统之间传达有关备份或还原操作的信息。ONTAP 支持具有关联默认值的环境变量。但是，您可以手动修改这些默认值。

如果手动修改备份应用程序设置的值，则该应用程序的行为可能无法预测。这是因为备份或还原操作可能无法实现备份应用程序的预期效果。但在某些情况下，明智的修改可能有助于发现或解决问题。

下表列出了转储和 SMTape 行为通用的环境变量以及仅转储和 SMTape 支持的变量。这些表还介绍了 ONTAP 支持的环境变量在使用时的工作原理：

[NOTE]
====
在大多数情况下、具有值的变量、 `Y` 另请接受 `T` 和 `N` 另请接受 `F`。

====


== 转储和 SMTape 支持的环境变量

|===
| 环境变量 | 有效值： | Default | Description 


 a| 
调试
 a| 
`Y` 或 `N`
 a| 
`N`
 a| 
指定打印调试信息。



 a| 
文件系统
 a| 
`string`
 a| 
`none`
 a| 
指定要备份的数据的根的路径名。



 a| 
NDMP_VERSION
 a| 
`return_only`
 a| 
`none`
 a| 
您不应修改 NDMP_VERSION 变量。由备份操作创建， NDMP_VERSION 变量返回 NDMP 版本。

ONTAP 会在备份期间设置 NDMP_VERSION 变量以供内部使用，并将其传递给备份应用程序以供参考。未使用此变量设置 NDMP 会话的 NDMP 版本。



 a| 
pathname_separator
 a| 
`return_value`
 a| 
`none`
 a| 
指定路径名称分隔符字符。

此字符取决于所备份的文件系统。对于 ONTAP ，将字符 "` /` " 分配给此变量。在启动磁带备份操作之前， NDMP 服务器会设置此变量。



 a| 
type
 a| 
`dump` 或 `smtape`
 a| 
`dump`
 a| 
指定支持执行磁带备份和还原操作的备份类型。



 a| 
详细
 a| 
`Y` 或 `N`
 a| 
`N`
 a| 
在执行磁带备份或还原操作时增加日志消息。

|===


== 支持转储的环境变量

|===
| 环境变量 | 有效值： | Default | Description 


 a| 
acl_start
 a| 
`return_only`
 a| 
`none`
 a| 
ACL_START 变量由备份操作创建，是直接访问还原或可重新启动的 NDMP 备份操作使用的偏移值。

偏移值是 ACL 数据（ Pass V ）开始处的转储文件中的字节偏移量，并在备份结束时返回。要使直接访问还原操作正确还原备份的数据，必须在还原操作开始时将 acl_start 值传递给还原操作。NDMP 可重新启动的备份操作使用 ACL_START 值与备份流中不可重新启动部分开始的备份应用程序进行通信。



 a| 
基准日期
 a| 
`0`， `-1`或 `DUMP_DATE` value
 a| 
`-1`
 a| 
指定增量备份的开始日期。

设置为时 `-1`，BASE_DATE_增量 说明符已禁用。设置为时 `0` 在级别0备份上、会启用增量备份。在初始备份之后，先前增量备份中的 DUMP_DATE 变量的值将分配给 BASE_DATE 变量。

这些变量可替代基于级别 / 更新的增量备份。



 a| 
直接
 a| 
`Y` 或 `N`
 a| 
`N`
 a| 
指定还原应直接快进到文件数据所在的磁带位置，而不是扫描整个磁带。

要使直接访问恢复正常工作，备份应用程序必须提供定位信息。如果此变量设置为 `Y`，备份应用程序指定文件或目录名称以及定位信息。



 a| 
dmp_name
 a| 
`string`
 a| 
`none`
 a| 
指定多个子树备份的名称。

对于多个子树备份，此变量是必需的。



 a| 
DUMP_DATE
 a| 
`return_value`
 a| 
`none`
 a| 
您不会直接更改此变量。如果BASE_DATE变量 设置为以外的值、则由备份创建 `-1`。

DUMP_DATE 变量是通过将 32 位级别值预先设置为转储软件计算的 32 位时间值来派生的。此级别从传递到 BASE_DATE 变量的最后一个级别值开始递增。生成的值用作后续增量备份的 BASE_DATE 值。



 a| 
ENHANCED_DAR_ENABLED
 a| 
`Y` 或 `N`
 a| 
`N`
 a| 
指定是否启用增强的 DAR 功能。增强的 DAR 功能支持对具有 NT 流的文件执行目录 DAR 和 DAR 。它可以提高性能。

只有满足以下条件，才能在还原期间增强 DAR ：

* ONTAP 支持增强的 DAR 。
* 备份期间会启用文件历史记录（ HIST=Y ）。
* 。 `ndmpd.offset_map.enable` 选项设置为 `on`。
* ENHANCEDAR_ENCEDABLE变量设置为 `Y` 还原期间。




 a| 
排除
 a| 
`pattern_string`
 a| 
`none`
 a| 
指定在备份数据时排除的文件或目录。

排除列表是一个以逗号分隔的文件或目录名称列表。如果文件或目录的名称与列表中的某个名称匹配，则它将从备份中排除。

在排除列表中指定名称时，应遵循以下规则：

* 必须使用文件或目录的确切名称。
* 通配符星号（ * ）必须是字符串的第一个或最后一个字符。
+
每个字符串最多可以包含两个星号。

* 文件或目录名称中的逗号必须前面带有反斜杠。
* 排除列表最多可包含 32 个名称。


[NOTE]
====
如果将NNO_配额 树设置为、则不会排除指定为排除备份的文件或目录 `Y` 同时。

====


 a| 
提取
 a| 
`Y`， `N`或 `E`
 a| 
`N`
 a| 
指定要还原备份数据集的子树。

备份应用程序指定要提取的子树的名称。如果指定的文件与备份了内容的目录匹配，则会以递归方式提取该目录。

要在还原期间不使用DAR重命名文件、目录或qtree、必须将extract环境变量设置为 `E`。



 a| 
提取 ACL
 a| 
`Y` 或 `N`
 a| 
`Y`
 a| 
指定在还原操作时还原备份文件中的 ACL 。

默认情况下，还原数据时会还原 ACL ，但 DARs 除外（ DIRECT=Y ）。



 a| 
【强制】
 a| 
`Y` 或 `N`
 a| 
`N`
 a| 
确定还原操作是否必须检查目标卷上的卷空间和索引节点可用性。

将此变量设置为 `Y` 使还原操作跳过目标路径上的卷空间和节点可用性检查。

如果目标卷上没有足够的卷空间或索引节点，则还原操作将恢复目标卷空间和索引节点可用性所允许的数据量。当卷空间或索引节点不可用时，还原操作将停止。



 a| 
历史记录
 a| 
`Y` 或 `N`
 a| 
`N`
 a| 
指定将文件历史记录信息发送到备份应用程序。

大多数商业备份应用程序都会将HIST变量设置为 `Y`。如果要提高备份操作的速度、或者要对文件历史记录收集问题进行故障排除、可以将此变量设置为 `N`。

[NOTE]
====
不应将HIST变量设置为 `Y` 备份应用程序不支持文件历史记录。

====


 a| 
ignore_CTIME
 a| 
`Y` 或 `N`
 a| 
`N`
 a| 
指定仅当文件的 ctime 值自上次增量备份以来发生更改时，才会以增量方式备份文件。

某些应用程序（例如病毒扫描软件）会更改索引节点中某个文件的 ctime 值，即使该文件或其属性未更改也是如此。因此，增量备份可能会备份未更改的文件。。 `IGNORE_CTIME` 只有当增量备份由于修改了ctime值而占用的时间或空间量无法接受时、才应指定变量。

[NOTE]
====
。 `NDMP dump` 命令集 `IGNORE_CTIME` to `false` 默认情况下。将其设置为 `true` 可能导致以下数据丢失：

. 条件 `IGNORE_CTIME` 设置为true、卷级别为增量 `ndmpcopy`，则会删除文件，这些文件会在源上的qtrees之间移动。
. 条件 `IGNORE_CTIME` 在卷级别增量转储期间设置为true、会导致删除文件、这些文件会在增量还原期间在源上的qtrees之间移动。


要避免此问题、 `IGNORE_CTIME` 必须在卷级别设置为false `NDMP dumps` 或 `ndmpcopy`。

====


 a| 
ignore_qtree
 a| 
`Y` 或 `N`
 a| 
`N`
 a| 
指定还原操作不从备份的 qtree 还原 qtree 信息。



 a| 
level
 a| 
`0`-`31`
 a| 
`0`
 a| 
指定备份级别。

级别 0 复制整个数据集。如果值大于 0 ，则增量备份级别会复制自上次增量备份以来的所有文件（新文件或已修改文件）。例如，级别 1 备份自级别 0 备份以来的新文件或修改后的文件，级别 2 备份自级别 1 备份以来的新文件或修改后的文件，依此类推。



 a| 
列表
 a| 
`Y` 或 `N`
 a| 
`N`
 a| 
列出备份的文件名和索引节点编号，而不实际还原数据。



 a| 
List_qtree
 a| 
`Y` 或 `N`
 a| 
`N`
 a| 
列出已备份的 qtree ，而不实际还原数据。



 a| 
多子树名称
 a| 
`string`
 a| 
`none`
 a| 
指定备份为多子树备份。

字符串中指定了多个子树，这是一个以换行符分隔的，以空为终止的子树名称列表。子树由与其公用根目录相关的路径名称指定，而该路径名必须指定为列表的最后一个元素。

如果使用此变量，则还必须使用 dmp_name 变量。



 a| 
NDMP_UNICODE_ FH
 a| 
`Y` 或 `N`
 a| 
`N`
 a| 
指定文件历史记录信息中除了文件的 NFS 名称之外还包含 Unicode 名称。

大多数备份应用程序不使用此选项，除非备份应用程序设计为接收这些附加文件名，否则不应设置此选项。此外，还必须设置 HIST 变量。



 a| 
no_ACL
 a| 
`Y` 或 `N`
 a| 
`N`
 a| 
指定备份数据时不能复制 ACL 。



 a| 
非配额树
 a| 
`Y` 或 `N`
 a| 
`N`
 a| 
指定在备份数据时必须忽略 qtree 中的文件和目录。

设置为时 `Y`，不会备份文件系统变量指定的数据集中qtrees中的项目。只有当 filesystem 变量指定整个卷时，此变量才有效。non_quota_tree 变量仅适用于级别 0 备份，如果指定了多子树名称变量，则该变量不起作用。

[NOTE]
====
如果将NNO_配额 树设置为、则不会排除指定为排除备份的文件或目录 `Y` 同时。

====


 a| 
NOWRITE
 a| 
`Y` 或 `N`
 a| 
`N`
 a| 
指定还原操作不能向磁盘写入数据。

此变量用于调试。



 a| 
递归
 a| 
`Y` 或 `N`
 a| 
`Y`
 a| 
指定在 DAR 还原期间展开目录条目。

必须启用直接环境变量和增强型DAR_ENenabled环境变量(设置为 `Y`)。如果禁用递归变量(设置为 `N`)、则只会从磁带还原原始源路径中所有目录的权限和ACL、而不会还原目录的内容。递归变量设置为时 `N` 或recover Full_paths变量设置为 `Y`，则恢复路径必须以原始路径结尾。

[NOTE]
====
如果已禁用递归变量，并且存在多个恢复路径，则所有恢复路径都必须包含在最长的恢复路径中。否则，将显示一条错误消息。

====
例如、以下是有效的恢复路径、因为所有恢复路径都在中 `foo/dir1/deepdir/myfile`：

* `/foo`
* `/foo/dir`
* `/foo/dir1/deepdir`
* `/foo/dir1/deepdir/myfile`


以下是无效的恢复路径：

* `/foo`
* `/foo/dir`
* `/foo/dir1/myfile`
* `/foo/dir2`
* `/foo/dir2/myfile`




 a| 
recovery_full_paths
 a| 
`Y` 或 `N`
 a| 
`N`
 a| 
指定在 DAR 之后还原完整恢复路径的权限和 ACL 。

必须启用Direct和enhanced DAR_enabled (设置为) `Y`)。如果recover Full_paths设置为 `Y`，则恢复路径必须以原始路径结尾。如果目标卷上已存在目录，则不会从磁带还原其权限和 ACL 。



 a| 
更新
 a| 
`Y` 或 `N`
 a| 
`Y`
 a| 
更新元数据信息以启用基于级别的增量备份。

|===


== SMTape 支持的环境变量

|===
| 环境变量 | 有效值： | Default | Description 


 a| 
基准日期
 a| 
`DUMP_DATE`
 a| 
`-1`
 a| 
指定增量备份的开始日期。

 `BASE_DATE`是引用快照标识符的字符串表示。SMTape使用 `BASE_DATE`字符串查找参考快照。

 `BASE_DATE` 基线备份不需要。对于增量备份、是的值 `DUMP_DATE` 先前基线或增量备份中的变量将分配给 `BASE_DATE` 变量。

备份应用程序将分配 `DUMP_DATE` 来自先前SMTape基线或增量备份的值。



 a| 
DUMP_DATE
 a| 
`return_value`
 a| 
`none`
 a| 
在SMTape备份结束时、dump_date包含一个字符串标识符、用于标识用于该备份的快照。此快照可用作后续增量备份的参考快照。

生成的 DUMP_DATE 值用作后续增量备份的 BASE_DATE 值。



 a| 
SMTAPE_BACKUP_SET_ID
 a| 
`string`
 a| 
`none`
 a| 
标识与基线备份关联的增量备份顺序。

备份集 ID 是在基线备份期间生成的 128 位唯一 ID 。备份应用程序会将此ID分配为的输入 `SMTAPE_BACKUP_SET_ID` 可变。



 a| 
SMTAPE_SNAPSHOT_NAME
 a| 
卷中可用的任何有效快照
 a| 
`Invalid`
 a| 
当SMTAPE_SnapSnapSnapshot变量设置为快照时、该快照及其旧快照将备份到磁带。

对于增量备份、此变量指定增量快照。BASE_DATE变量 提供基线快照。



 a| 
SMTAPE_DELETE_SNAPSHOT
 a| 
`Y` 或 `N`
 a| 
`N`
 a| 
对于SMTape自动创建的快照，如果SMTAPE_DELETE_Snapshot变量设置为 `Y`，则备份操作完成后，SMTape将删除此快照。但是、备份应用程序创建的快照不会被删除。



 a| 
SMTAPE_Breake_mirror
 a| 
`Y` 或 `N`
 a| 
`N`
 a| 
SMTABE_BRAGE_MOR镜像 变量设置为时 `Y`，类型的卷 `DP` 更改为 `RW` 卷。

|===