---
permalink: tape-backup/ndmp-modes-concept.html 
sidebar: sidebar 
keywords: ndmp, mode, operation, backup, restore, node, level, svm 
summary: '您可以选择在节点级别或Storage Virtual Machine (SVM)级别执行磁带备份和还原操作。要在 SVM 级别成功执行这些操作，必须在 SVM 上启用 NDMP 服务。' 
---
= 了解ONTAP NDMP 操作模式
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以选择在节点级别或Storage Virtual Machine (SVM)级别执行磁带备份和还原操作。要在 SVM 级别成功执行这些操作，必须在 SVM 上启用 NDMP 服务。

如果从 Data ONTAP 8.2 升级到 Data ONTAP 8.3 ，则在从 8.2 升级到 8.3 后， 8.2 中使用的 NDMP 操作模式将继续保留。

如果使用 Data ONTAP 8.2 或更高版本安装新集群，则 NDMP 默认处于 SVM 范围的 NDMP 模式。要在节点范围的 NDMP 模式下执行磁带备份和还原操作，您必须明确启用节点范围的 NDMP 模式。



== 了解节点范围的ONTAP NDMP 模式

在节点范围的 NDMP 模式下，您可以在节点级别执行磁带备份和还原操作。从 8.2 升级到 8.3 后， Data ONTAP 8.2 中使用的 NDMP 操作模式将继续保留。

在节点范围的 NDMP 模式下，您可以在拥有卷的节点上执行磁带备份和还原操作。要执行这些操作，您必须在拥有卷或磁带设备的节点上托管的 LIF 上建立 NDMP 控制连接。

[NOTE]
====
此模式已弃用，将在未来的主要版本中删除。

====


== 了解 SVM 范围的ONTAP NDMP 模式

如果在 SVM 上启用了 NDMP 服务，则可以在 Storage Virtual Machine （ SVM ）级别成功执行磁带备份和还原操作。如果备份应用程序支持 CAB 扩展，则可以备份和还原集群 SVM 中不同节点托管的所有卷。

可以在不同的 LIF 类型上建立 NDMP 控制连接。在 SVM 范围的 NDMP 模式下，这些 LIF 属于数据 SVM 或管理 SVM 。只有在拥有此 LIF 的 SVM 上启用了 NDMP 服务时，才能在 LIF 上建立连接。

数据 LIF 属于数据 SVM ，而集群间 LIF ，节点管理 LIF 和集群管理 LIF 属于管理 SVM 。

在 SVM 范围的 NDMP 模式下，用于备份和还原操作的卷和磁带设备的可用性取决于建立 NDMP 控制连接的 LIF 类型以及 CAB 扩展的状态。如果备份应用程序支持 CAB 扩展，并且某个卷和磁带设备共享相同的相关性，则备份应用程序可以执行本地备份或还原操作，而不是三向备份或还原操作。

.相关信息
xref:commands-manage-node-scoped-ndmp-reference.adoc[用于管理节点范围的 NDMP 模式的命令]
