---
permalink: tape-backup/options-ndmpcopy-command-reference.html 
sidebar: sidebar 
keywords: ndmpcopy, command, tranfer, data, nodeshell 
summary: 您应了解 ndmpcopy 命令可用于成功传输数据的选项。 
---
= ndmpcopy 命令的选项
:icons: font
:imagesdir: ../media/


[role="lead"]
要成功传输数据，您应了解 `ndmpcopy` 命令的可用选项。

下表列出了可用选项。有关详细信息，请参见 nodeshell 提供的 `ndmpcopy` 手册页。

|===
| 选项 | Description 


 a| 
` -sa` `用户名` ：`password`
 a| 
此选项用于设置用于连接到源存储系统的源身份验证用户名和密码。这是一个必需选项。

对于没有管理员权限的用户，您必须指定用户系统生成的 NDMP 专用密码。管理员和非管理员用户都必须使用系统生成的密码。



 a| 
` -da` `用户名` ：`密码`
 a| 
此选项用于设置用于连接到目标存储系统的目标身份验证用户名和密码。这是一个必需选项。



 a| 
`` `m｛` D5`｝` 文本 ｝
 a| 
此选项用于设置在连接到源存储系统时要使用的源身份验证类型。这是一个必需选项，因此用户应提供 `text` 或 `md5` 选项。



 a| 
` dt` ｛ `md5` ｝`文本` ｝
 a| 
此选项用于设置连接到目标存储系统时要使用的目标身份验证类型。



 a| 
` -l`
 a| 
此选项会将传输所使用的转储级别设置为指定的级别值。有效值为 `0` ， `1` ， `9` ，其中 `0` 表示完全传输， `1` 到 `9` 指定增量传输。默认值为 `0` 。



 a| 
` - d`
 a| 
使用此选项可以生成 ndmpcopy 调试日志消息。ndmpcopy 调试日志文件位于 ` /mroot/etc/log` 根卷中。ndmpcopy 调试日志文件名格式为 `ndmpcopy.yyyymmdd` 。



 a| 
` f`
 a| 
此选项将启用强制模式。通过此模式，可以覆盖 7- 模式卷根目录上的 ` /etc` 目录中的系统文件。



 a| 
` h`
 a| 
此选项将打印帮助消息。



 a| 
` -p`
 a| 
此选项会提示您输入源授权和目标授权的密码。此密码将覆盖为 ` -sa` 和 ` -da` 选项指定的密码。

[NOTE]
====
只有当命令在交互式控制台中运行时，才能使用此选项。

====


 a| 
` - 排除`
 a| 
此选项会从为数据传输指定的路径中排除指定的文件或目录。该值可以是以逗号分隔的目录或文件名列表，例如 ` * 。 pst` 或 ` * 。 txt` 。

|===