---
permalink: tape-backup/snapshot-copies-during-smtape-backup-concept.html 
sidebar: sidebar 
keywords: snapshot, copy, smtape, backup, baseline, incremental, snapmirror 
summary: 您应了解在SMTape基线备份和增量备份期间如何使用快照。使用 SMTape 执行备份时，还需要注意一些事项。 
---
= 在SMTape备份期间使用快照
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您应了解在SMTape基线备份和增量备份期间如何使用快照。使用 SMTape 执行备份时，还需要注意一些事项。



== 基线备份

在执行基线备份时、您可以指定要备份到磁带的快照的名称。如果未指定快照、则根据卷的访问类型(读/写或只读)、系统会自动创建快照或使用现有快照。如果为备份指定快照、则早于指定快照的所有快照也会备份到磁带。

如果未指定备份快照、则会发生以下情况：

* 对于读/写卷、系统会自动创建快照。
+
新创建的快照和所有较早的快照都会备份到磁带。

* 对于只读卷、所有快照(包括最新快照)都会备份到磁带。
+
在备份启动后创建的任何新快照都不会进行备份。





== 增量备份

对于SMTape增量或差异备份操作、符合NDMP的备份应用程序会创建和管理快照。

在执行增量备份操作时、您必须始终指定快照。要成功执行增量备份操作、上次备份操作(基线或增量)期间备份的快照必须位于从中执行备份的卷上。要确保使用此备份快照、您必须在配置备份策略时考虑为此卷分配的快照策略。



== 有关 SnapMirror 目标上的 SMTape 备份的注意事项

* 数据保护镜像关系会在目标卷上创建临时快照以进行复制。
+
您不应使用这些快照进行SMTape备份。

* 如果在对数据保护镜像关系中的目标卷执行SMTape备份操作期间、同一卷上发生SnapMirror更新、则不能在源卷上删除由SMTape备份的快照。
+
在备份操作期间、SMTape会锁定目标卷上的快照、如果删除源卷上的相应快照、则后续SnapMirror更新操作将失败。

* 在增量备份期间、不应使用这些快照。

