---
permalink: tape-backup/types-data-dump-engine-backs-up-concept.html 
sidebar: sidebar 
keywords: types, data, dump, engine, backs, up, files, directory, qtree, volumes 
summary: 通过转储引擎，您可以将数据备份到磁带，以防止发生灾难或控制器中断。除了备份文件，目录， qtree 或整个卷等数据对象之外，转储引擎还可以备份有关每个文件的多种类型的信息。了解转储引擎可以备份的数据类型以及要考虑的限制有助于您规划灾难恢复方法。 
---
= 转储引擎备份的数据类型
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过转储引擎，您可以将数据备份到磁带，以防止发生灾难或控制器中断。除了备份文件，目录， qtree 或整个卷等数据对象之外，转储引擎还可以备份有关每个文件的多种类型的信息。了解转储引擎可以备份的数据类型以及要考虑的限制有助于您规划灾难恢复方法。

除了备份文件中的数据之外，转储引擎还可以根据需要备份有关每个文件的以下信息：

* UNIX GID ，所有者 UID 和文件权限
* UNIX 访问，创建和修改时间
* 文件类型
* 文件大小
* DOS 名称， DOS 属性和创建时间
* 包含 1 ， 024 个访问控制条目（ ACE ）的访问控制列表（ ACL ）
* qtree 信息
* 接合路径


接合路径将备份为符号链接。

* LUN 和 LUN 克隆
+
您可以备份整个 LUN 对象，但不能备份 LUN 对象中的单个文件。同样，您可以还原整个 LUN 对象，但不能还原 LUN 中的单个文件。

+
[NOTE]
====
转储引擎将 LUN 克隆备份为独立的 LUN 。

====
* VM-aligned 文件
+
Data ONTAP 8.1.2 之前的版本不支持备份与 VM 对齐的文件。



[NOTE]
====
当 Snapshot 支持的 LUN 克隆从 7- 模式 Data ONTAP 过渡到 ONTAP 时，它将成为不一致的 LUN 。转储引擎不会备份不一致的 LUN 。

====
将数据还原到卷时，将限制要还原的 LUN 上的客户端 I/O 。只有在转储还原操作完成后，才会删除 LUN 限制。同样，在 SnapMirror 单个文件或 LUN 还原操作期间，客户端 I/O 会同时受限于要还原的文件和 LUN 。只有在单个文件或 LUN 还原操作完成后，才会删除此限制。如果对正在执行转储还原或 SnapMirror 单个文件或 LUN 还原操作的卷执行转储备份，则具有客户端 I/O 限制的文件或 LUN 不会包含在备份中。如果删除了客户端 I/O 限制，这些文件或 LUN 将包含在后续备份操作中。

[NOTE]
====
在 Data ONTAP 8.3 上运行并备份到磁带的 LUN 只能还原到 8.3 及更高版本，而不能还原到早期版本。如果将 LUN 还原到早期版本，则 LUN 将还原为文件。

====
将 SnapVault 二级卷或卷 SnapMirror 目标备份到磁带时，只会备份卷上的数据。不会备份关联的元数据。因此，在尝试还原卷时，只会还原该卷上的数据。有关卷 SnapMirror 关系的信息在备份中不可用，因此不会还原。

如果转储一个仅具有 Windows NT 权限的文件并将其还原到 UNIX 模式的 qtree 或卷，则该文件将获得该 qtree 或卷的默认 UNIX 权限。

如果转储一个仅具有 UNIX 权限的文件并将其还原到 NTFS 模式的 qtree 或卷，则该文件将获得该 qtree 或卷的默认 Windows 权限。

其他转储和还原操作会保留权限。

您可以备份与VM对齐的文件和 `vm-align-sector` 选项有关 VM 对齐文件的详细信息，请参见 link:../volumes/index.html["逻辑存储管理"]。
