---
permalink: tape-backup/user-authentication-svm-scoped-ndmp-mode-concept.html 
sidebar: sidebar 
keywords: user, authentication, svm, ndmp, node, vsadmin, backup, role, storage, virutal, machine, user 
summary: '在 Storage Virtual Machine （ SVM ）范围的 NDMP 模式中， NDMP 用户身份验证与基于角色的访问控制相集成。在 SVM 环境中， NDMP 用户必须具有 "vsadmin" 或 "vsadmin-backup" 角色。在集群环境中， NDMP 用户必须具有 " 管理员 " 或 " 备份 " 角色。' 
---
= SVM 范围的 NDMP 模式下的用户身份验证
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在 Storage Virtual Machine （ SVM ）范围的 NDMP 模式中， NDMP 用户身份验证与基于角色的访问控制相集成。在 SVM 环境中， NDMP 用户必须具有 "`vsadmin` " 或 "`vsadmin-backup` " 角色。在集群环境中， NDMP 用户必须具有 "`admin` " 或 "`backup` " 角色。

除了这些预定义角色之外，如果自定义角色的命令目录中包含 "`vserver services ndmp` " 文件夹，并且此文件夹的访问级别不是 "`none` " ，则与自定义角色关联的用户帐户也可用于 NDMP 身份验证。在此模式下，您必须为给定用户帐户生成 NDMP 密码，该密码是通过基于角色的访问控制创建的。具有管理员或备份角色的集群用户可以访问节点管理 LIF ，集群管理 LIF 或集群间 LIF 。具有 vsadmin-backup 或 vsadmin 角色的用户只能访问该 SVM 的数据 LIF 。因此，根据用户的角色，用于备份和还原操作的卷和磁带设备的可用性会有所不同。

此模式还支持对 NIS 和 LDAP 用户进行用户身份验证。因此， NIS 和 LDAP 用户可以使用通用用户 ID 和密码访问多个 SVM 。但是， NDMP 身份验证不支持 Active Directory 用户。

在此模式下，用户帐户必须与 SSH 应用程序和 "`User password` " 身份验证方法关联。

.相关信息
xref:commands-manage-svm-scoped-ndmp-reference.adoc[用于管理 SVM 范围的 NDMP 模式的命令]

link:../system-admin/index.html["系统管理"]
