---
permalink: tape-backup/workflow-task.html 
sidebar: sidebar 
keywords: perform, tape, backup, restore, flexvol, volume, ndmp, backup, application 
summary: 您可以使用启用了 NDMP 的备份应用程序执行磁带备份和还原操作。 
---
= ONTAP中的磁带备份和还原工作流
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用启用了 NDMP 的备份应用程序执行磁带备份和还原操作。

.关于此任务
磁带备份和还原工作流概述了执行磁带备份和还原操作所涉及的任务。有关执行备份和还原操作的详细信息，请参见备份应用程序文档。

.步骤
. 通过选择支持 NDMP 的磁带拓扑来设置磁带库配置。
. 在存储系统上启用 NDMP 服务。
+
您可以在节点级别或 Storage Virtual Machine （ SVM ）级别启用 NDMP 服务。这取决于您选择执行磁带备份和还原操作的 NDMP 模式。

. 使用 NDMP 选项管理存储系统上的 NDMP 。
+
您可以在节点级别或 SVM 级别使用 NDMP 选项。这取决于您选择执行磁带备份和还原操作的 NDMP 模式。

+
您可以在节点级别使用命令修改NDMP选项、在SVM级别使用 `vserver services ndmp modify`命令修改NDMP选项 `system services ndmp modify`。有关的详细信息 `system services ndmp modify`and `vserver services ndmp modify`，请参见link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=services+ndmp+modify["ONTAP 命令参考"^]。

. 使用启用了 NDMP 的备份应用程序执行磁带备份或还原操作。
+
ONTAP 支持转储和 SMTape 引擎进行磁带备份和还原。

+
有关使用备份应用程序（也称为 _Data Management Applications_ 或 _DMA_ ）执行备份或还原操作的详细信息，请参见备份应用程序文档。



.相关信息
xref:common-ndmp-topologies-reference.adoc[常见 NDMP 磁带备份拓扑]

xref:data-backup-dump-concept.adoc[了解 FlexVol 卷的转储引擎]
