---
permalink: asa/support-limitations.html 
sidebar: sidebar 
keywords: all flash san array, asa, san, array, software, configuration, configure, configuring, setup, set up, limitations, restrictions, nvme, mcc ip, persistent ports, host, settings, utilities, ways to identify 
summary: '纯闪存SAN阵列(ASA)配置限制和支持因ONTAP版本而异。' 
---
= 纯闪存SAN阵列配置限制和支持
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
纯闪存SAN阵列(ASA)配置限制和支持因ONTAP版本而异。

有关支持的配置限制的最新详细信息、请参见 link:https://hwu.netapp.com/["NetApp Hardware Universe"^]。



== 每个集群的SAN协议和节点数

每个集群对SAN协议和节点的ASA支持如下：

[cols="3*"]
|===


| 从ONTAP 开始... | 协议支持 | 每个集群的最大节点数 


| 9.12.1.  a| 
* NVMe (在四节点MetroCluster IP配置和非MetroCluster IP配置上受支持)
* FC
* iSCSI

| 12. 


| 9.9.1.  a| 
* NVMe (在非MetroCluster IP配置上受支持)
* FC
* iSCSI

 a| 
* 12个节点(适用于非MetroCluser IP配置)
* 8个节点(适用于MetroCluster IP配置)




| 9.7.  a| 
* FC
* iSCSI

| 4. 
|===


== 支持永久性端口

从ONTAP 9.8开始、默认情况下、配置为使用FC协议的纯闪存SAN阵列(ASAS)上会启用永久性端口。永久性端口仅适用于 FC ，并且需要使用全球通用端口名称（ WWPN ）标识的区域成员资格。

永久性端口可通过在 HA 配对节点的相应物理端口上创建影子 LIF 来减少接管的影响。接管节点后，配对节点上的影子 LIF 将采用原始 LIF 的标识，包括 WWPN 。在被接管节点的路径状态更改为故障之前，影子 LIF 将显示为主机 MPIO 堆栈的主动 / 优化路径，并且 I/O 将发生移动。这样可以减少 I/O 中断，因为即使在存储故障转移操作期间，主机也始终可以看到相同数量的目标路径。

对于永久性端口，以下 FCP 端口特征在 HA 对中应相同：

* FCP 端口计数
* FCP 端口名称
* FCP 端口速度
* FCP LIF 基于 WWPN 的分区


如果 HA 对中的上述任一特征不相同，则会生成以下 EMS 消息：

`EMS : scsiblade.lif.persistent.ports.fcp.init.error`

有关永久性端口的详细信息，请参见 link:http://www.netapp.com/us/media/tr-4080.pdf["NetApp 技术报告 4080 ：《可扩展 SAN ONTAP 9 最佳实践》"^]。
