---
permalink: asa/support-limitations.html 
sidebar: sidebar 
keywords: all san array, asa, san, array, software, configuration, configure, configuring, setup, set up, limitations, restrictions, nvme, mcc ip, persistent ports, host, settings, utilities, ways to identify 
summary: 使用 System Manager 按照以下过程配置全 SAN 阵列。 
---
= 所有SAN阵列配置限制和支持
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
您应使用为AFF 全SAN阵列(ASA)控制器建立的经过测试且受支持的最大配置限制。

为了确保操作可靠，您不应超过中列出的当前已测试和支持的限制 link:https://hwu.netapp.com/["NetApp Hardware Universe"^]。



== ASA 配置限制

从ONTAP 9.9.1开始、对于非MetroCluster IP配置、AFF ASA 控制器最多可支持12个节点、对于MetroCluster IP配置、最多可支持8个节点。

从ONTAP 9.1.1开始、除为MetroCluster 配置的控制器外、所有AFF ASA 控制器均支持NVMe-oF协议。MetroCluster 配置不支持NVMe-oF。



== 支持永久性端口

从 ONTAP 9.8 开始，默认情况下，配置为使用 FC 协议的所有 SAN 阵列（ ASA ）都会启用永久性端口。永久性端口仅适用于 FC ，并且需要使用全球通用端口名称（ WWPN ）标识的区域成员资格。

永久性端口可通过在 HA 配对节点的相应物理端口上创建影子 LIF 来减少接管的影响。接管节点后，配对节点上的影子 LIF 将采用原始 LIF 的标识，包括 WWPN 。在被接管节点的路径状态更改为故障之前，影子 LIF 将显示为主机 MPIO 堆栈的主动 / 优化路径，并且 I/O 将发生移动。这样可以减少 I/O 中断，因为即使在存储故障转移操作期间，主机也始终可以看到相同数量的目标路径。

对于永久性端口，以下 FCP 端口特征在 HA 对中应相同：

* FCP 端口计数
* FCP 端口名称
* FCP 端口速度
* FCP LIF 基于 WWPN 的分区


如果 HA 对中的上述任一特征不相同，则会生成以下 EMS 消息：

`EMS ： scsiblade.lif.persistent.ports.fcp.init.error`

有关永久性端口的详细信息，请参见 link:http://www.netapp.com/us/media/tr-4080.pdf["NetApp 技术报告 4080 ：《可扩展 SAN ONTAP 9 最佳实践》"^]。



== 支持NVMe-oF协议

从ONTAP 9.1.1开始、所有SAN阵列均支持NVMe-oF协议。

从ONTAP 9.12.1开始、4节点MetroCluster IP配置支持NVMe/FC。9.12.1之前的NVMe不支持MetroCluster 配置。
