---
sidebar: sidebar 
permalink: high-availability/ha_automatic_giveback_commands.html 
keywords: ontap, high, availability, ha, pair, automatic, giveback, commands 
summary: 自动交还命令 
---
= 自动交还命令
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
默认情况下、在脱机节点恢复联机后、接管配对节点会自动交还存储、从而恢复高可用性对关系。在大多数情况下、这是所需的行为。如果需要禁用自动交还、例如、如果要在交还之前调查接管的发生原因 、则需要了解非默认设置的交互情况。

|===


| 如果您要 ... | 使用此命令 ... 


 a| 
启用自动交还，以便在被接管节点启动，达到 Waiting for Giveback 状态以及自动交还前的延迟已过期后立即进行交还。

默认设置为 true 。
 a| 
`storage failover modify ‑node _nodename_ ‑auto‑giveback true`



 a| 
禁用自动交还。默认设置为 true 。

*注意：*将此参数设置为false不会禁用崩溃时接管后自动交还；必须通过设置来禁用崩溃时接管后自动交还 `‑auto‑giveback‑after‑panic` 参数设置为false。
 a| 
`storage failover modify ‑node _nodename_ ‑auto‑giveback false`



 a| 
在发生崩溃时禁用接管后自动交还（默认情况下，此设置处于启用状态）。
 a| 
`storage failover modify ‑node _nodename_ ‑auto‑giveback‑after‑panic false`



 a| 
将自动交还延迟指定的秒数（默认值为 600 ）。此选项用于确定在执行自动交还之前节点仍处于接管状态的最短时间。
 a| 
`storage failover modify ‑node _nodename_ ‑delay‑seconds _seconds_`

|===


== storage failover modify 命令的变体如何影响自动交还

自动交还的操作取决于您如何配置 storage failover modify 命令的参数。

下表列出了的默认设置 `storage failover modify` 适用于非崩溃引起的接管事件的命令参数。

|===


| 参数 | 默认设置 


 a| 
`-auto-giveback _true_ | _false_`
 a| 
`_true_`



 a| 
`-delay-seconds _integer_ (seconds)`
 a| 
600



 a| 
`-onreboot _true_ | _false_`
 a| 
`_true_`

|===
下表介绍了的组合方式 `-onreboot` 和 `-auto-giveback` 参数会影响非崩溃引起的接管事件的自动交还。

|===


| `storage failover modify` 使用的参数 | 接管的发生原因 | 是否发生自动交还？ 


 a| 
`-onreboot _true_`

`-auto-giveback _true_`
| reboot 命令 | 是的。 


| halt 命令，或者从服务处理器发出的重新启动操作 | 是的。 


 a| 
`-onreboot _true_`

`-auto-giveback _false_`
| reboot 命令 | 是的。 


| halt 命令，或者从服务处理器发出的重新启动操作 | 否 


 a| 
`-onreboot _false_`

`-auto-giveback _true_`
| reboot 命令 | 不适用
在这种情况下、不会发生接管 


| halt 命令，或者从服务处理器发出的重新启动操作 | 是的。 


 a| 
`-onreboot _false_`

`-auto-giveback _false_`
| reboot 命令 | 否 


| halt 命令，或者从服务处理器发出的重新启动操作 | 否 
|===
。 `-auto-giveback` 参数用于控制崩溃后的交还以及所有其他自动接管。如果 `-onreboot` 参数设置为 `true` 而接管是由于重新启动而发生的、则无论是否、都会始终执行自动交还 `-auto-giveback` 参数设置为 `true`。

。 `-onreboot` 参数适用场景重新启动并暂停ONTAP发出的命令。当 `-onreboot` 参数设置为false、则在节点重新启动时不会发生接管。因此、无论是否存在、都无法进行自动交还 `-auto-giveback` 参数设置为true。发生客户端中断。



== 适用于崩溃情况的自动交还参数组合的影响。

下表列出了 `storage failover modify` 适用于崩溃情况的命令参数：

|===


| 参数 | 默认设置 


 a| 
`-onpanic _true | false_`
 a| 
`_true_`



 a| 
`-auto-giveback-after-panic _true | false_`

（权限：高级）
 a| 
`_true_`



 a| 
`-auto-giveback _true | false_`
 a| 
`_true_`

|===
下表介绍了的参数组合方式 `storage failover modify` 命令会影响崩溃情况下的自动交还。

[cols="60,40"]
|===


| `storage failover` 使用的参数 | 崩溃后是否发生自动交还？ 


| `-onpanic true`
`-auto-giveback true`
`-auto-giveback-after-panic true` | 是的。 


| `-onpanic true`
`-auto-giveback true`
`-auto-giveback-after-panic false` | 是的。 


| `-onpanic true`
`-auto-giveback false`
`-auto-giveback-after-panic true` | 是的。 


| `-onpanic true`
`-auto-giveback false`
`-auto-giveback-after-panic false` | 否 


| `-onpanic false`
条件 `-onpanic` 设置为 `false`、则无论为设置的值如何、都不会发生接管/返回 `-auto-giveback` 或 `-auto-giveback-after-panic` | 否 
|===

NOTE: 接管可能是由与崩溃无关的故障引起的。  如果节点与其配对节点之间的通信丢失、则会出现_failure_、也称为_Heartbeat los_。如果因故障而发生接管、交还将由控制 `-onfailure` 参数、而不是 `-auto-giveback-after-panic parameter`。


NOTE: 当节点崩溃时、它会向其配对节点发送崩溃数据包。  如果配对节点由于任何原因未收到崩溃数据包、则此崩溃可能会被误解为故障。  如果未收到崩溃数据包、配对节点只知道通信已丢失、并且不知道发生崩溃。  在这种情况下、配对节点会将通信丢失视为故障而不是崩溃、交还由控制 `-onfailure` 参数(而不是 `-auto-giveback-after-panic parameter`）。

有关所有的详细信息、请参见 `storage failover modify` 参数、请参见 link:https://docs.netapp.com/us-en/ontap-cli-9131/storage-failover-modify.html["ONTAP 手册页"]。
