---
sidebar: sidebar 
permalink: high-availability/ha_automatic_giveback_commands.html 
keywords: ontap, high, availability, ha, pair, automatic, giveback, commands 
summary: 自动交还命令 
---
= 自动交还命令
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在某些情况下，您可能需要使用 ONTAP 命令管理自动交还设置。

|===


| 如果您要 ... | 使用此命令 ... 


 a| 
启用自动交还，以便在被接管节点启动，达到 Waiting for Giveback 状态以及自动交还前的延迟已过期后立即进行交还。

默认设置为 true 。
 a| 
`s存储故障转移修改 ‑node _nodename_ ‑auto‑giveback true`



 a| 
禁用自动交还。默认设置为 true 。

* 注意： * 将此参数设置为 false 不会禁用在发生崩溃时接管后自动交还；必须通过将 `‑auto‑giveback‑after‑panic` 参数设置为 false 来禁用在发生崩溃时接管后自动交还。
 a| 
`s存储故障转移修改 ‑node _nodename_ ‑auto‑giveback false`



 a| 
在发生崩溃时禁用接管后自动交还（默认情况下，此设置处于启用状态）。
 a| 
`storage failover modify ‑node _nodename_ ‑auto‑giveback‑after‑panic false`



 a| 
将自动交还延迟指定的秒数（默认值为 600 ）。此选项用于确定在执行自动交还之前节点仍处于接管状态的最短时间。
 a| 
`s存储故障转移修改 ‑node _nodename_ ‑delay‑seconds _seconds_`

|===


== storage failover modify 命令的变体如何影响自动交还

自动交还的操作取决于您如何配置 storage failover modify 命令的参数。

下表列出了适用于非崩溃引起的接管事件的 storage failover modify 命令参数：

|===


| 参数 | 默认设置 


 a| 
` 自动交还 _true_ _ _ _ _ false_`
 a| 
` _ true _`



 a| 
` - 延迟 - 秒 _intege_ （秒）`
 a| 
600



 a| 
` -onreboot _tru_ _ _ _ _ _false_`
 a| 
` _ true _`

|===
下表介绍了 ` -onreboot` 和 ` -auto-giveback` 参数的组合如何影响非崩溃引起的接管事件的自动交还。

|===


| `s存储故障转移修改` 使用的参数 | 接管的发生原因 | 是否发生自动交还？ 


 a| 
` -onreboot _tru_`

` 自动交还 _tru_`
| reboot 命令 | 是的。 


| halt 命令，或者从服务处理器发出的重新启动操作 | 是的。 


 a| 
` -onreboot _tru_`

` 自动交还 _false_`
| reboot 命令 | 否 


| halt 命令，或者从服务处理器发出的重新启动操作 | 否 


 a| 
` -onreboot _false_`

` 自动交还 _tru_`
| reboot 命令 | 不适用在这种情况下，不会发生接管 


| halt 命令，或者从服务处理器发出的重新启动操作 | 是的。 


 a| 
` -onreboot _false_`

` 自动交还 _false_`
| reboot 命令 | 否 


| halt 命令，或者从服务处理器发出的重新启动操作 | 否 
|===

NOTE: ` -auto-giveback` 参数用于控制崩溃后的交还以及所有其他自动接管。如果将 ` -onreboot` 参数设置为 `true` 而由于重新启动而发生接管，则无论 ` -auto-giveback` 参数是否设置为 `true` ，系统始终会执行自动交还。

` -onreboot` 参数适用场景将重新启动并暂停从 ONTAP 发出的命令。如果将 ` -onreboot` 参数设置为 false ，则在节点重新启动时不会发生接管。因此，无论 ` -auto-giveback` 参数是否设置为 true ，都不会发生自动交还。发生客户端中断。



== 适用于崩溃情况的自动交还参数组合的影响。

下表列出了适用于崩溃情况的 `storage failover modify` 命令参数：

|===


| 参数 | 默认设置 


 a| 
` -onpanic _true _ false_`
 a| 
` _ true _`



 a| 
` -auto-giveback-after-panic _true _ false_`

（权限：高级）
 a| 
` _ true _`



 a| 
` 自动交还 _true _ false _`
 a| 
` _ true _`

|===
下表介绍了 `storage failover modify` 命令的参数组合如何影响崩溃情况下的自动交还。


NOTE: 请注意，发生节点崩溃时，可能会出于其他原因发生接管。例如，如果节点崩溃，但其配对节点未收到崩溃数据包，则配对节点可能会执行检测信号丢失接管。在这种情况下，交还不会由 ` -auto-giveback-after-panic` 参数控制，而是由 ` -onfailure` 参数控制。

[cols="60,40"]
|===


| `s存储故障转移` 使用的参数 | 崩溃后是否发生自动交还？ 


| ` -onpanic true` ` auto-giveback true` ` -auto-giveback-after-panic true` | 是的。 


| ` -onpanic true` ` auto-giveback true` ` -auto-giveback-after-panic false` | 否 


| ` -onpanic true` ` auto-giveback false` ` -auto-giveback-after-panic true` | 是的。 


| ` -onpanic true` ` auto-giveback false` ` -auto-giveback-after-panic false` | 否 


| ` -onpanic false` 如果 ` -onpanic` 设置为 `false` ，则不会发生接管 / 交还，无论为 ` -auto-giveback` 或 ` -auto-giveback-after-panic` 设置的值如何 | 否 
|===
[NOTE]
====
如果您修改默认设置， ` -onpanic` 参数可以覆盖自动交还，如上表所示。

* 如果将 ` -onpanic` 参数设置为 `true` ，则在发生崩溃时始终会执行自动交还，除非您更改了 ` -auto-giveback` 和 ` -auto-giveback-after-panic` 参数的默认设置。如果这两个参数都从其默认值（`true` ）更改为 `false` ，则在发生崩溃后不会发生自动交还，即使 ` -onpanic` 参数设置为 `true` 也是如此。
* 如果将 ` -onpanic` 参数设置为 `false` ，则不会发生接管，并且客户端会遇到 ONTAP 数据服务中断。因此，即使将 ` -auto-giveback-after-panic` 参数设置为 `true` ，也不会发生自动交还。


====
[NOTE]
====
* 在节点崩溃期间，接管可能出于其他原因发生。在这种情况下，交还不受 `auto-giveback-after-panic` 设置的控制。
* 如果将 ` -onpanic` 参数设置为 `true` ，则在发生崩溃时始终会执行自动交还，除非您更改了 ` -auto-giveback` 和 ` -auto-giveback-after-panic` 参数的默认设置。如果这两个参数都从其默认值（`true` ）更改为 `false` ，则在发生崩溃后不会发生自动交还，即使 ` -onpanic` 参数设置为 `true` 也是如此。
* 如果将 ` -onpanic` 参数设置为 `false` ，则不会发生接管。因此，即使将 ` -auto-giveback-after-panic` 参数设置为 `true` ，也不会发生自动交还。发生客户端中断。


====