---
sidebar: sidebar 
permalink: high-availability/ha_manual_giveback.html 
keywords: ontap, high, availability, ha, pair, manual, giveback, interrupted, vetoed, veto, commands, performing, perform 
summary: 您可以执行正常交还，终止配对节点上的进程的交还或强制交还。 
---
= 手动交还命令
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以执行正常交还，终止配对节点上的进程的交还或强制交还。


NOTE: 在执行交还之前，您必须按照中所述删除接管系统中的故障驱动器 link:../disks-aggregates/index.html["磁盘和聚合管理"]。



== 交还中断时

如果接管节点在交还过程中遇到故障或断电，则该过程将停止，接管节点将返回接管模式，直到故障修复或电源恢复为止。

但是，这取决于发生故障的交还阶段。如果节点在部分交还状态（交还根聚合之后）遇到故障或断电，则它不会返回到接管模式。而是返回到部分交还模式。  如果发生这种情况，请重复交还操作以完成此过程。



== 如果交还被否决

如果交还被否决，则必须检查 EMS 消息以确定发生原因。根据原因，您可以决定是否可以安全地覆盖此否决。

。 `storage failover show-giveback` 命令可显示返回进度、并显示否决了此返回的子系统(如果有)。软否决可以被覆盖，而硬否决则不能被覆盖，即使强制执行也是如此。下表汇总了不应覆盖的软否决以及建议的解决方法。

您可以使用以下命令查看任何交还否决的 EMS 详细信息：

`event log show -node * -event gb*`

有关的详细信息 `event log show`，请参见link:https://docs.netapp.com/us-en/ontap-cli/event-log-show.html["ONTAP 命令参考"^]。



== 根聚合的交还

这些否决不适用于聚合重新定位操作：

[cols="35,65"]
|===


| 否决子系统模块 | 临时解决策 


 a| 
vfiler_low_level
 a| 
终止导致否决的SMB会话、或关闭建立已打开会话的SMB应用程序。

覆盖此否决可能发生原因会使使用 SMB 的应用程序突然断开连接并丢失数据。



 a| 
磁盘检查
 a| 
在尝试交还之前，应删除所有故障或绕过的磁盘。如果磁盘正在清理，则应等待操作完成。

覆盖此否决可能发生原因会导致因预留冲突或磁盘不可访问而导致聚合或卷脱机而导致中断。

|===


== SFO 聚合的交还

这些否决不适用于聚合重新定位操作：

[cols="35,65"]
|===


| 否决子系统模块 | 临时解决策 


 a| 
锁定管理器
 a| 
正常关闭具有打开文件的SMB应用程序、或者将这些卷移动到其他聚合。

覆盖此否决会导致SMB锁定状态丢失、从而导致中断和数据丢失。



 a| 
锁定管理器 ndo
 a| 
等待锁定镜像完成。

覆盖此否决会导致 Microsoft Hyper-V 虚拟机中断。



| RAID  a| 
检查 EMS 消息以确定否决的发生原因：

如果否决是由于 nvfile 导致的，请使脱机卷和聚合联机。

如果正在执行磁盘添加或磁盘所有权重新分配操作，请等待操作完成。

如果否决是由于聚合名称或 UUID 冲突而导致的，请对问题描述进行故障排除并解决问题。

如果否决是由于镜像重新同步，镜像验证或脱机磁盘导致的，则可以覆盖此否决，并且此操作会在交还后重新启动。



| 磁盘清单  a| 
进行故障排除以确定并解决问题的发生原因。

目标节点可能无法查看属于要迁移的聚合的磁盘。

磁盘不可访问可能导致聚合或卷不可访问。



| 卷移动操作  a| 
进行故障排除以确定并解决问题的发生原因。

此否决可防止卷移动操作在重要转换阶段中止。如果在转换期间中止了作业，则卷可能无法访问。

|===


=== 用于执行手动交还的命令

完成维护或解决后、您可以在HA对中的节点上手动启动交还、以便将存储归还给原始所有者
导致接管的任何问题。

|===


| 如果您要 ... | 使用此命令 ... 


 a| 
将存储交还给配对节点
| `storage failover giveback ‑ofnode _nodename_` 


 a| 
即使配对节点未处于等待交还模式，也交还存储
 a| 
`storage failover giveback ‑ofnode _nodename_`
`‑require‑partner‑waiting false`

除非可以接受更长时间的客户端中断，否则请勿使用此选项。



| 即使进程否决交还操作，也交还存储（强制交还）  a| 
`storage failover giveback ‑ofnode _nodename_`
`‑override‑vetoes true`

使用此选项可能会导致客户端中断时间延长，或者聚合和卷在交还后不联机。



| 仅交还 CFO 聚合（根聚合）  a| 
`storage failover giveback ‑ofnode _nodename_`

`‑only‑cfo‑aggregates true`



| 在问题描述 giveback 命令后监控交还进度 | `storage failover show‑giveback` 
|===