---
sidebar: sidebar 
permalink: high-availability/halt-reboot-node-wo-takeover-task.html 
keywords: high availability pair, hair, inhibit-takeover, reboot, epsilon, HA 
summary: 在对节点或磁盘架执行某些硬件维护时、如果要通过保持配对节点正常运行来限制停机时间、则无需启动接管即可暂停或重新启动双节点集群中的节点、 或者当出现问题而无法手动接管时、如果您希望使配对节点的聚合保持正常运行并提供数据、则也可以执行此操作。此外、如果技术支持正在协助您解决问题、他们可能会要求您在这些工作中执行此操作步骤。 
---
= 在双节点集群中，无需启动接管即可暂停或重新启动 ONTAP 节点
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在对节点或磁盘架执行某些硬件维护时、如果要通过保持配对节点正常运行来限制停机时间、则无需启动接管即可暂停或重新启动双节点集群中的节点、 或者当出现问题而无法手动接管时、如果您希望使配对节点的聚合保持正常运行并提供数据、则也可以执行此操作。此外、如果技术支持正在协助您解决问题、他们可能会要求您在这些工作中执行此操作步骤。

.关于此任务
* 在禁止接管之前(使用 `-inhibit-takeover true` 参数)、则禁用集群HA。


[CAUTION]
====
* 在双节点集群中、集群HA可确保一个节点发生故障时不会禁用集群。但是、如果在使用之前未禁用集群HA、则可以使用  `-inhibit-takeover true` 参数、则两个节点都会停止提供数据。
* 如果在禁用集群HA之前尝试暂停或重新启动节点、则ONTAP 会发出警告并指示您禁用集群HA。


====
* 将LIF (逻辑接口)迁移到要保持联机的配对节点。
* 如果要暂停或重新启动的节点上存在要保留的聚合、则将其移动到要保持联机的节点。


.步骤
. 验证两个节点是否正常：
+
[source, cli]
----
cluster show
----
+
对于这两个节点、 `true` 显示在中 `Health` 列。

+
[listing]
----
cluster::> cluster show
Node         Health  Eligibility
------------ ------- ------------
node1        true     true
node2        true     true
----
+
有关的详细信息 `cluster show`，请参见link:https://docs.netapp.com/us-en/ontap-cli/cluster-show.html["ONTAP 命令参考"^]。

. 将要停止或重新启动的节点上的所有 LIF 迁移到配对节点：
+
[source, cli]
----
network interface migrate-all -node <node_name>
----
+
有关的详细信息 `network interface migrate-all`，请参见link:https://docs.netapp.com/us-en/ontap-cli/network-interface-migrate-all.html["ONTAP 命令参考"^]。

. 如果要停止或重新启动的节点上存在您希望在节点关闭时保持在线的聚合，请将其重新定位到伙伴节点。
+
.. 显示将要停止或重新启动的节点上的聚合：
+
[source, cli]
----
storage aggregates show -node <node_name>
----
+
例如、node1是要暂停或重新启动的节点：

+
[listing]
----
cluster::> storage aggregates show -node node1
Aggregate  Size  Available  Used%  State  #Vols   Nodes   RAID  Status
---------  ----  ---------  -----  -----  -----   -----   ----  ------
aggr0_node_1_0
           744.9GB   32.68GB   96% online       2 node1    raid_dp,
                                                                normal
aggr1       2.91TB    2.62TB   10% online       8 node1    raid_dp,
                                                                normal
aggr2
            4.36TB    3.74TB   14% online      12 node1    raid_dp,
                                                                normal
test2_aggr  2.18TB    2.18TB    0% online       7 node1    raid_dp,
                                                                normal
4 entries were displayed.
----
.. 将聚合移动到合作伙伴节点：
+
[source, cli]
----
storage aggregate relocation start -node <node_name> -destination <node_name> -aggregate-list <aggregate_name>
----
+
例如、聚合aggr1、aggr2和test2_aggr将从node1移动到node2：

+
`storage aggregate relocation start -node _node1_ -destination _node2_ -aggregate-list _aggr1_,_aggr2_,_test2_aggr_`



. 禁用集群 HA：
+
[source, cli]
----
cluster ha modify -configured false
----
+
禁用集群 HA 时，epsilon 将自动移动到节点 1。返回输出确认已禁用 HA： `Notice: HA is disabled`

+

NOTE: 此操作不会禁用存储故障转移。

. 如果要停止或重新启动的节点是节点 1，则将 epsilon 移动到节点 2：
+
.. 将权限级别设置为高级：
+
[source, cli]
----
set -privilege advanced
----
.. 验证节点 2 是否健康且有资格使用 epsilon：
+
[source, cli]
----
cluster show
----
.. 从节点 1 移除 epsilon：
+
[source, cli]
----
cluster modify -node <node1_name> -epsilon false
----
.. 将 epsilon 分配给节点 2：
+
[source, cli]
----
cluster modify -node <node2_name> -epsilon true
----
.. 确认 epsilon 在节点 2 上：
+
[source, cli]
----
cluster show
----


. 停止或重新启动并禁止接管目标节点：
+
[cols="1h,1h"]
|===


 a| 
暂停节点而不启动接管：
 a| 
[source, cli]
----
system node halt -node _node_name_ -inhibit-takeover true
----


 a| 
重新启动节点而不启动接管：
 a| 
[source, cli]
----
system node reboot -node _node_name_ -inhibit-takeover true
----
|===
+

NOTE: 在命令输出中、您将看到一条警告、询问您是否要继续、请输入 `y`。

. 验证仍处于在线状态的节点是否处于正常状态（在合作伙伴处于关闭状态时）：
+
[source, cli]
----
cluster show
----
+
对于联机节点、 `true` 显示在中 `Health` 列。

+

NOTE: 在命令输出中，您将看到未配置集群 HA 的警告。您可以忽略该警告。

. 执行暂停或重新启动节点所需的操作。
. 从 LOADER 提示符处启动离线节点：
+
[source, cli]
----
boot_ontap
----
. 验证两个节点是否正常：
+
[source, cli]
----
cluster show
----
+
对于这两个节点、 `true` 显示在中 `Health` 列。

+

NOTE: 在命令输出中、您将看到一条警告、指出未配置集群HA。此时可以忽略此警告。

. 重新启用集群 HA：
+
[source, cli]
----
cluster ha modify -configured true
----
. 如果在此过程的早期将聚合重新定位到伙伴节点，请将它们移回其主节点。
+
[source, cli]
----
storage aggregate relocation start -node <node_name> -destination <node_name> -aggregate-list <aggregate_name>
----
+
例如、正在将聚合aggr1、aggr2和test2_aggR从节点node2移至节点node1：
`storage aggregate relocation start -node _node2_ -destination _node1_ -aggregate-list _aggr1_,_aggr2_,_test2_aggr_`

. 将LIF还原到其主端口：
+
.. 查看不在主位置的 LIF：
+
[source, cli]
----
network interface show -is-home false
----
+
有关的详细信息 `network interface show`，请参见link:https://docs.netapp.com/us-en/ontap-cli/network-interface-show.html["ONTAP 命令参考"^]。

.. 如果存在未从已关闭节点迁移的非主LIF、请在还原之前验证是否可以安全地移动这些LIF。
.. 如果执行此操作是安全的，请将所有 LIF 还原为主页。
+
[source, cli]
----
 network interface revert *
----
+
有关的详细信息 `network interface revert`，请参见link:https://docs.netapp.com/us-en/ontap-cli/network-interface-revert.html["ONTAP 命令参考"^]。





.相关信息
* link:https://docs.netapp.com/us-en/ontap-cli/cluster-ha-modify.html["cluster ha modify"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-relocation-start.html["存储聚合迁移开始"^]

