---
sidebar: sidebar 
permalink: high-availability/index.html 
keywords: high availability, ha, overview 
summary: 接管是指节点接管其配对节点存储的过程。交还是指将存储交还给配对节点的过程。 
---
= 高可用性管理概述
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
集群节点以高可用性（ HA ）对的形式进行配置，以实现容错和无中断运行。如果某个节点发生故障，或者您需要关闭某个节点进行日常维护，则其配对节点可以接管其存储并继续从该节点提供数据。当节点恢复联机时，配对节点会交还存储。

HA 对控制器配置由一对匹配的 FAS/AFF 存储控制器（本地节点和配对节点）组成。其中每个节点都会连接到另一个节点的磁盘架。当 HA 对中的一个节点遇到错误并停止处理数据时，其配对节点将检测到配对节点的故障状态，并从该控制器接管所有数据处理。

_Takeover_ 是节点接管其配对节点存储的过程。

_Giveback_ 是将存储返回给配对节点的过程。

默认情况下，在以下任何情况下都会自动发生接管：

* 导致崩溃的节点上发生软件或系统故障。HA 对控制器会自动故障转移到其配对节点。配对节点从崩溃中恢复并启动后，节点将自动执行交还，使配对节点恢复正常运行。
* 节点发生系统故障，节点无法重新启动。例如，当某个节点因断电而发生故障时， HA 对控制器会自动故障转移到其配对节点，并从运行正常的存储控制器提供数据。



NOTE: 如果节点的存储同时断电，则无法执行标准接管。

* 未从节点的配对节点收到检测信号消息。如果配对节点遇到硬件或软件故障（例如互连故障），而此故障不会导致崩溃，但仍会阻止其正常运行，则可能会发生这种情况。
* 您未使用 ` -f` 或 ` -inhibit-takeover true` 参数暂停其中一个节点。



NOTE: 在启用了集群 HA 的双节点集群中，使用 `‑inhibit‑takeover true` 参数暂停或重新启动节点会导致两个节点停止提供数据，除非先禁用集群 HA ，然后将 epsilon 分配给要保持联机的节点。

* 重新启动其中一个节点时，未使用 `‑inhibit‑takeover true` 参数。（默认情况下， `storage failover` 命令的 `‑onboot` 参数处于启用状态。）
* 远程管理设备（服务处理器）检测到配对节点故障。如果禁用硬件辅助接管，则此选项不适用。


您也可以使用 `storage failover takeover` 命令手动启动接管。
