---
permalink: nas-audit/create-fpolicy-event-task.html 
sidebar: sidebar 
keywords: creating, fpolicy event 
summary: 在创建 FPolicy 策略配置过程中，您需要创建 FPolicy 事件。您可以在创建事件时将其与 FPolicy 策略相关联。事件定义要监控的协议以及要监控和筛选的文件访问事件。 
---
= 创建 FPolicy 事件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在创建 FPolicy 策略配置过程中，您需要创建 FPolicy 事件。您可以在创建事件时将其与 FPolicy 策略相关联。事件定义要监控的协议以及要监控和筛选的文件访问事件。

.开始之前
您应完成FPolicy事件 link:https://docs.netapp.com/us-en/ontap/nas-audit/fpolicy-event-config-worksheet-reference.html["工作表"]。



== 创建 FPolicy 事件

. 使用 `vserver fpolicy policy event create` 命令创建 FPolicy 事件。
+
`vserver fpolicy policy event create -vserver vs1.example.com -event-name event1 -protocol cifs -file-operations open,close,read,write`

. 使用 `vserver fpolicy policy event show` 命令验证 FPolicy 事件配置。
+
`vserver fpolicy policy event show -vserver vs1.example.com`

+
[listing]
----

                  Event               File                    Is Volume
Vserver           Name      Protocols Operations    Filters   Operation
---------------   --------- --------- ------------- --------- ------------
vs1.example.com   event1    cifs      open, close,  -         false
                                      read, write
----




== 创建FPolicy拒绝访问事件

从ONTAP 9.13.1开始、用户可以收到因缺少权限而导致文件操作失败的通知。这些通知对于安全性、勒索软件防护和监管非常重要。

. 使用 `vserver fpolicy policy event create` 命令创建 FPolicy 事件。
+
`vserver fpolicy policy event create -vserver vs1.example.com -event-name event1 -protocol cifs -monitor-fileop-failure true -file-operations open`


