---
permalink: nas-audit/create-persistent-stores.html 
sidebar: sidebar 
keywords: create, persistent store, fpolicy 
summary: 从ONTAP 9.14.1开始、您可以通过FPolicy设置永久性存储、以捕获SVM中异步非强制策略的文件访问事件。永久性存储有助于将客户端I/O处理与FPolicy通知处理分离、以减少客户端延迟。不支持同步和异步强制配置。 
---
= 创建持久性存储
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
从ONTAP 9.14.1开始、FPolicy允许您设置 link:persistent-stores.html["永久性存储"] 捕获SVM中异步非强制策略的文件访问事件。永久性存储有助于将客户端I/O处理与FPolicy通知处理分离、以减少客户端延迟。不支持同步(强制或非强制)和异步强制配置。

.最佳实践
* 在使用永久性存储功能之前、请确保您的合作伙伴应用程序支持此配置。
* 永久性存储卷会按SVM进行设置。对于启用了FPolicy的每个SVM、您都需要一个永久性存储卷。
* 创建卷时指定的永久性存储卷名称和接合路径应匹配。
* 在包含预期Fpolicy监控的最大流量的生命周期的节点上创建永久性存储卷。
* 将Snapshot策略设置为 `none` 而不是 `default`。这是为了确保不会意外还原快照而导致当前事件丢失、并防止可能发生重复的事件处理。
* 使持久存储卷无法用于外部用户协议访问(CIFS或NFS)、以避免意外损坏或删除保留的事件记录。为此、在启用FPolicy后、请在ONTAP中卸载卷以删除接合路径、这样用户协议访问就无法访问该路径。


.步骤
. 在SVM上创建一个可为永久性存储配置的空卷：
+
`volume create -vserver <SVM Name> -volume <volume> -state <online> -junction-path <path> -policy <default> -unix-permissions <777> -size <value> -aggregate <aggregate name> -snapshot-policy <none>`

+
** 永久性存储卷的大小取决于您要使未传送到外部服务器(配对应用程序)的事件持久化的持续时间。
+
例如、如果您希望在每秒容量为3万次通知的集群中持久保留30分钟的事件：

+
所需卷大小= 30000 x 30 x 60 x 0.6 KB (平均通知记录大小)= 3240000 KB =~32 GB

+
要了解大致的通知率、您可以联系您的FPolicy合作伙伴申请、也可以使用FPolicy计数器 `requests_dispatched_rate`。

** 具有足够RBAC权限(用于创建卷)的管理员用户应使用volume CLI命令或REST API创建所需大小的卷、并将该卷的名称提供为 `-volume` 在永久性存储中、创建CLI命令或REST API。


. 创建永久性存储：
+
`vserver fpolicy persistent store create -vserver <SVM> -persistent-store <PS_name> -volume <volume>`

+
** 永久性存储：永久性存储名称
** volume：永久性存储卷


. 创建永久性存储后、您可以创建FPolicy策略并将此永久性存储名称添加到该策略中。
有关详细信息，请参见 link:https://docs.netapp.com/us-en/ontap/nas-audit/create-fpolicy-policy-task.html["创建 FPolicy 策略"]。

