---
permalink: nas-audit/create-security-trace-filters-task.html 
sidebar: sidebar 
keywords: create, security trace filters 
summary: 您可以创建安全跟踪筛选器来检测 Storage Virtual Machine （ SVM ）上的 SMB 和 NFS 客户端操作，并跟踪与此筛选器匹配的所有访问检查。您可以使用安全跟踪的结果来验证配置或对访问问题进行故障排除。 
---
= 创建安全跟踪筛选器
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以创建安全跟踪筛选器来检测 Storage Virtual Machine （ SVM ）上的 SMB 和 NFS 客户端操作，并跟踪与此筛选器匹配的所有访问检查。您可以使用安全跟踪的结果来验证配置或对访问问题进行故障排除。

vserver security trace filter create 命令需要两个参数：

[cols="2*"]
|===
| 所需参数 | Description 


 a| 
` -vserver` `vserver_name`
 a| 
_SVM 名称 _

包含要应用安全跟踪筛选器的文件或文件夹的 SVM 的名称。



 a| 
` 索引` `index_number`
 a| 
筛选索引号 _

要应用于筛选器的索引编号。每个 SVM 最多只能有 10 个跟踪筛选器。此参数允许的值为 1 到 10 。

|===
您可以使用多个可选筛选器参数自定义安全跟踪筛选器，以便缩小安全跟踪生成的结果范围：

[cols="2*"]
|===
| filter 参数 | Description 


 a| 
` 客户端 IP` `IP_Address`
 a| 
此筛选器指定用户从中访问 SVM 的 IP 地址。



 a| 
` 路径` `路径`
 a| 
此筛选器指定要应用权限跟踪筛选器的路径。` -path` 的值可以使用以下格式之一：

* 从共享或导出的根目录开始的完整路径
* 相对于共享根的部分路径


必须在路径值中使用 NFS 模式目录 UNIX 模式目录分隔符。



 a| 
` -windows-name` `win_user_name` 或 ` -unix-name``unix_user_name`
 a| 
您可以指定要跟踪其访问请求的 Windows 用户名或 UNIX 用户名。用户名变量不区分大小写。您不能在同一筛选器中同时指定 Windows 用户名和 UNIX 用户名。

[NOTE]
====
即使您可以跟踪 SMB 和 NFS 访问事件，在对混合或 UNIX 安全模式数据执行访问检查时，也可能会使用映射的 UNIX 用户和映射的 UNIX 用户组。

====


 a| 
` -trace-allow` ｛`yes` ｝`no` ｝
 a| 
对于安全跟踪筛选器，始终会启用对拒绝事件的跟踪。您可以选择跟踪允许事件。要跟踪允许事件，请将此参数设置为 `yes` 。



 a| 
` 已启用` ｛`已启用` `d已启用` 已禁用 ｝
 a| 
您可以启用或禁用安全跟踪筛选器。默认情况下，安全跟踪筛选器处于启用状态。



 a| 
` 时间启用` `整型`
 a| 
您可以为筛选器指定超时时间，超过此超时时间后将其禁用。

|===
.步骤
. 创建安全跟踪筛选器：
+
`vserver security trace filter create -vserver vserver_name -index index_numberfilter_parameters`

+
`filter_parameters` 是可选筛选器参数的列表。

+
有关详细信息，请参见命令的手册页。

. 验证安全跟踪筛选器条目：
+
`vserver security trace filter show -vserver vserver_name -index index_number`



以下命令将为从 IP 地址 10.10.10.7 访问共享路径为 ` \\server\share1\dir1\dir2\file.txt` 的文件的任何用户创建安全跟踪筛选器。此筛选器会为 ` -path` 选项使用一个完整路径。用于访问数据的客户端 IP 地址为 10.10.10.7 。筛选器在 30 分钟后超时：

[listing]
----
cluster1::> vserver security trace filter create -vserver vs1 -index 1 -path /dir1/dir2/file.txt -time-enabled 30 -client-ip 10.10.10.7
cluster1::> vserver security trace filter show -index 1
Vserver  Index   Client-IP            Path            Trace-Allow  Windows-Name
-------- -----  -----------  ----------------------   -----------  -------------
vs1        1    10.10.10.7   /dir1/dir2/file.txt          no       -
----
以下命令使用 ` 路径` 选项的相对路径创建安全跟踪筛选器。此筛选器会跟踪名为 "`Joe` " 的 Windows 用户的访问权限。Joe 正在访问共享路径为 ` \\server\share1\dir1\dir2\file.txt` 的文件。筛选器跟踪允许和拒绝事件：

[listing]
----
cluster1::> vserver security trace filter create -vserver vs1 -index 2 -path /dir1/dir2/file.txt -trace-allow yes -windows-name mydomain\joe

cluster1::> vserver security trace filter show -vserver vs1 -index 2
                                 Vserver: vs1
                            Filter Index: 2
              Client IP Address to Match: -
                                    Path: /dir1/dir2/file.txt
                       Windows User Name: mydomain\joe
                          UNIX User Name: -
                      Trace Allow Events: yes
                          Filter Enabled: enabled
               Minutes Filter is Enabled: 60
----