---
permalink: nas-audit/display-connections-external-fpolicy-servers-task.html 
sidebar: sidebar 
keywords: display, information, connections, external fpolicy servers 
summary: 您可以显示有关与集群或指定 Storage Virtual Machine （ SVM ）的外部 FPolicy 服务器（ FPolicy 服务器）连接的状态信息。此信息可帮助您确定连接了哪些 FPolicy 服务器。 
---
= 显示有关与外部 ONTAP FPolicy 服务器的连接的信息
:allow-uri-read: 


[role="lead"]
您可以显示有关与集群或指定 Storage Virtual Machine （ SVM ）的外部 FPolicy 服务器（ FPolicy 服务器）连接的状态信息。此信息可帮助您确定连接了哪些 FPolicy 服务器。

.关于此任务
如果未指定任何参数，则此命令将显示以下信息：

* SVM name
* Node name
* FPolicy policy name
* FPolicy 服务器 IP 地址
* FPolicy 服务器状态
* FPolicy 服务器类型


除了显示有关集群或特定 SVM 上的 FPolicy 连接的信息之外，您还可以使用命令参数按其他条件筛选命令的输出。

您可以指定 `-instance` 用于显示有关列出策略的详细信息的参数。或者、您也可以使用 `-fields` 参数、以便在命令输出中仅显示指示的字段。您可以输入 `?` 之后 `-fields` 用于确定可以使用哪些字段的参数。

.步骤
. 使用相应的命令显示有关节点与 FPolicy 服务器之间连接状态的筛选信息：
+
[cols="35,65"]
|===


| 要显示有关 FPolicy 服务器的连接状态信息 ... | 输入 ... 


 a| 
您指定的
 a| 
`vserver fpolicy show-engine -server IP_address`



 a| 
指定的 SVM
 a| 
`vserver fpolicy show-engine -vserver vserver_name`



 a| 
附加了指定策略的
 a| 
`vserver fpolicy show-engine -policy-name policy_name`



 a| 
指定的服务器状态
 a| 
`vserver fpolicy show-engine -server-status status`

服务器状态可以是以下状态之一：

** `connected`
** `disconnected`
** `connecting`
** `disconnecting`




 a| 
指定类型
 a| 
`vserver fpolicy show-engine -server-type type`

FPolicy 服务器类型可以是以下类型之一：

** `primary`
** `secondary`




 a| 
已因指定原因断开连接的
 a| 
`vserver fpolicy show-engine -disconnect-reason text`

断开连接的原因可能有多种。以下是断开连接的常见原因：

** `Disconnect command received from CLI.`
** `Error encountered while parsing notification response from FPolicy server.`
** `FPolicy Handshake failed.`
** `SSL handshake failed.`
** `TCP Connection to FPolicy server failed.`
** `The screen response message received from the FPolicy server is not valid.`


|===


.示例
此示例显示了有关 SVM vs1.example.com 上 FPolicy 服务器的外部引擎连接的信息：

[listing]
----
cluster1::> vserver fpolicy show-engine -vserver vs1.example.com
FPolicy                                              Server-       Server-
Vserver         Policy    Node         Server        status        type
--------------- --------- ------------ ------------- ------------- ---------
vs1.example.com policy1   node1        10.1.1.2      connected     primary
vs1.example.com policy1   node1        10.1.1.3      disconnected  primary
vs1.example.com policy1   node2        10.1.1.2      connected     primary
vs1.example.com policy1   node2        10.1.1.3      disconnected  primary
----
此示例仅显示有关已连接 FPolicy 服务器的信息：

[listing]
----
cluster1::> vserver fpolicy show-engine -fields server -server-status connected
node       vserver         policy-name server
---------- --------------- ----------- -------
node1      vs1.example.com policy1     10.1.1.2
node2      vs1.example.com policy1     10.1.1.2
----