---
permalink: nas-audit/display-audit-policies-windows-security-tab-task.html 
sidebar: sidebar 
keywords: display, information, audit policies, windows security tab 
summary: 您可以使用 Windows 属性窗口中的安全性选项卡显示已应用于文件和目录的审核策略的信息。这与驻留在 Windows 服务器上的数据使用的方法相同，这样客户就可以使用他们习惯使用的相同图形用户界面。 
---
= 通过访问ONTAP安全性选项卡查看Windows审核策略信息
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 Windows 属性窗口中的安全性选项卡显示已应用于文件和目录的审核策略的信息。这与驻留在 Windows 服务器上的数据使用的方法相同，这样客户就可以使用他们习惯使用的相同图形用户界面。

.关于此任务
通过显示应用于文件和目录的审核策略信息，您可以验证是否已在指定文件和文件夹上设置了适当的系统访问控制列表（ SACL ）。

要显示已应用于 NTFS 文件和文件夹的 SACL 的信息，请在 Windows 主机上完成以下步骤。

.步骤
. 从 Windows 资源管理器的 * 工具 * 菜单中，选择 * 映射网络驱动器 * 。
. 完成 * 映射网络驱动器 * 对话框：
+
.. 选择一个 * 驱动器 * 字母。
.. 在*文件夹*框中，键入Storage Virtual Machine (SVM)的IP地址或SMB服务器名称，该共享包含要审核的数据和共享名称。
+
如果SMB服务器名称为`SMB_Server`、而共享名为`shre1`、则应输入 `\\SMB_SERVER\share1`。

+
[NOTE]
====
您可以指定SMB服务器数据接口的IP地址、而不是SMB服务器名称。

====
.. 单击 * 完成 * 。


+
您选择的驱动器已挂载并准备就绪，此时将显示 Windows 资源管理器窗口，其中显示共享中包含的文件和文件夹。

. 选择要显示其审核信息的文件或目录。
. 右键单击文件或目录，然后选择 * 属性 * 。
. 选择 * 安全性 * 选项卡。
. 单击 * 高级 * 。
. 选择 * 审核 * 选项卡。
. 单击 * 继续 * 。
+
此时将打开审核框。"* 审核条目 * " 框显示应用了 SACL 的用户和组的摘要。

. 在 * 审核条目 * 框中，选择要显示其 SACL 条目的用户或组。
. 单击 * 编辑 * 。
+
此时将打开 "<objecy> 的审核条目 " 框。

. 在 * 访问 * 框中，查看应用于选定对象的当前 SACL 。
. 单击 * 取消 * 以关闭 * 审核条目 < 对象 >* 框。
. 单击 * 取消 * 关闭 * 审核 * 框。

