---
permalink: nas-audit/fpolicy-passthrough-read-enhances-usability-concept.html 
sidebar: sidebar 
keywords: fpolicy, passthrough-read, enhances, usability, hierarchical, storage management 
summary: 通过直通读取， FPolicy 服务器（用作分层存储管理（ HSM ）服务器）可以对脱机文件进行读取访问，而无需将文件从二级存储系统重新调用到主存储系统。 
---
= ONTAP FPolicy 直通读取如何增强分层存储管理的可用性
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过直通读取， FPolicy 服务器（用作分层存储管理（ HSM ）服务器）可以对脱机文件进行读取访问，而无需将文件从二级存储系统重新调用到主存储系统。

如果将 FPolicy 服务器配置为向 SMB 服务器上的文件提供 HSM ，则会发生基于策略的文件迁移，其中，文件脱机存储在二级存储上，而只有存根文件保留在主存储上。即使存根文件在客户端中显示为普通文件，但它实际上是一个与原始文件大小相同的稀疏文件。稀疏文件设置了SMB脱机位、并指向已迁移到二级存储的实际文件。

通常，在收到脱机文件的读取请求时，必须将请求的内容重新调用回主存储，然后通过主存储进行访问。需要将数据重新调用回主存储会产生一些不希望出现的影响。其中一个不希望受到的影响是，由于需要在响应请求之前重新调用内容，客户端请求的延迟增加，并且主存储上重新调用的文件所需的空间消耗增加。

通过 FPolicy 直通读取， HSM 服务器（ FPolicy 服务器）可以对已迁移的脱机文件提供读取访问，而无需将文件从二级存储系统重新调用到主存储系统。可以直接从二级存储处理读取请求，而不是将文件重新调用回主存储。

[NOTE]
====
FPolicy 直通读取操作不支持副本卸载（ ODX ）。

====
直通读取通过提供以下优势增强了可用性：

* 即使主存储没有足够的空间将请求的数据重新调用回主存储，也可以处理读取请求。
* 当数据重新调用可能激增时，例如脚本或备份解决方案需要访问多个脱机文件时，可以更好地管理容量和性能。
* 可以处理快照中脱机文件的读取请求。
+
由于快照是只读的、因此、如果存根文件位于快照中、则FPolicy服务器无法还原原始文件。使用直通读取可消除此问题。

* 可以设置策略来控制何时通过访问二级存储上的文件来处理读取请求，以及何时应将脱机文件重新调用到主存储。
+
例如，可以在 HSM 服务器上创建一个策略，用于指定在将脱机文件迁移回主存储之前的指定时间段内可以访问该文件的次数。此类策略可避免调用很少访问的文件。





== 启用 FPolicy 直通读取时如何管理读取请求

您应了解启用 FPolicy 直通读取时如何管理读取请求，以便以最佳方式配置 Storage Virtual Machine （ SVM ）和 FPolicy 服务器之间的连接。

启用 FPolicy 直通读取后，如果 SVM 收到脱机文件请求，则 FPolicy 将通过标准连接通道向 FPolicy 服务器（ HSM 服务器）发送通知。

收到通知后， FPolicy 服务器将从通知中发送的文件路径读取数据，并通过 SVM 与 FPolicy 服务器之间建立的直通读取特权数据连接将请求的数据发送到 SVM 。

发送数据后， FPolicy 服务器将对读取请求做出响应，即允许或拒绝。根据读取请求是被允许还是被拒绝， ONTAP 会向客户端发送请求的信息或错误消息。
