---
permalink: nas-audit/fpolicy-config-types-concept.html 
sidebar: sidebar 
keywords: fpolicy, configuration types 
summary: 有两种基本的 FPolicy 配置类型。一种配置使用外部 FPolicy 服务器处理通知并对通知采取措施。另一种配置不使用外部 FPolicy 服务器，而是使用 ONTAP 内部原生 FPolicy 服务器根据扩展来简单地阻止文件。 
---
= FPolicy 配置类型
:icons: font
:imagesdir: ../media/


[role="lead"]
有两种基本的 FPolicy 配置类型。一种配置使用外部 FPolicy 服务器处理通知并对通知采取措施。另一种配置不使用外部 FPolicy 服务器，而是使用 ONTAP 内部原生 FPolicy 服务器根据扩展来简单地阻止文件。

* * 外部 FPolicy 服务器配置 *
+
此通知将发送到 FPolicy 服务器，该服务器会筛选请求并应用规则来确定节点是否应允许所请求的文件操作。对于同步策略， FPolicy 服务器会向节点发送响应，以允许或阻止请求的文件操作。

* * 原生 FPolicy 服务器配置 *
+
通知将在内部进行筛选。根据在 FPolicy 范围中配置的文件扩展名设置，允许或拒绝此请求。





== 何时创建原生 FPolicy 配置

原生 FPolicy 配置使用 ONTAP 内部 FPolicy 引擎根据文件扩展名监控和阻止文件操作。此解决方案不需要外部 FPolicy 服务器（ FPolicy 服务器）。如果只需使用此简单解决方案，则可以使用原生文件阻止配置。

通过原生文件阻止，您可以监控与配置的操作和筛选事件匹配的任何文件操作，然后拒绝访问具有特定扩展名的文件。这是默认配置。

此配置提供了一种仅根据文件扩展名阻止文件访问的方法。例如，要阻止包含 `mP3` 扩展名的文件，您需要配置一个策略，以便为目标文件扩展名为 `mP3` 的某些操作提供通知。此策略配置为拒绝为生成通知的操作请求 `mP3` 文件。

以下适用场景原生 FPolicy 配置：

* 原生文件阻止也支持基于 FPolicy 服务器的文件筛选所支持的同一组筛选器和协议。
* 可以同时配置原生文件阻止和基于 FPolicy 服务器的文件筛选应用程序。
+
为此，您可以为 Storage Virtual Machine （ SVM ）配置两个单独的 FPolicy 策略，其中一个策略配置为阻止原生文件，另一个策略配置为基于 FPolicy 服务器的文件筛选。

* 原生文件阻止功能仅根据扩展名而不是文件内容对文件进行筛选。
* 对于符号链接，原生文件阻止使用根文件的文件扩展名。




== 何时创建使用外部 FPolicy 服务器的配置

使用外部 FPolicy 服务器处理和管理通知的 FPolicy 配置可为需要基于文件扩展名进行简单文件阻止的使用情形提供强大的解决方案。

如果要执行以下操作，您应创建一个使用外部 FPolicy 服务器的配置：监控和记录文件访问事件，提供配额服务，根据简单文件扩展名以外的标准执行文件阻止，使用分层存储管理应用程序提供数据迁移服务， 或者，提供一组细化策略，这些策略仅监控 Storage Virtual Machine （ SVM ）中的一部分数据。
