---
permalink: nas-audit/index.html 
sidebar: sidebar 
keywords: file, access, auditing, audit, smb, cifs, nfs, fpolicy, udit, nas, events, svms 
summary: 您可以将 SMB 和 NFS 协议可用的文件访问审核功能与 ONTAP 结合使用，例如，使用 FPolicy 进行原生审核和文件策略管理。 
---
= SMB 和 NFS 审核和安全跟踪
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以将 SMB 和 NFS 协议可用的文件访问审核功能与 ONTAP 结合使用，例如，使用 FPolicy 进行原生审核和文件策略管理。

在以下情况下，您应设计并实施 SMB 和 NFS 文件访问事件审核：

* 已配置基本 SMB 和 NFS 协议文件访问。
* 您希望使用以下方法之一创建和维护审核配置：
+
** 原生 ONTAP 功能
** 外部 FPolicy 服务器






== 审核 SVM 上的 NAS 事件

审核NAS事件是一种安全措施、可用于跟踪和记录Storage Virtual Machine (SVM)上的某些SMB和NFS事件。这有助于您跟踪潜在的安全问题，并提供任何安全违规的证据。您还可以暂存和审核 Active Directory 中央访问策略，以查看实施这些策略的结果。



=== SMB事件

您可以审核以下事件：

* SMB 文件和文件夹访问事件
+
您可以审核存储在属于已启用审核的 SVM 的 FlexVol 卷上的对象上的 SMB 文件和文件夹访问事件。

* SMB登录和注销事件
+
您可以审核SVM上SMB服务器的SMB登录和注销事件。

* 中央访问策略暂存事件
+
您可以使用通过建议的中央访问策略应用的权限审核SMB服务器上对象的有效访问。通过对中央访问策略的暂存进行审核，您可以在部署之前查看中央访问策略的影响。

+
中央访问策略暂存的审核是使用 Active Directory GPO 设置的；但是，必须配置 SVM 审核配置以审核中央访问策略暂存事件。

+
虽然您可以在审核配置中启用中央访问策略暂存、而无需在SMB服务器上启用动态访问控制、但只有在启用动态访问控制后、才会生成中央访问策略暂存事件。动态访问控制可通过SMB服务器选项启用。默认情况下，不会启用此功能。





=== NFS事件

您可以对SVM上存储的对象使用NFSv4 ACL来审核文件和目录事件。
