---
permalink: nas-audit/restrictions-fpolicy-mcc-svm-disaster-recovery-concept.html 
sidebar: sidebar 
keywords: restrictions, cluster-scoped, fpolicy, external engines, metrocluster, svm disaster recovery configurations 
summary: 您可以通过将集群 Storage Virtual Machine （ SVM ）分配给外部引擎来创建集群范围的 FPolicy 外部引擎。但是，在 MetroCluster 或 SVM 灾难恢复配置中创建集群范围的外部引擎时，在选择 SVM 用于与 FPolicy 服务器进行外部通信的身份验证方法时，存在某些限制。 
---
= 具有 MetroCluster 和 SVM 灾难恢复配置的集群范围 ONTAP FPolicy 外部引擎的限制
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以通过将集群 Storage Virtual Machine （ SVM ）分配给外部引擎来创建集群范围的 FPolicy 外部引擎。但是，在 MetroCluster 或 SVM 灾难恢复配置中创建集群范围的外部引擎时，在选择 SVM 用于与 FPolicy 服务器进行外部通信的身份验证方法时，存在某些限制。

创建外部 FPolicy 服务器时，您可以选择三种身份验证选项：无身份验证， SSL 服务器身份验证和 SSL 相互身份验证。尽管在将外部 FPolicy 服务器分配给数据 SVM 时选择身份验证选项没有任何限制，但在创建集群范围的 FPolicy 外部引擎时仍存在一些限制：

[cols="75,25"]
|===


| Configuration | 是否允许？ 


 a| 
MetroCluster 或 SVM 灾难恢复以及集群范围的 FPolicy 外部引擎，不进行身份验证（未配置 SSL ）
 a| 
是的。



 a| 
MetroCluster 或 SVM 灾难恢复以及具有 SSL 服务器或 SSL 相互身份验证的集群范围 FPolicy 外部引擎
 a| 
否

|===
* 如果存在具有 SSL 身份验证的集群范围的 FPolicy 外部引擎，而您要创建 MetroCluster 或 SVM 灾难恢复配置，则必须先修改此外部引擎以不使用身份验证或删除外部引擎，然后才能创建 MetroCluster 或 SVM 灾难恢复配置。
* 如果 MetroCluster 或 SVM 灾难恢复配置已存在，则 ONTAP 会阻止您使用 SSL 身份验证创建集群范围的 FPolicy 外部引擎。

