---
permalink: nas-audit/supported-file-operation-filter-fpolicy-nfsv4-concept.html 
sidebar: sidebar 
keywords: ontap 9, supported file operation, filter combinations, fpolicy, monitor, nfsv4 
summary: 在配置 FPolicy 事件时，您需要注意，在监控 NFSv4 文件访问操作时，仅支持特定的文件操作和筛选器组合。 
---
= ONTAP FPolicy 为 NFSv4 监控的支持的文件操作和过滤器组合
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在配置 FPolicy 事件时，您需要注意，在监控 NFSv4 文件访问操作时，仅支持特定的文件操作和筛选器组合。

从ONTAP 9.15.1开始、FPolicy支持NFSv4.1协议。

下表列出了对NFSv4或NFSv4.1文件访问事件执行FPolicy监控时支持的文件操作和筛选器组合：

[cols="30,70"]
|===


| 支持的文件操作 | 支持的筛选器 


 a| 
关闭
 a| 
脱机位，排除目录



 a| 
创建
 a| 
脱机位



 a| 
create_dir
 a| 
目前，此文件操作不支持任何筛选器。



 a| 
删除
 a| 
脱机位



 a| 
delete_dir
 a| 
目前，此文件操作不支持任何筛选器。



 a| 
getattr
 a| 
脱机位，排除目录



 a| 
链接。
 a| 
脱机位



 a| 
查找
 a| 
脱机位，排除目录



 a| 
打开
 a| 
脱机位，排除目录



 a| 
读取
 a| 
脱机位，首次读取



 a| 
写入
 a| 
脱机位，首次写入，写入时更改大小



 a| 
重命名
 a| 
脱机位



 a| 
rename_dir
 a| 
目前，此文件操作不支持任何筛选器。



 a| 
SETATTR
 a| 
脱机位， setattr_and_owner_change ， setattr_and_group_change ， setattr_and_mode_change ， setattr_and_sacl_change ， setattr_and_dacl_change ， setattr_and_modify_time_change ， setattr_and_access_time_change ， setattr_and_size_change ， exclude_directory



 a| 
符号链接
 a| 
脱机位

|===
从ONTAP 9.13.1开始、用户可以收到因缺少权限而导致文件操作失败的通知。下表列出了对NFSv4或NFSv4.1文件访问事件执行FPolicy监控时支持的拒绝访问文件操作和筛选器组合：

[cols="30,70"]
|===


| 支持拒绝访问文件操作 | 支持的筛选器 


 a| 
访问
 a| 
不适用



 a| 
创建
 a| 
不适用



 a| 
create_dir
 a| 
不适用



 a| 
删除
 a| 
不适用



 a| 
delete_dir
 a| 
不适用



 a| 
链接。
 a| 
不适用



 a| 
打开
 a| 
不适用



 a| 
读取
 a| 
不适用



 a| 
重命名
 a| 
不适用



 a| 
rename_dir
 a| 
不适用



 a| 
SETATTR
 a| 
不适用



 a| 
写入
 a| 
不适用

|===