---
permalink: nas-audit/troubleshoot-auditing-staging-volume-concept.html 
sidebar: sidebar 
keywords: troubleshoot, audit, stage, volume space, issues 
summary: 如果暂存卷或包含审核事件日志的卷上没有足够的空间，则可能会出现问题。如果空间不足，则无法创建新的审核记录，从而阻止客户端访问数据，并且访问请求将失败。您应了解如何对这些卷空间问题进行故障排除和解决。 
---
= 对审核和暂存卷空间问题进行故障排除
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果暂存卷或包含审核事件日志的卷上没有足够的空间，则可能会出现问题。如果空间不足，则无法创建新的审核记录，从而阻止客户端访问数据，并且访问请求将失败。您应了解如何对这些卷空间问题进行故障排除和解决。



== 对与事件日志卷相关的空间问题进行故障排除

如果包含事件日志文件的卷用尽空间，审核将无法将日志记录转换为日志文件。这会导致客户端访问失败。您必须了解如何对与事件日志卷相关的空间问题进行故障排除。

* Storage Virtual Machine （ SVM ）和集群管理员可以通过显示有关卷和聚合使用情况和配置的信息来确定卷空间是否不足。
* 如果包含事件日志的卷空间不足， SVM 和集群管理员可以通过删除某些事件日志文件或增加卷大小来解决空间问题。
+
[NOTE]
====
如果包含事件日志卷的聚合已满，则必须先增加聚合的大小，然后才能增加卷的大小。只有集群管理员才能增加聚合的大小。

====
* 可以通过修改审核配置将事件日志文件的目标路径更改为另一个卷上的目录。
+
[NOTE]
====
在以下情况下，数据访问被拒绝：

** 删除目标目录时。
** 如果托管目标目录的卷上的文件限制达到其最大级别。


====


详细了解：

* link:../volumes/index.html["如何查看有关卷和增加卷大小的信息"]。
* link:../disks-aggregates/index.html["如何查看有关聚合和管理聚合的信息"]。




== 对与暂存卷相关的空间问题进行故障排除

如果包含 Storage Virtual Machine （ SVM ）暂存文件的任何卷用尽空间，审核将无法将日志记录写入暂存文件。这会导致客户端访问失败。要对此问题描述进行故障排除，您需要通过显示有关卷使用情况的信息来确定 SVM 中使用的任何暂存卷是否已满。

如果包含整合事件日志文件的卷具有足够的空间，但由于空间不足仍存在客户端访问失败的情况，则暂存卷可能会空间不足。SVM 管理员必须与您联系，以确定包含 SVM 暂存文件的暂存卷是否空间不足。如果由于暂存卷空间不足而无法生成审核事件，则审核子系统将生成 EMS 事件。此时将显示以下消息： `No space left on device` 。只有您才能查看暂存卷的相关信息； SVM 管理员无法查看此信息。

所有暂存卷名称均以 `Mdm_aud_` 开头，后跟包含该暂存卷的聚合的 UUID 。以下示例显示了管理 SVM 上的四个系统卷，这些系统卷是在为集群中的数据 SVM 创建文件服务审核配置时自动创建的：

[listing]
----
cluster1::> volume show -vserver cluster1
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
cluster1  MDV_aud_1d0131843d4811e296fc123478563412
                       aggr0        online     RW          2GB     1.90GB    5%
cluster1  MDV_aud_8be27f813d7311e296fc123478563412
                       root_vs0     online     RW          2GB     1.90GB    5%
cluster1  MDV_aud_9dc4ad503d7311e296fc123478563412
                       aggr1        online     RW          2GB     1.90GB    5%
cluster1  MDV_aud_a4b887ac3d7311e296fc123478563412
                       aggr2        online     RW          2GB     1.90GB    5%
4 entries were displayed.
----
如果暂存卷中的空间不足，您可以通过增加卷的大小来解决空间问题。

[NOTE]
====
如果包含暂存卷的聚合已满，则必须先增加聚合的大小，然后才能增加卷的大小。只有您才能增加聚合的大小； SVM 管理员无法增加聚合的大小。

====
如果一个或多个聚合的可用空间小于 2 GB ，则 SVM 审核创建将失败。如果 SVM 审核创建失败，则已创建的暂存卷将被删除。
