---
permalink: san-config/fibre-channel-fcoe-zoning-concept.html 
sidebar: sidebar 
keywords: fibre, channel, fcoe zoning 
summary: FC ， FC-NVMe 或 FCoE 分区是网络结构中一个或多个端口的逻辑分组。要使设备能够彼此查看，连接，创建彼此的会话以及进行通信，两个端口都需要具有公共区域成员资格。建议使用单个启动程序分区。 
---
= 光纤通道和 FCoE 分区概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FC ， FC-NVMe 或 FCoE 分区是网络结构中一个或多个端口的逻辑分组。要使设备能够彼此查看，连接，创建彼此的会话以及进行通信，两个端口都需要具有公共区域成员资格。建议使用单个启动程序分区。



== 分区原因

* 分区可减少或消除启动程序 HBA 之间的 _c交叉 控制。
+
即使在小型环境中也会出现这种情况，这是实施分区的最佳参数之一。通过分区创建的逻辑网络结构子集可消除串扰问题。

* 分区可减少指向特定 FC ， FC-NVMe 或 FCoE 端口的可用路径数，并减少主机与可见的特定 LUN 之间的路径数。
+
例如，某些主机操作系统多路径解决方案会限制其可管理的路径数。分区可以减少操作系统多路径驱动程序看到的路径数。如果主机未安装多路径解决方案，则需要通过在网络结构中使用分区或在 SVM 中使用选择性 LUN 映射（ SLM ）和端口集的组合来验证是否只能显示 LUN 的一个路径。

* 分区通过限制对共享一个公共区域的端点的访问和连接来提高安全性。
+
没有通用分区的端口无法彼此通信。

* 分区可通过隔离发生的问题来提高 SAN 可靠性，并通过限制问题空间来帮助缩短问题解决时间。




== 分区建议

* 如果四个或更多主机连接到 SAN ，或者节点上未对 SAN 实施 SLM ，则应随时实施分区。
* 虽然某些交换机供应商可以使用全球通用节点名称分区，但要正确定义特定端口并有效使用 NPIV ，需要使用全球通用端口名称分区。
* 您应在保持易管理性的同时限制分区大小。
+
多个分区可以重叠以限制大小。理想情况下，为每个主机或主机集群定义一个分区。

* 您应使用单启动程序分区来消除启动程序 HBA 之间的串扰。

