---
permalink: san-config/host-support-multipathing-concept.html 
sidebar: sidebar 
keywords: host, support, multipathing 
summary: ONTAP 始终对 FC 和 iSCSI 路径使用非对称逻辑单元访问（ Asymmetric Logical Unit Access ， ALUA ）。请务必使用支持 FC 和 iSCSI 协议 ALUA 的主机配置。 
---
= ONTAP支持SAN主机多路径
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP可使用非对称逻辑单元访问(ANAUA)软件为FC和iSCSI主机提供多路径功能。

从ONTAP 9.5开始、使用异步命名空间访问(ANA)的NVMe主机支持多路径高可用性(HA)对故障转移/交还。在ONTAP 9.4中、NVMe仅支持从主机到目标的一条路径、因此应用程序主机必须管理到其HA配对节点的路径故障转移。

有关哪些特定主机配置支持 ALUA 或 ANA 的信息，请参见 https://mysupport.netapp.com/matrix["NetApp 互操作性表工具"^] 和 https://docs.netapp.com/us-en/ontap-sanhost/index.html["ONTAP SAN 主机配置"] 适用于主机操作系统。

在 HA 配置中建议使用多路径软件，也称为 MPIO（多路径 I/O）软件。您的 SAN 主机上需要多路径软件，以便它可以通过多条路径访问 LUN 或 NVMe 命名空间。它向操作系统提供到 LUN 或 NVMe 命名空间的所有路径的单个磁盘。如果没有它，操作系统可能会将每条路径视为单独的磁盘，从而导致数据损坏。

如果您具有以下任一项，则解决方案将被视为具有多个路径：

* 主机中的单个启动程序端口，连接到 SVM 中的多个 SAN LIF
* 多个启动程序端口连接到 SVM 中的单个 SAN LIF
* 多个启动程序端口连接到 SVM 中的多个 SAN LIF


您应该使用 Selective LUN Map、FC 交换机分区或端口集来限制用于访问 LUN 和命名空间的路径。

.相关信息
了解 link:../san-admin/multipath-automatic-lif-failover-support.html["ONTAP 支持的 SAN 多路径配置"]。



[[recommended-number-of-paths-from-host-to-nodes-in-cluster]]
== 从主机到集群中节点的建议路径数

从主机到集群中每个节点的路径不应超过八个。此外、您还不应超过主机操作系统可支持的路径总数以及主机上使用的多路径。

如果集群中有四个或更多节点，或者任何节点中的 SVM 正在使用四个以上的目标端口， 您可以使用以下方法限制可用于访问节点上 LUN 的路径数，以便不超过建议的最大路径数 8 个。

* link:../san-admin/selective-lun-map-concept.html["选择性 LUN 映射（ SLM ）"]
+
SLM 将从主机到 LUN 的路径数减少到只有拥有 LUN 的节点和拥有节点的 HA 配对节点上的路径。SLM 默认启用。每个 LUN 至少应有两个路径，这些路径通过群集中的存储虚拟机 (SVM) 使用的 SLM 连接到每个报告节点。这消除了单点故障，并使系统能够在组件故障中幸存下来。

* link:../san-admin/limit-lun-access-portsets-igroups-concept.html["端口集"]
+
可以将端口集与SLM结合使用、以便进一步限制某些目标对某些启动程序的访问。如果将 SLM 与端口集结合使用，则可以通过 LUN 所属节点以及该节点的 HA 配对节点上端口集中的一组 LIF 访问 LUN 。

* 来自主机的启动器组（igroup）映射
+
您可定义 igroup 并将其映射到 LUN，以控制哪些启动程序能够访问 LUN。

* link:../san-config/fc-fcoe-recommended-zoning-configuration.html["FC 交换机分区"]
+
如果主机未安装多路径解决方案，如果四个或更多主机连接到 SAN，或者集群中的节点未实施 SLM，则应创建分区配置。


