---
permalink: san-config/update-qlogic-hba-queue-depths-linux-host-task.html 
sidebar: sidebar 
keywords: updating, qlogic, hba, queue, depths, linux, host 
summary: 您可以在 Linux 主机上更新 QLogic 驱动程序的设备队列深度。要使更新在重新启动后保持持久性，必须创建新的 RAM 磁盘映像并重新启动主机。您可以使用 QLogic HBA 管理 GUI 或命令行界面（ CLI ）修改 QLogic HBA 队列深度。 
---
= 更新 Linux 主机上的 QLogic HBA 队列深度
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在 Linux 主机上更新 QLogic 驱动程序的设备队列深度。要使更新在重新启动后保持持久性，必须创建新的 RAM 磁盘映像并重新启动主机。您可以使用 QLogic HBA 管理 GUI 或命令行界面（ CLI ）修改 QLogic HBA 队列深度。

此任务显示如何使用 QLogic HBA 命令行界面修改 QLogic HBA 队列深度

.步骤
. 确定要修改的设备队列深度参数：
+
`modinfo qla2xxx` grep ql2xmaxqdepth

+
您只能修改 `ql2xmaxqdepth` queue depth 参数，该参数表示可以为每个 LUN 设置的最大队列深度。对于 RHEL 7.5 及更高版本，默认值为 64 。对于 RHEL 7.4 及更早版本，默认值为 32 。

+
[listing]
----
root@localhost ~]# modinfo qla2xxx|grep ql2xmaxqdepth
parm:       ql2xmaxqdepth:Maximum queue depth to set for each LUN. Default is 64. (int)
----
. 更新设备队列深度值：
+
** 如果要使修改持久，请执行以下步骤：
+
... 通过将队列深度参数添加到 Red Hat Enterprise Linux 5.x 系统的 ` /etc/modprobe.conf` 文件和 Red Hat Enterprise Linux 6.x 或 7.x 系统的 ` /etc/modprobe.d/scsi.conf` 文件或 SUSE Linux Enterprise Server 11.x 或 12.x 系统的 `/etc/modprobe.d/mscsi.conf` 文件来更新队列深度： options qmax_qla2xxx 或 maxqfase=new depth
... 创建新的 RAM 磁盘映像，然后重新启动主机，使更新在重新启动后保持不变。
+
有关详细信息，请参见适用于您的 Linux 操作系统版本的《系统管理参考指南》。



** 如果要仅修改当前会话的参数，请运行以下命令：
+
`echo new_queue_depth > /sys/module/qla2xxx/parameters/ql2xmaxqdepth`

+
在以下示例中，队列深度设置为 128 。

+
[listing]
----
echo 128 > /sys/module/qla2xxx/parameters/ql2xmaxqdepth
----


. 验证队列深度值是否已更新：
+
`cat /sys/module/qla2xxx/parameters/ql2xmaxqdepth`

+
此时将显示队列深度的当前值。

. 通过在 QLogic HBA BIOS 中更新固件参数 `Execution Throttle` 来修改 QLogic HBA 队列深度。
+
.. 登录到 QLogic HBA 管理 CLI ：
+
` /opt/QLogic_Corporation/QConvergeConsoleCLI/qaucli`

.. 从主菜单中，选择 `Adapter Configuration` 选项。
+
[listing]
----
[root@localhost ~]# /opt/QLogic_Corporation/QConvergeConsoleCLI/qaucli
Using config file: /opt/QLogic_Corporation/QConvergeConsoleCLI/qaucli.cfg
Installation directory: /opt/QLogic_Corporation/QConvergeConsoleCLI
Working dir: /root

QConvergeConsole

        CLI - Version 2.2.0 (Build 15)

    Main Menu

    1:  Adapter Information
    **2:  Adapter Configuration**
    3:  Adapter Updates
    4:  Adapter Diagnostics
    5:  Monitoring
    6:  FabricCache CLI
    7:  Refresh
    8:  Help
    9:  Exit


        Please Enter Selection: 2
----
.. 从适配器配置参数列表中，选择 `HBA Parameters` 选项。
+
[listing]
----
1:  Adapter Alias
    2:  Adapter Port Alias
    **3:  HBA Parameters**
    4:  Persistent Names (udev)
    5:  Boot Devices Configuration
    6:  Virtual Ports (NPIV)
    7:  Target Link Speed (iiDMA)
    8:  Export (Save) Configuration
    9:  Generate Reports
   10:  Personality
   11:  FEC
(p or 0: Previous Menu; m or 98: Main Menu; ex or 99: Quit)
        Please Enter Selection: 3
----
.. 从 HBA 端口列表中，选择所需的 HBA 端口。
+
[listing]
----
Fibre Channel Adapter Configuration

    HBA Model QLE2562 SN: BFD1524C78510
      1: Port   1: WWPN: 21-00-00-24-FF-8D-98-E0 Online
      2: Port   2: WWPN: 21-00-00-24-FF-8D-98-E1 Online
    HBA Model QLE2672 SN: RFE1241G81915
      3: Port   1: WWPN: 21-00-00-0E-1E-09-B7-62 Online
      4: Port   2: WWPN: 21-00-00-0E-1E-09-B7-63 Online


        (p or 0: Previous Menu; m or 98: Main Menu; ex or 99: Quit)
        Please Enter Selection: 1
----
+
此时将显示 HBA 端口的详细信息。

.. 从 HBA Parameters 菜单中，选择 `DisPlay HBA Parameters` 选项以查看 `Execution Throttle` 选项的当前值。
+
`Execution Throttle` 选项的默认值为 65535 。

+
[listing]
----
HBA Parameters Menu

=======================================================
HBA           : 2 Port: 1
SN            : BFD1524C78510
HBA Model     : QLE2562
HBA Desc.     : QLE2562 PCI Express to 8Gb FC Dual Channel
FW Version    : 8.01.02
WWPN          : 21-00-00-24-FF-8D-98-E0
WWNN          : 20-00-00-24-FF-8D-98-E0
Link          : Online
=======================================================

    1:  Display HBA Parameters
    2:  Configure HBA Parameters
    3:  Restore Defaults


        (p or 0: Previous Menu; m or 98: Main Menu; x or 99: Quit)
        Please Enter Selection: 1
--------------------------------------------------------------------------------
HBA Instance 2: QLE2562 Port 1 WWPN 21-00-00-24-FF-8D-98-E0 PortID 03-07-00
Link: Online
--------------------------------------------------------------------------------
Connection Options             : 2 - Loop Preferred, Otherwise Point-to-Point
Data Rate                      : Auto
Frame Size                     : 2048
Hard Loop ID                   : 0
Loop Reset Delay (seconds)     : 5
Enable Host HBA BIOS           : Enabled
Enable Hard Loop ID            : Disabled
Enable FC Tape Support         : Enabled
Operation Mode                 : 0 - Interrupt for every I/O completion
Interrupt Delay Timer (100us)  : 0
**Execution Throttle             : 65535**
Login Retry Count              : 8
Port Down Retry Count          : 30
Enable LIP Full Login          : Enabled
Link Down Timeout (seconds)    : 30
Enable Target Reset            : Enabled
LUNs Per Target                : 128
Out Of Order Frame Assembly    : Disabled
Enable LR Ext. Credits         : Disabled
Enable Fabric Assigned WWN     : N/A

Press <Enter> to continue:
----
.. 按 * 输入 * 继续。
.. 从 HBA Parameters 菜单中，选择 `Configure HBA Parameters` 选项以修改 HBA 参数。
.. 从 Configure Parameters 菜单中，选择 `Execute Throttle` 选项并更新此参数的值。
+
[listing]
----
Configure Parameters Menu

=======================================================
HBA           : 2 Port: 1
SN            : BFD1524C78510
HBA Model     : QLE2562
HBA Desc.     : QLE2562 PCI Express to 8Gb FC Dual Channel
FW Version    : 8.01.02
WWPN          : 21-00-00-24-FF-8D-98-E0
WWNN          : 20-00-00-24-FF-8D-98-E0
Link          : Online
=======================================================

    1:  Connection Options
    2:  Data Rate
    3:  Frame Size
    4:  Enable HBA Hard Loop ID
    5:  Hard Loop ID
    6:  Loop Reset Delay (seconds)
    7:  Enable BIOS
    8:  Enable Fibre Channel Tape Support
    9:  Operation Mode
   10:  Interrupt Delay Timer (100 microseconds)
   11:  Execution Throttle
   12:  Login Retry Count
   13:  Port Down Retry Count
   14:  Enable LIP Full Login
   15:  Link Down Timeout (seconds)
   16:  Enable Target Reset
   17:  LUNs per Target
   18:  Enable Receive Out Of Order Frame
   19:  Enable LR Ext. Credits
   20:  Commit Changes
   21:  Abort Changes


        (p or 0: Previous Menu; m or 98: Main Menu; x or 99: Quit)
        Please Enter Selection: 11
Enter Execution Throttle [1-65535] [65535]: 65500
----
.. 按 * 输入 * 继续。
.. 从 Configure Parameters 菜单中，选择 `Commit Changes` 选项以保存更改。
.. 退出菜单。




link:../system-admin/index.html["系统管理"]
