---
permalink: upgrade/concept_mixed_version_requirements.html 
sidebar: sidebar 
keywords: ontap, upgrade, mixed, version, clusters, mixed-version nodes, requirements 
summary: '混合版本的ONTAP集群由运行两个不同主要ONTAP版本(例如ONTAP 9.8和9.12.1)的节点组成。混合版本ONTAP集群仅在特定情形下受支持。' 
---
= 混合版本ONTAP集群
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
混合版本的ONTAP集群由在有限时间内运行两个不同主要ONTAP版本的节点组成。  例如、如果集群当前包含运行ONTAP 9.8和9.12.1的节点、则该集群为混合版本集群。  同样、节点运行ONTAP 9.9.1和9.13.1的集群也是混合版本集群。  NetApp支持混合版本的ONTAP集群、但时间有限、并且适用于特定场景。

以下是ONTAP集群处于混合版本状态的最常见情形：

* 在大型集群中升级ONTAP软件
* 计划向集群添加新节点时需要进行ONTAP软件升级


支持NetApp平台系统(例如AFF A系列和C系列、ASA和FAS以及C系列系统)的信息 适用场景 ONTAP版本。这些信息不适用于ONTAP云版本(9.x.0)、例如9.12.0。



== 混合版本ONTAP集群的要求

如果您的集群需要进入混合ONTAP版本状态、则需要了解重要的要求和限制。

* 在任何给定时间、一个集群中的主要ONTAP版本不能超过两个。例如、支持ONTAP 9.9.1和9.13.1,但不支持ONTAP 9.9.1、9.12.1和9.13.1.如果集群中的节点运行的是同一ONTAP版本的不同P或D修补程序级别(例如ONTAP 9.9.1P1和9.9.1P5)、则不会视为混合版本ONTAP集群。
* 当集群处于混合版本状态时、您不应输入任何更改集群操作或配置的命令、升级或数据迁移过程所需的命令除外。  例如、在升级和数据迁移完成之前、不应执行LIF迁移、计划内存储故障转移操作或大规模对象创建或删除等活动(但不限于此)。
* 为了获得最佳集群操作、集群处于混合版本状态的时间长度应尽可能短。  集群保持混合版本状态的最长时间取决于集群中最低的ONTAP版本。
+
[cols="2*"]
|===
| 如果混合版本集群中运行的最低ONTAP版本为： | 然后、您最多可以保持混合版本状态 


| ONTAP 9.8或更高版本 | 90天 


| ONTAP 9.7或更低版本 | 7天 
|===
* 从ONTAP 9.8开始、原始节点和新节点之间的版本差异不能大于4。例如、混合版本的ONTAP集群可以包含运行ONTAP 9.8和9.12.1的节点、也可以包含运行ONTAP 9.9.1和9.13.1的节点。但是、不支持包含运行ONTAP 9.8和9.13.1的节点的混合版本ONTAP集群。
+
有关支持的混合版本集群的完整列表、请参见 link:concept_upgrade_paths.html["支持的升级路径"]。混合版本集群支持所有_direct_升级路径。





== 更新大型集群的ONTAP版本

进入混合版本集群状态的一种情形是、升级包含多个节点的集群的ONTAP版本、以利用更高版本的ONTAP 9中提供的功能。如果需要升级大型集群的ONTAP版本、则在升级集群中的每个节点时、您将进入混合版本集群状态一段时间。



== 向ONTAP集群添加新节点

进入混合版本集群状态的另一种情况是向集群添加新节点。您可以向集群添加新节点以扩展其容量、也可以在完全更换控制器的过程中添加新节点。无论哪种情况、都需要将数据从现有控制器迁移到新系统中的新节点。

如果您计划向集群添加新节点、并且这些节点所需的最低ONTAP版本高于集群中当前运行的版本、则在添加新节点之前、您需要对集群中的现有节点执行任何受支持的软件升级。

理想情况下、您应将所有现有节点升级到计划添加到集群的节点所需的最低ONTAP版本。但是、如果由于某些现有节点不支持更高版本的ONTAP而无法做到这一点、则在升级过程中、您需要在有限时间内进入混合版本状态。如果您的节点不支持新控制器所需的最低ONTAP版本、则应执行以下操作：

. link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_methods.html["升级"] 不支持新控制器所需的最低ONTAP版本到其所支持的最高ONTAP版本的节点。
+
例如、如果您的FAS8080运行的是ONTAP 9.5、而您要添加运行ONTAP 9.12.1的新C系列平台、则应将FAS8080升级到ONTAP 9.8 (这是它支持的最大ONTAP版本)。

. https://review.docs.netapp.com/us-en/ontap_pcarriga-ontapdoc1416-9oct/system-admin/add-nodes-cluster-concept.html["将新节点添加到集群中"]。
. link:https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-create-aggregate-move-volumes.html["迁移数据"] 从要从集群中删除的节点到新添加的节点。
. link:https://docs.netapp.com/us-en/ontap/system-admin/remov-nodes-cluster-concept.html["从集群中删除不受支持的节点"^]。
. link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_methods.html["升级"] 将集群中的其余节点升级到与新节点版本相同的版本。
+
(可选)将整个集群(包括新节点)升级到 link:https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU2["最新建议的修补程序版本"] 新节点上运行的ONTAP版本。



有关数据迁移的详细信息、请参见：

* link:https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-create-aggregate-move-volumes.html["创建聚合并将卷移动到新节点"^]
* link:https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_move_linux_iscsi_hosts_from_mcc_fc_to_mcc_ip_nodes.html#setting-up-new-iscsi-connections["为SAN卷移动设置新的iSCSI连接"^]
* link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/encrypt-existing-volume-task.html["移动加密卷"^]

