---
permalink: upgrade/concept_upgrade_paths.html 
sidebar: sidebar 
keywords: ontap, upgrade, paths 
summary: 您可以升级到的 ONTAP 版本因节点上当前运行的 ONTAP 版本而异。 
---
= 我可以升级到哪个版本的 ONTAP ？
:hardbreaks:
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以升级到的 ONTAP 版本因硬件平台和节点上当前运行的 ONTAP 版本而异。请参见 https://hwu.netapp.com["NetApp Hardware Universe"^] 验证目标升级版本是否支持您的平台。

* 注意： * 这些准则仅指内部部署的 ONTAP 版本。有关在云中升级 ONTAP 的信息，请参见 https://docs.netapp.com/us-en/occm/task_updating_ontap_cloud.html["升级 Cloud Volumes ONTAP 软件"^]。

要确定当前的 ONTAP 版本，请执行以下操作：

* 在 System Manager 中，单击 * 集群 > 概述 * 。
* 在命令行界面（ CLI ）中，使用 `cluster image show` 命令。+ 您还可以在高级权限级别使用 `ssystem node image show` 命令来显示详细信息。


建议尽可能使用自动化无中断升级（ ANDU ）。根据当前版本和目标版本，您的升级路径将为 _directs_ ， _direct multi-hop_ 或 _multi-stagent_ 。除非另有说明，否则这些路径适用于所有 link:concept_upgrade_methods.html["升级方法"]；无中断或中断，自动或手动。

* _directly_ + 您始终可以使用一个软件映像直接升级到相邻的 ONTAP 版本系列。对于大多数版本，您还可以安装一个软件映像，以便直接升级到比正在运行的版本高两个版本的版本。例如，您可以使用直接更新路径从 9.8 到 9.9.1 或从 9.8 到 9.10.1 。
* _direct multi-hop_ + 对于某些自动无中断升级（ ANDU ）到非相邻版本，您可以安装中间版本和目标版本的软件映像。自动升级过程使用后台的中间映像完成目标版本的更新。在此过程中，您应该会执行多个接管 / 交还操作以及相关的重新启动。+ 此更新路径仅适用于 9.3 到 9.6 或 9.7 以及 9.5 到 9.8 或 9.1.1 之间的 andu 更新。例如，如果集群运行的是 9.3 ，而您要升级到 9.7 ，则应加载 9.5 和 9.7 的 ONTAP 安装包，然后启动 andu 到 9.7 。然后， ONTAP 会先自动将集群升级到 9.5 ，然后再自动升级到 9.7 。
* _Multi-stag容量 _ + 如果您的非相邻目标版本没有直接或直接多跃点路径，则必须先升级到受支持的中间版本，然后再升级到目标版本。例如，如果您当前运行的是 9.7 ，并且要升级到 9.10.1 ，则必须完成多阶段升级：首先从 9.7 升级到 9.9.1 ，然后从 9.9.1 升级到 9.10.1 。从早期版本升级可能需要三个或更多阶段，并需要进行多个中间升级。+ * 注意： * 开始多阶段升级之前，请确保您的硬件平台支持您的目标版本。


如果您计划从较旧的 ONTAP 版本（例如 9.3 ）进行 ONTAP 升级，则最佳做法是先升级到同一 ONTAP 版本系列中的最新修补程序版本，然后再升级到下一个受支持的主要版本。这样可以确保在升级之前解决旧版本中的所有问题。

例如，如果您的系统运行的是 ONTAP 9.3P9 ，并且您计划升级到 9.9.1 ，请在所有主要 ONTAP 版本中遵循以下升级路径： 9.3P9 -> 9.3P21 -> 9.7 -> 9.9.1 ，请使用最新可用的修补程序版本。



== ONTAP 9 版本系列中的升级路径

下表列出了所有支持的升级路径。除某些需要中断升级的系统配置外，所有路径均可使用自动和手动无中断升级方法，如表中所述。某些早期版本的升级映像不再可用。

[cols="3*"]
|===
| 如果您的当前 ONTAP 版本为… | 您的目标 ONTAP 版本为… | 您的升级路径为… 


| 9.9.1 | 9.10.1 | 直接 


.2+| 9.8 | 9.10.1 | 直接 


| 9.9.1 | 直接 


.3+| 9.7 | 9.10.1 | 直接多跃点（仅限 ANDU ，对于 9.8 和 9.10.1P2 或更高版本，需要映像） + 其他多阶段（通过 9.9.1 ） 


| 9.9.1 | 直接 


| 9.8 | 直接 


.4+| 9.6 | 9.10.1 | 多阶段（通过 9.8 ） 


| 9.9.1 | 多阶段（通过 9.8 ） 


| 9.8 | 直接 


| 9.7 | 直接 


.5+| 9.5 | 9.10.1 | 多阶段（通过 9.8 ） 


| 9.9.1 | 直接多跃点（仅限 ANDU ，需要 9.7 和 9.1.1 的映像） + 其他多阶段（通过 9.7 ） 


| 9.8 | 直接多跃点（仅限 ANDU ，需要 9.7 和 9.8 的映像） + 其他多阶段（通过 9.7 ） 


| 9.7 | 直接 


| 9.6 | 直接 


.6+| 9.4 | 9.10.1 | 多阶段（通过 9.5 和 9.8 ） 


| 9.9.1 | 多阶段（通过 9.5 和 9.8 ） 


| 9.8 | 多阶段（通过 9.5 ） 


| 9.7 | 多阶段（通过 9.5 ） 


| 9.6 | 多阶段（通过 9.5 ） 


| 9.5 | 直接 


.7+| 9.3 | 9.10.1 | 多阶段（通过 9.7 和 9.1.1 ） 


| 9.9.1 | 多阶段（通过 9.8 ） 


| 9.8 | 多阶段（通过 9.7 ） 


| 9.7 | 直接多跃点（仅限 ANDU ，需要 9.5 和 9.7 的映像） + 其他多阶段（通过 9.5 ） 


| 9.6 | 直接多跃点，仅限 ANDU （ 9.5 和 9.6 需要映像） + 其他多阶段（通过 9.5 ） 


| 9.5 | 直接 


| 9.4 | 不可用 


.8+| 9.2 | 9.10.1 | 多阶段（通过 9.3 ， 9.7 和 9.1.1 ） 


| 9.9.1 | 多阶段（通过 9.3 和 9.7 ） 


| 9.8 | 多阶段（通过 9.7 ） 


| 9.7 | 多阶段（通过 9.3 ） 


| 9.6 | 多阶段（通过 9.3 ） 


| 9.5 | 多阶段（通过 9.3 ） 


| 9.4 | 不可用 


| 9.3 | 直接 


.9+| 9.1 | 9.10.1 | 多阶段（通过 9.3 ， 9.7 和 9.1.1 ） 


| 9.9.1 | 多阶段（通过 9.3 和 9.7 ） 


| 9.8 | 多阶段（通过 9.3 和 9.7 ） 


| 9.7 | 多阶段（通过 9.3 ） 


| 9.6 | 多阶段（通过 9.3 ） 


| 9.5 | 多阶段（通过 9.3 ） 


| 9.4 | 不可用 


| 9.3 | 直接 


| 9.2 | 不可用 


.10+| 9.0 | 9.10.1 | 多阶段（通过 9.1 ， 9.3 ， 9.7 和 9.9.1 ） 


| 9.9.1 | 多阶段（通过 9.1 ， 9.3 和 9.7 ） 


| 9.8 | 多阶段（通过 9.1 ， 9.3 和 9.7 ） 


| 9.7 | 多阶段（通过 9.1 和 9.3 ） 


| 9.6 | 多阶段（通过 9.1 和 9.3 ） 


| 9.5 | 多阶段（通过 9.1 和 9.3 ） 


| 9.4 | 不可用 


| 9.3 | 多阶段（通过 9.1 ） 


| 9.2 | 不可用 


| 9.1 | 直接 
|===


== 从 Data ONTAP 8.* 版本升级到 ONTAP 9 版本的路径

请务必使用 See NetApp Hardware Universe 验证您的平台是否可以运行目标 ONTAP 版本。

* 注： * 《 Data ONTAP 8.3 升级指南》错误地指出，在四节点集群中，您应计划最后升级持有 epsilon 的节点。从 Data ONTAP 8.2.3 开始，升级不再需要此功能。有关详细信息，请参见 https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/805277["NetApp Bug Online 中的错误 ID 805277"^]。

从 Data ONTAP 8.3.x 开始:: 您可以直接升级到 ONTAP 9.1 ，然后按照中所述升级到更高版本 <<ontap9_paths>>。
从 8.3.x 之前的 Data ONTAP 版本开始，包括 8.2.x:: 您必须先升级到 Data ONTAP 8.3.x ，然后升级到 ONTAP 9.1 ，再按照中所述升级到更高版本 <<ontap9_paths>>。

