---
permalink: upgrade/concept_upgrade_paths.html 
sidebar: sidebar 
keywords: ontap, upgrade, paths 
summary: 您可以升级到的 ONTAP 版本因节点上当前运行的 ONTAP 版本而异。 
---
= 我可以升级到哪个版本的 ONTAP ？
:hardbreaks:
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以升级到的 ONTAP 版本因硬件平台和节点上当前运行的 ONTAP 版本而异。请参见 https://hwu.netapp.com["NetApp Hardware Universe"^] 验证您的平台是否支持升级。

要确定当前的 ONTAP 版本，请执行以下操作：

* 在 System Manager 中，单击 * 集群 > 概述 * 。
* 在命令行界面（ CLI ）中，使用 `ssystem image show` 命令。


如果您计划从较旧的 ONTAP 版本（例如 9.3 ）进行 ONTAP 升级，则最佳做法是先升级到同一 ONTAP 版本系列中的最新修补程序版本，然后再升级到下一个受支持的主要版本。这样可以确保在升级之前解决旧版本中的所有问题。

例如，如果您的系统运行的是 ONTAP 9.3P9 ，并且您计划升级到 9.9.1 ，请在所有主要 ONTAP 版本中遵循以下升级路径： 9.3P9 -> 9.3P21 -> 9.7 -> 9.9.1 ，请使用最新可用的修补程序版本。

[cols="2*"]
|===
| 您可以从以下位置升级 ... | 至 ... 


 a| 
ONTAP 9.10.0
 a| 
ONTAP 9.10.1



 a| 
ONTAP 9.9.1
 a| 
ONTAP 9.10.0 或 9.10.1



 a| 
ONTAP 9.9.0
 a| 
ONTAP 9.9.1



 a| 
ONTAP 9.8
 a| 
ONTAP 9.0.0 ， 9.9.1 或 9.10.1



 a| 
ONTAP 9.7
 a| 
ONTAP 9.8 或 9.9.1



 a| 
ONTAP 9.6
 a| 
ONTAP 9.7 或 9.8



 a| 
ONTAP 9.5
 a| 
ONTAP 9.6 ， 9.7 或 9.9.1

* 注： * 如果要从 ONTAP 9.5 直接升级到 9.1.1 ，则必须同时下载 ONTAP 9.7 和 9.1.1 的软件映像。自动升级过程会使用后台 9.7 映像完成到 9.1.1 的更新。在此过程中，您应该会多次重新启动。



 a| 
ONTAP 9.4
 a| 
ONTAP 9.5



 a| 
ONTAP 9.3
 a| 
ONTAP 9.4 ， 9.5 或 9.7

* 注： * 如果要从 ONTAP 9.3 直接升级到 9.7 ，则必须下载 ONTAP 9.5 和 9.7 的软件映像。自动升级过程会在后台使用 9.5 映像完成 9.7 的更新。在此过程中，您应该会多次重新启动。



 a| 
ONTAP 9.2
 a| 
ONTAP 9.3



 a| 
ONTAP 9.1
 a| 
ONTAP 9.2 或 9.3



 a| 
ONTAP 9.
 a| 
ONTAP 9.1



 a| 
Data ONTAP 8.3.x
 a| 
ONTAP 9 或 9.1



 a| 
Data ONTAP 8.2.x 或更早版本

* 注意： * 如果您运行的版本低于 Data ONTAP 8.3.x ，则无法直接升级到 ONTAP 9 或 9.1 。您必须先升级到 Data ONTAP 8.3.x ，然后再升级到 ONTAP 9 或 9.1 。
 a| 
Data ONTAP 8.3.x

|===