---
permalink: upgrade/concept_upgrade_requirements_for_snapmirror.html 
sidebar: sidebar 
keywords: ontap, upgrade, requirements, snapmirror 
summary: 要成功升级运行 SnapMirror 的集群，您必须执行某些任务。 
---
= SnapMirror 的升级要求
:icons: font
:imagesdir: ../media/


[role="lead"]
要成功升级运行 SnapMirror 的集群，您必须执行某些任务。

* 如果要升级具有 DP SnapMirror 关系的集群，则必须先升级目标集群 / 节点，然后再升级源集群 / 节点。
* 在升级运行 SnapMirror 的集群之前，必须为包含目标卷的每个节点暂停 SnapMirror 操作，并且每个对等 SVM 在集群中必须具有唯一的名称。
+
要防止 SnapMirror 传输失败，您必须暂停 SnapMirror 操作，在某些情况下，在升级源节点之前升级目标节点。下表介绍了暂停 SnapMirror 操作的两个选项。

+
[cols="3*"]
|===
| 选项 | Description | 是否先升级目标节点，再升级源节点？ 


 a| 
在 NDU 期间暂停 SnapMirror 操作（无中断升级）。
 a| 
在 SnapMirror 环境中，最简单的升级方法是暂停所有 SnapMirror 操作，执行升级，然后恢复 SnapMirror 操作。但是，在整个 NDU 期间不会发生任何 SnapMirror 传输。如果集群中的节点彼此镜像卷，则必须使用此方法。
 a| 
不可以，可以按任意顺序升级节点。



 a| 
一次暂停一个目标卷的 SnapMirror 操作。
 a| 
您可以暂停特定目标卷的 SnapMirror 传输，升级包含目标卷的节点（或 HA 对），升级包含源卷的节点（或 HA 对），然后恢复目标卷的 SnapMirror 传输。通过使用此方法，可以在升级包含原始目标卷和源卷的节点时继续所有其他目标卷的 SnapMirror 传输。
 a| 
是的。

|===


SVM 对等要求 SVM 名称在集群之间是唯一的。最佳做法是，使用唯一的完全限定域名（ FQDN ）来命名 SVM ，例如， `dataVerser.HQ` 或 `mirrorVserver.Offsite` 。使用 FQDN 命名模式可以更轻松地确保唯一性。

link:../concepts/index.html["ONTAP 概念"]
