---
permalink: upgrade/create-upgrade-plan.html 
sidebar: sidebar 
keywords: ontap, upgrade, plan, planning, upgrade advisor, advisor, digital advisor, active iq, create an upgrade plan, estimate upgrade, 
summary: Digital Advisor中的Upgrade Advisor服务提供智能信息、可帮助您规划升级并最大限度地降低不确定性和风险。 
---
= 使用Upgrade Advisor准备ONTAP升级
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您拥有的有效link:https://www.netapp.com/us/services/support-edge.aspx["SupportEdge 服务"^]合同link:https://docs.netapp.com/us-en/active-iq/upgrade_advisor_overview.html["Digital Advisor"^]，建议您使用Upgrade Advisor生成升级计划。

Digital Advisor中的Upgrade Advisor服务提供智能信息、可帮助您规划升级并最大限度地降低不确定性和风险。

Digital Advisor可确定您的环境中可以通过升级到较新版本的ONTAP来解决的问题。Upgrade Advisor 服务可帮助您规划成功升级，并提供有关要升级到的 ONTAP 版本中可能需要注意的问题的报告。


NOTE: Upgrade Advisor需要AutoSupport日志才能创建报告。如果您启用了AutoSupport、则升级顾问可以访问日志并成功创建报告。如果尚未启用AutoSupport，则可以 https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_manually_upload_AutoSupport_messages_to_NetApp_in_ONTAP_9["手动上传AutoSupport文件"^]。

如果您没有有效的Digital Advisor Support Edge服务合同，则应link:prepare.html["在不使用Upgrade Advisor的情况下准备升级"]。

.步骤
. https://aiq.netapp.com/["启动Active IQ数字顾问"^]
. 在Digital Advisor中link:https://docs.netapp.com/us-en/active-iq/task_view_risk_and_take_action.html["查看与集群相关的任何风险并手动采取更正操作"^]。
+
在执行ONTAP升级之前，需要解决“*软件配置更改*”、“*硬件配置更改*”和“硬件更换*”类别中包含的风险。

. 查看建议的升级路径和 link:https://docs.netapp.com/us-en/active-iq/upgrade_advisor_overview.html["生成升级计划"^]。


.下一步行动
* 您应查看 link:../release-notes/index.html["《 ONTAP 发行说明》"] 对于Upgrade Advisor为您的集群建议的目标ONTAP版本、您应按照Upgrade Advisor生成的计划升级集群。
* 您应该 link:reboot-sp-bmc.html["重新启动SP或BMC"] 升级开始之前。

