---
permalink: upgrade/index.html 
sidebar: sidebar 
keywords: upgrade overview, upgrade, digital advisor, summary, upgrade ontap, upgrading ontap, upgrade, upgrading, ontap, software, on-premise, prepare, preparation, major upgrade, minor upgrade, patch upgrade, upgrade assistance, upgrade help, upgrade technical support 
summary: 通过ONTAP升级、您可以利用新增功能和增强功能。开始升级前、请按照建议的步骤进行准备。 
---
= 了解ONTAP升级
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
升级ONTAP软件时、您可以利用新增的和增强的ONTAP功能、帮助您降低成本、加快关键工作负载的处理速度、提高安全性并扩大企业可用的数据保护范围。

主要的 ONTAP 升级包括从较低的 ONTAP 编号版本转移到较高的 ONTAP 编号版本。例如，将集群从 ONTAP 9.14.1 升级到 ONTAP 9.18.1。次要（或修补程序）升级包括从同一编号版本中的较低 ONTAP 版本转移到较高 ONTAP 版本。例如，将集群从 ONTAP 9.17.1P1 升级到 9.17.1P4。

要开始使用，您可以使用以下方法之一为升级做准备。

* Upgrade Advisor
+
如果您有 Active IQ Digital Advisor（也称为 Digital Advisor）的有效 SupportEdge 合同，您应该link:create-upgrade-plan.html["准备使用Upgrade Advisor进行升级"]。Upgrade Advisor 提供智能，通过评估群集并创建特定于配置的升级计划，帮助您最大限度地减少不确定性和风险。

+
Upgrade Advisor 适用于环境较小的用户，他们更喜欢基于云的、以 UI 为中心的体验。

+
详细了解link:https://docs.netapp.com/us-en/active-iq/upgrade_advisor_overview.html["Upgrade Advisor"^]。

* 升级运行状况检查器
+
您还可以 link:create-upgrade-plan.html["准备使用 Upgrade Health Checker 进行升级"]。Upgrade Health Checker 是一种升级咨询服务工具，可执行现场全面的运行状况检查，以识别升级阻止程序和警告。使用 Upgrade Health Checker 无需 SupportEdge 合约。

+
Upgrade Health Checker 适用于环境庞大或复杂、对互联网的访问受限或现有自动化和协调框架的用户。

+
详细了解link:https://docs.netapp.com/us-en/upgrade-health-checker/learn-about-upgrade-health-checker.html["升级运行状况检查器"^]。

* 手动准备
+
如果不使用 Upgrade Advisor 或 Upgrade Health Checker 工具，则需要link:prepare.html["准备手动升级"]。手动准备需要完成多个任务，以检查是否存在任何已知问题或障碍，并确保您的集群满足升级的必要要求。

+
详细了解link:prepare.html["手动升级准备"^]。



准备升级后，建议您使用执行升级link:task_upgrade_andu_sm.html["从System Manager自动无中断升级(ANDU)"]。ANDU可利用ONTAP的高可用性(HA)故障转移技术、确保集群在升级期间继续提供数据而不会中断。


NOTE: 从ONTAP 9.12.1 开始，系统管理器与NetApp控制台完全集成。如果您的系统上配置了控制台，您可以通过系统页面进行升级。

如果您需要有关升级ONTAP软件的帮助、NetApp专业服务提供了 link:https://www.netapp.com/pdf.html?item=/media/8144-sd-managed-upgrade-service.pdf["托管升级服务"^]。如果您有兴趣使用此服务、请联系您的NetApp销售代表或 link:https://www.netapp.com/forms/sales-contact/["提交NetApp的销售咨询表"^]。客户可以使用托管升级服务以及其他类型的升级支持 link:https://www.netapp.com/pdf.html?item=/media/8845-supportedge-expert-service.pdf["SupportEdge Expert服务"^] 无需额外费用。

.相关信息
* link:concept_upgrade_paths.html["支持的升级路径"]

