---
permalink: upgrade/remove-ems-lif-service-task.html 
sidebar: sidebar 
keywords: ontap, upgrade, after, post, ems, event, management, system, lifs, messages, not, delivered 
summary: 从 ONTAP 9.7 或更早版本升级到 9.8 或更高版本后，如果您使用 EMS，则可能需要从某些网络服务策略中删除 EMS LIF 服务。 
---
= 升级ONTAP后、从网络服务策略中删除EMS LIF服务
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您在从 ONTAP 9.7 或更早版本升级到 ONTAP 9.8 或更高版本之前设置了事件管理系统 (EMS) 消息，则升级后您的 EMS 消息可能无法传递。

在升级过程中，  `management-ems` （即 EMS LIF 服务）已添加到管理和系统 SVM 中所有现有的服务策略。这样，就可以从与服务策略关联的任何 LIF 发送 EMS 消息。如果选定LIF无法访问事件通知目标、则不会传送消息。

为防止这种情况，升级后您应该从不提供目标可达性的网络服务策略中删除 EMS LIF 服务。

link:../networking/lifs_and_service_policies96.html#service-policies-for-system-svms["了解有关 ONTAP LIF 和服务策略的更多信息"](英文)

.步骤
. 确定可通过其发送 EMS 消息的 LIF 和关联的网络服务策略：
+
[source, cli]
----
network interface show -fields service-policy -services management-ems
----
+
[listing]
----
vserver        lif            service-policy
-------------- ------------   ------------------
cluster-1      cluster_mgmt   default-management
cluster-1      node1-mgmt     default-management
cluster-1      node2-mgmt     default-management
cluster-1      inter_cluster  default-intercluster
4 entries were displayed.
----
. 检查每个LIF是否与EMS目标连接：
+
[source, cli]
----
network ping -lif <lif_name> -vserver <svm_name> -destination <destination_address>
----
+
在每个节点上执行此操作。

+
.示例
[listing]
----
cluster-1::> network ping -lif node1-mgmt -vserver cluster-1 -destination 10.10.10.10
10.10.10.10 is alive

cluster-1::> network ping -lif inter_cluster -vserver cluster-1 -destination 10.10.10.10
no answer from 10.10.10.10
----
. 输入高级权限级别：
+
[source, cli]
----
set advanced
----
. 对于不具有可达性的 LIF，删除 `management-ems`相应服务策略中的 LIF 服务：
+
[source, cli]
----
network interface service-policy remove-service -vserver <svm_name> -policy <service_policy_name> -service management-ems
----
+
有关的详细信息 `network interface service-policy remove-service`，请参见link:https://docs.netapp.com/us-en/ontap-cli/network-interface-service-policy-remove-service.html["ONTAP 命令参考"^]。

. 验证management-EMS LIF现在仅与可访问EMS目标的LIF关联：
+
[source, cli]
----
network interface show -fields service-policy -services management-ems
----

