---
permalink: upgrade/task_preparing_snapmirror_relationships_for_a_nondisruptive_upgrade_or_downgrade.html 
sidebar: sidebar 
keywords: ontap, upgrade, snapmirror, operations, quisce 
summary: 建议在执行无中断 ONTAP 升级之前暂停 SnapMirror 操作。 
---
= 准备 SnapMirror 关系以实现无中断升级
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
建议在执行无中断 ONTAP 升级之前暂停 SnapMirror 操作。

. 使用 snapmirror show 命令确定每个 SnapMirror 关系的目标路径。
. 对于每个目标卷，暂停未来的 SnapMirror 传输： `snapmirror quiesce -destination-path destination`
+
如果 SnapMirror 关系没有活动传输，则此命令会将其状态设置为已暂停。如果此关系具有活动传输，则状态将设置为 " 正在暂停 " ，直到传输完成，然后状态将变为 " 已暂停 " 。

+
此示例将从 SVMvs0.example.com 暂停涉及目标卷 vol1 的传输：

+
[listing]
----
cluster1::> snapmirror quiesce -destination-path vs0.example.com:vol1
----
. 验证所有 SnapMirror 关系是否已暂停： `snapmirror show -status ！ quiesced`
+
此命令将显示已暂停的任何 SnapMirror 关系。

+
此示例显示所有 SnapMirror 关系均已暂停：

+
[listing]
----
cluster1::> snapmirror show -status !Quiesced
There are no entries matching your query.
----
. 如果当前正在传输任何 SnapMirror 关系，请执行以下选项之一：
+
[cols="2*"]
|===
| 选项 | Description 


 a| 
等待传输完成，然后再执行 ONTAP 升级。
 a| 
每次传输完成后，此关系将更改为已暂停状态。



 a| 
停止传输： `snapmirror abort -destination-path destination -h` * 注： * 如果要中止负载共享镜像传输，必须使用 -foreground true 参数。
 a| 
此命令将停止 SnapMirror 传输并将目标卷还原到已成功传输的最后一个 Snapshot 副本。此关系将设置为已暂停状态。

|===


.相关信息
xref:concept_upgrade_requirements_for_snapmirror.adoc[SnapMirror 的升级要求]
