---
sidebar: sidebar 
permalink: upgrade/task_upgrade_andu_cli.html 
keywords: netapp, ontap, automate, automatic, automated, upgrade, nondisruptive, nondisruptively, non-disruptive update, nondisruptive upgrade, upgrade a cluster, shift workload between clusters, hardware platform, configuration, software image, update, update ONTAP, update software, ndu 
summary: 您可以无中断地更新集群上的 ONTAP 版本。 
---
= 使用命令行界面自动进行无中断 ONTAP 升级
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
对于自动升级、ONTAP会自动在每个节点上安装目标ONTAP映像、并验证集群组件以确保集群可以无中断升级、然后执行 xref:concept_upgrade_methods.html[批量升级或滚动升级] 根据节点数量在后台运行。

您可以使用命令行界面（ CLI ）验证集群是否可以无中断升级，在每个节点上安装目标 ONTAP 映像，然后在后台执行升级。


NOTE: 如果您不打算监控升级过程的进度，则最好这样做 link:task_requesting_notification_of_issues_encountered_in_nondisruptive_upgrades.html["请求可能需要手动干预的错误的 EMS 通知"]。

.开始之前
* 您应该 link:prepare.html["准备升级"]。
* 您应该 link:download-software-image.html["下载ONTAP软件映像"] 目标ONTAP版本。
* 对于每个 HA 对，每个节点应在同一广播域上具有一个或多个端口。
+
如果您有8个或更多节点、则会在自动无中断升级中使用批量升级方法。  在 ONTAP 9.7 及更早版本中，如果使用批处理方法，则 LIF 会迁移到要升级的节点的 HA 配对节点。  如果配对节点在同一广播域中没有任何端口，则 LIF 迁移将失败。

+
在ONTAP 9.8及更高版本中、如果使用批处理方法、则LIF会迁移到另一个批处理组。

* 如果您要执行 link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html#types-of-upgrade-paths["直接多跳升级"]、您必须已获取特定所需的两个正确ONTAP 映像 link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html#supported-upgrade-paths["升级路径"]。
* 如果要升级MetroCluster FC配置中的ONTAP、则应启用集群以自动执行计划外切换。



NOTE: 修改的设置 `storage failover modify-auto-giveback` 自动无中断升级(andu)开始之前的命令选项不会对升级过程产生任何影响。在更新所需的接管 / 交还期间， andu 进程会忽略此选项的任何预设值。例如、设置 `-autogiveback` 在开始andu之前设置为false不会中断交还前的自动升级。



== 第1步：将目标ONTAP软件映像加载到集群软件包存储库中

要开始ONTAP软件升级过程、您必须在集群软件包存储库中提供目标ONTAP软件映像。

.步骤
. 删除先前的 ONTAP 软件包：
+
[source, cli]
----
cluster image package delete -version previous_ONTAP_Version
----
. 将目标ONTAP软件映像加载到集群软件包存储库：
+
[source, cli]
----
cluster image package get -url location
----
+
[listing]
----
cluster1::> cluster image package get -url http://www.example.com/software/9.13.1/image.tgz

Package download completed.
Package processing completed.
----
+
如果您要执行 link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html#types-of-upgrade-paths["直接多跳升级"]，您还需要加载升级所需的ONTAP中间版本的软件包。例如、如果要从9.8升级到9.13.1、则需要加载适用于ONTAP 9.12.1的软件包、然后使用同一命令加载适用于9.13.1.的软件包。

. 验证集群软件包存储库中是否存在软件包：
+
[source, cli]
----
cluster image package show-repository
----
+
[listing]
----
cluster1::> cluster image package show-repository
Package Version  Package Build Time
---------------- ------------------
9.13.1              MM/DD/YYYY 10:32:15
----




== 第2步：执行自动升级前检查

(可选)在自动升级ONTAP软件之前、您可以使用 `cluster image validate` 命令以验证集群是否可以成功升级。  。 `cluster image validate` 命令会对集群组件运行一系列检查、然后提供一系列已执行的特定验证以及在继续升级之前需要采取的任何更正操作。

. 执行自动升级前检查：
+
[source, cli]
----
cluster image validate -version package_version_number
----
+
** 如果您要执行 link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html#types-of-upgrade-paths["直接多跳升级"]，使用目标ONTAP软件包进行验证。  您无需单独验证中间升级映像。  例如、如果要从9.8升级到9.13.1、则应使用9.13.1软件包进行验证。您不需要单独验证9.12.1软件包。
** 如果要升级双节点或四节点 MetroCluster 配置，则必须在两个集群上运行此命令，然后才能继续。
+
[listing]
----
cluster1::> cluster image validate -version 9.13.1

WARNING: There are additional manual upgrade validation checks that must be performed after these automated validation checks have completed...
----


. 监控验证进度：
+
[source, cli]
----
cluster image show-update-progress
----
. 完成验证确定的所有必需操作。




== 第3步：升级ONTAP软件

. 生成软件升级估计值：
+
[source, cli]
----
cluster image update -version package_version_number -estimate-only
----
+
软件升级估计值可显示有关要更新的每个组件的详细信息以及估计的升级持续时间。

. 执行软件升级：
+
[source, cli]
----
cluster image update -version package_version_number
----
+
** 如果您要执行 link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html#types-of-upgrade-paths["直接多跳升级"]，请使用packue_version_number的目标ONTAP版本。例如、如果要从ONTAP 9.8升级到9.13.1、请使用9.13.1作为packing_version_number。
** 如果集群包含 2 到 6 个节点，则会执行滚动升级。如果集群包含 8 个或更多节点，则默认情况下会执行批量升级。如果需要、您可以使用 `-force-rolling` 参数以指定滚动升级。
** 完成每次接管和交还后，升级将等待 8 分钟，以使客户端应用程序能够从接管和交还期间发生的 I/O 暂停中恢复。如果您的环境需要更多或更少的时间来实现客户端稳定、则可以使用 `-stabilize-minutes` 用于指定不同稳定时间量的参数。
** 对于除双节点 MetroCluster 系统之外的任何 MetroCluster 配置，在用户启动并在命令行上提供确认之后， ONTAP 升级过程会在两个站点（本地站点和灾难恢复站点）的 HA 对上同时启动。对于双节点 MetroCluster 系统，首先在灾难恢复站点（即未启动升级的站点）上启动更新。在灾难恢复站点上完成更新后，升级将在本地站点上开始。
+
[listing]
----
cluster1::> cluster image update -version 9.13.1

Starting validation for this update. Please wait..

It can take several minutes to complete validation...

WARNING: There are additional manual upgrade validation checks...

Pre-update Check      Status     Error-Action
--------------------- ---------- --------------------------------------------
...
20 entries were displayed

Would you like to proceed with update ? {y|n}: y
Starting update...

cluster-1::>
----


. 显示集群更新进度：
+
[source, cli]
----
cluster image show-update-progress
----
+
如果要升级4节点或8节点MetroCluster配置、请 `cluster image show-update-progress` command仅显示运行命令的节点的进度。您必须在每个节点上运行命令才能查看各个节点的进度。

. 验证是否已在每个节点上成功完成升级。
+
[source, cli]
----
cluster image show-update-progress
----
+
[listing]
----
cluster1::> cluster image show-update-progress

                                             Estimated         Elapsed
Update Phase         Status                   Duration        Duration
-------------------- ----------------- --------------- ---------------
Pre-update checks    completed                00:10:00        00:02:07
Data ONTAP updates   completed                01:31:00        01:39:00
Post-update checks   completed                00:10:00        00:02:00
3 entries were displayed.

Updated nodes: node0, node1.
----
. 触发 AutoSupport 通知：
+
[source, cli]
----
autosupport invoke -node * -type all -message "Finishing_NDU"
----
+
如果集群未配置为发送 AutoSupport 消息，则通知的副本将保存在本地。

. 验证集群是否已启用自动计划外切换：
+

NOTE: 此步骤仅适用于MetroCluster FC配置。  如果您使用的是MetroCluster IP配置、则无需执行此步骤。

+
.. 检查是否已启用自动计划外切换：
+
[source, cli]
----
metrocluster show
----
+
如果启用了自动计划外切换，则命令输出中将显示以下语句：

+
....
AUSO Failure Domain    auso-on-cluster-disaster
....
.. 如果输出中未显示该语句，请启用自动计划外切换：
+
[source, cli]
----
metrocluster modify -auto-switchover-failure-domain auso-on-cluster-disaster -overide-vetoes true
----
+

NOTE: 在自动无中断升级完成之前、您无法执行切回操作。

.. 验证是否已启用自动计划外切换：
+
[source, cli]
----
metrocluster show
----




.相关信息
* https://aiq.netapp.com/["启动 Active IQ"]
* https://docs.netapp.com/us-en/active-iq/["Active IQ 文档"]

