---
sidebar: sidebar 
permalink: upgrade/task_upgrade_andu_cli.html 
keywords: netapp, ontap, automate, automatic, automated, upgrade, nondisruptive, nondisruptively, non-disruptive update, nondisruptive upgrade, upgrade a cluster, shift workload between clusters, hardware platform, configuration, software image, update, update ONTAP, update software, ndu 
summary: 您可以无中断地更新集群上的 ONTAP 版本。 
---
= 使用命令行界面自动进行无中断 ONTAP 升级
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
您可以使用命令行界面（ CLI ）验证集群是否可以无中断升级，在每个节点上安装目标 ONTAP 映像，然后在后台执行升级。

升级后，您应验证集群版本，集群运行状况和存储运行状况。


NOTE: 如果您使用的是 MetroCluster FC 配置，则还需要验证集群是否已启用自动计划外切换。

如果您不打算监控升级过程的进度，则最好这样做 link:task_requesting_notification_of_issues_encountered_in_nondisruptive_upgrades.html["请求可能需要手动干预的错误的 EMS 通知"]。

.开始之前
* 您应启动 Active IQ 数字顾问。
+
Active IQ 数字顾问的 Upgrade Advisor 组件可帮助您规划成功的升级。

+
Active IQ 数字顾问会向所有与 * SupportEdge * 签有有效合同的 NetApp 客户提供数据驱动型洞察和建议（功能因产品和支持层而异）。

* 您必须满足升级准备要求。
* 对于每个 HA 对，每个节点应在同一广播域上具有一个或多个端口。
+
如果您有8个或更多节点、则会在自动无中断升级中使用批量升级方法。在 ONTAP 9.7 及更早版本中，如果使用批处理方法，则 LIF 会迁移到要升级的节点的 HA 配对节点。如果配对节点在同一广播域中没有任何端口，则 LIF 迁移将失败。

+
在ONTAP 9.8及更高版本中、如果使用批处理方法、则LIF会迁移到另一个批处理组。

* 如果您要执行 link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html#types-of-upgrade-paths["直接多跳升级"]、您必须已获取特定所需的两个正确ONTAP 映像 link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html#supported-upgrade-paths["升级路径"]。


.关于此任务
`cluster image validate` 命令会检查集群组件，以验证升级是否可以无中断地完成，然后提供每个检查的状态以及执行软件升级之前必须执行的任何必要操作。


NOTE: 在自动无中断升级（ ANDU ）开始之前修改 `storage failover modify-auto-giveback` 命令选项的设置不会影响升级过程。在更新所需的接管 / 交还期间， andu 进程会忽略此选项的任何预设值。例如，在开始 andu 之前将 ` -autogiveback` 设置为 false 不会中断交还前的自动升级。

. 删除先前的 ONTAP 软件包：
+
`cluster image package delete -version previous _ontap_Version`

. 下载目标 ONTAP 软件包：
+
`集群映像包 get -url location`

+

NOTE: 如果要从 ONTAP 9.3 升级到 9.7 ，请下载 ONTAP 9.5 的软件包，然后使用同一命令下载 9.7 的软件包。如果要从 ONTAP 9.5 升级到 9.1.1 ，请下载 ONTAP 9.7 的软件包，然后使用同一命令下载 9.1.1 的软件包。

+
[listing]
----
cluster1::> cluster image package get -url http://www.example.com/software/9.7/image.tgz

Package download completed.
Package processing completed.
----
. 验证集群软件包存储库中是否存在软件包：
+
`集群映像包 show-repository`

+
[listing]
----
cluster1::> cluster image package show-repository
Package Version  Package Build Time
---------------- ------------------
9.7              MM/DD/YYYY 10:32:15
----
. 验证集群是否已做好无中断升级的准备：
+
`cluster image validate -version package_version_number`

+
** 如果要升级双节点或四节点 MetroCluster 配置，则必须在两个集群上运行此命令，然后才能继续。
** 如果要从 ONTAP 9.3 升级到 9.7 ，请使用 9.7 软件包进行验证。您无需单独验证 9.5 软件包。
** 如果要从 ONTAP 9.5 升级到 9.9.1 ，请使用 9.9.1 软件包进行验证。您无需单独验证 9.7 软件包。


+
[listing]
----
cluster1::> cluster image validate -version 9.7

WARNING: There are additional manual upgrade validation checks that must be performed after these automated validation checks have completed...
----
. 监控验证进度：
+
`cluster image show-update-progress`

. 完成验证确定的所有必需操作。
. 生成软件升级估计值：
+
`cluster image update -version package_version_number -estimate-only`

+
软件升级估计值可显示有关要更新的每个组件的详细信息以及估计的升级持续时间。

. 执行软件升级：
+
`cluster image update -version package_version_number`

+
** 如果要从 ONTAP 9.3 升级到 9.7 ，请使用上述命令中的 9.7 package_version_number 。
** 如果要从 ONTAP 9.5 升级到 9.9.1 ，请使用上述命令中的 9.9.1 package_version_number 。
** 对于除双节点 MetroCluster 系统之外的任何 MetroCluster 配置，在用户启动并在命令行上提供确认之后， ONTAP 升级过程会在两个站点（本地站点和灾难恢复站点）的 HA 对上同时启动。对于双节点 MetroCluster 系统，首先在灾难恢复站点（即未启动升级的站点）上启动更新。在灾难恢复站点上完成更新后，升级将在本地站点上开始。
** 如果集群包含 2 到 6 个节点，则会执行滚动升级。如果集群包含 8 个或更多节点，则默认情况下会执行批量升级。如果需要，您可以使用 ` -force-rolling` 参数指定滚动升级。
** 完成每次接管和交还后，升级将等待 8 分钟，以使客户端应用程序能够从接管和交还期间发生的 I/O 暂停中恢复。如果您的环境需要的客户端稳定时间或多或少，您可以使用 ` -stify-minutes` 参数指定不同的稳定时间量。
+
[listing]
----
cluster1::> cluster image update -version 9.7

Starting validation for this update. Please wait..

It can take several minutes to complete validation...

WARNING: There are additional manual upgrade validation checks...

Pre-update Check      Status     Error-Action
--------------------- ---------- --------------------------------------------
...
20 entries were displayed

Would you like to proceed with update ? {y|n}: y
Starting update...

cluster-1::>
----


. 显示集群更新进度：
+
`cluster image show-update-progress`

+

NOTE: 如果要升级 4 节点或 8 节点 MetroCluster 配置，则 `cluster image show-update-progress` 命令仅会显示运行此命令的节点的进度。您必须在每个节点上运行命令才能查看各个节点的进度。

. 验证是否已在每个节点上成功完成升级。
+
[listing]
----
cluster1::> cluster image show-update-progress

                                             Estimated         Elapsed
Update Phase         Status                   Duration        Duration
-------------------- ----------------- --------------- ---------------
Pre-update checks    completed                00:10:00        00:02:07
Data ONTAP updates   completed                01:31:00        01:39:00
Post-update checks   completed                00:10:00        00:02:00
3 entries were displayed.

Updated nodes: node0, node1.

cluster1::>
----
. 触发 AutoSupport 通知：
+
`AutoSupport invoke -node * -type all -message "fining_NDU"`

+
如果集群未配置为发送 AutoSupport 消息，则通知的副本将保存在本地。

. 验证集群是否已启用自动计划外切换：
+

NOTE: 仅对 MetroCluster FC 配置执行此操作步骤 。如果您使用的是 MetroCluster IP 配置，请跳过此操作步骤 。

+
.. 检查是否已启用自动计划外切换：
+
`MetroCluster show`

+
如果启用了自动计划外切换，则命令输出中将显示以下语句：

+
....
AUSO Failure Domain    auso-on-cluster-disaster
....
.. 如果输出中未显示该语句，请启用自动计划外切换：
+
`MetroCluster modify -auto-switchover-failure-domain auso-on-cluster-disaster`

.. 重复步骤 1 ，验证是否已启用自动计划外切换。






== 在自动升级过程中出现错误后恢复升级（使用命令行界面）

如果自动升级因错误而暂停，您可以解决此错误并恢复自动升级，也可以取消自动升级并手动完成此过程。如果选择继续自动升级，请勿手动执行任何升级步骤。

.关于此任务
如果要手动完成升级，请使用 `cluster image cancel-update` 命令取消自动过程并手动继续。如果要继续自动升级，请完成以下步骤。

.步骤
. 查看升级错误：
+
`cluster image show-update-progress`

. 解决此错误。
. 恢复更新：
+
`集群映像 resume-update`



.相关信息
https://aiq.netapp.com/["启动 Active IQ"]

https://docs.netapp.com/us-en/active-iq/["Active IQ 文档"]
