---
permalink: upgrade/task_verify_status.html 
sidebar: sidebar 
keywords: ontap, upgrade, upgrade, verify, status, ha, ldap, dns, networking, storage, metrocluster 
summary: 各种配置设置可能会影响集群升级准备情况。 
---
= 验证状态
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在升级之前，您应验证以下内容：

* HA 对状态
* LDAP 状态（适用于 ONTAP 9.2 或更高版本）
* DNS 服务器状态（适用于 ONTAP 9.2 或更高版本），
* 网络连接和存储状态（对于 MetroCluster 配置）




== 正在验证 HA 状态

在执行无中断升级之前，您应验证是否已为每个 HA 对启用存储故障转移。如果集群仅包含两个节点，则还应验证是否已启用集群 HA 。

如果您计划执行中断升级，则无需验证 HA 状态，因为此升级方法不需要存储故障转移。

. 验证是否已为每个 HA 对启用存储故障转移并可进行此操作： `storage failover show`
+
此示例显示 node0 和 node1 上已启用并可执行存储故障转移：

+
[listing]
----
cluster1::> storage failover show
                              Takeover
Node           Partner        Possible State
-------------- -------------- -------- -------------------------------------
node0          node1          true     Connected to node1
node1          node0          true     Connected to node0
2 entries were displayed.
----
+
如有必要，您可以使用 storage failover modify 命令启用存储故障转移。

. 如果集群仅包含两个节点（一个 HA 对），请验证是否已配置集群 HA ： `cluster ha show`
+
此示例显示已配置集群 HA ：

+
[listing]
----
cluster1::> cluster ha show
High Availability Configured: true
----
+
如有必要，您可以使用 cluster ha modify 命令启用集群 HA 。





== 验证 LDAP 状态（ ONTAP 9.2 及更高版本）

从 ONTAP 9.2 开始，如果 Storage Virtual Machine （ SVM ）使用 LDAP ，则必须建立 LDAP 连接才能执行无中断升级。在开始升级之前，您应验证 LDAP 连接。

如果您要从 ONTAP 9.1 或更早版本升级，则此任务不适用。

. 检查 LDAP 状态： `ldap check -vserver vserver_name`
. 如果 LDAP 状态为 down ，请将其修改为： `ldap client modify -client-config ldap_client -ldap-servers ip_address`
. 验证 LDAP 状态是否为 up ： `ldap check -vserver vserver_name`




== 验证 DNS 服务器状态（ ONTAP 9.2 及更高版本）

从 ONTAP 9.2 及更高版本开始，您应在执行无中断升级前后验证域名服务（ DNS ）服务器的状态。

如果您要从 ONTAP 9.1 或更早版本升级，则此任务不适用。

. 检查 DNS 服务器的状态： `dns check -vserver vserver_name`
+
up 状态表示服务正在运行。关闭状态表示服务未运行。

. 如果 DNS 服务器已关闭，请修改它： `dns modify -vserver vserver_name -domains domain_name -name-servers name_server_ipaddress`
. 验证 DNS 服务器的状态是否为已启动。

