---
permalink: upgrade/task_updating_an_ontap_cluster_disruptively.html 
sidebar: sidebar 
keywords: ontap, upgrade, disruptively 
summary: 如果您可以使集群脱机以升级到新的 ONTAP 版本，则可以使用中断升级方法。此方法包括几个步骤：为每个 HA 对禁用存储故障转移，重新启动集群中的每个节点，然后重新启用存储故障转移。 
---
= 使用命令行界面手动执行中断升级
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您可以使集群脱机以升级到新的 ONTAP 版本，则可以使用中断升级方法。此方法包括几个步骤：为每个 HA 对禁用存储故障转移，重新启动集群中的每个节点，然后重新启用存储故障转移。

* 您必须满足准备要求。
+
特别是、您必须使用操作步骤 下载并安装软件映像 link:task_download_and_install_ontap_software_image.html#for-manual-upgrades["用于手动升级"]。

* 如果您在 SAN 环境中运行，则必须关闭或暂停所有 SAN 客户端，直到升级完成。
+
如果在中断升级之前未关闭或暂停 SAN 客户端，则客户端文件系统和应用程序会发生错误，可能需要在升级完成后手动恢复。



在中断升级中，需要停机，因为每个 HA 对都禁用了存储故障转移，并且每个节点都会更新。禁用存储故障转移后，每个节点将充当单节点集群；也就是说，只要系统需要重新启动，与该节点关联的系统服务就会中断。

. 将权限级别从 admin 设置为 advanced ，并在系统提示您继续时输入 * y* ： `set -privilege advanced`
+
此时将显示高级提示符（` * >` ）。

. 将新的 ONTAP 软件映像设置为默认映像： `ssystem image modify ｛ -node * -iscurrent false ｝ -isdefault true`
+
此命令使用扩展查询将目标 ONTAP 软件映像（作为备用映像安装）更改为每个节点的默认映像。

. 验证新的 ONTAP 软件映像是否设置为默认映像： `ssystem image show`
+
在以下示例中，映像 2 是新的 ONTAP 版本，并设置为两个节点上的默认映像：

+
[listing]
----
cluster1::*> system image show
                 Is      Is                Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------- -------------------
node0
         image1  false   true    X.X.X     MM/DD/YYYY TIME
         image2  true    false   Y.Y.Y     MM/DD/YYYY TIME
node1
         image1  false   true    X.X.X     MM/DD/YYYY TIME
         image2  true    false   Y.Y.Y     MM/DD/YYYY TIME
4 entries were displayed.
----
. 执行以下步骤之一：
+
[cols="2*"]
|===
| 集群是否包含 ... | 执行此操作 ... 


 a| 
一个节点
 a| 
继续执行下一步。



 a| 
两个节点
 a| 
.. 禁用集群高可用性： `cluster ha modify -configured false`
+
出现提示时，输入 `y` 继续。

.. 为 HA 对禁用存储故障转移： `storage failover modify -node * -enabled false`




 a| 
两个以上节点
 a| 
为集群中的每个 HA 对禁用存储故障转移： `storage failover modify -node * -enabled false`

|===
. 重新启动集群中的节点： `ssystem node reboot -node nodename -ignore-quorum-warnings`
+

IMPORTANT: 请勿一次重新启动多个节点。

+
节点将启动新的 ONTAP 映像。此时将显示 ONTAP 登录提示，指示重新启动过程已完成。

. 使用新的 ONTAP 映像重新启动节点或一组节点后，确认新软件正在运行： `ssystem node image show`
+
在以下示例中， image1 是新的 ONTAP 版本，并设置为 node0 上的当前版本：

+
[listing]
----
cluster1::*> system node image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  true    true    X.X.X       MM/DD/YYYY TIME
         image2  false   false   Y.Y.Y      MM/DD/YYYY TIME
node1
         image1  true    false   X.X.X      MM/DD/YYYY TIME
         image2  false   true    Y.Y.Y      MM/DD/YYYY TIME
4 entries were displayed.
----
. 验证升级是否已成功完成：
+
.. 将权限级别设置为 advanced ： `set -privilege advanced`
.. 验证每个节点的升级状态是否已完成： `ssystem node upgrade-revert show -node nodename`
+
此状态应列为已完成。

+
如果升级失败，请从节点运行 system node upgrade-revert upgrade 命令。如果此命令未完成节点的升级，请立即联系技术支持。

.. 返回到管理权限级别： `set -privilege admin`


. 对其他每个节点重复步骤 2 到 7 。
. 如果集群包含两个或更多节点，请为集群中的每个 HA 对启用存储故障转移： `storage failover modify -node * -enabled true`
. 如果集群仅包含两个节点，请启用集群高可用性： `cluster ha modify -configured true`

