---
permalink: upgrade/task_updating_an_ontap_cluster_disruptively.html 
sidebar: sidebar 
keywords: ontap, upgrade, disruptively 
summary: 如果您可以使集群脱机以升级到新的 ONTAP 版本，则可以使用中断升级方法。 
---
= 使用命令行界面手动执行中断ONTAP升级
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您可以使集群脱机以升级到新的 ONTAP 版本，则可以使用中断升级方法。此方法包括几个步骤：为每个 HA 对禁用存储故障转移，重新启动集群中的每个节点，然后重新启用存储故障转移。

* 您必须 link:download-software-image.html["下载"] 和 link:install-software-manual-upgrade.html["安装"] 软件映像。
* 如果您在 SAN 环境中运行，则必须关闭或暂停所有 SAN 客户端，直到升级完成。
+
如果在中断升级之前未关闭或暂停 SAN 客户端，则客户端文件系统和应用程序会发生错误，可能需要在升级完成后手动恢复。



在中断升级中，需要停机，因为每个 HA 对都禁用了存储故障转移，并且每个节点都会更新。禁用存储故障转移后，每个节点将充当单节点集群；也就是说，只要系统需要重新启动，与该节点关联的系统服务就会中断。

.步骤
. 将权限级别从admin设置为advance,在系统提示您继续时输入*y*：
+
[source, cli]
----
set -privilege advanced
----
+
高级提示符 (`*>`)。

. 将新的ONTAP软件映像设置为默认映像：
+
[source, cli]
----
system image modify {-node * -iscurrent false} -isdefault true
----
+
此命令使用扩展查询将目标 ONTAP 软件映像（作为备用映像安装）更改为每个节点的默认映像。

. 验证新的ONTAP软件映像是否设置为默认映像：
+
[source, cli]
----
system image show
----
+
在以下示例中，映像 2 是新的 ONTAP 版本，并设置为两个节点上的默认映像：

+
[listing]
----
cluster1::*> system image show
                 Is      Is                Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------- -------------------
node0
         image1  false   true    X.X.X     MM/DD/YYYY TIME
         image2  true    false   Y.Y.Y     MM/DD/YYYY TIME
node1
         image1  false   true    X.X.X     MM/DD/YYYY TIME
         image2  true    false   Y.Y.Y     MM/DD/YYYY TIME
4 entries were displayed.
----
. 执行以下步骤之一：
+
[cols="2*"]
|===
| 集群是否包含 ... | 执行此操作 ... 


 a| 
一个节点
 a| 
继续执行下一步。



 a| 
两个节点
 a| 
.. 禁用集群高可用性：
+
[source, cli]
----
cluster ha modify -configured false
----
+
输入 ... `y` 出现提示时继续。

.. 对HA对禁用存储故障转移：
+
[source, cli]
----
storage failover modify -node * -enabled false
----




 a| 
两个以上节点
 a| 
为集群中的每个HA对禁用存储故障转移：

[source, cli]
----
storage failover modify -node * -enabled false
----
|===
. 重新启动集群中的节点：
+
[source, cli]
----
system node reboot -node nodename -ignore-quorum-warnings
----
+

IMPORTANT: 请勿一次重新启动多个节点。

+
节点将启动新的 ONTAP 映像。此时将显示 ONTAP 登录提示，指示重新启动过程已完成。

. 使用新的ONTAP 映像重新启动节点或一组节点后、将权限级别设置为高级：
+
[source, cli]
----
set -privilege advanced
----
+
在系统提示您继续时、输入*

. 确认新软件正在运行：
+
[source, cli]
----
system node image show
----
+
在以下示例中， image1 是新的 ONTAP 版本，并设置为 node0 上的当前版本：

+
[listing]
----
cluster1::*> system node image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  true    true    X.X.X       MM/DD/YYYY TIME
         image2  false   false   Y.Y.Y      MM/DD/YYYY TIME
node1
         image1  true    false   X.X.X      MM/DD/YYYY TIME
         image2  false   true    Y.Y.Y      MM/DD/YYYY TIME
4 entries were displayed.
----
. 验证升级是否已成功完成：
+
.. 将权限级别设置为高级：
+
[source, cli]
----
set -privilege advanced
----
.. 验证每个节点的升级状态是否为complete：
+
[source, cli]
----
system node upgrade-revert show -node nodename
----
+
此状态应列为已完成。

+
如果状态不是complete、请link:http://mysupport.netapp.com/["请联系NetApp支持部门"^]立即。

.. 返回到管理权限级别：
+
[source, cli]
----
set -privilege admin
----


. 对其他每个节点重复步骤5到8。
. 如果集群包含两个或更多节点、请为集群中的每个HA对启用存储故障转移：
+
[source, cli]
----
storage failover modify -node * -enabled true
----
. 如果集群仅包含两个节点、请启用集群高可用性：
+
[source, cli]
----
cluster ha modify -configured true
----


.相关信息
* link:https://docs.netapp.com/us-en/ontap-cli/storage-failover-modify.html["存储故障转移修改"^]

