---
permalink: upgrade/task_verifying_the_lif_failover_configuration.html 
sidebar: sidebar 
keywords: ontap, upgrade, verifying, verify, lif, failover, configuration 
summary: 在执行升级之前，您必须验证是否已正确配置故障转移策略和故障转移组。 
---
= 验证LIF故障转移配置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在升级ONTAP之前、您必须验证是否已正确配置集群的故障转移策略和故障转移组。


NOTE: 在升级过程中，将根据升级方法迁移 LIF 。根据升级方法，可能会使用 LIF 故障转移策略，也可能不使用该策略。

.批量升级和滚动升级
如果集群中有 8 个或更多节点，则会使用批处理方法执行自动升级。批量升级方法包括将集群划分为多个升级批处理，升级第一批处理中的一组节点，升级其高可用性（ HA ）配对节点，然后对其余批重复此过程。在 ONTAP 9.7 及更早版本中，如果使用批处理方法，则 LIF 会迁移到要升级的节点的 HA 配对节点。在ONTAP 9.8及更高版本中、如果使用批处理方法、则LIF会迁移到另一个批处理组。

如果集群中的节点数少于 8 个，则会使用滚动方法执行自动升级。滚动升级方法包括对HA对中的每个节点启动故障转移操作、更新已进行故障转移的节点、启动交还、然后对集群中的每个HA对重复此过程。如果使用滚动方法，则 LIF 将迁移到 LIF 故障转移策略定义的故障转移目标节点。

.验证LIF故障转移配置
. 显示每个数据 LIF 的故障转移策略：
+
[cols="2*"]
|===
| 如果您的 ONTAP 版本为 ... | 使用此命令 ... 


| 9.6或更高版本  a| 
`network interface show -service-policy \*data* -failover`



| 9.5或更早版本  a| 
`network interface show -role data -failover`

|===
+
此示例显示了具有两个数据 LIF 的双节点集群的默认故障转移配置：

+
[listing]
----
cluster1::> network interface show -role data -failover
         Logical         Home                  Failover        Failover
Vserver  Interface       Node:Port             Policy          Group
-------- --------------- --------------------- --------------- ---------------
vs0
         lif0            node0:e0b             nextavail       system-defined
                         Failover Targets: node0:e0b, node0:e0c,
                                           node0:e0d, node0:e0e,
                                           node0:e0f, node1:e0b,
                                           node1:e0c, node1:e0d,
                                           node1:e0e, node1:e0f
vs1
         lif1            node1:e0b             nextavail       system-defined
                         Failover Targets: node1:e0b, node1:e0c,
                                           node1:e0d, node1:e0e,
                                           node1:e0f, node0:e0b,
                                           node0:e0c, node0:e0d,
                                           node0:e0e, node0:e0f
----
+
"* 故障转移目标 * " 字段显示每个 LIF 的故障转移目标的优先级列表。例如、如果"if0"从其主端口(node0上的e0b)进行故障转移、则它会首先尝试故障转移到node0上的端口e0c。如果if0无法故障转移到e0c、则会尝试故障转移到node0上的端口e0d、依此类推。

. 如果SAN LIF以外的任何LIF的故障转移策略设置为*禁用*、请使用 `network interface modify` 命令以启用故障转移。
. 对于每个 LIF ，请验证 * 故障转移目标 * 字段是否包含不同节点的数据端口，这些数据端口将在升级 LIF 的主节点时保持正常运行。
+
您可以使用 `network interface failover-groups modify` 命令将故障转移目标添加到故障转移组。

+
.示例
[listing]
----
network interface failover-groups modify -vserver vs0 -failover-group fg1 -targets sti8-vsim-ucs572q:e0d,sti8-vsim-ucs572r:e0d
----


.相关信息
link:../networking/networking_reference.html["网络和 LIF 管理"]
