---
sidebar: sidebar 
permalink: upgrade/task_upgrade_disruptive_automated_cli.html 
keywords: netapp, ontap, upgrade, nondisruptive, nondisruptively, non-disruptive update, nondisruptive upgrade, upgrade a cluster, shift workload between clusters, hardware platform, configuration, software image, update, update ONTAP, update software, ndu 
summary: 您可以无中断地更新集群上的 ONTAP 版本。 
---
= 使用 CLI 自动中断（仅限单节点集群）
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
从 ONTAP 9.2 开始，您可以自动更新单节点集群。由于单节点集群缺少冗余，因此更新始终会造成中断。

* 您必须满足升级准备要求。
+
.. 删除先前的 ONTAP 软件包： `cluster image package delete -version previous_package_version`
.. 下载目标 ONTAP 软件包： `cluster image package get -url location`
+
[listing]
----
cluster1::> cluster image package get -url http://www.example.com/software/9.7/image.tgz

Package download completed.
Package processing completed.
----
.. 验证集群软件包存储库中是否存在软件包： `cluster image package show-repository`
+
[listing]
----
cluster1::> cluster image package show-repository
Package Version  Package Build Time
---------------- ------------------
9.7              M/DD/YYYY 10:32:15
----
.. 验证集群是否已做好升级准备： `cluster image validate -version package_version_number`
+
[listing]
----
cluster1::> cluster image validate -version 9.7

WARNING: There are additional manual upgrade validation checks that must be performed after these automated validation checks have completed...
----
.. 监控验证进度： `cluster image show-update-progress`
.. 完成验证确定的所有必需操作。
.. (可选)生成软件升级预估： `cluster image update -version package_version_number -estimate-only`
+
软件升级估计值可显示有关要更新的每个组件的详细信息以及估计的升级持续时间。

.. 执行软件升级： `cluster image update -version package_version_number`
+

NOTE: 如果遇到问题描述，更新将暂停并提示您采取更正操作。您可以使用 cluster image show-update-progress 命令查看有关任何问题的详细信息以及更新进度。更正问题描述后，您可以使用 cluster image resume-update 命令恢复更新。

.. 显示集群更新进度： `cluster image show-update-progress`
+
此节点将在更新过程中重新启动，并且在重新启动时无法访问。

.. 触发通知： `autosupport invoke -node * -type all -message "Finishing_Upgrade"`
+
如果集群未配置为发送消息，则通知的副本将保存在本地。




