---
permalink: upgrade/task_download_and_install_ontap_software_image.html 
sidebar: sidebar 
keywords: ontap, software, image, download, downloading, install, installing 
summary: 您必须先下载 ONTAP 软件，然后才能进行安装。 
---
= 下载并安装 ONTAP 软件映像
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须先从 NetApp 支持站点下载 ONTAP 软件，然后才能进行安装。



== 下载软件映像

对于 ONTAP 9.4 及更高版本，您可以将 ONTAP 软件映像从 NetApp 支持站点复制到本地文件夹。对于从 ONTAP 9.3 或更早版本升级的系统，您必须将 ONTAP 软件映像复制到网络上的 HTTP 服务器或 FTP 服务器。

您应注意以下重要信息：

* 软件映像特定于平台型号。
+
您必须为集群获取正确的映像。您可以从 NetApp 支持站点获取适用于您的平台型号的软件映像，固件版本信息和最新固件。

* 软件映像包括在发布给定版本的 ONTAP 时可用的最新版本系统固件。
* 如果要将使用 NetApp 卷加密的系统升级到 ONTAP 9.5 或更高版本，则必须下载适用于非受限国家或地区的 ONTAP 软件映像，其中包括 NetApp 卷加密。
+
如果使用适用于受限国家或地区的 ONTAP 软件映像升级采用 NetApp 卷加密的系统，则系统将崩溃，您将无法访问卷。

* 如果要从 ONTAP 9.5 升级到 9.1.1 ，则必须复制 ONTAP 9.7 和 9.1.1 的软件映像。
* 如果要从 ONTAP 9.3 升级到 9.7 ，则必须复制 ONTAP 9.5 和 9.7 的软件映像。
+
.. 在中找到目标 ONTAP 软件 link:http://mysupport.netapp.com/NOW/cgi-bin/software["软件下载"] NetApp 支持站点的区域。
.. 复制软件映像。
+
*** 对于 ONTAP 9.3 或更早版本，请将软件映像（例如 93_q_image.tgz ）从 NetApp 支持站点复制到 HTTP 服务器或 FTP 服务器上要提供此映像的目录。
*** 对于 ONTAP 9.4 或更高版本，请将软件映像（例如 97_q_image.tgz ）从 NetApp 支持站点复制到要从中提供此映像的 HTTP 服务器或 FTP 服务器上的目录或本地文件夹。








== 安装软件映像

您必须在集群节点上安装目标软件映像。

* 如果要将使用 NetApp 卷加密的系统升级到 ONTAP 9.5 或更高版本，则必须已下载适用于非受限国家或地区的 ONTAP 软件映像，其中包括 NetApp 卷加密。
+
如果使用适用于受限国家或地区的 ONTAP 软件映像升级采用 NetApp 卷加密的系统，则系统将崩溃，您将无法访问卷。

* 如果要从 ONTAP 9.5 直接升级到 9.1.1 ，则必须下载 ONTAP 9.7 和 9.1.1 的软件映像。如果要从 ONTAP 9.3 直接升级到 9.7 ，则必须下载 ONTAP 9.5 和 9.7 的软件映像。
+
自动升级过程会使用后台的两个映像完成升级。

+
.. 将权限级别设置为高级，在系统提示您继续时输入 * y* ： `set -privilege advanced`
+
此时将显示高级提示符（` * >` ）。







=== 自动无中断升级（ ANDU ）

. 检查映像存储库并删除任何先前的映像。
+
`集群映像包 show-repository`

+
[listing]
----
cluster image package show-repository\
<<smoke6-vsim-ucs6b4c#c-login_27|There are no packages in the repository.\r\n
----
. 下载映像。
+
`集群映像包 get -url url_to_image_on_nssl`

+
`集群映像包 get -url http://10.60.132.98/x/eng/rlse/DOT/9.7P13X2/promo/9.7P13X2/x86_64.optimize/image.tgz`[]

. 验证软件包是否已下载。
+
`集群映像包 show-repository`

+
.示例
[listing]
----
cluster image package show-repository -fields download-ver\
<<smoke6-vsim-ucs6b4c#c-login_27| download-verX;X\r\n
<<smoke6-vsim-ucs6b4c#c-login_27| Downloaded VersionX;X\r\n
<<smoke6-vsim-ucs6b4c#c-login_27| Stormking__9.10.0X;X\r\n
----




=== 用于手动升级

. 下载映像。
+
.. 如果要升级非 MetroCluster 配置或双节点 MetroCluster 配置，请使用以下命令下载映像：
+
`ssystem node image update -node * -package location -replace -package true -setdefault true -background true`

+

NOTE: 此命令可同时在所有节点上下载并安装软件映像。要一次在每个节点上下载并安装一个映像，请勿指定 -background 参数。

.. 如果要升级四节点或八节点 MetroCluster 配置，则必须在两个集群上执行问题描述以下命令：
+
`ssystem node image update -node * -package location -replace -package true -background true -setdefault false`

+
此命令使用扩展查询来更改目标软件映像，该映像作为备用映像安装在每个节点上。



. 出现提示时，输入 `y` 继续。
. 验证是否已在每个节点上下载并安装软件映像。
+
`ssystem node image show-update-progress -node *`

+
此命令将显示软件映像下载和安装的当前状态。您应继续运行此命令，直到所有节点报告 * 运行状态 * 为 * 已退出 * ， * 退出状态 * 为 * 成功 * 。

+
system node image update 命令可能会失败并显示错误或警告消息。解决任何错误或警告后，您可以再次运行此命令。

+
此示例显示了一个双节点集群，其中软件映像已成功下载并安装在两个节点上：

+
[listing]
----
cluster1::*> system node image show-update-progress -node *
There is no update/install in progress
Status of most recent operation:
        Run Status:     Exited
        Exit Status:    Success
        Phase:          Run Script
        Exit Message:   After a clean shutdown, image2 will be set as the default boot image on node0.
There is no update/install in progress
Status of most recent operation:
        Run Status:     Exited
        Exit Status:    Success
        Phase:          Run Script
        Exit Message:   After a clean shutdown, image2 will be set as the default boot image on node1.
2 entries were acted on.
----

