---
permalink: zero-trust/zero-trust-automation-orchestration.html 
sidebar: sidebar 
keywords: ontap, netapp, security, automation, orchestration, control, ansible 
summary: 借助自动化、企业可以将零信任部署扩展到手动过程之外、以防止同时自动化的不当活动。 
---
= ONTAP外部的NetApp安全自动化和业务流程控制
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过自动化、您可以在最少的人工协助下执行流程或程序。借助自动化、企业可以将零信任部署扩展到远远超出手动过程的范围、从而防止同时自动化的不当活动。

Ans还是 一款开源软件配置、配置管理和应用程序部署工具。它可以在许多类Unix系统上运行、并且可以配置类Unix系统以及Microsoft Windows。它包含自己的声明性语言来描述系统配置。《安赛威》由Michael DeHaan编写、并于2015年被Red Hat收购。Ansil可能 无代理、通过SSH或Windows远程管理临时远程连接(允许远程执行PowerShell)以执行任务。NetApp开发了更多产品 https://www.netapp.com/us/getting-started-with-netapp-approved-ansible-modules/index.aspx["150个适用于ONTAP软件的Ans负责 模块"^]，可进一步与Ans得 自动化框架集成。适用于NetApp的Ans得 模块提供了一组有关如何定义所需状态并将其中继到目标NetApp环境的说明。这些模块旨在支持设置许可、创建聚合和Storage Virtual Machine、创建卷和还原快照等任务。《NetApp DoD统一功能(UC)部署指南》专门指定了一个"Ands还是And"角色 https://github.com/NetApp/ansible/tree/master/nar_ontap_security_ucd_guide["发布在GitHub上"^] 。

使用可用模块库、用户可以轻松开发Ans得 易操作手册、并根据自己的应用程序和业务需求对其进行自定义、以自动执行日常任务。编写完播放手册后、您可以运行它来执行指定的任务、从而节省时间并提高工作效率。NetApp已创建并共享了可直接使用或根据您的需求定制的示例操作手册。

Cloud Insights是一款基础架构监控工具、可让您深入了解整个基础架构。借助Cloud Insights、您可以监控和优化所有资源、包括公有云实例和私有数据中心、并对其进行故障排除。Cloud Insights可以将平均解决时间缩短90%、并防止80%的云问题影响最终用户。此外、它还可以利用可指导行动的智能信息保护您的数据、从而将云基础架构成本平均降低33%、并降低您遭受内部威胁的风险。通过Cloud Insights的存储工作负载安全性功能、可以使用AI和ML进行用户行为分析、以便在内部威胁导致出现异常用户行为时发出警报。对于ONTAP、存储工作负载安全性使用零信任FPolicy引擎。
