---
permalink: performance-admin/adaptive-qos-policy-groups-task.html 
sidebar: sidebar 
keywords: use, adaptive, qos, policy, groups 
summary: 您可以使用自适应 QoS 策略组自动将吞吐量上限或下限扩展到卷大小，从而在卷大小发生变化时保持 IOPS 与 TBSGB 的比率。如果您要在大型部署中管理数百或数千个工作负载，则这是一项显著优势。 
---
= 使用自适应 QoS 策略组
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 _adaptive QoS_ 策略组自动将吞吐量上限或下限扩展到卷大小，从而在卷大小发生变化时保持 IOPS 与 TBSGB 的比率。如果您要在大型部署中管理数百或数千个工作负载，则这是一项显著优势。

.您需要什么？ #8217 ；将需要什么
* 您必须运行 ONTAP 9.3 。自 ONTAP 9.3 起，可使用自适应 QoS 策略组。
* 您必须是集群管理员才能创建策略组。


存储对象可以是自适应策略组或非自适应策略组的成员，但不能同时是这两者。存储对象的 SVM 和策略必须相同。存储对象必须处于联机状态。

自适应 QoS 策略组始终为非共享组：定义的吞吐量上限或每个成员工作负载的下限适用场景。

吞吐量限制与存储对象大小的比率取决于以下字段的交互：

* `expected-IOPS` 是每个已分配 TB-GB 的最小预期 IOPS 。
+
[NOTE]
====
`只能在 AFF 平台上保证预期 IOPS` 。只有当分层策略设置为 " 无 " 且云中没有块时， FabricPool 才会保证 `expected-IOPS` 。对于未建立 SnapMirror 同步关系的卷，可以保证 `expected-IOPS` 。

====
* `peak-IOPS` 是每个已分配或已使用 TB-GB 的最大可能 IOPS 。
* `expected-IOPS-allocation` 指定预期 IOPS 是使用已分配空间（默认值）还是已用空间。
+
[NOTE]
====
`expected-IOPS-allocation` 适用于 ONTAP 9.5 及更高版本。ONTAP 9.4 及更早版本不支持此功能。

====
* `peak-IOPS-allocation` 指定是将已分配空间还是已用空间（默认值）用于 `peak-IOPS` 。
* `ab绝对 最小 IOPS` 是绝对最小 IOPS 数。您可以对非常小的存储对象使用此字段。当 `abory-min-IOPS` 大于计算得出的 `expected-IOPS` 时，它会同时覆盖 `peak-IOPS` 和 / 或 `expected-IOPS` 。
+
例如，如果将 `expected-IOPS` 设置为 1 ， 000 IOPS/TB ，并且卷大小小于 1 GB ，则计算的 `expected-IOPS` 将为一个百分比 IOP 。计算得出的 `峰值 IOPS` 将是更小的比例。您可以通过将 `abisy-min-IOPS` 设置为实际值来避免这种情况。

* `block-size` 指定应用程序 I/O 块大小。默认值为 32 K 。有效值为 8K ， 16K ， 32K ， 64K ，任意。any 表示不强制实施块大小。


可用的三个默认自适应 QoS 策略组如下表所示。您可以将这些策略组直接应用于卷。

|===


| 默认策略组 | 预期 IOPS/TB | 峰值 IOPS/TB | 绝对最小 IOPS 


 a| 
`至高`
 a| 
6,144
 a| 
12,288
 a| 
1000



 a| 
`性能`
 a| 
2 ， 048
 a| 
4,096
 a| 
500



 a| 
`值`
 a| 
128.
 a| 
512
 a| 
75

|===
如果某个存储对象的包含对象或子对象属于某个策略组，则不能将该存储对象分配给该策略组。下表列出了这些限制。

|===
| 如果您分配 ... | 则不能分配 ... 


 a| 
SVM 到策略组
 a| 
将 SVM 包含的任何存储对象分配给策略组



 a| 
卷到策略组
 a| 
包含 SVM 的卷或策略组的任何子 LUN



 a| 
LUN 到策略组
 a| 
将包含 LUN 的卷或 SVM 分配给策略组



 a| 
文件到策略组
 a| 
将文件包含的卷或 SVM 分配给策略组

|===
.步骤
. 创建自适应 QoS 策略组：
+
`qos adaptive-policy-group create -policy group _policy_group_ -vserver _svm_ -expected-IOPS _number_of_IOPS_/TB_GB -pease-IOPS _number_of_IOPS_/TB_GB -expected-IOPS-allocation-space lused-space -pease-IOPS- allocation allocated-space| used-space| used-space -used-space - used-space - used-space - used-space - used -space - space- used -space - space- used -space - space- space- space- space- space`

+
有关完整的命令语法，请参见手册页。

+
[NOTE]
====
ONTAP 9.5 及更高版本中提供了 ` -expected-IOPS-allocation` 和 ` -block-size` 。ONTAP 9.4 及更早版本不支持这些选项。

====
+
以下命令将创建自适应 QoS 策略组 `adpg-app1` ，其中 ` -expected-IOPS` 设置为 300 IOPS/TB ， ` -peak-IOPS` 设置为 1 ， 000 IOPS/TB ， ` -peak-IOPS-allocation` 设置为 `used-space` ， ` -abrey-min-IOPS` 设置为 50 IOPS ：

+
[listing]
----
cluster1::> qos adaptive-policy-group create -policy group adpg-app1 -vserver vs2 -expected-iops 300iops/tb -peak-iops 1000iops/TB -peak-iops-allocation used-space -absolute-min-iops 50iops
----
. 将自适应 QoS 策略组应用于卷：
+
`volume create -vserver SVM -volume _volume_-aggregate _aggregate_ -size _number_of_TB_GB -qos-adaptive-policy-group _policy_group_`

+
有关完整的命令语法，请参见手册页。

+
以下命令会将自适应 QoS 策略组 `adpg-app1` 应用于卷 `app1` ：

+
[listing]
----
cluster1::> volume create -vserver vs1 -volume app1 -aggregate aggr1 -size 2TB -qos-adaptive-policy-group adpg-app1
----
+
以下命令会将默认的自适应 QoS 策略组 `至` 至新卷 `app4` 和现有卷 `app5` 。为策略组适用场景 volumes `app4` 和 `app5` 分别定义的吞吐量上限：

+
[listing]
----
cluster1::> volume create -vserver vs4 -volume app4 -aggregate aggr4 -size 2TB -qos-adaptive-policy-group extreme
----
+
[listing]
----
cluster1::> volume modify -vserver vs5 -volume app5 -qos-adaptive-policy-group extreme
----

