---
permalink: performance-admin/adaptive-qos-policy-groups-task.html 
sidebar: sidebar 
keywords: use, adaptive, qos, policy, groups 
summary: 您可以使用自适应 QoS 策略组自动将吞吐量上限或下限扩展到卷大小，从而在卷大小发生变化时保持 IOPS 与 TBSGB 的比率。如果您要在大型部署中管理数百或数千个工作负载，则这是一项显著优势。 
---
= 使用自适应 QoS 策略组
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 _adaptive QoS_ 策略组自动将吞吐量上限或下限扩展到卷大小，从而在卷大小发生变化时保持 IOPS 与 TBSGB 的比率。如果您要在大型部署中管理数百或数千个工作负载，则这是一项显著优势。

.开始之前
* 您必须运行ONTAP 9.3或更高版本。自 ONTAP 9.3 起，可使用自适应 QoS 策略组。
* 您必须是集群管理员才能创建策略组。


.关于此任务
存储对象可以是自适应策略组或非自适应策略组的成员，但不能同时是这两者。存储对象的 SVM 和策略必须相同。存储对象必须处于联机状态。

自适应 QoS 策略组始终为非共享组：定义的吞吐量上限或每个成员工作负载的下限适用场景。

吞吐量限制与存储对象大小的比率取决于以下字段的交互：

* `expected-iops` 是每分配的TB|GB的最小预期IOPS。
+
[NOTE]
====
 `expected-iops` 仅在AFF平台上提供担保。 `expected-iops` 只有当层策略设置为"无"且云中没有任何块时、才保证适用于FabricPool。 `expected-iops` 保证适用于不属于SnapMirror同步关系的卷。

====
* `peak-iops` 是已分配或已使用的每TB|GB可能的最大IOPS。
* `expected-iops-allocation` 指定是将已分配空间(默认值)还是已用空间用于预期IOPS。
+
[NOTE]
====
`expected-iops-allocation` 适用于ONTAP 9.5及更高版本。ONTAP 9.4 及更早版本不支持此功能。

====
* `peak-iops-allocation` 指定是将已分配空间用于还是将已用空间(默认值)用于 `peak-iops`。
*  `absolute-min-iops` 是绝对最小IOPS数。您可以对非常小的存储对象使用此字段。它会同时覆盖这两者 `peak-iops` 和 / 或 `expected-iops` 时间 `absolute-min-iops` 大于计算得出的 `expected-iops`。
+
例如、如果您设置了 `expected-iops` 计算得出的值为1、000 IOS/TB、并且卷大小小于1 GB `expected-iops` 将是部分IOP。计算的 `peak-iops` 将是一个更小的比例。您可以通过设置来避免此问题 `absolute-min-iops` 以获得实际价值。

* `block-size` 指定应用程序I/O块大小。默认值为 32 K 。有效值为 8K ， 16K ， 32K ， 64K ，任意。any 表示不强制实施块大小。


可用的三个默认自适应 QoS 策略组如下表所示。您可以将这些策略组直接应用于卷。

|===


| 默认策略组 | 预期 IOPS/TB | 峰值 IOPS/TB | 绝对最小 IOPS 


 a| 
`extreme`
 a| 
6、144
 a| 
12、288
 a| 
1000



 a| 
`performance`
 a| 
2 ， 048
 a| 
4、096
 a| 
500



 a| 
`value`
 a| 
128.
 a| 
512
 a| 
75

|===
如果某个存储对象的包含对象或子对象属于某个策略组，则不能将该存储对象分配给该策略组。下表列出了这些限制。

|===
| 如果您分配 ... | 则不能分配 ... 


 a| 
SVM 到策略组
 a| 
将 SVM 包含的任何存储对象分配给策略组



 a| 
卷到策略组
 a| 
包含 SVM 的卷或策略组的任何子 LUN



 a| 
将LUN分配给策略组
 a| 
将包含 LUN 的卷或 SVM 分配给策略组



 a| 
文件到策略组
 a| 
将文件包含的卷或 SVM 分配给策略组

|===
.步骤
. 创建自适应 QoS 策略组：
+
`qos adaptive-policy-group create -policy group _policy_group_ -vserver _SVM_ -expected-iops _number_of_iops_/TB|GB -peak-iops _number_of_iops_/TB|GB -expected-iops-allocation-space|used-space -peak-iops-allocation allocated-space|used-space -absolute-min-iops _number_of_iops_ -block-size 8K|16K|32K|64K|ANY`

+
有关完整的命令语法，请参见手册页。

+
[NOTE]
====
`-expected-iops-allocation` 和 `-block-size` 适用于ONTAP 9.5及更高版本。ONTAP 9.4 及更早版本不支持这些选项。

====
+
以下命令将创建自适应QoS策略组 `adpg-app1` 使用 `-expected-iops` 设置为300 IOS/TB、 `-peak-iops` 设置为1、000 IOS/TB、 `-peak-iops-allocation` 设置为 `used-space`，和 `-absolute-min-iops` 设置为50 IOPS：

+
[listing]
----
cluster1::> qos adaptive-policy-group create -policy group adpg-app1 -vserver vs2 -expected-iops 300iops/tb -peak-iops 1000iops/TB -peak-iops-allocation used-space -absolute-min-iops 50iops
----
. 将自适应 QoS 策略组应用于卷：
+
`volume create -vserver SVM -volume _volume_ -aggregate _aggregate_ -size _number_of_ TB|GB -qos-adaptive-policy-group _policy_group_`

+
有关完整的命令语法，请参见手册页。

+
以下命令将应用自适应QoS策略组 `adpg-app1` 到卷 `app1`：

+
[listing]
----
cluster1::> volume create -vserver vs1 -volume app1 -aggregate aggr1 -size 2TB -qos-adaptive-policy-group adpg-app1
----
+
以下命令将应用默认自适应QoS策略组 `extreme` 到新卷 `app4` 和到现有卷 `app5`。为策略组适用场景卷定义的吞吐量上限 `app4` 和 `app5` 单独：

+
[listing]
----
cluster1::> volume create -vserver vs4 -volume app4 -aggregate aggr4 -size 2TB -qos-adaptive-policy-group extreme
----
+
[listing]
----
cluster1::> volume modify -vserver vs5 -volume app5 -qos-adaptive-policy-group extreme
----

