---
permalink: performance-admin/set-throughput-floor-qos-task.html 
sidebar: sidebar 
keywords: setting, throughput, floor, qos 
summary: 您可以使用策略组的 min-throughput 字段为存储对象工作负载定义吞吐量下限（ QoS 最小值）。您可以在创建或修改存储对象时应用策略组。从 ONTAP 9.8 开始，您可以以 IOPS 或 MBps 或 IOPS 和 MBps 为单位指定吞吐量下限。 
---
= 在ONTAP中使用QoS设置吞吐量下限
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `min-throughput` 用于为存储对象工作负载定义吞吐量下限(QoS最小值)的策略组字段。您可以在创建或修改存储对象时应用策略组。从 ONTAP 9.8 开始，您可以以 IOPS 或 MBps 或 IOPS 和 MBps 为单位指定吞吐量下限。

.开始之前
* 您必须运行 ONTAP 9.2 或更高版本。从 ONTAP 9.2 开始，吞吐量下限可用。
* 您必须是集群管理员才能创建策略组。
* 从ONTAP 9.131开始，您可以使用在SVM级别强制实施吞吐量下限xref:adaptive-policy-template-task.html[自适应策略组模板]。您不能在具有QoS策略组的SVM上设置自适应策略组模板。


.关于此任务
* 从 ONTAP 9.4 开始，您可以使用 _non-shared_ QoS 策略组来指定将定义的吞吐量下限分别应用于每个成员工作负载。只有在这种情况下，吞吐量下限的策略组才能应用于多个工作负载。
+
设置 `-is-shared=false` 。 `qos policy-group create` 命令以指定非共享策略组。

* 如果节点或聚合上的性能容量（余量）不足，则工作负载的吞吐量可能会低于指定的下限。
* 受 QoS 限制的存储对象必须包含在策略组所属的 SVM 中。多个策略组可以属于同一个 SVM 。
* QoS 最佳实践是将策略组应用于相同类型的存储对象。
* 定义吞吐量下限的策略组不能应用于 SVM 。


.步骤
. 检查节点或聚合上是否具有足够的性能容量，如中所述 link:identify-remaining-performance-capacity-task.html["确定剩余性能容量"]。
. 创建策略组。
+
`qos policy-group create -policy group _policy_group_ -vserver _SVM_ -min-throughput _qos_target_ -is-shared true|false`

+
有关的详细信息 `qos policy-group create`，请参见link:https://docs.netapp.com/us-en/ontap-cli/qos-policy-group-create.html["ONTAP 命令参考"^]。



您可以使用 `qos policy-group modify`命令调整吞吐量下限。

+以下命令将创建最小吞吐量为1、000 IOPS的共享策略组 `pg-vs2`：

+

[listing]
----
cluster1::> qos policy-group create -policy group pg-vs2 -vserver vs2 -min-throughput 1000iops -is-shared true
----
+以下命令将创建无吞吐量限制的非共享策略组 `pg-vs4`：

+

[listing]
----
cluster1::> qos policy-group create -policy group pg-vs4 -vserver vs4 -is-shared false
----
. 将策略组应用于卷或 LUN ：
+
`_storage_object_ create -vserver _SVM_ -qos-policy-group _policy_group_`

+
有关此过程中所述命令的更多信息，请参见link:https://docs.netapp.com/us-en/ontap-cli/["ONTAP 命令参考"^]。您可以使用 `_storage_object_modify`命令将其他策略组应用于存储对象。

+
以下命令将应用策略组 `pg-app2` 卷 `app2`：

+
[listing]
----
cluster1::> volume create -vserver vs2 -volume app2 -aggregate aggr1 -qos-policy-group pg-app2
----
. 监控策略组性能：
+
`qos statistics performance show`

+
有关的详细信息 `qos statistics performance show`，请参见link:https://docs.netapp.com/us-en/ontap-cli/qos-statistics-performance-show.html["ONTAP 命令参考"^]。

+
[NOTE]
====
从集群监控性能。请勿使用主机上的工具监控性能。

====
+
以下命令显示策略组性能：

+
[listing]
----
cluster1::> qos statistics performance show
Policy Group           IOPS      Throughput   Latency
-------------------- -------- --------------- ----------
-total-                 12316       47.76MB/s  1264.00us
pg_app2                  7216       28.19MB/s   420.00us
_System-Best-Effort        62       13.36KB/s     4.13ms
_System-Background         30           0KB/s        0ms
----
. 监控工作负载性能：
+
`qos statistics workload performance show`

+
有关的详细信息 `qos statistics workload performance show`，请参见link:https://docs.netapp.com/us-en/ontap-cli/qos-statistics-workload-performance-show.html["ONTAP 命令参考"^]。

+
[NOTE]
====
从集群监控性能。请勿使用主机上的工具监控性能。

====
+
以下命令显示工作负载性能：

+
[listing]
----
cluster1::> qos statistics workload performance show
Workload          ID     IOPS      Throughput    Latency
--------------- ------ -------- ---------------- ----------
-total-              -    12320        47.84MB/s  1215.00us
app2-wid7967      7967     7219        28.20MB/s   319.00us
vs1-wid12279     12279     5026        19.63MB/s     2.52ms
_USERSPACE_APPS     14       55        10.92KB/s   236.00us
_Scan_Backgro..   5688       20            0KB/s        0ms
----
+
[NOTE]
====
您可以使用 `qos statistics workload latency show`命令查看QoS工作负载的详细延迟统计信息。有关的详细信息 `qos statistics workload latency show`，请参见link:https://docs.netapp.com/us-en/ontap-cli/qos-statistics-workload-latency-show.html["ONTAP 命令参考"^]。

====

