---
permalink: peering/add-svm-intercluster-relationship-93-later-task.html 
sidebar: sidebar 
keywords: add, intercluster, svm, peer, vserver peer create 
summary: 如果在配置集群对等关系后创建 SVM ，则需要手动为此 SVM 添加对等关系。您可以使用 vserver peer create 命令在 SVM 之间创建对等关系。创建对等关系后，您可以在远程集群上运行 Vserver peer accept 以授权对等关系。 
---
= 添加集群间 SVM 对等关系
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果在配置集群对等关系后创建 SVM ，则需要手动为此 SVM 添加对等关系。您可以使用 `vserver peer create` 命令在SVM之间创建对等关系。创建对等关系后、您可以运行 `vserver peer accept` 以授权对等关系。

.开始之前
源集群和目标集群必须建立对等关系。

.关于此任务
您可以在同一集群中的 SVM 之间创建对等关系，以便进行本地数据备份。有关详细信息，请参见 `vserver peer create` 手册页。

管理员偶尔会使用 `vserver peer reject` 命令以拒绝建议的SVM对等关系。如果SVM之间的关系位于中 `rejected` 状态、则必须先删除此关系、然后才能创建新关系。有关详细信息，请参见 `vserver peer delete` 手册页。

.步骤
. 在数据保护源集群上，与数据保护目标集群上的 SVM 创建对等关系：
+
`vserver peer create -vserver _local_SVM_ -peer-vserver _remote_SVM_ -applications snapmirror|file-copy|lun-copy -peer-cluster _remote_cluster_`

+
以下示例将在本地SVM之间创建对等关系``pvs1`` 和远程SVM``vs1``

+
[listing]
----
cluster01::> vserver peer create -vserver pvs1 -peer-vserver vs1 -applications snapmirror -peer-cluster cluster02
----
+
如果本地和远程 SVM 具有相同的名称，则必须使用 _local name_ 创建 SVM 对等关系：

+
[listing]
----
cluster01::> vserver peer create -vserver vs1 -peer-vserver
vs1 -applications snapmirror -peer-cluster cluster01
-local-name cluster1vs1LocallyUniqueName
----
. 在数据保护源集群上，验证是否已启动对等关系：
+
`vserver peer show-all`

+
有关完整的命令语法，请参见手册页。

+
以下示例显示了SVM之间的对等关系``pvs1`` 和SVM``vs1`` 已启动：

+
[listing]
----
cluster01::> vserver peer show-all
            Peer        Peer                      Peering
Vserver     Vserver     State      Peer Cluster   Applications
--------    --------    ---------  -------------  ------------
pvs1        vs1         initiated   Cluster02       snapmirror
----
. 在数据保护目标集群上，显示待定 SVM 对等关系：
+
`vserver peer show`

+
有关完整的命令语法，请参见手册页。

+
以下示例列出了的待定对等关系 `cluster02`：

+
[listing]
----
cluster02::> vserver peer show

                   Peer               Peer
Vserver            Vserver            State
-----------        -----------        ------------
vs1                pvs1               pending
----
. 在数据保护目标集群上，授权待定对等关系：
+
`vserver peer accept -vserver _local_SVM_ -peer-vserver _remote_SVM_`

+
有关完整的命令语法，请参见手册页。

+
以下示例将授权本地SVM之间的对等关系 `vs1` 和远程SVM `pvs1`：

+
[listing]
----
cluster02::> vserver peer accept -vserver vs1 -peer-vserver pvs1
----
. 验证 SVM 对等关系：
+
`vserver peer show`

+
[listing]
----
cluster01::> vserver peer show
            Peer        Peer                           Peering        Remote
Vserver     Vserver     State        Peer Cluster      Applications   Vserver
----------- ----------- ------------ ----------------- -------------- ---------
pvs1        vs1         peered       cluster02         snapmirror     vs1
----

