---
permalink: peering/configure-intercluster-lifs-share-data-ports-task.html 
sidebar: sidebar 
keywords: configure, intercluster, lifs, shared, data, ports 
summary: 您可以在与数据网络共享的端口上配置集群间 LIF 。这样可以减少集群间网络连接所需的端口数量。 
---
= 在共享数据端口上配置集群间 LIF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在与数据网络共享的端口上配置集群间 LIF 。这样可以减少集群间网络连接所需的端口数量。

.步骤
. 列出集群中的端口：
+
`network port show`

+
有关完整的命令语法，请参见手册页。

+
以下示例显示了 `cluster01` 中的网络端口：

+
[listing]
----

cluster01::> network port show
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
cluster01-01
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
cluster01-02
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
----
. 在系统 SVM 上创建集群间 LIF ：
+
|===
| 选项 | Description 


 a| 
* 在 ONTAP 9.6 及更高版本中： *
 a| 
`network interface create -vserver _system_svm_ -lif _LIF_name_ -service-policy default-intercluster -home-node _node_-home-port port -address _port_ip_ -netmask _netmask_`



 a| 
* 在 ONTAP 9.5 及更早版本中： *
 a| 
`network interface create -vserver _system_svm_ -lif _LIF_name_ -role intercluster -home-node _node_-home-port _port_ -address _port_ip_ -netmask _netmask_`

|===
+
有关完整的命令语法，请参见手册页。

+
以下示例将创建集群间 LIF `cluster01_icl01` 和 `cluster01_icl02` ：

+
[listing]
----

cluster01::> network interface create -vserver cluster01 -lif cluster01_icl01 -service-
policy default-intercluster -home-node cluster01-01 -home-port e0c -address 192.168.1.201
-netmask 255.255.255.0

cluster01::> network interface create -vserver cluster01 -lif cluster01_icl02 -service-
policy default-intercluster -home-node cluster01-02 -home-port e0c -address 192.168.1.202
-netmask 255.255.255.0
----
. 验证是否已创建集群间 LIF ：
+
|===
| 选项 | Description 


 a| 
* 在 ONTAP 9.6 及更高版本中： *
 a| 
`network interface show -service-policy default-intercluster`



 a| 
* 在 ONTAP 9.5 及更早版本中： *
 a| 
`network interface show -role intercluster`

|===
+
有关完整的命令语法，请参见手册页。

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
cluster01
            cluster01_icl01
                       up/up      192.168.1.201/24   cluster01-01  e0c     true
            cluster01_icl02
                       up/up      192.168.1.202/24   cluster01-02  e0c     true
----
. 验证集群间 LIF 是否冗余：
+
|===
| 选项 | Description 


 a| 
* 在 ONTAP 9.6 及更高版本中： *
 a| 
`network interface show – service-policy default-intercluster -failover`



 a| 
* 在 ONTAP 9.5 及更早版本中： *
 a| 
`network interface show -role intercluster -failover`

|===
+
有关完整的命令语法，请参见手册页。

+
以下示例显示 `e0c` 端口上的集群间 LIF `cluster01_icl01` 和 `cluster01_icl02` 将故障转移到 `e0d` 端口。

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster –failover
         Logical         Home                  Failover        Failover
Vserver  Interface       Node:Port             Policy          Group
-------- --------------- --------------------- --------------- --------
cluster01
         cluster01_icl01 cluster01-01:e0c   local-only      192.168.1.201/24
                            Failover Targets: cluster01-01:e0c,
                                              cluster01-01:e0d
         cluster01_icl02 cluster01-02:e0c   local-only      192.168.1.201/24
                            Failover Targets: cluster01-02:e0c,
                                              cluster01-02:e0d
----

