---
permalink: peering/configure-intercluster-lifs-use-ports-own-networks-task.html 
sidebar: sidebar 
keywords: configure, intercluster, LIFs  custom, ipspaces 
summary: 您可以在自定义 IP 空间中配置集群间 LIF 。这样可以在多租户环境中隔离复制流量。 
---
= 在自定义 IP 空间中配置集群间 LIF
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在自定义 IP 空间中配置集群间 LIF 。这样可以在多租户环境中隔离复制流量。

创建自定义 IP 空间时，系统会创建一个系统 Storage Virtual Machine （ SVM ），用作该 IP 空间中系统对象的容器。您可以使用新的 SVM 作为新 IP 空间中任何集群间 LIF 的容器。新的 SVM 与自定义 IP 空间同名。

.步骤
. 列出集群中的端口：
+
`network port show`

+
有关完整的命令语法，请参见手册页。

+
以下示例显示了 `cluster01` 中的网络端口：

+
[listing]
----

cluster01::> network port show
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
cluster01-01
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
       e0e       Default      Default          up     1500   auto/1000
       e0f       Default      Default          up     1500   auto/1000
cluster01-02
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
       e0e       Default      Default          up     1500   auto/1000
       e0f       Default      Default          up     1500   auto/1000
----
. 在集群上创建自定义 IP 空间：
+
`network ipspace create -ipspace _ipspace_`

+
以下示例将创建自定义 IP 空间 `ipspace-IC1` ：

+
[listing]
----
cluster01::> network ipspace create -ipspace ipspace-IC1
----
. 确定哪些端口可专用于集群间通信：
+
`network interface show -fields home-port ， curr-port`

+
有关完整的命令语法，请参见手册页。

+
以下示例显示未为端口 `e0e` 和 `e0f` 分配 LIF ：

+
[listing]
----

cluster01::> network interface show -fields home-port,curr-port
vserver lif                  home-port curr-port
------- -------------------- --------- ---------
Cluster cluster01_clus1   e0a       e0a
Cluster cluster01_clus2   e0b       e0b
Cluster cluster02_clus1   e0a       e0a
Cluster cluster02_clus2   e0b       e0b
cluster01
        cluster_mgmt         e0c       e0c
cluster01
        cluster01-01_mgmt1   e0c       e0c
cluster01
        cluster01-02_mgmt1   e0c       e0c
----
. 从默认广播域中删除可用端口：
+
`network port broadcast-domain remove-ports -broadcast-domain default -ports ports ports`

+
一个端口一次不能位于多个广播域中。有关完整的命令语法，请参见手册页。

+
以下示例将从默认广播域中删除端口 `e0e` 和 `e0f` ：

+
[listing]
----
cluster01::> network port broadcast-domain remove-ports -broadcast-domain Default -ports
cluster01-01:e0e,cluster01-01:e0f,cluster01-02:e0e,cluster01-02:e0f
----
. 验证端口是否已从默认广播域中删除：
+
`network port show`

+
有关完整的命令语法，请参见手册页。

+
以下示例显示已从默认广播域中删除端口 `e0e` 和 `e0f` ：

+
[listing]
----
cluster01::> network port show
                                                       Speed (Mbps)
Node   Port    IPspace   Broadcast Domain Link   MTU    Admin/Oper
------ ------- --------- --------------- ----- ------- ------------
cluster01-01
       e0a     Cluster    Cluster          up    9000  auto/1000
       e0b     Cluster    Cluster          up    9000  auto/1000
       e0c     Default    Default          up    1500  auto/1000
       e0d     Default    Default          up    1500  auto/1000
       e0e     Default    -                up    1500  auto/1000
       e0f     Default    -                up    1500  auto/1000
       e0g     Default    Default          up    1500  auto/1000
cluster01-02
       e0a     Cluster    Cluster          up    9000  auto/1000
       e0b     Cluster    Cluster          up    9000  auto/1000
       e0c     Default    Default          up    1500  auto/1000
       e0d     Default    Default          up    1500  auto/1000
       e0e     Default    -                up    1500  auto/1000
       e0f     Default    -                up    1500  auto/1000
       e0g     Default    Default          up    1500  auto/1000
----
. 在自定义 IP 空间中创建广播域：
+
`network port broadcast-domain create -ipspace _ipspace_-broadcast-domain _broadcast_domain_ -mtu _mtu _ -ports _ports_`

+
以下示例将在 IP 空间 `ipspace-IC1` 中创建广播域 `ipspace-IC1-bd` ：

+
[listing]
----
cluster01::> network port broadcast-domain create -ipspace ipspace-IC1 -broadcast-domain
ipspace-IC1-bd -mtu 1500 -ports cluster01-01:e0e,cluster01-01:e0f,
cluster01-02:e0e,cluster01-02:e0f
----
. 验证是否已创建广播域：
+
`network port broadcast-domain show`

+
有关完整的命令语法，请参见手册页。

+
[listing]
----
cluster01::> network port broadcast-domain show
IPspace Broadcast                                         Update
Name    Domain Name    MTU  Port List                     Status Details
------- ----------- ------  ----------------------------- --------------
Cluster Cluster       9000
                            cluster01-01:e0a              complete
                            cluster01-01:e0b              complete
                            cluster01-02:e0a              complete
                            cluster01-02:e0b              complete
Default Default       1500
                            cluster01-01:e0c              complete
                            cluster01-01:e0d              complete
                            cluster01-01:e0f              complete
                            cluster01-01:e0g              complete
                            cluster01-02:e0c              complete
                            cluster01-02:e0d              complete
                            cluster01-02:e0f              complete
                            cluster01-02:e0g              complete
ipspace-IC1
        ipspace-IC1-bd
                      1500
                            cluster01-01:e0e              complete
                            cluster01-01:e0f              complete
                            cluster01-02:e0e              complete
                            cluster01-02:e0f              complete
----
. 在系统 SVM 上创建集群间 LIF 并将其分配给广播域：
+
|===
| 选项 | Description 


 a| 
* 在 ONTAP 9.6 及更高版本中： *
 a| 
`network interface create -vserver _system_svm_ -lif _LIF_name_ -service-policy default-intercluster -home-node _node_-home-port _port_ -address _port_ip_ -netmask _netmask_`



 a| 
* 在 ONTAP 9.5 及更早版本中： *
 a| 
`network interface create -vserver _system_svm_ -lif _LIF_name_ -role intercluster -home-node _node_-home-port _port_ -address _port_ip_ -netmask _netmask_`

|===
+
此时将在分配主端口的广播域中创建 LIF 。此广播域具有一个默认故障转移组，其名称与此广播域相同。有关完整的命令语法，请参见手册页。

+
以下示例将在广播域 `ipspace-IC1-bd` 中创建集群间 LIF `cluster01_icl01` 和 `cluster01_icl02` ：

+
[listing]
----
cluster01::> network interface create -vserver ipspace-IC1 -lif cluster01_icl01 -service-
policy default-intercluster -home-node cluster01-01 -home-port e0e -address 192.168.1.201
-netmask 255.255.255.0

cluster01::> network interface create -vserver ipspace-IC1 -lif cluster01_icl02 -service-
policy default-intercluster -home-node cluster01-02 -home-port e0e -address 192.168.1.202
-netmask 255.255.255.0
----
. 验证是否已创建集群间 LIF ：
+
|===
| 选项 | Description 


 a| 
* 在 ONTAP 9.6 及更高版本中： *
 a| 
`network interface show -service-policy default-intercluster`



 a| 
* 在 ONTAP 9.5 及更早版本中： *
 a| 
`network interface show -role intercluster`

|===
+
有关完整的命令语法，请参见手册页。

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
ipspace-IC1
            cluster01_icl01
                       up/up      192.168.1.201/24   cluster01-01  e0e     true
            cluster01_icl02
                       up/up      192.168.1.202/24   cluster01-02  e0f     true
----
. 验证集群间 LIF 是否冗余：
+
|===
| 选项 | Description 


 a| 
* 在 ONTAP 9.6 及更高版本中： *
 a| 
`network interface show -service-policy default-intercluster -failover`



 a| 
* 在 ONTAP 9.5 及更早版本中： *
 a| 
`network interface show -role intercluster -failover`

|===
+
有关完整的命令语法，请参见手册页。

+
以下示例显示 SVM `e0e` 端口上的集群间 LIF `cluster01_icl01` 和 `cluster01_icl02` 故障转移到`e0f`端口：

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster –failover
         Logical         Home                  Failover        Failover
Vserver  Interface       Node:Port             Policy          Group
-------- --------------- --------------------- --------------- --------
ipspace-IC1
         cluster01_icl01 cluster01-01:e0e   local-only      intercluster01
                            Failover Targets:  cluster01-01:e0e,
                                               cluster01-01:e0f
         cluster01_icl02 cluster01-02:e0e   local-only      intercluster01
                            Failover Targets:  cluster01-02:e0e,
                                               cluster01-02:e0f
----

