---
permalink: peering/configure-intercluster-lifs-use-dedicated-ports-task.html 
sidebar: sidebar 
keywords: configure, intercluster, lifs, dedicated, ports 
summary: 您可以在专用端口上配置集群间 LIF 。这样做通常会增加复制流量的可用带宽。 
---
= 在专用端口上配置集群间 LIF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在专用端口上配置集群间 LIF 。这样做通常会增加复制流量的可用带宽。

.步骤
. 列出集群中的端口：
+
`network port show`

+
有关完整的命令语法，请参见手册页。

+
以下示例显示了 `cluster01` 中的网络端口：

+
[listing]
----

cluster01::> network port show
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
cluster01-01
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
       e0e       Default      Default          up     1500   auto/1000
       e0f       Default      Default          up     1500   auto/1000
cluster01-02
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
       e0e       Default      Default          up     1500   auto/1000
       e0f       Default      Default          up     1500   auto/1000
----
. 确定哪些端口可专用于集群间通信：
+
`network interface show -fields home-port ， curr-port`

+
有关完整的命令语法，请参见手册页。

+
以下示例显示未为端口 `e0e` 和 `e0f` 分配 LIF ：

+
[listing]
----

cluster01::> network interface show -fields home-port,curr-port
vserver lif                  home-port curr-port
------- -------------------- --------- ---------
Cluster cluster01-01_clus1   e0a       e0a
Cluster cluster01-01_clus2   e0b       e0b
Cluster cluster01-02_clus1   e0a       e0a
Cluster cluster01-02_clus2   e0b       e0b
cluster01
        cluster_mgmt         e0c       e0c
cluster01
        cluster01-01_mgmt1   e0c       e0c
cluster01
        cluster01-02_mgmt1   e0c       e0c
----
. 为专用端口创建故障转移组：
+
`network interface failover-groups create -vserver _system_svm_ -failover-group _failover_group_ -targets _physical_or_logical_ports_`

+
以下示例将端口 `e0e` 和 `e0f` 分配给系统 SVM `cluster01` 上的故障转移组 `intercluster01` ：

+
[listing]
----
cluster01::> network interface failover-groups create -vserver cluster01 -failover-group
intercluster01 -targets
cluster01-01:e0e,cluster01-01:e0f,cluster01-02:e0e,cluster01-02:e0f
----
. 验证是否已创建故障转移组：
+
`network interface failover-groups show`

+
有关完整的命令语法，请参见手册页。

+
[listing]
----
cluster01::> network interface failover-groups show
                                  Failover
Vserver          Group            Targets
---------------- ---------------- --------------------------------------------
Cluster
                 Cluster
                                  cluster01-01:e0a, cluster01-01:e0b,
                                  cluster01-02:e0a, cluster01-02:e0b
cluster01
                 Default
                                  cluster01-01:e0c, cluster01-01:e0d,
                                  cluster01-02:e0c, cluster01-02:e0d,
                                  cluster01-01:e0e, cluster01-01:e0f
                                  cluster01-02:e0e, cluster01-02:e0f
                 intercluster01
                                  cluster01-01:e0e, cluster01-01:e0f
                                  cluster01-02:e0e, cluster01-02:e0f
----
. 在系统 SVM 上创建集群间 LIF 并将其分配给故障转移组。
+
|===
| 选项 | Description 


 a| 
* 在 ONTAP 9.6 及更高版本中： *
 a| 
`network interface create -vserver _system_svm_ -lif _LIF_name_ -service-policy default-intercluster -home-node _node_-home-port _port_ -address _port_ip_ -netmask _netmask_ -failover-group _failover_group_`



 a| 
* 在 ONTAP 9.5 及更早版本中： *
 a| 
`network interface create -vserver _system_svm_ -lif _LIF_name_ -role intercluster -home-node _node_-home-port _port_ -address _port_ip_ -netmask _netmask_ -failover-group _failover_group_`

|===
+
有关完整的命令语法，请参见手册页。

+
以下示例将在故障转移组 `intercluster01` 中创建集群间 LIF `cluster01_icl01` 和 `cluster01_icl02` ：

+
[listing]
----
cluster01::> network interface create -vserver cluster01 -lif cluster01_icl01 -service-
policy default-intercluster -home-node cluster01-01 -home-port e0e -address 192.168.1.201
-netmask 255.255.255.0 -failover-group intercluster01

cluster01::> network interface create -vserver cluster01 -lif cluster01_icl02 -service-
policy default-intercluster -home-node cluster01-02 -home-port e0e -address 192.168.1.202
-netmask 255.255.255.0 -failover-group intercluster01
----
. 验证是否已创建集群间 LIF ：
+
|===
| 选项 | Description 


 a| 
* 在 ONTAP 9.6 及更高版本中： *
 a| 
`network interface show -service-policy default-intercluster`



 a| 
* 在 ONTAP 9.5 及更早版本中： *
 a| 
`network interface show -role intercluster`

|===
+
有关完整的命令语法，请参见手册页。

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
cluster01
            cluster01_icl01
                       up/up      192.168.1.201/24   cluster01-01  e0e     true
            cluster01_icl02
                       up/up      192.168.1.202/24   cluster01-02  e0f     true
----
. 验证集群间 LIF 是否冗余：
+
|===
| 选项 | Description 


 a| 
* 在 ONTAP 9.6 及更高版本中： *
 a| 
`network interface show -service-policy default-intercluster -failover`



 a| 
* 在 ONTAP 9.5 及更早版本中： *
 a| 
`network interface show -role intercluster -failover`

|===
+
有关完整的命令语法，请参见手册页。

+
以下示例显示 SVM``e0e`` 端口上的集群间 LIF `cluster01_icl01` 和 `cluster01_icl02` 将故障转移到 `e0f` 端口。

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster –failover
         Logical         Home                  Failover        Failover
Vserver  Interface       Node:Port             Policy          Group
-------- --------------- --------------------- --------------- --------
cluster01
         cluster01_icl01 cluster01-01:e0e   local-only      intercluster01
                            Failover Targets:  cluster01-01:e0e,
                                               cluster01-01:e0f
         cluster01_icl02 cluster01-02:e0e   local-only      intercluster01
                            Failover Targets:  cluster01-02:e0e,
                                               cluster01-02:e0f
----

