---
permalink: peering/create-cluster-relationship-92-earlier-task.html 
sidebar: sidebar 
keywords: create, cluster, peer, relationship 
summary: 您可以使用 cluster peer create 命令在本地和远程集群之间启动对等关系请求。在本地集群请求建立对等关系后，您可以在远程集群上运行 cluster peer create 以接受此关系。 
---
= 创建集群对等关系（ ONTAP 9.2 及更早版本）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `cluster peer create` 命令在本地和远程集群之间启动对等关系请求。在本地集群请求建立对等关系后，您可以在远程集群上运行 `cluster peer create` 来接受此关系。

.您需要什么？ #8217 ；将需要什么
* 您必须已在要建立对等关系的集群中的每个节点上创建集群间 LIF 。
* 集群管理员必须已就每个集群用于向另一集群进行身份验证的密码短语达成一致。


.步骤
. 在数据保护目标集群上，与数据保护源集群创建对等关系：
+
`cluster peer create -peer-addrs _peer_LIF_IPs_ -ipspace _ipspace_s`

+
如果您不使用自定义 IP 空间，则可以忽略 ` -ipspace` 选项。有关完整的命令语法，请参见手册页。

+
以下示例将与集群间 LIF IP 地址为 192.168.2.201 和 192.168.2.202 的远程集群创建集群对等关系：

+
[listing]
----
cluster02::> cluster peer create -peer-addrs 192.168.2.201,192.168.2.202
Enter the passphrase:
Please enter the passphrase again:
----
+
出现提示时，输入对等关系的密码短语。

. 在数据保护源集群上，对目标集群的源集群进行身份验证：
+
`cluster peer create -peer-addrs _peer_LIF_IPs_ -ipspace _ipspace_s`

+
有关完整的命令语法，请参见手册页。

+
以下示例将本地集群通过集群间 LIF IP 地址 192.140.112.203 和 192.140.112.204 的远程集群进行身份验证：

+
[listing]
----
cluster01::> cluster peer create -peer-addrs 192.168.2.203,192.168.2.204
Please confirm the passphrase:
Please confirm the passphrase again:
----
+
出现提示时，输入对等关系的密码短语。

. 验证是否已创建集群对等关系：
+
`cluster peer show – instance`

+
有关完整的命令语法，请参见手册页。

+
[listing]
----
cluster01::> cluster peer show –instance
Peer Cluster Name: cluster01
Remote Intercluster Addresses: 192.168.2.201,192.168.2.202
Availability: Available
Remote Cluster Name: cluster02
Active IP Addresses: 192.168.2.201,192.168.2.202
Cluster Serial Number: 1-80-000013
----
. 检查对等关系中节点的连接和状态：
+
`集群对等运行状况显示`

+
有关完整的命令语法，请参见手册页。

+
[listing]
----
cluster01::> cluster peer health show
Node       cluster-Name                Node-Name
             Ping-Status               RDB-Health Cluster-Health  Avail…
---------- --------------------------- ---------  --------------- --------
cluster01-01
           cluster02                   cluster02-01
             Data: interface_reachable
             ICMP: interface_reachable true       true            true
                                       cluster02-02
             Data: interface_reachable
             ICMP: interface_reachable true       true            true
cluster01-02
           cluster02                   cluster02-01
             Data: interface_reachable
             ICMP: interface_reachable true       true            true
                                       cluster02-02
             Data: interface_reachable
             ICMP: interface_reachable true       true            true
----

