---
permalink: peering/create-intercluster-svm-peer-relationship-93-later-task.html 
sidebar: sidebar 
keywords: create, intercluster, svm, peer, relationship 
summary: 您可以使用 vserver peer create 命令在本地和远程集群上的 SVM 之间创建对等关系。 
---
= 在ONTAP中创建集群间SVM对等关系
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `vserver peer create` 命令在本地集群和远程集群上的SVM之间创建对等关系。

.开始之前
* 源集群和目标集群必须建立对等关系。
* 集群必须运行 ONTAP 9.3 。（如果集群运行的是 ONTAP 9.2 或更早版本，请参阅中的过程 link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2494079["此归档文档"^]）
* 您必须为远程集群上的 SVM 建立 " 预先授权 " 对等关系。
+
有关详细信息，请参见 link:create-cluster-relationship-93-later-task.html["创建集群对等关系"]。



.关于此任务
在ONTAP 9.2及更早版本中、一次只能为一个SVM授权对等关系。这意味着您需要运行 `vserver peer accept` 命令。

从ONTAP 9.3开始、您可以通过在中列出SVM来对多个SVM的对等关系进行"预先授权" `-initial-allowed-vserver` 选项。有关详细信息，请参见 link:create-cluster-relationship-93-later-task.html["创建集群对等关系"]。

.步骤
. 在数据保护目标集群上，显示已预先授权建立对等关系的 SVM ：
+
`vserver peer permission show`

+
[listing]
----
cluster02::> vserver peer permission show
Peer Cluster         Vserver               Applications
-------------------  --------------------  --------------------
cluster02            vs1,vs2               snapmirror
----
. 在数据保护源集群上，创建与数据保护目标集群上预先授权的 SVM 的对等关系：
+
`vserver peer create -vserver _local_SVM_ -peer-vserver _remote_SVM_`

+
有关的详细信息 `vserver peer create`，请参见link:https://docs.netapp.com/us-en/ontap-cli/vserver-peer-create.html["ONTAP 命令参考"^]。

+
以下示例将在本地SVM之间创建对等关系 `pvs1` 和预先授权的远程SVM `vs1`：

+
[listing]
----
cluster01::> vserver peer create -vserver pvs1 -peer-vserver vs1
----
. 验证 SVM 对等关系：
+
`vserver peer show`

+
[listing]
----
cluster01::> vserver peer show
            Peer        Peer                           Peering        Remote
Vserver     Vserver     State        Peer Cluster      Applications   Vserver
----------- ----------- ------------ ----------------- -------------- ---------
pvs1        vs1         peered       cluster02         snapmirror     vs1
----

