---
permalink: san-admin/asa-iscsi-lif-fo-task.html 
sidebar: sidebar 
keywords: failover, iscsi, all san array, cli, system manager, auto-revert, revert network interface 
summary: 升级到ONTAP 9.11.1或更高版本后、您应在ONTAP 9.10.1或更早版本中创建的所有iSCSI LIF上手动启用自动LIF故障转移。 
---
= 启用或禁用自动iSCSI LIF故障转移
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
升级到ONTAP 9.11.1或更高版本后、您应在ONTAP 9.10.1或更早版本中创建的所有iSCSI LIF上手动启用自动LIF故障转移。

从ONTAP 9.11.1开始、您可以为全闪存SAN阵列平台上的iSCSI LIF启用自动LIF故障转移。如果发生存储故障转移、iSCSI LIF会自动从其主节点或端口迁移到其HA配对节点或端口、然后在故障转移完成后再迁移回。  或者、如果iSCSI LIF的端口运行状况不正常、则LIF会自动迁移到其当前主节点上运行状况良好的端口、然后在该端口恢复运行状况良好后、再迁移回其原始端口。  通过、在iSCSI上运行的SAN工作负载可以在发生故障转移后更快地恢复I/O服务。

默认情况下、在ONTAP 9.11.1及更高版本中、如果满足以下条件之一、则会为新创建的iSCSI LIF启用自动LIF故障转移：

* 此SVM上没有iSCSI LUN
* SVM上的所有iSCSI LIF均已启用自动LIF故障转移




== 启用自动iSCSI LIF故障转移

默认情况下、在ONTAP 9.10.1及更早版本中创建的iSCSI LIF不会启用自动LIF故障转移。  如果SVM上的iSCSI LIF未启用自动LIF故障转移、则新创建的LIF也不会启用自动LIF故障转移。  如果未启用自动LIF故障转移、并且发生了故障转移事件、则iSCSI LIF将不会迁移。

详细了解 link:../networking/configure_lifs_cluster_administrators_only_overview.html#lif-failover-and-giveback["LIF故障转移和恢复"]。

.步骤
. 为iSCSI LIF启用自动故障转移：
+
[source, cli]
----
network interface modify -vserver <SVM_name> -lif <iscsi_lif> -failover-policy sfo-partner-only -auto-revert true
----
+
要更新SVM上的所有iSCSI LUN、请使用 `-lif*` 而不是 `lif`。





== 禁用iSCSI LIF自动故障转移

如果您之前在ONTAP 9.10.1或更早版本中创建的iSCSI LIF上启用了自动iSCSI LIF故障转移、则可以选择将其禁用。

.步骤
. 禁用iSCSI LIF的自动故障转移：
+
[source, cli]
----
network interface modify -vserver <SVM_name> -lif <iscsi_lif> -failover-policy disabled -auto-revert false
----
+
要更新SVM上的所有iSCSI LUN、请使用 `-lif*` 而不是 `lif`。



.相关信息
* link:../networking/create_a_lif.html["创建 LIF"]
* 手动 link:../networking/migrate_a_lif.html["迁移LIF"]
* 手动 link:../networking/revert_a_lif_to_its_home_port.html["将LIF还原到其主端口"]
* link:../networking/configure_failover_settings_on_a_lif.html["在 LIF 上配置故障转移设置"]

