---
permalink: san-admin/backup-lun-host-backup-system-task.html 
sidebar: sidebar 
keywords: back up, lun, through, host, backup, system 
summary: 您可以使用快照中的克隆LUN作为主机备份系统的源数据。 
---
= 通过主机备份系统备份 LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用快照中的克隆LUN作为主机备份系统的源数据。

.开始之前
生产 LUN 必须存在并映射到包含应用程序服务器的 WWPN 或启动程序节点名称的 igroup 。此外， LUN 还必须进行格式化并可供主机访问

.步骤
. 将主机文件系统缓冲区的内容保存到磁盘。
+
您可以使用主机操作系统提供的命令，也可以使用适用于 Windows 的 SnapDrive 或适用于 UNIX 的 SnapDrive 。您也可以选择将此步骤加入 SAN 备份预处理脚本。

. 使用 `volume snapshot create`命令创建生产LUN的快照。
+
`volume snapshot create -vserver vs0 -volume vol3 -snapshot vol3_snapshot -comment "Single snapshot" -foreground false`

. 使用 `volume file clone create` 命令创建生产LUN的克隆。
+
`volume file clone create -vserver vs3 -volume vol3 -source-path lun1 -snapshot-name snap_vol3 -destination-path lun1_backup`

. 使用 `lun igroup create` 命令以创建包含备份服务器WWPN的igrop。
+
`lun igroup create -vserver vs3 -igroup igroup3 -protocol fc -ostype windows -initiator 10:00:00:00:c9:73:5b:91`

+
有关的详细信息 `lun igroup create`，请参见link:https://docs.netapp.com/us-en/ontap-cli/lun-igroup-create.html["ONTAP 命令参考"^]。

. 使用 `lun mapping create` 命令将步骤3中创建的LUN克隆映射到备份主机。
+
`lun mapping create -vserver vs3 -volume vol3 -lun lun1_backup -igroup igroup3`

+
您可以选择将此步骤加入到 SAN 备份应用程序的后处理脚本中。

+
有关的详细信息 `lun mapping create`，请参见link:https://docs.netapp.com/us-en/ontap-cli/lun-mapping-create.html["ONTAP 命令参考"^]。

. 在主机中，发现新的 LUN 并使文件系统可供主机使用。
+
您可以选择将此步骤加入到 SAN 备份应用程序的后处理脚本中。

. 使用 SAN 备份应用程序将 LUN 克隆中的数据从备份主机备份到磁带。
. 使用 `lun modify` 命令使LUN克隆脱机。
+
`lun modify -vserver vs3 -path /vol/vol3/lun1_backup -state offline`

+
有关的详细信息 `lun modify`，请参见link:https://docs.netapp.com/us-en/ontap-cli/lun-modify.html["ONTAP 命令参考"^]。

. 使用 `lun delete` 删除LUN克隆。
+
`lun delete -vserver vs3 -volume vol3 -lun lun1_backup`

+
有关的详细信息 `lun delete`，请参见link:https://docs.netapp.com/us-en/ontap-cli/lun-delete.html["ONTAP 命令参考"^]。

. 使用 `volume snapshot delete`命令删除快照。
+
`volume snapshot delete -vserver vs3 -volume vol3 -snapshot vol3_snapshot`


