---
permalink: san-admin/configure-fc-adapters-task.html 
sidebar: sidebar 
keywords: configure, fc, adapters, target, initiator, mode 
summary: 每个板载 FC 端口都可以单独配置为启动程序或目标。某些 FC 适配器上的端口也可以单独配置为目标端口或启动程序端口，就像板载 FC 端口一样。  
---
= 配置FC适配器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
每个板载 FC 端口都可以单独配置为启动程序或目标。某些 FC 适配器上的端口也可以单独配置为目标端口或启动程序端口，就像板载 FC 端口一样。中提供了可为目标模式配置的适配器列表 link:https://hwu.netapp.com["NetApp Hardware Universe"^]。

目标模式用于将端口连接到 FC 启动程序。启动程序模式用于通过 FlexArray 虚拟化或外部 LUN 导入（ FLI ）将端口连接到磁带驱动器，磁带库或第三方存储。

为 FC 协议和 FC-NVMe 协议配置 FC 适配器时，使用的步骤相同。但是，只有某些 FC 适配器支持 FC-NVMe 。请参见 link:https://hwu.netapp.com["NetApp Hardware Universe"^] 有关支持 FC-NVMe 协议的适配器的列表。



== 为目标模式配置 FC 适配器

.步骤
. 使适配器脱机：
+
`node run -node _node_name_ storage disable adapter _adapter_name_`

+
如果适配器未脱机，您也可以从系统上的相应适配器端口拔下缆线。

. 将适配器从启动程序更改为目标：
+
`system hardware unified-connect modify -t target -node _node_name_ adapter _adapter_name_`

. 重新启动托管已更改适配器的节点。
. 验证目标端口的配置是否正确：
+
`network fcp adapter show -node _node_name_`

+
有关的详细信息 `network fcp adapter show`，请参见link:https://docs.netapp.com/us-en/ontap-cli/network-fcp-adapter-show.html["ONTAP 命令参考"^]。

. 使适配器联机：
+
`network fcp adapter modify -node _node_name_ -adapter _adapter_port_ -state up`





== 为启动程序模式配置 FC 适配器

.开始之前
* 适配器上的 LIF 必须从其所属的任何端口集中删除。
* 在将物理端口的特性从目标更改为启动程序之前，必须迁移或销毁使用要修改的物理端口的每个 Storage Virtual Machine （ SVM ）中的所有 LIF 。


[NOTE]
====
NVMe/FC 支持启动程序模式。

====
.步骤
. 从适配器中删除所有 LIF ：
+
`network interface delete -vserver _SVM_name_ -lif _LIF_name,LIF_name_`

. 使适配器脱机：
+
`network fcp adapter modify -node _node_name_ -adapter _adapter_port_ -status-admin down`

+
如果适配器未脱机，您也可以从系统上的相应适配器端口拔下缆线。

. 将适配器从目标更改为启动程序：
+
`system hardware unified-connect modify -t initiator _adapter_port_`

. 重新启动托管已更改适配器的节点。
. 验证 FC 端口是否已配置为适用于您的配置的正确状态：
+
`system hardware unified-connect show`

. 将适配器恢复联机：
+
`node run -node _node_name_ storage enable adapter _adapter_port_`


