---
permalink: san-admin/control-monitor-io-performance-luns-qos-task.html 
sidebar: sidebar 
keywords: control, monitor, i/o, performance, luns, using, storage qos 
summary: 您可以通过将 LUN 分配给存储 QoS 策略组来控制 LUN 的输入 / 输出（ I/O ）性能。您可以控制 I/O 性能，以确保工作负载实现特定的性能目标，或者限制对其他工作负载产生负面影响的工作负载。 
---
= 使用存储 QoS 控制和监控 LUN 的 I/O 性能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以通过将 LUN 分配给存储 QoS 策略组来控制 LUN 的输入 / 输出（ I/O ）性能。您可以控制 I/O 性能，以确保工作负载实现特定的性能目标，或者限制对其他工作负载产生负面影响的工作负载。

.关于此任务
策略组强制实施最大吞吐量限制（例如 100 MB/ 秒）。您可以在不指定最大吞吐量的情况下创建策略组，从而可以在控制工作负载之前监控性能。

您还可以将具有 FlexVol 卷和 LUN 的 Storage Virtual Machine （ SVM ）分配给策略组。

在将 LUN 分配给策略组时，请注意以下要求：

* LUN 必须包含在策略组所属的 SVM 中。
+
您可以在创建策略组时指定 SVM 。

* 如果将 LUN 分配给策略组，则不能将 LUN 所在的卷或 SVM 分配给策略组。


有关如何使用存储 QoS 的详细信息，请参见 link:../system-admin/index.html["《系统管理参考》"]。

.步骤
. 使用 `qos policy-group create` 命令以创建策略组。
+
有关的详细信息 `qos policy-group create`，请参见link:https://docs.netapp.com/us-en/ontap-cli/qos-policy-group-create.html["ONTAP 命令参考"^]。

. 使用 `lun create` 命令或 `lun modify` 命令 `-qos-policy-group` 用于将LUN分配给策略组的参数。
+
有关的详细信息 `lun`，请参见link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=lun["ONTAP 命令参考"^]。

. 使用 `qos statistics` 用于查看性能数据的命令。
. 如有必要、请使用 `qos policy-group modify` 命令以调整策略组的最大吞吐量限制。
+
有关的详细信息 `qos policy-group modify`，请参见link:https://docs.netapp.com/us-en/ontap-cli/qos-policy-group-modify.html["ONTAP 命令参考"^]。


