---
permalink: san-admin/create-nvme-namespace-subsystem-task.html 
sidebar: sidebar 
keywords: create, nvme, namespace, subsystem 
summary: 对于使用 NVMe 协议的系统，您必须创建一个或多个 NVMe 命名空间和子系统。然后，可以将每个命名空间映射到 NVMe 子系统，以便从主机系统访问数据。 
---
= 配置 NVMe 存储
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果特定主机的操作步骤 不可用、您可以使用以下步骤为任何NVMe支持的主机创建命名空间并配置存储。

此操作步骤会在现有 Storage VM 上创建新的命名空间。必须为 Storage VM 配置 NVMe ，并且应已设置 FC 或 TCP 传输。

从 ONTAP 9.8 开始，在配置存储时，默认情况下会启用 QoS 。您可以在配置过程中或稍后时间禁用 QoS 或选择自定义 QoS 策略。

[role="tabbed-block"]
====
.System Manager
--
使用ONTAP System Manager (9.7及更高版本)创建命名空间以使用NVMe协议提供存储。

.步骤
. 在 System Manager 中，单击 * 存储 > NVMe 命名空间 * ，然后单击 * 添加 * 。
+
如果需要创建新子系统，请单击 * 更多选项 * 。

. 如果您运行的是 ONTAP 9.8 或更高版本，并且要禁用 QoS 或选择自定义 QoS 策略，请单击 * 更多选项 * ，然后在 * 存储和优化 * 下选择 * 性能服务级别 * 。
. 按 WWPN 对 FC 交换机进行分区。每个启动程序使用一个分区，并在每个分区中包含所有目标端口。
. 在主机上、发现新命名空间。
. 初始化命名空间并使用文件系统对其进行格式化。
. 验证主机是否可以在命名空间上写入和读取数据。


--
.命令行界面
--
使用ONTAP 命令行界面创建命名空间以使用NVMe协议提供存储。

此操作步骤 会在已配置NVMe协议的现有Storage VM上创建NVMe命名空间和子系统、然后将此命名空间映射到子系统、以便可以从主机系统访问数据。

如果需要为NVMe配置Storage VM、请参见 link:configure-svm-nvme-task.html["为 NVMe 配置 SVM"]。

.步骤
. 验证是否已为 NVMe 配置 SVM ：
+
[source, cli]
----
vserver show -vserver <svm_name> -fields allowed-protocols
----
+
`NVMe` 应显示在下 `allowed-protocols` 列。

. 创建 NVMe 命名空间：
+
[source, cli]
----
vserver nvme namespace create -vserver <svm_name> -path <path> -size <size_of_namespace> -ostype <OS_type>
----
. 创建 NVMe 子系统：
+
[source, cli]
----
vserver nvme subsystem create -vserver <svm_name> -subsystem <name_of_subsystem> -ostype <OS_type>
----
+
NVMe 子系统名称区分大小写。必须包含1到96个字符。允许使用特殊字符。

. 验证是否已创建子系统：
+
[source, cli]
----
vserver nvme subsystem show -vserver <svm_name>
----
+
。 `nvme` 子系统应显示在下 `Subsystem` 列。

. 从主机获取 NQN 。
. 将主机 NQN 添加到子系统：
+
[source, cli]
----
vserver nvme subsystem host add -vserver <svm_name> -subsystem <subsystem_name> -host-nqn <Host_NQN>
----
. 将命名空间映射到子系统：
+
[source, cli]
----
vserver nvme subsystem map add -vserver <svm_name> -subsystem <subsystem_name> -path <path>
----
+
一个命名空间只能映射到一个子系统。

. 验证命名空间是否已映射到子系统：
+
[source, cli]
----
vserver nvme namespace show -vserver <svm_name> -instance
----
+
此子系统应列为 `Attached subsystem`。



--
====