---
permalink: san-admin/host-side-management-concept.html 
sidebar: sidebar 
keywords: understand, host-side, space, management 
summary: 在精简配置环境中、主机端空间管理完成了从存储系统管理已在主机文件系统中释放的空间的过程。 
---
= SAN主机端空间管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在精简配置环境中、主机端空间管理完成了从存储系统管理已在主机文件系统中释放的空间的过程。

主机文件系统包含元数据，用于跟踪哪些块可用于存储新数据，哪些块包含不能覆盖的有效数据。此元数据存储在LUN或命名空间中。删除主机文件系统中的文件后，文件系统元数据将更新，以将该文件的块标记为可用空间。然后重新计算文件系统的总可用空间，以包括新释放的块。对于存储系统，这些元数据更新与主机执行的任何其他写入操作没有任何不同。因此，存储系统不会意识到发生了任何删除操作。

这会在主机报告的可用空间量与底层存储系统报告的可用空间量之间造成差异。例如，假设存储系统为主机分配了一个新配置的 200 GB LUN 。主机和存储系统均报告有 200 GB 的可用空间。然后，主机将写入 100 GB 的数据。此时，主机和存储系统均报告已用空间为 100 GB ，未用空间为 100 GB 。

然后，从主机中删除 50 GB 的数据。此时，主机将报告已用空间为 50 GB ，未用空间为 150 GB 。但是，您的存储系统将报告已用空间为 100 GB ，未用空间为 100 GB 。

主机端空间管理使用各种方法来协调主机和存储系统之间的空间差异。



== 使用 SnapCenter 简化主机管理

您可以使用 SnapCenter 软件简化与 iSCSI 和 FC 存储相关的某些管理和数据保护任务。SnapCenter 是一个适用于 Windows 和 UNIX 主机的可选管理软件包。

您可以使用 SnapCenter 软件从可分布在多个存储系统之间的存储池轻松创建虚拟磁盘，并自动执行存储配置任务，并简化从与主机数据一致的 Snapshot 副本创建 Snapshot 副本和克隆的过程。

有关的详细信息、请参见NetApp产品文档 https://docs.netapp.com/us-en/snapcenter/index.html["SnapCenter"]。

.相关链接
link:enable-space-allocation-scsi-thin-provisioned-luns-task.html["为SAN协议启用ONTAP空间分配"]
