---
permalink: san-admin/manage-nvme-concept.html 
sidebar: sidebar 
keywords: manage, nvme, overview, license 
summary: 从 ONTAP 9.4 开始，支持 NVMe/FC 。从 ONTAP 9.5 开始，需要许可证才能支持 NVMe 。如果在 ONTAP 9.4 中启用了 NVMe ，则在升级到 ONTAP 9.5 之后，可以在 90 天的宽限期内获取许可证。 
---
= NVMe 概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
从ONTAP 9.4开始、非MetroCluster AFF 配置支持NVMe/FC。从ONTAP 9.9.1开始、所有非MetroCluster AFF 全SAN阵列(ASA)配置也支持NVMe/FC

您可以使用非易失性内存快速（ NVMe ）协议在 SAN 环境中提供存储。NVMe 协议针对固态存储的性能进行了优化。

对于 NVMe ，存储目标称为命名空间。NVMe 命名空间是指可格式化为逻辑块并作为标准块设备提供给主机的非易失性存储数量。您可以创建命名空间和子系统，然后将命名空间映射到子系统，类似于配置 LUN 并将其映射到 FC 和 iSCSI 的 igroup 的方式。

NVMe 目标通过使用 FC 交换机的标准 FC 基础架构或使用以太网交换机和主机端适配器的标准 TCP 基础架构连接到网络。

支持以下 NVMe 协议：

[cols="3*"]
|===


| 协议 | 开头为 ... | 允许者 ... 


| TCP | ONTAP 9.10.1 | Default 


| FCP | ONTAP 9.4 | Default 
|===


== NVMe许可证要求

从 ONTAP 9.5 开始，需要许可证才能支持 NVMe 。如果在 ONTAP 9.4 中启用了 NVMe ，则在升级到 ONTAP 9.5 之后，可以在 90 天的宽限期内获取许可证。

您可以使用以下命令启用许可证：

`ssystem license add -license-code _nva_license_key_`



== 什么是 NVMe

非易失性内存快速（ NVMe ）协议是一种用于访问非易失性存储介质的传输协议。

基于网络结构的 NVMe （ NVMeoF ）是 NVMe 的一个规范定义扩展，支持通过 PCIe 以外的连接进行基于 NVMe 的通信。此接口允许将外部存储机箱连接到服务器。

NVMe 旨在提供对使用非易失性内存构建的存储设备的高效访问，从闪存技术到性能更高的持久性内存技术。因此，它的限制与为硬盘驱动器设计的存储协议不同。闪存和固态设备（ SSD ）是一种非易失性内存（ NVM ）。NVM 是一种在断电期间保留其内容的内存。您可以通过 NVMe 访问该内存。

NVMe 的优势包括提高了数据传输的速度，工作效率，吞吐量和容量。具体特征如下：

* NVMe 的设计可支持多达 64 ， 000 个队列。
+
反过来，每个队列最多可以有 64 ， 000 个并发命令。

* 多家硬件和软件供应商均支持 NVMe
* NMVe 利用闪存技术提高了工作效率，从而加快了响应速度
* NVMe 支持对发送到 SSD 的每个 "n `request` " 发出多个数据请求。
+
NVMe 对 " `request` " 进行解码所需时间更短，并且在多线程程序中不需要线程锁定。

* NVMe 支持防止 CPU 级别出现瓶颈的功能，并可随着系统扩展实现大规模可扩展性


.相关信息
* link:../task_nvme_provision_suse_linux.html["为 SUSE Linux 配置 NVMe 存储"]
* link:san-admin/configure-svm-nvme-task.html["为NVMe配置Storage VM"]

