---
permalink: san-admin/manage-nvme-concept.html 
sidebar: sidebar 
keywords: manage, nvme, overview, license 
summary: 您可以使用非易失性内存快速（ NVMe ）协议在 SAN 环境中提供存储。NVMe 协议针对固态存储的性能进行了优化。 
---
= NVMe 概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用非易失性内存快速（ NVMe ）协议在 SAN 环境中提供存储。NVMe 协议针对固态存储的性能进行了优化。

对于 NVMe ，存储目标称为命名空间。NVMe 命名空间是指可格式化为逻辑块并作为标准块设备提供给主机的非易失性存储数量。您可以创建命名空间和子系统，然后将命名空间映射到子系统，类似于配置 LUN 并将其映射到 FC 和 iSCSI 的 igroup 的方式。

NVMe 目标通过使用 FC 交换机的标准 FC 基础架构或使用以太网交换机和主机端适配器的标准 TCP 基础架构连接到网络。

根据您的ONTAP 版本、对NVMe的支持会有所不同。请参见 link:../nvme/support-limitations.html["NVMe支持和限制"] 了解详细信息。



== 什么是 NVMe

非易失性内存快速（ NVMe ）协议是一种用于访问非易失性存储介质的传输协议。

基于网络结构的 NVMe （ NVMeoF ）是 NVMe 的一个规范定义扩展，支持通过 PCIe 以外的连接进行基于 NVMe 的通信。此接口允许将外部存储机箱连接到服务器。

NVMe 旨在提供对使用非易失性内存构建的存储设备的高效访问，从闪存技术到性能更高的持久性内存技术。因此，它的限制与为硬盘驱动器设计的存储协议不同。闪存和固态设备（ SSD ）是一种非易失性内存（ NVM ）。NVM 是一种在断电期间保留其内容的内存。您可以通过 NVMe 访问该内存。

NVMe 的优势包括提高了数据传输的速度，工作效率，吞吐量和容量。具体特征如下：

* NVMe 的设计可支持多达 64 ， 000 个队列。
+
反过来，每个队列最多可以有 64 ， 000 个并发命令。

* 多家硬件和软件供应商均支持 NVMe
* NMVe 利用闪存技术提高了工作效率，从而加快了响应速度
* NVMe 支持对发送到 SSD 的每个 "n `request` " 发出多个数据请求。
+
NVMe 对 " `request` " 进行解码所需时间更短，并且在多线程程序中不需要线程锁定。

* NVMe支持防止CPU级别出现瓶颈的功能、并可随着系统扩展实现大规模可扩展性。




== 关于 NVMe 命名空间

NVMe 命名空间是指可格式化为逻辑块的非易失性内存（ NVM ）数量。如果为 Storage Virtual Machine 配置了 NVMe 协议，并且命名空间相当于 FC 和 iSCSI 协议的 LUN ，则会使用命名空间。

配置一个或多个命名空间并将其连接到 NVMe 主机。每个命名空间可以支持不同的块大小。

通过 NVMe 协议，可以通过多个控制器访问命名空间。使用大多数操作系统都支持的 NVMe 驱动程序，固态驱动器（ SSD ）命名空间会显示为标准块设备，可以在这些设备上部署文件系统和应用程序，而无需任何修改。

命名空间 ID （ NSID ）是控制器用来提供对命名空间访问的标识符。在为主机或主机组设置 NSID 时，您还可以配置主机对卷的可访问性。逻辑块一次只能映射到一个主机组，而给定主机组不具有任何重复的 NSID 。



== 关于 NVMe 子系统

NVMe 子系统包括一个或多个 NVMe 控制器，命名空间， NVM 子系统端口，一个 NVM 存储介质以及一个控制器与 NVM 存储介质之间的接口。创建NVMe命名空间时、默认情况下不会将其映射到子系统。您也可以选择将其映射为新的或现有的子系统。

.相关信息
* link:../task_nvme_provision_suse_linux.html["为 SUSE Linux 配置 NVMe 存储"]
* link:create-nvme-namespace-subsystem-task.html["为其他主机配置NVMe存储"]
* link:map-nvme-namespace-subsystem-task.html["将 NVMe 命名空间映射到子系统"]

