---
permalink: san-admin/microsoft-offloaded-data-transfer-odx-concept.html 
sidebar: sidebar 
keywords: microsoft, offloaded, data, transfer, odx 
summary: Microsoft 卸载数据传输（ Offloaded Data Transfer ， ODX ）也称为副本卸载，可在存储设备内部或兼容存储设备之间直接传输数据，而无需通过主机计算机传输数据。 
---
= Microsoft 卸载数据传输（ Offloaded Data Transfer ， ODX ）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Microsoft 卸载数据传输（ Offloaded Data Transfer ， ODX ）也称为 _copy ofload_ ，可在存储设备内部或兼容存储设备之间直接传输数据，而无需通过主机计算机传输数据。

ONTAP支持对SMB和SAN协议使用ODX。

在非 ODX 文件传输中，数据将从源读取，并通过网络传输到主机。主机通过网络将数据传输回目标。在 ODX 文件传输中，数据会直接从源复制到目标，而无需通过主机。

由于ODX卸载副本是直接在源和目标之间执行的、因此、如果在同一卷中执行副本、则可以获得显著的性能优势、包括加快相同卷副本的复制速度、降低客户端上的CPU和内存利用率以及降低网络I/O带宽利用率。如果副本跨卷、则与基于主机的副本相比、性能可能不会显著提高。

对于 SAN 环境，只有当主机和存储系统都支持 ODX 时， ODX 才可用。支持 ODX 且启用了 ODX 的客户端计算机在移动或复制文件时会自动透明地使用卸载文件传输。无论您是通过 Windows 资源管理器拖放文件还是使用命令行文件复制命令，还是客户端应用程序启动文件复制请求，系统都会使用 ODX 。



== 使用 ODX 的要求

如果您计划使用 ODX 进行副本卸载，则需要熟悉卷支持注意事项，系统要求和软件功能要求。

要使用 ODX ，您的系统必须具备以下条件：

* ONTAP
+
ODX 会在支持的 ONTAP 版本中自动启用。

* 源卷最小为 2 GB
+
为了获得最佳性能，源卷应大于 260 GB 。

* Windows 客户端上的 ODX 支持
+
Windows Server 2012 或更高版本以及 Windows 8 或更高版本均支持 ODX 。互操作性表包含有关受支持的 Windows 客户端的最新信息。

+
https://mysupport.netapp.com/matrix["NetApp 互操作性表工具"^]

* ODX 的复制应用程序支持
+
执行数据传输的应用程序必须支持 ODX 。支持 ODX 的应用程序操作包括：

+
** Hyper-V 管理操作，例如创建和转换虚拟硬盘（ VHD ），管理 Snapshot 副本以及在虚拟机之间复制文件
** Windows 资源管理器操作
** Windows PowerShell copy 命令
** Windows 命令提示符复制命令
Microsoft TechNet库包含有关Windows服务器和客户端上支持的ODX应用程序的详细信息。


* 如果使用的是压缩卷，则压缩组大小必须为 8K 。
+
不支持 32 K 压缩组大小。



ODX 不适用于以下卷类型：

* 容量小于 2 GB 的源卷
* 只读卷
* link:../flexcache/supported-unsupported-features-concept.html["FlexCache 卷"]
+

NOTE:  FlexCache初始卷支持ODX。

* link:../san-admin/san-volumes-concept.html#semi-thick-provisioning-for-volumes["半厚配置卷"]




== 特殊的系统文件要求

您可以删除在 qtree 中找到的 ODX 文件。请勿删除或修改任何其他ODX系统文件、除非技术支持要求您这样做。

使用 ODX 功能时，系统的每个卷中都存在 ODX 系统文件。这些文件可以对 ODX 传输期间使用的数据进行时间点表示。以下系统文件位于包含 LUN 或将数据卸载到的文件的每个卷的根级别：

* `.copy-offload` (隐藏目录)
* `.tokens` (文件位于隐藏的下 `.copy-offload` 目录)


您可以使用 `copy-offload delete-tokens -path dir_path -node _node_name_` 用于删除包含ODX文件的qtree的命令。



== ODX 的用例

您应了解在 SVM 上使用 ODX 的使用情形，以便确定 ODX 在何种情况下可为您带来性能优势。

支持 ODX 的 Windows 服务器和客户端会使用副本卸载作为在远程服务器之间复制数据的默认方式。如果 Windows 服务器或客户端不支持 ODX ，或者 ODX 副本卸载在任何时刻失败，则复制或移动操作将回退为复制或移动操作的传统读写操作。

以下使用情形支持使用 ODX 副本和移动：

* 卷内
+
源文件或 LUN 与目标文件或 LUN 位于同一个卷中。

* 卷间，同一节点，同一 SVM
+
源文件或 LUN 和目标文件或 LUN 位于同一节点上的不同卷上。数据属于同一个 SVM 。

* 卷间，不同节点，相同 SVM
+
源文件或 LUN 和目标文件或 LUN 位于不同节点上的不同卷上。数据属于同一个 SVM 。

* SVM 间，同一节点
+
源和目标文件或 LUN 位于同一节点上的不同卷上。数据属于不同的 SVM 。

* SVM 间，不同节点
+
源和目标文件或 LUN 位于不同节点上的不同卷上。数据属于不同的 SVM 。

* 集群间
+
源 LUN 和目标 LUN 位于集群中不同节点上的不同卷上。只有SAN支持此功能、SMB不支持此功能。



还有一些其他特殊使用情形：

* 在 ONTAP ODX 实施中，您可以使用 ODX 在 SMB 共享与 FC 或 iSCSI 连接的虚拟驱动器之间复制文件。
+
您可以使用 Windows 资源管理器， Windows 命令行界面或 PowerShell ， Hyper-V 或其他支持 ODX 的应用程序，在 SMB 共享和连接的 LUN 之间使用 ODX 副本卸载功能无缝复制或移动文件，但前提是 SMB 共享和 LUN 位于同一集群上。

* Hyper-V 还提供了一些 ODX 副本卸载的其他使用情形：
+
** 您可以使用 ODX 副本卸载直通与 Hyper-V 在虚拟硬盘（ VHD ）文件内部或之间复制数据，或者在同一集群中映射的 SMB 共享和连接的 iSCSI LUN 之间复制数据。
+
这样，子操作系统中的副本就可以传递到底层存储。

** 创建固定大小的 VHD 时， ODX 用于使用众所周知的置零令牌以零初始化磁盘。
** 如果源存储和目标存储位于同一集群上，则使用 ODX 副本卸载进行虚拟机存储迁移。


+
[NOTE]
====
要利用 Hyper-V ODX 副本卸载直通的使用情形，子操作系统必须支持 ODX ，而子操作系统的磁盘必须是 SCSI 磁盘，并由支持 ODX 的存储（ SMB 或 SAN ）提供支持。子操作系统上的 IDE 磁盘不支持 ODX 直通。

====

