---
permalink: san-admin/modify-slm-reporting-nodes-task.html 
sidebar: sidebar 
keywords: modify, slm, reporting-nodes, list 
summary: 如果要将 LUN 或包含 LUN 的卷移动到同一集群中的另一个高可用性（ HA ）对，则应在启动移动之前修改选择性 LUN 映射（ SLM ）报告节点列表，以确保活动的优化 LUN 路径保持不变。 
---
= 修改 SLM 报告节点列表
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果要将 LUN 或包含 LUN 的卷移动到同一集群中的另一个高可用性（ HA ）对，则应在启动移动之前修改选择性 LUN 映射（ SLM ）报告节点列表，以确保活动的优化 LUN 路径保持不变。

.步骤
. 将目标节点及其配对节点添加到聚合或卷的报告节点列表中：
+
`lun mapping add-reporting-nodes -vserver _vserver_name_ -path _lun_path_ -igroup _igroup_name_ [-destination-aggregate _aggregate_name_|-destination-volume _volume_name_]`

+
如果您的命名约定一致、则可以使用同时修改多个LUN映射 `*-igroup*` 而不是 `igroup`。

. 重新扫描主机以发现新添加的路径。
. 如果操作系统需要，请将新路径添加到多路径网络 I/O （ MPIO ）配置中。
. 对所需的移动操作运行命令，然后等待操作完成。
. 验证是否正在通过主动 / 优化路径处理 I/O ：
+
`lun mapping show -fields reporting-nodes`

. 从报告节点列表中删除先前的 LUN 所有者及其配对节点：
+
`lun mapping remove-reporting-nodes -vserver _vserver_name_ -path _lun_path_ -igroup _igroup_name_ -remote-nodes`

. 验证是否已从现有 LUN 映射中删除此 LUN ：
+
`lun mapping show -fields reporting-nodes`

. 删除主机操作系统的任何陈旧设备条目。
. 根据需要更改任何多路径配置文件。
. 重新扫描主机以验证是否删除了旧路径。+
有关重新扫描主机的具体步骤，请参见主机文档。

