---
permalink: san-admin/move-san-lifs-task.html 
sidebar: sidebar 
keywords: move, san, lifs 
summary: 如果节点需要脱机，则可以移动 SAN LIF 以保留其配置信息（例如其 WWPN），并避免重新分区交换机结构。 
---
= 移动 ONTAP SAN LIF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果需要使节点脱机，则可以移动 SAN LIF 以保留其配置信息，例如其 WWPN。移动 LIF 不需要重新分区 FC 结构或在群集主机和目标接口之间创建新的 iSCSI 会话。您可以将 SAN LIF 移动到群集中的任何节点，但不能在存储虚拟机 (SVM) 之间移动。

您可以移动 LIF 以无中断地执行以下操作：

* 以对访问 LUN 或命名空间数据的主机透明的方式，用升级后的 HA 对替换群集中的一个 HA 对
* 升级目标接口卡
* 将 Storage Virtual Machine （ SVM ）的资源从集群中的一组节点移至集群中的另一组节点


您不能使用 `network interface move`命令移动 SAN LIF。要移动 SAN LIF，您必须将其脱机，将其移动到新的主节点或端口，然后将其重新联机。由于 SAN LIF 在移动之前必须离线，因此主机流量必须依靠主机多路径软件来提供对 LUN 的无中断访问，这样就不会出现 I/O 中断。

.开始之前
如果 LIF 是端口集的成员，则必须先从端口集中删除 LIF ，然后才能将 LIF 移动到其他节点。

.关于此任务
要移动的 LIF 的目标节点和物理端口必须位于同一个 FC 网络结构或以太网网络上。如果将 LIF 移动到尚未正确分区的其他网络结构，或者将 LIF 移动到 iSCSI 启动程序与目标之间没有连接的以太网网络，则在将 LUN 恢复联机后将无法访问。

.步骤
. 查看 LIF 的管理和运行状态：
+
[source, cli]
----
network interface show -vserver <SVM_name>
----
+
有关的详细信息 `network interface show`，请参见link:https://docs.netapp.com/us-en/ontap-cli/network-interface-show.html["ONTAP 命令参考"^]。

. 将LIF的状态更改为 `down` (脱机)：
+
[source, cli]
----
network interface modify -vserver <SVM_name> -lif <LIF_name> -status-admin down
----
+
有关的详细信息 `network interface modify`，请参见link:https://docs.netapp.com/us-en/ontap-cli/network-interface-modify.html["ONTAP 命令参考"^]。

. 为 LIF 分配一个新节点和端口：
+
[source, cli]
----
network interface modify -vserver <SVM_name> -lif <LIF_name> -home-node <node_name> -home-port <port_name>
----
. 将LIF的状态更改为 `up` (联机)：
+
[source, cli]
----
network interface modify -vserver <SVM_name> -lif <LIF_name> -status-admin up
----
. 验证所做的更改：
+
[source, cli]
----
network interface show -vserver <SVM_name>
----

