---
permalink: san-admin/nvme-namespaces-considerations-concept.html 
sidebar: sidebar 
keywords: nvme, namespaces, considerations, provisioning 
summary: 要在 SAN 环境中设置 NVMe 协议，您必须为 NVMe 配置 SVM ，创建命名空间和子系统，配置 NVMe/FC LIF ，然后将命名空间映射到子系统。 
---
= NVMe 命名空间注意事项
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
要在 SAN 环境中设置 NVMe 协议，您必须为 NVMe 配置 SVM ，创建命名空间和子系统，配置 NVMe/FC LIF ，然后将命名空间映射到子系统。使用 NVMe 命名空间时，您应注意一些注意事项。

* 如果 LUN 中的数据丢失，则无法从命名空间还原数据，反之亦然。
* 命名空间的空间保证与所属卷的空间保证相同。
* 从 ONTAP 9.6 开始，命名空间支持 512 字节块和 4096 字节块。
+
默认值为 4096 。只有当主机操作系统不支持 4096 字节块时，才应使用 512 。

* 命名空间不支持以下内容：
+
** 正在重命名
+
您不能重命名命名空间。

** 卷间移动
** 卷间副本




从 ONTAP 9.10.1 开始，您可以 xref:../nvme/resize-namespace-task.html[调整命名空间大小]。ONTAP 9.10.1 之前的版本不支持调整命名空间大小。



== 关于 NVMe 命名空间

NVMe 命名空间是指可格式化为逻辑块的非易失性内存（ NVM ）数量。如果为 Storage Virtual Machine 配置了 NVMe 协议，并且命名空间相当于 FC 和 iSCSI 协议的 LUN ，则会使用命名空间。

配置一个或多个命名空间并将其连接到 NVMe 主机。每个命名空间可以支持不同的块大小。

通过 NVMe 协议，可以通过多个控制器访问命名空间。使用大多数操作系统都支持的 NVMe 驱动程序，固态驱动器（ SSD ）命名空间会显示为标准块设备，可以在这些设备上部署文件系统和应用程序，而无需任何修改。

命名空间 ID （ NSID ）是控制器用来提供对命名空间访问的标识符。在为主机或主机组设置 NSID 时，您还可以配置主机对卷的可访问性。逻辑块一次只能映射到一个主机组，而给定主机组不具有任何重复的 NSID 。



=== NVMe 命名空间的 NVMe 子系统配置

NVMe 子系统包括一个或多个 NVMe 控制器，命名空间， NVM 子系统端口，一个 NVM 存储介质以及一个控制器与 NVM 存储介质之间的接口。创建 NVMe 命名空间时，您可以选择将 NVMe 子系统映射到命名空间，如下所示：

* * 无（默认） * + 无 NVMe 子系统映射到命名空间。
* * 现有子系统 * + 您可以选择一个现有 NVMe 子系统以映射到命名空间。NVMe 子系统会根据主机操作系统和 SVM 字段列出。将指针悬停在 NVMe 子系统名称上时，将显示有关此子系统的更多详细信息。
* * 新子系统 * + 您可以创建新的 NVMe 子系统并将其映射到命名空间。在主机操作系统和 SVM 上创建子系统。


您可以通过提供以下详细信息来配置子系统：

* * NVMe 子系统名称 * + NVMe 子系统名称区分大小写。必须包含 1 到 96 个字符，并且允许使用特殊字符。
* * 主机操作系统 * + 要创建子系统的主机操作系统类型。
* * 主机 NQN* + 连接到控制器的主机 NVMe 限定名称。此列可以包含逗号分隔值，因为一个子系统可能连接一个或多个主机。

