---
permalink: san-admin/prevent-flexclone-file-lun-deleted-task.html 
sidebar: sidebar 
keywords: prevent, specific, flexclone file, flexclone lun, automatically, deleted 
summary: 如果将 FlexVol 卷配置为自动删除 FlexClone 文件和 FlexClone LUN ，则符合指定条件的任何克隆都可能被删除。如果您要保留特定的 FlexClone 文件或 FlexClone LUN ，则可以将其从自动 FlexClone 删除过程中排除。 
---
= 防止自动删除特定的 FlexClone 文件或 FlexClone LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果将 FlexVol 卷配置为自动删除 FlexClone 文件和 FlexClone LUN ，则符合指定条件的任何克隆都可能被删除。如果您要保留特定的 FlexClone 文件或 FlexClone LUN ，则可以将其从自动 FlexClone 删除过程中排除。

.您需要的内容
必须安装 FlexClone 许可证。此许可证包含在中 link:https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP One"]。

.关于此任务
创建 FlexClone 文件或 FlexClone LUN 时，默认情况下会禁用克隆的自动删除设置。如果将 FlexVol 卷配置为自动删除克隆以回收卷上的空间，则禁用了自动删除的 FlexClone 文件和 FlexClone LUN 会保留下来。

[NOTE]
====
如果您设置了 `commitment` 将卷上的级别调到 `try` 或 `disrupt`，您可以通过禁用特定FlexClone文件或FlexClone LUN的自动删除来单独保留这些克隆。但是、如果您设置了 `commitment` 将卷上的级别调到 `destroy` 销毁列表包括 `lun_clone,file_clone`、卷设置将覆盖克隆设置、无论克隆的自动删除设置如何、所有FlexClone文件和FlexClone LUN均可删除。

====
.步骤
. 使用防止自动删除特定FlexClone文件或FlexClone LUN `volume file clone autodelete` 命令：
+
以下示例显示了如何为 vol1 中包含的 FlexClone LUN lun1_clone 禁用自动删除：

+
[listing]
----
cluster1::> volume file clone autodelete -vserver vs1 -volume vol1 -clone-path lun1_clone -enable false
----
+
无法自动删除已禁用自动删除的 FlexClone 文件或 FlexClone LUN 以回收卷上的空间。

. 使用验证是否已为FlexClone文件或FlexClone LUN禁用自动删除 `volume file clone show-autodelete` 命令：
+
以下示例显示了 FlexClone LUN lun1_clone 的自动删除为 false ：

+
[listing]
----
cluster1::> volume file clone show-autodelete -vserver vs1 -clone-path vol/vol1/lun1_clone
															Vserver Name: vs1
															Clone Path: vol/vol1/lun1_clone
															Autodelete Enabled: false
----

