---
permalink: san-admin/register-svm-isns-server-task.html 
sidebar: sidebar 
keywords: register, svm, isns, server 
summary: 您可以使用 vserver iscsi isns 命令将 Storage Virtual Machine （ SVM ）配置为向 iSNS 服务器注册。 
---
= 将 SVM 注册到 iSNS 服务器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `vserver iscsi isns` 命令将 Storage Virtual Machine （ SVM ）配置为向 iSNS 服务器注册。

.关于此任务
`vserver iscsi isns create` 命令可将 SVM 配置为向 iSNS 服务器注册。SVM 不提供可用于配置或管理 iSNS 服务器的命令。要管理 iSNS 服务器，您可以使用服务器管理工具或 iSNS 服务器供应商提供的接口。

.步骤
. 在 iSNS 服务器上，确保 iSNS 服务已启动且可提供服务。
. 在数据端口上创建 SVM 管理 LIF ：
+
`network interface create -vserver _svm_name_ -lif _lif_name_ -role data -data-protocol none -home-node _home_node_name_ -home-port _home_port_ -address _ip_address_ -netmask _network_mask_`

. 如果 SVM 上尚不存在 iSCSI 服务，请创建此服务：
+
`vserver iscsi create -vserver _svm_name_`

. 验证是否已成功创建 iSCSI 服务：
+
`iscsi show -vserver _svm_name_`

. 验证 SVM 是否存在默认路由：
+
`network route show -vserver _svm_name_`

. 如果 SVM 不存在默认路由，请创建默认路由：
+
`network route create -vserver _svm_name_ -destination _destination_-gateway _gateway_`

. 将 SVM 配置为向 iSNS 服务注册：
+
`vserver iscsi isns create -vserver _svm_name_ -address _ip_address_`

+
IPv4 和 IPv6 地址系列均受支持。iSNS 服务器的地址系列必须与 SVM 管理 LIF 的地址系列相同。

+
例如，您不能将具有 IPv4 地址的 SVM 管理 LIF 连接到具有 IPv6 地址的 iSNS 服务器。

. 验证 iSNS 服务是否正在运行：
+
`vserver iscsi isns show -vserver _svm_name_`

. 如果 iSNS 服务未运行，请启动它：
+
`vserver iscsi isns start -vserver _svm_name_`


