---
permalink: san-admin/selective-lun-map-concept.html 
sidebar: sidebar 
keywords: select, selective, lun, map, slm, enabled, modify, reporting, nodes, list 
summary: 选择性 LUN 映射（ SLM ）可减少从主机到 LUN 的路径数。使用 SLM ，创建新的 LUN 映射后，只能通过 LUN 所属节点及其 HA 配对节点上的路径访问此 LUN 。 
---
= 选择性 LUN 映射概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
选择性 LUN 映射（ SLM ）可减少从主机到 LUN 的路径数。使用 SLM ，创建新的 LUN 映射后，只能通过 LUN 所属节点及其 HA 配对节点上的路径访问此 LUN 。

SLM 支持在每个主机上管理一个 igroup ，并支持不需要操作端口集或重新映射 LUN 的无中断 LUN 移动操作。

可以将端口集与SLM结合使用、以便进一步限制某些目标对某些启动程序的访问。如果将 SLM 与端口集结合使用，则可以通过 LUN 所属节点以及该节点的 HA 配对节点上端口集中的一组 LIF 访问 LUN 。

默认情况下，所有新 LUN 映射都会启用 SLM 。



== 确定是否已在 LUN 映射上启用 SLM

如果您的环境既有在ONTAP 9版本中创建的LUN、又有从先前版本转换的LUN、则您可能需要确定是否对特定LUN启用了选择性LUN映射(SLM)。

您可以使用的输出中显示的信息 `lun mapping show -fields reporting-nodes, node` 命令以确定是否对LUN映射启用了SLM。如果未启用SLM、则会在命令输出的`report-nDES`列下的单元格中显示"-"。如果启用了SLM、则"`nDES`"列下显示的节点列表会复制到"`report-nDES`"列中。



== 修改 SLM 报告节点列表

如果要将 LUN 或包含 LUN 的卷移动到同一集群中的另一个高可用性（ HA ）对，则应在启动移动之前修改选择性 LUN 映射（ SLM ）报告节点列表，以确保活动的优化 LUN 路径保持不变。

.步骤
. 将目标节点及其配对节点添加到聚合或卷的报告节点列表中：
+
`lun mapping add-reporting-nodes -vserver _vserver_name_ -path _lun_path_ -igroup _igroup_name_ [-destination-aggregate _aggregate_name_|-destination-volume _volume_name_]`

+
如果您的命名约定一致、则可以使用同时修改多个LUN映射 `_igroup_prefix*_` 而不是 `_igroup_name_`。

. 重新扫描主机以发现新添加的路径。
. 如果操作系统需要，请将新路径添加到多路径网络 I/O （ MPIO ）配置中。
. 对所需的移动操作运行命令，然后等待操作完成。
. 验证是否正在通过主动 / 优化路径处理 I/O ：
+
`lun mapping show -fields reporting-nodes`

. 从报告节点列表中删除先前的 LUN 所有者及其配对节点：
+
`lun mapping remove-reporting-nodes -vserver _vserver_name_ -path _lun_path_ -igroup _igroup_name_ -remote-nodes`

. 验证是否已从现有 LUN 映射中删除此 LUN ：
+
`lun mapping show -fields reporting-nodes`

. 删除主机操作系统的任何陈旧设备条目。
. 根据需要更改任何多路径配置文件。
. 重新扫描主机以验证是否删除了旧路径。+
有关重新扫描主机的具体步骤，请参见主机文档。

