---
permalink: san-admin/use-cases-odx-concept.html 
sidebar: sidebar 
keywords: odx, use cases 
summary: 您应了解在 SVM 上使用 ODX 的使用情形，以便确定 ODX 在何种情况下可为您带来性能优势。 
---
= ODX 的用例
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您应了解在 SVM 上使用 ODX 的使用情形，以便确定 ODX 在何种情况下可为您带来性能优势。

支持 ODX 的 Windows 服务器和客户端会使用副本卸载作为在远程服务器之间复制数据的默认方式。如果 Windows 服务器或客户端不支持 ODX ，或者 ODX 副本卸载在任何时刻失败，则复制或移动操作将回退为复制或移动操作的传统读写操作。

以下使用情形支持使用 ODX 副本和移动：

* 卷内
+
源文件或 LUN 与目标文件或 LUN 位于同一个卷中。

* 卷间，同一节点，同一 SVM
+
源文件或 LUN 和目标文件或 LUN 位于同一节点上的不同卷上。数据属于同一个 SVM 。

* 卷间，不同节点，相同 SVM
+
源文件或 LUN 和目标文件或 LUN 位于不同节点上的不同卷上。数据属于同一个 SVM 。

* SVM 间，同一节点
+
源和目标文件或 LUN 位于同一节点上的不同卷上。数据属于不同的 SVM 。

* SVM 间，不同节点
+
源和目标文件或 LUN 位于不同节点上的不同卷上。数据属于不同的 SVM 。

* 集群间
+
源 LUN 和目标 LUN 位于集群中不同节点上的不同卷上。只有SAN支持此功能、SMB不支持此功能。



还有一些其他特殊使用情形：

* 在 ONTAP ODX 实施中，您可以使用 ODX 在 SMB 共享与 FC 或 iSCSI 连接的虚拟驱动器之间复制文件。
+
您可以使用 Windows 资源管理器， Windows 命令行界面或 PowerShell ， Hyper-V 或其他支持 ODX 的应用程序，在 SMB 共享和连接的 LUN 之间使用 ODX 副本卸载功能无缝复制或移动文件，但前提是 SMB 共享和 LUN 位于同一集群上。

* Hyper-V 还提供了一些 ODX 副本卸载的其他使用情形：
+
** 您可以使用 ODX 副本卸载直通与 Hyper-V 在虚拟硬盘（ VHD ）文件内部或之间复制数据，或者在同一集群中映射的 SMB 共享和连接的 iSCSI LUN 之间复制数据。
+
这样，子操作系统中的副本就可以传递到底层存储。

** 创建固定大小的 VHD 时， ODX 用于使用众所周知的置零令牌以零初始化磁盘。
** 如果源存储和目标存储位于同一集群上，则使用 ODX 副本卸载进行虚拟机存储迁移。


+
[NOTE]
====
要利用 Hyper-V ODX 副本卸载直通的使用情形，子操作系统必须支持 ODX ，而子操作系统的磁盘必须是 SCSI 磁盘，并由支持 ODX 的存储（ SMB 或 SAN ）提供支持。子操作系统上的 IDE 磁盘不支持 ODX 直通。

====




== 特殊的系统文件要求

您可以删除在 qtree 中找到的 ODX 文件。除非技术支持要求您删除或修改任何其他 ODX 系统文件，否则不得删除或修改此类文件。

使用 ODX 功能时，系统的每个卷中都存在 ODX 系统文件。这些文件可以对 ODX 传输期间使用的数据进行时间点表示。以下系统文件位于包含 LUN 或将数据卸载到的文件的每个卷的根级别：

* `.copy-offload` (隐藏目录)
* `.tokens` (文件位于隐藏的下 `.copy-offload` 目录)


您可以使用 `copy-offload delete-tokens -path dir_path -node _node_name_` 用于删除包含ODX文件的qtree的命令。
