---
permalink: smb-config/requirements-create-share-concept.html 
sidebar: sidebar 
keywords: creating, create, smb, share, requirement, path, properties, property, home, directories, directory, requirements and considerations for creating an smb share 
summary: 在创建 SMB 共享之前，您必须了解共享路径和共享属性的要求，尤其是主目录的要求。 
---
= 创建 SMB 共享的要求和注意事项
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在创建 SMB 共享之前，您必须了解共享路径和共享属性的要求，尤其是主目录的要求。

创建 SMB 共享需要指定客户端要访问的目录路径结构（在 `vserver cifs share create` 命令中使用 ` -path` 选项）。目录路径对应于您在 SVM 命名空间中创建的卷或 qtree 的接合路径。在创建共享之前，必须存在目录路径和相应的接合路径。

共享路径具有以下要求：

* 目录路径名称的长度最多可以包含 255 个字符。
* 如果路径名称中有空格，则必须将整个字符串置于引号中（例如， ` /new volume/mount here"` ）。
* 如果共享的 UNC 路径（` \\servername\sharename\filepath` ）包含超过 256 个字符（不包括 UNC 路径中的初始 "` \\` " ），则 Windows 属性框中的 * 安全性 * 选项卡不可用。
+
这是 Windows 客户端问题描述，而不是 ONTAP 问题描述。要避免此问题描述，请勿使用超过 256 个字符的 UNC 路径创建共享。



可以更改共享属性默认值：

* 所有共享的默认初始属性为 `oplocks` ， `browable` ， `changenotify` 和 `sHow-previous-versions` 。
* 可以选择在创建共享时指定共享属性。
+
但是，如果在创建共享时指定了共享属性，则不会使用默认值。如果在创建共享时使用 ` -share-properties` 参数，则必须使用逗号分隔列表指定要应用于共享的所有共享属性。

* 要指定主目录共享，请使用 `homedirectory` 属性。
+
通过此功能，您可以配置一个共享，该共享可根据连接到它的用户和一组变量映射到不同的目录。您无需为每个用户创建单独的共享，而是使用一些主目录参数配置一个共享，以定义用户在入口点（共享）与其主目录（ SVM 上的目录）之间的关系。

+
[NOTE]
====
创建共享后，您无法添加或删除此属性。

====


主目录共享具有以下要求：

* 在创建 SMB 主目录之前，必须使用 `vserver cifs home-directory search-path add` 命令至少添加一个主目录搜索路径。
* 使用 ` -share-properties` 参数上的 `homedirectory` 值指定的主目录共享必须在共享名称中包含 ` %w` （ Windows 用户名）动态变量。
+
此外，共享名称还可以包含 ` %d` （域名）动态变量（例如， ` %d/%w` ）或共享名称中的静态部分（例如， `home1_%w` ）。

* 如果管理员或用户使用共享连接到其他用户的主目录（使用 `vserver cifs home-directory modify` 命令的选项），则动态共享名称模式前面必须有一个颚化符（`~` ）。


link:../smb-admin/index.html["SMB 管理"] 和 `Vserver cifs share` 手册页具有追加信息。
