---
permalink: smb-config/where-provision-storage-capacity-task.html 
sidebar: sidebar 
keywords: create, smb, volume, qtree, exist, configuration, svm, decision, workflow, decide where to provision new SMB storage capacity 
summary: 在创建新的 SMB 卷或 qtree 之前，您必须确定是将其置于新的还是现有的 SVM 中，以及 SVM 需要多少配置。此决定将决定您的工作流。 
---
= 确定在何处配置新的 SMB 存储容量
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在创建新的 SMB 卷或 qtree 之前，您必须确定是将其置于新的还是现有的 SVM 中，以及 SVM 需要多少配置。此决定将决定您的工作流。

.选项
* 如果要在新 SVM 或已启用但未配置 SMB 的现有 SVM 上配置卷或 qtree ，请完成 "`配置对 SVM 的 SMB 访问` " 和 "`向启用了 SMB 的 SVM` 添加存储容量 " 中的步骤。
+
xref:configure-access-svm-task.adoc[配置对 SVM 的 SMB 访问]

+
xref:configure-client-access-shared-storage-concept.adoc[配置 SMB 客户端对共享存储的访问]

+
如果满足以下条件之一，您可以选择创建新的 SVM ：

+
** 首次在集群上启用 SMB 。
** 集群中的现有 SVM 不希望启用 SMB 支持。
** 一个集群中有一个或多个启用了 SMB 的 SVM ，您需要以下连接之一：
+
*** 到其他 Active Directory 林或工作组。
*** 连接到隔离命名空间中的 SMB 服务器（多租户情形）。您还应选择此选项，以便在已启用但未配置 SMB 的现有 SVM 上配置存储。如果您创建了用于 SAN 访问的 SVM ，或者在创建 SVM 时未启用任何协议，则可能会出现这种情况。




+
在 SVM 上启用 SMB 后，继续配置卷或 qtree 。

* 如果要在已完全配置为可进行 SMB 访问的现有 SVM 上配置卷或 qtree ，请完成 "`将存储容量添加到已启用 SMB 的 SVM` " 中的步骤。
+
xref:configure-client-access-shared-storage-concept.adoc[配置 SMB 客户端对共享存储的访问]


