---
permalink: smb-config/worksheet-reference.html 
sidebar: sidebar 
keywords: smb, configuration, worksheet, enable, collect, require, information, access, client, worksheet, gather, cifs, worksheet for gathering SMB configuration information 
summary: 通过SMB配置工作表、您可以收集为客户端设置SMB访问所需的信息。 
---
= 用于收集SMB配置信息的工作表
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过SMB配置工作表、您可以收集为客户端设置SMB访问所需的信息。

您应完成工作表的一个或两个部分，具体取决于您决定在何处配置存储：

* 如果要配置对 SVM 的 SMB 访问，则应完成这两个部分。
+
xref:configure-access-svm-task.adoc[配置对SVM的SMB访问]

+
xref:configure-client-access-shared-storage-concept.adoc[配置 SMB 客户端对共享存储的访问]

* 如果要向启用了SMB的SVM添加存储容量、则只应完成第二部分。
+
xref:configure-client-access-shared-storage-concept.adoc[配置 SMB 客户端对共享存储的访问]



命令手册页包含有关参数的详细信息。



== 配置对SVM的SMB访问

* 用于创建 SVM* 的参数

您可以在中提供这些值 `vserver create` 命令。

|===
| 字段 | Description | 您的价值 


 a| 
`-vserver`
 a| 
您为新 SVM 提供的名称，可以是完全限定域名（ FQDN ），也可以遵循在集群中强制实施唯一 SVM 名称的其他约定。
 a| 



 a| 
`-aggregate`
 a| 
集群中具有足够空间来容纳新SMB存储容量的聚合的名称。
 a| 



 a| 
`-rootvolume`
 a| 
为 SVM 根卷提供的唯一名称。
 a| 



 a| 
`-rootvolume-security-style`
 a| 
对SVM使用NTFS安全模式。
 a| 
`ntfs`



 a| 
`-language`
 a| 
在此工作流中使用默认语言设置。
 a| 
`C.UTF-8`



 a| 
`ipspace`
 a| 
可选： IP 空间是 SVM 所在的不同 IP 地址空间。
 a| 

|===
* 用于创建 LIF* 的参数

您可以在中提供这些值 `network interface create` 命令。

|===
| 字段 | Description | 您的价值 


 a| 
`-lif`
 a| 
为新 LIF 提供的名称。
 a| 



 a| 
`-role`
 a| 
在此工作流中使用数据 LIF 角色。
 a| 
`data`



 a| 
`-data-protocol`
 a| 
在此工作流中仅使用SMB协议。
 a| 
`cifs`



 a| 
`-home-node`
 a| 
LIF返回到的节点 `network interface revert` 命令将在LIF上运行。
 a| 



 a| 
`-home-port`
 a| 
LIF返回到的端口或接口组 `network interface revert` 命令将在LIF上运行。
 a| 



 a| 
`-address`
 a| 
集群上要由新 LIF 用于数据访问的 IPv4 或 IPv6 地址。
 a| 



 a| 
`-netmask`
 a| 
LIF 的网络掩码和网关。
 a| 



 a| 
`-subnet`
 a| 
IP 地址池。已使用、而不是 `-address` 和 `-netmask` 自动分配地址和网络掩码。
 a| 



 a| 
`-firewall-policy`
 a| 
在此工作流中使用默认数据防火墙策略。
 a| 
`data`



 a| 
`-auto-revert`
 a| 
可选：指定数据 LIF 是在启动时还是在其他情况下自动还原到其主节点。默认设置为 `false`。
 a| 

|===
* 用于 DNS 主机名解析的参数 *

您可以在中提供这些值 `vserver services name-service dns create` 命令。

|===
| 字段 | Description | 您的价值 


 a| 
`-domains`
 a| 
最多五个 DNS 域名。
 a| 



 a| 
`-name-servers`
 a| 
每个 DNS 名称服务器最多三个 IP 地址。
 a| 

|===


== 在 Active Directory 域中设置 SMB 服务器

* 时间服务配置的参数 *

您可以在中提供这些值 `cluster time-service ntp server create` 命令。

|===
| 字段 | Description | 您的价值 


 a| 
`-server`
 a| 
Active Directory 域的 NTP 服务器的主机名或 IP 地址。
 a| 

|===
* 用于在 Active Directory 域中创建 SMB 服务器的参数 *

您可以在中提供这些值 `vserver cifs create` 命令。

|===
| 字段 | Description | 您的价值 


 a| 
`-vserver`
 a| 
要在其中创建 SMB 服务器的 SVM 的名称。
 a| 



 a| 
`-cifs-server`
 a| 
SMB 服务器的名称（最多 15 个字符）。
 a| 



 a| 
`-domain`
 a| 
要与 SMB 服务器关联的 Active Directory 域的完全限定域名（ FQDN ）。
 a| 



 a| 
`-ou`
 a| 
可选： Active Directory 域中要与 SMB 服务器关联的组织单位。默认情况下，此参数设置为 CN=Computers 。
 a| 



 a| 
`-netbios-aliases`
 a| 
可选： NetBIOS 别名列表，这些别名是 SMB 服务器名称的备用名称。
 a| 



 a| 
`-comment`
 a| 
可选：服务器的文本注释。在网络上浏览服务器时， Windows 客户端可以看到此 SMB 服务器问题描述。
 a| 

|===


== 在工作组中设置 SMB 服务器

* 用于在工作组中创建 SMB 服务器的参数 *

您可以在中提供这些值 `vserver cifs create` 命令。

|===
| 字段 | Description | 您的价值 


 a| 
`-vserver`
 a| 
要在其中创建 SMB 服务器的 SVM 的名称。
 a| 



 a| 
`-cifs-server`
 a| 
SMB 服务器的名称（最多 15 个字符）。
 a| 



 a| 
`-workgroup`
 a| 
工作组的名称（最多 15 个字符）。
 a| 



 a| 
`-comment`
 a| 
可选：服务器的文本注释。在网络上浏览服务器时， Windows 客户端可以看到此 SMB 服务器问题描述。
 a| 

|===
* 用于创建本地用户的参数 *

您可以在创建本地用户时使用提供以下值 `vserver cifs users-and-groups local-user create` 命令：它们对于工作组中的 SMB 服务器是必需的，在 AD 域中是可选的。

|===
| 字段 | Description | 您的价值 


 a| 
`-vserver`
 a| 
要在其中创建本地用户的 SVM 的名称。
 a| 



 a| 
`-user-name`
 a| 
本地用户的名称（最多 20 个字符）。
 a| 



 a| 
`-full-name`
 a| 
可选：用户的全名。如果全名包含空格，请将全名用双引号括起来。
 a| 



 a| 
`-description`
 a| 
可选：本地用户的问题描述。如果问题描述包含空格，请将参数用引号括起来。
 a| 



 a| 
`-is-account-disabled`
 a| 
可选：指定用户帐户是启用还是禁用。如果未指定此参数，则默认为启用用户帐户。
 a| 

|===
* 用于创建本地组的参数 *

您可以在创建本地组时使用提供以下值 `vserver cifs users-and-groups local-group create` 命令：对于 AD 域和工作组中的 SMB 服务器，它们是可选的。

|===
| 字段 | Description | 您的价值 


 a| 
`-vserver`
 a| 
要在其中创建本地组的 SVM 的名称。
 a| 



 a| 
`-group-name`
 a| 
本地组的名称（最多 256 个字符）。
 a| 



 a| 
`-description`
 a| 
可选：本地组的问题描述。如果问题描述包含空格，请将参数用引号括起来。
 a| 

|===


== 向启用了SMB的SVM添加存储容量

用于创建卷的 * 参数 *

您可以在中提供这些值 `volume create` 命令。

|===
| 字段 | Description | 您的价值 


 a| 
`-vserver`
 a| 
要托管新卷的新 SVM 或现有 SVM 的名称。
 a| 



 a| 
`-volume`
 a| 
为新卷提供的唯一描述性名称。
 a| 



 a| 
`-aggregate`
 a| 
集群中为新SMB卷提供足够空间的聚合的名称。
 a| 



 a| 
`-size`
 a| 
为新卷的大小提供的整数。
 a| 



 a| 
`-security-style`
 a| 
对此工作流使用NTFS安全模式。
 a| 
`ntfs`



 a| 
`-junction-path`
 a| 
根（ / ）下要挂载新卷的位置。
 a| 

|===
用于创建 qtree* 的 * 参数

您可以在中提供这些值 `volume qtree create` 命令。

|===
| 字段 | Description | 您的价值 


 a| 
`-vserver`
 a| 
包含 qtree 的卷所在 SVM 的名称。
 a| 



 a| 
`-volume`
 a| 
要包含新 qtree 的卷的名称。
 a| 



 a| 
`-qtree`
 a| 
为新 qtree 提供的唯一描述性名称，不超过 64 个字符。
 a| 



 a| 
`-qtree-path`
 a| 
格式的qtree路径参数 `/vol/volume_name/qtree_name\>` 可以指定、而不是将卷和qtree指定为单独的参数。
 a| 

|===
* 用于创建 SMB 共享的参数 *

您可以在中提供这些值 `vserver cifs share create` 命令：

|===
| 字段 | Description | 您的价值 


 a| 
`-vserver`
 a| 
要在其中创建 SMB 共享的 SVM 的名称。
 a| 



 a| 
`-share-name`
 a| 
要创建的 SMB 共享的名称（最多 256 个字符）。
 a| 



 a| 
`-path`
 a| 
SMB 共享路径的名称（最多 256 个字符）。在创建共享之前，此路径必须存在于卷中。
 a| 



 a| 
`-share-properties`
 a| 
可选：共享属性列表。默认设置为 `oplocks`， `browsable`， `changenotify`，和 `show-previous-versions`。
 a| 



 a| 
`-comment`
 a| 
可选：服务器的文本注释（最多 256 个字符）。在网络上浏览时， Windows 客户端可以看到此 SMB 共享问题描述。
 a| 

|===
* 用于创建 SMB 共享访问控制列表（ ACL ）的参数 *

您可以在中提供这些值 `vserver cifs share access-control create` 命令：

|===
| 字段 | Description | 您的价值 


 a| 
`-vserver`
 a| 
要在其中创建 SMB ACL 的 SVM 的名称。
 a| 



 a| 
`-share`
 a| 
要创建的 SMB 共享的名称。
 a| 



 a| 
`-user-group-type`
 a| 
要添加到共享 ACL 的用户或组的类型。默认类型为 `windows`
 a| 
`windows`



 a| 
`-user-or-group`
 a| 
要添加到共享 ACL 的用户或组。如果指定用户名，则必须使用 `domain\username` 格式包含用户的域。
 a| 



 a| 
`-permission`
 a| 
指定用户或组的权限。
 a| 
`[ No_access | Read | Change | Full_Control ]`

|===