---
permalink: disks-aggregates/commands-manage-disks-reference.html 
sidebar: sidebar 
keywords: commands, manage, disks 
summary: 您可以使用 storage disk 和 storage aggregate 命令管理磁盘。 
---
= 用于管理磁盘的命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `storage disk` 和 `storage aggregate` 命令来管理磁盘。

|===


| 如果您要 ... | 使用此命令 ... 


 a| 
按所有者显示备用磁盘列表，包括分区磁盘
 a| 
`s存储聚合 show-spare-disks`



 a| 
按聚合显示磁盘 RAID 类型，当前使用情况和 RAID 组
 a| 
`s存储聚合显示状态`



 a| 
显示 RAID 类型，当前使用情况，聚合和 RAID 组，包括备用磁盘， 物理磁盘
 a| 
`storage disk show -RAID`



 a| 
显示故障磁盘的列表
 a| 
`storage disk show -broken`



 a| 
显示磁盘的集群前（节点范围）驱动器名称
 a| 
`storage disk show -primary-paths` （高级）



 a| 
点亮特定磁盘或磁盘架的 LED
 a| 
`s存储磁盘设置 LED`



 a| 
显示特定磁盘的校验和类型
 a| 
`storage disk show -fields checksum-compati兼容 性`



 a| 
显示所有备用磁盘的校验和类型
 a| 
`storage disk show -fields checksum-compati兼容 性 -container-type spare`



 a| 
显示磁盘连接和放置信息
 a| 
`storage disk show -fields disk ， primary-port ， secondary -name ， secondary -port ， shelf ， bay`



 a| 
显示特定磁盘的集群前磁盘名称
 a| 
`storage disk show -disk diskname -fields diskpathnames`



 a| 
显示维护中心中的磁盘列表
 a| 
`storage disk show -maintenance`



 a| 
显示 SSD 使用寿命
 a| 
`storage disk show -sds-wear`



 a| 
取消对共享磁盘的分区
 a| 
`s存储磁盘取消分区` （可在诊断级别使用）



 a| 
将所有未置零的磁盘置零
 a| 
`s存储磁盘置零`



 a| 
停止一个或多个指定磁盘上正在进行的清理过程
 a| 
`ssystem node run -node nodename -command disk sanitize`



 a| 
显示存储加密磁盘信息
 a| 
`s存储加密磁盘 show`



 a| 
从所有链接的密钥管理服务器检索身份验证密钥
 a| 
`s安全密钥管理器还原`

|===
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9 命令"]
