---
permalink: disks-aggregates/commands-manage-disks-reference.html 
sidebar: sidebar 
keywords: commands, manage, disks 
summary: 您可以使用 storage disk 和 storage aggregate 命令管理磁盘。 
---
= 用于管理磁盘的命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `storage disk` 和 `storage aggregate` 用于管理磁盘的命令。

|===


| 如果您要 ... | 使用此命令 ... 


 a| 
按所有者显示备用磁盘列表，包括分区磁盘
 a| 
`storage aggregate show-spare-disks`



 a| 
按聚合显示磁盘 RAID 类型，当前使用情况和 RAID 组
 a| 
`storage aggregate show-status`



 a| 
显示 RAID 类型，当前使用情况，聚合和 RAID 组，包括备用磁盘， 物理磁盘
 a| 
`storage disk show -raid`



 a| 
显示故障磁盘的列表
 a| 
`storage disk show -broken`



 a| 
显示磁盘的集群前（节点范围）驱动器名称
 a| 
`storage disk show -primary-paths` (高级)



 a| 
点亮特定磁盘或磁盘架的 LED
 a| 
`storage disk set-led`



 a| 
显示特定磁盘的校验和类型
 a| 
`storage disk show -fields checksum-compatibility`



 a| 
显示所有备用磁盘的校验和类型
 a| 
`storage disk show -fields checksum-compatibility -container-type spare`



 a| 
显示磁盘连接和放置信息
 a| 
`storage disk show -fields disk,primary-port,secondary-name,secondary-port,shelf,bay`



 a| 
显示特定磁盘的集群前磁盘名称
 a| 
`storage disk show -disk diskname -fields diskpathnames`



 a| 
显示维护中心中的磁盘列表
 a| 
`storage disk show -maintenance`



 a| 
显示 SSD 使用寿命
 a| 
`storage disk show -ssd-wear`



 a| 
取消对共享磁盘的分区
 a| 
`storage disk unpartition` (可在诊断级别使用)



 a| 
将所有未置零的磁盘置零
 a| 
`storage disk zerospares`



 a| 
停止一个或多个指定磁盘上正在进行的清理过程
 a| 
`system node run -node nodename -command disk sanitize`



 a| 
显示存储加密磁盘信息
 a| 
`storage encryption disk show`



 a| 
从所有链接的密钥管理服务器检索身份验证密钥
 a| 
`security key-manager restore`

|===
.相关信息
* link:http://docs.netapp.com/us-en/ontap-cli["ONTAP 9命令参考"^]

