---
permalink: disks-aggregates/convert-raid-dp-tec-task.html 
sidebar: sidebar 
keywords: convert, raid-dp, raid-tec, raid policy 
summary: 如果要添加三重奇偶校验保护，可以从 RAID-DP 转换为 RAID-TEC 。如果本地层中使用的磁盘大小大于4 TiB、建议使用RAID-TEC。 
---
= 从ONTAP RAID-DP转换为RAID-TEC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果要添加三重奇偶校验保护，可以从 RAID-DP 转换为 RAID-TEC 。如果本地层中使用的磁盘大小大于4 TiB、建议使用RAID-TEC。


NOTE: 在ONTAP 9.7之前的版本中、System Manager会使用术语_AGREL_来描述_local ti层_。无论您的ONTAP版本如何、ONTAP命令行界面都使用术语_AGREL_。要了解有关本地层的更多信息，请参见link:../disks-aggregates/index.html["磁盘和本地层"]。

.开始之前
要转换的本地层必须至少具有七个磁盘。

.关于此任务
* 硬盘驱动器(HDD)本地层可以从RAID-DP转换为RAID-TEC。这包括Flash Pool本地层中的HDD层。


.闪存池/混合聚合的过程，其中需要使用 -disktype 来更改每个磁盘类型
[-T, -disktype {ATA | BSAS | FCAL | FSAS | LUN | MSATA | SAS | SSD | VMDISK | SSD-NVM | SSD-CAP | SSD-ZNS | VMLUN | VMLUN-SSD}] - 磁盘类型

此参数指定要修改的 RAID 组的磁盘类型。对于 Flash Pool，它指定 HDD 层或 SSD 层。如果 HDD 层由多个类型的磁盘组成，则指定任何正在使用的磁盘类型都会导致修改该层。如果当前聚合 RAID 类型为 mixed_raid_type，则此参数为必需参数。

.步骤
. 验证本地层是否已联机且至少具有六个磁盘：
+
`storage aggregate show-status -aggregate _aggregate_name_`

. 将本地层从RAID-DP转换为RAID-TEC：
+
`storage aggregate modify -aggregate _aggregate_name_ -raidtype raid_tec`

. 验证本地层RAID策略是否为RAID-TEC：
+
`storage aggregate show _aggregate_name_`



.相关信息
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-modify.html["storage aggregate modify"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show-status.html["存储聚合显示状态"^]

