---
permalink: disks-aggregates/correct-misaligned-spare-partitions-task.html 
sidebar: sidebar 
keywords: correct, misaligned, partition 
summary: 将分区磁盘添加到聚合时，必须保留一个包含根分区和数据分区的磁盘，作为每个节点的备用磁盘。否则，如果节点发生中断， ONTAP 将无法将核心转储到备用数据分区。 
---
= 更正错位的备用分区
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
将分区磁盘添加到聚合时，必须保留一个包含根分区和数据分区的磁盘，作为每个节点的备用磁盘。否则，如果节点发生中断， ONTAP 将无法将核心转储到备用数据分区。

备用数据分区和备用根分区必须位于同一节点所拥有的相同类型磁盘上。

.步骤
. 显示节点的备用分区：
+
`storage aggregate show-spare-disks -original-owner _node_name_`

+
记下哪个磁盘具有备用数据分区（ spare_data ），哪个磁盘具有备用根分区（ spare_root ）。备用分区的 `Local Data Usable` 或 `Local Root Usable` 列下将显示非零值。

. 将具有备用数据分区的磁盘替换为具有备用根分区的磁盘：
+
`s存储磁盘 replace -disk _spare_data_ -replacement _spare_root_ -action start`

+
您可以在任一方向复制数据；但是，完成根分区复制所需的时间较短。

. 监控磁盘更换的进度：
+
`storage aggregate show-status -aggregate _aggr_name_`

. 更换操作完成后，再次显示备用磁盘以确认您的备用磁盘已满：
+
`storage aggregate show-spare-disks -original-owner _node_name_`

+
您应在 `Local Data Usable` 和 `Local Root Usable` 下看到一个具有可用空间的备用磁盘。



显示节点 C1-01 的备用分区，并发现备用分区未对齐：

[listing]
----
c1::> storage aggregate show-spare-disks -original-owner c1-01

Original Owner: c1-01
 Pool0
  Shared HDD Spares
                                                            Local    Local
                                                             Data     Root Physical
 Disk                        Type     RPM Checksum         Usable   Usable     Size
 --------------------------- ----- ------ -------------- -------- -------- --------
 1.0.1                       BSAS    7200 block           753.8GB       0B  828.0GB
 1.0.10                      BSAS    7200 block                0B  73.89GB  828.0GB
----
启动磁盘更换作业：

[listing]
----
c1::> storage disk replace -disk 1.0.1 -replacement 1.0.10 -action start
----
在等待替换操作完成时，您将显示此操作的进度：

[listing]
----
c1::> storage aggregate show-status -aggregate aggr0_1

Owner Node: c1-01
 Aggregate: aggr0_1 (online, raid_dp) (block checksums)
  Plex: /aggr0_1/plex0 (online, normal, active, pool0)
   RAID Group /aggr0_1/plex0/rg0 (normal, block checksums)
                                                              Usable Physical
     Position Disk                        Pool Type     RPM     Size     Size Status
     -------- --------------------------- ---- ----- ------ -------- -------- ----------
     shared   1.0.1                        0   BSAS    7200  73.89GB  828.0GB (replacing, copy in progress)
     shared   1.0.10                       0   BSAS    7200  73.89GB  828.0GB (copy 63% completed)
     shared   1.0.0                        0   BSAS    7200  73.89GB  828.0GB (normal)
     shared   1.0.11                       0   BSAS    7200  73.89GB  828.0GB (normal)
     shared   1.0.6                        0   BSAS    7200  73.89GB  828.0GB (normal)
     shared   1.0.5                        0   BSAS    7200  73.89GB  828.0GB (normal)
----
更换操作完成后，您需要确认您的备用磁盘已满：

[listing]
----
ie2220::> storage aggregate show-spare-disks -original-owner c1-01

Original Owner: c1-01
 Pool0
  Shared HDD Spares
                                                            Local    Local
                                                             Data     Root Physical
 Disk                        Type     RPM Checksum         Usable   Usable     Size
 --------------------------- ----- ------ -------------- -------- -------- --------
 1.0.1                       BSAS    7200 block           753.8GB  73.89GB  828.0GB
----