---
permalink: disks-aggregates/create-flash-pool-aggregate-physical-ssds-task.html 
sidebar: sidebar 
keywords: create, flash, pool, aggregate, physical, ssds 
summary: 您可以在由 HDD RAID 组组成的现有聚合上启用 Flash Pool 聚合功能，然后向该聚合添加一个或多个 SSD RAID 组来创建 Flash Pool 聚合。这会导致该聚合出现两组 RAID 组： SSD RAID 组（ SSD 缓存）和 HDD RAID 组。 
---
= 使用物理 SSD 创建 Flash Pool 聚合
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在由 HDD RAID 组组成的现有聚合上启用 Flash Pool 聚合功能，然后向该聚合添加一个或多个 SSD RAID 组来创建 Flash Pool 聚合。这会导致该聚合出现两组 RAID 组： SSD RAID 组（ SSD 缓存）和 HDD RAID 组。

.您需要什么？ #8217 ；将需要什么
* 您必须已确定一个由 HDD 组成的有效聚合，以转换为 Flash Pool 聚合。
* 您必须已确定与聚合关联的卷的写入缓存资格，并已完成解决资格问题所需的所有步骤。
* 您必须已确定要添加的 SSD ，并且这些 SSD 必须归要创建 Flash Pool 聚合的节点所有。
* 您必须已确定要添加的 SSD 以及聚合中已有的 HDD 的校验和类型。
* 您必须已确定要添加的 SSD 数量以及 SSD RAID 组的最佳 RAID 组大小。
+
在 SSD 缓存中使用较少的 RAID 组可减少所需的奇偶校验磁盘数量，但较大的 RAID 组需要 RAID-DP 。

* 您必须已确定要用于 SSD 缓存的 RAID 级别。
* 您必须已确定系统的最大缓存大小，并确定向聚合添加 SSD 缓存不会导致发生原因超出此限制。
* 您必须已熟悉 Flash Pool 聚合的配置要求。


将 SSD 缓存添加到聚合以创建 Flash Pool 聚合后，您无法删除 SSD 缓存以将聚合转换回其原始配置。

默认情况下， SSD 缓存的 RAID 级别与 HDD RAID 组的 RAID 级别相同。您可以通过在添加第一个 SSD RAID 组时指定 `RAIDType` 选项来覆盖此默认选择。

.步骤
. 将聚合标记为有资格成为 Flash Pool 聚合：
+
`storage aggregate modify -aggregate _aggr_name_ -hybrid-enabled true`

+
如果此步骤未成功，请确定目标聚合的写入缓存资格。

. 使用 `storage aggregate add` 命令将 SSD 添加到聚合。
+
您可以按 ID 或使用 `diskcount` 和 `disktype` 参数指定 SSD 。

+
如果 HDD 和 SSD 的校验和类型不同，或者聚合是混合校验和聚合，则必须使用 `checksumstyle` 参数指定要添加到聚合的磁盘的校验和类型。

+
您可以使用 `RAIDType` 参数为 SSD 缓存指定其他 RAID 类型。

+
如果您希望缓存 RAID 组大小与所使用 RAID 类型的默认值不同，则应立即使用 ` -cache-raid-group-size` 参数进行更改。


