---
permalink: disks-aggregates/create-aggregates-manual-task.html 
sidebar: sidebar 
keywords: ontap 9, create, aggregates, manually 
summary: 在手动创建聚合之前，您应查看磁盘配置选项并模拟创建过程。然后，您可以通过问题描述创建存储聚合并验证结果。 
---
= 手动创建聚合
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在手动创建聚合之前，您应查看磁盘配置选项并模拟创建过程。然后，您可以对 `s存储聚合 create` 执行问题描述并验证结果。

您必须已确定聚合中所需的磁盘数量和热备用磁盘数量。

如果已启用根 - 数据 - 数据分区，并且配置中的固态驱动器（ SSD ）不超过 24 个，则建议将数据分区分配给不同的节点。

用于在启用了根数据分区和根数据数据分区的系统上创建聚合的操作步骤与用于在使用未分区磁盘的系统上创建聚合的操作步骤相同。如果您的系统已启用根数据分区，则应使用 ` -diskcount` 选项中的磁盘分区数。对于根 - 数据 - 数据分区， ` -diskcount` 选项指定要使用的磁盘数。

[NOTE]
====
创建多个聚合以用于 FlexGroup 时，聚合的大小应尽可能接近。

====
`storage aggregate create` 手册页包含有关聚合创建选项和要求的详细信息。

.步骤
. 查看备用磁盘分区列表，以验证是否有足够的空间来创建聚合：
+
`storage aggregate show-spare-disks -original-owner _node_name_`

+
数据分区显示在 `Local Data Usable` 下。根分区不能用作备用分区。

. 模拟聚合的创建：
+
`storage aggregate create -aggregate _aggregate_name_ -node _node_name_ -raidtype raid_dp -diskcount _number_of_disks_or_partitions_ -simulate true`

. 如果模拟命令显示任何警告，请调整命令并重复模拟。
. 创建聚合：
+
`storage aggregate create -aggregate _aggr_name_ -node _node_name_ -raidtype raid_dp -diskcount _number_of_disks_or_partitions_`

. 显示聚合以验证其是否已创建：
+
`storage aggregate show-status aggregate_name`



http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9 命令"]
