---
permalink: disks-aggregates/create-ssd-storage-pool-task.html 
sidebar: sidebar 
keywords: create, provision, ssd, storage, flash, pool, add, cache, local tier, aggregate 
summary: '您可以创建固态驱动器(SSD)存储池、以便为两到四个Flash Pool本地层(聚合)提供SSD缓存。' 
---
= 通过创建SSD存储池向本地层(聚合)添加缓存
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以通过添加固态驱动器(SSD)将现有本地层(聚合)转换为Flash Pool本地层(聚合)来配置缓存。

您可以创建固态驱动器(SSD)存储池、以便为两到四个Flash Pool本地层(聚合)提供SSD缓存。通过 Flash Pool 聚合，您可以将闪存部署为工作数据集的高性能缓存，同时使用低成本的 HDD 来存储访问频率较低的数据。

.关于此任务
* 在创建磁盘或向存储池添加磁盘时，必须提供磁盘列表。
+
存储池不支持 `diskcount` 参数。

* 存储池中使用的 SSD 大小应相同。


[role="tabbed-block"]
====
.System Manager
--
.使用System Manager添加SSD缓存(ONTAP 9.12.1及更高版本)
[%collapsible%open]
=====
从ONTAP 9.12.1开始、您可以使用System Manager添加SSD缓存。


NOTE: 存储池选项在AFF 系统上不可用。

.步骤
. 单击*集群>磁盘*、然后单击*显示/隐藏*。
. 选择*类型*并验证集群上是否存在备用SSD。
. 单击*存储>层*、然后单击*添加存储池*。
. 选择磁盘类型。
. 输入磁盘大小。
. 选择要添加到存储池的磁盘数。
. 查看估计的缓存大小。


=====
.使用 System Manager 添加 SSD 缓存（仅限 ONTAP 9.7 ）
[%collapsible%open]
=====

NOTE: 如果您使用的ONTAP 版本高于ONTAP 9.7或低于ONTAP 9.12.1、请使用命令行界面操作步骤。

.步骤
. 单击 * （返回经典版本） * 。
. 单击 * 存储 > 聚合和磁盘 > 聚合 * 。
. 选择本地层（聚合），然后单击 * 操作 > 添加缓存 * 。
. 选择缓存源作为 " 存储池 " 或 " 专用 SSD " 。
. 单击 * （切换到新体验） * 。
. 单击 * 存储 > 层 * 以验证新聚合的大小。


=====
--
.命令行界面
--
*使用命令行界面创建SSD存储池*

.步骤
. 确定可用备用 SSD 的名称：
+
`storage aggregate show-spare-disks -disk-type SSD`

+
存储池中使用的 SSD 可以归 HA 对中的任一节点所有。

. 创建存储池：
+
`s存储池 create -storage-pool _sp_name_ -disk-list _disk1_ ， _disk2_ ， ...`

. * 可选： * 验证新创建的存储池：
+
`storage pool show -storage-pool _sp_name_`



--
====
.结果
将 SSD 放入存储池后，它们将不再显示为集群上的备用磁盘，即使存储池提供的存储尚未分配给任何 Flash Pool 缓存。您不能将 SSD 作为离散驱动器添加到 RAID 组；其存储只能使用其所属存储池的分配单元进行配置。
