---
permalink: disks-aggregates/customize-size-raid-groups-task.html 
sidebar: sidebar 
keywords: raidsize, customize, raid groups 
summary: 您可以自定义RAID组的大小、以确保RAID组大小适合计划包含在本地层中的存储量。 
---
= 自定义ONTAP RAID组的大小
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以自定义RAID组的大小、以确保RAID组大小适合计划包含在本地层中的存储量。


NOTE: 在ONTAP 9.7之前的版本中、System Manager会使用术语_AGREL_来描述_local ti层_。无论您的ONTAP版本如何、ONTAP命令行界面都使用术语_AGREL_。要了解有关本地层的更多信息，请参见link:../disks-aggregates/index.html["磁盘和本地层"]。

.关于此任务
对于标准本地层、您可以单独更改每个本地层的RAID组大小。对于Flash Pool本地层、您可以单独更改SSD RAID组和HDD RAID组的RAID组大小。

以下列表概括了有关更改 RAID 组大小的一些事实：

* 默认情况下，如果最近创建的 RAID 组中的磁盘或阵列 LUN 数量小于新的 RAID 组大小，则会将磁盘或阵列 LUN 添加到最近创建的 RAID 组中，直到其达到新大小为止。
* 此本地层中所有其他现有RAID组的大小保持不变、除非您明确向其添加磁盘。
* 您不能将RAID组的发生原因 设置为大于本地层的当前最大RAID组大小。
* 您不能减小已创建的 RAID 组的大小。
* 新大小的适用场景 将显示该本地层中的所有RAID组(如果是Flash Pool本地层、则显示受影响RAID组类型为SSD或HDD的所有RAID组)。


.步骤
. 使用适用的命令：
+
|===


| 如果您要 ... | 输入以下命令 ... 


 a| 
更改Flash Pool本地层中SSD RAID组的最大RAID组大小
 a| 
`storage aggregate modify -aggregate aggr_name -cache-raid-group-size size`



 a| 
更改任何其他 RAID 组的最大大小
 a| 
`storage aggregate modify -aggregate aggr_name -maxraidsize size`

|===


.示例
以下命令会将本地层n1_a4的最大RAID组大小更改为20个磁盘或阵列LUN：

`storage aggregate modify -aggregate n1_a4 -maxraidsize 20`

以下命令将Flash Pool本地层n1_cache_a2的SSD缓存RAID组的最大RAID组大小更改为24：

`storage aggregate modify -aggregate n1_cache_a2 -cache-raid-group-size 24`

.相关信息
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-modify.html["storage aggregate modify"^]

