---
permalink: disks-aggregates/determine-control-volume-space-aggregate-concept.html 
sidebar: sidebar 
keywords: determine, control. volume, space usage, aggregate 
summary: '您可以确定哪些FlexVol 卷在本地层(聚合)中使用的空间最多、以及具体确定卷中使用的功能。' 
---
= 确定并控制本地层(聚合)中卷的空间使用量
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以确定哪些FlexVol 卷在本地层(聚合)中使用的空间最多、以及具体确定卷中使用的功能。

。 `volume show-footprint` 命令可提供有关卷占用空间或卷在所属聚合中的空间使用量的信息。

。 `volume show-footprint` 命令可显示有关聚合中每个卷(包括脱机卷)的空间使用量详细信息。此命令可弥补输出之间的差距 `volume show-space` 和 `aggregate show-space` 命令所有百分比均按聚合大小的百分比计算。

以下示例显示了 `volume show-footprint` 名为testvol的卷的命令输出：

....
cluster1::> volume show-footprint testvol

      Vserver : thevs
      Volume  : testvol

      Feature                                   Used    Used%
      --------------------------------    ----------    -----
      Volume Data Footprint                  120.6MB       4%
      Volume Guarantee                        1.88GB      71%
      Flexible Volume Metadata               11.38MB       0%
      Delayed Frees                           1.36MB       0%
      Total Footprint                         2.01GB      76%
....
下表介绍了的输出中的一些关键行 `volume show-footprint` 命令以及您可以执行哪些操作来减少此功能的空间使用量：

|===


| 行 / 功能名称 | 行的说明 / 内容 | 减少的方法 


 a| 
`Volume Data Footprint`
 a| 
活动文件系统中卷数据在所属聚合中使用的总空间量，以及卷的 Snapshot 副本使用的空间量。此行不包括预留空间。
 a| 
* 从卷中删除数据。
* 从卷中删除 Snapshot 副本。




 a| 
`Volume Guarantee`
 a| 
聚合中的卷为将来写入而预留的空间量。预留的空间量取决于卷的保证类型。
 a| 
将卷的保证类型更改为 `none`。



 a| 
`Flexible Volume Metadata`
 a| 
卷的元数据文件在聚合中使用的总空间量。
 a| 
没有直接的控制方法。



 a| 
`Delayed Frees`
 a| 
ONTAP 用于提高性能的块，不能立即释放这些块。对于SnapMirror目标、此行的值为 `0` 不会显示和。
 a| 
没有直接的控制方法。



 a| 
`File Operation Metadata`
 a| 
为文件操作元数据预留的总空间量。
 a| 
没有直接的控制方法。



 a| 
`Total Footprint`
 a| 
卷在聚合中使用的总空间量。它是所有行的总和。
 a| 
用于减少卷所用空间的任何方法。

|===
.相关信息
https://www.netapp.com/pdf.html?item=/media/19670-tr-3483.pdf["NetApp 技术报告 3483 ：《 NetApp SAN 或 IP SAN 企业环境中的精简配置》"^]
