---
permalink: disks-aggregates/determine-control-volume-space-aggregate-concept.html 
sidebar: sidebar 
keywords: determine, control. volume, space usage, aggregate 
summary: 您可以确定哪些FlexVol卷在本地层中使用的空间最多、以及具体确定卷中的哪些功能。 
---
= 在ONTAP的本地层中确定和控制卷的空间使用量
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以确定哪些FlexVol卷在本地层中使用的空间最多、以及具体确定卷中的哪些功能。

 `volume show-footprint`命令可提供有关卷占用空间或卷在所属本地层中的空间使用量的信息。


NOTE: 在ONTAP 9.7之前的版本中、System Manager会使用术语_AGREL_来描述_local ti层_。无论您的ONTAP版本如何、ONTAP命令行界面都使用术语_AGREL_。要了解有关本地层的更多信息，请参见link:../disks-aggregates/index.html["磁盘和本地层"]。

命令可 `volume show-footprint`显示有关本地层中每个卷(包括脱机卷)的空间使用量的详细信息。此命令弥补了和 `aggregate show-space`命令输出之间的差距 `volume show-space`。所有百分比均按本地层大小的百分比计算。

以下示例显示了 `volume show-footprint` 名为testvol的卷的命令输出：

....
cluster1::> volume show-footprint testvol

      Vserver : thevs
      Volume  : testvol

      Feature                                   Used    Used%
      --------------------------------    ----------    -----
      Volume Data Footprint                  120.6MB       4%
      Volume Guarantee                        1.88GB      71%
      Flexible Volume Metadata               11.38MB       0%
      Delayed Frees                           1.36MB       0%
      Total Footprint                         2.01GB      76%
....
下表介绍了的输出中的一些关键行 `volume show-footprint` 命令以及您可以执行哪些操作来减少此功能的空间使用量：

|===


| 行 / 功能名称 | 行的说明 / 内容 | 减少的方法 


 a| 
`Volume Data Footprint`
 a| 
活动文件系统中卷的数据在所属本地层中使用的总空间量以及卷的快照使用的空间量。此行不包括预留空间。
 a| 
* 从卷中删除数据。
* 从卷中删除快照。




 a| 
`Volume Guarantee`
 a| 
卷在本地层中为将来写入预留的空间量。预留的空间量取决于卷的保证类型。
 a| 
将卷的保证类型更改为 `none`。



 a| 
`Flexible Volume Metadata`
 a| 
卷的元数据文件在本地层中使用的总空间量。
 a| 
没有直接的控制方法。



 a| 
`Delayed Frees`
 a| 
ONTAP 用于提高性能的块，不能立即释放这些块。对于SnapMirror目标、此行的值为 `0` 不会显示和。
 a| 
没有直接的控制方法。



 a| 
`File Operation Metadata`
 a| 
为文件操作元数据预留的总空间量。
 a| 
没有直接的控制方法。



 a| 
`Total Footprint`
 a| 
卷在本地层中使用的总空间量。它是所有行的总和。
 a| 
用于减少卷所用空间的任何方法。

|===
.相关信息
https://www.netapp.com/pdf.html?item=/media/19670-tr-3483.pdf["NetApp 技术报告 3483 ：《 NetApp SAN 或 IP SAN 企业环境中的精简配置》"^]
