---
permalink: disks-aggregates/determine-modify-caching-policy-flash-pool-task.html 
sidebar: sidebar 
keywords: modify, cache, policy, flash pool, aggregate, local tier 
summary: 您可以将缓存保留策略分配给Flash Pool本地层中的卷、以确定卷数据在Flash Pool缓存中保留的时间长度。但是，在某些情况下，更改缓存保留策略可能不会影响卷数据在缓存中的保留时间。 
---
= 确定是否修改Flash Pool本地层的ONTAP缓存策略
:allow-uri-read: 


[role="lead"]
您可以将缓存保留策略分配给Flash Pool本地层中的卷、以确定卷数据在Flash Pool缓存中保留的时间长度。但是，在某些情况下，更改缓存保留策略可能不会影响卷数据在缓存中的保留时间。

.关于此任务
如果数据满足以下任一条件，更改缓存保留策略可能不会产生影响：

* 您的工作负载是顺序的。
* 您的工作负载不会重新读取固态驱动器（ SSD ）中缓存的随机块。
* 卷的缓存大小太小。


.步骤
以下步骤将检查数据必须满足的条件。此任务必须在高级权限模式下使用命令行界面完成。

. 使用CLI查看工作负载卷：
+
`statistics start -object workload_volume`

. 确定卷的工作负载模式：
+
`statistics show -object workload_volume -instance _volume-workload_ -counter sequential_reads`

. 确定卷的命中率：
+
`statistics show -object wafl_hya_vvol -instance _volume_ -counter read_ops_replaced_pwercent|wc_write_blks_overwritten_percent`

. 确定 `Cacheable Read` 和 `Project Cache Alloc` 卷：
+
`system node run -node node_name wafl awa start _aggr_name_`

. 显示 AWA 摘要：
+
`system node run -node node_name wafl awa print _aggr_name_`

. 将卷的命中率与进行比较 `Cacheable Read`。
+
如果卷的命中率大于 `Cacheable Read`则工作负载不会重新读取SSD中缓存的随机块。

. 将卷的当前缓存大小与进行比较 `Project Cache Alloc`。
+
卷的当前缓存大小大于 `Project Cache Alloc`则卷缓存的大小过小。



.相关信息
* link:https://docs.netapp.com/us-en/ontap-cli/statistics-show.html["统计数据显示"^]

