---
permalink: disks-aggregates/determine-space-usage-aggregate-concept.html 
sidebar: sidebar 
keywords: space, usage, aggregate, local tier, volume 
summary: '您可以查看一个或多个本地层(聚合)中所有卷使用的空间量、以便采取措施释放更多空间。' 
---
= 确定本地层(聚合)中的空间使用量
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以查看一个或多个本地层(聚合)中所有卷使用的空间量、以便采取措施释放更多空间。

WAFL会为聚合级别元数据和性能预留总磁盘空间的一定百分比。  用于维护聚合中的卷的空间将从WAFL 预留中出来、并且无法更改。

在小于30 TB的聚合中、WAFL会为聚合级别元数据和性能预留总磁盘空间的10%。

从ONTAP 9.12.1开始、在容量大于或等于30 TB的聚合中、为聚合级别元数据和性能预留的磁盘空间量会减少、从而使聚合中的可用空间增加5%。此空间节省的可用性因您的平台和ONTAP版本而异。

[cols="30,30,40"]
|===
| ONTAP在聚合中预留的磁盘空间为30 TB或更高 | 适用场景平台 | 在ONTAP版本中 


| 5% | 所有AFF和FAS平台 | ONTAP 9.14.1及更高版本 


| 5% | AFF平台和FAS500f平台 | ONTAP 9.12.1及更高版本 


| 10% | 所有平台 | ONTAP 9.11.1及更高版本 
|===
您可以使用查看一个或多个聚合中所有卷的空间使用量 `aggregate show-space` 命令：这有助于您查看哪些卷在其所属聚合中占用的空间最多，以便您可以采取措施释放更多空间。

聚合中的已用空间直接受其包含的 FlexVol 卷中使用的空间影响。用于增加卷空间的措施也会影响聚合中的空间。


NOTE: 从ONTAP 9.15.1开始、提供了两个新的元数据计数器。加上对多个现有计数器的更改、您可以更清楚地查看已分配的用户数据量。请参见 link:../volumes/determine-space-usage-volume-aggregate-concept.html["确定卷或聚合中的空间使用量"] 有关详细信息 ...

中包括以下行 `aggregate show-space` 命令输出：

* *卷脚本*
+
聚合中所有卷占用空间的总数。它包括由所属聚合中所有卷的所有数据和元数据使用或预留的所有空间。

* *聚合元数据*
+
聚合所需的总文件系统元数据，例如分配位图和索引节点文件。

* * Snapshot 预留 *
+
根据卷大小为聚合 Snapshot 副本预留的空间量。它被视为已用空间，不可用于卷或聚合数据或元数据。

* * Snapshot预留不可用*
+
最初为聚合 Snapshot 预留分配的空间量，由于聚合 Snapshot 副本正在由与聚合关联的卷使用而无法用于聚合 Snapshot 副本。仅适用于具有非零聚合 Snapshot 预留的聚合。

* *已用总容量*
+
聚合中卷，元数据或 Snapshot 副本已用或预留的所有空间之和

* *已用物理空间总量*
+
当前用于数据的空间量 （而不是保留供将来使用）包括聚合 Snapshot 副本使用的空间



以下示例显示了 `aggregate show-space` Snapshot预留为5%的聚合的命令输出。如果 Snapshot 预留为 0 ，则不会显示该行。

....
cluster1::> storage aggregate show-space

						Aggregate : wqa_gx106_aggr1

      Feature                                   Used      Used%
      --------------------------------    ----------     ------
      Volume Footprints                      101.0MB         0%
      Aggregate Metadata                       300KB         0%
      Snapshot Reserve                        5.98GB         5%

      Total Used                              6.07GB         5%
      Total Physical Used                    34.82KB         0%
....
.相关信息
* link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Space_Usage["知识库文章：空间使用量"^]
* link:https://www.netapp.com/blog/free-up-storage-capacity-upgrade-ontap/["升级到ONTAP 9.12.1可释放5%的存储容量"^]

