---
permalink: disks-aggregates/disk-autoassignment-policy-concept.html 
sidebar: sidebar 
keywords: disk, auto-assign, spare, policy, automatic, assignment, disk ownership 
summary: 默认情况下、无主磁盘的自动分配处于启用状态。系统初始化10分钟后会自动分配磁盘所有权、在系统正常运行期间会每5分钟分配一次磁盘所有权。 
---
= 关于磁盘所有权的自动分配
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
默认情况下、无主磁盘的自动分配处于启用状态。系统初始化10分钟后会自动分配磁盘所有权、在系统正常运行期间会每5分钟分配一次磁盘所有权。

向系统添加新磁盘时、例如在更换故障磁盘、响应低备用磁盘消息或添加容量时、默认的自动分配策略会将磁盘所有权分配给作为备用磁盘的节点。您可以使用禁用自动分配或选择其他自动分配策略 `storage disk option modify` 命令：

默认的自动分配策略基于平台特定的特征、但它使用以下方法之一分配磁盘所有权：

|===


| 分配方法 | 对节点分配的影响 | 平台 


 a| 
托架
 a| 
偶数托架分配给节点A、奇数托架分配给节点B
 a| 
采用HA配置且具有一个共享磁盘架的入门级系统。



 a| 
磁盘架
 a| 
磁盘架中的所有磁盘都分配给节点A
 a| 
采用HA配置的入门级系统、其中一个堆栈包含两个或更多磁盘架、而MetroCluster 配置则包含每个节点一个堆栈、两个或更多磁盘架。



 a| 
拆分磁盘架
 a| 
磁盘架左侧的磁盘分配给节点A、右侧的磁盘分配给节点B新系统上的部分磁盘架出厂时已从磁盘架边缘向中心装入磁盘。
 a| 
AFF C190系统和某些MetroCluster 配置。



 a| 
堆栈
 a| 
堆栈中的所有磁盘都分配给节点A
 a| 
独立的入门级系统和所有其他配置。

|===
如果您的环境不需要使用默认分配方法、则可以使用指定托架、磁盘架或堆栈分配方法 `-autoassign-policy` 参数 `storage disk option modify` 命令：请注意以下规则：

* 如果尝试使用 `bay autoassign-policy` 对于非入门级平台、它将失败。
* 没有用于指定拆分磁盘架方法的相应非默认策略。


您也可以使用手动管理磁盘分配 `storage disk assign` 命令：

* 如果禁用自动分配、则新磁盘在分配到使用的节点之前不会作为备用磁盘使用 `storage disk assign` 命令：
* 如果您希望自动分配磁盘、并且您的多个堆栈或磁盘架必须具有不同的所有权、则必须在每个堆栈或磁盘架上手动分配一个磁盘、以便在每个堆栈或磁盘架上自动分配所有权。
* 如果启用了自动分配、而您手动将一个驱动器分配给未在活动策略中指定的节点、则自动分配将停止工作、并显示EMS消息。


了解更多信息 link:manual-assign-ownership-partitioned-disks-task.html["手动分配磁盘所有权"]。

您可以使用显示当前的自动分配设置 `storage disk option show` 命令：
