---
permalink: disks-aggregates/disk-autoassignment-policy-concept.html 
sidebar: sidebar 
keywords: disk, auto-assign, spare, policy, automatic, assignment, disk ownership 
summary: 默认情况下、无主磁盘的自动分配处于启用状态。在HA对初始化10分钟后自动分配磁盘所有权、在正常系统操作期间每5分钟自动分配一次磁盘所有权。 
---
= 了解ONTAP磁盘所有权的自动分配
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
默认情况下、无主磁盘的自动分配处于启用状态。在HA对初始化10分钟后自动分配磁盘所有权、在正常系统操作期间每5分钟自动分配一次磁盘所有权。

将新磁盘添加到HA对时、例如、在更换故障磁盘、响应"备用磁盘不足"消息或添加容量时、默认自动分配策略会将磁盘所有权作为备用磁盘分配给节点。

默认的自动分配策略基于平台特定的特征、如果HA对只有DS460C磁盘架、则基于DS460C磁盘架、并使用以下方法(策略)之一分配磁盘所有权：

|===


| 分配方法 | 对节点分配的影响 | 默认为分配方法的平台配置 


 a| 
托架
 a| 
偶数托架分配给节点A、奇数托架分配给节点B
 a| 
具有单个共享磁盘架的HA对配置中的入门级系统。



 a| 
磁盘架
 a| 
磁盘架中的所有磁盘都分配给节点A
 a| 
采用HA对配置的入门级系统、其中一个堆栈包含两个或更多磁盘架、而采用MetroCluster配置的每个节点一个堆栈、两个或更多磁盘架。



 a| 
拆分磁盘架

此`d属于的"默认`"值范围 `-autoassign-policy` 的参数 `storage disk option` 适用于适用平台和磁盘架配置的命令。
 a| 
磁盘架左侧的磁盘分配给节点A、右侧的磁盘分配给节点BHA对上的部分磁盘架出厂时已从磁盘架边缘向中心填充磁盘。
 a| 
大多数AFF平台和某些MetroCluster配置。



 a| 
堆栈
 a| 
堆栈中的所有磁盘都分配给节点A
 a| 
独立的入门级系统和所有其他配置。



 a| 
半抽屉

此`d属于的"默认`"值范围 `-autoassign-policy` 的参数 `storage disk option` 适用于适用平台和磁盘架配置的命令。
 a| 
DS460C抽盒左半部分中的所有驱动器(驱动器托架0到5)均分配给节点A；抽盒右半部分中的所有驱动器(驱动器托架6到11)均分配给节点B

在初始化仅包含DS460C磁盘架的HA对时、不支持自动分配磁盘所有权。您必须遵循半抽盒策略、手动为包含具有根分区的根/容器驱动器的驱动器分配所有权。
 a| 
在HA对初始化(启动)之后、仅包含DS460C磁盘架的HA对。

HA对启动后、系统会自动启用磁盘所有权自动分配、并使用半抽盒策略为其余驱动器(具有根分区的根驱动器/容器驱动器除外)以及未来添加的任何驱动器分配所有权。

如果您的HA对除了具有其他磁盘架型号外还具有DS460C磁盘架、则不会使用半抽盒策略。所使用的默认策略由平台特定的特征决定。

|===
自动分配设置和修改：

* 您可以使用显示当前的自动分配设置(开/关) `storage disk option show` 命令：
* 您可以使用禁用自动分配 `storage disk option modify` 命令：
* 如果您的环境不希望使用默认自动分配策略、则可以使用指定(更改)托架、磁盘架或堆栈分配方法 `-autoassign-policy` 中的参数 `storage disk option modify` 命令：
+
了解操作方法 link:configure-auto-assignment-disk-ownership-task.html["更改磁盘所有权自动分配的设置"]。

+
[NOTE]
====
半抽盒和分层磁盘架默认自动分配策略是唯一的、因为用户无法像托架、磁盘架和堆栈策略那样设置这些策略。

====


在高级驱动器分区(ADP)系统中、要在半填充磁盘架上执行自动分配、必须根据您的磁盘架类型将驱动器安装在正确的磁盘架托架中：

* 如果您的磁盘架不是DS460C磁盘架、请在最左侧和最右侧等量安装驱动器、并朝中间移动。例如、一个DS224C磁盘架的托架0-5中有六个驱动器、托架18-23中有六个驱动器。
* 如果您的磁盘架是DS460C磁盘架、请在每个抽盒的前排(驱动器托架0、3、6和9)中安装驱动器。对于其余驱动器、通过从前至后填充抽屉排、将其均匀分布在每个抽盒中。如果没有足够的驱动器来填充行、请成对安装、以便驱动器均匀地占据抽盒的左侧和右侧。
+
在每个抽盒的前排安装驱动器可确保空气流通、并防止过热。



[NOTE]
====
如果驱动器未安装在半填充磁盘架上的正确磁盘架托架中、则在容器驱动器发生故障并进行更换时、ONTAP不会自动分配所有权。在这种情况下、需要手动分配新容器驱动器。为容器驱动器分配所有权后、ONTAP会自动处理所需的任何驱动器分区和分区分配。

====
在某些情况下、如果自动分配不起作用、则需要使用手动分配磁盘所有权 `storage disk assign` 命令：

* 如果禁用自动分配、则新磁盘在手动分配给节点之前不能用作备用磁盘。
* 如果您希望自动分配磁盘、并且您的多个堆栈或磁盘架必须具有不同的所有权、则必须在每个堆栈或磁盘架上手动分配一个磁盘、以便在每个堆栈或磁盘架上自动分配所有权。
* 如果启用了自动分配、而您手动将一个驱动器分配给未在活动策略中指定的节点、则自动分配将停止工作、并显示EMS消息。


了解操作方法 link:manual-assign-disks-ownership-manage-task.html["手动分配未分区磁盘的磁盘所有权"]。

了解操作方法 link:manual-assign-ownership-partitioned-disks-task.html["手动分配已分区磁盘的磁盘所有权"]。

.相关信息
* link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-assign.html["storage disk assign"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-option-modify.html["存储磁盘选项修改"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-option-show.html["存储磁盘选项显示"^]

