---
permalink: disks-aggregates/flash-pool-aggregate-caching-policies-concept.html 
sidebar: sidebar 
keywords: cache, flash pool, policy, work 
summary: 缓存策略会应用于 Flash Pool 聚合中的卷。在更改缓存策略之前，您应了解这些策略的工作原理。 
---
= Flash Pool 聚合缓存策略的工作原理
:icons: font
:imagesdir: ../media/


[role="lead"]
通过 Flash Pool 聚合中卷的缓存策略，您可以将闪存部署为工作数据集的高性能缓存，同时对访问频率较低的数据使用成本较低的 HDD 。如果要为两个或更多 Flash Pool 聚合提供缓存，则应使用 Flash Pool SSD 分区功能在 Flash Pool 中的聚合之间共享 SSD 。

缓存策略会应用于 Flash Pool 聚合中的卷。在更改缓存策略之前，您应了解这些策略的工作原理。

在大多数情况下，默认缓存策略 `auto` 是最佳缓存策略。只有当其他策略可为您的工作负载提供更好的性能时，才应更改缓存策略。配置错误的缓存策略可能会严重降低卷性能；性能下降可能会随着时间的推移逐渐增加。

缓存策略将读取缓存策略与写入缓存策略结合使用。策略名称将读取缓存策略和写入缓存策略的名称串联在一起，并用连字符分隔。如果策略名称中没有连字符，则写入缓存策略为 "`none` " ，但 `auto` 策略除外。

除了 HDD 上存储的数据之外，读取缓存策略还会将一份数据副本放在缓存中，以优化未来的读取性能。对于将数据插入缓存以执行写入操作的读取缓存策略，缓存将作为 _write-through 缓存运行。

使用写入缓存策略插入到缓存中的数据仅存在于缓存中； HDD 中不存在副本。Flash Pool 缓存受 RAID 保护。启用写入缓存可使写入操作中的数据立即从缓存中读取，同时将数据写入 HDD ，直到其在缓存中过期为止。

您可以通过将 ` -caching-policy` 参数与 `volume create` 命令结合使用来更改 Flash Pool 聚合上的卷的缓存策略。在 Flash Pool 聚合上创建卷时，默认情况下会将 `auto` 缓存策略分配给该卷。

如果将卷从 Flash Pool 聚合移动到单层聚合，则会丢失其缓存策略；如果稍后将其移回 Flash Pool 聚合，则会为其分配默认缓存策略 `auto` 。如果在两个 Flash Pool 聚合之间移动卷，则会保留缓存策略。
