---
permalink: disks-aggregates/manual-assign-ownership-partitioned-disks-task.html 
sidebar: sidebar 
keywords: manual, assign, disk, ownership, partition, disks 
summary: 您可以手动设置容器磁盘或分区的所有权，也可以使用自动分配来设置，就像对未分区磁盘那样。 
---
= 手动分配已分区磁盘的所有权概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用CLI、您可以手动设置容器磁盘或分区的所有权、也可以像对待未分区磁盘一样使用自动分配来设置。

[NOTE]
====
如果半填充磁盘架中的容器磁盘发生故障并被更换，则 ONTAP 不会自动分配所有权。在这种情况下，任何新磁盘的分配都需要手动完成。要在半填充磁盘架上执行自动分配工作，请将磁盘等分放置在下半部分，并将 6 个磁盘放在最右侧托架上。即，托架 0-5 中有 6 个磁盘，托架 18-23 中有 6 个磁盘。在配置了 ADP 的系统中分配容器磁盘后， ONTAP 的软件将处理所需的任何分区和分区分配，而无需用户干预。

====
您可以在命令行界面中执行以下任务：

.手动分配具有根数据分区功能的磁盘
====
对于根数据分区、有三个自有实体(容器磁盘和两个分区)由HA对共同拥有。

容器磁盘和两个分区并不都由 HA 对中的同一节点拥有，只要它们全部由 HA 对中的一个节点拥有即可。但是、在本地层(聚合)中使用分区时、分区必须归拥有本地层的同一节点所有。

.步骤
. 使用命令行界面显示分区磁盘的当前所有权：
+
`storage disk show -disk _disk_name_ -partition-ownership`

. 将命令行界面权限级别设置为高级：
+
`set -privilege advanced`

. 根据要分配所有权的所有权实体，输入相应的命令：
+
[cols="25,75"]
|===


| 如果要为 ... 分配所有权 | 使用此命令 ... 


 a| 
容器磁盘
 a| 
`s存储磁盘分配 -disk _disk_name_ -owner _owner_name_`



 a| 
数据分区
 a| 
`s存储磁盘分配-disk _disk_name_-owner _owner_name_-data true`



 a| 
根分区
 a| 
`s存储磁盘分配-disk _disk_name_-owner _owner_name_-root true`

|===
+
如果已拥有任何所有权实体、则必须包括"`-force`"选项。



====
.手动分配具有根 - 数据 - 数据分区功能的磁盘
====
对于根-数据-数据分区、HA对共有四个自有实体(容器磁盘和三个分区)。

根 - 数据 - 数据分区功能可创建一个小分区作为根分区，并创建两个大小相等的较大数据分区。

参数必须与`disk assign`命令结合使用、才能为根-数据-数据分区磁盘分配正确的分区。您不能对存储池中的磁盘使用这些参数。默认值为"`false`"。

* `-data1 true`参数分配root-data1-data2分区磁盘的`data1`分区。
* `-data2 true`参数分配root-data1-data2分区磁盘的`data2`分区。


.步骤
. 使用命令行界面显示分区磁盘的当前所有权：
+
`storage disk show -disk _disk_name_ -partition-ownership`

. 将命令行界面权限级别设置为高级：
+
`set -privilege advanced`

. 根据要分配所有权的所有权实体，输入相应的命令：
+
[cols="25,75"]
|===


| 如果要为 ... 分配所有权 | 使用此命令 ... 


 a| 
容器磁盘
 a| 
`s存储磁盘分配 -disk _disk_name_ -owner _owner_name_`



 a| 
Data1 分区
 a| 
`s存储磁盘分配-disk _disk_name_-owner _owner_name_-data1 true`



 a| 
Data2 分区
 a| 
`s存储磁盘分配-disk _disk_name_-owner _owner_name_-data2 true`



 a| 
根分区
 a| 
`s存储磁盘分配-disk _disk_name_-owner _owner_name_-root true`

|===


如果已拥有任何所有权实体、则必须包括"`-force`"选项。

====