---
permalink: disks-aggregates/sizing-raid-groups-concept.html 
sidebar: sidebar 
keywords: consideration, size, raid groups 
summary: 配置最佳 RAID 组大小需要权衡各种因素。您必须确定哪些因素对要配置的聚合最重要— RAID 重建速度，防止因驱动器故障而导致数据丢失的风险，优化 I/O 性能以及最大限度地增加数据存储空间。 
---
= 调整 RAID 组大小的注意事项
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
配置最佳 RAID 组大小需要权衡各种因素。您必须确定哪些因素对要配置的聚合最重要— RAID 重建速度，防止因驱动器故障而导致数据丢失的风险，优化 I/O 性能以及最大限度地增加数据存储空间。

创建较大的 RAID 组时，您可以最大程度地利用数据存储空间来存储用于奇偶校验的相同存储量（也称为 "`奇偶校验税` " ）。另一方面，当较大 RAID 组中的磁盘发生故障时，重建时间会增加，从而在较长的时间内影响性能。此外，在一个 RAID 组中使用更多磁盘会增加同一 RAID 组中多个磁盘发生故障的可能性。



== HDD 或阵列 LUN RAID 组

在估算由 HDD 或阵列 LUN 组成的 RAID 组的规模时，应遵循以下准则：

* 聚合中的所有 RAID 组都应具有相同数量的磁盘。
+
虽然在一个聚合上，最多可以将不同 RAID 组中的磁盘数量减少 50% 或更多，但在某些情况下，这可能会导致性能瓶颈，因此最好避免这种情况。

* 建议的 RAID 组磁盘编号范围介于 12 到 20 之间。
+
如果需要，性能磁盘的可靠性最多可支持 28 个 RAID 组。

* 如果您可以使用多个 RAID 组磁盘编号满足前两条准则，则应选择更多的磁盘。




== Flash Pool 聚合中的 SSD RAID 组

SSD RAID 组大小可以与 Flash Pool 聚合中 HDD RAID 组的 RAID 组大小不同。通常，您应确保一个 Flash Pool 聚合只有一个 SSD RAID 组，以最大程度地减少奇偶校验所需的 SSD 数量。



== SSD 聚合中的 SSD RAID 组

在调整由 SSD 组成的 RAID 组的大小时，应遵循以下准则：

* 聚合中的所有 RAID 组都应具有相同数量的驱动器。
+
RAID 组的大小不必完全相同，但应尽可能避免在同一聚合中使用小于其他 RAID 组一半大小的任何 RAID 组。

* 对于 RAID-DP ，建议的 RAID 组大小范围介于 20 到 28 之间。

