---
permalink: disks-aggregates/sizing-raid-groups-concept.html 
sidebar: sidebar 
keywords: consideration, size, raid groups 
summary: '配置最佳 RAID 组大小需要权衡各种因素。对于要配置的本地层(聚合)、您必须确定哪些因素最重要—RAID重建速度、防止因驱动器故障而导致数据丢失的风险、优化I/O性能以及最大限度地增加数据存储空间。' 
---
= 调整 RAID 组大小的注意事项
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
配置最佳 RAID 组大小需要权衡各种因素。您必须确定哪些因素对您要配置的(本地层)聚合最重要—RAID重建速度、防止因驱动器故障而导致数据丢失的风险、优化I/O性能以及最大限度地增加数据存储空间。

创建较大的 RAID 组时，您可以最大程度地利用数据存储空间来存储用于奇偶校验的相同存储量（也称为 "`奇偶校验税` " ）。另一方面，当较大 RAID 组中的磁盘发生故障时，重建时间会增加，从而在较长的时间内影响性能。此外，在一个 RAID 组中使用更多磁盘会增加同一 RAID 组中多个磁盘发生故障的可能性。



== HDD 或阵列 LUN RAID 组

在估算由 HDD 或阵列 LUN 组成的 RAID 组的规模时，应遵循以下准则：

* 本地层(聚合)中的所有RAID组都应具有相同数量的磁盘。
+
虽然在一个本地层上、最多可以将不同RAID组中的磁盘数量减少50%或更多、但在某些情况下、这可能会导致性能瓶颈、因此最好避免这种情况。

* 建议的 RAID 组磁盘编号范围介于 12 到 20 之间。
+
如果需要，性能磁盘的可靠性最多可支持 28 个 RAID 组。

* 如果您可以使用多个 RAID 组磁盘编号满足前两条准则，则应选择更多的磁盘。




== Flash Pool本地层中的SSD RAID组(聚合)

SSD RAID组大小可以与Flash Pool本地层(聚合)中HDD RAID组的RAID组大小不同。通常、您应确保Flash Pool本地层只有一个SSD RAID组、以最大程度地减少奇偶校验所需的SSD数量。



== SSD本地层中的SSD RAID组(聚合)

在调整由 SSD 组成的 RAID 组的大小时，应遵循以下准则：

* 本地层(聚合)中的所有RAID组都应具有类似数量的驱动器。
+
RAID组的大小不必完全相同、但应尽可能避免在同一本地层中使用小于其他RAID组一半大小的任何RAID组。

* 对于 RAID-DP ，建议的 RAID 组大小范围介于 20 到 28 之间。

