---
permalink: flexgroup/configure-automatic-grow-shrink-task.html 
sidebar: sidebar 
keywords: configure, flexgroup, volume, automatic, grow, shrink, size 
summary: 从 ONTAP 9.3 开始，您可以将 FlexGroup 卷配置为根据其当前所需的空间量自动增长和缩减。 
---
= 将 FlexGroup 卷配置为自动增长和缩减其大小
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
从 ONTAP 9.3 开始，您可以将 FlexGroup 卷配置为根据其当前所需的空间量自动增长和缩减。

.开始之前
FlexGroup 卷必须处于联机状态。

.关于此任务
您可以在两种模式下自动调整 FlexGroup 卷的大小：

* 自动增加卷的大小 (`grow` 模式)
+
如果聚合可以提供更多空间，则自动增长有助于防止 FlexGroup 卷用尽空间。您可以配置卷的最大大小。根据写入卷的数据量与当前已用空间量和设置的任何阈值的关系，系统会自动触发增加。

+
默认情况下，卷可以增长到的最大大小为启用自动增长时大小的 120% 。如果需要确保卷的大小可以增长到大于该大小，则必须相应地设置卷的最大大小。

* 自动缩减卷大小 (`grow_shrink` 模式)
+
自动缩减可防止卷超出所需大小，从而腾出聚合中的空间供其他卷使用。

+
自动缩减只能与自动增长结合使用，以满足不断变化的空间需求，而不能单独使用。启用自动缩减后， ONTAP 会自动管理卷的缩减行为，以防止自动增长和自动缩减操作出现无限循环。



随着卷的增长，它可以包含的最大文件数可能会自动增加。卷缩减后，其可包含的最大文件数保持不变，并且卷不能自动缩减到低于其当前最大文件数对应的大小。因此，可能无法将卷一直自动缩减到其原始大小。

.步骤
. 将卷配置为自动增长和缩减其大小： `volume autosize -vserver vserver_name -volume vol_name -mode [grow | grow_shrink]`
+
此外，还可以指定卷增长或缩减的最大大小，最小大小和阈值。

+
以下命令将为名为 fg1 的卷启用自动大小更改。如果卷已满 70% ，则此卷的大小将配置为增长到最大 5 TB 。

+
[listing]
----
cluster1::> volume autosize -volume fg1 -mode grow -maximum-size 5TB -grow-threshold-percent 70
vol autosize: volume "vs_src:fg1" autosize settings UPDATED.
----

