---
permalink: flexgroup/convert-flexvol-snapmirror-relationship-task.html 
sidebar: sidebar 
keywords: convert, flexvol, volume, snapmirror, relation, flexgroup 
summary: 要在 ONTAP 中将 FlexVol 卷 SnapMirror 关系转换为 FlexGroup 卷 SnapMirror 关系，必须先转换目标 FlexVol 卷，然后再转换源 FlexVol 卷。 
---
= 将ONTAP FlexVol volume SnapMirror关系转换为ONTAP FlexGroup卷SnapMirror关系
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
要在 ONTAP 中将 FlexVol 卷 SnapMirror 关系转换为 FlexGroup 卷 SnapMirror 关系，必须先转换目标 FlexVol 卷，然后再转换源 FlexVol 卷。

.关于此任务
* 只有SnapMirror异步关系才支持FlexGroup转换。
* 转换时间取决于多个变量。其中一些变量包括：
+
** 控制器的CPU
** 其他应用程序对CPU的利用率
** 初始快照中的数据量
** 网络带宽
** 其他应用程序使用的带宽




.开始之前
* 要转换的 FlexVol 卷必须处于联机状态。
* SnapMirror 关系中的源 FlexVol 卷不能是多个 SnapMirror 关系的源卷。
+
从ONTAP 9.1.1开始、FlexGroup 卷支持扇出SnapMirror关系。有关详细信息，请参见 link:../flexgroup/create-snapmirror-cascade-fanout-reference.html#considerations-for-creating-cascading-relationships["为FlexGroup卷创建SnapMirror级联和扇出关系的注意事项"]。

* FlexVol 卷上的操作和配置必须与转换过程兼容。
+
如果 FlexVol 卷不兼容，并且卷转换已中止，则会生成一条错误消息。您可以采取更正操作并重试转换。



.步骤
. 验证SnapMirror关系是否运行正常：
+
[source, cli]
----
snapmirror show
----
+
只能转换 XDP 类型的镜像关系。

+
示例

+
[listing]
----
cluster2::> snapmirror show
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vs0:src_dpv DP   vs2:dst_dpv  Snapmirrored
                                      Idle           -         true    -
vs0:src_xdp XDP  vs2:dst_xdp  Snapmirrored
                                      Idle           -         true    -
----
. 验证源卷是否与转换兼容：
+
.. 登录到高级权限模式：
+
[source, cli]
----
set -privilege advanced
----
.. 验证转换过程：
+
[source, cli]
----
volume conversion start -vserver <src_svm_name> -volume <src_vol> -check-only true
----
+
示例

+
[listing]
----
volume conversion start -vserver vs1 -volume src_vol -check-only true
----
+
在转换卷之前，必须更正所有错误。



. 将目标 FlexVol 卷转换为 FlexGroup 卷。
+
.. 将FlexVol SnapMirror关系静用：
+
[source, cli]
----
snapmirror quiesce -destination-path <dest_svm:dest_volume>
----
+
示例

+
[listing]
----
cluster2::> snapmirror quiesce -destination-path vs2:dst_xdp
----
.. 开始转换：
+
[source, cli]
----
volume conversion start -vserver <dest_svm> -volume <dest_volume>
----
+
示例

+
[listing]
----
cluster-1::> volume conversion start -vserver vs2 -volume dst_xdp

Warning: After the volume is converted to a FlexGroup, it will not be possible
to change it back to a flexible volume.
Do you want to continue? {y|n}: y

[Job 510] Job succeeded: SnapMirror destination volume "dst_xdp" has been successfully converted to a FlexGroup volume.
You must now convert the relationship's source volume, "vs0:src_xdp", to a FlexGroup.
Then, re-establish the SnapMirror relationship using the "snapmirror resync" command.
----


. 将源FlexVol卷转换为FlexGroup卷：`
+
[source, cli]
----
volume conversion start -vserver <src_svm_name> -volume <src_vol_name>
----
+
示例

+
[listing]
----
cluster-1::> volume conversion start -vserver vs0 -volume src_xdp

Warning: Converting flexible volume "src_xdp" in Vserver "vs0" to a FlexGroup
         will cause the state of all Snapshot copies from the volume to be set
         to "pre-conversion". Pre-conversion snapshots cannot be
         restored.
Do you want to continue? {y|n}: y
[Job 57] Job succeeded: success
----
. 重新同步此关系：
+
[source, cli]
----
snapmirror resync -destination-path dest_svm_name:dest_volume
----
+
示例

+
[listing]
----
cluster2::> snapmirror resync -destination-path vs2:dst_xdp
----


.完成后
您必须确保在扩展源 FlexGroup 卷以包含更多成分卷时，目标卷也会进行扩展。

.相关信息
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-quiesce.html["SnapMirror 静默"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-resync.html["snapmirror resync"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-show.html["snapmirror show"^]

