---
permalink: flexgroup/convert-flexvol-svm-dr-relationship-task.html 
sidebar: sidebar 
keywords: convert, flexvol, flexgroup, svm-dr 
summary: 从 ONTAP 9.10.1 开始，您可以将 FlexVol 卷转换为 SVM-DR 源上的 FlexGroup 卷。 
---
= 将 FlexVol 卷转换为 SVM-DR 关系中的 FlexGroup 卷
:icons: font
:imagesdir: ../media/


[role="lead"]
从 ONTAP 9.10.1 开始，您可以将 FlexVol 卷转换为 SVM-DR 源上的 FlexGroup 卷。

.您将需要什么
* 要转换的 FlexVol 卷必须处于联机状态。
* FlexVol 卷上的操作和配置必须与转换过程兼容。
+
如果 FlexVol 卷存在任何不兼容性，并且已取消卷转换，则会生成一条错误消息。您可以采取更正操作并重试转换。有关详细信息，请参见 xref:convert-flexvol-concept.html#considerations-for-converting-flexvol-volumes-to-flexgroup-volumes [将 FlexVol 卷转换为 FlexGroup 卷的注意事项]



.步骤
. 从目标位置更新 SVM-DR 关系：
+
` * snapmirror update -destination-path destination_svm_name ： -source-path source_svm_name ： *`

. 确保 SVM-DR 关系处于 SnapMirrored 状态且未断开：
+
` * SnapMirror show*`

. 从目标 SVM 中，验证 FlexVol 卷是否已做好转换准备：
+
` * 卷转换 start -vserver svm_name -volume vol_name -check-only true*`

. 从目标上，禁用 SVM-DR 关系上的传输：
+
` * snapmirror quiesce -destination-path dest_svm ： *`

. 开始转换：
+
` * 卷转换 start -vserver svm_name -volume vol_name*`

. 验证转换是否成功：
+
` * volume show vol_name -fields -volume-style-extended" ， state*`

+
[listing]
----
cluster-1::*> volume show my_volume -fields volume-style-extended,state

vserver   volume     state    volume-style-extended
-------       ---------     ------    ---------------------
vs0     my_volume  online  flexgroup
----
. 从目标集群恢复关系的传输：
+
` * snapmirror resume -destination-path dest_svm ： *`

. 在目标集群中，执行更新以将转换传播到目标：
+
` * snapmirror update -destination-path dest_sVM ： *`

. 确保 SVM-DR 关系处于 SnapMirrored 状态且未断开：
+
` * SnapMirror show*`

. 确保在目标上进行转换：
+
` * volume show vol_name -fields -volume-style-extended" ， state*`

+
[listing]
----
cluster-2::*> volume show my_volume -fields volume-style-extended,state

vserver    volume       state     volume-style-extended
-------       -------           ------     ---------------------
vs0_dst   my_volume  online  flexgroup
----

