---
permalink: flexgroup/convert-flexvol-svm-dr-relationship-task.html 
sidebar: sidebar 
keywords: convert, flexvol, flexgroup, svm-dr 
summary: 从 ONTAP 9.10.1 开始，您可以将 FlexVol 卷转换为 SVM-DR 源上的 FlexGroup 卷。 
---
= 将ONTAP FlexVol volume转换为SVM-DR关系中的FlexGroup卷
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
从 ONTAP 9.10.1 开始，您可以将 FlexVol 卷转换为 SVM-DR 源上的 FlexGroup 卷。

.开始之前
* 要转换的 FlexVol 卷必须处于联机状态。
* FlexVol 卷上的操作和配置必须与转换过程兼容。
+
如果 FlexVol 卷存在任何不兼容性，并且已取消卷转换，则会生成一条错误消息。您可以采取更正操作并重试转换。
有关详细信息，请参见 link:convert-flexvol-concept.html["将 FlexVol 卷转换为 FlexGroup 卷的注意事项"]



.步骤
. 使用高级权限模式登录： `set -privilege advanced`
. 从目标位置更新 SVM-DR 关系：
+
[source, cli]
----
snapmirror update -destination-path <destination_svm_name>: -source-path <source_svm_name>:
----
+
[NOTE]
====
您必须在选项中的SVM名称后面输入冒号(：) `-destination-path` 。

====
. 确保 SVM-DR 关系处于 SnapMirrored 状态且未断开：
+
[source, cli]
----
snapmirror show
----
. 从目标 SVM 中，验证 FlexVol 卷是否已做好转换准备：
+
[source, cli]
----
volume conversion start -vserver <svm_name> -volume <vol_name> -check-only true
----
+
如果此命令生成除"此为目标SVMDR卷"以外的任何错误、您可以采取适当的更正操作、再次运行此命令并继续进行转换。

. 从目标上，禁用 SVM-DR 关系上的传输：
+
[source, cli]
----
snapmirror quiesce -destination-path <dest_svm>:
----
+
[NOTE]
====
您必须在选项中的SVM名称后面输入冒号(：) `-destination-path` 。

====
. 从源集群中、开始转换：
+
[source, cli]
----
volume conversion start -vserver <svm_name> -volume <vol_name>
----
. 验证转换是否成功：
+
[source, cli]
----
volume show <vol_name> -fields volume-style-extended,state
----
+
[listing]
----
cluster-1::*> volume show my_volume -fields volume-style-extended,state

vserver  volume     state    volume-style-extended
-------  ---------  ------   ---------------------
vs0      my_volume  online   flexgroup
----
. 从目标集群恢复关系的传输：
+
[source, cli]
----
snapmirror resume -destination-path <dest_svm>:
----
+
[NOTE]
====
您必须在选项中的SVM名称后面输入冒号(：) `-destination-path` 。

====
. 在目标集群中，执行更新以将转换传播到目标：
+
[source, cli]
----
snapmirror update -destination-path <dest_svm>:
----
+
[NOTE]
====
您必须在选项中的SVM名称后面输入冒号(：) `-destination-path` 。

====
. 确保 SVM-DR 关系处于 SnapMirrored 状态且未断开：
+
[source, cli]
----
snapmirror show
----
. 确保在目标上进行转换：
+
[source, cli]
----
volume show <vol_name> -fields volume-style-extended,state
----
+
[listing]
----
cluster-2::*> volume show my_volume -fields volume-style-extended,state

vserver  volume     state   volume-style-extended
-------  -------    ------  ---------------------
vs0_dst  my_volume  online  flexgroup
----

