---
permalink: flexgroup/create-snapvault-relationship-task.html 
sidebar: sidebar 
keywords: create, snapvault, relationship, flexgroup, volumes 
summary: 您可以配置 SnapVault 关系并为此关系分配 SnapVault 策略以创建 SnapVault 备份。 
---
= 为 FlexGroup 卷创建 SnapVault 关系
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以配置 SnapVault 关系并为此关系分配 SnapVault 策略以创建 SnapVault 备份。

您必须了解为 FlexGroup 卷创建 SnapVault 关系的注意事项。

.步骤
. 创建类型为 `DP` 的目标 FlexGroup 卷，该卷的成分卷数与源 FlexGroup 卷的成分卷数相同：
+
.. 从源集群中，确定源 FlexGroup 卷中的成分卷数： `volume show -volume volume_name* -is-constituent true`
+
[listing]
----
cluster1::> volume show  -volume src* -is-constituent true
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
vss       src          -            online     RW         400TB   172.86GB  56%
vss       src__0001    Aggr_cmode   online     RW         25GB    10.86TB   56%
vss       src__0002    aggr1        online     RW         25TB    10.86TB   56%
vss       src__0003    Aggr_cmode   online     RW         25TB    10.72TB   57%
vss       src__0004    aggr1        online     RW         25TB    10.73TB   57%
vss       src__0005    Aggr_cmode   online     RW         25TB    10.67TB   57%
vss       src__0006    aggr1        online     RW         25TB    10.64TB   57%
vss       src__0007    Aggr_cmode   online     RW         25TB    10.63TB   57%
...
----
.. 从目标集群中，创建类型为 `DP` 的目标 FlexGroup 卷，其成分卷数与源 FlexGroup 卷的成分卷数相同。
+
[listing]
----
cluster2::> volume create -vserver vsd -aggr-list aggr1,aggr2 -aggr-list-multiplier 8 -size 400TB -type DP dst

Warning: The FlexGroup volume "dst" will be created with the following number of constituents of size 25TB: 16.
Do you want to continue? {y|n}: y
[Job 766] Job succeeded: Successful
----
.. 从目标集群中，验证目标 FlexGroup 卷中的成分卷数： `volume show -volume volume_name* -is-constituent true`
+
[listing]
----
cluster2::> volume show  -volume dst* -is-constituent true
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
vsd       dst          -            online     RW         400TB   172.86GB  56%
vsd       dst__0001    Aggr_cmode   online     RW         25GB    10.86TB   56%
vsd       dst__0002    aggr1        online     RW         25TB    10.86TB   56%
vsd       dst__0003    Aggr_cmode   online     RW         25TB    10.72TB   57%
vsd       dst__0004    aggr1        online     RW         25TB    10.73TB   57%
vsd       dst__0005    Aggr_cmode   online     RW         25TB    10.67TB   57%
vsd       dst__0006    aggr1        online     RW         25TB    10.64TB   57%
vsd       dst__0007    Aggr_cmode   online     RW         25TB    10.63TB   57%
...
----


. 创建作业计划： `job schedule cron create -name job_name -month month -dayofweek day_of_week -day day_of_month -hour -minute minute`
+
对于 ` - 月` ， ` - 天 / 周` 和 ` - 小时` ，您可以指定 `所有` 来分别按每月，一周中的一天和每小时运行作业。

+
以下示例将创建一个名为 `my_weekly` 的作业计划，该计划将在星期六凌晨 3 ： 00 运行：

+
[listing]
----
cluster1::> job schedule cron create -name my_weekly -dayofweek "Saturday" -hour 3 -minute 0
----
. 创建 SnapVault 策略，然后为 SnapVault 策略定义规则：
+
.. 为 SnapVault 关系创建类型为 `vault` 的自定义策略： `snapmirror policy create -vserver svm_name -policy policy_name -type vault`
.. 为 SnapVault 策略定义一条规则，用于确定在初始化和更新操作期间传输哪些 Snapshot 副本： `snapmirror policy add-rule -vserver svm_name -policy policy_for_rule - snapmirror-label snapmirror-label -keep retention_count -schedule schedule`


+
如果不创建自定义策略，则应为 SnapVault 关系指定 `XDPDefault` 策略。

. 创建 SnapVault 关系： `snapmirror create -source-path src_sVM ： src_flexgroup -destination-path dest_sVM ： dest_flexgroup -type XDP -schedule schedule_name -policy XDPDefault`
+
在 ONTAP 9.4 及更早版本中，如果未使用 `snapmirror create` 命令指定策略，则默认使用 `MirrorAllSnapshots` 策略。在 ONTAP 9.5 中，如果未使用 `snapmirror create` 命令指定策略，则默认使用 `MirrorAndVault` 策略。

+
[listing]
----
cluster2::> snapmirror create -source-path vss:srcFG -destination-path vsd:dstFG -type XDP -schedule Daily -policy XDPDefault
----
. 从目标集群中，通过执行基线传输来初始化 SnapVault 关系： `snapmirror initialize -destination-path dest_sVM ： dest_flexgroup`
+
[listing]
----
cluster2::> snapmirror initialize -destination-path vsd:dst
Operation is queued: snapmirror initialize of destination "vsd:dst".
----

