---
permalink: flexgroup/create-svm-disaster-recovery-relationship-task.html 
sidebar: sidebar 
keywords: create, svm, disaster, recovery, svm dr, svm-dr, relationship, flexgroup, volume, flex group, flexclone, flex clone 
summary: 从 ONTAP 9.1.1 开始，您可以使用 FlexGroup 卷创建 SVM 灾难恢复（ SVM DR ）关系。SVM DR 关系可通过同步和复制 SVM 配置及其数据，提供冗余并在发生灾难时恢复 FlexGroup 。SVM DR 需要 SnapMirror 许可证。 
---
= 为 FlexGroup 卷创建 SVM 灾难恢复关系
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
从 ONTAP 9.1.1 开始，您可以使用 FlexGroup 卷创建 SVM 灾难恢复（ SVM DR ）关系。SVM DR 关系可通过同步和复制 SVM 配置及其数据，提供冗余并在发生灾难时恢复 FlexGroup 。SVM DR 需要 SnapMirror 许可证。

.开始之前
您无法创建符合以下条件的FlexGroup SVM DR关系。

* 已存在 FlexClone FlexGroup 配置
* FlexGroup 卷包含 FabricPool 配置
* FlexGroup卷是级联关系的一部分
* FlexGroup卷是扇出关系的一部分、集群运行的ONTAP版本早于ONTAP 9.12.1。(从ONTAP 9.13.1开始、支持扇出关系。)


.关于此任务
* 两个集群中的所有节点都必须与添加了 SVM DR 支持的节点运行相同的 ONTAP 版本（ ONTAP 9.9.1 或更高版本）。
* 主站点和二级站点之间的 SVM DR 关系应运行正常，并且在主 SVM 和二级 SVM 上都应有足够的空间来支持 FlexGroup 卷。
* 在创建FlexGroup SVM DR关系时、如果此关系中的FlexGroup卷属于扇出关系、则应注意以下要求：
+
** 源集群和目标集群必须运行ONTAP 9.13.1或更高版本。
** 使用FlexGroup 卷的SVM DR支持对八个站点建立SnapMirror扇出关系。




有关创建 SVM DR 关系的信息，请参见 https://["管理 SnapMirror SVM 复制"]。

.步骤
. 创建 SVM DR 关系或使用现有关系。
+
https://["复制整个 SVM 配置"]

. 在主站点上使用所需数量的成分卷创建 FlexGroup 卷。
+
link:create-task.html["创建 FlexGroup 卷"]。

+
请等待 FlexGroup 及其所有成分卷均已创建，然后再继续。

. 要复制FlexGroup卷、请更新二级站点上的SVM： `snapmirror update -destination-path destination_svm_name: -source-path source_svm_name:`
+
您还可以输入来检查是否已存在计划的SnapMirror更新 `snapmirror show -fields schedule`

. 在二级站点上，验证 SnapMirror 关系是否运行正常： `snapmirror show`
+
[listing]
----
cluster2::> snapmirror show
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vs1:        XDP  vs1_dst:     Snapmirrored
                                      Idle           -         true    -
----
. 从二级站点上，验证新的 FlexGroup 卷及其成分卷是否存在： `snapmirror show -expand`
+
[listing]
----
cluster2::> snapmirror show -expand
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vs1:        XDP  vs1_dst:     Snapmirrored
                                      Idle           -         true    -
vs1:fg_src  XDP  vs1_dst:fg_src
                              Snapmirrored
                                      Idle           -         true    -
vs1:fg_src__0001
            XDP  vs1_dst:fg_src__0001
                              Snapmirrored
                                      Idle           -         true    -
vs1:fg_src__0002
            XDP  vs1_dst:fg_src__0002
                              Snapmirrored
                                      Idle           -         true    -
vs1:fg_src__0003
            XDP  vs1_dst:fg_src__0003
                              Snapmirrored
                                      Idle           -         true    -
vs1:fg_src__0004
            XDP  vs1_dst:fg_src__0004
                              Snapmirrored
                                      Idle           -         true    -
6 entries were displayed.
----

