---
permalink: flexgroup/expand-destination-snapmirror-relationship-task.html 
sidebar: sidebar 
keywords: expand, destination, flexgroup, volume, snapmirror, relationship 
summary: 您可以自动或手动扩展目标 FlexGroup 卷并重新建立 SnapMirror 关系。默认情况下， SnapMirror 关系设置为自动扩展，如果源卷扩展，则目标 FlexGroup 卷会自动扩展。 
---
= 展开SnapMirror关系的目标ONTAP FlexGroup卷
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以自动或手动扩展目标 FlexGroup 卷并重新建立 SnapMirror 关系。默认情况下， SnapMirror 关系设置为自动扩展，如果源卷扩展，则目标 FlexGroup 卷会自动扩展。

.开始之前
* 源 FlexGroup 卷必须已扩展。
* SnapMirror关系必须位于中 `SnapMirrored` 状态。
+
不得中断或删除 SnapMirror 关系。



.关于此任务
* 创建目标 FlexGroup 卷时，默认情况下会将此卷设置为自动扩展。
+
如果需要，您可以修改目标 FlexGroup 卷以进行手动扩展。

+
[NOTE]
====
最佳实践是自动扩展目标 FlexGroup 卷。

====
* 所有 SnapMirror 操作都将失败，直到源 FlexGroup 卷和目标 FlexGroup 卷都已扩展并具有相同数量的成分卷为止。
* 如果在中断或删除 SnapMirror 关系后扩展目标 FlexGroup 卷，则无法重新同步原始关系。
+
如果要重复使用目标FlexGroup卷、请勿在删除SnapMirror关系后扩展此卷。



.选项
* 执行更新传输以自动扩展目标 FlexGroup 卷：
+
.. 执行SnapMirror更新传输： `snapmirror update -destination-path svm:vol_name`
.. 验证SnapMirror关系的状态是否在中 `SnapMirrored` 状态： `snapmirror show`
+
[listing]
----
cluster2::> snapmirror show
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vs_src:src_fg
            XDP  vs_dst:dst_fg
                              Snapmirrored
                                      Idle           -         true   -
----


+
根据聚合的大小和可用性，系统会自动选择聚合，并将与源 FlexGroup 卷的成分卷匹配的新成分卷添加到目标 FlexGroup 卷。扩展后，系统会自动触发重新同步操作。

* 手动扩展目标 FlexGroup 卷：
+
.. 如果SnapMirror关系处于自动扩展模式、请将SnapMirror关系设置为手动扩展模式： `snapmirror modify -destination-path svm:vol_name -is-auto-expand-enabled false`
+
[listing]
----
cluster2::> snapmirror modify -destination-path vs_dst:dst_fg -is-auto-expand-enabled false
Operation succeeded: snapmirror modify for the relationship with destination "vs_dst:dst_fg".
----
.. 将SnapMirror关系静用： `snapmirror quiesce -destination-path svm:vol_name`
+
[listing]
----
cluster2::> snapmirror quiesce -destination-path vs_dst:dst_fg
Operation succeeded: snapmirror quiesce for destination "vs_dst:dst_fg".
----
.. 扩展目标FlexGroup卷： `+volume expand -vserver vserver_name -volume fg_name -aggr-list aggregate name,... [-aggr-list-multiplier constituents_per_aggr]+`
+
[listing]
----
cluster2::> volume expand -volume dst_fg -aggr-list aggr1 -aggr-list-multiplier 2  -vserver vs_dst

Warning: The following number of constituents of size 50GB will be added to FlexGroup "dst_fg": 2.
Do you want to continue? {y|n}: y
[Job 68] Job succeeded: Successful
----
.. 重新同步SnapMirror关系： `snapmirror resync -destination-path svm:vol_name`
+
[listing]
----
cluster2::> snapmirror resync -destination-path vs_dst:dst_fg
Operation is queued: snapmirror resync to destination "vs_dst:dst_fg".
----
.. 验证SnapMirror关系的状态是否为 `SnapMirrored`： `snapmirror show`
+
[listing]
----
cluster2::> snapmirror show
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vs_src:src_fg
            XDP  vs_dst:dst_fg
                              Snapmirrored
                                      Idle           -         true   -
----




.相关信息
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-quiesce.html["SnapMirror 静默"^]

