---
permalink: flexgroup/fast-directory-delete-asynchronous-task.html 
sidebar: sidebar 
keywords: perform, directory, delete, files, asynchronous, share, flexvol, flex vol, flexgroup, flex group, cancel 
summary: 从ONTAP 9.8开始、您可以使用volume file async-delete命令在后台从Linux和Windows客户端共享中删除文件和目录。您可以对 FlexVol 和 FlexGroup 卷执行异步删除。 
---
= 在ONTAP集群上异步删除目录
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
从Linux-8开始、您可以使用异步删除功能异步(即在后台)从ONTAP 9和Windows客户端共享中删除目录。集群和SVM管理员可以对FlexVol 和FlexGroup 卷执行异步删除操作。

如果您使用的ONTAP版本早于SVM.11.1、则必须是使用高级权限模式的集群管理员或ONTAP 9管理员。

从ONTAP 9.11.1开始、存储管理员可以授予对卷的权限、以允许NFS和SMB客户端执行异步删除操作。有关详细信息，请参见 link:manage-client-async-dir-delete-task.html["管理客户端异步删除目录的权限"]。

从CLI.8开始、您可以使用ONTAP ONTAP 9使用异步删除功能。从ONTAP 9.1.1开始、您可以在System Manager中使用此功能。有关此过程的详细信息，请参见link:../task_nas_file_system_analytics_take_corrective_action.html["根据分析结果采取更正操作"]。

[role="tabbed-block"]
====
.System Manager
--
. 单击 * 存储 > 卷 * ，然后单击 * 资源管理器 * 。
+
将鼠标悬停在文件或文件夹上时，将显示删除选项。一次只能删除一个对象。




NOTE: 删除目录和文件后，不会立即显示新的存储容量值。

--
.命令行界面
--
*使用命令行界面执行异步删除*

. 进入高级权限模式：
+
`-privilege advance`

. 删除FlexVol 或FlexGroup 卷上的目录：
+
`volume file async-delete start -vserver vserver_name -volume volume_name -path file_path -throttle throttle`

+
最小限制值为 10 ，最大值为 100 ， 000 ，默认值为 5000 。

+
以下示例将删除名为 d2 的目录，该目录位于名为 d1 的目录中。

+
....
cluster::*>volume file async-delete start -vserver vs1 -volume vol1 -path d1/d2
....
. 验证是否已删除此目录：
+
`event log show`

+
以下示例显示了成功删除目录后事件日志的输出。

+
....
cluster-cli::*> event log show
Time                 Node             Severity      Event
-------------------  ---------------- ------------- --------------------
MM/DD/YYYY 00:11:11  cluster-vsim     INFORMATIONAL asyncDelete.message.success: Async delete job on path d1/d2 of volume (MSID: 2162149232) was completed.
....


*取消目录删除作业*

. 进入高级权限模式：
+
`set -privilege advanced`

. 验证目录删除是否正在进行中：
+
`volume file async-delete show`

+
如果显示SVM、卷、作业ID和目录路径、则可以取消作业。

. 取消目录删除：
+
`volume file async-delete cancel -vserver _SVM_name_ -volume _volume_name_ -jobid _job_id_`



--
====