---
permalink: flexgroup/increase-capacity-task.html 
sidebar: sidebar 
keywords: increase, size, flexgroup, volume, flex group 
summary: 通过向卷的现有组成部分添加更多容量或通过使用新成员卷扩展 FlexGroup 卷来增加 FlexGroup 卷的大小。 
---
= 增加ONTAP FlexGroup卷的大小
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以通过向FlexGroup卷的现有成员卷(成分卷)添加更多容量或使用新成员卷扩展FlexGroup卷来增加FlexGroup卷的大小。一个FlexGroup卷的成员卷不能超过200个。

.开始之前
聚合中必须有足够的可用空间。

.关于此任务
如果要添加更多空间，可以增加 FlexGroup 卷的总大小。增加FlexGroup卷的大小会调整FlexGroup卷的现有成员卷的大小。

如果要提高性能，可以扩展 FlexGroup 卷。在以下情况下、您可能需要扩展FlexGroup卷并添加新成员卷：

* 已向集群添加新节点。
* 已在现有节点上创建新的本地层(聚合)。
* FlexGroup卷的现有成员卷已达到硬件的最大FlexVol大小(如果已启用、则为100 TB或300 TB)、因此、如果不添加其他成员卷、link:../volumes/enable-large-vol-file-support-task.html["支持大卷"]则无法调整FlexGroup卷的大小。


[NOTE]
====
如果您修改 FlexGroup 卷以包含更多成员，则先前创建的快照将被视为“部分”，并且只能由来自 `.snapshot`目录或“*以前的版本*”选项卡。

如果快照被视为“部分”，则不能用于 SnapRestore 操作。但是，部分快照可用于从 `.snapshot`目录或“*以前的版本*”选项卡。

====
在ONTAP 9.3之前的版本中、建立FlexGroup关系后、请勿扩展SnapMirror卷。如果在 ONTAP 9.3 之前的版本中中断 SnapMirror 关系后扩展源 FlexGroup 卷，则必须再次向目标 FlexGroup 卷执行基线传输。从 ONTAP 9.3 开始，您可以扩展 SnapMirror 关系中的 FlexGroup 卷。

.步骤
. 根据需要通过提高 FlexGroup 卷的容量或性能来增加 FlexGroup 卷的大小：
+
|===


| 如果要增加 ... | 然后执行此操作 ... 


 a| 
FlexGroup 卷的容量
 a| 
调整FlexGroup卷的成员卷大小：

`volume modify -vserver vserver_name -volume fg_name -size new_size`



 a| 
FlexGroup 卷的性能
 a| 
通过添加新成员卷(成分卷)来扩展FlexGroup卷：

`+volume expand -vserver vserver_name -volume fg_name -aggr-list aggregate name,... [-aggr-list-multiplier constituents_per_aggr]+`

的默认值 `-aggr-list-multiplier` 参数为1。

使用扩展FlexGroup卷时link:../fabricpool/index.html["FabricPool"]、所有本地层(聚合)都必须附加到同一云层。

|===


假设现有聚合(本地层)或成员卷未达到其最大容量(每个聚合为100/300 TB或20亿个文件)、则最好增加FlexGroup卷的总大小、而不是添加更多成员卷。

只有在无法增加现有卷大小或文件数量或者要在新硬件之间扩展FlexGroup时、才使用volume expand.应向所有节点添加相同数量的成员卷、以确保性能稳定一致。例如、如果现有FlexGroup卷具有8个成员卷、每个节点具有4个成员卷、则每个节点添加2个成员将产生12个成员卷、每个节点具有6个成员卷。

向新节点添加新成员时、请尝试保持每个节点的成员卷数量与现有节点中的卷数量一致。例如、如果现有FlexGroup卷具有8个成员卷、每个节点具有4个成员卷、则在将FlexGroup卷扩展到新节点时、应添加4个成员卷、从而形成12个成员的FlexGroup卷。

向FlexGroup卷添加新成员会更改入射启发法、以支持新的空成员卷、并且可能会影响新数据入射的整体性能、直到新成员卷与已有成员卷达到平衡为止。

.示例
*增加现有成员卷容量的示例*

以下示例显示了如何向 FlexGroup 卷 volX 添加 20 TB 空间：

[listing]
----
cluster1::> volume modify -vserver svm1 -volume volX -size +20TB
----
如果FlexGroup卷具有16个成员卷、则每个成员卷的空间会增加1.25 TB。

*通过添加新成员卷提高性能的示例*

以下示例显示了如何向FlexGroup卷fg1添加四个额外的成员卷、每个底层本地层(聚合)各添加两个：

[listing]
----
cluster1::> volume expand -vserver svm1 -volume fg1 -aggr-list aggr1,aggr2 -aggr-list-multiplier 2
----
新成员卷的大小与现有成员卷的大小相同。
