---
permalink: flexgroup/increase-capacity-task.html 
sidebar: sidebar 
keywords: increase, size, flexgroup, volume 
summary: 您可以通过向 FlexGroup 卷的现有成分卷添加更多容量或使用新成分卷扩展 FlexGroup 卷来增加 FlexGroup 卷的大小。 
---
= 增加 FlexGroup 卷的大小
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以通过向 FlexGroup 卷的现有成分卷添加更多容量或使用新成分卷扩展 FlexGroup 卷来增加 FlexGroup 卷的大小。

聚合中必须有足够的可用空间。

如果要添加更多空间，可以增加 FlexGroup 卷的总大小。增加 FlexGroup 卷的大小会调整 FlexGroup 卷的现有成分卷的大小。

如果要提高性能，可以扩展 FlexGroup 卷。在以下情况下，您可能需要扩展 FlexGroup 卷并添加新的成分卷：

* 已向集群添加新节点。
* 已在现有节点上创建新聚合。
* FlexGroup 卷的现有成分卷已达到硬件的最大 FlexVol 大小，因此无法调整 FlexGroup 卷的大小。


在 ONTAP 9.3 之前的版本中，您不能在建立 SnapMirror 关系后扩展 FlexGroup 卷。如果在 ONTAP 9.3 之前的版本中中断 SnapMirror 关系后扩展源 FlexGroup 卷，则必须再次向目标 FlexGroup 卷执行基线传输。从 ONTAP 9.3 开始，您可以扩展 SnapMirror 关系中的 FlexGroup 卷。

.步骤
. 根据需要通过提高 FlexGroup 卷的容量或性能来增加 FlexGroup 卷的大小：
+
[cols="2*"]
|===
| 如果要增加 ... | 然后执行此操作 ... 


 a| 
FlexGroup 卷的容量
 a| 
调整 FlexGroup 卷的成分卷大小： `volume modify -vserver vserver_name -volume fg_name -size new_size`



 a| 
FlexGroup 卷的性能
 a| 
通过添加新成分卷来扩展 FlexGroup 卷： ` + volume expand -vserver vserver_name -volume fg_name -aggr-list aggregate name ， ... ` aggr-list-multiplier constituents_per_aggr++ `` -aggr-list-multiplier 参数的默认值为 1 。

要在 ONTAP 9.5 中为 FabricPool 扩展 FlexGroup 卷，使用的任何新聚合都必须为 FabricPool 。

|===
+
应尽可能增加 FlexGroup 卷的容量。如果必须扩展 FlexGroup 卷，则应以与现有 FlexGroup 卷的成分卷相同的倍数添加成分卷，以确保性能一致。例如，如果现有 FlexGroup 卷包含 16 个成分卷，每个节点包含 8 个成分卷，则可以将现有 FlexGroup 卷扩展 8 个或 16 个成分卷。



* 增加现有成分卷容量的示例 *

以下示例显示了如何向 FlexGroup 卷 volX 添加 20 TB 空间：

[listing]
----
cluster1::> volume modify -vserver svm1 -volume volX -size +20TB
----
如果 FlexGroup 卷包含 16 个成分卷，则每个成分卷的空间将增加 1.25 TB 。

* 通过添加新成分卷提高性能的示例 *

以下示例显示了如何向 FlexGroup 卷 volX 再添加两个成分卷：

[listing]
----
cluster1::> volume expand -vserver vs1 -volume volX -aggr-list aggr1,aggr2
----
新成分卷的大小与现有成分卷的大小相同。
