---
permalink: flexgroup/manage-client-async-dir-delete-task.html 
sidebar: sidebar 
keywords: perform, directory, enable, delete, asynchronous, client rights, SMB, NFS, share, flexvol, flex vol, flexgroup, flex group 
summary: '从NFS.11.1开始、存储管理员可以授予对卷的权限、以允许ONTAP 9和SMB客户端执行异步删除操作。启用async delete后、NFS客户端可以使用命令、SMB客户端 `mv`可以使用 `rename`命令删除指定卷上的目录、并将该目录移动到默认名为.ontaptrashbin的隐藏目录。' 
---
= 管理客户端权限以使用 FlexGroups 异步删除 ONTAP 目录
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
从ONTAP 9.11.1 开始，存储管理员可以授予卷上的权限，以允许 NFS 和 SMB 客户端执行异步删除操作。当集群启用异步删除时，Linux 客户端用户可以使用 `mv`命令和 Windows 客户端用户可以使用 `rename`命令通过将目录移动到默认名为 .ontaptrashbin 的隐藏目录来删除指定卷上的目录。

权利是按卷授予的。  NFS 客户端用户应该在 NFS 客户端上具有 root 访问权限，并在 NFS 导出上具有超级用户访问权限。

您只能移动目录。您不能将文件移动到 .ontaptrashbin 目录。

link:fast-directory-delete-asynchronous-task.html#delete-directories-asynchronously["了解如何使用ONTAP从FlexGroup卷异步删除目录"] 。



== 启用客户端异步目录删除

.步骤
. 从集群命令行界面进入高级权限模式： `-privilege advance`
. 在卷的挂载点启用客户端异步删除，并且如果需要，为垃圾桶目录提供备用名称：
+
`volume file async-delete client enable volume _volname_ vserver _vserverName_ trashbinname _name_`

+
使用默认垃圾桶名称的示例：

+
[listing]
----
cluster1::*> volume file async-delete client enable -volume v1 -vserver  vs0

Info: Async directory delete from the client has been enabled on volume "v1" in
      Vserver "vs0".
----
+
指定备用垃圾桶名称的示例：

+
[listing]
----
cluster1::*> volume file async-delete client enable -volume test -trashbin .ntaptrash -vserver vs1

Success: Async directory delete from the client is enabled on volume "v1" in
      Vserver "vs0".
----
. 验证是否已启用客户端异步删除：
+
`volume file async-delete client show`

+
示例

+
[listing]
----
cluster1::*> volume file async-delete client show

Vserver Volume      async-delete client TrashBinName
------------ ------------ ----------------------- -------------
vs1          vol1         Enabled          .ntaptrash
vs2          vol2         Disabled          -

2 entries were displayed.
----




== 禁用客户端异步目录删除

.步骤
. 在集群CLI中、禁用客户端时间同步目录删除：
+
`volume file async-delete client disable volume _volname_ vserver _vserverName_`

+
示例

+
[listing]
----
cluster1::*> volume file async-delete client disable -volume vol1 -vserver vs1

       Success: Asynchronous directory delete client disabled successfully on volume.
----
. 验证是否已禁用客户端异步删除：
+
`volume file async-delete client show`

+
示例

+
[listing]
----
cluster1::*> volume file async-delete client show

Vserver      Volume      async-delete client      TrashBinName
------------ ------------ ----------------------- -------------
vs1          vol1         Disabled                -
vs2          vol2         Disabled                -

2 entries were displayed.
----

