---
permalink: flexgroup/monitor-volume-usage-file-system-analytics-task.html 
sidebar: sidebar 
keywords: monitor, volume, ontap, file, system, analytics 
summary: 文件系统分析是一个用于收集和显示有关 FlexGroup 或 FlexVol 卷内容的数据的框架。 
---
= 使用 ONTAP 文件系统分析监控卷使用情况
:icons: font
:imagesdir: ../media/


[role="lead"]
文件系统分析是一个用于收集和显示有关 FlexGroup 或 FlexVol 卷内容的数据的框架。文件系统分析可在卷的文件系统层次结构的每个级别提供详细信息，使您能够：

* 评估容量使用情况和趋势
* 监控文件和目录计数
* 评估文件活动和历史记录


在 ONTAP 9.8 及更高版本中启用后，可以使用 System Manager 显示文件系统分析。您还可以使用 ONTAP REST API 以编程方式访问数据。

启用文件系统分析会对性能产生影响。如果您的环境需要最大性能，您可能会选择不启用分析。如果您的测试显示性能影响不可接受，则也可以禁用分析。禁用分析后，先前为该卷收集的数据将不再显示。

从 ONTAP 9.1.1 开始，文件系统分析可用于从 7- 模式系统过渡的卷。尽管如此，由于文件系统分析可能会占用存储空间，因此不应在容量接近最大的已过渡卷上运行。ONTAP 9.9.1 还提供了为数据监控设置自定义非活动期限的功能。

从 ONTAP 9.10.1 开始，您可以通过文件系统分析框架通过活动跟踪监控最高流量和吞吐量。活动跟踪功能可在以下四个区域显示读取 IOPS ，写入 IOPS ，读取吞吐量和写入吞吐量：文件，客户端，用户和目录。

文件系统分析当前不适用于以下卷类型：

* FlexCache 目标卷
* SnapMirror 目标卷
+
[NOTE]
====
如果您对包含 SVM 的卷处于保护关系中的卷启用了文件系统分析，则分析数据不会复制到目标 SVM 。如果必须在恢复操作中重新同步源 SVM ，则必须在恢复后手动重新启用对所需卷的分析。

====
* SnapLock 卷
* 包含 LUN 的卷
* 仅用于保存 SMB 审核日志的卷（ MDV 卷）
* 节点根卷（ /mroot ） * 按版本提供的功能可用性 *


[cols="55,15,15,15"]
|===


|  | ONTAP 9.8 | ONTAP 9.9.1 | ONTAP 9.10.1 


| System Manager 中的可视化 | X | X | X 


| 容量分析 | X | X | X 


| 非活动数据信息 | X | X | X 


| 从 7- 模式系统过渡的卷的可用性 |  | X | X 


| 用于在 System Manager 中更改非活动期限的选项 |  | X | X 


| 活动跟踪 |  |  | X 


| 下载到 CSV （活动跟踪） |  |  | X 
|===