---
permalink: flexgroup/monitor-snapmirror-data-transfers-task.html 
sidebar: sidebar 
keywords: monitor, snapmirror, data, transfer, flexgroup, volumes 
summary: 您应定期监控 FlexGroup 卷 SnapMirror 关系的状态，以验证目标 FlexGroup 卷是否按指定计划定期更新。 
---
= 监控 FlexGroup 卷的 SnapMirror 数据传输
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您应定期监控 FlexGroup 卷 SnapMirror 关系的状态，以验证目标 FlexGroup 卷是否按指定计划定期更新。

您必须从目标集群执行此任务。

.步骤
. 查看所有 FlexGroup 卷关系的 SnapMirror 关系状态： `snapmirror show -relationship-group-type FlexGroup`
+
[listing]
----
cluster2::> snapmirror show -relationship-group-type flexgroup
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vss:s       XDP  vsd:d        Snapmirrored
                                      Idle           -         true    -
vss:s2      XDP  vsd:d2       Uninitialized
                                      Idle           -         true    -
2 entries were displayed.
----
. 查看 FlexGroup 卷中每个成分卷的 SnapMirror 关系状态： `snapmirror show -expand`
+
[listing]
----
cluster2::> snapmirror show -expand
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vss:s       XDP  vsd:d        Snapmirrored
                                      Idle           -         true    -
vss:s__0001 XDP  vsd:d__0001  Snapmirrored
                                      Idle           -         true    -
vss:s__0002 XDP  vsd:d__0002  Snapmirrored
                                      Idle           -         true    -
vss:s__0003 XDP  vsd:d__0003  Snapmirrored
                                      Idle           -         true    -
vss:s__0004 XDP  vsd:d__0004  Snapmirrored
                                      Idle           -         true    -
vss:s__0005 XDP  vsd:d__0005  Snapmirrored
                                      Idle           -         true    -
vss:s__0006 XDP  vsd:d__0006  Snapmirrored
                                      Idle           -         true    -
vss:s__0007 XDP  vsd:d__0007  Snapmirrored
                                      Idle           -         true    -
vss:s__0008 XDP  vsd:d__0008  Snapmirrored
                                      Idle           -         true    -
...
----
. 如果 SnapMirror 传输失败，请确定传输失败的 FlexGroup 卷成分卷以及错误原因： `snapmirror show -fields last-transfer-error -expand`
+
[listing]
----
cluster2::> snapmirror show -fields last-transfer-error -expand
source-path destination-path last-transfer-error
----------- ---------------- -----------------------------------------------
vss:s       vsd:d            Group Update failed (Failed to complete update operation on one or more item relationships.)
vss:s__0001 vsd:d__0001      -
vss:s__0002 vsd:d__0002      -
vss:s__0003 vsd:d__0003      Failed to get information for source volume "vss:s__0003" for setup of transfer. (Failed to get volume attributes for e2de028c-8049-11e6-96ea-005056851ca2:s__0003. (Volume is offline))
vss:s__0004 vsd:d__0004      -
vss:s__0005 vsd:d__0005      -
vss:s__0006 vsd:d__0006      -
vss:s__0007 vsd:d__0007      -
vss:s__0008 vsd:d__0008      -
9 entries were displayed.
----
+
更正问题描述后，必须重新运行 SnapMirror 操作。


