---
permalink: flexgroup/move-constituents-task.html 
sidebar: sidebar 
keywords: constituents, flexgroup, volume, flex group, balancing, balance, traffic, free, space, aggregate, snapmirror, snap mirror, 
summary: 您可以将FlexGroup卷的成分卷从一个聚合移动到另一个聚合、以便在某些成分卷遇到更多流量时平衡负载。移动成分卷还有助于释放聚合上的空间，以便调整现有成分卷的大小。 
---
= 移动ONTAP FlexGroup卷的成分卷
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以将FlexGroup卷的成分卷从一个聚合移动到另一个聚合、以便在某些成分卷遇到更多流量时平衡负载。移动成分卷还有助于释放聚合上的空间，以便调整现有成分卷的大小。

.开始之前
要移动 SnapMirror 关系中的 FlexGroup 卷成分卷，必须已初始化 SnapMirror 关系。

.关于此任务
在扩展 FlexGroup 卷的成分卷时，无法执行卷移动操作。

.步骤
. 确定要移动的FlexGroup卷成分卷：
+
`volume show -vserver svm_name -is-constituent true`

+
[listing]
----
cluster1::> volume show -vserver vs2 -is-constituent true
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
vs2       fg1          -            online     RW        400TB    15.12TB   62%
vs2       fg1__0001    aggr1        online     RW         25TB     8.12MB   59%
vs2       fg1__0002    aggr2        online     RW         25TB     2.50TB   90%
...
----
. 确定可将FlexGroup卷成分卷移动到的聚合：
+
`volume move target-aggr show -vserver svm_name -volume vol_constituent_name`

+
所选聚合中的可用空间必须大于要移动的 FlexGroup 卷成分卷的大小。

+
[listing]
----
cluster1::> volume move target-aggr show -vserver vs2 -volume fg1_0002
Aggregate Name   Available Size   Storage Type
--------------   --------------   ------------
aggr2            467.9TB          hdd
node12a_aggr3    100.34TB         hdd
node12a_aggr2    100.36TB         hdd
node12a_aggr1    100.36TB         hdd
node12a_aggr4    100.36TB         hdd
5 entries were displayed.
----
. 验证FlexGroup卷成分卷是否可以移动到预期聚合：
+
`volume move start -vserver svm_name -volume vol_constituent_name -destination-aggregate aggr_name -perform-validation-only true`

+
[listing]
----
cluster1::> volume move start -vserver vs2 -volume fg1_0002 -destination-aggregate node12a_aggr3 -perform-validation-only true
Validation succeeded.
----
. 移动FlexGroup卷成分卷：
+
`volume move start -vserver svm_name -volume vol_constituent_name -destination-aggregate aggr_name [-allow-mixed-aggr-types {true|false}]`

+
卷移动操作将作为后台进程运行。

+
从ONTAP 9.5开始、您可以通过设置将FlexGroup卷成分卷从Fabric Pool移动到非Fabric Pool、反之亦然 `-allow-mixed-aggr-types` 参数设置为 `true`。默认情况下、 `-allow-mixed-aggr-types` 选项设置为 `false`。

+
[NOTE]
====
您不能使用 `volume move` 用于在FlexGroup卷上启用加密的命令。

====
+
[listing]
----
cluster1::> volume move start -vserver vs2 -volume fg1_002 -destination-aggregate node12a_aggr3
----
+
[NOTE]
====
如果卷移动操作因活动的SnapMirror操作而失败、则应使用中止SnapMirror操作 `snapmirror abort -h` 命令：     在某些情况下， SnapMirror 中止操作也可能失败。在这种情况下，您应中止卷移动操作并稍后重试。

====
. 验证卷移动操作的状态：
+
`volume move show -volume vol_constituent_name`

+
以下示例显示了已完成复制阶段且处于卷移动操作转换阶段的 FlexGroup 成分卷的状态：

+
[listing]
----
cluster1::> volume move show -volume fg1_002
Vserver   Volume     State    Move Phase  Percent-Complete Time-To-Complete
--------- ---------- -------- ----------  ---------------- ----------------
vs2       fg1_002    healthy  cutover     -                -
----

