---
permalink: flexgroup/protect-snapshot-copies-task.html 
sidebar: sidebar 
keywords: protect, flexgroup, volume, snapshot, copy, flex group, snap shot, manually, manual, automatically, automatic, policy 
summary: 您可以创建自动管理快照创建的快照策略、也可以手动为FlexGroup卷创建快照。只有在ONTAP能够为FlexGroup卷的每个成分卷成功创建快照之后、才会为FlexGroup卷创建有效的快照。 
---
= 使用快照保护FlexGroup卷
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以创建自动管理快照创建的快照策略、也可以手动为FlexGroup卷创建快照。只有在ONTAP能够为FlexGroup卷的每个成分卷成功创建快照之后、才会为FlexGroup卷创建有效的快照。

.关于此任务
* 如果有多个FlexGroup卷与一个快照策略关联、则应确保FlexGroup卷计划不会重叠。
* 从ONTAP 9.8开始、FlexGroup卷上支持的最大快照数为1023。



NOTE: 从ONTAP 9.8开始、 `volume snapshot show`适用于FlexGroup卷的命令将使用逻辑块报告快照大小、而不是计算拥有的最小块。这种新的大小计算方法可能会使快照大小显示为大于早期版本ONTAP中的计算值。

.步骤
. 创建快照策略或手动创建快照：
+
|===


| 如果要创建 ... | 输入此命令 ... 


 a| 
快照策略
 a| 
`volume snapshot policy create`


NOTE: 与FlexGroup卷的Snapshot策略关联的计划的间隔必须大于30分钟。

创建FlexGroup卷时、 `default`快照策略将应用于FlexGroup卷。



 a| 
手动创建Snapshot
 a| 
`volume snapshot create`


NOTE: 为FlexGroup卷创建快照后、您将无法修改快照的属性。如果要修改这些属性、必须先删除快照、然后再重新创建。

|===


创建快照时、客户端对FlexGroup卷的访问会短暂处于静音状态。

. 验证是否为FlexGroup卷创建了有效的快照： `volume snapshot show -volume volume_name -fields state`
+
[listing]
----
cluster1::> volume snapshot show -volume fg -fields state
vserver volume snapshot               state
------- ------ ---------------------- -----
fg_vs   fg     hourly.2016-08-23_0505 valid
----
. 查看FlexGroup卷成分卷的快照： `volume snapshot show -is-constituent true`
+
[listing]
----
cluster1::> volume snapshot show -is-constituent true
                                                                 ---Blocks---
Vserver  Volume   Snapshot                                  Size Total% Used%
-------- -------- ------------------------------------- -------- ------ -----
fg_vs    fg__0001
                  hourly.2016-08-23_0505                    72MB     0%   27%
         fg__0002
                  hourly.2016-08-23_0505                    72MB     0%   27%
         fg__0003
                  hourly.2016-08-23_0505                    72MB     0%   27%
...
         fg__0016
                  hourly.2016-08-23_0505                    72MB     0%   27%
----

