---
permalink: flexgroup/provision-automatically-task.html 
sidebar: sidebar 
keywords: provision, flexgroup, volume, automatic, create, flex group, aggregate, space 
summary: 创建FlexGroup卷时、您可以通过自动选择聚合来选择让ONTAP配置FlexGroup卷。为了获得最佳性能，系统会根据最佳实践选择聚合。 
---
= 自动配置ONTAP FlexGroup卷
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
创建FlexGroup卷时、您可以通过选择聚合来选择让ONTAP自动配置FlexGroup卷。聚合会根据最佳实践进行选择、以获得最佳性能和容量。

.开始之前
集群中的每个节点必须至少有一个聚合。

[NOTE]
====
要在 ONTAP 9.5 中为 FabricPool 创建 FlexGroup 卷，每个节点必须至少有一个 FabricPool 聚合。

====
.关于此任务
ONTAP 会在每个节点上选择两个可用空间最大的聚合来创建 FlexGroup 卷。如果两个聚合不可用，则 ONTAP 会为每个节点选择一个聚合来创建 FlexGroup 卷。

从ONTAP 9.15.1开始、在自动配置FlexGroup卷时、ONTAP会使用平衡放置(Balanced Placement、BP)来选择聚合和FlexGroup成分卷布局。BP的一个方面是、它如何在创建"无"保证的FlexGroup卷时限制过度配置聚合。整个FlexGroup卷的大小受聚合上可用空间量的限制、但该限制高于"卷"保证的FlexGroup卷。使用REST API或ONTAP命令行界面创建FlexGroup卷时 `auto-provision-as` 、由于此限制导致空间不足、配置可能会失败。您可以通过创建较小的FlexGroup卷或使用参数来避免这种情况 link:create-task.html["创建FlexGroup卷并手动选择聚合"] `aggr-list` 。

.步骤
. 配置 FlexGroup 卷：
+
`volume create -vserver svm_name -volume fg_vol_name –auto-provision-as flexgroup -size fg_size [–encrypt true] [-qos-policy-group qos_policy_group_name] [-support-tiering true]`

+
从ONTAP 9.5开始、您可以为FabricPool 创建FlexGroup 卷。要在FabricPool上自动配置FlexGroup卷、必须设置 `-support-tiering` 参数设置为 `true`。卷保证必须始终设置为 `none` 适用于FabricPool。您还可以为 FlexGroup 卷指定分层策略和分层最小冷却期。

+
link:../disks-aggregates/index.html["磁盘和聚合管理"]

+
您可以为FlexGroup卷指定吞吐量上限(QoS最大值)。这会限制FlexGroup卷可以使用的性能资源。从 ONTAP 9.4 开始，您可以为 FlexGroup 卷指定吞吐量下限（ QoS 最小值）和自适应 QoS 。

+
link:../performance-admin/index.html["性能管理"]

+
如果要对FlexGroup卷启用加密、可以将参数设置 `-encrypt`为 `true`。要创建加密卷，必须已安装卷加密许可证和密钥管理器。

+

NOTE: 您必须在创建 FlexGroup 卷时对其启用加密。您不能对现有 FlexGroup 卷启用加密。

+
link:../encryption-at-rest/index.html["空闲数据加密"]

+
。 `size` 参数用于指定FlexGroup卷的大小(以KB、MB、GB、TB或PB为单位)。

+
以下示例显示了如何配置大小为400 TB的FlexGroup卷：

+
[listing]
----
cluster-1::> volume create -vserver vs0 -volume fg –auto-provision-as flexgroup -size 400TB
Warning: The FlexGroup "fg" will be created with the following number of constituents of size 25TB: 16.
The constituents will be created on the following aggregates: aggr1,aggr2
Do you want to continue? {y|n}: y
[Job 34] Job succeeded: Successful
----
+
以下示例显示了如何为吞吐量上限创建 QoS 策略组以及如何将其应用于 FlexGroup 卷：

+
[listing]
----
cluster1::> qos policy-group create -policy group pg-vs1 -vserver vs1 -max-throughput 5000iops
----
+
[listing]
----
cluster-1::> volume create -vserver vs0 -volume fg –auto-provision-as flexgroup -size 400TB -qos-policy-group pg-vs1
Warning: The FlexGroup "fg" will be created with the following number of constituents of size 25TB: 16.
The constituents will be created on the following aggregates: aggr1,aggr2
Do you want to continue? {y|n}: y
[Job 34] Job succeeded: Successful
----
+
以下示例显示了如何在 ONTAP 9.5 中的 FabricPool 中的聚合上配置大小为 400 TB 的 FlexGroup 卷：

+
[listing]
----
cluster-1::> volume create -vserver vs0 -volume fg –auto-provision-as flexgroup -size 400TB -support-tiering true -tiering-policy auto
Warning: The FlexGroup "fg" will be created with the following number of constituents of size 25TB: 16.
The constituents will be created on the following aggregates: aggr1,aggr2
Do you want to continue? {y|n}: y
[Job 34] Job succeeded: Successful
----
+
创建 FlexGroup 卷时，集群中的每个节点上都有八个成分卷。这些成分卷会在每个节点上的两个最大聚合之间平均分布。

+
默认情况下、FlexGroup卷是使用创建的 `volume` 空间保证设置(AFF系统除外)。对于AFF系统、默认情况下会使用创建FlexGroup卷 `none` 空间保证。

. 使用接合路径挂载FlexGroup卷：
+
`volume mount -vserver vserver_name -volume vol_name -junction-path junction_path`

+
[listing]
----
cluster1::> volume mount -vserver vs0 -volume fg2 -junction-path /fg2
----


.完成后
您应从客户端挂载 FlexGroup 卷。

如果您运行的是 ONTAP 9.6 或更早版本，并且 Storage Virtual Machine （ SVM ）同时配置了 NFSv3 和 NFSv4 ，则从客户端挂载 FlexGroup 卷可能会失败。在这种情况下，您必须在从客户端挂载 FlexGroup 卷时明确指定 NFS 版本。

[listing]
----
# mount -t nfs -o vers=3 192.53.19.64:/fg2 /mnt/fg2
# ls /mnt/fg2
file1  file2
----