---
permalink: flexgroup/transition-snapmirror-relationship-svm-dr-task.html 
sidebar: sidebar 
keywords: transition, flexgroup, snapmirror, relationship, svm, dr 
summary: 您可以通过过渡现有的 FlexGroup 卷 SnapMirror 关系来创建 FlexGroup SVM DR 关系。 
---
= 将现有 FlexGroup SnapMirror 关系过渡到 SVM DR
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以通过过渡现有的 FlexGroup 卷 SnapMirror 关系来创建 FlexGroup SVM DR 关系。

.您需要什么？ #8217 ；将需要什么
* FlexGroup 卷 SnapMirror 关系处于运行状况良好的状态。
* 源和目标 FlexGroup 卷的名称相同。


.步骤
. 从 SnapMirror 目标重新同步 FlexGroup 级别的 SnapMirror 关系： `snapmirror resync`
. 创建FlexGroup SVM DR SnapMirror关系。使用在FlexGroup 卷SnapMirror关系上配置的相同SnapMirror策略：`snapmirror create -destination-path dest_SVM：-source-path src_SVM：-identity-preserve true -policy MirrorAllSnapshots`


[]
====
创建复制关系时，您必须使用 `snapmirror create` 命令的 ` -identity-preserve true` 选项。

====
. 验证此关系是否已断开：`snapmirror show -destination-path dest_svm：-source-path src_svm：`
+
[listing]
----
snapmirror show -destination-path fg_vs_renamed: -source-path fg_vs:

                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
fg_vs:        XDP  fg_vs1_renamed:     Broken-off
                                      Idle           -         true   -
----
. 停止目标 SVM ： `vserver stop -vserver vs_name`
+
[listing]
----
vserver stop -vserver fg_vs_renamed
[Job 245] Job is queued: Vserver Stop fg_vs_renamed.
[Job 245] Done
----
. 重新同步SVM SnapMirror关系：`snapmirror resync -destination-path dest_svm：-source-path src_svm：`
+
[listing]
----
snapmirror resync -destination-path fg_vs_renamed: -source-path fg_vs:
Warning: This Vserver has volumes which are the destination of FlexVol or FlexGroup SnapMirror relationships. A resync on the Vserver SnapMirror relationship will cause disruptions in data access
----
. 验证 SVM DR 级别 SnapMirror 关系是否达到正常的空闲状态： `snapmirror show -expand`
. 验证 FlexGroup SnapMirror 关系是否处于运行状况良好的状态： `snapmirror show`

