---
permalink: flexcache-writeback/flexcache-write-back-overview.html 
sidebar: sidebar 
keywords: tr-4743, flexcache writeback, flexcache write-back, overview, technical report, netapp tr, ontap tr 
summary: FlexCache回写是在ONTAP 9.151中推出的一种备用操作模式、用于在缓存中写入数据。 
---
= FlexCache回写概述
:allow-uri-read: 


[role="lead"]
FlexCache回写是在ONTAP 9.151中推出的一种备用操作模式、用于在缓存中写入数据。通过回写、可以将写入提交到缓存中的稳定存储、并向客户端确认、而无需等待数据传输到源站。数据会异步转储回源站。因此、可以构建一个全球分布式文件系统、使特定工作负载和环境能够以接近本地的速度执行写入、从而显著提高性能。


NOTE: ONTAP 9.12.1引入了一项回写功能、可作为公共预览。这称为回写版本1 (wbv1)、不应视为与ONTAP 9.15.1中的回写相同、后者称为回写版本2 (wbv2)。


NOTE: 从2024年7月开始、以前以PDF格式发布的技术报告中的内容已与ONTAP产品文档集成。现在、ONTAP安全文档包含了_TR-4743：《ONTAP 9.11.1_中的FlexCache》中的内容。



== 回写与绕写

自FlexCache在ONTAP 9.5中推出以来、它一直是一种可读写缓存；但是、它在绕写模式下运行。缓存中的写入操作会发送到初始卷、以提交到稳定存储。初始服务器成功将写入提交到稳定存储后、它会确认写入缓存。然后、缓存会向客户端确认写入。这样、每次写入都会导致在缓存和源站之间遍历网络。FlexCache回写将更改此设置。


NOTE: 升级到ONTAP 9.15.1后、您可以将传统的绕写缓存转换为回写缓存、并在必要时返回到绕写缓存。但是、如果出现问题、这可能会使读取诊断日志变得更加困难。

|===
|  | 绕写 | 回写 


| ONTAP 版本 | 9.6多个 | 9.15.1+ 


| 用例 | 读取繁重的工作负载 | 写入量大的工作负载 


| 数据提交时间 | 来源 | 缓存 


| 客户体验 | 类似于WAN | LAN-lke 


| 限制 | 每个原产地100个 | 每个原产地10个 


| https://en.wikipedia.org/wiki/CAP_theorem["Cap Theorem"^] | 对分区可用并容错 | 可用且一致 
|===


== FlexCache回写术语

了解使用FlexCache回写的关键概念和术语。

[cols="12%,88%"]
|===
| 期限 | 定义 


| [[dirty数据]]*dirty数据* | 已提交到缓存中的稳定存储、但尚未转储到源站的数据。 


| *专用锁定委派(XLD)* | 按文件授予缓存的协议级锁定权限。此授权允许缓存向客户端分发专用写入锁定、而无需联系源站。 


| *共享锁定委派(SLD)* | 按文件授予缓存的协议级锁定权限。此授权允许缓存向客户端分发共享读取锁定、而无需联系源站。 


| *回写* | 一种FlexCache操作模式、其中、对缓存的写入会提交到该缓存中的稳定存储、并立即向客户端确认。数据会异步写入源站。 


| *绕写式* | 一种FlexCache操作模式、其中、对缓存的写入会转发到初始卷以提交到稳定存储。提交后、初始服务器将确认对缓存的写入、而缓存将确认对客户端的写入。 


| *脏数据记录系统(DDRS)* | 一种专有机制、可在启用了回写功能的缓存中按文件跟踪脏数据。 


| *原产地* | 包含所有FlexCache缓存卷的源数据的FlexGroup或FlexVol。它是唯一的数据来源、可协调锁定、并确保100%的数据一致性、货币性和一致性。 


| *缓存* | FlexGroup是FlexCache初始卷的稀疏缓存卷。 
|===


=== 一致、当前和一致

FlexCache是NetApp的解决方案、可随时随地提供正确的数据。FlexCache始终保持100%一致、当前和一致：

* *一致：*无论访问数据的位置、数据都是相同的。
* *current：*数据始终是最新的。
* *一致：*数据正确/未损坏。

