---
permalink: flexcache-writeback/flexcache-write-back-guidelines.html 
sidebar: sidebar 
keywords: tr-4743, flexcache writeback, flexcache write-back, flexcache, write-back, write back, guidelines, best practices, performance, ontap tr, netapp tr 
summary: 使用FlexCache回写时、请遵循以下准则以确保性能最佳。 
---
= ONTAP FlexCache回写准则
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexCache写回涉及源服务器和缓存服务器之间的许多复杂交互。为了获得最佳性能，您应该确保您的环境遵循以下准则。这些指南基于内容创建时可用的最新主要ONTAP版本（ONTAP 9.17.1）。

作为最佳实践、请在非生产环境中测试生产工作负载。如果您在这些准则之外实施FlexCache回写、则这一点更为重要。

以下准则已在NetApp内部经过充分测试。*_잿 쇒_*붨 틩 您待在他们里面。否则、可能会发生意外行为。

* ONTAP 9.17.1P1 引入了对FlexCache回写功能的重大增强。强烈建议您在源集群和缓存集群上，在 9.17.1P1 版本之后运行当前推荐版本。如果您无法运行 9.17.1 代码线，建议使用最新的 P 版本 9.16.1。ONTAP 9.15.1 尚未包含FlexCache回写所需的全部修复和改进，因此不建议用于生产工作负载。
* 在当前迭代过程中、应为FlexCache回写缓存配置一个成分卷来容纳整个FlexCache卷。多成分卷FlexCaches可能会导致从缓存中意外删除数据。
* 测试针对小于 100GB 的文件进行，缓存和源之间的 WAN 往返时间不超过 200ms。超出这些限制的任何工作负载都可能导致意想不到的性能特征。
* 写入SMB备用数据流会导致主文件从缓存中逐出。需要先将主文件的所有脏数据转储到原始文件、然后才能对该文件执行任何其他操作。备用数据流也会转发到源。
* 重命名文件会导致文件从缓存中逐出。需要先将文件的所有脏数据转储到源、然后才能对该文件执行任何其他操作。
* 此时、只能对启用了回写的FlexCache卷上的文件更改或设置以下属性：
+
** 时间戳
** 模式位
** NT ACL
** 所有者
** 组
** Size
+
更改或设置的任何其他属性都会转发到原始属性、这可能会导致从缓存中逐出文件。如果您需要在缓存中更改或设置其他属性、请要求您的客户团队创建PVR。



* 在初始卷创建的快照会导致从与该初始卷关联的每个已启用回写的缓存中调用所有未处理的脏数据。如果正在进行大量回写活动、则可能需要多次重试此操作、因为清除这些脏文件可能需要一段时间。
* 启用回写功能的FlexCache卷不支持 SMB 机会锁（Oplocks）写入。
* 原产地必须保持在80%满量以下。如果初始卷中没有至少20%的剩余空间、则不会为缓存卷授予独占锁定委派。在这种情况下、对启用了回写的缓存的调用将转发到源站。这有助于防止源站空间不足、从而导致在启用了回写的缓存中孤立脏数据。
* 低带宽和/或有损的集群间网络会对FlexCache写回性能产生显著的负面影响。虽然没有具体的带宽要求，因为它很大程度上取决于您的工作负载，但强烈建议您确保缓存和源之间的集群间链路的健康状况。

