---
sidebar: sidebar 
permalink: smbc/smbc_troubleshoot_link_between_site_b_and_mediator_down.html 
keywords: SM-BC, SMBC, troubleshooting, link down, Mediator 
summary: 从站点 B 建立的调解器连接显示为无法访问。 
---
= 站点B和调解器之间的链路关闭、站点A关闭
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
要检查ONTAP调解器的连接、请使用 `snapmirror mediator show` 命令：如果连接状态不可访问、并且站点B无法访问站点A、则会显示一个类似于以下内容的输出。按照解决方案 中的步骤还原连接

....
cluster::*> snapmirror mediator show
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
10.237.86.17     C1_cluster       unreachable       true
SnapMirror consistency group relationship status is out of sync.

C2_cluster::*> snapmirror show -expand
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vs0:/cg/src_cg_1 XDP vs1:/cg/dst_cg_1 Snapmirrored OutOfSync - false   -
vs0:zrto_cg_655724_188a_RW1 XDP vs1:zrto_cg_655755_188c_DP1 Snapmirrored OutOfSync - false -
vs0:zrto_cg_655733_188a_RW2 XDP vs1:zrto_cg_655762_188c_DP2 Snapmirrored OutOfSync - false -
vs0:zrto_cg_655739_188b_RW1 XDP vs1:zrto_cg_655768_188d_DP1 Snapmirrored OutOfSync - false -
vs0:zrto_cg_655748_188b_RW2 XDP vs1:zrto_cg_655776_188d_DP2 Snapmirrored OutOfSync - false -
5 entries were displayed.

Site B cluster is unable to reach Site A.
C2_cluster::*> cluster peer show
Peer Cluster Name         Cluster Serial Number Availability   Authentication
------------------------- --------------------- -------------- --------------
C1_cluster 			  1-80-000011           Unavailable    ok
....
.解决方案
强制执行故障转移以启用站点 B 的 I/O ，然后从站点 B 到站点 A 建立零 RTO 关系要在站点 B 上执行强制故障转移，请完成以下步骤

. 从站点 B 取消映射属于一致性组的所有 LUN
. 使用 force 选项删除 SnapMirror 一致性组关系。
. 输入SnapMirror中断命令 (`snapmirror break -destination_path _svm_:_volume_`)以将卷从DP转换为RW、从而启用站点B的I/O
+
您必须为一致性组中的每个关系使用问题描述命令。例如、如果一致性组中有三个卷、则需要对每个卷使用问题描述命令。

. 启动站点 A 节点以创建从站点 B 到站点 A 的零 RTO 关系
. 释放站点 A 上具有 relationship-info-only 的一致性组，以保留通用 Snapshot 副本并取消映射属于此一致性组的 LUN 。
. 通过使用 Sync 策略或异步策略设置卷级别关系，将站点 A 上的卷从 RW 转换为 DP 。
. 问题描述 `snapmirror resync` 命令以同步关系。
. 删除站点 A 上的同步 SnapMirror 关系策略
. 在站点 B 上使用 relationship-info-only true 释放带有 Sync 策略的 SnapMirror 关系
. 在站点B与站点A之间创建一致性组关系
. 从源集群重新同步此一致性组。验证一致性组状态是否为同步。
. 重新扫描主机LUN I/O路径以还原LUN的所有路径。

