---
sidebar: sidebar 
permalink: smbc/smbc_intro_terminology.html 
keywords: SM-BC, SMBC, Mediator, terminology 
summary: 在您开始了解 ONTAP SnapMirror 业务连续性并规划部署时，熟悉关键术语和概念会很有帮助。 
---
= 关键概念
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在您开始了解 ONTAP SnapMirror 业务连续性并规划部署时，熟悉关键术语和概念会很有帮助。

ONTAP 9.8 及更高版本提供的 SnapMirror 业务连续性（ SM-BC ）解决方案的缩写。

从 ONTAP 9.10.1 开始，一致性组已成为第一个订单管理单元。要了解有关一致性组的详细信息，请参见 link:../consistency-groups/index.html["一致性组概述"]。

一致性组（ Consistency Group ， CG ）是一组 FlexVol 卷，可为需要保护的应用程序工作负载提供写入顺序一致性保证，以确保业务连续性。一致性组的目的是，在一个时间点同时为一组卷创建崩溃状态一致的 Snapshot 副本。在常规部署中，选择作为 CG 一部分的一组卷会映射到应用程序实例。SnapMirror 关系（也称为 CG 关系）是在源 CG 和目标 CG 之间建立的。源和目标 CG 必须包含相同数量和类型的卷。

属于一致性组的各个 FlexVol 卷。

ONTAP 调解器提供指向对等集群的备用运行状况路径，而集群间 LIF 则提供另一个运行状况路径。利用调解器的运行状况信息，集群可以区分集群间 LIF 故障和站点故障。当站点发生故障时，调解器会根据需要将运行状况信息传递到对等集群，以便对等集群进行故障转移。利用调解器提供的信息和集群间 LIF 运行状况检查信息， ONTAP 可确定是执行自动故障转移，如果无法进行故障转移，则继续还是停止。

调解器是 SM — BC 仲裁的三方之一，与主集群和二级集群合作以达成共识。协商一致要求仲裁中至少有两个方同意某项操作。

应用程序 I/O 未复制到二级存储系统。目标卷与源卷不同步，因为未发生 SnapMirror 复制。如果镜像状态为 Snapmirrored ，则表示传输失败或因操作不受支持而失败。

零恢复点目标。这是可接受的停机数据丢失量。

通过使用基于主机多路径 I/O （ MPIO ）软件的路径故障转移功能提供对存储的无中断访问，可以实现零恢复时间目标或透明应用程序故障转移。

一种手动操作，用于更改 SM-BC 关系中副本的角色。主节点成为二级节点，二级节点成为主节点。ALUA 报告也会发生变化。

对镜像副本执行故障转移的自动操作。此操作需要调解器协助，以检测主副本是否不可用。
