---
sidebar: sidebar 
permalink: smbc/smbc_plan_additional_restrictions_and_limitations.html 
keywords: SM-BC, SMBC, restrictions, consistency group, endpoint limits, solaris 
summary: 使用 SnapMirror Business Continuity 解决方案时，还存在一些其他限制和限制。 
---
= 其他限制和限制
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
使用 SnapMirror Business Continuity 解决方案时，还存在一些其他限制和限制。



=== 一致性组

从 ONTAP 9.8 到 9.1.1 ，集群中的最大 SM-BC 一致性组关系数为 5 ，这一限制与平台无关。从 ONTAP 9.10.1 开始，集群中的最大 SM-BC 一致性组关系数为 20 。



=== 每个一致性组的卷数

从 ONTAP 9.8 到 9.1.1 ，每个 SM-BC 一致性组关系支持的最大卷数为 12 个，这一限制与平台无关。从 ONTAP 9.10.1 开始，每个 SM-BC 关系支持的最大卷数为十六。



=== Volumes

在 SM-BC 中，限制是根据端点数量而不是关系数量来计算的。包含 12 个卷的一致性组会在源和目标上提供 12 个端点。SM-BC 和 SnapMirror 同步关系都会影响端点总数。

下表列出了每个平台的最大端点数量。

|===
| S否 | 平台 2+| SM-BC 的每个 HA 端点 2+| 每个 HA 的整体同步端点和 SM-BC 端点 


|  |  | ONTAP 9.8-9.9 | ONTAP 9.10.1 | ONTAP 9.8-9.9 | ONTAP 9.10.1 


| 1. | AFF | 60 | 200 | 80 | 200 


| 2. | ASA | 60 | 200 | 80 | 200 
|===


=== SAN 对象限制

下表列出了以下 SAN 对象限制，这些限制与平台无关。

|===
| SM-BC 关系中的对象限制 | 计数 


| 每个卷的 LUN 数 | 256 


| 每个节点的 LUN 映射数 | 2048 


| 每个集群的 LUN 映射数 | 4096 


| 每个 SVM 的 LIF （至少有一个卷处于 SM-BC 关系） | 256 


| 每个节点的集群间 LIF | 4. 


| 每个集群的集群间 LIF | 8. 
|===


=== NTFS 安全模式

SM-BC 卷不支持 NTFS 安全模式。



=== SM-BC 配置的 Solaris 主机设置建议

从 ONTAP 9.10.1 开始， SM-BC 支持 Solaris 11.4 。为了确保在 SM-BC 环境中发生计划外站点故障转移切换时 Solaris 客户端应用程序不会造成中断，需要在 Solaris 11.4 主机上配置以下设置。此设置将覆盖故障转移模块 `f_tpgs` ，以防止执行检测到冲突的代码路径。

按照说明配置 override 参数：

. 为连接到主机的 NetApp 存储类型创建配置文件 ` /etc/driver/drv/scsi_vhci.conf` ，并输入类似于以下内容的条目：
+
[listing]
----
scsi-vhci-failover-override =
"NETAPP  LUN","f_tpgs"
----
. 使用 `devprop` 和 `mdb` 命令验证是否已成功应用覆盖：
+
[listing]
----
root@host-A:~# devprop -v -n /scsi_vhci scsi-vhci-failover-override scsi-vhci-failover-override=NETAPP  LUN + f_tpgs
root@host-A:~# echo "*scsi_vhci_dip::print -x struct dev_info devi_child | ::list struct dev_info devi_sibling| ::print struct dev_info devi_mdi_client| ::print mdi_client_t ct_vprivate| ::print struct scsi_vhci_lun svl_lun_wwn svl_fops_name"| mdb -k`
----
+
[listing]
----
svl_lun_wwn = 0xa002a1c8960 "600a098038313477543f524539787938"
svl_fops_name = 0xa00298d69e0 "conf f_tpgs"
----



NOTE: 应用 `scsI-vhcI-failover-override` 后， `conf` 将添加到 `svl_fPS_name` 中。有关追加信息以及对默认设置的建议更改，请参阅 NetApp 知识库文章 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/Solaris_Host_support_recommended_settings_in_SnapMirror_Business_Continuity_(SM-BC)_configuration["Solaris 主机支持 SnapMirror 业务连续性（ SM-BC ）配置中的建议设置"]。
