---
sidebar: sidebar 
permalink: smbc/smbc_admin_monitoring.html 
keywords: SM-BC, SMBC, monitoring, Mediator status, EMS, errors, planned failover status, automatic unplanned failover status, SM-BC status 
summary: 您可以监控多个 SM-BC 组件和操作。 
---
= 基本监控
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以监控多个 SM-BC 组件和操作。



=== ONTAP 调解器

在正常操作期间，应连接调解器状态。如果处于任何其他状态，则可能表示出现错误情况。您可以查看事件管理系统（ EMS ）消息以确定错误和相应的更正操作。

|===
| EMS 名称 | Description 


| sm.medier.added | 已成功添加调解器 


| sm.medier.removed | 已成功删除调解器 


| sm.medier.unusable | 由于调解器服务器损坏，调解器无法使用 


| sm.medier.misconfigured | 调解器已重新利用，或者调解器服务器上不再安装调解器软件包 


| sm.medier.unreachable | 无法访问调解器 


| sm.mediate.removed.force | 使用 "force" 选项从集群中删除调解器 


| sm.mediator.cacert.expiring | 调解器证书颁发机构（ CA ）证书应在 30 天或更短时间内过期 


| sm.mediator.serverc.expiring | 调解器服务器证书将在 30 天或更短时间内过期 


| sm.mediate.clientc.expedent.expedisn.exp用 | 调解器客户端证书应在 30 天或更短时间内过期 


| sm.mediator.cacert.expired | 调解器证书颁发机构（ CA ）证书已过期 


| sm.mediator.serverc.expired | 调解器服务器证书已过期 


| sm.mediate.clientc.expired. | 调解器客户端证书已过期 


| sm.mediator.in.quorum | 所有 SM-BC 记录都会与调解器重新同步 
|===


=== 计划内故障转移操作

您可以使用 `snapmirror failover show` 命令监控计划内故障转移操作的状态和进度。例如：

....
ClusterB::> snapmirror failover start -destination-path vs1:/cg/dcg1
....
故障转移操作完成后，您可以从新的目标集群监控同步 SnapMirror 保护状态。例如：

....
ClusterA::> snapmirror show
....
您还可以查看以下消息以确定是否存在错误并采取适当的更正措施。

|===
| EMS 名称 | Description 


| SMBC.PFO.FAILED | SMBC 计划的故障转移操作失败。目标路径： 


| SMBC.PFO.START 。目标路径： | 已启动 SMBC 计划内故障转移操作 
|===


=== 自动计划外故障转移操作

在计划外自动故障转移期间，您可以使用 `snapmirror failover show` 命令监控操作状态。例如：

....
ClusterB::> snapmirror failover show -instance
Start Time: 9/23/2020 22:03:29
         Source Path: vs1:/cg/scg3
    Destination Path: vs3:/cg/dcg3
     Failover Status: completed
        Error Reason:
            End Time: 9/23/2020 22:03:30
Primary Data Cluster: cluster-2
Last Progress Update: -
       Failover Type: unplanned
  Error Reason codes: -
....
您还可以查看以下消息以确定是否存在错误并采取适当的更正措施。

|===
| EMS 名称 | Description 


| smbc.aufo.failed | SnapMirror 自动计划故障转移操作失败。目标路径： 


| smbc.aufo.start 。目标路径： | 已启动 SMBC 计划内故障转移操作 


| smbc.aufo.completed: | 已完成 SnapMirror 自动计划故障转移操作。目标路径： 


| smbc.aufo.failover.incapable | block.giveback.during.aufo 
|===


=== SM-BC 可用性

您可以在主集群，二级集群或这两者上使用一系列命令来检查 SM-BC 关系的可用性。

您使用的命令包括在主集群和二级集群上使用 `snapmirror mediator show` 命令检查连接和仲裁状态，使用 `snapmirror show` 命令和 `volume show` 命令。例如：

....
SMBC_A::*> snapmirror mediator show
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
10.236.172.86    SMBC_B           connected         true

SMBC_B::*> snapmirror mediator show
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
10.236.172.86    SMBC_A           connected         true

SMBC_B::*> snapmirror show -expand
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vs0:/cg/cg1 XDP  vs1:/cg/cg1_dp Snapmirrored InSync  -         true    -
vs0:vol1    XDP  vs1:vol1_dp  Snapmirrored InSync    -         true    -
2 entries were displayed.

SMBC_A::*> volume show -fields is-smbc-master,smbc-consensus,is-smbc-failover-capable -volume vol1
vserver volume is-smbc-master is-smbc-failover-capable smbc-consensus
------- ------ -------------- ------------------------ --------------
vs0     vol1   true           false                    Consensus

SMBC_B::*> volume show -fields is-smbc-master,smbc-consensus,is-smbc-failover-capable -volume vol1_dp
vserver volume  is-smbc-master is-smbc-failover-capable smbc-consensus
------- ------- -------------- ------------------------ --------------
vs1     vol1_dp false          true                     No-consensus
....