---
sidebar: sidebar 
permalink: smbc/smbc_admin_converting_existing_relationships_to_smbc.html 
keywords: SM-BC, SMBC, convert, Synchronous SnapMirror, zero RPO, zero recovery time objective, zero RTO, existing, snapmirror active sync 
summary: 您可以将现有的零恢复点保护（零 RPO ）同步 SnapMirror 关系转换为 SM-BC 零 RTO 同步 SnapMirror 一致性组关系。 
---
= 将现有关系转换为 SM-BC 关系
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
如果源集群和目标集群之间存在同步SnapMirror关系、则可以将其转换为SM-BC关系。这样、您就可以将镜像卷与一致性组关联起来、从而确保多卷工作负载的RPO为零。此外、如果您需要还原到建立SM-BC关系之前的某个时间点、则可以保留现有SnapMirror快照。

.开始之前
* 主集群和二级集群之间必须存在零RPO同步SnapMirror关系。
* 必须取消映射目标卷上的所有LUN、然后才能创建零RTO SnapMirror关系。
* SM-BC 仅支持 SAN 协议（而不是 NFS/CIFS ）。确保未挂载一致性组的任何成分卷以进行 NAS 访问。


.关于此任务
* 您必须是主集群和二级集群上的集群和SVM管理员。
* 您不能通过更改 SnapMirror 策略将零 RPO 转换为零 RTO 同步。
* 在发出之前、必须确保已取消LUN映射 `snapmirror create` 命令：
+
如果已映射二级卷上的现有LUN、则为和 `AutomatedFailover` 策略、即 `snapmirror create` 将触发错误。



.步骤
. 从二级集群中、对现有关系执行SnapMirror更新：
+
`destination::>snapmirror update -destination-path vs1_dst:vol1`

. 验证 SnapMirror 更新是否已成功完成：
+
`destination::>snapmirror show`

. 暂停每个零 RPO 同步关系：
+
`destination::>snapmirror quiesce -destination-path vs1_dst:vol1`

+
`destination::>snapmirror quiesce -destination-path vs1_dst:vol2`

. 删除每个零 RPO 同步关系：
+
`destination::>snapmirror delete -destination-path vs1_dst:vol1`

+
`destination::>snapmirror delete -destination-path vs1_dst:vol2`

. 释放源 SnapMirror 关系，但保留通用 Snapshot 副本：
+
`source::>snapmirror release -relationship-info-only true -destination-path vs1_dst:vol1`

+
`source::>snapmirror release -relationship-info-only true -destination-path vs1_dst:vol2`

. 创建组零 RTO 同步 SnapMirror 关系：
+
`destination::> snapmirror create -source-path vs1_src:/cg/cg_src -destination-path vs1_dst:/cg/cg_dst -cg-item-mappings vol1:@vol1,vol2:@vol2 -policy AutomatedFailover`

. 重新同步一致性组：
+
`destination::> snapmirror resync -destination-path vs1_dst:/cg/cg_dst`

. 重新扫描主机 LUN I/O 路径以还原 LUN 的所有路径。

