= 
:allow-uri-read: 


. 使用 `system license show` 命令以验证您是否具有FC或iSCSI许可证。
+
`system license show`

+
[listing]
----

Package           Type    Description           Expiration
 ----------------- ------- --------------------- --------------------
 Base              site    Cluster Base License  -
 NFS               site    NFS License           -
 CIFS              site    CIFS License          -
 iSCSI             site    iSCSI License         -
 FCP               site    FCP License           -
----
. 如果您没有FC或iSCSI许可证、请使用 `license add` 命令：
+
`license add -license-code _your_license_code_`

. 在SVM上启用协议服务：
+
*对于iSCSI：* `vserver iscsi create -vserver _vserver_name_ -target-alias _vserver_name_`

+
*对于FC：* `vserver fcp create -vserver _vserver_name_ -status-admin up`

. 在每个节点上为SVM创建两个LIF：
+
`network interface create -vserver _vserver_name_ -lif _lif_name_ -role data -data-protocol iscsi|fc -home-node _node_name_ -home-port _port_name_ -address _ip_address_ -netmask netmask`

+
对于每个提供数据的SVM、NetApp至少支持每个节点一个iSCSI或FC LIF。但是、要实现冗余、每个节点需要两个LIF。

. 确认已创建LIFs且其运行状态为 `online`：
+
`network interface show -vserver _vserver_name_ _lif_name_`

. 创建 LUN ：
+
`lun create -vserver vserver_name -volume _volume_name_ -lun _lun_name_ -size _lun_size_ -ostype linux -space-reserve enabled|disabled`

+
LUN 名称不能超过 255 个字符，并且不能包含空格。

+

NOTE: 在卷中创建 LUN 时， NVFAIL 选项会自动启用。

. 创建 igroup ：
+
`igroup create -vserver _vserver_name_ -igroup _igroup_name_ -protocol fcp|iscsi|mixed -ostype linux -initiator _initiator_name_`

. 将 LUN 映射到 igroup ：
+
`lun mapping create -vserver _vserver_name_ -volume _volume_name_ -lun _lun_name_ -igroup _igroup_name_`

. 验证是否已正确配置 LUN ：
+
`lun show -vserver _vserver_name_`

. link:san-admin/create-port-sets-binding-igroups-task.html["创建端口集并绑定到igroup"] （可选）。
. 按照主机文档中的步骤在特定主机上启用块访问。
. 使用 Host Utilities 完成 FC 或 iSCSI 映射并发现主机上的 LUN 。

