---
sidebar: sidebar 
permalink: networking/commands_for_managing_snmp.html 
keywords: snmp, traps, traphosts, trap, traphost, manage, managing, users, user, configure, configuring, modify, modifying, set, setting, event, command, system snmp, security, options -option-name snmp.enable -option-value on, options -option-name snmp.enable -option-value off, commands for managing snmp, commands for managing snmp v1, v2c, and v3 users, commands for providing contact and location information, commands for managing SNMP communities, command for displaying snmp option values, commands for managing snmp traps and traphosts, commands for managing events related to snmp traps, system snmp, security login create, security snmpusers and security login show -application snmp, security login create, security login delete, security snmpusers and security login show -application snmp, security login modify, system snmp contact, system snmp location, system snmp community add, system snmp community delete, system snmp community show, system snmp show 
summary: 管理 SNMP ， SNMP 用户，陷阱，陷阱事件和陷阱主机 
---
= 用于管理 SNMP 的命令
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用 `ssystem snmp` 命令管理 SNMP ，陷阱和陷阱主机。您可以使用 `sSecurity` 命令管理每个 SVM 的 SNMP 用户。您可以使用 `event` 命令管理与 SNMP 陷阱相关的事件。



== 用于配置 SNMP 的命令

[cols="2*"]
|===
| 如果您要 ... | 使用此命令 ... 


| 在集群上启用 SNMP | 管理（ mgmt ）防火墙策略必须允许 SNMP 服务上的 options -option-name snmp.enable -option-value 。您可以使用 system services firewall policy show 命令验证是否允许使用 SNMP 。 


| 在集群上禁用 SNMP | options -option-name snmp.enable -option-value off 
|===


== 用于管理 SNMP v1 ， v2c 和 v3 用户的命令

[cols="2*"]
|===
| 如果您要 ... | 使用此命令 ... 


| 配置 SNMP 用户 | 创建安全登录 


| 显示 SNMP 用户 | security snmpusers 和 security login show -application snmp 


| 删除 SNMP 用户 | 安全登录删除 


| 修改 SNMP 用户登录方法的访问控制角色名称 | 安全登录修改 
|===


== 用于提供联系人和位置信息的命令

[cols="2*"]
|===
| 如果您要 ... | 使用此命令 ... 


| 显示或修改集群的联系详细信息 | 系统 SNMP 联系人 


| 显示或修改集群的位置详细信息 | 系统 SNMP 位置 
|===


== 用于管理 SNMP 社区的命令

[cols="2*"]
|===
| 如果您要 ... | 使用此命令 ... 


| 为 SVM 或集群中的所有 SVM 添加只读（ ro ）社区 | 系统 SNMP 社区添加 


| 删除一个社区或所有社区 | 系统 SNMP 社区删除 


| 显示所有社区的列表 | system snmp community show 
|===
由于 SVM 不是 SNMP 标准的一部分，因此对数据 LIF 的查询必须包含 NetApp 根 OID （ 1.3.6.1.4.1.789 ），例如， `snmpwalk -v 2c -c snmpNFS 10.238.19.14 1.3.6.1.4.1.789` 。



== 用于显示 SNMP 选项值的命令

[cols="2*"]
|===
| 如果您要 ... | 使用此命令 ... 


| 显示所有 SNMP 选项的当前值，包括集群联系人，联系人位置，集群是否配置为发送陷阱，陷阱主机列表以及社区列表和访问控制类型 | system snmp show 
|===


== 用于管理 SNMP 陷阱和陷阱主机的命令

[cols="2*"]
|===
| 如果您要 ... | 使用此命令 ... 


| 启用从集群发送的 SNMP 陷阱 | 系统 SNMP init -init 1 


| 禁用从集群发送的 SNMP 陷阱 | 系统 SNMP init -init 0 


| 添加一个陷阱主机，用于接收集群中特定事件的 SNMP 通知 | 系统 SNMP 陷阱主机添加 


| 删除陷阱主机 | 系统 SNMP 陷阱主机删除 


| 显示陷阱主机的列表 | system snmp traphost show 
|===


== 用于管理与 SNMP 陷阱相关的事件的命令

[cols="2*"]
|===
| 如果您要 ... | 使用此命令 ... 


 a| 
显示为其生成 SNMP 陷阱（内置）的事件
 a| 
event route show

使用 -snmp-support true 参数仅查看与 SNMP 相关的事件。

使用 instance -messagename <message> 参数查看可能发生事件的详细问题描述以及任何更正操作。

不支持将单个 SNMP 陷阱事件路由到特定陷阱主机目标。所有 SNMP 陷阱事件都会发送到所有陷阱主机目标。



 a| 
显示 SNMP 陷阱历史记录的列表，这些记录是已发送到 SNMP 陷阱的事件通知
 a| 
event snmphistory show



 a| 
删除 SNMP 陷阱历史记录
 a| 
事件 snmphistory delete

|===
有关 `ssystem snmp` ， `ssecurity` 和 `event` 命令的详细信息，请参见手册页： http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9 命令"^]
