---
sidebar: sidebar 
permalink: networking/configure_vlans_over_physical_ports.html 
keywords: configure, configuration, configuring, setup, setting, set, up, vlans, virtual local area network, physical, port, logical, segmentation, configure vlans over physical ports, vlans provide logical segmentation of networks, create a vlan, network port vlan create, delete a vlan, network port vlan delete 
summary: 您可以在ONTAP中使用VLAN来创建单独的广播域、这些广播域是在交换机端口上定义的、而不是在物理边界上定义的传统广播域、从而实现网络的逻辑分段。 
---
= 通过物理端口配置 VLAN
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以在ONTAP中使用VLAN来创建单独的广播域、这些广播域是在交换机端口上定义的、而不是在物理边界上定义的传统广播域、从而实现网络的逻辑分段。

一个 VLAN 可以跨越多个物理网段。属于 VLAN 的终端工作站按功能或应用程序相关联。

例如， VLAN 中的终端工作站可以按部门（如工程和会计）或项目（如 release1 和 release2 ）进行分组。由于终端工作站的物理位置在 VLAN 中并不重要，因此您可以将终端工作站分散在不同的地理位置，并且仍会将广播域包含在交换网络中。

在ONTAP 9.13.1和9.14.1中、任何逻辑接口(Logical Interface、lifs)未使用且所连接交换机上缺少本机VLAN连接的未标记端口将标记为已降级。这有助于确定未使用的端口、并不表示发生中断。本机VLAN允许在ifgrp基本端口上传输未标记的流量、例如ONTAP CFM广播。在交换机上配置本机VLAN、以防止阻止未标记的流量。

您可以通过创建，删除或显示 VLAN 的相关信息来管理 VLAN 。


NOTE: 您不应在标识符与交换机的原生 VLAN 相同的网络接口上创建 VLAN 。例如，如果网络接口 e0b 位于原生 VLAN 10 上，则不应在此接口上创建 VLAN e0b-10 。



== 创建VLAN

您可以使用System Manager或创建VLAN、以便在同一网络域中维护单独的广播域 `network port vlan create` 命令：

.开始之前
确认已满足以下要求：

* 网络中部署的交换机必须符合 IEEE 802.1Q 标准，或者实施供应商专用的 VLAN 。
* 要支持多个 VLAN ，必须静态配置一个终端工作站，使其属于一个或多个 VLAN 。
* VLAN 未连接到托管集群 LIF 的端口。
* VLAN 未连接到分配给集群 IP 空间的端口。
* 不会在不包含任何成员端口的接口组端口上创建 VLAN 。


.关于此任务
创建 VLAN 会将 VLAN 连接到集群中指定节点上的网络端口。

首次通过端口配置 VLAN 时，此端口可能会关闭，从而导致网络暂时断开连接。随后向同一端口添加 VLAN 不会影响端口状态。


NOTE: 您不应在标识符与交换机的原生 VLAN 相同的网络接口上创建 VLAN 。例如，如果网络接口 e0b 位于原生 VLAN 10 上，则不应在此接口上创建 VLAN e0b-10 。

您关注的操作步骤 取决于您使用的界面—System Manager或命令行界面：

[role="tabbed-block"]
====
.System Manager
--
*使用System Manager创建VLAN*

从ONTAP 9.12.0开始、您可以自动选择广播域或从列表中手动选择On。以前、始终会根据第2层连接自动选择广播域。如果您手动选择广播域、则会显示一条警告、指出手动选择广播域可能会导致连接丢失。

.步骤
. 选择*网络>以太网端口>+ VLAN*。
. 从下拉列表中选择节点。
. 从以下选项中进行选择：
+
.. ONTAP *自动选择广播域(建议)*。
.. 从列表中手动选择广播域。


. 选择要构成VLAN的端口。
. 指定VLAN ID。
. 保存所做的更改。


--
.命令行界面
--
*使用命令行界面创建VLAN*

在某些情况下、如果要在已降级的端口上创建VLAN端口、而不更正硬件问题描述或任何软件配置错误、则可以设置 `-ignore-health-status` 的参数 `network port modify` 命令作为 `true`。

.步骤
. 使用 `network port vlan create` 命令以创建VLAN。
. 您必须指定 `vlan-name` 或 `port` 和 `vlan-id` 选项。
VLAN 名称是端口（或接口组）名称和网络交换机 VLAN 标识符的组合，两者之间带有连字符。例如： `e0c-24` 和 `e1c-80` 是有效的VLAN名称。


以下示例显示了如何创建VLAN `e1c-80` 已连接到网络端口 `e1c` 在节点上 `cluster-1-01`：

....
network port vlan create -node cluster-1-01 -vlan-name e1c-80
....
从 ONTAP 9.8 开始， VLAN 会在创建后大约一分钟自动放置到相应的广播域中。如果您不希望ONTAP执行此操作、而希望手动将VLAN置于广播域中、请指定 `-skip-broadcast-domain-placement` 参数作为的一部分 `vlan create` 命令：

有关此命令的详细信息，请参见 https://docs.netapp.com/us-en/ontap-cli["ONTAP 命令参考"^]。

--
====


== 编辑VLAN

您可以更改广播域或禁用VLAN。

.使用System Manager编辑VLAN
从ONTAP 9.12.0开始、您可以自动选择广播域或从列表中手动选择On。以前的广播域始终会根据第2层连接自动选择。如果您手动选择广播域、则会显示一条警告、指出手动选择广播域可能会导致连接丢失。

.步骤
. 选择*网络>以太网端口> VLAN*。
. 选择编辑图标。
. 执行以下操作之一：
+
** 通过从列表中选择其他广播域来更改此广播域。
** 清除*已启用*复选框。


. 保存所做的更改。




== 删除VLAN

在从插槽中删除 NIC 之前，您可能需要删除 VLAN 。删除 VLAN 时，它会自动从使用它的所有故障转移规则和组中删除。

.开始之前
确保没有与 VLAN 关联的 LIF 。

.关于此任务
从端口删除最后一个 VLAN 可能发生原因会导致网络与端口暂时断开连接。

您关注的操作步骤 取决于您使用的界面—System Manager或命令行界面：

[role="tabbed-block"]
====
.System Manager
--
*使用System Manager删除VLAN*

.步骤
. 选择*网络>以太网端口> VLAN*。
. 选择要删除的VLAN。
. 单击 * 删除 * 。


--
.命令行界面
--
*使用命令行界面删除VLAN*

.步骤
使用 `network port vlan delete` 命令删除VLAN。

以下示例显示了如何删除VLAN `e1c-80` 从网络端口 `e1c` 在节点上 `cluster-1-01`：

....
network port vlan delete -node cluster-1-01 -vlan-name e1c-80
....
--
====