---
sidebar: sidebar 
permalink: networking/configure_lif_service_policies.html 
keywords: create service policy, assign service policy, service policy commands, configure lif service policies, create and assign a service policy for lifs, configure lif service policies, create a service policy for lifs, network interface service show, service-policy create, assign a service policy to a lif, examples, commands for managing lif service policies 
summary: 为 LIF 创建并分配服务策略 
---
= 为ONTAP集群配置LIF服务策略
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以配置 LIF 服务策略以确定要使用 LIF 的单个服务或服务列表。



== 为 LIF 创建服务策略

您可以为 LIF 创建服务策略。您可以将服务策略分配给一个或多个 LIF ，从而使 LIF 能够传输单个服务或一系列服务的流量。

您需要具有高级权限才能运行 `network interface service-policy create` 命令：

.关于此任务
内置服务和服务策略可用于管理数据和系统 SVM 上的数据和管理流量。大多数使用情形均可通过内置服务策略来满足，而不是创建自定义服务策略。

如果需要，您可以修改这些内置服务策略。

.步骤
. 查看集群中可用的服务：
+
....
network interface service show
....
+
服务表示 LIF 访问的应用程序以及集群提供服务的应用程序。每个服务包含零个或多个应用程序正在侦听的 TCP 和 UDP 端口。

+
此外，还提供了以下附加数据和管理服务：

+
....
cluster1::> network interface service show

Service                     Protocol:Ports
-------                     --------------
cluster-core                -
data-cifs                   -
data-core                   -
data-flexcache              -
data-iscsi                  -
data-nfs                    -
intercluster-core           tcp:11104-11105
management-autosupport      -
management-bgp              tcp:179
management-core             -
management-https            tcp:443
management-ssh              tcp:22
12 entries were displayed.
....
. 查看集群中存在的服务策略：
+
....
cluster1::> network interface service-policy show

Vserver   Policy                     Service: Allowed Addresses
--------- -------------------------- ----------------------------------------
cluster1
          default-intercluster       intercluster-core: 0.0.0.0/0
                                     management-https: 0.0.0.0/0

          default-management         management-core: 0.0.0.0/0
                                     management-autosupport: 0.0.0.0/0
                                     management-ssh: 0.0.0.0/0
                                     management-https: 0.0.0.0/0

          default-route-announce     management-bgp: 0.0.0.0/0

Cluster
          default-cluster            cluster-core: 0.0.0.0/0

vs0
          default-data-blocks        data-core: 0.0.0.0/0
                                     data-iscsi: 0.0.0.0/0

          default-data-files         data-core: 0.0.0.0/0
                                     data-nfs: 0.0.0.0/0
                                     data-cifs: 0.0.0.0/0
                                     data-flexcache: 0.0.0.0/0

          default-management         data-core: 0.0.0.0/0
                                     management-ssh: 0.0.0.0/0
                                     management-https: 0.0.0.0/0

7 entries were displayed.
....
. 创建服务策略：
+
....
cluster1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them only when directed to do so by technical support.
Do you wish to continue? (y or n): y

cluster1::> network interface service-policy create -vserver <svm_name> -policy <service_policy_name> -services <service_name> -allowed-addresses <IP_address/mask,...>
....
+
** "service_name" 指定应包含在策略中的服务列表。
** "ip_address/mask" 指定允许访问服务策略中服务的地址的子网掩码列表。默认情况下，添加所有指定服务时，默认允许的地址列表为 0.0.0.0/0 ，允许来自所有子网的流量。如果提供了非默认允许的地址列表，则会将使用此策略的 LIF 配置为阻止源地址与任何指定掩码不匹配的所有请求。
+
以下示例显示了如何为包含_nfs_和_smb_服务的SVM创建数据服务策略_svm1_data_policy_：

+
....
cluster1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them only when directed to do so by technical support.
Do you wish to continue? (y or n): y

cluster1::> network interface service-policy create -vserver svm1 -policy svm1_data_policy -services data-nfs,data-cifs,data-core
....
+
以下示例显示了如何创建集群间服务策略：

+
....
cluster1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them only when directed to do so by technical support.
Do you wish to continue? (y or n): y

cluster1::> network interface service-policy create -vserver cluster1 -policy intercluster1 -services intercluster-core
....


. 验证是否已创建服务策略。
+
....
cluster1::> network interface service-policy show
....
+
以下输出显示了可用的服务策略：

+
....
cluster1::> network interface service-policy show

Vserver   Policy                     Service: Allowed Addresses
--------- -------------------------- ----------------------------------------
cluster1
          default-intercluster       intercluster-core: 0.0.0.0/0
                                     management-https: 0.0.0.0/0

          intercluster1              intercluster-core: 0.0.0.0/0

          default-management         management-core: 0.0.0.0/0
                                     management-autosupport: 0.0.0.0/0
                                     management-ssh: 0.0.0.0/0
                                     management-https: 0.0.0.0/0

          default-route-announce     management-bgp: 0.0.0.0/0

Cluster
          default-cluster            cluster-core: 0.0.0.0/0

vs0
          default-data-blocks        data-core: 0.0.0.0/0
                                     data-iscsi: 0.0.0.0/0

          default-data-files         data-core: 0.0.0.0/0
                                     data-nfs: 0.0.0.0/0
                                     data-cifs: 0.0.0.0/0
                                     data-flexcache: 0.0.0.0/0

          default-management         data-core: 0.0.0.0/0
                                     management-ssh: 0.0.0.0/0
                                     management-https: 0.0.0.0/0

          svm1_data_policy           data-core: 0.0.0.0/0
                                     data-nfs: 0.0.0.0/0
                                     data-cifs: 0.0.0.0/0

9 entries were displayed.
....


.完成后
在创建 LIF 时或通过修改现有 LIF 将服务策略分配给 LIF 。



== 为 LIF 分配服务策略

您可以在创建 LIF 时为 LIF 分配服务策略，也可以通过修改 LIF 来分配服务策略。服务策略用于定义可与 LIF 一起使用的服务列表。

.关于此任务
您可以在管理和数据 SVM 中为 LIF 分配服务策略。

.步骤
根据您要将服务策略分配给 LIF 的时间，请执行以下操作之一：

[cols="25,75"]
|===
| 如果您 ... | 分配服务策略 ... 


| 创建 LIF | 网络接口 create -vserver svm_name -lif <lif_name> -home-node <node_name> -home-port <port_name> ｛ （ -address <IP_address> -netmask <IP_address> ） -subnet-name <subnet_name> ｝ -service-policy <service_policy_name> 


| 修改 LIF | network interface modify -vserver <svm_name> -lif <lif_name> -service-policy <service_policy_name> 
|===
为 LIF 指定服务策略时，无需为此 LIF 指定数据协议和角色。此外，还支持通过指定角色和数据协议来创建 LIF 。


NOTE: 服务策略只能由创建服务策略时指定的同一 SVM 中的 LIF 使用。



=== 示例

以下示例显示了如何修改 LIF 的服务策略以使用默认管理服务策略：

....
cluster1::> network interface modify -vserver cluster1 -lif lif1 -service-policy default-management
....


== 用于管理 LIF 服务策略的命令

使用 `network interface service-policy` 用于管理LIF服务策略的命令。

有关的详细信息 `network interface service-policy`，请参见link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+interface+service-policy["ONTAP 命令参考"^]。

.开始之前
修改活动SnapMirror关系中LIF的服务策略会中断复制计划。如果将LIF从集群间转换为非集群间(或反之)、则这些更改不会复制到对等集群。要在修改LIF服务策略后更新对等集群、请先执行 `snapmirror abort` 操作 xref:../data-protection/resynchronize-relationship-task.html[重新同步复制关系]。

|===
| 如果您要 ... | 使用此命令 ... 


 a| 
创建服务策略(需要高级权限)
 a| 
`network interface service-policy create`



 a| 
向现有服务策略添加其他服务条目(需要高级权限)
 a| 
`network interface service-policy add-service`



 a| 
克隆现有服务策略(需要高级权限)
 a| 
`network interface service-policy clone`



 a| 
修改现有服务策略中的服务条目(需要高级权限)
 a| 
`network interface service-policy modify-service`



 a| 
从现有服务策略中删除服务条目(需要高级权限)
 a| 
`network interface service-policy remove-service`



 a| 
重命名现有服务策略(需要高级权限)
 a| 
`network interface service-policy rename`



 a| 
删除现有服务策略(需要高级权限)
 a| 
`network interface service-policy delete`



 a| 
将内置服务策略还原到其原始状态(需要高级权限)
 a| 
`network interface service-policy restore-defaults`



 a| 
显示现有服务策略
 a| 
`network interface service-policy show`

|===
.相关信息
* link:https://docs.netapp.com/us-en/ontap-cli/network-interface-service-show.html["network interface service show"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+interface+service-policy["network interface service-policy"^]

