---
sidebar: sidebar 
permalink: networking/create_an_snmp_community_and_assigning_it_to_a_lif.html 
keywords: create, creation, creating, add, adding, snmp, community, assign, assigning, lif, logical, interface, create an snmp community and assigning it to a lif, snmpwalk, snmpget, snmp community add 
summary: 创建一个 SNMP 社区，用作管理工作站和 SVM 之间的身份验证机制 
---
= 创建 SNMP 社区并将其分配给 LIF
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用 SNMPv1 和 SNMPv2c 时，您可以创建 SNMP 社区，作为管理工作站和 Storage Virtual Machine （ SVM ）之间的身份验证机制。

通过在数据SVM中创建SNMP社区、您可以执行等命令 `snmpwalk` 和 `snmpget` 在数据生命周期中。

.关于此任务
* 在新安装的 ONTAP 中， SNMPv1 和 SNMPv2c 默认处于禁用状态。
+
创建 SNMP 社区后， SNMPv1 和 SNMPv2c 将处于启用状态。

* ONTAP 支持只读社区。
* 默认情况下、分配给数据"LIF"的"数据"防火墙策略会将SNMP服务设置为 `deny`。
+
您必须创建一个新的防火墙策略、并将SNMP服务设置为 `allow` 为数据SVM创建SNMP用户时。

+

NOTE: 从ONTAP 9.10.1开始、防火墙策略已弃用、并完全替换为LIF服务策略。有关详细信息，请参见 link:../networking/configure_firewall_policies_for_lifs.html["为 LIF 配置防火墙策略"]。

* 您可以为管理 SVM 和数据 SVM 的 SNMPv1 和 SNMPv2c 用户创建 SNMP 社区。
* 由于SVM不是SNMP标准的一部分、因此对数据NetApp的查询必须包括SVM根OID (1.3.6.1.4.1.789)、例如 `snmpwalk -v 2c -c snmpNFS 10.238.19.14 1.3.6.1.4.1.789`。


.步骤
. 使用创建SNMP社区 `system snmp community add` 命令：以下命令显示如何在管理 SVM cluster-1 中创建 SNMP 社区：
+
....
system snmp community add -type ro -community-name comty1 -vserver cluster-1
....
+
以下命令显示如何在数据 SVM vs1 中创建 SNMP 社区：

+
....
system snmp community add -type ro -community-name comty2 -vserver vs1
....
. 使用 system snmp community show 命令验证是否已创建社区。
+
以下命令显示了为 SNMPv1 和 SNMPv2c 创建的两个社区：

+
....
system snmp community show
cluster-1
rocomty1
vs1
rocomty2
....
. 使用检查"data"防火墙策略中是否允许SNMP作为服务 `system services firewall policy` `show` 命令：
+
以下命令显示默认 "data" 防火墙策略中不允许使用 SNMP 服务（仅 "mgmt" 防火墙策略中允许使用 SNMP 服务）：

+
....
system services firewall policy show
Vserver Policy       Service    Allowed
------- ------------ ---------- -------------------
cluster-1
        data
                     dns        0.0.0.0/0
                     ndmp       0.0.0.0/0
                     ndmps      0.0.0.0/0
cluster-1
        intercluster
                     https      0.0.0.0/0
                     ndmp       0.0.0.0/0
                     ndmps      0.0.0.0/0
cluster-1
        mgmt
                     dns        0.0.0.0/0
                     http       0.0.0.0/0
                     https      0.0.0.0/0
                     ndmp       0.0.0.0/0
                     ndmps      0.0.0.0/0
                     ntp        0.0.0.0/0
                     snmp       0.0.0.0/0
                     ssh        0.0.0.0/0
....
. 使用创建允许访问的新防火墙策略 `snmp` 服务 `system services firewall policy create` 命令：
+
以下命令将创建一个名为data1的新数据防火墙策略、此策略允许使用 `snmp`

+
....
system services firewall policy create -policy data1 -service snmp -vserver  vs1 -allow-list 0.0.0.0/0

cluster-1::> system services firewall policy show -service snmp
Vserver  Policy       Service    Allowed
-------  ------------ ---------- -------------------
cluster-1
         mgmt
                      snmp       0.0.0.0/0
vs1
         data1
                      snmp       0.0.0.0/0
....
. 使用带有 -firewall-policy 参数的 `network interface modify `命令将防火墙策略应用于数据 LIF 。
+
以下命令会将新的 "data1" 防火墙策略分配给 LIF "datalif1" ：

+
....
network interface modify -vserver vs1 -lif datalif1 -firewall-policy data1
....

