---
sidebar: sidebar 
permalink: networking/create_a_lif.html 
keywords: example LIFs, add LIFs, configure LIFs, create, creation, creating, add, adding, logical, interface, service, policies, policy, create a lif, network interface capacity show, lif examples 
summary: 创建一个 LIF ，此 LIF 是与物理或逻辑端口关联的 IP 地址。 
---
= 创建 LIF
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
LIF 是指与物理或逻辑端口关联的 IP 地址。如果组件出现故障，则 LIF 可以故障转移到或迁移到其他物理端口，从而继续与网络通信。

.开始之前
* 底层物理或逻辑网络端口必须已配置为管理启动状态。
* 如果您计划使用子网名称为 LIF 分配 IP 地址和网络掩码值，则此子网必须已存在。
+
子网包含属于同一第 3 层子网的 IP 地址池。可以使用 `network subnet create` 命令创建这些子网。

* 用于指定 LIF 处理的流量类型的机制已发生更改。对于 ONTAP 9.5 及更早版本， LIF 使用角色指定要处理的流量类型。从 ONTAP 9.6 开始， LIF 使用服务策略指定要处理的流量类型。


.关于此任务
* 您不能将 NAS 和 SAN 协议分配给同一个 LIF 。
+
支持的协议包括 SMB ， NFS ， FlexCache ， iSCSI 和 FC ； iSCSI 和 FC 不能与其他协议结合使用。但是， NAS 和基于以太网的 SAN 协议可以位于同一物理端口上。

* 您可以在同一网络端口上创建 IPv4 和 IPv6 LIF 。
* SVM 使用的所有名称映射和主机名解析服务，例如 DNS ， NIS ， LDAP 和 Active Directory 。 必须可从至少一个处理 SVM 数据流量的 LIF 进行访问。
* 处理节点之间集群内流量的 LIF 不应与处理管理流量的 LIF 或处理数据流量的 LIF 位于同一子网上。
* 如果创建的 LIF 没有有效的故障转移目标，则会显示一条警告消息。
* 如果集群中有大量 LIF ，您可以使用 `network interface capacity show` 命令验证集群上支持的 LIF 容量，并使用 `network interface capacity details show` 命令验证每个节点上支持的 LIF 容量 （在高级权限级别）。
* 从 ONTAP 9.7 开始，如果同一子网中已存在 SVM 的其他 LIF ，则无需指定 LIF 的主端口。ONTAP 会自动在与已在同一子网中配置的其他 LIF 位于同一广播域的指定主节点上选择一个随机端口。
+
从 ONTAP 9.4 开始，支持 FC-NVMe 。如果要创建 FC-NVMe LIF ，应注意以下事项：

+
** 创建 LIF 的 FC 适配器必须支持 NVMe 协议。
** FC-NVMe 可以是数据 LIF 上的唯一数据协议。


* 必须为支持 SAN 的每个 Storage Virtual Machine （ SVM ）配置一个 LIF 处理管理流量。
* NVMe LIF 和命名空间必须托管在同一节点上。
* 每个 SVM 只能配置一个处理数据流量的 NVMe LIF 。


.步骤
. 创建 LIF ：
+
....
network interface create -vserver vserver_name -lif lif_name -service-policy service_policy_name -home-node node_name -home-port port_name {-address IP_address - netmask Netmask_value | -subnet-name subnet_name} -firewall- policy policy -auto-revert {true|false}
....
+
** ` -home-node` 是在 LIF 上运行 `network interface revert` 命令时 LIF 返回到的节点。
+
您还可以使用 -auto-revert 选项指定 LIF 是否应自动还原到主节点和主端口。

** ` 主端口` 是在 LIF 上运行 `network interface revert` 命令时 LIF 返回到的物理或逻辑端口。
** 您可以使用 ` 地址` 和 ` 网络掩码` 选项指定 IP 地址，也可以使用 ` -subnet_name` 选项从子网进行分配。
** 使用子网提供 IP 地址和网络掩码时，如果使用网关定义了子网，则在使用该子网创建 LIF 时，系统会自动向 SVM 添加指向该网关的默认路由。
** 如果您手动分配 IP 地址（而不使用子网），则在其他 IP 子网上存在客户端或域控制器时，可能需要配置指向网关的默认路由。`network route create` 手册页包含有关在 SVM 中创建静态路由的信息。
** 使用 ` -auto-revert` 可以指定在启动，更改管理数据库状态或建立网络连接等情况下数据 LIF 是否自动还原到其主节点。默认设置为 `false` ，但您可以根据环境中的网络管理策略将其设置为 `true` 。
** ` -service-policy` 从 ONTAP 9.5 开始，您可以使用 ` -service-policy` 选项为 LIF 分配服务策略。为 LIF 指定服务策略时，将使用该策略为 LIF 构建默认角色，故障转移策略和数据协议列表。在 ONTAP 9.5 中，只有集群间和 BGP 对等服务才支持服务策略。在 ONTAP 9.6 中，您可以为多个数据和管理服务创建服务策略。
** 使用 ` 数据协议` ，您可以创建支持光纤通道协议（ FCP ）或 NVMe/FC 协议的 LIF 。创建 IP LIF 时不需要此选项。


. * 可选 * ：如果要在 -address 选项中分配 IPv6 地址：
+
.. 使用 network ndp prefix show 命令查看在各种接口上获取的 RA 前缀列表。
+
可以在高级权限级别使用 `network ndp prefix show` 命令。

.. 使用格式 `prefix ：： id` 手动构建 IPv6 地址。
+
`prefix` 是在各种接口上获取的前缀。

+
要派生 `id` ，请选择一个 64 位随机十六进制数。



. 使用 `network interface show` 命令验证是否已成功创建 LIF 。
. 验证配置的 IP 地址是否可访问：


|===


| 要验证 ... | 使用 ... 


| IPv4 地址 | 网络 ping 


| IPv6 地址 | 网络 ping6. 
|===


== 示例

以下命令将创建一个 LIF ，并使用 ` 地址` 和 ` 网络掩码` 参数指定 IP 地址和网络掩码值：

....
network interface create -vserver vs1.example.com -lif datalif1 -service-policy default-data-files -home-node node-4 -home-port e1c -address 192.0.2.145 -netmask 255.255.255.0 -auto-revert true
....
以下命令将创建一个 LIF ，并从指定子网（名为 client1_sub ）分配 IP 地址和网络掩码值：

....
network interface create -vserver vs3.example.com -lif datalif3 -service-policy default-data-files -home-node node-3 -home-port e1c -subnet-name client1_sub - auto-revert true
....
以下命令将创建 NVMe/FC LIF 并指定 `NVMe-fc` 数据协议：

....
network interface create -vserver vs1.example.com -lif datalif1 -data-protocol nvme-fc -home-node node-4 -home-port 1c -address 192.0.2.145 -netmask 255.255.255.0 -auto-revert true
....