---
sidebar: sidebar 
permalink: networking/create_a_dns_load_balancing_zone.html 
keywords: create, creation, creating, add, adding, dns, naming, name, service, load, balancing, balance, zone, lif, create a dns load balancing zone, improve lif performance 
summary: 创建 DNS 负载平衡区域以提高 LIF 性能 
---
= 为ONTAP网络创建DNS负载平衡区域
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以创建 DNS 负载平衡区域，以便根据负载动态选择 LIF ，即装载在 LIF 上的客户端数量。您可以在创建数据 LIF 时创建负载平衡区域。

.开始之前
必须将站点范围 DNS 服务器上的 DNS 转发器配置为将负载平衡区域的所有请求转发到已配置的 LIF 。

知识库文章 link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_set_up_DNS_load_balancing_in_clustered_Data_ONTAP["如何在集群模式下设置 DNS 负载平衡"^] NetApp 支持站点上提供了有关使用条件转发配置 DNS 负载平衡的详细信息。

.关于此任务
* 任何数据 LIF 都可以响应 DNS 查询，以获取 DNS 负载平衡区域名称。
* DNS 负载平衡区域在集群中必须具有唯一名称，并且此区域名称必须满足以下要求：
+
** 不应超过 256 个字符。
** 它应至少包含一个句点。
** 第一个和最后一个字符不应是句点或任何其他特殊字符。
** 字符之间不能包含任何空格。
** DNS 名称中的每个标签不应超过 63 个字符。
+
标签是指在句点之前或之后显示的文本。例如，名为 storage.company.com 的 DNS 区域具有三个标签。





.步骤
使用 `network interface create` 命令 `dns-zone` 用于创建DNS负载平衡区域的选项。

如果负载平衡区域已存在，则会将 LIF 添加到该区域中。有关命令的详细信息，请参见 https://docs.netapp.com/us-en/ontap-cli["ONTAP 命令参考"^]。

以下示例演示如何在创建LIF时创建名为storage.company.com的DNS负载平衡区域 `lif1`：

....
network interface create -vserver vs0 -lif lif1 -home-node node1
-home-port e0c -address 192.0.2.129 -netmask 255.255.255.128 -dns-zone storage.company.com
....