---
sidebar: sidebar 
permalink: networking/determine_which_ports_can_be_used_for_a_broadcast_domains.html 
keywords: move, moving, broadcast, domain, ipspace, determining which ports can be used for a broadcast domain, before you can configure a broadcast domain to add to the new ipspace, you must determine what ports are available for the broadcast domain 
summary: 在配置要添加到新 IP 空间的广播域之前，您必须先确定哪些端口可用于此广播域 
---
= 确定哪些端口可用于广播域(ONTAP 9.7及更早版本)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在配置要添加到新 IP 空间的广播域之前，您必须先确定哪些端口可用于此广播域。


NOTE: 此任务与 ONTAP 9.0 - 9.7 相关，而不是与 ONTAP 9.8 相关。

.开始之前
您必须是集群管理员才能执行此任务。

.关于此任务
* 端口可以是物理端口， VLAN 或接口组（ ifgroups ）。
* 不能将要添加到新广播域的端口分配给现有广播域。
* 如果要添加到广播域的端口已位于另一个广播域中（例如，默认 IP 空间中的默认广播域），则必须先从该广播域中删除这些端口，然后再将其分配给新的广播域。
* 无法从广播域中删除已分配 LIF 的端口。
* 由于集群管理和节点管理 LIF 已分配给默认 IP 空间中的默认广播域，因此无法从默认广播域中删除分配给这些 LIF 的端口。


.步骤
. 确定当前端口分配。
+
`network port show`

+
[listing]
----
Node   Port IPspace  Broadcast Domain Link   MTU  Admin/Oper
------ ---- -------  ---------------- ----- ----  ------------
node1
       e0a  Cluster  Cluster          up    9000  auto/1000
       e0b  Cluster  Cluster          up    9000  auto/1000
       e0c  Default  Default          up    1500  auto/1000
       e0d  Default  Default          up    1500  auto/1000
       e0e  Default  Default          up    1500  auto/1000
       e0f  Default  Default          up    1500  auto/1000
       e0g  Default  Default          up    1500  auto/1000
node2
       e0a  Cluster  Cluster          up    9000  auto/1000
       e0b  Cluster  Cluster          up    9000  auto/1000
       e0c  Default  Default          up    1500  auto/1000
       e0d  Default  Default          up    1500  auto/1000
       e0e  Default  Default          up    1500  auto/1000
       e0f  Default  Default          up    1500  auto/1000
       e0g  Default  Default          up    1500  auto/1000
----
+
在此示例中，命令的输出提供了以下信息：

+
** 端口 `e0c`， `e0d`， `e0e`， `e0f`，和 `e0g` 在每个节点上、系统会将其分配给默认广播域。
** 这些端口可能可在要创建的 IP 空间的广播域中使用。


. 确定默认广播域中的哪些端口已分配给 LIF 接口，因此无法移动到新的广播域。
+
`network interface show`

+
[listing]
----
         Logical      Status     Network         Current   Current Is
Vserver  Interface    Admin/Oper Address/Mask    Node      Port    Home
-------  ----------   ---------- ------------   --------- -------  ----
Cluster
         node1_clus1  up/up       10.0.2.40/24   node1     e0a     true
         node1_clus2  up/up       10.0.2.41/24   node1     e0b     true
         node2_clus1  up/up       10.0.2.42/24   node2     e0a     true
         node2_clus2  up/up       10.0.2.43/24   node2     e0b     true

cluster1
         cluster_mgmt up/up       10.0.1.41/24   node1     e0c     true
         node1_mgmt   up/up       10.0.1.42/24   node1     e0c     true
         node2_mgmt   up/up       10.0.1.43/24   node2     e0c     true
----
+
在以下示例中，命令的输出提供了以下信息：

+
** 节点端口将分配给端口 `e0c` 在每个节点上、并且集群管理LIF的主节点处于打开状态 `e0c` 开启 `node1`。
** 端口 `e0d`， `e0e`， `e0f`，和 `e0g` 在每个节点上、均不托管任何生命周期、可以从默认广播域中删除、然后将其添加到新IP空间的新广播域中。



