---
sidebar: sidebar 
permalink: networking/lif_compatibility_with_port_types.html 
keywords: lif, compatibility, port, types, lif compatibility with port types 
summary: LIF 可以具有不同的特性来支持不同的端口类型 
---
= LIF 与端口类型的兼容性
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
LIF 可以具有不同的特性来支持不同的端口类型。


NOTE: 如果在同一子网中配置了集群间和管理 LIF ，则管理流量可能会被外部防火墙阻止，并且 AutoSupport 和 NTP 连接可能会失败。您可以通过运行来恢复系统 `network interface modify -vserver _vserver name_ -lif _intercluster LIF_ -status-admin up|down` 命令切换集群间LIF。但是，您应在不同子网中设置集群间 LIF 和管理 LIF ，以避免使用此问题描述。

[cols="30,70"]
|===


| LIF | Description 


| 数据 LIF | 与 Storage Virtual Machine （ SVM ）关联并用于与客户端通信的 LIF 。
一个端口上可以有多个数据 LIF 。这些接口可以在整个集群中进行迁移或故障转移。您可以通过将数据 LIF 的防火墙策略修改为 mgmt 来将其用作 SVM 管理 LIF 。

与 NIS ， LDAP ， Active Directory ， WINS 和 DNS 服务器建立的会话使用数据 LIF 。 


| 集群 LIF | 一种 LIF ，用于在集群中的节点之间传输集群内流量。必须始终在集群端口上创建集群 LIF 。

集群 LIF 可以在同一节点上的集群端口之间进行故障转移，但不能迁移或故障转移到远程节点。当新节点加入集群时，系统会自动生成 IP 地址。但是，如果要手动为集群 LIF 分配 IP 地址，则必须确保新 IP 地址与现有集群 LIF 位于同一子网范围内。 


| 集群管理 LIF | 为整个集群提供一个管理接口的 LIF 。

集群管理 LIF 可以故障转移到集群中的任何节点。它无法故障转移到集群或集群间端口 


| 集群间 LIF | 一种用于跨集群通信，备份和复制的 LIF 。您必须先在集群中的每个节点上创建一个集群间 LIF ，然后才能建立集群对等关系。

这些 LIF 只能故障转移到同一节点中的端口。它们不能迁移或故障转移到集群中的另一个节点。 


| 节点管理 LIF | 一种 LIF ，用于提供用于管理集群中特定节点的专用 IP 地址。节点管理 LIF 是在创建或加入集群时创建的。这些 LIF 用于系统维护，例如，当节点无法从集群访问时。 


| VIP LIF | VIP LIF 是指在 VIP 端口上创建的任何数据 LIF 。要了解更多信息，请参见 link:https://docs.netapp.com/us-en/ontap/networking/configure_virtual_ip_@vip@_lifs.html["配置虚拟 IP （ VIP ） LIF"^]。 
|===