---
sidebar: sidebar 
permalink: networking/lifs_and_service_policies96.html 
keywords: service policies for system svms, lif service policies, lif, logical, interface, service, policy, policies, lifs and service policies in ontap 9.6 and later, assign service policies to lifs to specify the supported traffic, service policies for system svms, service policies for data svms, data-core service 
summary: 为 LIF 分配服务策略以指定支持的流量 
---
= ONTAP 9.6及更高版本
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以将服务策略(而不是LIF角色或防火墙策略)分配给LIF、以确定LIF支持的流量类型。服务策略定义 LIF 支持的一组网络服务。ONTAP 提供了一组可与 LIF 关联的内置服务策略。

您可以使用以下命令显示服务策略及其详细信息：
`network interface service-policy show`

未绑定到特定服务的功能将使用系统定义的行为为出站连接选择生命周期。



== 系统 SVM 的服务策略

管理 SVM 和任何系统 SVM 都包含可用于该 SVM 中 LIF 的服务策略，包括管理和集群间 LIF 。创建 IP 空间时，系统会自动创建这些策略。

下表列出了截至ONTAP 9.12.1的系统SVM中的内置的LUN策略。对于其他版本，使用以下命令显示服务策略及其详细信息：

`network interface service-policy show`

[cols="20,20,20,40"]
|===


| 策略 | 包括的服务 | 等效角色 | Description 


 a| 
default-intercluster
 a| 
集群间核心，管理 https
 a| 
集群间
 a| 
由传输集群间流量的 LIF 使用。
注意： ONTAP 9.5 提供了名称为 net-intercluster service policy 的服务集群间核心。



 a| 
default-route-announce
 a| 
管理 BGP
 a| 
-
 a| 
由传输BGP对等连接的生命周期管理器使用
注意：从ONTAP 9.5开始提供、名称为net-route-n탻 늼 服务策略。



 a| 
default-management
 a| 
management-core、management-https、management-http、management-ssh、management-autosupport、 management-EMS、management-dns-client、management-ad-client、management-ldap-client、management-nis-client、 management-ntp-client、management-log-forwarding
 a| 
node-mgmt 或 cluster-mgmt
 a| 
使用此系统范围的管理策略创建系统SVM所拥有的节点和集群范围的管理LIF。这些LIF可用于到DNS、AD、LDAP或NIS服务器的出站连接、以及一些附加连接、以支持代表整个系统运行的应用程序。
从ONTAP 9.12.1开始、您可以使用 `management-log-forwarding` 用于控制用于将审核日志转发到远程系统日志服务器的LIF的服务。

|===
下表列出了自ONTAP 9.11.1之日LIF可在系统SVM上使用的服务：

[cols="25,25,50"]
|===


| 服务 | 故障转移限制 | Description 


 a| 
集群间核心
 a| 
仅主节点
 a| 
核心集群间服务



 a| 
管理核心
 a| 
-
 a| 
核心管理服务



 a| 
management-ssh
 a| 
-
 a| 
用于 SSH 管理访问的服务



 a| 
management-http
 a| 
-
 a| 
用于HTTP管理访问的服务



 a| 
management-https
 a| 
-
 a| 
用于HTTPS管理访问的服务



 a| 
management-autosupport
 a| 
-
 a| 
与发布 AutoSupport 有效负载相关的服务



 a| 
管理 BGP
 a| 
仅主端口
 a| 
与 BGP 对等交互相关的服务



 a| 
backup-ndmp-control
 a| 
-
 a| 
NDMP 备份控制服务



 a| 
管理 EMS
 a| 
-
 a| 
用于管理消息访问的服务



 a| 
management-ntp-client
 a| 
-
 a| 
在ONTAP 9.10.1中引入。
用于 NTP 客户端访问的服务。



 a| 
management-ntp-server
 a| 
-
 a| 
在ONTAP 9.10.1中引入。
用于 NTP 服务器管理访问的服务



 a| 
management-portmap
 a| 
-
 a| 
端口映射管理服务



 a| 
management-rsh-server
 a| 
-
 a| 
用于 RSH 服务器管理的服务



 a| 
management-snmp-server
 a| 
-
 a| 
SNMP 服务器管理服务



 a| 
management-telnet-server
 a| 
-
 a| 
用于 telnet 服务器管理的服务



 a| 
management-log-forwarding
 a| 
-
 a| 
在ONTAP 9.12.1中推出。
用于审核日志转发的服务

|===


== 数据 SVM 的服务策略

所有数据 SVM 都包含可由该 SVM 中的 LIF 使用的服务策略。

下表列出了自ONTAP 9.11.1之日数据SVM中LIF的内置策略。对于其他版本，使用以下命令显示服务策略及其详细信息：

`network interface service-policy show`

[cols="20,20,20,40"]
|===


| 策略 | 包括的服务 | 等效数据协议 | Description 


 a| 
default-management
 a| 
management-https、management-http、management-ssh、management-ds-client、management-ad-client、 management-ldap-client、management-nis-client
 a| 
无
 a| 
使用此SVM范围的管理策略创建数据SVM所拥有的SVM管理LIF。这些 LIF 可用于为 SVM 管理员提供 SSH 或 HTTPS 访问权限。必要时、可以使用这些LIF与外部DNS、AD、LDAP或NIS服务器进行出站连接。



 a| 
default-data-blocks
 a| 
数据核心，数据 iSCSI
 a| 
iSCSI
 a| 
由传输面向块的SAN数据流量的LIF使用。从ONTAP 9.10.1开始、"default-data-blocs"策略已弃用。请改用"default-data-iscsi"服务策略。



 a| 
default-data-files
 a| 
data-fpolicy-client、data-ds-server、data-FlexCache、data-cifs、data-nfs、 management-dns-client、management-ad-client、management-ldap-client、management-nis-client
 a| 
NFS ， CIFS ， fcache
 a| 
使用default-data-files策略创建支持基于文件的数据协议的NAS LIF。有时、SVM中只有一个LIF、因此、此策略允许使用此LIF与外部DNS、AD、LDAP或NIS服务器进行出站连接。如果您希望这些连接仅使用管理LIF、则可以从此策略中删除这些服务。



 a| 
default-data-iscsi
 a| 
数据核心，数据 iSCSI
 a| 
iSCSI
 a| 
由传输iSCSI数据流量的LIF使用。



 a| 
default-data-NVMe-tcp
 a| 
数据核心、数据NVMe-TCP
 a| 
NVMe-TCP
 a| 
由传输NVMe/TCP数据流量的LIF使用。

|===
下表列出了数据SVM上可使用的服务以及每个服务自ONTAP 9.11.1之日对LIF的故障转移策略施加的任何限制：

[cols="25,25,50"]
|===


| 服务 | 故障转移限制 | Description 


 a| 
management-ssh
 a| 
-
 a| 
用于 SSH 管理访问的服务



 a| 
management-http
 a| 
-
 a| 
在ONTAP 9.10.1中推出
用于HTTP管理访问的服务



 a| 
management-https
 a| 
-
 a| 
用于HTTPS管理访问的服务



 a| 
management-portmap
 a| 
-
 a| 
用于 portmap 管理访问的服务



 a| 
management-snmp-server
 a| 
-
 a| 
在ONTAP 9.10.1中推出
用于SNMP服务器管理访问的服务



 a| 
数据核心
 a| 
-
 a| 
核心数据服务



 a| 
数据 NFS
 a| 
-
 a| 
NFS 数据服务



 a| 
数据 CIFS
 a| 
-
 a| 
CIFS数据服务



 a| 
数据 FlexCache
 a| 
-
 a| 
FlexCache 数据服务



 a| 
数据 iSCSI
 a| 
仅主端口
 a| 
iSCSI 数据服务



 a| 
backup-ndmp-control
 a| 
-
 a| 
在ONTAP 9.10.1中推出
备份 NDMP 控制数据服务



 a| 
data-ds-server
 a| 
-
 a| 
在ONTAP 9.10.1中推出
DNS 服务器数据服务



 a| 
data-fpolicy-client
 a| 
-
 a| 
文件筛选策略数据服务



 a| 
data-NVMe-tcp
 a| 
仅主端口
 a| 
在ONTAP 9.10.1中推出
NVMe TCP 数据服务



 a| 
data-s3-server
 a| 
-
 a| 
简单存储服务（ S3 ）服务器数据服务

|===
您应了解如何将服务策略分配给数据 SVM 中的 LIF ：

* 如果创建的数据 SVM 包含一系列数据服务，则会使用指定的服务创建该 SVM 中的内置 "default-data-files" 和 "default-data-blocs" 服务策略。
* 如果在创建数据 SVM 时未指定数据服务列表，则会使用默认数据服务列表创建该 SVM 中的内置 "default-data-files" 和 "default-data-blocs" 服务策略。
+
默认数据服务列表包括iSCSI、NFS、NVMe、SMB和FlexCache 服务。

* 创建包含数据协议列表的 LIF 时，系统会为 LIF 分配与指定数据协议等效的服务策略。
* 如果不存在等效服务策略，则会创建自定义服务策略。
* 如果创建 LIF 时没有服务策略或数据协议列表，则默认情况下会将 default-data-files 服务策略分配给 LIF 。




== 数据核心服务

通过数据核心服务，以前使用具有数据角色的 LIF 的组件可以在已升级的集群上按预期工作，以便使用服务策略而不是 LIF 角色（在 ONTAP 9.6 中已弃用）来管理 LIF 。

将数据核心指定为服务不会打开防火墙中的任何端口，但此服务应包含在数据 SVM 的任何服务策略中。例如， default-data-files 服务策略默认包含以下服务：

* 数据核心
* 数据 NFS
* 数据 CIFS
* 数据 FlexCache


策略中应包含数据核心服务，以确保使用 LIF 的所有应用程序均按预期运行，但如果需要，可以删除其他三项服务。



== 客户端 LIF 服务

从 ONTAP 9.10.1 开始， ONTAP 为多个应用程序提供客户端 LIF 服务。这些服务可代表每个应用程序控制用于出站连接的 LIF 。

以下新服务可使管理员控制哪些 LIF 用作某些应用程序的源地址。

[cols="25,25,50"]
|===


| 服务 | SVM 限制 | Description 


 a| 
management-ad-client
 a| 
-
 a| 
从ONTAP 9.11.1开始、ONTAP 为与外部AD服务器的出站连接提供Active Directory客户端服务。



| management-dns-client  a| 
-
 a| 
从ONTAP 9.11.1开始、ONTAP 为与外部DNS服务器的出站连接提供DNS客户端服务。



| management-ldap-client  a| 
-
 a| 
从ONTAP 9.11.1开始、ONTAP为与外部LDAP服务器的出站连接提供LDAP客户端服务。



| management-nis-client  a| 
-
 a| 
从ONTAP 9.11.1开始、ONTAP为与外部NIS服务器的出站连接提供NIS客户端服务。



 a| 
management-ntp-client
 a| 
仅限系统
 a| 
从 ONTAP 9.10.1 开始， ONTAP 为与外部 NTP 服务器的出站连接提供 NTP 客户端服务。



 a| 
data-fpolicy-client
 a| 
纯数据
 a| 
从 ONTAP 9.8 开始， ONTAP 为出站 FPolicy 连接提供客户端服务。

|===
每个新服务都会自动包含在某些内置服务策略中，但管理员可以从内置策略中删除这些服务，或者将其添加到自定义策略中，以代表每个应用程序控制用于出站连接的 LIF 。
