---
sidebar: sidebar 
permalink: networking/ontap_port_usage_on_a_storage_system_overview.html 
keywords: port, tcp, udp, ontap, external, externally, service, services, introduce, introduction, introducing, overview, ontap port usage overview, ontap port usage, network ports, ontap ports, tcp ports, udp ports, ssh, port 22, telnet, port 23, dns, port 53, http, port 80, rpcbind, port 111, ntp, port 123, msrpc, port 135, netbios-ssn, port 139, snmp, port 161, https, port 443, microsoft-ds, port 445, mount, port 635, named, port 953, nfs, port 2049, nrv, port 2050, iscsi, port 3260, lockd, port 4045, nsm, port 4046, rquotad, port 4049, krb524, port 4444, mdns, port 5353, https, port 5986, port 8443, ndmp, port 10000, cluster peering, port 11104, port 11105, ports 18600 through 18699, cifs witness, port 40001, tls, port 50000, port 65200 
summary: 预留端口，用于与特定服务进行 ONTAP 通信 
---
= 概述
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
为与特定服务进行 ONTAP 通信预留了许多已知端口。如果存储网络环境中的端口值与 ONTAP 端口上的端口值相同，则会发生端口冲突。

下表列出了 ONTAP 使用的 TCP 端口和 UDP 端口。

[cols="25,25,50"]
|===


| 服务 | 端口 / 协议 | Description 


| SSH | 22/TCP | 安全 Shell 登录 


| Telnet | 23TCP | 远程登录 


| DNS | 53/TCP | 负载平衡 DNS 


| HTTP | 80/TCP | 超文本传输协议 


| rpcbind | 111/TCP | 远程操作步骤调用 


| rpcbind | 111/UDP | 远程操作步骤调用 


| NTP | 123/UDP | 网络时间协议 


| MSRPC | 135/UDP | MSRPC 


| Netbios-SSN | 139/TCP | NetBIOS 服务会话 


| SNMP | 161/UDP | 简单网络管理协议 


| HTTPS | 443/TCP | 基于 TLS 的 HTTP 


| Microsoft DS | 445/TCP | Microsoft DS 


| 挂载 | 635/TCP | NFS 挂载 


| 挂载 | 635/UDP | NFS 挂载 


| 已命名 | 953/UDP | 名称守护进程 


| NFS | 2049 UDP | NFS 服务器守护进程 


| NFS | 2049/TCP | NFS 服务器守护进程 


| Nrv | 20205/TCP | NetApp 远程卷协议 


| iSCSI | 3260/TCP | iSCSI 目标端口 


| 锁定 | 4045/TCP | NFS 锁定守护进程 


| 锁定 | 4045/UDP | NFS 锁定守护进程 


| NSM | 4046/ TCP | 网络状态监控器 


| NSM | 4046/UDP | 网络状态监控器 


| rquotad | 4049/UDP | NFS Rquotad 协议 


| krb524 | 444/UDP | Kerberos 524 


| mDNS | 5533/UDP | 多播 DNS 


| HTTPS | 5986/UDP | HTTPS 端口—侦听二进制协议 


| HTTPS | 843/TCP | 通过 https 使用 7MTT GUI 工具 


| NDMP | 10000/TCP | 网络数据管理协议 


| 集群对等 | 11104/TCP | 集群对等 


| 集群对等 | 11105/TCP | 集群对等 


| NDMP | 18600 - 18699/TCP | NDMP 


| CIFS 见证端口 | 40001/TCP | CIFS 见证端口 


| TLS | 50000/TCP | 传输层安全性 


| iSCSI | 65200/TCP | iSCSI 端口 
|===