---
sidebar: sidebar 
permalink: networking/use_cdp_to_detect_network_connectivity.html 
keywords: display, view, show, network, connectivity, neighbor, discovery, protocol, cdp, use cdp to detect network connectivity, considerations for using cdp, enable or disable cdp, view cdp neighbor information, example of showing and clearing statistics, cisco 
summary: '在数据中心中，您可以使用邻居发现协议查看一对物理或虚拟系统及其网络接口之间的网络连接。ONTAP支持两种邻居发现协议：Cisco发现协议(CDP)和链路层发现协议(Link Layer Discovery Protocol、LDP)。' 
---
= 使用CDP检测ONTAP网络连接
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
使用 CDP 检测网络连接包括查看部署注意事项，在数据端口上启用它，查看相邻设备以及根据需要调整 CDP 配置值。默认情况下， CDP 在集群端口上处于启用状态。

还必须在任何交换机和路由器上启用 CDP ，才能显示有关相邻设备的信息。

[cols="30,70"]
|===


| ONTAP 版本 | Description 


 a| 
9.10.1及更早版本
 a| 
集群交换机运行状况监控器还使用 CDP 自动发现集群和管理网络交换机。



 a| 
9.11.1及更高版本
 a| 
集群交换机运行状况监控器还使用CDP自动发现集群、存储和管理网络交换机。

|===
.相关信息
link:../system-admin/index.html["系统管理"^]



== 使用 CDP 的注意事项

默认情况下， CDP 兼容设备会发送 CDPv2 公告。CDP 兼容设备仅在收到 CDPv1 公告时才会发送 CDPv1 公告。ONTAP 仅支持 CDPv1 。因此，当 ONTAP 节点发送 CDPv1 公告时， CDP 兼容的相邻设备会发回 CDPv1 公告。

在节点上启用 CDP 之前，应考虑以下信息：

* 所有端口均支持 CDP 。
* CDP 公告由处于 up 状态的端口发送和接收。
* 必须在传输和接收设备上启用 CDP ，才能发送和接收 CDP 公告。
* CDP 公告会定期发送，您可以配置时间间隔。
* 更改 LIF 的 IP 地址后，节点会在下一个 CDP 公告中发送更新后的信息。
* ONTAP 9.10.1及更早版本：
+
** CDP 始终在集群端口上启用。
** 默认情况下，所有非集群端口上都会禁用 CDP 。


* ONTAP 9.11.1及更高版本：
+
** CDP始终在集群和存储端口上启用。
** 默认情况下、所有非集群和非存储端口上都会禁用CDP。





NOTE: 有时，当节点上的 LIF 发生更改时， CDP 信息不会在接收设备端（例如交换机）进行更新。如果遇到此类问题，应将节点的网络接口配置为 down 状态，然后再配置为 up 状态。

* 只有 IPv4 地址才会在 CDP 公告中公布。
* 对于带有 VLAN 的物理网络端口，该端口上 VLAN 上配置的所有 LIF 都会公布。
* 对于属于接口组的物理端口，该接口组上配置的所有 IP 地址都会在每个物理端口上公布。
* 对于托管 VLAN 的接口组，接口组上配置的所有 LIF 和 VLAN 都会在每个网络端口上公布。
* 由于CDP数据包在端口上限制为不超过1500字节
配置了大量LIP地址、只能在相邻交换机上报告其中一部分IP地址。




== 启用或禁用 CDP

要发现并向 CDP 兼容的相邻设备发送公告，必须在集群的每个节点上启用 CDP 。

默认情况下、在ONTAP 9.10.1及更早版本中、CDP会在节点的所有集群端口上启用、并在节点的所有非集群端口上禁用。

默认情况下、在ONTAP 9.11.1及更高版本中、CDP会在节点的所有集群和存储端口上启用、并在节点的所有非集群和非存储端口上禁用。

.关于此任务
。 `cdpd.enable` 选项用于控制在节点的端口上启用还是禁用CDP：

* 对于ONTAP 9.10.1及更早版本、on会在非集群端口上启用CDP。
* 对于ONTAP 9.11.1及更高版本、on会在非集群和非存储端口上启用CDP。
* 对于ONTAP 9.10.1及更早版本、off会在非集群端口上禁用CDP；您不能在集群端口上禁用CDP。
* 对于ONTAP 9.11.1及更高版本、off会在非集群和非存储端口上禁用CDP；您不能在集群端口上禁用CDP。


如果在连接到 CDP 兼容设备的端口上禁用 CDP ，则网络流量可能无法优化。

.步骤
. 显示节点或集群中所有节点的当前 CDP 设置：
+
[cols="30,70"]
|===


| 要查看 CDP 设置 ... | 输入 ... 


 a| 
节点
 a| 
`run - node <node_name> options cdpd.enable`



 a| 
集群中的所有节点
 a| 
`options cdpd.enable`

|===
. 在节点的所有端口或集群中所有节点的所有端口上启用或禁用 CDP ：
+
[cols="30,70"]
|===


| 要启用或禁用 CDP ，请执行以下操作 ... | 输入 ... 


 a| 
节点
 a| 
`run -node node_name options cdpd.enable {on or off}`



 a| 
集群中的所有节点
 a| 
`options cdpd.enable {on or off}`

|===




== 查看 CDP 邻居信息

您可以查看有关连接到集群节点的每个端口的相邻设备的信息，前提是该端口连接到 CDP 兼容设备。您可以使用 `network device-discovery show -protocol cdp` 命令以查看邻居信息。

.关于此任务
在ONTAP 9.10.1及更早版本中、由于CDP始终为集群端口启用、因此始终会显示这些端口的CDP邻居信息。必须在非集群端口上启用 CDP ，才能显示这些端口的邻居信息。

在ONTAP 9.11.1及更高版本中、由于CDP始终为集群和存储端口启用、因此始终会显示这些端口的CDP邻居信息。必须在非集群和非存储端口上启用CDP、才能显示这些端口的邻居信息。

.步骤
显示有关连接到集群中节点上端口的所有 CDP 兼容设备的信息：

....
network device-discovery show -node node -protocol cdp
....
以下命令显示了连接到节点sti2650/212上端口的邻居：

....
network device-discovery show -node sti2650-212 -protocol cdp
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
sti2650-212/cdp
            e0M    RTP-LF810-510K37.gdl.eng.netapp.com(SAL1942R8JS)
                                             Ethernet1/14      N9K-C93120TX
            e0a    CS:RTP-CS01-510K35        0/8               CN1610
            e0b    CS:RTP-CS01-510K36        0/8               CN1610
            e0c    RTP-LF350-510K34.gdl.eng.netapp.com(FDO21521S76)
                                             Ethernet1/21      N9K-C93180YC-FX
            e0d    RTP-LF349-510K33.gdl.eng.netapp.com(FDO21521S4T)
                                             Ethernet1/22      N9K-C93180YC-FX
            e0e    RTP-LF349-510K33.gdl.eng.netapp.com(FDO21521S4T)
                                             Ethernet1/23      N9K-C93180YC-FX
            e0f    RTP-LF349-510K33.gdl.eng.netapp.com(FDO21521S4T)
                                             Ethernet1/24      N9K-C93180YC-FX
....
输出列出了连接到指定节点的每个端口的 Cisco 设备。



== 配置 CDP 消息的保持时间

保持时间是 CDP 公告存储在相邻 CDP 兼容设备的缓存中的时间段。保持时间在每个 CDPv1 数据包中公布，并且每当节点收到 CDPv1 数据包时都会更新。

* 的值 `cdpd.holdtime` 选项应在HA对的两个节点上设置为相同的值。
* 默认保持时间值为 180 秒，但您可以输入 10 秒到 255 秒之间的值。
* 如果在保持时间到期之前删除 IP 地址，则会缓存 CDP 信息，直到保持时间到期为止。


.步骤
. 显示节点或集群中所有节点的当前 CDP 保持时间：
+
[cols="30,70"]
|===


| 要查看保持时间 ... | 输入 ... 


 a| 
节点
 a| 
`run -node node_name options cdpd.holdtime`



 a| 
集群中的所有节点
 a| 
`options cdpd.holdtime`

|===
. 在节点的所有端口或集群中所有节点的所有端口上配置 CDP 保持时间：
+
[cols="30,70"]
|===


| 要设置保持时间 ... | 输入 ... 


 a| 
节点
 a| 
`run -node node_name options cdpd.holdtime holdtime`



 a| 
集群中的所有节点
 a| 
`options cdpd.holdtime holdtime`

|===




== 设置发送 CDP 公告的间隔

CDP 公告会定期发送到 CDP 邻居。您可以根据网络流量和网络拓扑变化增加或减少发送 CDP 公告的间隔。

* 的值 `cdpd.interval` 选项应在HA对的两个节点上设置为相同的值。
* 默认间隔为 60 秒，但您可以输入一个介于 5 秒到 900 秒之间的值。


.步骤
. 显示节点或集群中所有节点的当前 CDP 公告时间间隔：
+
[cols="30,70"]
|===


| 要查看间隔 ... | 输入 ... 


 a| 
节点
 a| 
`run -node node_name options cdpd.interval`



 a| 
集群中的所有节点
 a| 
`options cdpd.interval`

|===
. 配置为节点的所有端口或集群中所有节点的所有端口发送 CDP 公告的间隔：
+
[cols="30,70"]
|===


| 要设置间隔 ... | 输入 ... 


 a| 
节点
 a| 
`run -node node_name options cdpd.interval interval`



 a| 
集群中的所有节点
 a| 
`options cdpd.interval interval`

|===




== 查看或清除 CDP 统计信息

您可以查看每个节点上的集群和非集群端口的 CDP 统计信息，以检测潜在的网络连接问题。CDP 统计信息是自上次清除以来累积的。

.关于此任务
在ONTAP 9.10.1及更早版本中、由于CDP始终为端口启用、因此始终会显示这些端口上的流量的CDP统计信息。必须在端口上启用CDP、才能显示这些端口的统计信息。

在ONTAP 9.11.1及更高版本中、由于CDP始终为集群和存储端口启用、因此始终为这些端口上的流量显示CDP统计信息。必须在非集群或非存储端口上启用CDP、才能显示这些端口的统计信息。

.步骤
显示或清除节点上所有端口的当前 CDP 统计信息：

[cols="30,70"]
|===


| 如果您要 ... | 输入 ... 


 a| 
查看 CDP 统计信息
 a| 
`run -node node_name cdpd show-stats`



 a| 
清除 CDP 统计信息
 a| 
`run -node node_name cdpd zero-stats`

|===


=== 显示和清除统计信息的示例

以下命令显示清除之前的 CDP 统计信息。输出将显示自上次清除统计信息以来已发送和接收的数据包总数。

....
run -node node1 cdpd show-stats

RECEIVE
 Packets:         9116  | Csum Errors:       0  | Unsupported Vers:  4561
 Invalid length:     0  | Malformed:         0  | Mem alloc fails:      0
 Missing TLVs:       0  | Cache overflow:    0  | Other errors:         0

TRANSMIT
 Packets:         4557  | Xmit fails:        0  | No hostname:          0
 Packet truncated:   0  | Mem alloc fails:   0  | Other errors:         0

OTHER
 Init failures:      0
....
以下命令将清除 CDP 统计信息：

....
run -node node1 cdpd zero-stats
....
....
run -node node1 cdpd show-stats

RECEIVE
 Packets:            0  | Csum Errors:       0  | Unsupported Vers:     0
 Invalid length:     0  | Malformed:         0  | Mem alloc fails:      0
 Missing TLVs:       0  | Cache overflow:    0  | Other errors:         0

TRANSMIT
 Packets:            0  | Xmit fails:        0  | No hostname:          0
 Packet truncated:   0  | Mem alloc fails:   0  | Other errors:         0

OTHER
 Init failures:      0
....
清除统计信息后，在发送或接收下一个 CDP 公告后，这些统计信息将开始累积。



== 连接到不支持CDP的以太网交换机

多个供应商交换机不支持CDP。  请参见知识库文章 https://kb.netapp.com/onprem/ontap/da/NAS/ONTAP_device_discovery_shows_nodes_instead_of_the_switch["ONTAP设备发现显示的是节点、而不是交换机"^] 了解更多详细信息。

可通过两种方法解决此问题描述：

* 禁用CDP并启用CDP (如果支持)。请参见 link:use_lldp_to_detect_network_connectivity.html["使用LDP检测网络连接"] 了解更多详细信息。
* 在交换机上配置MAC地址数据包筛选器以丢弃CDP公告。

