---
sidebar: sidebar 
permalink: multi-admin-verify/manage-requests-task.html 
keywords: ontap, mav, multi, admin, multi admin verify, verification, administrator, protected, operation, rules, request, cluster, approve, rbac, manage, cli, system, manager 
summary: 当 MAV 审批组中的管理员收到待处理操作请求的通知时，他们必须在规定时间内做出批准或否决的回应。 
---
= 在ONTAP中管理受MAV保护的操作请求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
当 MAV 审批组中的管理员（MAV 管理员）收到待处理的操作执行请求通知时，他们必须在固定时间内（审批到期）回复批准或否决消息。如果没有收到足够数量的批准，请求者必须删除该请求并提出另一个请求。

.关于此任务
批准请求使用索引编号进行标识、索引编号包含在电子邮件消息和请求队列的显示中。


NOTE: `multi-admin-verify`处于终端状态的请求可能会被自动覆盖或删除。使用link:../system-admin/audit-display-log-contents-task.html["审核日志"]审查先前的请求。

可以显示请求队列中的以下信息：

操作:: 创建请求的受保护操作。
查询:: 用户要应用操作的一个或多个对象。
State:: 请求的当前状态；待定、已批准、已拒绝、已过期、 已执行。如果一个审批者拒绝了某个请求、则无法执行其他操作。
所需审批者:: 批准请求所需的MAV管理员数量。用户可以为此操作规则设置requireed-approvers参数。如果用户未将所需审批者设置为规则、则会应用全局设置中的所需审批者。
待定审批者:: 仍然需要批准请求以将此请求标记为已批准的MAV管理员数量。
批准到期:: MAV管理员必须对批准请求做出响应的期限。任何授权用户都可以为操作规则设置批准到期时间。如果未为此规则设置Approval expiry、则会应用全局设置中的Approval expiry。
执行到期:: 发出请求的管理员必须完成操作的期限。任何授权用户都可以为操作规则设置执行到期时间。如果未为此规则设置execing-expiry、则会应用全局设置中的execing-expiry。
已批准用户:: 批准此请求的MAV管理员。
已否决用户:: 已否决此请求的MAV管理员。
Storage VM (SVM):: 与请求关联的SVM。此版本仅支持管理SVM。
用户已请求:: 创建请求的用户的用户名。
创建时间:: 创建请求的时间。
批准时间:: 请求状态更改为"已批准"的时间。
comment:: 与请求关联的任何注释。
允许的用户:: 允许执行请求获得批准的受保护操作的用户列表。条件 `users-permitted` 为空、则具有适当权限的任何用户均可执行此操作。


[role="tabbed-block"]
====
.System Manager
--
MAV 管理员会收到电子邮件，其中包含批准请求的详细信息、请求到期期限以及批准或拒绝请求的链接。他们可以通过单击电子邮件中的链接访问批准对话框，或导航至系统管理器中的*事件和作业>请求*。

当启用多管理员验证时，*请求*窗口可用，根据用户的登录 ID 和 MAV 角色（是否为批准者）显示待处理的请求。

* 操作
* 索引(编号)
* 状态(待定、已批准、已拒绝、已执行或已过期)
+
如果一个审批者拒绝了某个请求、则无法执行其他操作。

* 查询(请求操作的任何参数或值)
* 正在请求用户
* 请求将于到期
* (数量)待定审批者
* (数量)潜在审批者


MAV管理员在此窗口中具有其他控件；他们可以批准、拒绝或删除单个操作或选定的操作组。但是、如果MAV管理员是发出请求的用户、他们将无法批准、拒绝或删除自己的请求。

--
.命令行界面
--
. 当通过电子邮件收到待处理请求的通知时，请记下请求的索引号和批准有效期。索引号也可以使用下面提到的 *show* 或 *show-pending* 选项显示。
. 批准或否决此请求。
+
[cols="50,50"]
|===
| 如果要… | 输入此命令 


 a| 
批准请求
 a| 
`security multi-admin-verify request approve _nn_`



 a| 
否决请求
 a| 
`security multi-admin-verify request veto _nn_`



 a| 
显示所有请求、待处理请求或单个请求
 a| 
`security multi-admin-verify request { show | show-pending } [_nn_]
{ -fields _field1_[,_field2_...] |  [-instance ]  }`

您可以显示队列中的所有请求、也可以仅显示待处理的请求。如果输入索引编号、则仅显示该索引编号的信息。您可以显示有关特定字段的信息(使用 `-fields` 参数)或关于所有字段(使用 `-instance` 参数)。



 a| 
删除请求
 a| 
`security multi-admin-verify request delete _nn_`

|===


.示例
在MAV管理员收到索引编号为3的请求电子邮件后、以下顺序将批准请求、该电子邮件已获得一项批准。

[listing]
----
          cluster1::> security multi-admin-verify request show-pending
                                   Pending
Index Operation      Query State   Approvers Requestor
----- -------------- ----- ------- --------- ---------
    3 volume delete  -     pending 1         julia


cluster-1::> security multi-admin-verify request approve 3

cluster-1::> security multi-admin-verify request show 3

     Request Index: 3
         Operation: volume delete
             Query: -
             State: approved
Required Approvers: 2
 Pending Approvers: 0
   Approval Expiry: 2/25/2022 14:32:03
  Execution Expiry: 2/25/2022 14:35:36
         Approvals: mav-admin2
       User Vetoed: -
           Vserver: cluster-1
    User Requested: julia
      Time Created: 2/25/2022 13:32:03
     Time Approved: 2/25/2022 13:35:36
           Comment: -
   Users Permitted: -
----
.示例
在MAV管理员收到索引编号为3的请求电子邮件后、以下顺序将否决此请求、此电子邮件已获得一项批准。

[listing]
----
      cluster1::> security multi-admin-verify request show-pending
                                   Pending
Index Operation      Query State   Approvers Requestor
----- -------------- ----- ------- --------- ---------
    3 volume delete  -     pending 1         pavan


cluster-1::> security multi-admin-verify request veto 3

cluster-1::> security multi-admin-verify request show 3

     Request Index: 3
         Operation: volume delete
             Query: -
             State: vetoed
Required Approvers: 2
 Pending Approvers: 0
   Approval Expiry: 2/25/2022 14:32:03
  Execution Expiry: 2/25/2022 14:35:36
         Approvals: mav-admin1
       User Vetoed: mav-admin2
           Vserver: cluster-1
    User Requested: pavan
      Time Created: 2/25/2022 13:32:03
     Time Approved: 2/25/2022 13:35:36
           Comment: -
   Users Permitted: -
----
--
====
.相关信息
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+multi-admin-verify["安全多管理员验证"^]

