---
permalink: concepts/builtin-storage-efficiency-concept.html 
sidebar: sidebar 
keywords: storage efficiency, built-in, platform, controller, offload, aff a1k, aff a90, aff a70, fas90, fas70, aff a50, aff a30 
summary: 某些 AFF 和 FAS 系统支持专用卸载处理器存储效率。这些系统不使用对温度敏感的存储效率。压缩无需等待数据变冷即可开始，并使用专用卸载处理器执行。 
---
= 了解ONTAP专用卸载处理器的存储效率
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
专用卸载处理器存储效率对连续物理块进行顺序打包，并使用专用卸载处理器进行 32k 数据压缩。通过 32k 压缩，空间节省是在聚合层实现的，这与使用 8k 自适应压缩的系统不同，后者的空间节省是在卷层实现的。使用专用卸载处理器存储效率的系统不使用温度敏感型存储效率 (TSSE)，这意味着压缩不基于热数据或冷数据。从而可以立即节省空间，且不会对性能产生任何影响。

以下系统支持专用卸载处理器存储效率。默认情况下，它在列出的 AFF 系统上处于启用状态。


NOTE: AFF A20 平台不支持专用卸载处理器存储效率。对于 AFF A20 系统，使用 SnapMirror 技术迁移的数据将使用主 CPU 自动转换为 32k 内联压缩。

* AFF A 系列系统：AFF A90、AFF A70、AFF A50、AFF A30
* AFF A1K
* AFF C 系列系统：AFF C80、AFF C60、AFF C30
* FAS 系统：FAS90、FAS70、FAS50


对于以下系统，存储效率会自动启用，无需配置。这适用于所有新创建的精简配置卷和现有数据，包括从其他系统移动的卷。无论空间保证设置如何，都会启用重复数据删除。压缩和数据压缩都要求将空间保证设置为无。使用卷移动或 SnapMirror 技术迁移的数据会自动转换为 32k 内联压缩。

* AFF A 系列系统：AFF A90、AFF A70、AFF A50、AFF A30
* AFF A1K
* AFF C 系列系统：AFF C80、AFF C60、AFF C30


对于以下系统，默认情况下，存储效率仅在升级到 ONTAP 9.15.1 或更高版本之前已启用存储效率的现有精简配置卷上启用。您可以使用 ONTAP CLI 或 ONTAP REST API 方法在新创建的卷上启用存储效率。只有在原始平台上启用了压缩的情况下，使用卷移动或 SnapMirror 技术迁移的数据才会转换为 32k 内联压缩。

* FAS90
* FAS70
* FAS50


有关将控制器升级到受支持系统之一的信息，请参见 https://docs.netapp.com/us-en/ontap-systems-upgrade/choose_controller_upgrade_procedure.html["ONTAP硬件升级文档"^]。
