---
permalink: concepts/cloud-backup-support-traditional-backups-concept.html 
sidebar: sidebar 
keywords: cloud backup, support, traditional backups 
summary: 除了先前仅使用磁盘到磁盘的 SnapMirror 和 SnapVault 数据保护关系之外，现在还有几种备份解决方案可以为长期数据保留提供一种成本更低的替代方案。 
---
= 云备份以及对传统备份的支持
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
除了先前仅使用磁盘到磁盘的 SnapMirror 和 SnapVault 数据保护关系之外，现在还有几种备份解决方案可以为长期数据保留提供一种成本更低的替代方案。

许多第三方数据保护应用程序为 ONTAP 管理的数据提供传统备份。Veeam ， Veritas 和 Commvault 等均可为 ONTAP 系统提供集成备份。

从 ONTAP 9.8 开始， SnapMirror Cloud 可将 Snapshot 副本从 ONTAP 实例异步复制到对象存储端点。SnapMirror 云复制要求使用许可的应用程序来协调和管理数据保护工作流。ONTAP 系统支持通过 SnapMirror 云关系来选择内部部署和公有云对象存储目标，包括 AWS S3 ， Google 云存储平台或 Microsoft Azure Blob 存储，从而通过供应商备份软件提高效率。有关受支持的认证应用程序和对象存储供应商列表，请联系您的 NetApp 代表。

如果您对云原生数据保护感兴趣，可以使用 Cloud Manager 在内部卷和公有云中的 Cloud Volumes ONTAP 实例之间配置 SnapMirror 或 SnapVault 关系。

此外， Cloud Manager 还可以使用软件即服务（ SaaS ）模式备份 Cloud Volumes ONTAP 实例。用户可以使用 NetApp Cloud Central 上的 Cloud Backup 将其 Cloud Volumes ONTAP 实例备份到 S3 和 S3 兼容的公有云对象存储。

https://www.netapp.com/cloud-services/cloud-manager/documentation/["Cloud Volumes ONTAP 和 Cloud Manager 文档资源"]

https://cloud.netapp.com["NetApp Cloud Central"]
