---
permalink: concepts/insights-system-optimization-concept.html 
sidebar: sidebar 
keywords: system manager, optimize, optimise, optimization, optimisation, insight, cluster, system, analysis, analyze, perform, performing, performance, capacity, local tier, storage tier, telnet, remote shell, rsh, autosupport, auto support, auto-support, insecure protocol, login banner, log in banner, ssh, secure shell, cbc cipher, ntp server, admin user, administrative, user, best practice, practise, fabricpool, fabric pool, physical capacity, aggregate, cloud, snapshot, directories, directory, file, remote access, transport protocol, https, http, autogrow, auto grow, auto-grow, shrink, reduce, reduction, dismiss, undismiss, explore, fix, remove, replace, analytic, security, compliance, secure, comply, volume, applications, reclaim, space, full, provisioning, provisioned cluster, serial, port, node 
summary: 借助System Manager、您可以查看有助于优化系统性能和安全性的见解。 
---
= System Manager洞察力
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
从ONTAP 9.11.1开始、System Manager将显示_洞察力_、帮助您优化系统的性能和安全性。


NOTE: 要查看、自定义和响应洞察力、请参见 link:../insights-system-optimization-task.html["获得洞察力，帮助优化您的系统"]



== 容量洞察力

System Manager可以根据系统中的容量状况显示以下见解：

[cols="15,15,20,50"]
|===


| 洞察力 | severity | 条件 | 修复 


 a| 
本地层即将用尽物理容量
 a| 
修复风险
 a| 
一个或多个本地层已达到95%以上、并且增长迅速。
 a| 
*建议修复*：执行其他选项之一。

*其他选项*：

* 清除卷恢复队列。
* 在厚配置卷上启用精简配置、以释放陷阱存储。
* 将卷移动到另一本地层。
* 删除不需要的Snapshot副本。
* 删除卷中不需要的目录或文件。
* 启用Fabric Pool以将数据分层到云。




 a| 
FlexGroup卷的容量不平衡
 a| 
优化存储
 a| 
一个或多个FlexGroup卷的不平衡率较高。
 a| 
*建议*：重新平衡FlexGroup卷。



 a| 
应用程序即将用尽空间
 a| 
需要关注
 a| 
已满超过95%的卷未启用自动增长。
 a| 
*建议*：启用自动增长、最多可达到当前容量的150%。

*其他选项*：

* 通过删除Snapshot副本回收空间。
* 调整卷大小。
* 删除目录或文件。


|===


== 安全洞察

System Manager可显示以下见解、以应对可能危及数据或系统安全的情况。

[cols="15,15,20,50"]
|===


| 洞察力 | severity | 条件 | 修复 


 a| 
已启用Telnet
 a| 
最佳实践
 a| 
应使用安全Shell (SSH)进行安全远程访问。
 a| 
*建议*：禁用Telnet并使用SSH进行安全远程访问。



 a| 
配置的NTP服务器太少
 a| 
最佳实践
 a| 
为NTP配置的服务器数量小于3。
 a| 
*建议*：添加NTP服务器、使其至少为3个。



 a| 
AutoSupport正在使用不安全协议
 a| 
最佳实践
 a| 
AutoSupport未配置为通过HTTPS进行通信。
 a| 
*建议*：将传输协议更改为HTTPS。



 a| 
默认管理员用户未锁定
 a| 
最佳实践
 a| 
没有人使用默认管理帐户(admin或diag)登录、这些帐户不会锁定。
 a| 
*建议*：在不使用默认管理帐户时将其锁定。



 a| 
卷没有Snapshot策略
 a| 
需要关注
 a| 
一个或多个卷未附加足够的Snapshot策略。
 a| 
*建议*：将Snapshot策略附加到没有此策略的卷。否则、在发生勒索软件攻击时、可能无法恢复这些卷的数据。



 a| 
已启用Snapshot自动删除
 a| 
需要关注
 a| 
为一个或多个卷启用了Snapshot副本自动删除。
 a| 
*建议*：禁用Snapshot副本自动删除功能。否则、在发生勒索软件攻击时、可能无法恢复这些卷的数据。



 a| 
不会监控卷的勒索软件攻击
 a| 
需要关注
 a| 
多个卷支持反勒索软件、但尚未对其进行配置。否则、您可能无法注意到卷何时受到威胁或攻击。
 a| 
*建议*：在卷上启用反勒索软件。



 a| 
没有为Storage VM配置反勒索软件
 a| 
最佳实践
 a| 
多个Storage VM支持反勒索软件、但尚未对其进行配置。
 a| 
*建议*：在Storage VM上启用反勒索软件。否则、您可能无法注意到Storage VM何时受到威胁或攻击。



 a| 
未配置本机FPolicy
 a| 
最佳实践
 a| 
未为NAS Storage VM设置FPolicy。
 a| 
*建议*：在NAS Storage VM中配置FPolicy、以控制允许或不允许在集群中的卷上写入的文件扩展名。



 a| 
未为防反防兰索程序启用活动模式
 a| 
需要关注
 a| 
多个卷已完成其学习模式、但活动模式尚未打开。
 a| 
*建议*：为这些卷打开活动模式。



 a| 
未配置登录横幅
 a| 
最佳实践
 a| 
没有为此集群或Storage VM配置登录消息。
 a| 
*建议*：设置集群或Storage VM的登录横幅并启用其使用。



 a| 
已启用远程Shell (RSH)
 a| 
最佳实践
 a| 
应使用安全Shell (SSH)进行安全远程访问。
 a| 
*建议*：禁用RSH并使用SSH进行安全远程访问。



 a| 
安全Shell (SSH)正在使用不安全的加密方法
 a| 
最佳实践
 a| 
当前配置使用不安全的CBC密例。
 a| 
*建议*：删除名称包含"CBC"的加密、例如"ais128-CBC"、"Aes192-CBC"、"AES256-CBC"和"3DES-CBC"。



 a| 
已禁用全局FIPS
 a| 
最佳实践
 a| 
已禁用全局FIPS 140-2合规性。
 a| 
*建议*：启用全局FIPS 140-2合规性。

|===


== 配置洞察

System Manager可以显示以下见解、以解决有关系统配置的问题。

[cols="15,15,20,50"]
|===


| 洞察力 | severity | 条件 | 修复 


 a| 
未启用自动更新。
 a| 
最佳实践
 a| 
尚未接受此集群的EULA。
 a| 
*建议*：接受集群的EULA。



 a| 
有最新的固件更新可用
 a| 
最佳实践
 a| 
您的系统没有最新的固件更新、此更新可能会提供一些改进、安全修补程序或新功能、以帮助保护集群、从而提高性能。
 a| 
*建议*：更新ONTAP固件。



 a| 
未配置通知
 a| 
最佳实践
 a| 
未将电子邮件、webhook或SNMP陷阱主机配置为接收有关集群问题的通知。
 a| 
*建议*：为集群配置通知。

|===