---
permalink: concepts/insights-system-optimization-concept.html 
sidebar: sidebar 
keywords: system manager, optimize, optimise, optimization, optimisation, insight, cluster, system, analysis, analyze, perform, performing, performance, capacity, local tier, storage tier, telnet, remote shell, rsh, autosupport, auto support, auto-support, insecure protocol, nonsecure, login banner, log in banner, ssh, secure shell, cbc cipher, ntp server, admin user, administrative, user, best practice, practise, fabricpool, fabric pool, physical capacity, aggregate, cloud, snapshot, directories, directory, file, remote access, transport protocol, https, http, autogrow, auto grow, auto-grow, shrink, reduce, reduction, dismiss, undismiss, explore, fix, remove, replace, analytic, security, compliance, secure, comply, volume, applications, reclaim, space, full, provisioning, provisioned cluster, serial, port, node, global fips 140-2 
summary: 从ONTAP 9.11.1开始、System Manager可提供有助于优化系统性能和安全性的洞察力。 
---
= System Manager洞察力
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
从ONTAP 9.11.1开始、System Manager将显示_洞察力_、帮助您优化系统的性能和安全性。


NOTE: 要查看、自定义和响应洞察力、请参见 link:../insights-system-optimization-task.html["获得洞察力，帮助优化您的系统"]



== 容量洞察力

System Manager可以根据系统中的容量状况显示以下见解：

[cols="15,15,20,50"]
|===


| 洞察力 | severity | 条件 | 修复 


 a| 
本地层缺少空间
 a| 
修复风险
 a| 
一个或多个本地层已达到95%以上、并且增长迅速。现有工作负载可能无法增长、或者在极端情况下、现有工作负载可能会用尽空间并发生故障。
 a| 
*建议修复*：执行以下选项之一。

* 清除卷恢复队列。
* 在厚配置卷上启用精简配置、以释放陷阱存储。
* 将卷移动到另一本地层。
* 删除不需要的Snapshot副本。
* 删除卷中不需要的目录或文件。
* 启用Fabric Pool以将数据分层到云。




 a| 
应用程序缺少空间
 a| 
需要关注
 a| 
一个或多个卷的容量已超过95%、但未启用自动增长。
 a| 
*建议*：启用自动增长、最多可达到当前容量的150%。

*其他选项*：

* 通过删除Snapshot副本回收空间。
* 调整卷大小。
* 删除目录或文件。




 a| 
FlexGroup卷的容量不平衡
 a| 
优化存储
 a| 
一个或多个FlexGroup卷的成分卷大小随着时间的推移增长不平衡、从而导致容量使用不平衡。  如果成分卷已满、则可能会发生写入失败。
 a| 
*建议*：重新平衡FlexGroup卷。



 a| 
Storage VM即将用尽容量
 a| 
优化存储
 a| 
一个或多个Storage VM接近其最大容量。  如果Storage VM达到最大容量、您将无法为新卷或现有卷配置更多空间。
 a| 
*建议*：如果可能、增加Storage VM的最大容量限制。

|===


== 安全洞察

System Manager可显示以下见解、以应对可能危及数据或系统安全的情况。

[cols="15,15,20,50"]
|===


| 洞察力 | severity | 条件 | 修复 


 a| 
卷仍处于反勒索软件学习模式
 a| 
需要关注
 a| 
一个或多个卷已处于反勒索软件学习模式90天。
 a| 
*建议*：为这些卷启用反勒索软件活动模式。



 a| 
已在卷上启用Snapshot副本自动删除
 a| 
需要关注
 a| 
已在一个或多个卷上启用Snapshot自动删除。
 a| 
*建议*：禁用Snapshot副本自动删除功能。否则、在发生勒索软件攻击时、可能无法恢复这些卷的数据。



 a| 
卷没有Snapshot策略
 a| 
需要关注
 a| 
一个或多个卷未附加足够的Snapshot策略。
 a| 
*建议*：将Snapshot策略附加到没有此策略的卷。否则、在发生勒索软件攻击时、可能无法恢复这些卷的数据。



 a| 
未配置本机FPolicy
 a| 
最佳实践
 a| 
未在一个或多个NAS Storage VM上配置FPolicy。
 a| 
*建议*：在NAS Storage VM中配置FPolicy、以控制允许或不允许在集群中的卷上写入的文件扩展名。这有助于防止使用已知文件扩展名的勒索软件攻击。



 a| 
已启用Telnet
 a| 
最佳实践
 a| 
应使用安全Shell (SSH)进行安全远程访问。
 a| 
*建议*：禁用Telnet并使用SSH进行安全远程访问。



 a| 
配置的NTP服务器太少
 a| 
最佳实践
 a| 
为NTP配置的服务器数量小于3。
 a| 
*建议*：至少将三个NTP服务器与集群相关联。  否则、集群时间同步可能会出现问题。



 a| 
已启用远程Shell (RSH)
 a| 
最佳实践
 a| 
应使用安全Shell (SSH)进行安全远程访问。
 a| 
*建议*：禁用RSH并使用SSH进行安全远程访问。



 a| 
未配置登录横幅
 a| 
最佳实践
 a| 
没有为集群和/或Storage VM配置登录消息。
 a| 
*建议*：设置集群和Storage VM的登录横幅并启用其使用。



 a| 
AutoSupport正在使用非安全协议
 a| 
最佳实践
 a| 
AutoSupport未配置为通过HTTPS进行通信。
 a| 
*建议*：强烈建议使用HTTPS作为默认传输协议、以便向技术支持发送AutoSupport消息。



 a| 
默认管理员用户未锁定
 a| 
最佳实践
 a| 
没有人使用默认管理帐户(admin或diag)登录、这些帐户不会锁定。
 a| 
*建议*：在不使用默认管理帐户时将其锁定。



 a| 
安全Shell (SSH)正在使用非安全加密
 a| 
最佳实践
 a| 
当前配置使用非安全CBC加密。
 a| 
*建议*：您应在Web服务器上仅允许使用安全加密来保护与访问者的安全通信。删除名称包含"CBC"的加密、例如"ais128-CBC"、"aes192-CBC"、"AES256-CBC"和"3DES-CBC"。



 a| 
已禁用全局FIPS 140-2合规性
 a| 
最佳实践
 a| 
已在集群上禁用全局FIPS 140-2合规性。
 a| 
*建议*：出于安全原因、您应启用符合FIPS 140-2的全局加密法、以确保ONTAP可以安全地与外部客户端或服务器客户端进行通信。



 a| 
不会监控卷的勒索软件攻击
 a| 
需要关注
 a| 
已在一个或多个卷上禁用反勒索软件。
 a| 
*建议*：在卷上启用反勒索软件。否则、您可能无法注意到卷何时受到威胁或攻击。



 a| 
没有为Storage VM配置反勒索软件
 a| 
最佳实践
 a| 
一个或多个Storage VM未配置反勒索软件保护。
 a| 
*建议*：在Storage VM上启用反勒索软件。否则、您可能无法注意到Storage VM何时受到威胁或攻击。

|===


== 配置洞察

System Manager可以显示以下见解、以解决有关系统配置的问题。

[cols="15,15,20,50"]
|===


| 洞察力 | severity | 条件 | 修复 


 a| 
没有为集群配置通知
 a| 
最佳实践
 a| 
未将电子邮件、webhook或SNMP陷阱主机配置为接收有关集群问题的通知。
 a| 
*建议*：为集群配置通知。



 a| 
集群未配置自动更新。
 a| 
最佳实践
 a| 
集群尚未配置为接收最新磁盘认证包、磁盘固件、磁盘架固件和SP/BMC固件文件(如果有)的自动更新。
 a| 
*建议*：启用此功能。



 a| 
集群固件不是最新版本
 a| 
最佳实践
 a| 
您的系统没有最新的固件更新、此更新可能会提供一些改进、安全修补程序或新功能、以帮助保护集群、从而提高性能。
 a| 
*建议*：更新ONTAP固件。

|===