---
permalink: concepts/storage-efficiency-overview.html 
sidebar: sidebar 
keywords: storage efficiency, storage efficiencies, storage efficiency technologies, space utilization, space savings, optimizing, space optimization, minimizing, wasted space, reducing, footprint, thin provisioning, deduplication, zero block, zero-block, inline, deduplication, background deduplication, postprocessing, post-processing, compression, compaction, flex-clone technologies 
summary: 存储效率衡量存储系统如何通过优化存储资源、最大限度地减少空间浪费以及减少写入数据的物理占用空间来有效利用可用空间。 
---
= ONTAP存储效率概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
存储效率衡量存储系统如何通过优化存储资源、最大限度地减少空间浪费以及减少写入数据的物理占用空间来有效利用可用空间。通过提高存储效率、您可以以尽可能低的成本在尽可能小的空间中存储最大数量的数据。例如、利用可检测和消除重复数据块和填充为零的数据块的高效存储技术、可以减少所需的总物理存储量并降低总成本。

ONTAP提供了广泛的存储效率技术、可减少数据占用的物理硬件或云存储量、并显著提高系统性能、包括加快数据读取速度、加快数据集副本速度以及加快VM配置速度。

.ONTAP存储效率技术包括：
* * 精简配置 *
+
xref:thin-provisioning-concept.html[精简配置] 用于根据需要在卷或LUN中分配存储、而不是预先预留存储。  这样、您可以根据潜在使用情况过度分配卷或LUN、而无需预留当前未使用的空间、从而减少所需的物理存储量。

* * 重复数据删除 *
+
xref:deduplication-concept.html[重复数据删除] 可通过三种不同的方式减少卷所需的物理存储量。

+
** *零块重复数据删除*
+
零块重复数据删除可检测并消除全零数据块、并且仅更新元数据。然后、零块通常使用的空间将节省100%。  默认情况下、所有经过重复数据删除的卷都会启用零块重复数据删除。

** *实时重复数据删除*
+
实时重复数据删除会检测重复的数据块、并在将数据写入磁盘之前将其替换为对唯一共享块的引用。实时重复数据删除可将VM配置速度加快20%到30%。  实时重复数据删除可在卷或聚合级别使用、具体取决于您的ONTAP版本和平台。  默认情况下、AFF和ASA系统会启用此功能。您需要在FAS系统上手动启用实时重复数据删除。

** *后台重复数据删除*
+
后台重复数据删除还会检测重复的数据块、并将其替换为对唯一共享块的引用、但在将数据写入磁盘后会进一步提高存储效率。  您可以将后台重复数据删除设置为在存储系统满足特定条件时运行。例如、您可以在卷利用率达到10%时启用后台重复数据删除。  您也可以手动触发后台重复数据删除、或者将其设置为按特定计划运行。默认情况下、AFF和ASA系统会启用此功能。您需要在FAS系统上手动启用后台重复数据删除。



+
重复数据删除在卷内部以及聚合内的卷之间均受支持。  读取经过重复数据删除的数据通常不会对性能产生任何影响。

* * 数据压缩 *
+
xref:compression-concept.html[压缩] 通过将数据块合并到数据压缩组中(每个数据块存储为一个块)、减少卷所需的物理存储量。收到读取或覆盖请求时、只会读取一小组块、而不会读取整个文件。此过程可优化读取和覆盖性能、并提高所压缩文件大小的可扩展性。

+
数据压缩可以实时运行、也可以后处理运行。实时数据压缩可在将数据写入磁盘之前压缩内存中的数据、从而立即节省空间。后处理压缩首先将块以未压缩格式写入磁盘、然后按计划压缩数据。默认情况下、AFA系统会启用此功能。您需要在所有其他系统上手动启用数据压缩。

* *压缩*
+
数据缩减可通过采集存储在4 KB块中但大小小于4 KB的数据块并将其合并为一个块来减少卷所需的物理存储量。数据缩减是在数据仍位于内存中时进行的、因此磁盘上不会占用不必要的空间。  默认情况下、AFF和ASA系统会启用此功能。您需要手动在FAS系统上启用数据缩减。

* *FlexClone卷、文件和LUN*
+
xref:flexclone-volumes-files-luns-concept.html[FlexClone技术]利用Snapshot元数据为卷、文件或LUN创建可写时间点副本。副本与其父副本共享数据块、在将更改写入副本或其父副本之前、除了元数据所需的存储外、不会占用任何存储。写入更改时、仅存储增量。

+
传统的数据集副本可能需要几分钟甚至几小时才能创建、而FlexClone技术甚至可以让您近乎瞬时地复制最大的数据集。

* *对温度敏感的存储效率*
+
ONTAP可以通过评估卷数据的访问频率并将该频率映射到应用于该数据的压缩程度来提供 link:../volumes/enable-temperature-sensitive-efficiency-concept.html["对温度敏感的存储效率"] 优势。对于不常访问的冷数据、将压缩较大的数据块。对于访问频率较高且覆盖频率较高的热数据、较小的数据块会进行压缩、从而提高处理效率。

+
ONTAP 9.8中推出的温度敏感型存储效率(TSSE)会在新创建的精简配置AFF卷上自动启用。在ONTAP 9.15.1中推出的使用硬件卸载处理器的上未启用此link:builtin-storage-efficiency-concept.html["AFF A70、AFF A90和AFF A1K平台"]功能。

* *CPU或专用卸载处理器存储效率*
+
从ONTAP 9.15.1 开始，link:builtin-storage-efficiency-concept.html["CPU或专用卸载处理器存储效率"]在某些AFF和FAS平台上自动启用，无需配置。这些平台不使用对温度敏感的存储效率。压缩无需等待数据冷却即可开始，并使用主 CPU 或专用卸载处理器执行。这些平台还使用连续物理块的顺序打包来进一步提高压缩数据的存储效率。



您可以轻松地在日常运营中实现这些技术的优势。  例如、假设您需要为5、000个用户提供主目录存储、并且您估计任何用户所需的最大空间为1 GB。您可以提前预留一个5 TB的聚合、以满足总的潜在存储需求。  但是、您也知道、您的组织中的主目录容量要求差别很大。  您可以创建2 TB聚合、而不是为组织预留5 TB的总空间。  然后、您可以使用精简配置为每个用户分配1 GB的存储、但仅在需要时分配存储。  您可以随时主动监控聚合、并根据需要增加实际物理大小。

在另一个示例中、假设您使用的虚拟桌面基础架构(Virtual Desktop Infrastructure、VDI)在虚拟桌面之间存在大量重复数据。重复数据删除可自动删除VDI中重复的信息块、并将其替换为指向原始块的指针、从而降低存储使用量。数据压缩等其他ONTAP存储效率技术也可以在后台运行、而无需您干预。

ONTAP磁盘分区技术还可以提高存储效率。  RAID DP技术可防止出现双磁盘故障、而不会影响性能或增加磁盘镜像开销。ONTAP 9的高级SSD分区功能可将可用容量提高近20%。

NetApp提供与云中的内部ONTAP相同的存储效率功能。将数据从内部ONTAP迁移到云时、现有的存储效率将得以保留。例如、假设您有一个SQL数据库、其中包含要从内部系统迁移到云的业务关键型数据。您可以在BlueXP  中使用数据复制来迁移数据、并且在迁移过程中、您可以为云中的快照启用最新的内部策略。
