---
sidebar: sidebar 
permalink: concepts/sysmgr-integration-bluexp-concept.html 
keywords: netapp, ontap, system manager, experience, integrate, integration, bluexp, hybrid, cloud, dashboard, multicloud 
summary: 您可以使用 BlueXP 中的 System Manager 管理 ONTAP 9.10.1 及更高版本。这种集成让您可以使用统一的控制平面高效地监管混合多云基础架构，同时保留熟悉的 System Manager 用户界面。 
---
= 将 ONTAP 系统管理器与 BlueXP 集成
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以使用 BlueXP 中的 System Manager 管理 ONTAP 9.10.1 及更高版本。这种集成让您可以使用统一的控制平面高效地监管混合多云基础架构，同时保留熟悉的 System Manager 用户界面。

BlueXP 使您能够创建和管理云存储（例如，Cloud Volumes ONTAP）、使用 NetApp 数据服务（例如，Cloud Backup）以及控制许多内部部署和边缘存储设备。

BlueXP提供了两种发现和管理集群的方法：

* 通过系统管理器直接发现并进行管理（ONTAP 9.12.1 及更高版本）
* 通过Connector进行发现


连接器是安装在您环境中的软件。它允许您通过系统管理器访问管理功能，并访问提供数据复制、备份和恢复、数据分类、数据分层等功能的 BlueXP 云服务。

详细了解 link:https://docs.netapp.com/us-en/bluexp-ontap-onprem/index.html["使用BlueXP进行内部ONTAP集群管理"^]。

.步骤
. 登录 BlueXP。
+
.. 如果您有 BlueXP 登录名，请使用它。
.. 如果这是您第一次，请选择使用您的 NetApp 支持站点凭据登录，然后在 BlueXP 登录页面上输入您的凭据。


. 使用连接器或直接发现功能在 BlueXP 中发现您的本地集群。了解更多信息，请访问：https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html[发现本地 ONTAP 集群^]。
+
.. 了解如何link:https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-manage-ontap-direct.html["管理直接发现的集群"^]。
.. 了解如何link:https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-manage-ontap-connector.html["管理使用连接器发现的集群"^]。


. 使用系统管理器管理您的本地集群。在“我的工作环境”画布上，选择集群，然后在“服务”列表中点击“系统管理器”。
+
.. 详细了解 link:https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-manage-ontap-direct.html["管理直接发现的集群"^]。
.. 了解如何link:https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-manage-ontap-connector.html["管理使用连接器发现的集群"^]。






== BlueXP 和 ONTAP 9.12.1

注意：如果您使用的是 ONTAP 9.12.1，则会出现一条消息提示您试用 BlueXP。

+ 如果集群已连接到 BlueXP，则会显示登录提示。

. 单击*继续到BlueXp *以访问BlueXP链接。
+

NOTE: 如果您的系统设置已阻止外部网络、您将无法访问BlueXP。  要使用BlueXP访问System Manager、必须确保您的系统可以访问地址"`cloudmanager.cloud.netapp.com`"。  否则、您可以在提示符处选择使用随ONTAP系统安装的System Manager版本。

. 在BlueXP登录页面上、选择*使用您的NetApp 支持站点 凭据登录*并输入您的凭据。
+
如果您已经使用过 BlueXP 并使用电子邮件和密码登录，那么您需要继续使用该登录选项。

+
https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-logging-in.html["了解有关登录到BlueXP的更多信息"^]。

. 如果出现提示，请输入新 BlueXP 帐户的名称。
+
在大多数情况下、BlueXP会根据集群中的数据自动为您创建一个帐户。

. 输入集群的集群管理员凭据。


.结果
此时将显示System Manager、您现在可以从BlueXP管理集群。



== 了解有关BlueXP的更多信息

* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-overview.html["BlueXP概述"^]
* https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/index.html["通过BlueXP管理您的NetApp AFF 和FAS 系统"^]

