---
sidebar: sidebar 
permalink: concepts/sysmgr-integration-bluexp-concept.html 
keywords: netapp, ontap, system manager, experience, integrate, integration, bluexp, hybrid, cloud, dashboard, multicloud 
summary: 从ONTAP 9.12.1开始、System Manager与BlueXP完全集成。  借助BlueXP、您可以从一个控制平台管理混合多云基础架构、同时保留熟悉的System Manager信息板。 
---
= 将 ONTAP 系统管理器与 BlueXP 集成
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
从ONTAP 9.12.1开始、System Manager与BlueXP完全集成。  借助BlueXP、您可以从一个控制平台管理混合多云基础架构、同时保留熟悉的System Manager信息板。

借助BlueXP、您可以创建和管理云存储(例如Cloud Volumes ONTAP)、使用NetApp的数据服务(例如Cloud Backup)以及控制许多内部和边缘存储设备。

要在BlueXP中使用System Manager、请执行以下步骤：

.步骤
. 打开Web浏览器并输入集群管理网络接口的IP地址。
+
如果集群已连接到BlueXP、则会显示登录提示。

. 单击*继续到BlueXp *以访问BlueXP链接。
+

NOTE: 如果您的系统设置已阻止外部网络、您将无法访问BlueXP。  要使用BlueXP访问System Manager、必须确保您的系统可以访问地址"`cloudmanager.cloud.netapp.com`"。  否则、您可以在提示符处选择使用随ONTAP系统安装的System Manager版本。

. 在BlueXP登录页面上、选择*使用您的NetApp 支持站点 凭据登录*并输入您的凭据。
+
如果您已经使用过 BlueXP 并使用电子邮件和密码登录，那么您需要继续使用该登录选项。

+
https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-logging-in.html["了解有关登录到BlueXP的更多信息"^]。

. 如果出现提示，请输入新 BlueXP 帐户的名称。
+
在大多数情况下、BlueXP会根据集群中的数据自动为您创建一个帐户。

. 输入集群的集群管理员凭据。


.结果
此时将显示System Manager、您现在可以从BlueXP管理集群。



== 直接从BlueXP发现集群

BlueXP提供了两种发现和管理集群的方法：

* 直接发现、以便通过System Manager进行管理
+
此发现选项与上一节中所述的相同、您可以使用此选项执行重定向。

* 通过Connector进行发现
+
Connector是安装在您环境中的软件、可用于通过System Manager访问管理功能、还可访问提供数据复制、备份和恢复、数据分类、数据分层等功能的BlueXP云服务。



转至 https://docs.netapp.com/us-en/cloud-manager-family/index.html["BlueXP文档"^] 了解有关这些发现和管理选项的更多信息。



== 了解有关BlueXP的更多信息

* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-overview.html["BlueXP概述"^]
* https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/index.html["通过BlueXP管理您的NetApp AFF 和FAS 系统"^]

