---
permalink: nfs-rdma/configure-nics-task.html 
sidebar: sidebar 
keywords: networking, NICs, NFS over RDMA, NVIDIA, NFS, system manager, ports, ethernet ports 
summary: 本文介绍客户端系统和存储平台配置如何处理 NIC 在 ONTAP 中通过 RDMA 使用 NFS 的要求。 
---
= 为基于 RDMA 的 NFS 配置 NIC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
基于 RDMA 的 NFS 需要为客户端系统和存储平台配置 NIC 。



== 存储平台配置

需要在服务器上安装 X1148 RDMA 适配器。如果您使用的是 HA 配置，则故障转移配对节点上必须具有相应的 X1148 适配器，以便 RDMA 服务可以在故障转移期间继续运行。NIC 必须支持 ROCE 。

从ONTAP 9.10.1开始、您可以使用以下命令查看RDMA卸载协议列表：
`network port show -rdma-protocols roce`



== 客户端系统配置

客户端必须使用支持 Mellanox RDMA 的 NIC 卡（例如 X1148 ）和 Mellanox OFED 网络软件。有关支持的型号和版本，请参见 Mellanox 文档。尽管客户端和服务器可以直接连接，但由于交换机的故障转移性能有所提高，因此建议使用交换机。

客户端、服务器、任何交换机以及交换机上的所有端口都必须使用巨型帧进行配置。此外，还应确保优先级流量控制在任何交换机上有效。

确认此配置后，您可以挂载 NFS 。

[role="tabbed-block"]
====
.System Manager
--
您必须使用ONTAP 9.12.1或更高版本使用System Manager通过RDMA使用NFS配置网络接口。

.步骤
. 检查是否支持RDMA。导航到*网络>以太网端口*、然后在组视图中选择相应的节点。展开节点时，请查看给定端口的*RDMA协议*字段：值*RoCE*表示支持RDMA；短划线(*-*)表示不支持RDMA。
. 要添加VLAN、请选择*+ VLAN*。选择相应的节点。在*Port*下拉菜单中，如果可用的端口支持RDMA，它们将显示文本*RoCE Enabled"。如果不支持RDMA、则不会显示任何文本。
. 按照中的工作流进行操作 xref:../task_nas_enable_linux_nfs.html[使用 NFS 为 Linux 服务器启用 NAS 存储] 配置新的NFS服务器。
+
添加网络接口时、您可以选择*使用RoCE端口*。对于要使用基于RDMA的NFS的任何网络接口、请选择此选项。



--
.命令行界面
--
. 使用命令检查 NFS 服务器上是否启用了 RDMA 访问：
+
`vserver nfs show-vserver _SVM_name_`

+
默认情况下、 `-rdma` 应启用。如果不是，请在 NFS 服务器上启用 RDMA 访问：

+
`vserver nfs modify -vserver _SVM_name_ -rdma enabled`

. 通过 NFSv4.0 通过 RDMA 挂载客户端：
+
.. proto 参数的输入取决于服务器 IP 协议版本。如果为IPv4、请使用 `proto=rdma`。如果使用IPv6、请使用 `proto=rdma6`。
.. 将NFS目标端口指定为 `port=20049` 而不是标准端口2049：
+
`mount -o vers=4,minorversion=0,proto=rdma,port=20049 _Server_IP_address_:/_volume_path_ _mount_point_`



. *可选*：如果需要卸载客户端、请运行命令 `unmount _mount_path_`


--
====
.更多信息
* xref:../nfs-config/create-server-task.html[创建 NFS 服务器]
* xref:../task_nas_enable_linux_nfs.html[使用 NFS 为 Linux 服务器启用 NAS 存储]

