---
permalink: nfs-admin/access-cache-concept.html 
sidebar: sidebar 
keywords: access, cache 
summary: ONTAP 使用访问缓存来存储导出策略规则评估的结果，以供客户端对卷或 qtree 的访问操作使用。这样可以提高性能，因为与每次客户端发送 I/O 请求时执行导出策略规则评估过程相比，从访问缓存中检索信息的速度要快得多。 
---
= 访问缓存的工作原理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 使用访问缓存来存储导出策略规则评估的结果，以供客户端对卷或 qtree 的访问操作使用。这样可以提高性能，因为与每次客户端发送 I/O 请求时执行导出策略规则评估过程相比，从访问缓存中检索信息的速度要快得多。

每当 NFS 客户端发送 I/O 请求以访问卷或 qtree 上的数据时， ONTAP 都必须评估每个 I/O 请求，以确定是授予还是拒绝 I/O 请求。此评估涉及检查与卷或 qtree 关联的导出策略的每个导出策略规则。如果卷或 qtree 的路径涉及跨越一个或多个接合点，则可能需要对路径上的多个导出策略执行此检查。

请注意，此评估适用于从 NFS 客户端发送的每个 I/O 请求，例如读取，写入，列表，复制和其他操作；而不仅仅适用于初始挂载请求。

在 ONTAP 确定适用的导出策略规则并决定允许还是拒绝请求后， ONTAP 会在访问缓存中创建一个条目来存储此信息。

当 NFS 客户端发送 I/O 请求时， ONTAP 会记下客户端的 IP 地址， SVM 的 ID 以及与目标卷或 qtree 关联的导出策略，并首先检查访问缓存中是否存在匹配条目。如果访问缓存中存在匹配的条目， ONTAP 将使用存储的信息来允许或拒绝 I/O 请求。如果不存在匹配条目， ONTAP 将按照上述说明完成评估所有适用策略规则的正常过程。

当前未使用的访问缓存条目不会刷新。这样可以减少与外部名称服务器之间不必要的浪费通信。

从访问缓存中检索信息比对每个 I/O 请求执行整个导出策略规则评估过程要快得多。因此，使用访问缓存可以降低客户端访问检查的开销，从而显著提高性能。
