---
permalink: nfs-admin/create-volumes-specified-junction-task.html 
sidebar: sidebar 
keywords: create, data, volume, specify, junction, point 
summary: 您可以在创建数据卷时指定接合点。生成的卷会自动挂载在接合点，并可立即配置用于 NAS 访问。 
---
= 在ONTAP中创建具有指定接合点的数据卷
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在创建数据卷时指定接合点。生成的卷会自动挂载在接合点，并可立即配置用于 NAS 访问。

.开始之前
* 要创建卷的聚合必须已存在。
* 从ONTAP 9.13.1开始、您可以创建启用了容量分析和活动跟踪的卷。要启用容量或活动跟踪、请问题描述 `volume create` 命令 `-analytics-state` 或 `-activity-tracking-state` 设置为 `on`。
+
要了解有关容量分析和活动跟踪的更多信息，请参见 https://docs.netapp.com/us-en/ontap/task_nas_file_system_analytics_enable.html["启用文件系统分析"]。




NOTE: 接合路径中不能使用以下字符： * # " > < | ？\

+
此外，接合路径长度不能超过 255 个字符。

.步骤
. 创建具有接合点的卷：
+
`volume create -vserver _vserver_name_ -volume _volume_name_ -aggregate _aggregate_name_ -size {integer[KB|MB|GB|TB|PB]} -security-style {ntfs|unix|mixed} -junction-path _junction_path_`

+
接合路径必须以根（ / ）开头，并且可以同时包含目录和接合卷。接合路径不需要包含卷的名称。接合路径与卷名称无关。

+
指定卷安全模式是可选的。如果未指定安全模式，则 ONTAP 将使用应用于 Storage Virtual Machine （ SVM ）根卷的相同安全模式创建卷。但是，根卷的安全模式可能不是要应用于您创建的数据卷的安全模式。建议您在创建卷时指定安全模式，以最大程度地减少难以解决的文件访问问题。

+
接合路径不区分大小写； `/ENG` 与相同 `/eng`。如果创建 CIFS 共享， Windows 会将接合路径视为区分大小写。例如、如果接合为 `/ENG`，SMB共享的路径必须以开头 `/ENG`，不是 `/eng`。

+
您可以使用许多可选参数自定义数据卷。有关的详细信息 `volume create`，请参见link:https://docs.netapp.com/us-en/ontap-cli/volume-create.html["ONTAP 命令参考"^]。

. 验证是否已使用所需的接合点创建卷：
+
`volume show -vserver _vserver_name_ -volume _volume_name_ -junction`



.示例
以下示例将在` SVM VS1上创建一个具有接合路径的名为"`home"的卷 `/eng/home`：

[listing]
----
cluster1::> volume create -vserver vs1 -volume home4 -aggregate aggr1 -size 1g -junction-path /eng/home
[Job 1642] Job succeeded: Successful

cluster1::> volume show -vserver vs1 -volume home4 -junction
                  Junction                 Junction
Vserver   Volume  Active   Junction Path   Path Source
--------- ------- -------- --------------- -----------
vs1       home4   true     /eng/home       RW_volume
----