---
permalink: nfs-admin/modify-credential-cache-time-to-live-reference.html 
sidebar: sidebar 
keywords: reason, modify, nfs, credential, cache, time, live 
summary: 修改 NFS 凭据缓存生存时间（ TTL ）时，有多种情况可帮助解决问题。您应了解这些情形的含义以及进行这些修改的后果。 
---
= 修改 NFS 凭据缓存生存时间的原因
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 使用凭据缓存存储 NFS 导出访问的用户身份验证所需的信息，以加快访问速度并提高性能。您可以配置凭据缓存中存储信息的时间长度，以便根据您的环境对其进行自定义。

修改 NFS 凭据缓存生存时间（ TTL ）时，有多种情况可帮助解决问题。您应了解这些情形的含义以及进行这些修改的后果。



== reasons

在以下情况下，请考虑更改默认 TTL ：

[cols="2*"]
|===
| 问题描述 | 补救措施 


 a| 
由于来自 ONTAP 的请求负载较高，您环境中的名称服务器的性能正在下降。
 a| 
增加缓存的肯定和否定凭据的 TTL ，以减少从 ONTAP 到名称服务器的请求数。



 a| 
名称服务器管理员进行了更改，以允许访问先前被拒绝的 NFS 用户。
 a| 
减少缓存的否定凭据的 TTL ，以减少 NFS 用户等待 ONTAP 从外部名称服务器请求新凭据以获得访问权限所需的时间。



 a| 
名称服务器管理员进行了更改，以拒绝先前允许的 NFS 用户访问。
 a| 
减少缓存肯定凭据的 TTL ，以缩短 ONTAP 从外部名称服务器请求新凭据的时间，从而使 NFS 用户现在被拒绝访问。

|===


== 后果

您可以分别修改缓存肯定和否定凭据的时间长度。但是，您应该了解这种做法的优缺点。

[cols="3*"]
|===
| 如果您 ... | 优势是 ... | 缺点是 ... 


 a| 
增加肯定凭据缓存时间
 a| 
ONTAP 向名称服务器发送凭据请求的频率较低，从而减少了名称服务器上的负载。
 a| 
拒绝访问以前允许访问但不再允许访问的 NFS 用户需要更长时间。



 a| 
减少肯定凭据缓存时间
 a| 
拒绝访问先前允许访问但不再允许访问的 NFS 用户所需的时间更短。
 a| 
ONTAP 会更频繁地向名称服务器发送凭据请求，从而增加名称服务器的负载。



 a| 
增加否定凭据缓存时间
 a| 
ONTAP 向名称服务器发送凭据请求的频率较低，从而减少了名称服务器上的负载。
 a| 
向以前不允许访问但现在允许访问的 NFS 用户授予访问权限需要更长时间。



 a| 
减少否定凭据缓存时间
 a| 
为以前不允许访问但现在允许访问的 NFS 用户授予访问权限所需的时间更短。
 a| 
ONTAP 会更频繁地向名称服务器发送凭据请求，从而增加名称服务器的负载。

|===