---
permalink: nfs-admin/nfs-credential-cache-concept.html 
sidebar: sidebar 
keywords: nfs, credential, cache 
summary: 当 NFS 用户请求访问存储系统上的 NFS 导出时， ONTAP 必须从外部名称服务器或本地文件检索用户凭据以对用户进行身份验证。然后， ONTAP 会将这些凭据存储在内部凭据缓存中，以供日后参考。了解 NFS 凭据缓存的工作原理有助于您处理潜在的性能和访问问题。 
---
= ONTAP NFS 凭据缓存的工作原理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
当 NFS 用户请求访问存储系统上的 NFS 导出时， ONTAP 必须从外部名称服务器或本地文件检索用户凭据以对用户进行身份验证。然后， ONTAP 会将这些凭据存储在内部凭据缓存中，以供日后参考。了解 NFS 凭据缓存的工作原理有助于您处理潜在的性能和访问问题。

如果没有凭据缓存， ONTAP 将必须在 NFS 用户每次请求访问时查询名称服务。在许多用户访问的繁忙存储系统上，这可能会快速导致严重的性能问题，从而导致不必要的延迟，甚至拒绝 NFS 客户端访问。

通过凭据缓存， ONTAP 会检索用户凭据，然后将其存储一段预定的时间，以便在 NFS 客户端发送另一个请求时快速轻松地进行访问。此方法具有以下优势：

* 它可以减少对外部名称服务器（例如 NIS 或 LDAP ）的请求，从而减轻存储系统的负载。
* 它可以减少向外部名称服务器发送的请求，从而减轻这些服务器的负载。
* 它可以在用户进行身份验证之前，消除从外部源获取凭据的等待时间，从而加快用户访问速度。


ONTAP 会将肯定和否定凭据存储在凭据缓存中。肯定凭据表示用户已通过身份验证并获得访问权限。否定凭据表示用户未通过身份验证，并被拒绝访问。

默认情况下， ONTAP 会将肯定凭据存储 24 小时；也就是说，在对用户进行初始身份验证后， ONTAP 会对该用户 24 小时内的任何访问请求使用缓存的凭据。如果用户在 24 小时后请求访问，则此周期将重新开始： ONTAP 丢弃缓存的凭据，并从相应的名称服务源再次获取凭据。如果名称服务器上的凭据在过去 24 小时内发生更改，则 ONTAP 会缓存更新后的凭据，以供未来 24 小时使用。

默认情况下， ONTAP 会将否定凭据存储两个小时；也就是说，在最初拒绝用户访问后， ONTAP 会继续拒绝该用户的任何访问请求两个小时。如果用户在 2 小时后请求访问，则循环将重新开始： ONTAP 再次从相应的名称服务源获取凭据。如果名称服务器上的凭据在过去两小时内发生更改，则 ONTAP 会缓存更新后的凭据，以供未来两小时使用。
