---
sidebar: sidebar 
permalink: anti-ransomware/enable-task.html 
keywords: anti-ransomware overview, ransomware, security, introduce, autotonomous, protection, arp, detection, threat, attack, suspect, what ontap anti-ransomware detects, entropy, abnormal volume activity, extension conformity, how to recover data in after a ransomware attack, ransomware protection strategy 
summary: '可以在新卷或现有卷上启用自动勒索软件保护(ARP)。您首先可以在学习模式下启用ARP、在此模式下、系统会分析工作负载以确定正常行为特征、然后切换到主动模式、在主动模式下、系统会标记异常活动以供评估。' 
---
= 启用自主勒索软件保护
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
从ONTAP 9.10.1开始、可以在新卷或现有卷上启用自动勒索软件保护(ARP)。您首先可以在学习模式下启用ARP、在此模式下、系统会分析工作负载以确定正常行为特征、然后切换到主动模式、在主动模式下、系统会标记异常活动以供评估。

.您需要什么？ #8217 ；将需要什么
* 为 NFS 或 SMB （或这两者）启用的 Storage VM 。
* 已为您的ONTAP 版本安装正确的许可证。
+
[cols="2*"]
|===
| ONTAP 版本 | 许可证 


 a| 
ONTAP 9.8-9.10.1
 a| 
MT_EK_Mgmt (多租户密钥管理)



 a| 
ONTAP 9.11.1及更高版本
 a| 
反勒索软件

|===
* 配置了客户端的 NAS 工作负载。
* 要保护的卷必须具有活动接合路径。
* 可选但建议：EMS系统配置为发送电子邮件通知、其中包括ARP活动通知。有关详细信息，请参见 link:../error-messages/configure-ems-events-send-email-task.html["配置 EMS 事件以发送电子邮件通知"]。


NetApp ARP包括一个初始学习周期(也称为"试运行")、在该学习周期中、ONTAP 系统会学习哪些文件扩展名有效、并使用分析后的数据来开发警报配置文件。在学习模式下运行ARP并有足够的时间来评估工作负载特征后、您可以切换到活动模式并开始保护数据。反勒索软件会继续收集和分析数据以细化警报配置文件。

在学习期间，系统会自动学习已配置卷的工作负载特征，并执行特殊观察和模式分析。

建议学习时间为 30 天。虽然您可以随时从学习切换到主动模式，但提前切换可能会导致误报过多。

在ONTAP 命令行界面中、您可以使用`security anti勒索 软件volume workload-behavior show`命令显示迄今为止检测到的文件扩展名。但是，建议不要使用此工具缩短学习时间。

您可以在现有卷上启用ARP、也可以从头创建新卷并启用ARP。


NOTE: 在现有卷中，学习和活动模式仅适用于新写入的数据，而不适用于卷中已有的数据。不会扫描和分析现有数据、因为在为卷启用ARP后、系统会根据新数据假设先前正常数据流量的特征。

在 ONTAP 命令行界面中，我们引入了一个新的命令系列来管理此功能： `sSecurity anti-ransafecurt volume` 。您也可以使用 `volume modify` 命令和 ` -anti勒索 软件` 参数来管理此功能。

.步骤
[role="tabbed-block"]
====
.System Manager
--
. 单击 * 存储 > 卷 * ，然后选择要保护的卷。
. 在*卷*概述的*安全性*选项卡中、单击*防勒索软件*框中的*状态*以在学习模式下从已禁用切换到已启用。
. 学习期结束后、将ARP切换到活动模式。
+
.. 单击 * 存储 > 卷 * ，然后选择已准备好进入活动模式的卷。
.. 在*卷*概述的*安全性*选项卡中、单击防勒索软件框中的*切换*至活动模式。


. 您始终可以在*防勒索软件*框中验证卷的ARP状态。要显示所有卷的ARP状态：在*卷*窗格中、单击*显示/隐藏*、然后确保已选中*防勒索软件*状态。


--
.命令行界面
--
. 修改现有卷以在学习模式下启用勒索软件保护：
+
`s安全防勒索软件卷 dry-run -volume _vol_name_ -vserver _svm_name_`

+
您还可以使用 `volume modify` 命令启用勒索软件：

+
`volume modify -volume _vol_name_ -vserver _svm_name_ -anti-ransone-state dry-run`

+
在 CLI 中，您还可以在配置数据之前创建一个启用了反勒索软件保护的新卷。

+
`volume create -volume _vol_name_ -vserver _svm_name_ -aggregate _aggr_name_ -size _nn_ -anti-ransonve-state dry-run -junction-path /_path_name_`

+

NOTE: 最初应始终在dry-run状态下启用ARP。从活动状态开始，可能会导致误报报告过多。

. 学习期结束后，修改受保护卷以切换到活动模式：
+
`s安全防勒索软件卷 enable -volume _vol_name_ -vserver _svm_name_`

+
您也可以使用 modify volume 命令切换到活动模式：

+
`volume modify -volume _vol_name_ -vserver _svm_name_ -anti-ransone-state active`

. 验证卷的ARP状态。
+
`s安全性反勒索软件卷显示`



--
====