---
sidebar: sidebar 
permalink: anti-ransomware/modify-automatic-shapshot-options-task.html 
keywords: anti-ransomware, automatic Snapshot copy, suspected attack, vserver options command 
summary: '从ONTAP 9.11.1开始、您可以控制针对可疑勒索软件攻击自动生成的反勒索软件(ARW) Snapshot副本的数量和保留期限。' 
---
= 修改自动Snapshot副本的选项
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
从ONTAP 9.11.1开始、您可以控制针对可疑勒索软件攻击自动生成的反勒索软件(ARW) Snapshot副本的数量和保留期限。

*注*：`vserver options`命令是一个隐藏命令。要查看手册页、请在ONTAP 命令行界面中输入`man vserver options`。

可以修改以下自动Snapshot副本选项：

arw.snap.max.count:: 指定在任何给定时间卷中可以存在的最大ARW Snapshot副本数。系统会删除旧副本、以确保ARW Snapshot副本总数不超过此指定限制。
arw.snap.create.interval.hours:: 指定ARW Snapshot副本之间的间隔(以小时为单位)。如果怀疑发生攻击、而先前创建的副本早于此指定间隔、则会创建一个新的Snapshot副本。
arw.snap.normal.retain.interval.hours:: 指定保留ARW Snapshot副本的持续时间(以小时为单位)。如果某个ARW Snapshot副本变为旧副本、则会删除在最新副本之前为达到此期限而创建的任何其他ARW Snapshot副本。任何ARW Snapshot副本都不能早于此持续时间。
arw.snap.max.retain.interval.days:: 指定可保留ARW Snapshot副本的最长持续时间(以天为单位)。如果卷上未报告攻击、则超过此持续时间的任何ARW Snapshot副本将被删除。
arw.snap.create.interval.hours.post.max.count:: 指定当卷已包含最大ARW Snapshot副本数时ARW Snapshot副本之间的间隔(以小时为单位)。达到最大数量后、将删除一个ARW Snapshot副本、以便为新副本腾出空间。使用此选项可以降低新的ARW Snapshot副本创建速度、以保留旧副本。如果卷已包含最大数量的ARW Snapshot副本、则此选项中指定的间隔将用于下次创建ARW Snapshot副本、而不是创建arw.snap.create.interval.hours。
arw.surge.snap.interval.days:: 指定两个ARW快速增长Snapshot副本之间的间隔(以天为单位)。如果IO流量激增、而上次创建的ARW Snapshot副本早于此指定间隔、则会创建新的ARW Snapshot喘振副本。此选项还指定保留ARW快速增长Snapshot副本的持续时间(以天为单位)。




== 命令行界面操作步骤

要显示当前所有ARW Snapshot副本设置、请输入：`vserver options -vserver _svm_name_ arw*`

要显示选定的当前ARW Snapshot副本设置、请输入：`vserver options -vserver _svm_name_-option-name _arw_setting_name_`

要修改ARW Snapshot副本设置、请输入：`vserver options -vserver _svm_name_-option-name _arw_setting_name_-option-value _arw_setting_value_`
