---
sidebar: sidebar 
permalink: anti-ransomware/modify-automatic-shapshot-options-task.html 
keywords: anti-ransomware, automatic Snapshot copy, suspected attack, vserver options, autonomous ransomware protection, arp 
summary: 修改在发生可疑勒索软件攻击时自动生成的自动勒索软件保护Snapshot副本的设置。 
---
= 修改自动Snapshot副本的选项
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
从ONTAP 9.11.1开始、您可以使用命令行界面来控制在发生可疑勒索软件攻击时自动生成的自动勒索软件保护(Autonomous Ransomware Protection、ARP) Snapshot副本的保留设置。

.开始之前
您只能修改节点SVM上的ARP Snapshot选项。

.步骤
. 要显示所有当前ARP Snapshot副本设置、请输入：
`vserver options -vserver _svm_name_ arw*`
+

NOTE: 。 `vserver options` command是一个隐藏命令。要查看手册页、请输入 `man vserver options` 在ONTAP 命令行界面上。

. 要显示选定的当前ARP Snapshot副本设置、请输入：
`vserver options -vserver _svm_name_ -option-name _arw_setting_name_`
. 要修改ARP Snapshot副本设置、请输入：
`vserver options -vserver _svm_name_ -option-name _arw_setting_name_ -option-value _arw_setting_value_`
+
以下设置可修改：

+
[cols="1,3"]
|===
| ARW设置 | Description 


| *arw.snap.max.count* | 指定在任何给定时间卷中可以存在的最大ARP Snapshot副本数。系统会删除较早的副本、以确保ARP Snapshot副本总数不超过此指定限制。 


| * arw.snap.create.interval.hours* | 指定两个ARP Snapshot副本之间的间隔_in Hours_。如果怀疑发生攻击、并且之前创建的副本早于指定的时间间隔、则会创建一个新的Snapshot副本。 


| * arw.snap.normal.retain.interval.hours* | 指定保留ARP Snapshot副本的持续时间_以小时为单位_。当ARP Snapshot副本变为旧副本时、将删除在最新副本之前为达到此期限而创建的任何其他ARP Snapshot副本。任何ARP Snapshot副本都不能早于此持续时间。 


| * arw.snap.max.retain.interval.days*  a| 
指定可以保留ARP Snapshot副本的最长持续时间(以天为单位)。如果卷上未报告任何早于此持续时间的ARP Snapshot副本攻击、则此副本将被删除。

+


NOTE: 如果检测到中等威胁、则会忽略ARP Snapshot的最大保留间隔。为响应威胁而创建的Snapshot将保留、直到您对威胁做出响应为止。将威胁标记为误报删除卷上的ARP Snapshot副本。



| * arw.snap.create.interval.hours.post.max.count* | 指定卷已包含最大ARP Snapshot副本数时两个ARP Snapshot副本之间的间隔_in Hours_。达到最大数量后、将删除ARP Snapshot副本、以便为新副本腾出空间。可以使用此选项降低新的ARP Snapshot副本创建速度、以保留旧副本。如果卷已包含最大数量的ARP Snapshot副本、则此选项中指定的时间间隔将用于下次创建ARP Snapshot副本、而不是arw.snap.create.interval.hours。 


| * arw.surge.snap.interval.days* | 指定ARP激增Snapshot副本之间的间隔_in days _。如果IO流量激增、而上次创建的ARP Snapshot副本早于此指定间隔、则ONTAP会创建一个ARP Snapshot激增副本。此选项还指定ARP激增快照的保留期限_in day_。 
|===

