---
sidebar: sidebar 
permalink: anti-ransomware/pause-task.html 
keywords: anti-ransomware, ransomware, pause, autonomous, protection, arp 
summary: 如果您预期会发生异常工作负载事件、则可以随时暂时暂停并恢复自动防兰森异常保护分析。 
---
= 暂停自主勒索软件保护以从分析中排除工作负载事件
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果您预期会发生异常工作负载事件、您可以随时临时暂停和恢复自主勒索软件保护(ARP)分析。

从ONTAP 9.13.1开始、您可以启用多管理员验证(MAV)、以便需要两个或更多经过身份验证的用户管理员来暂停ARP。 link:../multi-admin-verify/enable-disable-task.html["了解更多信息。"^]。

.关于此任务
在ARP暂停期间、不会记录任何事件、也不会对新写入执行任何操作。但是，分析操作仍会在后台对早期日志执行。


NOTE: 请勿使用ARP禁用功能暂停分析。这样做会禁用卷上的ARP、并且与所了解的工作负载行为相关的所有现有信息都将丢失。这需要重新开始学习。

.步骤
您可以使用System Manager或ONTAP命令行界面暂停ARP。

[role="tabbed-block"]
====
.System Manager
--
. 选择*存储>卷*，然后选择要暂停ARP的卷。
. 在卷概述的**安全性**选项卡中，选择*反勒索软件*框中的*暂停反勒索软件*。
+

NOTE: 从ONTAP 9.13.1开始，如果使用MAV保护ARP设置，暂停操作将提示您获得一个或多个其他管理员的批准。 link:../multi-admin-verify/request-operation-task.html["必须获得所有管理员的批准"] 与MAV审批组关联、否则操作将失败。



--
.命令行界面
--
. 暂停卷上的ARP：
+
`security anti-ransomware volume pause -vserver _svm_name_ -volume _vol_name_`

. 要恢复处理、请使用 `resume` 命令：
+
`security anti-ransomware volume resume -vserver _svm_name_ -volume _vol_name_`

. *如果您使用MAV (从ONTAP 9.13.1开始可用于ARP)来保护ARP设置，*暂停操作将提示您获得一个或多个额外管理员的批准。必须从与MAV批准组关联的所有管理员处获得批准、否则操作将失败。
+
如果您正在使用MAV、并且预期的暂停操作需要额外的审批、则每个MAV组审批人将执行以下操作：

+
.. 显示请求：
+
`security multi-admin-verify request show`

.. 批准申请：
+
`security multi-admin-verify request approve -index[_number returned from show request_]`

+
最后一个组批准者的响应指示卷已修改、并且ARP状态已暂停。

+
如果您正在使用MAV、并且您是MAV组批准者、则可以拒绝暂停操作请求：

+
`security multi-admin-verify request veto -index[_number returned from show request_]`





--
====