---
sidebar: sidebar 
permalink: anti-ransomware/switch-learning-to-active-mode.html 
keywords: ransomware, arp, mode, switch, active, learning, autonomous ransomware protection 
summary: '对于自动防兰软件保护(ARP 9.15.1及更早版本)、手动或自动将已启用ARP的卷从学习模式切换到活动模式。' 
---
= 学习一段时间后切换到ARP活动模式
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
对于自动防兰软件保护(ARP 9.15.1及更早版本或随FlexGroup卷一起运行的ARP)、手动或自动将启用了ARP的卷从学习模式切换到活动模式。在ARP完成至少30天的学习模式运行后、您可以手动切换到活动模式。从ARP.13.1.开始、ONTAP 9会自动确定最佳学习周期间隔并自动执行交换机操作、这可能会在30天之前发生。

如果在运行9.16.1 9.161或更高版本的FlexVol卷上使用ARP、则ARP/AI保护将启用并自动变为活动状态。无需学习。


NOTE: 在现有卷中、学习和活动模式仅适用于新写入的数据、而不适用于卷中已有的数据。不会扫描和分析现有数据、因为在为卷启用ARP后、系统会根据新数据假设先前正常数据流量的特征。



== 记忆期过后、手动切换到激活模式

对于带有FlexGroup卷的ARP.10.1 9.15.1和ONTAP、您可以使用System Manager或ONTAP 9命令行界面手动从ARP.10.1学习模式过渡到活动模式。

[role="tabbed-block"]
====
.System Manager
--
.步骤
. 选择*存储>卷*，然后选择已准备好进入活动模式的卷。
. 在*Volumes*概述的*Security*选项卡中，在Anti-勒索 软件框中选择*切换到活动模式*。
. 您可以在*Anti-勒索 软件*框中验证卷的ARP状态。


--
.命令行界面
--
.步骤
. 学习期结束后、如果尚未自动修改受保护卷以切换到活动模式、请将其修改为：
+
[source, cli]
----
security anti-ransomware volume enable -volume <vol_name> -vserver <svm_name>
----
+
您也可以使用 modify volume 命令切换到活动模式：

+
[source, cli]
----
volume modify -volume <vol_name> -vserver <svm_name> -anti-ransomware-state active
----
. 验证卷的ARP状态。
+
[source, cli]
----
security anti-ransomware volume show
----


--
====


== 自动从学习模式切换到活动模式

从ARP.13.1.开始、ONTAP 9分析中添加了自适应学习功能、并会自动从学习模式切换到主动模式。ARP自动决定从学习模式切换到活动模式取决于以下选项的配置设置：

[listing]
----
 -anti-ransomware-auto-switch-minimum-incoming-data-percent
 -anti-ransomware-auto-switch-duration-without-new-file-extension
 -anti-ransomware-auto-switch-minimum-learning-period
 -anti-ransomware-auto-switch-minimum-file-count
 -anti-ransomware-auto-switch-minimum-file-extension
----
学习30天后、卷会自动切换到活动模式、即使其中一个或多个条件不满足也是如此。也就是说、如果启用了自动切换、则卷将在最长30天后切换到活动模式。30天的最大值是固定的、不可修改。

有关ARP配置选项(包括默认值)的详细信息、请参见 link:https://docs.netapp.com/us-en/ontap-cli/security-anti-ransomware-volume-auto-switch-to-enable-mode-show.html["ONTAP 命令参考"^]。
