---
sidebar: sidebar 
permalink: anti-ransomware/switch-learning-to-active-mode.html 
keywords: ransomware, arp, mode, switch, active, learning, autonomous ransomware protection 
summary: 对于 NAS 环境中的 ARP 9.15.1 及更早版本，手动或自动将启用 ARP 的卷从学习模式切换到活动模式。 
---
= 学习一段时间后、在ONTAP ARP中切换到活动模式
:allow-uri-read: 


[role="lead"]
对于 NAS 环境，手动或自动将启用 ARP 的卷从学习模式切换到活动模式。如果您在ONTAP 9.15.1 及更早版本中使用 ARP，或者在ONTAP 9.17.1 及更早版本的FlexGroup卷上运行 ARP，则需要切换模式。

ARP 完成建议至少 30 天的学习模式运行后，您可以手动切换到活动模式。从ONTAP 9.13.1 开始，ARP 会自动确定最佳学习周期间隔并自动切换，切换可能在 30 天之前发生。

如果您将 ARP 与 ARP/AI 保护结合使用，则 ARP 会自动激活。无需学习期。


NOTE: 在现有卷中、学习和活动模式仅适用于新写入的数据、而不适用于卷中已有的数据。不会扫描和分析现有数据、因为在为卷启用ARP后、系统会根据新数据假设先前正常数据流量的特征。



== 记忆期过后、手动切换到激活模式

对于ONTAP 9.10.1 至 9.15.1（ONTAP 9.17.1 及更早版本，带FlexGroup卷），学习期结束后，您可以使用系统管理器或ONTAP CLI 手动将 ARP 学习模式转换为活动模式。

.关于此任务
本过程中描述的学习期后手动过渡到主动模式特定于 NAS 环境。

.步骤
您可以使用系统管理器或ONTAP CLI 从学习模式切换到主动模式。

[role="tabbed-block"]
====
.System Manager
--
. 选择*存储>卷*，然后选择已准备好进入活动模式的卷。
. 在*Volumes*概述的*Security*选项卡中，在Anti-勒索 软件框中选择*切换到活动模式*。
. 您可以在*Anti-勒索 软件*框中验证卷的ARP状态。


--
.命令行界面
--
. 如果尚未自动完成，则修改受保护的卷以切换到活动模式：
+
[source, cli]
----
security anti-ransomware volume enable -volume <vol_name> -vserver <svm_name>
----
+
您也可以使用 modify volume 命令切换到活动模式：

+
[source, cli]
----
volume modify -volume <vol_name> -vserver <svm_name> -anti-ransomware-state enabled
----
. 验证卷的ARP状态。
+
[source, cli]
----
security anti-ransomware volume show
----


--
====


== 自动从学习模式切换到活动模式

从ONTAP 9.13.1 开始，自适应学习已添加到 ARP 分析中，并且可以自动从学习模式切换到主动模式。ARP自动从学习模式切换到主动模式的自主决策基于以下选项的配置设置：

[listing]
----
 -anti-ransomware-auto-switch-minimum-incoming-data-percent
 -anti-ransomware-auto-switch-duration-without-new-file-extension
 -anti-ransomware-auto-switch-minimum-learning-period
 -anti-ransomware-auto-switch-minimum-file-count
 -anti-ransomware-auto-switch-minimum-file-extension
----
如果启用自动切换功能，即使未满足所有条件，卷也会在最多 30 天后自动切换到活动模式。此 30 天的限制是固定的，无法更改。

有关ARP配置选项(包括默认值)的详细信息、请参见 link:https://docs.netapp.com/us-en/ontap-cli/security-anti-ransomware-volume-auto-switch-to-enable-mode-show.html["ONTAP 命令参考"^]。

.相关信息
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+anti-ransomware+volume["安全反勒索软件量"^]

