---
sidebar: sidebar 
permalink: anti-ransomware/use-cases-restrictions-concept.html 
keywords: anti-ransomware workloads, anti-ransomware requirements, anti-ransomware performance, volumes, anti-ransomware encryption, anti-ransomware system configurations, arp 
summary: 在当前版本中，勒索软件保护最适合 NAS 环境。未来版本将支持其他环境。 
---
= 自主勒索软件保护使用情形和注意事项
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
自动防软件功能的可用性取决于您使用的ONTAP 版本。



== 支持和不支持的配置

ONTAP 平台支持：

* 从ONTAP 9.10.1开始、所有内部ONTAP 系统均可使用自动勒索软件保护(ARP)功能。


合适的工作负载：

* NFS 存储上的数据库
* Windows 或 Linux 主目录
+
由于用户可能会创建在学习期间未检测到扩展名的文件、因此在此工作负载中出现误报的可能性更大。

* 图像和视频
+
例如，医疗保健记录和电子设计自动化（ Electronic Design Automation ， EDA ）数据。



从ONTAP 9.12.1开始、ARP可用于以下配置：

* 使用SnapMirror保护的卷
* 使用SnapMirror进行保护的SVM
* 已启用SVM进行迁移(SVM数据移动性)


不适合的工作负载：

* 文件创建或删除频率较高的工作负载（几秒内就有数十万个文件；例如，测试 / 开发工作负载）
* ARP取决于能否识别文件创建、重命名或删除活动异常激增的情况。如果应用程序本身是文件活动的源，则无法有效地将其与勒索软件活动区分开来
* 应用程序或主机对数据ARP进行加密的工作负载取决于将传入数据区分为加密或未加密。如果应用程序本身正在对数据进行加密，则此功能的有效性将会降低。但是、该功能仍可根据文件活动(删除、覆盖或创建、或者使用新文件扩展名创建或重命名)和文件类型来工作。


不支持的系统配置：

* SAN 环境
* ONTAP S3 环境
* NFS 上的 VMDK


卷要求：

* 容量不足 100%
* 接合路径必须处于活动状态


不支持的卷类型：

* 使卷脱机
* 受限卷
* SnapLock 卷
* FlexGroup 卷(从ONTAP 9.13.1开始、支持FlexGroup 卷)
* FlexCache卷(原始FlexVol卷支持ARP、但缓存卷不支持ARP)
* Storage VM的根卷
* SnapMirror 同步
* SAN-only volumes
* 已停止Storage VM的卷




== SnapMirror和ARP互操作性

从ONTAP 9.12.1开始、异步SnapMirror目标卷支持ARP。SnapMirror同步**不支持ARP。

如果SnapMirror源卷已启用ARP、则SnapMirror目标卷会自动获取源卷的ARP配置状态(学习、已启用等)、ARP培训数据以及ARP创建的Snapshot。无需显式启用。

虽然目标卷包含只读(Read Only、RO) Snapshot副本、但不会对其数据执行ARP处理。但是、当SnapMirror目标卷转换为读写(rw)时、将自动在RW转换的目标卷上启用ARP。除了已记录在源卷上的内容之外、目标卷不需要任何其他学习操作步骤。

在ONTAP 9.10.1和9.11.1中、SnapMirror不会将ARP配置状态、培训数据和Snapshot副本从源卷传输到目标卷。因此、在将SnapMirror目标卷转换为RW后、必须在转换后的学习模式下明确启用目标卷上的ARP。



== ARP性能和频率注意事项

根据吞吐量和峰值IOPS衡量、ARP对系统性能的影响最小。ARP功能的影响取决于特定的卷工作负载。对于常见工作负载、建议遵循以下配置限制：

[cols="30,20,30"]
|===
| 工作负载特征 | 每个节点的建议卷限制 | 超出每节点卷限制时性能下降传递：[*] 


| 读取密集型数据或数据可以压缩。 | 150 | 最大IOPS的4% 


| 写入密集型、无法压缩数据。 | 60 | 最大IOPS的10% 
|===
密码：[*]无论添加的卷数是否超过建议的限制、系统性能均不会超过这些百分比。

由于ARP分析按优先级顺序运行、因此随着受保护卷数量的增加、在每个卷上运行分析的频率会降低。



== 对受自动防兰功能保护的卷进行多管理员验证(ARP)

从ONTAP 9.13.1开始、您可以使用ARP启用多管理员验证(MAV)、以提高安全性。MAV可确保至少需要两个或更多经过身份验证的管理员在受保护的卷上关闭ARP、暂停ARP或将可疑攻击标记为误报。了解操作方法 link:../multi-admin-verify/enable-disable-task.html["为受ARP保护的卷启用MAV"^]。

您需要为MAV组定义管理员并为创建MAV规则 `security anti-ransomware volume disable`， `security anti-ransomware volume pause`，和 `security anti-ransomware volume attack clear-suspect` 要保护的ARP命令。MAV组中的每个管理员都必须批准每个新规则请求和 link:../multi-admin-verify/enable-disable-task.html["再次添加MAV规则"^] 在MAV设置中。
