---
sidebar: sidebar 
permalink: snapmirror-active-sync/aufo-site-b-troubleshoot-task.html 
keywords: SM-BC, SMBC, troubleshooting, automatic unplanned failover, aufo, failover, Mediator, quorum, snapmirror active sync 
summary: 站点 A 故障不会在站点 B 上触发计划外故障转移 
---
= 站点 B 未触发自动计划外故障转移
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


.问题描述 ：
[role="lead"]
站点 A 故障不会在站点 B 上触发计划外故障转移

.可能的发生原因 1：
未配置ONTAP调解器。要确定这是否为发生原因、请问题描述the `snapmirror mediator show` 命令。

....
Cluster2::*> snapmirror mediator show
This table is currently empty.
....
此示例指示未在站点B上配置ONTAP调解器

.解决方案 ：
确保已在两个集群上配置ONTAP调解器、并且状态为已连接、并且仲裁设置为True。

.可能的发生原因#2：
SnapMirror 一致性组不同步。要确定这是否为发生原因，请查看事件日志以查看一致性组在站点 A 发生故障期间是否处于同步状态。

....
cluster::*> event log show -event *out.of.sync*

Time                Node             Severity      Event
------------------- ---------------- ------------- ---------------------------
10/1/2020 23:26:12  sti42-vsim-ucs511w ERROR       sms.status.out.of.sync: Source volume "vs0:zrto_cg_556844_511u_RW1" and destination volume "vs1:zrto_cg_556881_511w_DP1" with relationship UUID "55ab7942-03e5-11eb-ba5a-005056a7dc14" is in "out-of-sync" status due to the following reason: "Transfer failed."
....
.解决方案 ：
要在站点 B 上执行强制故障转移，请完成以下步骤

. 从站点 B 取消映射属于一致性组的所有 LUN
. 使用删除SnapMirror一致性组关系 `force` 选项
. 输入 `snapmirror break` 命令将卷从DP转换为R/W、以启用站点B的I/O
. 启动站点 A 节点以创建从站点 B 到站点 A 的零 RTO 关系
. 使用释放站点A上的一致性组 `relationship-info-only`、以保留通用快照并取消映射属于该一致性组的LUN。
. 通过使用 Sync 策略或异步策略设置卷级别关系，将站点 A 上的卷从 R/W 转换为 DP 。
. 问题描述 `snapmirror resync` 同步关系。
. 删除站点 A 上具有 Sync 策略的 SnapMirror 关系
. 使用释放具有Sync策略的SnapMirror关系 `relationship-info-only true` 在站点B上
. 创建从站点 B 到站点 A 的一致性组关系
. 从站点 A 执行一致性组重新同步，然后验证一致性组是否处于同步状态。
. 重新扫描主机 LUN I/O 路径以还原 LUN 的所有路径。


.相关信息
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-break.html["SnapMirror 中断"^]

