---
sidebar: sidebar 
permalink: snapmirror-active-sync/convert-relationships-task.html 
keywords: SM-BC, SMBC, convert, SnapMirror synchronous, zero RPO, zero recovery time objective, zero RTO, existing, snapmirror active sync 
summary: 在SnapMirror活动同步配置中的对称保护和非对称保护之间进行转换。 
---
= 转换SnapMirror活动同步关系类型
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
从ONTAP 9.15.1开始、您可以在不同类型的SnapMirror主动同步保护之间进行转换：从非对称到对称主动/主动、反之亦然。



== 转换为对称主动/主动关系

您可以将具有同步保护的SnapMirror活动同步关系转换为使用对称主动/主动。

.开始之前
* 两个集群都必须运行ONTAP 9.151或更高版本。
* 对称主动/主动配置需要 `AutomatedFailoverDuplex` 保护策略。或者、您也可以 xref:../data-protection/create-custom-replication-policy-concept.html[创建自定义SnapMirror策略] 提供了 `-type` 为 `automated-failover-duplex`。


[role="tabbed-block"]
====
.System Manager
--
.统一配置的步骤
. 删除目标igrop：
+
.. 在目标集群上、导航到**主机**>** SAN启动程序组**。
.. 选择具有SnapMirror关系的igroup，然后选择**删除**。
.. 在对话框中，选择**取消映射关联的LUO**框，然后选择**删除**。


. 编辑SnapMirror活动同步关系。
+
.. 导航到**保护**>**关系**。
.. 选择要修改的关系旁边的kabob菜单，然后选择**编辑**。
.. 将**保护策略**修改为AutomatedFailover双 工。
.. 选择 `AutoMatedFailoverDuplex` 提示对话框修改主机邻近设置。对于启动程序，请为**启动程序近端**选择适当的选项，然后选择**保存**。
.. 选择**保存**。


. 在“**保护**”菜单中，当关系显示为时，确认操作成功 `InSync`。


.非一致配置的步骤
. 删除目标igrop：
+
.. 在二级站点上，导航到**主机**>** SAN启动程序组**。
.. 选择具有SnapMirror关系的igroup，然后选择**删除**。
.. 在对话框中，选择**取消映射关联的LUO**框，然后选择**删除**。


. 创建新的igrop：
+
.. 在目标站点上的“** SAN启动程序组**”菜单中，选择“**添加**”。
.. 提供**名称**，选择**主机操作系统**，然后选择**启动程序组成员**。
.. 选择**保存**。


. 将新igrop映射到目标LUN。
+
.. 导航到**存储**>** LUN **。
.. 选择要映射到此igrop的所有LUN。
.. 选择**更多**，然后选择**映射到启动程序组**。


. 编辑SnapMirror活动同步关系。
+
.. 导航到**保护**>**关系**。
.. 选择要修改的关系旁边的kabob菜单，然后选择**编辑**。
.. 将**保护策略**修改为AutomatedFailover双 工。
.. 选择AutoMatedFailover双 工可启动修改主机邻近设置的选项。对于启动程序，请为**启动程序近端**选择适当的选项，然后选择**保存**。
.. 选择**保存**。


. 在“**保护**”菜单中，当关系显示为时，确认操作成功 `InSync`。


--
.命令行界面
--
.统一配置的步骤
. 从修改SnapMirror策略 `AutomatedFailover` to `AutomatedFailoverDuplex`：
+
`snapmirror modify -destination-path _destination_path_ -policy AutomatedFailoverDuplex`

. 修改策略将触发重新同步。等待重新同步完成、然后确认此关系为 `Insync`：
+
`snapmirror show -destination-path _destination_path_`

. 如果现有主机位于主集群的本地、请将该主机添加到第二个集群、并建立与每个集群的相应访问权限的连接。
. 在二级站点上、删除与远程主机关联的igroui上的LUN映射。
+

NOTE: 确保igrop不包含未复制LUN的映射。

+
`SiteB::> lun mapping delete -vserver _svm_name_ -igroup _igroup_ -path <>`

. 在主站点上、修改现有主机的启动程序配置、以便为本地集群上的启动程序设置近端路径。
+
`SiteA::> igroup initiator add-proximal-vserver -vserver _svm_name_ -initiator _host_ -proximal-vserver _server_`

. 为新主机添加新的igrop和启动程序、并设置主机与本地站点关联性的主机接近度。启用igrop复制以复制配置并在远程集群上转换主机位置。
+
``
SiteA::> igroup modify -vserver vsA -igroup ig1 -replication-peer vsB
SiteA::> igroup initiator add-proximal-vserver -vserver vsA -initiator host2 -proximal-vserver vsB
``

. 发现主机上的路径、并验证主机是否具有从首选集群到存储LUN的主动/优化路径
. 部署应用程序并在集群之间分布VM工作负载。


.非一致配置的步骤
. 从修改SnapMirror策略 `AutomatedFailover` to `AutomatedFailoverDuplex`：
+
`snapmirror modify -destination-path _destination_path_ -policy AutomatedFailoverDuplex`

. 修改策略将触发重新同步。等待重新同步完成、然后确认此关系为 `Insync`：
+
`snapmirror show -destination-path _destination_path_`

. 如果现有主机是主集群的本地主机、请将该主机添加到第二个集群、并建立与每个集群的相应访问权限的连接。
. 在二级站点上、删除与远程主机关联的igroui上的LUN映射。
+

NOTE: 确保igrop不包含未复制LUN的映射。

+
`SiteB::> lun mapping delete -vserver _svm_name_ -igroup _igroup_ -path <>`

. 在主站点上、修改现有主机的启动程序配置、以便为本地集群上的启动程序设置近端路径。
+
`SiteA::> igroup initiator add-proximal-vserver -vserver _Svm_name_ -initiator _host_ -proximal-vserver _server_`

. 在二级站点上、为新主机添加新的igrop和启动程序、并设置主机与其本地站点关联性的主机邻近度。将LUN映射到igrop。
+
``
SiteB::> igroup create -vserver _svm_name_ -igroup _igroup_name_
SiteB::> igroup add -vserver _svm_name_ -igroup  _igroup_name_ -initiator _host_name_
SiteB::> lun mapping create -igroup  _igroup_name_ -path _path_name_
``

. 发现主机上的路径、并验证主机是否具有从首选集群到存储LUN的主动/优化路径
. 部署应用程序并在集群之间分布VM工作负载。


--
====


== 从对称主动/主动关系转换为非对称关系

如果您已配置对称主动/主动保护、则可以使用ONTAP命令行界面将此关系转换为非对称保护。

.步骤
. 将所有VM工作负载移动到源集群的本地主机。
. 为不管理VM实例的主机删除igrop配置、并修改igrop配置以终止igrop复制。
+
`code`

. 在二级站点上、取消映射LUN。
+
`SiteB::> lun mapping delete -vserver _svm_name_ -igroup _igroup_name_ -path <>`

. 在二级站点上、删除对称主动/主动关系。
+
`SiteB::> snapmirror delete -destination-path _destination_path_`

. 在主站点上、释放对称主动/主动关系。
`SiteA::> snapmirror release -destination-path _destination_path_ -relationship-info-only true`
. 在二级站点中、使用创建与同一组卷的关系 `AutomatedFailover` 策略重新同步此关系。
+
``
SiteB::> snapmirror create -source-path _source_path_ -destination-path _destination_path_ -cg-item-mappings _source:@destination_ -policy AutomatedFailover
SiteB::> snapmirror resync -destination-path vs1:/cg/cg1_dst
``

+

NOTE: 二级站点上的一致性组需要 link:../consistency-groups/delete-task.html["待删除"] 重新创建关系之前。目标卷 link:https://kb.netapp.com/onprem/ontap/dp/SnapMirror/How_to_change_a_volume_type_from_RW_to_DP["必须转换为DP类型"^]。

. 确认关系镜像状态为 `Snapmirrored` 关系状态为 `Insync`。
+
`snapmirror show -destination-path _destination_path_`

. 从主机重新发现路径。

