---
sidebar: sidebar 
permalink: snapmirror-active-sync/convert-active-sync-task.html 
keywords: SM-BC, SMBC, convert, SnapMirror synchronous, existing, snapmirror active sync 
summary: 将SnapMirror关系转换为SnapMirror活动同步。 
---
= 将现有SnapMirror关系转换为SnapMirror活动同步关系
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
如果您已配置SnapMirror保护、则可以将此关系转换为SnapMirror活动同步。从ONTAP 9.15.1开始、您可以转换此关系以使用对称主动/主动保护。



== 将现有的 iSCSI 或 FC SnapMirror关系转换为非对称SnapMirror主动同步关系

如果源集群和目标集群之间已存在 iSCSI 或 FC SnapMirror同步关系，您可以将其转换为非对称SnapMirror主动同步关系。这样，您就可以将镜像卷与一致性组关联，从而确保多卷工作负载的 RPO 为零。此外，如果您需要恢复到建立SnapMirror主动同步关系之前的时间点，您可以保留现有的SnapMirror快照。

.关于此任务
* 您必须是主集群和二级集群上的集群和SVM管理员。
* 您不能通过更改 SnapMirror 策略将零 RPO 转换为零 RTO 同步。
* 在发出之前、必须确保已取消LUN映射 `snapmirror create` 命令：
+
如果已映射二级卷上的现有LUN、则为和 `AutomatedFailover` 策略、即 `snapmirror create` 命令触发错误。



.开始之前
* 主集群和二级集群之间必须存在零RPO SnapMirror同步关系。
* 必须取消映射目标卷上的所有LUN、然后才能创建零RTO SnapMirror关系。
* SnapMirror主动同步仅支持SAN协议(而不支持NFS/CCIFS)。确保未挂载一致性组的任何成分卷以进行 NAS 访问。


.步骤
. 从二级集群中、对现有关系执行SnapMirror更新：
+
`SiteB::>snapmirror update -destination-path vs1_dst:vol1`

. 验证 SnapMirror 更新是否已成功完成：
+
`SiteB::>snapmirror show`

. 暂停每个零RPO同步关系：
+
`SiteB::>snapmirror quiesce -destination-path vs1_dst:vol1`

+
`SiteB::>snapmirror quiesce -destination-path vs1_dst:vol2`

. 删除每个零 RPO 同步关系：
+
`SiteB::>snapmirror delete -destination-path vs1_dst:vol1`

+
`SiteB::>snapmirror delete -destination-path vs1_dst:vol2`

. 释放源SnapMirror关系、但保留通用快照：
+
`SiteA::>snapmirror release -relationship-info-only true -destination-path vs1_dst:vol1`

+
`SiteA::>snapmirror release -relationship-info-only true -destination-path vs1_dst:vol2`

. 创建零RTO SnapMirror同步关系：
+
`SiteB::> snapmirror create -source-path vs1_src:/cg/cg_src -destination-path vs1_dst:/cg/cg_dst -cg-item-mappings vol1:@vol1,vol2:@vol2 -policy AutomatedFailover`

. 重新同步一致性组：
+
`SiteB::> snapmirror resync -destination-path vs1_dst:/cg/cg_dst`

. 重新扫描主机 LUN I/O 路径以还原 LUN 的所有路径。




== 将现有的 iSCSI 或 FC SnapMirror关系转换为对称主动/主动

从ONTAP 9.15.1 开始，您可以将现有的 iSCSI 或 FC SnapMirror关系转换为SnapMirror主动同步对称主动/主动关系。

.开始之前
* 您必须运行ONTAP 9.151或更高版本。
* 主集群和二级集群之间必须存在零RPO SnapMirror同步关系。
* 必须取消映射目标卷上的所有LUN、然后才能创建零RTO SnapMirror关系。
* SnapMirror主动同步仅支持SAN协议(而不支持NFS/CCIFS)。确保未挂载一致性组的任何成分卷以进行 NAS 访问。


.步骤
. 从二级集群中、对现有关系执行SnapMirror更新：
+
`SiteB::>snapmirror update -destination-path vs1_dst:vol1`

. 验证 SnapMirror 更新是否已成功完成：
+
`SiteB::>snapmirror show`

. 暂停每个零RPO同步关系：
+
`SiteB::>snapmirror quiesce -destination-path vs1_dst:vol1`

+
`SiteB::>snapmirror quiesce -destination-path vs1_dst:vol2`

. 删除每个零 RPO 同步关系：
+
`SiteB::>snapmirror delete -destination-path vs1_dst:vol1`

+
`SiteB::>snapmirror delete -destination-path vs1_dst:vol2`

. 释放源SnapMirror关系、但保留通用快照：
+
`SiteA::>snapmirror release -relationship-info-only true -destination-path vs1_dst:vol1`

+
`SiteA::>snapmirror release -relationship-info-only true -destination-path vs1_dst:vol2`

. 使用AutomatedFailover双 工策略创建零RTO SnapMirror同步关系：
+
`SiteB::> snapmirror create -source-path vs1_src:/cg/cg_src -destination-path vs1_dst:/cg/cg_dst -cg-item-mappings vol1:@vol1,vol2:@vol2 -policy AutomatedFailoverDuplex`

. 如果现有主机位于主集群的本地、请将该主机添加到二级集群、并建立与每个集群的相应访问权限的连接。
. 在二级站点上、删除与远程主机关联的igroui上的LUN映射。
+

NOTE: 确保igrop不包含未复制LUN的映射。

+
`SiteB::> lun mapping delete -vserver <svm_name> -igroup <igroup> -path <>`

. 在主站点上、修改现有主机的启动程序配置、以便为本地集群上的启动程序设置近端路径。
+
`SiteA::> igroup initiator add-proximal-vserver -vserver <svm_name> -initiator <host> -proximal-vserver <server>`

. 为新主机添加新的igrop和启动程序、并设置主机与本地站点关联性的主机接近度。启用igrop复制以复制配置并在远程集群上转换主机位置。
+
``
SiteA::> igroup modify -vserver vsA -igroup ig1 -replication-peer vsB
SiteA::> igroup initiator add-proximal-vserver -vserver vsA -initiator host2 -proximal-vserver vsB
``

. 发现主机上的路径、并验证主机是否具有从首选集群到存储LUN的主动/优化路径
. 部署应用程序并在集群之间分布VM工作负载。
. 重新同步一致性组：
+
`SiteB::> snapmirror resync -destination-path vs1_dst:/cg/cg_dst`

. 重新扫描主机 LUN I/O 路径以还原 LUN 的所有路径。


.相关信息
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["SnapMirror 创建"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-delete.html["SnapMirror删除"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-quiesce.html["SnapMirror 静默"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-release.html["SnapMirror 发布"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-resync.html["snapmirror resync"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-show.html["snapmirror show"^]

