---
sidebar: sidebar 
permalink: snapmirror-active-sync/index.html 
keywords: SM-BC, SMBC, failover, terms, benefits, snapmirror active sync, TR-4878 
summary: 使用SnapMirror主动同步保护具有LUN的应用程序、使应用程序能够透明地进行故障转移、从而确保发生灾难时的业务连续性。 
---
= ONTAP中的SnapMirror主动同步概述
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SnapMirror主动同步(也称为SnapMirror业务连续性_[SM-BC]_)支持业务服务即使在站点完全瘫痪的情况下仍可继续运行、从而支持应用程序使用二级副本透明地进行故障转移。使用SnapMirror活动同步触发故障转移无需手动干预或自定义脚本。

从ONTAP 9.9.1开始、AFF集群、纯闪存SAN阵列(ASA)集群和C系列(AFF或ASA)均支持SnapMirror主动同步。主集群和二级集群的类型必须相同：ASA或AFF。SnapMirror主动同步可通过iSCSI或FCP LUN保护应用程序。

从ONTAP 9.151开始，SnapMirror主动同步支持xref:architecture-concept.html[对称主动/主动功能]。对称主动/主动允许通过双向同步复制从受保护LUN的两个副本执行读写I/O操作、以便两个LUN副本都可以在本地处理I/O操作。在ONTAP 9.15.1之前的版本中、SnapMirror主动同步仅支持非对称主动/主动配置、在这种配置中、二级站点上的数据会代理到LUN。从9.16.1 9.161 GA开始、四节点ONTAP集群还支持对称主动/主动。


NOTE: 从2024年7月开始、以前以PDF格式发布的技术报告中的内容已与ONTAP产品文档集成。ONTAP SnapMirror主动同步文档现在包含了_TR-4878：SnapMirror active sync_中的内容。



== 优势

SnapMirror主动同步具有以下优势：

* 为业务关键型应用程序提供持续可用性。
* 能够从主站点和二级站点交替托管关键应用程序。
* 使用一致性组简化应用程序管理、以实现依赖写入顺序的一致性。
* 能够测试每个应用程序的故障转移。
* 即时创建镜像克隆、而不影响应用程序可用性。
* 能够在同一ONTAP集群中部署受保护和非受保护的工作负载。
* LUN标识保持不变、因此应用程序会将其视为共享虚拟设备。
* 能够重复使用二级集群、并灵活地创建即时克隆以供应用程序使用、以用于开发测试、UAT或报告目的、而不会影响应用程序性能或可用性。


SnapMirror主动同步支持您保护数据LUN、从而使应用程序能够透明地进行故障转移、以便在发生灾难时保持业务连续性。有关详细信息，请参见 link:use-cases-concept.html["用例"]。



== 关键概念

SnapMirror主动同步利用一致性组和ONTAP调解器来确保即使在发生灾难的情况下也能复制和提供数据。在规划SnapMirror主动同步部署时、了解SnapMirror主动同步及其架构中的基本概念非常重要。

.不对称和对称
SnapMirror主动同步支持非对称解决方案、并且从ONTAP 9.15.1开始支持对称主动/主动解决方案。这些选项是指主机如何访问存储路径和写入数据。在非对称配置中、二级站点上的数据会代理到LUN。在对称主动/主动配置中、两个站点均可访问本地存储以执行活动I/O

对称主动/主动已针对集群应用程序进行了优化、包括VMware VMSC、采用SQL的Windows故障转移集群和Oracle RAC。

有关详细信息，请参见 xref:architecture-concept.html[SnapMirror主动同步架构]。

.一致性组
答 link:../consistency-groups/index.html["一致性组"] 是一组FlexVol卷、可为必须受到保护才能实现业务连续性的应用程序工作负载提供一致性保证。

一致性组的目的是同时为多个卷创建Snapshot映像、从而确保在某个时间点为一组卷创建崩溃状态一致的副本。一致性组可确保数据集的所有卷先处于静音状态、然后在完全相同的时间点进行对等。这样可以在支持数据集的卷之间提供数据一致的还原点。因此、一致性组可以保持依赖写入顺序的一致性。如果您决定保护应用程序以实现业务连续性、则必须将与此应用程序对应的一组卷添加到一致性组中、以便在源一致性组和目标一致性组之间建立数据保护关系。源和目标一致性必须包含相同数量和类型的卷。

.成分卷
在SnapMirror活动同步关系中受保护的一致性组中的单个卷或LUN。

.ONTAP 调解器
。 link:../mediator/index.html["ONTAP 调解器"] 接收有关对等ONTAP集群和节点的运行状况信息、在这两个集群之间进行编排、并确定每个节点/集群是否运行正常。ONTAP调解器可提供有关以下内容的运行状况信息：

* 对等ONTAP集群
* 对等ONTAP集群节点
* 一致性组(用于定义SnapMirror活动同步关系中的故障转移单元)；对于每个一致性组、将提供以下信息：
+
** 复制状态：未初始化、同步或不同步
** 哪个集群托管主副本
** 操作上下文(用于计划内故障转移)




利用此ONTAP调解器运行状况信息、集群可以区分不同类型的故障、并确定是否执行自动故障转移。ONTAP调解器是SnapMirror活动同步仲裁以及两个ONTAP集群(主集群和二级集群)中的三方之一。要达成协商一致意见，法定人数中至少有两个当事方必须同意某项行动。


NOTE: 从ONTAP 9.15.1开始、System Manager将显示任一集群的SnapMirror活动同步关系的状态。您还可以从System Manager中的任一集群监控ONTAP调解器的状态。在早期版本的ONTAP中、System Manager会显示源集群中SnapMirror活动同步关系的状态。

.计划内故障转移
用于更改SnapMirror活动同步关系中副本角色的手动操作。主站点将成为二级站点、而二级站点将成为主站点。

.主要-优先和主要偏倚
SnapMirror主动同步采用主优先原则、在网络分区情况下、优先使用主副本来提供I/O。

主偏置是一种特殊的仲裁实施方式、可提高受SnapMirror活动同步保护的数据集的可用性。如果主副本可用、则当无法从两个集群访问ONTAP调解器时、主偏置将生效。

从ONTAP 9.15.1开始、SnapMirror主动同步支持主优先级和主优先级偏差。主副本在System Manager中指定、并通过REST API和命令行界面输出。

.自动计划外故障转移(AUTOFO)
对镜像副本执行故障转移的自动操作。此操作需要ONTAP调解器的帮助才能检测到主副本不可用。

.不同步(OOS)
如果应用程序I/O未复制到二级存储系统，则会报告为**不同步**。不同步状态表示二级卷未与主卷(源卷)同步、并且未进行SnapMirror复制。

如果镜像状态为 `Snapmirrored`，表示传输失败或由于操作不受支持而失败。

SnapMirror主动同步支持自动重新同步、使副本能够返回到InSync状态。

从ONTAP 9.15.1开始、SnapMirror主动同步支持 link:interoperability-reference.html#fan-out-configurations["在扇出配置中自动重新配置"]。

.统一和非统一配置
* **统一主机访问**表示两个站点的主机都连接到两个站点上存储集群的所有路径。跨站点路径会跨越多个距离。
* **非统一主机访问**表示每个站点中的主机仅连接到同一站点中的集群。跨站点路径和延伸型路径未连接。



NOTE: 任何SnapMirror主动同步部署均支持统一主机访问；只有对称主动/主动部署才支持非统一主机访问。

.零RPO
RPO表示恢复点目标、即在给定时间段内视为可接受的数据丢失量。零RPO表示不允许丢失任何数据。

.零RTO
RTO表示恢复时间目标、是指在发生中断、故障或其他数据丢失事件后、应用程序可以无中断地恢复正常运行的时间量。RTO为零表示任何停机时间都不可接受。
