---
sidebar: sidebar 
permalink: snapmirror-active-sync/monitor-task.html 
keywords: SM-BC, SMBC, monitoring, Mediator status, EMS, errors, planned failover status, automatic unplanned failover status, , snapmirror active sync 
summary: 您可以监控多个SnapMirror活动同步组件和操作。 
---
= 监控ONTAP中的SnapMirror活动同步操作
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以监控以下SnapMirror活动同步操作、以确保SnapMirror活动同步配置的运行状况：

* ONTAP 调解器
* 计划内故障转移操作
* 自动计划外故障转移操作
* SnapMirror活动同步可用性



NOTE: 从ONTAP 9.15.1开始、System Manager将显示任一集群的SnapMirror活动同步关系的状态。您还可以从System Manager中的任一集群监控ONTAP调解器的状态。



== ONTAP 调解器

在正常操作期间、ONTAP调解器状态应为已连接。如果它处于任何其他状态、则可能表示出现错误情况。您可以查看 link:https://docs.netapp.com/us-en/ontap-ems-9131/sm-mediator-events.html["事件管理系统(EMS)消息"^] 确定错误并采取适当的更正操作。



== 计划内故障转移操作

您可以使用监控计划内故障转移操作的状态和进度 `snapmirror failover show` 命令：例如：

....
ClusterB::> snapmirror failover start -destination-path vs1:/cg/dcg1
....
故障转移操作完成后、您可以从新的目标集群监控SnapMirror保护状态。例如：

....
ClusterA::> snapmirror show
....
请参见 link:https://docs.netapp.com/us-en/ontap-ems-9131/smbc-pfo-events.html["EMS参考"^] 了解事件消息和更正操作。



== 自动计划外故障转移操作

在计划外自动故障转移期间、您可以使用监控操作状态 `snapmirror failover show` 命令：

....
ClusterB::> snapmirror failover show -instance
Start Time: 9/23/2020 22:03:29
         Source Path: vs1:/cg/scg3
    Destination Path: vs3:/cg/dcg3
     Failover Status: completed
        Error Reason:
            End Time: 9/23/2020 22:03:30
Primary Data Cluster: cluster-2
Last Progress Update: -
       Failover Type: unplanned
  Error Reason codes: -
....
请参见 link:https://docs.netapp.com/us-en/ontap-ems-9131/smbc-aufo-events.html["EMS参考"^] 了解事件消息和更正操作。



== SnapMirror活动同步可用性

您可以在主集群、二级集群或这两者上使用一系列命令来检查SnapMirror活动同步关系的可用性。

您使用的命令包括 `snapmirror mediator show` 在主集群和二级集群上运行命令以检查连接和仲裁状态、即 `snapmirror show` 命令和 `volume show` 命令：例如：

....
SMBC_A::*> snapmirror mediator show
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
10.236.172.86    SMBC_B           connected         true

SMBC_B::*> snapmirror mediator show
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
10.236.172.86    SMBC_A           connected         true

SMBC_B::*> snapmirror show -expand
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vs0:/cg/cg1 XDP  vs1:/cg/cg1_dp Snapmirrored Insync -         true    -
vs0:vol1    XDP  vs1:vol1_dp  Snapmirrored Insync   -         true    -
2 entries were displayed.

SMBC_A::*> volume show -fields is-smbc-master,smbc-consensus,is-smbc-failover-capable -volume vol1
vserver volume is-smbc-master is-smbc-failover-capable smbc-consensus
------- ------ -------------- ------------------------ --------------
vs0     vol1   true           false                    Consensus

SMBC_B::*> volume show -fields is-smbc-master,smbc-consensus,is-smbc-failover-capable -volume vol1_dp
vserver volume  is-smbc-master is-smbc-failover-capable smbc-consensus
------- ------- -------------- ------------------------ --------------
vs1     vol1_dp false          true                     No-consensus
....