---
sidebar: sidebar 
permalink: snapmirror-active-sync/protect-task.html 
keywords: SM-BC, snapmirror business continuity, consistency group, remote protection, destination, scsi, nvme 
summary: 为业务连续性配置保护涉及选择 ONTAP 源集群上的 LUN 并将其添加到一致性组。 
---
= 使用ONTAP SnapMirror主动同步进行保护
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SnapMirror主动同步可提供非对称保护、从ONTAP 9.15.1开始、还可提供对称主动/主动保护。



== 配置非对称保护

使用SnapMirror活动同步配置非对称保护涉及在ONTAP源集群上选择LUN并将其添加到一致性组。

.开始之前
* 您必须具有SnapMirror同步许可证。
* 您必须是集群或 Storage VM 管理员。
* 一致性组中的所有成分卷都必须位于一个Storage VM (SVM)中。
+
** LUN 可以驻留在不同的卷上。


* 源集群和目标集群不能相同。
* 您不能在ASA集群和非ASA集群之间建立SnapMirror活动同步一致性组关系。
* 对于集群对等关系、SnapMirror活动同步需要默认IP空间。不支持自定义 IP 空间。
* 一致性组的名称必须是唯一的。
* 二级(目标)集群上的卷类型必须为DP。
* 主SVM和二级SVM必须处于对等关系中。


.步骤
您可以使用ONTAP命令行界面或系统管理器配置一致性组。

从ONTAP 9.10.1 开始， ONTAP在 System Manager 中提供了一致性组端点和菜单，从而提供了额外的管理实用程序。如果您使用的是ONTAP 9.10.1 或更高版本，请参阅link:../consistency-groups/configure-task.html["配置一致性组"]然后link:../consistency-groups/protect-task.html["配置保护"]创建SnapMirror主动同步关系。


IMPORTANT: 从ONTAP 9.8到9.14.1、SnapMirror主动同步称为SnapMirror业务连续性(SM-BC)。

[role="tabbed-block"]
====
.System Manager
--
. 在主集群上、导航到*保护>概述>保护以实现业务连续性>保护LUN*。
. 选择要保护的LUN并将其添加到保护组。
. 选择目标集群和 SVM 。
. 默认情况下会选中 * 初始化关系 * 。单击 * 保存 * 开始保护。
. 转至 * 信息板 > 性能 * 以验证 LUN 的 IOPS 活动。
. 在目标集群上，使用 System Manager 验证对业务连续性关系的保护是否同步： * 保护 > 关系 * 。


--
.命令行界面
--
. 从目标集群创建一致性组关系。
`destination::> snapmirror create -source-path _source-path_ -destination-path _destination-path_ -cg-item-mappings _volume-paths_ -policy _policy-name_`
+
您最多可以使用映射12个成分卷 `cg-item-mappings` 参数 `snapmirror create` 命令：

+
以下示例将创建两个一致性组： `cg_src_ on the source with `vol1` 和 `vol2` 和镜像目标一致性组、 `cg_dst`。

+
`destination::> snapmirror create -source-path vs1_src:/cg/cg_src -destination-path vs1_dst:/cg/cg_dst -cg-item-mappings vol_src1:@vol_dst1,vol_src2:@vol_dst2 -policy AutomatedFailOver`

. 从目标集群中、初始化一致性组。
+
`destination::>snapmirror initialize -destination-path _destination-consistency-group_`

. 确认初始化操作已成功完成。状态应为 `InSync`。
+
`snapmirror show`

. 在每个集群上、创建一个igrop、以便将LUN映射到应用程序主机上的启动程序。
`lun igroup create -igroup _name_ -protocol _fcp|iscsi_ -ostype _os_ -initiator _initiator_name_`
+
有关的详细信息 `lun igroup create`，请参见link:https://docs.netapp.com/us-en/ontap-cli/lun-igroup-create.html["ONTAP 命令参考"^]。

. 在每个集群上、将LUN映射到igrop：
+
`lun map -path _path_name_ -igroup _igroup_name_`

. 使用验证LUN映射是否已成功完成 `lun map` 命令：然后、您可以在应用程序主机上发现新的LUN。


--
====


== 配置对称主动/主动保护

您可以使用System Manager或ONTAP命令行界面建立对称保护。在这两个界面中、的步骤不同 xref:index.html#key-concepts[统一和非统一配置]。

.开始之前
* 两个集群都必须运行ONTAP 9.151或更高版本。
* 对称主动/主动配置需要 `AutomatedFailoverDuplex` 保护策略。或者、您也可以 xref:../data-protection/create-custom-replication-policy-concept.html[创建自定义SnapMirror策略] 提供了 `-type` 为 `automated-failover-duplex`。
* 在ONTAP 9.15.1中、只有双节点集群才支持对称主动/主动。
* 从9.16.1 9.161 GA开始、SnapMirror主动同步支持在四节点集群上采用对称主动/主动配置。
+
** 要在四节点集群上使用SnapMirror主动同步、您必须运行9.16.1 9.161 GA或更高版本。
** 在部署四节点配置之前，您必须xref:../peering/create-cluster-relationship-93-later-task.adoc[创建集群对等关系]。
** 查看xref:limits-reference.adoc[限制]四节点集群的。
** 如果要还原到双节点集群、则必须在还原之前从此集群中删除SnapMirror活动同步关系。
** 您可以使用四节点配置升级存储和控制器。此过程不会造成系统中断、并会在将卷移至新节点时扩展集群。有关详细信息，请参见 link:upgrade-revert-task.html#refresh-a-cluster["刷新集群"]。


* 从ONTAP 9.17.1 开始，仅当两个集群都运行ONTAP 9.17.1 或更高版本时，您才能在 NVMe 命名空间上配置对称主动/主动保护。




== 使用 SCSI SnapMirror主动同步配置来配置对称主动/主动保护

.步骤
您可以使用 System Manager 或ONTAP CLI 通过 SCSI 协议主机映射配置对称主动/主动保护。

[role="tabbed-block"]
====
.System Manager
--
.统一配置的步骤
. 在主站点上、 link:../consistency-groups/configure-task.html#create-a-consistency-group-with-new-luns-or-volumes["使用新LUN创建一致性组。"^]
+
.. 创建一致性组时、请指定主机启动程序以创建igroGroup。
.. 选中“**启用SnapMirror”复选框，然后选择 `AutomatedFailoverDuplex` 策略。
.. 在显示的对话框中，选中**复制启动程序组**复选框以复制igroGroup。在**编辑邻近设置**中，为主机设置近端SVM。
.. 选择**保存**。




.非一致配置的步骤
. 在主站点上、 link:../consistency-groups/configure-task.html#create-a-consistency-group-with-new-luns-or-volumes["使用新LUN创建一致性组。"^]
+
.. 创建一致性组时、请指定主机启动程序以创建igroGroup。
.. 选中“**启用SnapMirror”复选框，然后选择 `AutomatedFailoverDuplex` 策略。
.. 选择**保存**以创建LUN、一致性组、igroup、SnapMirror关系和igroup映射。


. 在二级站点上、创建一个igrop并映射LUN。
+
.. 导航到**主机**>** SAN启动程序组**。
.. 选择**+Add**以创建新的igroup。
.. 提供**名称**，选择**主机操作系统**，然后选择**启动程序组成员**。
.. 选择**保存**以初始化关系。


. 将新igrop映射到目标LUN。
+
.. 导航到**存储**>** LUN **。
.. 选择要映射到此igrop的所有LUN。
.. 选择**更多**，然后选择**映射到启动程序组**。




--
.命令行界面
--
.统一配置的步骤
. 创建一个新的SnapMirror关系、对应用程序中的所有卷进行分组。请确保指定 `AutomatedFailOverDuplex` 用于建立双向同步复制的策略。
+
`snapmirror create -source-path <source_path> -destination-path <destination_path> -cg-item-mappings <source_volume:@destination_volume> -policy AutomatedFailOverDuplex`

. 初始化SnapMirror关系：
`snapmirror initialize -destination-path <destination-consistency-group>`
. 等待以确认操作已成功 `Mirrored State` 以显示为 `SnapMirrored` 和 `Relationship Status` 作为 `Insync`。
+
`snapmirror show -destination-path <destination_path>`

. 在主机上、根据需要配置主机连接并访问每个集群。
. 建立igrop配置。为本地集群上的启动程序设置首选路径。指定将配置复制到对等集群的选项以实现反向相关性。
+
`SiteA::> igroup create -vserver <svm_name> -ostype <os_type> -igroup <igroup_name> -replication-peer <peer_svm_name> -initiator <host>`

+

NOTE: 从ONTAP 9.161开始、请在此命令中使用 `-proximal-vserver local`参数。

+
`SiteA::> igroup add -vserver <svm_name> -igroup <igroup_name> -ostype <os_type> -initiator <host>`

+

NOTE: 从ONTAP 9.161开始、请在此命令中使用 `-proximal-vserver peer`参数。

. 从主机中、发现路径、并验证主机是否具有从首选集群到存储LUN的主动/优化路径。
. 部署应用程序并在集群之间分布VM工作负载、以实现所需的负载平衡。


.非一致配置的步骤
. 创建一个新的SnapMirror关系、对应用程序中的所有卷进行分组。请确保指定 `AutomatedFailOverDuplex` 用于建立双向同步复制的策略。
+
`snapmirror create -source-path <source_path> -destination-path <destination_path> -cg-item-mappings <source_volume:@destination_volume> -policy AutomatedFailOverDuplex`

. 初始化SnapMirror关系：
`snapmirror initialize -destination-path <destination-consistency-group>`
. 等待以确认操作已成功 `Mirrored State` 以显示为 `SnapMirrored` 和 `Relationship Status` 作为 `Insync`。
+
`snapmirror show -destination-path <destination_path>`

. 在主机上、根据需要配置主机连接并访问每个集群。
. 在源集群和目标集群上建立igrop配置。
+
`# primary site
SiteA::> igroup create -vserver <svm_name> -igroup <igroup_name> -initiator <host_1_name_>`

+
`# secondary site
SiteB::> igroup create -vserver <svm_name> -igroup <igroup_name> -initiator <host_2_name>`

. 从主机中、发现路径、并验证主机是否具有从首选集群到存储LUN的主动/优化路径。
. 部署应用程序并在集群之间分布VM工作负载、以实现所需的负载平衡。


--
====


== 使用 NVMe SnapMirror主动同步配置来配置对称主动/主动保护

.开始之前
除了配置对称主动/主动保护的要求之外，您还应该注意使用 NVMe 协议时支持和不支持的配置。

* 一致性组可以有一个或多个子系统。
* 一致性组内的卷可以具有来自多个子系统的命名空间映射。
* 子系统不能具有属于多个一致性组的命名空间映射。
* 子系统不能具有一些属于一致性组的命名空间映射和一些不属于一致性组的命名空间映射。
* 子系统必须具有属于同一一致性组的命名空间映射。


.步骤
从ONTAP 9.17.1 开始，您可以使用 System Manager 或ONTAP CLI 创建一致性组并使用 NVMe 协议主机映射配置对称主动/主动保护。

[role="tabbed-block"]
====
.System Manager
--
. 在主站点上， link:../consistency-groups/configure-task.html#create-a-consistency-group-with-new-luns-or-volumes["使用新卷或 NVMe 命名空间创建一致性组。"^]
. 选择 *+添加* 并选择 *使用新的 NVMe 命名空间*。
. 输入一致性组名称。
. 选择*更多*。
. 在“保护”部分中，选择“启用SnapMirror”，然后选择 `AutomatedFailoverDuplex`政策。
. 在 *主机映射* 部分中，选择 *现有 NVMe 子系统* 或 *新 NVMe 子系统*。
. 选择“邻近”可更改近端 SVM。默认选择源 SVM。
. 如果需要，添加另一个 NVMe 子系统。


--
.命令行界面
--
. 创建新的SnapMirror关系，将所有包含应用程序使用的所有 NVMe 命名空间的卷分组。确保指定 `AutomatedFailOverDuplex`建立双向同步复制的策略。
+
`snapmirror create -source-path <source_path> -destination-path <destination_path> -cg-item-mappings <source_volume:@destination_volume> -policy AutomatedFailOverDuplex`

+
示例

+
[listing]
----
DST::> snapmirror create -source-path vs_src:/cg/cg_src_1 -destination-path vs_dst:/cg/cg_dst_1 -cg-item-mappings vs_src_vol1:@vs_dst_vol1,vs_src_vol2:@vs_dst_vol2 -policy AutomatedFailOverDuplex
----
. 初始化SnapMirror关系：
`snapmirror initialize -destination-path <destination-consistency-group>`
+
示例

+
[listing]
----
DST::> snapmirror initialize -destination-path vs1:/cg/cg_dst_1
----
. 等待以确认操作已成功 `Mirrored State` 以显示为 `SnapMirrored` 和 `Relationship Status` 作为 `Insync`。
+
`snapmirror show -destination-path <destination_path>`

+
与主卷中的 NVMe 命名空间关联的 NVMe 子系统会自动复制到辅助集群。

. 在主机上、根据需要配置主机连接并访问每个集群。
. 指定与每个主机最接近的 SVM。这样，主机就可以使用首选集群中的路径访问 NVMe 命名空间。这可能是主集群中的 SVM，也可能是 DR 集群中的 SVM。
+
以下命令表示SVM VS_A距离主机H1较近，并将VS_A设置为近端SVM：

+
`SiteA::> vserver nvme subsystem host add -subsystem ss1 -host-nqn <H1_NQN> -proximal-vservers <VS_A>`

+
以下命令表示 SVM VS_B 距离主机 H2 较近，并将 VS_B 设置为近端 SVM：

+
`SiteB::> vserver nvme subsystem host add -subsystem ss1 -host-nqn <H2_NQN> -proximal-vservers <VS_B>`

. 从主机发现路径并验证主机是否具有从首选集群到存储的活动/优化路径。
. 部署应用程序并在集群之间分布VM工作负载、以实现所需的负载平衡。


--
====
.相关信息
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["SnapMirror 创建"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-initialize.html["SnapMirror 初始化"^]

