---
sidebar: sidebar 
permalink: snapmirror-active-sync/upgrade-revert-task.html 
keywords: upgrade, revert, snapmirror active sync, SMBC, SM-BC 
summary: 升级或还原ONTAP会影响您的SnapMirror活动同步关系、尤其是在迁移到ONTAP 9.9.1或更高版本或者9.7及更早版本时。 
---
= 使用SnapMirror活动同步升级和还原ONTAP
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
从ONTAP 9.9.1开始、支持SnapMirror主动同步。升级和还原ONTAP集群会影响SnapMirror活动同步关系、具体取决于要升级或还原到的ONTAP版本。



== 使用SnapMirror活动同步升级ONTAP

要使用SnapMirror主动同步、源集群和目标集群上的所有节点都必须运行ONTAP 9.9.1或更高版本。

在升级具有活动SnapMirror活动同步关系的ONTAP时、应使用 xref:../upgrade/automated-upgrade-task.html[自动化无中断升级(ANDU)]。使用ANDU可确保您的SnapMirror活动同步关系在升级过程中保持同步且运行状况良好。

没有为ONTAP升级准备SnapMirror活动同步部署的配置步骤。但是、建议您在升级前后检查：

* SnapMirror活动同步关系处于同步状态。
* 事件日志中没有与SnapMirror相关的错误。
* 调解器在两个集群中均处于联机状态且运行状况良好。
* 所有主机均可正确查看所有路径以保护LUN。



NOTE: 将集群从ONTAP 9.9.1或9.9.1升级到ONTAP 9.10.1及更高版本时、ONTAP会创建新的 xref:../consistency-groups/index.html[一致性组] 可使用System Manager配置的SnapMirror活动同步关系的源集群和目标集群上。


NOTE: 。 `snapmirror quiesce` 和 `snampirror resume` SnapMirror活动同步不支持命令。



== 从ONTAP 9.10.1还原到ONTAP 9.9.1

要将关系从9.10.1还原到9.9.1、必须先删除SnapMirror活动同步关系、然后再删除9.10.1一致性组实例。无法删除具有活动SnapMirror活动同步关系的一致性组。在 9.9.1 或更早版本中升级到 9.10.1 且先前与另一个智能容器或企业应用程序关联的任何 FlexVol 卷将在还原时不再关联。删除一致性组不会删除成分卷或卷粒度快照。请参见 link:../consistency-groups/delete-task.html["删除一致性组"] 有关ONTAP 9.10.1及更高版本中此任务的详细信息、请参见。



== 从ONTAP 9.9.1还原


NOTE: 混合ONTAP集群不支持SnapMirror活动同步、因为其中包含的版本早于ONTAP 9.9.1。

从ONTAP 9.9.1还原到ONTAP的早期版本时、必须注意以下事项：

* 如果集群托管SnapMirror活动同步目标、则在中断并删除关系之前、不允许还原到ONTAP 9.8或更早版本。
* 如果集群托管SnapMirror活动同步源、则在释放此关系之前、不允许还原到ONTAP 9.8或更早版本。
* 还原到ONTAP 9.8或更早版本之前、必须删除用户创建的所有自定义SnapMirror活动同步策略。


要满足这些要求、请参见 link:remove-configuration-task.html["删除SnapMirror活动同步配置"]。

.步骤
. 从SnapMirror活动同步关系中的一个集群输入以下命令、确认您已准备好还原：
+
`cluster::> system node revert-to -version 9.7 -check-only`

+
以下示例输出显示了尚未准备好还原的集群、并提供了清理说明。

+
[listing]
----
cluster::> system node revert-to -version 9.7 -check-only
Error: command failed: The revert check phase failed. The following issues must be resolved before revert can be completed. Bring the data LIFs down on running vservers. Command to list the running vservers: vserver show -admin-state running Command to list the data LIFs that are up: network interface show -role data -status-admin up Command to bring all data LIFs down: network interface modify {-role data} -status-admin down
Disable snapshot policies.
    Command to list snapshot policies: "snapshot policy show".
    Command to disable snapshot policies: "snapshot policy modify -vserver
   * -enabled false"

   Break off the initialized online data-protection (DP) volumes and delete
   Uninitialized online data-protection (DP) volumes present on the local
   node.
    Command to list all online data-protection volumes on the local node:
   volume show -type DP -state online -node <local-node-name>
    Before breaking off the initialized online data-protection volumes,
   quiesce and abort transfers on associated SnapMirror relationships and
   wait for the Relationship Status to be Quiesced.
    Command to quiesce a SnapMirror relationship: snapmirror quiesce
    Command to abort transfers on a SnapMirror relationship: snapmirror
   abort
    Command to see if the Relationship Status of a SnapMirror relationship
   is Quiesced: snapmirror show
    Command to break off a data-protection volume: snapmirror break
    Command to break off a data-protection volume which is the destination
   of a SnapMirror relationship with a policy of type "vault": snapmirror
   break -delete-snapshots
    Uninitialized data-protection volumes are reported by the "snapmirror
   break" command when applied on a DP volume.
    Command to delete volume: volume delete

   Delete current version snapshots in advanced privilege level.
    Command to list snapshots: "snapshot show -fs-version 9.9.1"
    Command to delete snapshots: "snapshot prepare-for-revert -node
   <nodename>"

   Delete all user-created policies of the type active-strict-sync-mirror
   and active-sync-mirror.
   The command to see all active-strict-sync-mirror and active-sync-mirror
   type policies is:
    snapmirror policy show -type
   active-strict-sync-mirror,active-sync-mirror
   The command to delete a policy is :
    snapmirror policy delete -vserver <SVM-name> -policy <policy-name>
----
. 满足还原检查的要求后、请参见 link:../revert/index.html["还原 ONTAP"]。

