---
sidebar: sidebar 
permalink: snapmirror-active-sync/use-cases-concept.html 
keywords: SM-BC, SMBC, overview, benefits, use cases, architecture, snapmirror active sync 
summary: 使用SnapMirror主动同步保护具有LUN的应用程序、使应用程序能够透明地进行故障转移、从而确保发生灾难时的业务连续性。 
---
= ONTAP SnapMirror主动同步的用例
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
全球互联业务环境的需求要求快速恢复业务关键型应用程序数据、在发生网络攻击、断电或自然灾难等中断时不会丢失任何数据。金融等领域以及遵守《一般数据保护条例》(GDPR)等法规要求的领域、这些要求都更加严苛。

SnapMirror主动同步提供了以下使用情形：

.零恢复时间目标(RTO)的应用程序部署
在SnapMirror主动同步部署中，您有一个主集群和一个辅助集群。主集群中的 LUN  `L1P` ) 有一面镜子 `L1S` )；两个 LUN 共享相同的序列号，并向主机报告为读写 LUN。然而，在非对称配置中，读写操作仅对主 LUN 进行。  `L1P` .任何写入镜像 `L1S`由代理提供服务。

.零RTO或透明应用程序故障转移(TAF)的应用程序部署
TAF 基于主机 MPIO 软件的路径故障转移，以实现对存储的无中断访问。两个 LUN 副本（例如，主卷 (L1P) 和镜像副本 (L1S)）具有相同的标识（序列号），并向主机报告为可读写。然而，在非对称配置中，读写操作仅由主卷提供。发送到镜像副本的 I/O 会被代理到主副本。根据非对称逻辑单元访问 (ALUA) 的访问状态“主动优化”(A/O)，主机到 L1 的首选路径是 VS1:N1。ONTAP调解ONTAP是部署的一部分，主要用于在主卷发生存储中断时执行故障转移（计划内或计划外）。

TAF 有两种运行模式：自动故障转移和自动故障转移双工。在自动故障转移模式下，读写操作仅由主卷处理，因此发送到镜像副本（镜像副本无法自行处理写入操作）的 IO 会被代理到主副本。在自动故障转移双工模式下，主副本和辅助副本均可处理 IO，因此无需代理。

如果您使用 NVMe 通过ONTAP 9.17.1 进行主机访问，则仅支持自动故障转移双工。

SnapMirror主动同步使用ALOA机制、该机制允许应用程序主机多路径软件使用通过优先级和访问可用性公布的路径与存储阵列进行通信。AUA会将指向LUN所属控制器的活动优化路径以及其他路径标记为活动非优化路径、只有在主路径发生故障时才会使用。

采用 NVMe 协议的SnapMirror主动同步使用 ANA，这使得应用程序主机能够发现通往受保护的 NVMe 命名空间的优化路径和非优化路径。ONTAPONTAP目标会发布相应的路径状态，以使应用程序主机能够使用受保护 NVMe 命名空间的最佳路径。

.集群应用程序
集群应用程序(包括VMware Metro Storage Cluster、Oracle RAC和使用SQL的Windows故障转移集群)需要同时访问、以便VM可以故障转移到其他站点、而不会产生任何性能开销。SnapMirror主动同步对称主动/主动通过双向复制在本地提供IO、以满足集群应用程序的要求。从ONTAP 9.16.1开始、四节点集群配置支持对称主动/主动、这是在ONTAP 9.15.1中双节点集群限制的范围内扩展的。

.灾难情形
在地理位置分散的站点之间同步复制应用程序的多个卷。主系统发生中断时、您可以自动故障转移到二级副本、从而为第一层应用程序实现业务连续性。当托管主集群的站点发生灾难时、主机多路径软件会将通过集群的所有路径标记为已关闭、并使用二级集群的路径。这样、ONTAP调解器就会对镜像副本启用无中断故障转移。

.Windows故障转移
SnapMirror主动同步通过易于使用的应用程序级粒度和自动故障转移提供灵活性。SnapMirror主动同步可通过IP网络使用经验证的SnapMirror同步复制功能、通过LAN或WAN高速复制数据、从而在虚拟和物理环境中为Oracle、Microsoft SQL Server等业务关键型应用程序实现高数据可用性和快速数据复制。

通过将TAF复制到二级副本、SnapMirror主动同步功能可以使任务关键型业务服务即使在站点完全瘫痪时也能继续运行。触发此故障转移无需手动干预或执行其他脚本。
