---
permalink: smb-hyper-v-sql/continuously-available-share-hyper-v-concept.html 
sidebar: sidebar 
keywords: share, requirements, continuously, share, consideration, hyper, v, smb, nondiruptive, operation 
summary: 在为支持无中断运行的基于 SMB 的 Hyper-V 配置配置配置持续可用的共享时，您需要了解某些要求和注意事项。 
---
= 基于 SMB 的 Hyper-V 的持续可用共享要求和注意事项
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在为支持无中断运行的基于 SMB 的 Hyper-V 配置配置配置持续可用的共享时，您需要了解某些要求和注意事项。



== 共享要求

* 应用程序服务器使用的共享必须配置为具有持续可用属性集。
+
连接到持续可用共享的应用程序服务器会收到永久性句柄，使其能够无中断地重新连接到 SMB 共享，并在发生接管，交还和聚合重新定位等中断事件后回收文件锁定。

* 如果要使用启用了 VSS 的远程备份服务，则不能将 Hyper-V 文件放入包含接合的共享中。
+
在自动恢复情形下，如果在遍历共享时遇到接合，则卷影副本创建将失败。在非自动恢复情况下，卷影副本创建不会失败，但接合不会指向任何内容。

* 如果要将启用了 VSS 的远程备份服务与自动恢复结合使用，则不能将 Hyper-V 文件置于包含以下内容的共享中：
+
** 符号链接，硬链接或 Widelink
** 非常规文件
+
如果共享中存在指向卷影副本的任何链接或非常规文件，则卷影副本创建将失败。此要求仅支持具有自动恢复功能的适用场景卷影副本。

** 要成功执行卷影复制操作，卷上必须有足够的可用空间（仅适用于基于 SMB 的 Hyper-V ）。
+
可用空间必须至少与卷影副本备份集中包含的共享中的所有文件，目录和子目录所使用的总空间相同。此要求仅支持具有自动恢复功能的适用场景卷影副本。



* 不得在应用程序服务器使用的持续可用共享上设置以下共享属性：
+
** 主目录
** 属性缓存
** BranchCache
** 基于访问的枚举






== 注意事项

* 持续可用的共享支持配额。
* 基于 SMB 的 Hyper-V 配置不支持以下功能：
+
** 审核
** fpolicy


* 不会对 `continuous-availability` 参数设置为 `Yes` 的 SMB 共享执行病毒扫描。

