---
permalink: smb-hyper-v-sql/display-open-smb-files-task.html 
sidebar: sidebar 
keywords: display, information, open, smb, file, session, id, nondisruptive, protection, level 
summary: 您可以显示有关打开的 SMB 文件的信息，包括 SMB 连接和会话 ID ，托管卷，共享名称和共享路径。您还可以显示有关文件的持续可用保护级别的信息，这有助于确定打开的文件是否处于支持无中断操作的状态。 
---
= 显示有关打开的 SMB 文件的信息
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以显示有关打开的 SMB 文件的信息，包括 SMB 连接和会话 ID ，托管卷，共享名称和共享路径。您还可以显示有关文件的持续可用保护级别的信息，这有助于确定打开的文件是否处于支持无中断操作的状态。

.关于此任务
您可以显示有关已建立的 SMB 会话上打开的文件的信息。如果需要确定 SMB 会话中特定文件的 SMB 会话信息，则显示的信息非常有用。

例如、如果您有一个SMB会话、其中一些打开的文件已打开且具有持续可用的保护、而另一些文件未打开且具有持续可用的保护(的值 `-continuously-available` 字段输入 `vserver cifs session show` 命令输出为 `Partial`)、则可以使用此命令确定哪些文件不持续可用。

您可以使用以摘要形式显示Storage Virtual Machine (SVM)上已建立的SMB会话上的所有打开文件的信息 `vserver cifs session file show` 命令、而不带任何可选参数。

但是，在许多情况下，返回的输出量很大。您可以通过指定可选参数来自定义输出中显示的信息。如果您只想查看一小部分打开文件的信息，这将非常有用。

* 您可以使用可选 `-fields` 用于显示所选字段的输出的参数。
+
您可以单独使用此参数，也可以与其他可选参数结合使用。

* 您可以使用 `-instance` 用于显示有关打开的SMB文件的详细信息的参数。
+
您可以单独使用此参数，也可以与其他可选参数结合使用。



.步骤
. 执行以下操作之一：
+
|===
| 如果要显示打开的 SMB 文件 ... | 输入以下命令 ... 


 a| 
以摘要形式显示在 SVM 上
 a| 
`*vserver cifs session file show -vserver _vserver_name_*`



 a| 
在指定节点上
 a| 
`*vserver cifs session file show -vserver _vserver_name_ -node {node_name|local}*`



 a| 
指定的文件 ID
 a| 
`*vserver cifs session file show -vserver _vserver_name_ -file-id integer*`



 a| 
指定的 SMB 连接 ID
 a| 
`*vserver cifs session file show -vserver _vserver_name_ -connection-id integer*`



 a| 
指定的 SMB 会话 ID
 a| 
`*vserver cifs session file show -vserver _vserver_name_ -session-id integer*`



 a| 
在指定的托管聚合上
 a| 
`*vserver cifs session file show -vserver _vserver_name_ -hosting-aggregate _aggregate_name_*`



 a| 
在指定卷上
 a| 
`*vserver cifs session file show -vserver _vserver_name_ -hosting-volume _volume_name_*`



 a| 
指定的 SMB 共享上
 a| 
`*vserver cifs session file show -vserver _vserver_name_ -share _share_name_*`



 a| 
指定的 SMB 路径上
 a| 
`*vserver cifs session file show -vserver _vserver_name_ -path _path_*`



 a| 
具有指定级别的持续可用保护
 a| 
`*vserver cifs session file show -vserver _vserver_name_ -continuously-available _continuously_available_status_*`

的值 `-continuously-available` 可以是以下选项之一：

** `No`
** `Yes`
+
[NOTE]
====
持续可用状态为 `No`，这意味着这些打开的文件无法从接管和恢复中无系统地恢复。它们也无法从高可用性关系中的合作伙伴之间的常规聚合重新定位中恢复。

====




 a| 
具有指定的重新连接状态
 a| 
`*vserver cifs session file show -vserver _vserver_name_ -reconnected _reconnected_state_*`

的值 `-reconnected` 可以是以下选项之一：

** `No`
** `Yes`
+
[NOTE]
====
如果重新连接状态为 `No`，断开连接事件后打开的文件不会重新连接。这可能意味着文件从未断开连接，或者文件已断开连接且未成功重新连接。如果重新连接状态为 `Yes`，这意味着打开的文件在断开连接事件后成功重新连接。

====


|===
+
您可以使用其他可选参数来细化输出结果。有关详细信息，请参见手册页。



.示例
以下示例显示了有关 SVM vs1 上打开的文件的信息：

[listing]
----
cluster1::> vserver cifs session file show -vserver vs1
Node:       node1
Vserver:    vs1
Connection: 3151274158
Session:    1
File    File      Open Hosting               Continuously
ID      Type      Mode Volume    Share       Available
------- --------- ---- --------- ----------- ------------
41      Regular   r    data      data        Yes
Path: \mytest.rtf
----
以下示例显示了有关 SVM vs1 上文件 ID 82 的已打开 SMB 文件的详细信息：

[listing]
----
cluster1::> vserver cifs session file show -vserver vs1 -file-id 82 -instance

                  Node: node1
               Vserver: vs1
               File ID: 82
         Connection ID: 104617
            Session ID: 1
             File Type: Regular
             Open Mode: rw
Aggregate Hosting File: aggr1
   Volume Hosting File: data1
            CIFS Share: data1
  Path from CIFS Share: windows\win8\test\test.txt
            Share Mode: rw
           Range Locks: 1
Continuously Available: Yes
           Reconnected: No
----