---
permalink: smb-hyper-v-sql/nondisruptive-operations-glossary-concept.html 
sidebar: sidebar 
keywords: key, concepts, nondisruptive, operation, hyper, v, sql, server, smb, configure 
summary: 在通过 SMB 解决方案配置 Hyper-V 或 SQL Server 之前，您应了解有关无中断运行（ NDOS ）的某些概念。 
---
= 有关基于 SMB 的 Hyper-V 和 SQL Server 无中断运行的关键概念
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在通过 SMB 解决方案配置 Hyper-V 或 SQL Server 之前，您应了解有关无中断运行（ NDOS ）的某些概念。

* * 持续可用共享 *
+
设置了持续可用共享属性的 SMB 3.0 共享。通过持续可用的共享进行连接的客户端可以在接管，交还和聚合重新定位等中断事件发生后继续运行。

* *节点*
+
作为集群成员的单个控制器。为了区分 SFO 对中的两个节点，一个节点有时称为 _local nodge_ ，另一个节点有时称为 _partner nodge_ 或 _remote nodge_ 。存储的主所有者是本地节点。辅助所有者是配对节点，在主所有者出现故障时控制存储。每个节点都是其存储的主所有者，也是其配对节点存储的二级所有者。

* * 无中断聚合重新定位 *
+
能够在集群中 SFO 对内的配对节点之间移动聚合，而不会中断客户端应用程序。

* * 无中断故障转移 *
+
请参见 _Takeover_ 。

* * 无中断 LIF 迁移 *
+
能够执行 LIF 迁移，而不会中断通过 LIF 连接到集群的客户端应用程序。对于 SMB 连接，只有使用 SMB 2.0 或更高版本进行连接的客户端才可以执行此操作。

* * 无中断运行 * 。
+
能够执行主要的 ONTAP 管理和升级操作，并在不中断客户端应用程序的情况下承受节点故障。此术语指的是从整体上收集的无中断接管，无中断升级和无中断迁移功能。

* * 无中断升级 *
+
能够在不中断应用程序的情况下升级节点硬件或软件。

* * 无中断卷移动 *
+
可以在整个集群中自由移动卷，而不会中断正在使用该卷的任何应用程序。对于 SMB 连接，所有版本的 SMB 都支持无中断卷移动。

* * 持久性句柄 *
+
SMB 3.0 的一个属性，允许持续可用的连接在断开连接时透明地重新连接到 CIFS 服务器。与持久句柄类似，在与连接客户端的通信丢失后， CIFS 服务器会将永久性句柄保留一段时间。但是，持久句柄比持久句柄更具弹性。在重新连接后，除了让客户端有机会在 60 秒的窗口内回收句柄之外， CIFS 服务器还会在该 60 秒窗口期间拒绝访问请求访问文件的任何其他客户端。

+
有关永久性句柄的信息会镜像到 SFO 配对节点的永久性存储上，这样，在 SFO 配对节点接管节点存储所有权的事件发生后，具有已断开永久性句柄的客户端可以回收此持久句柄。除了在发生 LIF 移动时提供无中断操作（持久处理支持）之外，永久性句柄还可为接管，交还和聚合重新定位提供无中断操作。

* * SFO 交还 *
+
从接管事件中恢复时，将聚合返回到其主位置。

* * SFO 对 *
+
一对节点，其控制器已配置为在其中一个节点停止运行时彼此提供数据。根据系统型号，两个控制器可以位于一个机箱中，也可以位于不同的机箱中。在双节点集群中称为 HA 对。

* * 接管 *
+
当存储的主所有者出现故障时，配对节点控制存储的过程。在 SFO 环境下，故障转移和接管是同义词。


