---
permalink: smb-hyper-v-sql/remote-vss-considerations-concept.html 
sidebar: sidebar 
keywords: remote, vss, consideration, hyper, v, smb, configuration, backup, solution, automatic, recovery, shadow, copy 
summary: 在对基于 SMB 的 Hyper-V 配置使用支持远程 VSS 的备份解决方案时，您需要了解一些注意事项。 
---
= 基于 SMB 的 Hyper-V 配置的远程 VSS 注意事项
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在对基于 SMB 的 Hyper-V 配置使用支持远程 VSS 的备份解决方案时，您需要了解一些注意事项。



== 常规远程 VSS 注意事项

* 每个 Microsoft 应用程序服务器最多可配置 64 个共享。
+
如果卷影副本集中的共享超过 64 个，则卷影复制操作将失败。这是 Microsoft 的要求。

* 每个 CIFS 服务器仅允许设置一个活动卷影副本。
+
如果正在同一 CIFS 服务器上执行卷影复制操作，则卷影复制操作将失败。这是 Microsoft 的要求。

* 在远程 VSS 创建卷影副本的目录结构中，不允许使用任何接合。
+
** 在自动恢复情形下，如果在遍历共享时遇到接合，则卷影副本创建将失败。
** 在非自动恢复情形下，卷影副本创建不会失败，但接合不会指向任何内容。






== 仅适用于具有自动恢复功能的卷影副本的远程 VSS 注意事项

某些限制仅适用于具有自动恢复功能的卷影副本。

* 创建卷影副本时，最多允许五个子目录的深度。
+
这是卷影复制服务创建卷影副本备份集所使用的目录深度。如果包含虚拟机文件的目录嵌套深度超过五个级别，则卷影副本创建将失败。这样可以限制克隆共享时的目录遍历。可以使用 CIFS 服务器选项更改最大目录深度。

* 卷上的可用空间量必须足够。
+
可用空间必须至少与卷影副本备份集中包含的共享中的所有文件，目录和子目录所使用的总空间相同。

* 在远程 VSS 创建卷影副本的目录结构中，不允许使用任何链接或非常规文件。
+
如果共享中存在指向卷影副本的任何链接或非常规文件，则卷影副本创建将失败。克隆过程不支持这些设置。

* 目录上不允许使用 NFSv4 ACL 。
+
虽然卷影复制创建会保留文件上的 NFSv4 ACL ，但目录上的 NFSv4 ACL 会丢失。

* 创建卷影副本集最多允许 60 秒。
+
Microsoft 规范最多允许 60 秒创建卷影副本集。如果 VSS 客户端无法在此时间内创建卷影副本集，则卷影复制操作将失败；因此，这会限制卷影副本集中的文件数。备份集中可包含的文件或虚拟机的实际数量各不相同；该数量取决于多种因素，必须根据每个客户环境来确定。


