---
permalink: smb-hyper-v-sql/server-volume-requirements-hyper-v-concept.html 
sidebar: sidebar 
keywords: smb, cifs, server, volume, requirements, hyper, v, configuration, nondisruptive, operation 
summary: 在创建基于 SMB 的 Hyper-V 配置以实现无中断运行时，您需要了解特定的 SMB 服务器和卷要求。 
---
= 基于 SMB 的 Hyper-V 的 SMB 服务器和卷要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在创建基于 SMB 的 Hyper-V 配置以实现无中断运行时，您需要了解特定的 SMB 服务器和卷要求。



== SMB 服务器要求

* 必须启用 SMB 3.0 。
+
默认情况下，此选项处于启用状态。

* 必须使用有效的 UNIX 用户帐户配置默认 UNIX 用户 CIFS 服务器选项。
+
应用程序服务器在创建 SMB 连接时使用计算机帐户。由于所有 SMB 访问都要求 Windows 用户成功映射到 UNIX 用户帐户或默认 UNIX 用户帐户，因此 ONTAP 必须能够将应用程序服务器的计算机帐户映射到默认 UNIX 用户帐户。

* 必须禁用自动节点转介（默认情况下，此功能处于禁用状态）。
+
如果要使用自动节点转介来访问 Hyper-V 计算机文件以外的数据，则必须为该数据创建单独的 SVM 。

* SMB 服务器所属的域必须允许 Kerberos 和 NTLM 身份验证。
+
ONTAP 不会为远程 VSS 公布 Kerberos 服务；因此，应将域设置为允许 NTLM 。

* 必须启用卷影复制功能。
+
默认情况下，此功能处于启用状态。

* 卷影复制服务在创建卷影副本时使用的 Windows 域帐户必须是 SMB 服务器本地 BUILTIN\Administrators 或 BUILTIN\Backup Operators 组的成员。




== 卷要求：

* 用于存储虚拟机文件的卷必须创建为 NTFS 安全模式卷。
+
要使用持续可用的 SMB 连接为应用程序服务器提供 NDOS ，包含共享的卷必须为 NTFS 卷。此外，它必须始终是 NTFS 卷。您不能将混合安全模式卷或 UNIX 安全模式卷更改为 NTFS 安全模式卷，也不能通过 SMB 共享将其直接用于 NDOS 。如果您将混合安全模式卷更改为 NTFS 安全模式卷，并打算通过 SMB 共享将其用于 NDOS ，则必须手动将 ACL 放置在卷顶部，并将该 ACL 传播到包含的所有文件和文件夹。否则，如果源卷或目标卷最初创建为混合卷或 UNIX 安全模式卷，然后更改为 NTFS 安全模式，则将文件移至另一个卷的虚拟机迁移或数据库文件导出和导入可能会失败。

* 要成功执行卷影复制操作，卷上必须有足够的可用空间。
+
可用空间必须至少与卷影副本备份集中包含的共享中的所有文件，目录和子目录所使用的总空间相同。此要求仅支持具有自动恢复功能的适用场景卷影副本。



http://technet.microsoft.com/en-us/library/["Microsoft TechNet 库： technet.microsoft.com/en-us/library/"]
