---
permalink: file-system-analytics/activity-tracking-task.html 
sidebar: sidebar 
keywords: monitor, volume, ontap, FSA, File System Analytics, 
summary: 活动跟踪可查看指定卷中的热文件，目录，客户端和用户，以便通过实时排除性能故障 
---
= 启用活动跟踪
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
从ONTAP 9.10.1开始、文件系统分析包括一项活动跟踪功能、可用于识别热对象并将其下载为CSV文件。从ONTAP 9.11.1开始、活动跟踪已扩展到SVM范围。此外、从ONTAP 9.11.1开始、System Manager还提供了活动跟踪时间表、您可以查看长达五分钟的活动跟踪数据。

通过活动跟踪，可以监控以下四个类别：

* 目录
* 文件
* 客户端
* 用户


对于监控的每个类别，活动跟踪将显示读取 IOPS ，写入 IOPS ，读取吞吐量和写入吞吐量。有关活动跟踪的查询，每 10 到 15 秒刷新一次与系统中在前五秒间隔内发现的热点相关的信息。

活动跟踪信息为近似信息，数据的准确性取决于传入 I/O 流量的分布情况。

在System Manager中查看卷级别的活动跟踪时、只有扩展卷的菜单才会主动刷新。如果任何卷的视图已折叠，则只有在卷显示展开后，这些卷才会刷新。您可以使用 * 暂停刷新 * 按钮停止刷新。可以下载 CSV 格式的活动数据，此格式将显示为选定卷捕获的所有时间点数据。

从ONTAP 9.11.1开始提供时间线功能、您可以记录卷或SVM上的热点活动、大约每五秒持续更新一次、并保留前五分钟的数据。只有页面的可见区域字段才会保留时间线数据。如果折叠跟踪类别或滚动以使时间线无法显示、则时间线将停止收集数据。默认情况下、时间线处于禁用状态、当您离开活动选项卡时、时间线将自动禁用。



== 为单个卷启用活动跟踪

您可以使用ONTAP System Manager或ONTAP 命令行界面启用活动跟踪。

如果将 RBAC 与 ONTAP REST API 或 System Manager 结合使用，则需要创建自定义角色来管理对活动跟踪的访问。请参见  access control (RBAC) and Activity Tracking 。

[role="tabbed-block"]
====
.System Manager
--
.步骤
. 选择 * 存储 > 卷 * 。选择所需的卷。从单个卷菜单中，选择文件系统，然后选择活动选项卡。
. 确保已启用 * 活动跟踪 * ，以查看有关顶层目录，文件，客户端和用户的各个报告。
. 要在不刷新的情况下更深入地分析数据，请选择 * 暂停刷新 * 。您也可以下载数据以获取报告的 CSV 记录。


--
.命令行界面
--
.步骤
. 启用活动跟踪：
+
`-vsverer _svm_name_ -volume _volume_name_` 上的卷活动跟踪

. 您可以使用命令检查卷的活动跟踪状态是打开还是关闭：
+
`volume active-tracking show -vsverer _svm_name_ -volume _volume_name_ -state`

. 启用后，使用 ONTAP 系统管理器或 ONTAP REST API 显示活动跟踪数据。


--
====


== 为多个卷启用活动跟踪

您可以使用System Manager一次性为多个卷启用活动跟踪。

如果将 RBAC 与 ONTAP REST API 或 System Manager 结合使用，则需要创建自定义角色来管理对活动跟踪的访问。请参见  access control (RBAC) and Activity Tracking 。

[role="tabbed-block"]
====
.用于特定卷
--
.步骤
. 选择 * 存储 > 卷 * 。选择所需的卷。从单个卷菜单中，选择文件系统，然后选择活动选项卡。
. 选择要启用活动跟踪的卷。在卷列表顶部、选择*更多选项*按钮。选择*启用活动跟踪*。
. 要在SVM级别查看活动跟踪、请从*存储>卷*中选择要查看的特定SVM。导航到文件系统选项卡、然后导航到活动、您将看到已启用活动跟踪的卷的数据。


--
.对于SVM中的所有卷
--
.步骤
. 选择 * 存储 > 卷 * 。从菜单中选择一个SVM。
. 导航到*文件系统*选项卡、选择*更多*选项卡以对SVM中的所有卷启用活动跟踪。


--
====


== 基于角色的访问控制(Role-Based Access Control、RBAC)和活动跟踪

如果您使用 xref:../concepts/administrator-authentication-rbac-concept.html[基于角色的访问控制] (RBAC)在System Manager或ONTAP REST API中、您需要创建一个专用角色来控制对文件系统分析中活动跟踪的访问权限。

.步骤
. 创建一个默认角色以访问所有功能。
+
在创建限制性角色之前需要执行此操作，以确保此角色仅对活动跟踪具有限制性：

+
`ssecurity login role create -cmddirname default -access all -role storageAdmin`

. 创建限制性角色：
+
`ssecurity login role create -cmddirname "volume file show-disk-usage" -access none -role storageAdmin`

. 授权角色访问 SVM 的 Web 服务：
+
** `rest` 用于 REST API 调用
** `s安全性` 用于密码保护
** `sysmgr` 用于 System Manager 访问
+
`vserver services web access create -vserver _svm-name_-name_-name REST -role storageAdmin`

+
`vserver services web access create -vserver _svm-name_-name security -role storageAdmin`

+
`vserver services web access create -vserver _svm-name_-name sysmgr -role storageAdmin`



. 创建用户。
+
您必须为要应用于用户的每个应用程序问题描述 一个不同的 create 命令。在同一用户上多次调用 create 只会将所有应用程序应用于该用户，而不会每次创建新用户。应用程序类型的 `http` 参数适用于 ONTAP REST API 和系统管理器。

+
`ssecurity login create -user-or-group-name storageUser -authentication-method password -application http -role storageAdmin`

. 现在、您可以使用新的用户凭据登录到System Manager或使用ONTAP REST API访问文件系统分析数据。


link:https://docs.netapp.com/us-en/ontap-automation/rest/rbac_overview.html["详细了解RBAC角色和ONTAP REST API"^]
