---
permalink: file-system-analytics/activity-tracking-task.html 
sidebar: sidebar 
keywords: monitor, volume, ontap, FSA, File System Analytics, 
summary: 活动跟踪功能、可用于识别热对象并将其作为CSV文件下载。 
---
= 启用活动跟踪
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
从ONTAP 9.10.1开始、文件系统分析包括一项活动跟踪功能、可用于识别热对象并将数据下载为CSV文件。从ONTAP 9.11.1开始、活动跟踪已扩展到SVM范围。此外、从ONTAP 9.11.1开始、System Manager还提供了活动跟踪时间表、您可以查看长达五分钟的活动跟踪数据。

通过活动跟踪，可以监控以下四个类别：

* 目录
* 文件
* 客户端
* 用户


对于监控的每个类别，活动跟踪将显示读取 IOPS ，写入 IOPS ，读取吞吐量和写入吞吐量。有关活动跟踪的查询，每 10 到 15 秒刷新一次与系统中在前五秒间隔内发现的热点相关的信息。

活动跟踪信息为近似信息，数据的准确性取决于传入 I/O 流量的分布情况。

在System Manager中查看卷级别的活动跟踪时、只有扩展卷的菜单才会主动刷新。如果任何卷的视图已折叠，则只有在卷显示展开后，这些卷才会刷新。您可以使用 * 暂停刷新 * 按钮停止刷新。可以下载 CSV 格式的活动数据，此格式将显示为选定卷捕获的所有时间点数据。

从ONTAP 9.11.1开始提供时间线功能、您可以记录卷或SVM上的热点活动、大约每五秒持续更新一次、并保留前五分钟的数据。只有页面的可见区域字段才会保留时间线数据。如果折叠跟踪类别或滚动以使时间线无法显示、则时间线将停止收集数据。默认情况下、时间线处于禁用状态、当您离开活动选项卡时、时间线将自动禁用。



== 为单个卷启用活动跟踪

您可以使用ONTAP系统管理器或命令行界面启用活动跟踪。

.关于此任务
如果将 RBAC 与 ONTAP REST API 或 System Manager 结合使用，则需要创建自定义角色来管理对活动跟踪的访问。请参见 xref:role-based-access-control-task.html[基于角色的访问控制] 。

[role="tabbed-block"]
====
.System Manager
--
.步骤
. 选择 * 存储 > 卷 * 。选择所需的卷。从单个卷菜单中，选择文件系统，然后选择活动选项卡。
. 确保已启用 * 活动跟踪 * ，以查看有关顶层目录，文件，客户端和用户的各个报告。
. 要在不刷新的情况下更深入地分析数据，请选择 * 暂停刷新 * 。您也可以下载数据以获取报告的 CSV 记录。


--
.命令行界面
--
.步骤
. 启用活动跟踪：
+
`volume activity-tracking on -vserver _svm_name_ -volume _volume_name_`

. 使用命令检查卷的活动跟踪状态是打开还是关闭：
+
`volume activity-tracking show -vserver _svm_name_ -volume _volume_name_ -state`

. 启用后，使用 ONTAP 系统管理器或 ONTAP REST API 显示活动跟踪数据。


--
====


== 为多个卷启用活动跟踪

您可以使用System Manager一次性为多个卷启用活动跟踪。

.关于此任务
如果将 RBAC 与 ONTAP REST API 或 System Manager 结合使用，则需要创建自定义角色来管理对活动跟踪的访问。请参见 xref:role-based-access-control-task.html[基于角色的访问控制] 。

[role="tabbed-block"]
====
.System Manager
--
.为特定卷启用
. 选择 * 存储 > 卷 * 。选择所需的卷。从单个卷菜单中，选择文件系统，然后选择活动选项卡。
. 选择要启用活动跟踪的卷。在卷列表顶部、选择*更多选项*按钮。选择*启用活动跟踪*。
. 要在SVM级别查看活动跟踪、请从*存储>卷*中选择要查看的特定SVM。导航到文件系统选项卡、然后导航到活动、您将看到已启用活动跟踪的卷的数据。


.为所有卷启用
. 选择 * 存储 > 卷 * 。从菜单中选择一个SVM。
. 导航到*文件系统*选项卡、选择*更多*选项卡以对SVM中的所有卷启用活动跟踪。


--
.命令行界面
--
从ONTAP 9.13.1开始、您可以使用ONTAP命令行界面为多个卷启用活动跟踪。

.步骤
. 启用活动跟踪：
+
`volume activity-tracking on -vserver _svm_name_ -volume [*|!_volume_names_]`

+
使用 ... `*` 为指定Storage VM上的所有卷启用活动跟踪。

+
使用 ... `!` 后跟卷名称、以便为SVM上的所有卷(命名卷除外)启用活动跟踪。

. 确认操作成功：
+
`volume show -fields activity-tracking-state`

. 启用后，使用 ONTAP 系统管理器或 ONTAP REST API 显示活动跟踪数据。


--
====