---
sidebar: sidebar 
permalink: file-system-analytics/considerations-concept.html 
keywords: file system analytics, performance, 7-mode 
summary: 文件系统分析旨在提供对包含活动 NAS 数据的卷的可见性。其使用存在限制和限制。 
---
= 文件系统分析注意事项
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您应了解与实施文件系统分析相关的特定使用限制和潜在性能影响。



== 支持的卷类型

文件系统分析旨在提供对包含活动 NAS 数据的卷的可见性，但 FlexCache 缓存和 SnapMirror 目标卷除外。



== 性能注意事项

启用文件系统分析可能会在初始元数据收集期间影响性能。请勿对利用率最高的系统启用分析。

ONTAP System Manager 可提供 xref:../concept_cluster_performance_overview.adoc[性能监控工具] 以管理集群运行状况和指标。

* 受 SVM 保护的关系 *

如果已对包含 SVM 的卷处于保护关系中的卷启用文件系统分析，则分析数据不会复制到目标 SVM 。如果必须在恢复操作中重新同步源 SVM ，则必须在恢复后手动重新启用对所需卷的分析。



== RBAC

如果您是 System Manager 或 ONTAP REST API 的用户 xref:../concepts/administrator-authentication-rbac-concept.html[RBAC] 在您的 ONTAP 设置中，您需要创建一个专用角色来控制对文件系统分析中活动跟踪的访问权限。

.控制对活动跟踪的访问
. 创建一个默认角色以访问所有功能。在创建限制性角色之前需要执行此操作，以确保此角色仅对活动跟踪具有限制性：
+
`ssecurity login role create -cmddirname default -access all -role storageAdmin`

. 创建限制性角色：
+
`ssecurity login role create -cmddirname "volume file show-disk-usage" -access none -role storageAdmin`

. 授权角色访问 SVM 的 Web 服务：
+
** `rest` 用于 REST API 调用
** `s安全性` 用于密码保护
** `sysmgr` 用于 System Manager 访问
+
====
vserver services web access create -vserver _svm-name_ -name REST -role storageAdmin + vserver services web access create -vserver _svm-name_ -name security -role storageAdmin + vserver services web access create -vserver _svm-name_ -name sysmgr -role storageAdmin

====


. 创建用户。您必须为要应用于用户的每个应用程序问题描述 一个不同的 create 命令。在同一用户上多次调用 create 只会将所有应用程序应用于该用户，而不会每次创建新用户。应用程序类型的 `http` 参数适用于 ONTAP REST API 和系统管理器。
+
`ssecurity login create -user-or-group-name storageUser -authentication-method password -application http -role storageAdmin`

. 现在、您可以使用新的用户凭据登录到System Manager或使用ONTAP REST API访问文件系统分析数据。

