---
permalink: antivirus/apply-scanner-policies-disaster-recovery-mcc-task.html 
sidebar: sidebar 
keywords: apply, scanner policies, metrocluster, configurations 
summary: 扫描程序策略用于确定扫描程序池是否处于活动状态。必须将扫描程序策略应用于 MetroCluster 配置中每个集群上的主扫描程序池和二级扫描程序池。 
---
= 在 MetroCluster 配置中应用扫描程序策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
扫描程序策略用于确定扫描程序池是否处于活动状态。必须将扫描程序策略应用于 MetroCluster 配置中每个集群上的主扫描程序池和二级扫描程序池。

.关于此任务
* 一个扫描程序池只能应用一个扫描程序策略。
* 如果为集群中的所有SVM创建了扫描程序池、则必须分别对每个SVM应用扫描程序策略。
* 对于灾难恢复和MetroCluster配置、您必须将扫描程序策略应用于本地集群和远程集群中的每个扫描程序池。
* 在为本地集群创建的策略中、必须在中指定本地集群 `cluster` 参数。在为远程集群创建的策略中、必须在中指定远程集群 `cluster` 参数。然后、远程集群可以在发生灾难时接管病毒扫描操作。


.步骤
. 应用扫描程序策略：
+
`vserver vscan scanner-pool apply-policy -vserver _data_SVM_ -scanner-pool _scanner_pool_ -scanner-policy primary|secondary|idle -cluster _cluster_to_apply_policy_on_`

+
扫描程序策略可以具有以下值之一：

+
** `Primary` 指定扫描程序池处于活动状态。
** `Secondary` 指定只有在主扫描程序池中没有Vscan服务器连接时扫描程序池才处于活动状态。
** `Idle` 指定扫描程序池处于非活动状态。
+
[NOTE]
====
您必须应用包含主 SVM 的集群中的所有扫描程序策略。

====
+
以下命令会将扫描程序策略应用于 MetroCluster 配置中每个集群上的主扫描程序池和二级扫描程序池：

+
[listing]
----
cluster1::>vserver vscan scanner-pool apply-policy -vserver cifssvm1
-scanner-pool pool1_for_site1 -scanner-policy primary -cluster cluster1

cluster1::>vserver vscan scanner-pool apply-policy -vserver cifssvm1
-scanner-pool pool2_for_site1 -scanner-policy secondary -cluster cluster1

cluster1::>vserver vscan scanner-pool apply-policy -vserver cifssvm1
-scanner-pool pool1_for_site2 -scanner-policy primary -cluster cluster2

cluster1::>vserver vscan scanner-pool apply-policy -vserver cifssvm1
-scanner-pool pool2_for_site2 -scanner-policy secondary -cluster cluster2
----


. 验证扫描程序池是否处于活动状态：
+
`vserver vscan scanner-pool show -vserver data_SVM|cluster_admin_SVM -scanner-pool scanner_pool`

+
有关完整的选项列表，请参见命令手册页。

+
以下命令显示扫描程序池的详细信息 `pool1`：

+
[listing]
----
cluster1::> vserver vscan scanner-pool show -vserver cifssvm1 -scanner-pool pool1_for_site1

                                    Vserver: cifssvm1
                               Scanner Pool: pool1_for_site1
                             Applied Policy: primary
                             Current Status: on
         Cluster on Which Policy Is Applied: cluster1
                  Scanner Pool Config Owner: vserver
       List of IPs of Allowed Vscan Servers:
List of Host Names of Allowed Vscan Servers: scan1
                   List of Privileged Users: cifs\u1,cifs\u2
----
+
您可以使用 `vserver vscan scanner-pool show-active` 命令以查看SVM上的活动扫描程序池。有关完整的命令语法，请参见命令手册页。


