---
permalink: antivirus/commands-manage-on-access-policies-reference.html 
sidebar: sidebar 
keywords: commands, manage, on-access, policies 
summary: 您可以修改，禁用或删除实时策略。您可以查看策略的摘要和详细信息。 
---
= 用于在ONTAP中管理实时策略的命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以修改，禁用或删除实时策略。您可以查看策略的摘要和详细信息。

|===


| 如果您要 ... | 输入以下命令 ... 


 a| 
创建实时策略
 a| 
`vserver vscan on-access-policy create`



 a| 
修改实时策略
 a| 
`vserver vscan on-access-policy modify`



 a| 
启用实时策略
 a| 
`vserver vscan on-access-policy enable`



 a| 
禁用实时策略
 a| 
`vserver vscan on-access-policy disable`



 a| 
删除实时策略
 a| 
`vserver vscan on-access-policy delete`



 a| 
查看实时策略的摘要和详细信息
 a| 
`vserver vscan on-access-policy show`



 a| 
添加到要排除的路径列表
 a| 
`vserver vscan on-access-policy paths-to-exclude add`



 a| 
从要排除的路径列表中删除
 a| 
`vserver vscan on-access-policy paths-to-exclude remove`



 a| 
查看要排除的路径列表
 a| 
`vserver vscan on-access-policy paths-to-exclude show`



 a| 
添加到要排除的文件扩展名列表
 a| 
`vserver vscan on-access-policy file-ext-to-exclude add`



 a| 
从要排除的文件扩展名列表中删除
 a| 
`vserver vscan on-access-policy file-ext-to-exclude remove`



 a| 
查看要排除的文件扩展名列表
 a| 
`vserver vscan on-access-policy file-ext-to-exclude show`



 a| 
添加到要包含的文件扩展名列表中
 a| 
`vserver vscan on-access-policy file-ext-to-include add`



 a| 
从要包含的文件扩展名列表中删除
 a| 
`vserver vscan on-access-policy file-ext-to-include remove`



 a| 
查看要包括的文件扩展名列表
 a| 
`vserver vscan on-access-policy file-ext-to-include show`

|===
有关此过程中所述命令的更多信息，请参见link:https://docs.netapp.com/us-en/ontap-cli/["ONTAP 命令参考"^]。
