---
permalink: antivirus/create-on-demand-task-task.html 
sidebar: sidebar 
keywords: create, on-demand, task, vserver vscan 
summary: 按需任务定义了按需扫描的范围。您可以指定要扫描的文件的最大大小，要包含在扫描中的文件的扩展名和路径，以及要从扫描中排除的文件的扩展名和路径。 
---
= 创建按需任务
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
按需任务定义按需病毒扫描的范围。您可以指定要扫描的文件的最大大小，要包含在扫描中的文件的扩展名和路径，以及要从扫描中排除的文件的扩展名和路径。默认情况下会扫描子目录中的文件。

.关于此任务
* 每个SVM最多可以有十(10)个按需任务、但只能有一个处于活动状态。
* 按需任务会创建一个报告、其中包含与扫描相关的统计信息。可通过命令或下载任务在定义的位置创建的报告文件来访问此报告。


.开始之前
* 您必须拥有 xref:create-on-access-policy-task.html[已创建实时策略]。此策略可以是默认策略、也可以是用户创建的策略。如果没有实时策略、则无法启用扫描。


.步骤
. 创建按需任务：
+
`vserver vscan on-demand-task create -vserver _data_SVM_ -task-name _task_name_ -scan-paths _paths_of_files_to_scan_ -report-directory _report_directory_path_ -report-expiry-time _expiration_time_for_report_ -schedule cron_schedule -max-file-size _max_size_of_files_to_scan_ -paths-to-exclude _paths_ -file-ext-to-exclude _file_extensions_ -file-ext-to-include _file_extensions_ -scan-files-with-no-ext true|false -directory-recursion true|false`

+
** 。 `-file-ext-to-exclude` 设置将覆盖 `-file-ext-to-include` 设置。
** 设置 `-scan-files-with-no-ext` 设置为true可扫描不带扩展名的文件。


+
有关完整的选项列表、请参见 link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-on-demand-task-create.html["命令参考"^]。

+
以下命令将创建一个名为的按需任务 `Task1` 在`VS1`s虚拟机上：

+
[listing]
----
cluster1::> vserver vscan on-demand-task create -vserver vs1 -task-name Task1 -scan-paths "/vol1/","/vol2/cifs/" -report-directory "/report" -schedule daily -max-file-size 5GB -paths-to-exclude "/vol1/cold-files/" -file-ext-to-include "vmdk?","mp*" -file-ext-to-exclude "mp3","mp4" -scan-files-with-no-ext false
[Job 126]: Vscan On-Demand job is queued. Use the "job show -id 126" command to view the status.
----
+

NOTE: 您可以使用 `job show` 命令以查看作业状态。您可以使用 `job pause` 和 `job resume` 用于暂停和重新启动作业的命令、或 `job stop` 命令以结束作业。

. 验证是否已创建按需任务：
+
`vserver vscan on-demand-task show -instance data_SVM -task-name task_name`

+
有关完整的选项列表，请参见命令手册页。

+
以下命令将显示的详细信息 `Task1` 任务：

+
[listing]
----
cluster1::> vserver vscan on-demand-task show -instance vs1 -task-name Task1

                           Vserver: vs1
                         Task Name: Task1
                List of Scan Paths: /vol1/, /vol2/cifs/
             Report Directory Path: /report
                      Job Schedule: daily
Max File Size Allowed for Scanning: 5GB
            File Paths Not to Scan: /vol1/cold-files/
       File Extensions Not to Scan: mp3, mp4
           File Extensions to Scan: vmdk?, mp*
      Scan Files with No Extension: false
           Request Service Timeout: 5m
                    Cross Junction: true
               Directory Recursion: true
                     Scan Priority: low
                  Report Log Level: info
        Expiration Time for Report: -
----


.完成后
在计划运行任务之前，必须在 SVM 上启用扫描。
