---
permalink: revert/task_things_to_verify_before_revert.html 
sidebar: sidebar 
keywords: ontap, revert, reversion, reverting, downgrade, downgrading, preparation 
summary: 各种配置设置可能会影响集群升级准备情况。 
---
= 还原前需要验证的事项
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在还原之前，您应验证集群运行状况，存储运行状况和系统时间。  此外、您还应删除正在运行的任何集群作业、并正常终止不持续可用的任何SMB会话。



== 验证集群运行状况

在还原集群之前，您应验证节点是否运行正常且符合加入集群的条件，以及集群是否处于仲裁状态。

. 验证集群中的节点是否已联机且符合加入集群的条件： `cluster show`
+
[listing]
----
cluster1::> cluster show
Node                  Health  Eligibility
--------------------- ------- ------------
node0                 true    true
node1                 true    true
----
+
如果任何节点运行状况不正常或不符合条件，请检查 EMS 日志中的错误并采取更正措施。

. 将权限级别设置为高级：+
`set -privilege advanced`
+
输入 ... `y` 以继续。

. 验证每个 RDB 进程的配置详细信息。
+
** 每个节点的关系数据库 epoch 和数据库 epochs 应匹配。
** 所有节点的每环仲裁主机都应相同。
+
请注意，每个环可能具有不同的仲裁主环。

+
[cols="2*"]
|===
| 要显示此 RDB 进程 ... | 输入此命令 ... 


 a| 
管理应用程序
 a| 
`cluster ring show -unitname mgmt`



 a| 
卷位置数据库
 a| 
`cluster ring show -unitname vldb`



 a| 
虚拟接口管理器
 a| 
`cluster ring show -unitname vifmgr`



 a| 
SAN 管理守护进程
 a| 
`cluster ring show -unitname bcomd`

|===
+
此示例显示了卷位置数据库过程：

+
[listing]
----
cluster1::*> cluster ring show -unitname vldb
Node      UnitName Epoch    DB Epoch DB Trnxs Master    Online
--------- -------- -------- -------- -------- --------- ---------
node0     vldb     154      154      14847    node0     master
node1     vldb     154      154      14847    node0     secondary
node2     vldb     154      154      14847    node0     secondary
node3     vldb     154      154      14847    node0     secondary
4 entries were displayed.
----


. 返回到管理权限级别：+
`set -privilege admin`
. 如果您在 SAN 环境中运行，请验证每个节点是否处于 SAN 仲裁状态： `event log show  -severity informational -message-name scsiblade.*`
+
每个节点的最新 scsiblade 事件消息应指示 SCSI 刀片处于仲裁状态。

+
[listing]
----
cluster1::*> event log show  -severity informational -message-name scsiblade.*
Time             Node       Severity       Event
---------------  ---------- -------------- ---------------------------
MM/DD/YYYY TIME  node0      INFORMATIONAL  scsiblade.in.quorum: The scsi-blade ...
MM/DD/YYYY TIME  node1      INFORMATIONAL  scsiblade.in.quorum: The scsi-blade ...
----


.相关信息
link:../system-admin/index.html["系统管理"]



== 验证存储运行状况

在还原集群之前，您应验证磁盘，聚合和卷的状态。

. 验证磁盘状态：
+
[cols="2*"]
|===
| 要检查 ... | 执行此操作 ... 


 a| 
磁盘已损坏
 a| 
.. 显示任何损坏的磁盘： `storage disk show -state broken`
.. 卸下或更换任何损坏的磁盘。




 a| 
正在进行维护或重建的磁盘
 a| 
.. 显示处于维护，待定或重建状态的任何磁盘： `storage disk show -state maintenance|pending|reconstructing`
.. 等待维护或重建操作完成，然后再继续。


|===
. 通过显示物理和逻辑存储（包括存储聚合）的状态，验证所有聚合是否联机： `storage aggregate show -state !online`
+
此命令将显示 _not_ 联机的聚合。在执行重大升级或还原之前和之后，所有聚合都必须处于联机状态。

+
[listing]
----
cluster1::> storage aggregate show -state !online
There are no entries matching your query.
----
. 通过显示任何 _not_ 联机的卷来验证所有卷是否均已联机： `volume show -state !online`
+
在执行重大升级或还原之前和之后，所有卷都必须处于联机状态。

+
[listing]
----
cluster1::> volume show -state !online
There are no entries matching your query.
----
. 验证是否没有不一致的卷： `volume show -is-inconsistent true`
+
请参见知识库文章 link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Volume_Showing_WAFL_Inconsistent["卷显示WAFL 不一致"] 有关如何处理不一致的卷的信息。



.相关信息
link:../disks-aggregates/index.html["磁盘和聚合管理"]



== 验证系统时间

在还原之前，您应验证是否已配置 NTP ，以及时间是否已在集群中同步。

. 验证集群是否已与NTP服务器关联： `cluster time-service ntp server show`
. 验证每个节点的日期和时间是否相同： `cluster date show`
+
[listing]
----
cluster1::> cluster date show
Node      Date                Timezone
--------- ------------------- -------------------------
node0     4/6/2013 20:54:38   GMT
node1     4/6/2013 20:54:38   GMT
node2     4/6/2013 20:54:38   GMT
node3     4/6/2013 20:54:38   GMT
4 entries were displayed.
----




== 确认没有正在运行的作业

在还原 ONTAP 软件之前，您必须验证集群作业的状态。如果存在任何聚合，卷， NDMP （转储或还原）或 Snapshot 作业（例如创建，删除，移动，修改，复制， 和挂载作业）正在运行或排队，您必须允许作业成功完成或停止已排队的条目。

. 查看任何正在运行或已排队的聚合、卷或Snapshot作业的列表： `job show`
+
[listing]
----
cluster1::> job show
                            Owning
Job ID Name                 Vserver    Node           State
------ -------------------- ---------- -------------- ----------
8629   Vol Reaper           cluster1   -              Queued
       Description: Vol Reaper Job
8630   Certificate Expiry Check
                            cluster1   -              Queued
       Description: Certificate Expiry Check
.
.
.
----
. 删除任何正在运行或已排队的聚合、卷或Snapshot副本作业： `job delete -id job_id`
+
[listing]
----
cluster1::> job delete -id 8629
----
. 验证是否没有聚合、卷或Snapshot作业正在运行或已排队： `job show`
+
在此示例中，已删除所有正在运行和已排队的作业：

+
[listing]
----
cluster1::> job show
                            Owning
Job ID Name                 Vserver    Node           State
------ -------------------- ---------- -------------- ----------
9944   SnapMirrorDaemon_7_2147484678
                            cluster1   node1          Dormant
       Description: Snapmirror Daemon for 7_2147484678
18377  SnapMirror Service Job
                            cluster1   node0          Dormant
       Description: SnapMirror Service Job
2 entries were displayed
----




== 应终止的SMB会话

在还原之前，您应确定并正常终止任何不持续可用的 SMB 会话。

通过使用 SMB 3.0 协议的 Hyper-V 或 Microsoft SQL Server 客户端访问的持续可用 SMB 共享，无需在升级或降级之前终止。

. 确定任何已建立但不持续可用的SMB会话： `vserver cifs session show -continuously-available No -instance`
+
此命令可显示有关无持续可用性的任何SMB会话的详细信息。在继续 ONTAP 降级之前，您应终止它们。

+
[listing]
----
cluster1::> vserver cifs session show -continuously-available No -instance

                        Node: node1
                     Vserver: vs1
                  Session ID: 1
               Connection ID: 4160072788
Incoming Data LIF IP Address: 198.51.100.5
      Workstation IP address: 203.0.113.20
    Authentication Mechanism: NTLMv2
                Windows User: CIFSLAB\user1
                   UNIX User: nobody
                 Open Shares: 1
                  Open Files: 2
                  Open Other: 0
              Connected Time: 8m 39s
                   Idle Time: 7m 45s
            Protocol Version: SMB2_1
      Continuously Available: No
1 entry was displayed.
----
. 如有必要、确定为您确定的每个SMB会话打开的文件： `vserver cifs session file show -session-id session_ID`
+
[listing]
----
cluster1::> vserver cifs session file show -session-id 1

Node:       node1
Vserver:    vs1
Connection: 4160072788
Session:    1
File    File      Open Hosting                               Continuously
ID      Type      Mode Volume          Share                 Available
------- --------- ---- --------------- --------------------- ------------
1       Regular   rw   vol10           homedirshare          No
Path: \TestDocument.docx
2       Regular   rw   vol10           homedirshare          No
Path: \file1.txt
2 entries were displayed.
----




== NVMe/TCP安全身份验证

如果您运行的是NVMe/TCP协议、并且已使用DH-HMAC-CHAP建立安全身份验证、则必须在还原之前从NVMe子系统中删除任何使用DH-HMAC-CHAP的主机。  如果未删除这些主机、还原将失败。
