---
permalink: revert/task_enabling_and_reverting_lifs_to_home_ports_completing_post_reversion_tasks.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, downgrade, downgrading, enable, enabling, lifs, home, ports 
summary: 在重新启动期间，某些 LIF 可能已迁移到其分配的故障转移端口。还原集群后，您必须启用并还原不在其主端口上的任何 LIF 。 
---
= 在ONTAP还原后、启用并将LUN还原到主端口
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在重新启动期间，某些 LIF 可能已迁移到其分配的故障转移端口。还原ONTAP集群后、您必须启用并还原不在主端口上的任何LUN。

network interface revert 命令会将当前不在主端口上的 LIF 还原到其主端口，前提是主端口正常运行。创建 LIF 时会指定 LIF 的主端口；您可以使用 network interface show 命令确定 LIF 的主端口。

.步骤
. 显示所有LIF的状态：
+
[source, cli]
----
network interface show
----
+
此示例显示 Storage Virtual Machine （ SVM ）的所有 LIF 的状态。

+
[listing]
----
cluster1::> network interface show -vserver vs0
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
vs0
            data001    down/down  192.0.2.120/24     node0         e0e     true
            data002    down/down  192.0.2.121/24     node0         e0f     true
            data003    down/down  192.0.2.122/24     node0         e2a     true
            data004    down/down  192.0.2.123/24     node0         e2b     true
            data005    down/down  192.0.2.124/24     node0         e0e     false
            data006    down/down  192.0.2.125/24     node0         e0f     false
            data007    down/down  192.0.2.126/24     node0         e2a     false
            data008    down/down  192.0.2.127/24     node0         e2b     false
8 entries were displayed.
----
+
如果任何 LIF 的状态为 Admin 状态为 down 或状态为 false ，请继续执行下一步。

. 启用数据生命周期：
+
[source, cli]
----
network interface modify {-role data} -status-admin up
----
. 将LIF还原到其主端口：
+
[source, cli]
----
network interface revert *
----
. 验证所有的SIFs是否都位于其主端口中：
+
[source, cli]
----
network interface show
----
+
此示例显示 SVM vs0 的所有 LIF 均位于其主端口上。

+
[listing]
----
cluster1::> network interface show -vserver vs0
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
vs0
            data001      up/up    192.0.2.120/24     node0         e0e     true
            data002      up/up    192.0.2.121/24     node0         e0f     true
            data003      up/up    192.0.2.122/24     node0         e2a     true
            data004      up/up    192.0.2.123/24     node0         e2b     true
            data005      up/up    192.0.2.124/24     node1         e0e     true
            data006      up/up    192.0.2.125/24     node1         e0f     true
            data007      up/up    192.0.2.126/24     node1         e2a     true
            data008      up/up    192.0.2.127/24     node1         e2b     true
8 entries were displayed.
----


.相关信息
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+interface["网络接口"^]

