---
permalink: smb-admin/access-snapshot-directories-clients-smb2-concept.html 
sidebar: sidebar 
keywords: method, access, snapshot, directory, windows, client, smb, data, store, copies, copy, how to access the snapshot directory from windows clients using smb 2.x 
summary: 使用 SMB 2.x 从 Windows 客户端访问 ~Snapshot 目录的方法与使用 SMB 1.0 的方法不同。使用 SMB 2.x 连接成功访问 Snapshot 副本中存储的数据时，您需要了解如何访问 ~Snapshot 目录。 
---
= 使用 SMB 2.x 从 Windows 客户端访问 ~Snapshot 目录
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
用于访问的方法 `~snapshot` 使用SMB 2.x的Windows客户端的目录与使用SMB 1.0的方法不同。您需要了解如何访问 `~snapshot` 使用SMB 2.x连接成功访问Snapshot副本中存储的数据时的目录。

SVM管理员控制Windows客户端上的用户是否可以查看和访问 `~snapshot` 通过启用或禁用共享上的目录 `showsnapshot` 使用Vserver CIFS共享属性系列中的命令共享属性。

当 `showsnapshot` 共享属性已禁用、使用SMB 2.x的Windows客户端上的用户无法查看 `~snapshot` 目录中的Snapshot副本 `~snapshot` 目录、即使手动输入的路径也是如此 `~snapshot` 目录或目录中的特定Snapshot副本。

当 `showsnapshot` 已启用共享属性、使用SMB 2.x的Windows客户端上的用户仍无法查看 `~snapshot` 目录位于共享根目录或共享根目录下的任何接合或目录中。但是、在连接到共享后、用户可以访问隐藏的 `~snapshot` 目录 `\~snapshot` 到共享路径的末尾。隐藏的 `~snapshot` 可从两个入口点访问目录：

* 位于共享的根目录
* 共享空间中的每个接合点


隐藏的 `~snapshot` 无法从共享中的非接合子目录访问目录。

.示例
对于以下示例中所示的配置、SMB 2.x连接到"`eng`"共享的Windows客户端上的用户可以访问 `~snapshot` 目录 `\~snapshot` 共享路径位于共享的根目录以及路径中的每个接合点。隐藏的 `~snapshot` 可从以下三个路径访问目录：

* `\\vs1\eng\~snapshot`
* `\\vs1\eng\projects1\~snapshot`
* `\\vs1\eng\projects2\~snapshot`


[listing]
----
cluster1::> volume show -vserver vs1 -fields volume,junction-path
vserver volume       junction-path
------- ------------ ----------------------------------------
vs1     vs1_root      /
vs1     vs1_vol1      /eng
vs1     vs1_vol2      /eng/projects1
vs1     vs1_vol3      /eng/projects2

cluster1::> vserver cifs share show
Vserver  Share   Path     Properties    Comment  ACL
-------- ------  -------  ----------    -------- ----------
vs1      eng     /eng     oplocks       -        Everyone / Full Control
                          changenotify
                          browsable
                          showsnapshot
----