---
permalink: smb-admin/access-snapshot-directories-clients-smb2-concept.html 
sidebar: sidebar 
keywords: method, access, snapshot, directory, windows, client, smb, data, store, copies, copy, how to access the snapshot directory from windows clients using smb 2.x 
summary: 使用 SMB 2.x 从 Windows 客户端访问 ~Snapshot 目录的方法与使用 SMB 1.0 的方法不同。使用 SMB 2.x 连接成功访问 Snapshot 副本中存储的数据时，您需要了解如何访问 ~Snapshot 目录。 
---
= 使用 SMB 2.x 从 Windows 客户端访问 ~Snapshot 目录
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用 SMB 2.x 从 Windows 客户端访问 `~snapshot` 目录的方法与 SMB 1.0 使用的方法不同。使用 SMB 2.x 连接成功访问 Snapshot 副本中存储的数据时，您需要了解如何访问 `~snapshot` 目录。

SVM 管理员可通过使用 Vserver CIFS 共享属性系列中的命令启用或禁用 `showsnapshot` share 属性来控制 Windows 客户端上的用户是否可以查看和访问共享上的 `~snapshot` 目录。

禁用 `showsnapshot` share 属性后，使用 SMB 2.x 的 Windows 客户端上的用户无法查看 `~snapshot` 目录，也无法访问 `~snapshot` 目录中的 Snapshot 副本，即使手动输入 `~snapshot` 目录或目录中特定 Snapshot 副本的路径也是如此。

启用 `showsnapshot` share 属性后，使用 SMB 2.x 的 Windows 客户端上的用户仍无法查看共享根目录或共享根目录下任何接合或目录中的 `~snapshot` 目录。但是，在连接到共享后，用户可以通过手动将 ` \~snapshot` 附加到共享路径的末尾来访问隐藏的 `~snapshot` 目录。可以从两个入口点访问隐藏的 `~snapshot` 目录：

* 位于共享的根目录
* 共享空间中的每个接合点


无法从共享中的非接合子目录访问隐藏的 `~snapshot` 目录。

.示例
使用以下示例中所示的配置，与 "`eng` " 共享建立 SMB 2.x 连接的 Windows 客户端上的用户可以通过手动将 ` \~snapshot` 附加到共享根目录和路径中每个接合点的共享路径来访问 `~snapshot` 目录。可以从以下三个路径访问隐藏的 `~snapshot` 目录：

* ` \\vs1\eng\~snapshot`
* ` \\vs1\eng\projects1\~snapshot`
* ` \\vs1\eng\projects2\~snapshot`


[listing]
----
cluster1::> volume show -vserver vs1 -fields volume,junction-path
vserver volume       junction-path
------- ------------ ----------------------------------------
vs1     vs1_root      /
vs1     vs1_vol1      /eng
vs1     vs1_vol2      /eng/projects1
vs1     vs1_vol3      /eng/projects2

cluster1::> vserver cifs share show
Vserver  Share   Path     Properties    Comment  ACL
-------- ------  -------  ----------    -------- ----------
vs1      eng     /eng     oplocks       -        Everyone / Full Control
                          changenotify
                          browsable
                          showsnapshot
----