---
permalink: smb-admin/add-home-directory-search-path-task.html 
sidebar: sidebar 
keywords: ontap, smb, directories, directory, add, path, add a home directory search path 
summary: 如果要使用 ONTAP SMB 主目录，必须至少添加一个主目录搜索路径。 
---
= 添加主目录搜索路径
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果要使用 ONTAP SMB 主目录，必须至少添加一个主目录搜索路径。

.关于此任务
您可以使用添加主目录搜索路径 `vserver cifs home-directory search-path add` 命令：

。 `vserver cifs home-directory search-path add` 命令会检查中指定的路径 `-path` 选项。如果指定的路径不存在，该命令将生成一条消息，提示您是否要继续。任您选择 `y` 或 `n`。如果您选择 `y` 要继续操作、ONTAP将创建搜索路径。但是，必须先创建目录结构，然后才能在主目录配置中使用搜索路径。如果选择不继续，则命令将失败；不会创建搜索路径。然后、您可以创建路径目录结构并重新运行 `vserver cifs home-directory search-path add` 命令：

.步骤
. 添加主目录搜索路径： `vserver cifs home-directory search-path add -vserver vserver -path path`
. 使用验证是否已成功添加搜索路径 `vserver cifs home-directory search-path show` 命令：


.示例
以下示例将添加路径 `/home1` 到SVM VS1上的主目录配置。

[listing]
----
cluster::> vserver cifs home-directory search-path add -vserver vs1 -path /home1

vs1::> vserver cifs home-directory search-path show
Vserver     Position Path
----------- -------- -----------------
vs1         1        /home1
----
以下示例将尝试添加路径 `/home2` 到SVM VS1上的主目录配置。此路径不存在。选择不继续。

[listing]
----
cluster::> vserver cifs home-directory search-path add -vserver vs1 -path /home2
Warning: The specified path "/home2" does not exist in the namespace
         belonging to Vserver "vs1".
Do you want to continue? {y|n}: n
----
.相关信息
xref:add-home-directory-share-task.adoc[添加主目录共享]
