---
permalink: smb-admin/add-remove-replace-trusted-domains-preferred-lists-task.html 
sidebar: sidebar 
keywords: add, remove, trust, domain, prefer, cifs, server, modify, list, configure, bidirectional, multidomain, name, mapping, search, add remove or replace trusted domains in preferred trusted domain list, replace 
summary: 您可以从 CIFS 服务器的首选受信任域列表中添加或删除受信任域，也可以修改当前列表。如果您配置了首选受信任域列表，则在执行多域名称映射搜索时，系统将使用此列表，而不是发现的双向受信任域。 
---
= 在首选列表中添加、删除或替换受信任的ONTAP SMB域
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在SMB服务器的首选受信任域列表中添加或删除受信任域、也可以修改当前列表。如果您配置了首选受信任域列表，则在执行多域名称映射搜索时，系统将使用此列表，而不是发现的双向受信任域。

.关于此任务
* 如果要向现有列表添加受信任域，则新列表将与现有列表合并，并在末尾放置新条目系统将按受信任域列表中显示的顺序搜索这些受信任域。
* 如果您要从现有列表中删除受信任域，但未指定列表，则会删除指定 Storage Virtual Machine （ SVM ）的整个受信任域列表。
* 如果修改现有受信任域列表，则新列表将覆盖现有列表。


[NOTE]
====
您应在首选受信任域列表中仅输入双向受信任域。即使您可以在首选域列表中输入出站或入站信任域，但在执行多域名称映射搜索时不会使用它们。ONTAP 会跳过单向域的条目，然后转到列表中的下一个双向受信任域。

====
.步骤
. 执行以下操作之一：
+
|===
| 如果要对首选受信任域列表执行以下操作 ... | 使用命令 ... 


 a| 
将受信任域添加到列表中
 a| 
`+vserver cifs domain name-mapping-search add -vserver _vserver_name_ -trusted-domains FQDN, ...+`



 a| 
从列表中删除受信任域
 a| 
`+vserver cifs domain name-mapping-search remove -vserver _vserver_name_ [-trusted-domains FQDN, ...]+`



 a| 
修改现有列表
 a| 
`+vserver cifs domain name-mapping-search modify -vserver _vserver_name_ -trusted-domains FQDN, ...+`

|===


.示例
以下命令会将两个受信任域（ cifs1.example.com 和 cifs2.example.com ）添加到 SVM vs1 使用的首选受信任域列表中：

[listing]
----
cluster1::> vserver cifs domain name-mapping-search add -vserver vs1 -trusted-domains cifs1.example.com, cifs2.example.com
----
以下命令将从 SVM vs1 使用的列表中删除两个受信任域：

[listing]
----
cluster1::> vserver cifs domain name-mapping-search remove -vserver vs1 -trusted-domains cifs1.example.com, cifs2.example.com
----
以下命令将修改 SVM vs1 使用的受信任域列表。新列表将替换原始列表：

[listing]
----
cluster1::> vserver cifs domain name-mapping-search modify -vserver vs1 -trusted-domains cifs3.example.com
----
.相关信息
xref:display-preferred-trusted-domain-list-task.adoc[显示有关首选受信任域列表的信息]
