---
permalink: smb-admin/add-privileges-local-domain-users-groups-task.html 
sidebar: sidebar 
keywords: manage, right, user, local, domain, add, privilege, override, default, object, enhance, customize, user, group, add privileges to local or domain users or groups 
summary: 您可以通过添加权限来管理本地或域用户或组的用户权限。添加的权限将覆盖分配给其中任何对象的默认权限。这样可以自定义用户或组的权限，从而增强安全性。 
---
= 向本地或域用户或组添加权限
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以通过添加权限来管理本地或域用户或组的用户权限。添加的权限将覆盖分配给其中任何对象的默认权限。这样可以自定义用户或组的权限，从而增强安全性。

.开始之前
要添加权限的本地或域用户或组必须已存在。

.关于此任务
向对象添加权限将覆盖该用户或组的默认权限。添加权限不会删除先前添加的权限。

在向本地或域用户或组添加权限时，必须牢记以下几点：

* 您可以添加一个或多个权限。
* 在向域用户或组添加权限时， ONTAP 可能会通过联系域控制器来验证域用户或组。
+
如果 ONTAP 无法与域控制器联系，则命令可能会失败。



.步骤
. 向本地或域用户或组添加一个或多个权限： `+vserver cifs users-and-groups privilege add-privilege -vserver _vserver_name_ -user-or-group-name name -privileges _privilege_[,...]+`
. 验证所需权限是否已应用于对象： `vserver cifs users-and-groups privilege show -vserver _vserver_name_ ‑user-or-group-name _name_`


.示例
以下示例将特权 `SeTcbPrivilege` 和 `SeTakeOwnershipPrivilege` 添加到 Storage Virtual Machine （ SVM ，以前称为 Vserver ） vs1 上的用户 "`CIFS_SERVER\sue` " 中：

[listing]
----
cluster1::> vserver cifs users-and-groups privilege add-privilege -vserver vs1 -user-or-group-name CIFS_SERVER\sue -privileges SeTcbPrivilege,SeTakeOwnershipPrivilege

cluster1::> vserver cifs users-and-groups privilege show -vserver vs1
Vserver   User or Group Name    Privileges
--------- --------------------- ---------------
vs1       CIFS_SERVER\sue       SeTcbPrivilege
                                SeTakeOwnershipPrivilege
----