---
permalink: smb-admin/add-list-netbios-aliases-server-task.html 
sidebar: sidebar 
keywords: smb, client, connect, cifs, server, alias, create, list, netbios 
summary: 如果您希望 SMB 客户端使用别名连接到 CIFS 服务器，您可以创建 NetBIOS 别名列表，也可以将 NetBIOS 别名添加到现有 NetBIOS 别名列表中。 
---
= 向 SMB 服务器添加 NetBIOS 别名列表
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您希望 SMB 客户端使用别名连接到 SMB 服务器，您可以创建 NetBIOS 别名列表，也可以将 NetBIOS 别名添加到现有 NetBIOS 别名列表中。

.关于此任务
* NetBIOS 别名长度最多可以为 15 个字符。
* 您最多可以在 SMB 服务器上配置 200 个 NetBIOS 别名。
* 不允许使用以下字符：
+
@ # * （） = + [ ] | ；： " ， < > \ / ？



.步骤
. 添加 NetBIOS 别名： + `vserver cifs add-netbios-aliases -vserver _vserver_name_ -netbios-aliases _netbios_alias_ ， ...`
+
`vserver cifs add-netbios-aliases -vserver vs1 -netbios-aliases alias_1 ， alias_2 ， alias_3`

+
** 您可以使用逗号分隔列表指定一个或多个 NetBIOS 别名。
** 指定的 NetBIOS 别名将添加到现有列表中。
** 如果 NetBIOS 别名列表当前为空，则会创建一个新的 NetBIOS 别名列表。


. 验证是否已正确添加 NetBIOS 别名： `vserver cifs show -vserver vserver_name -display-netbios-aliases`
+
`vserver cifs show -vserver vs1 -display-netbios-aliases`

+
[listing]
----
Vserver: vs1

         Server Name: CIFS_SERVER
         NetBIOS Aliases: ALIAS_1, ALIAS_2, ALIAS_3
----


xref:remove-netbios-aliases-from-list-task.adoc[从 NetBIOS 别名列表中删除 NetBIOS 别名]

xref:display-list-netbios-aliases-task.adoc[显示 CIFS 服务器上的 NetBIOS 别名列表]
