---
permalink: smb-admin/commands-manage-servers-reference.html 
sidebar: sidebar 
keywords: command, creating, create, display, modify, stop, start, deleting, delete 
summary: 您需要了解用于创建、显示、修改、停止、启动、 和删除SMB服务器。此外，还可以使用命令重置和重新发现服务器，更改或重置计算机帐户密码，计划更改计算机帐户密码以及添加或删除 NetBIOS 别名。 
---
= 用于管理SMB服务器的ONTAP命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您需要了解用于创建、显示、修改、停止、启动、 和删除SMB服务器。此外，还可以使用命令重置和重新发现服务器，更改或重置计算机帐户密码，计划更改计算机帐户密码以及添加或删除 NetBIOS 别名。

|===


| 如果您要 ... | 使用此命令 ... 


 a| 
创建SMB服务器
 a| 
`vserver cifs create`



 a| 
显示有关 SMB 服务器的信息
 a| 
`vserver cifs show`



 a| 
修改SMB服务器
 a| 
`vserver cifs modify`



 a| 
将 SMB 服务器移动到另一个域
 a| 
`vserver cifs modify`



 a| 
停止 SMB 服务器
 a| 
`vserver cifs stop`



 a| 
启动 SMB 服务器
 a| 
`vserver cifs start`



 a| 
删除SMB服务器
 a| 
`vserver cifs delete`



 a| 
重置和重新发现 SMB 服务器的服务器
 a| 
`vserver cifs domain discovered-servers reset-servers`



 a| 
更改SMB服务器的计算机帐户密码
 a| 
`vserver cifs domain password change`



 a| 
重置SMB服务器的计算机帐户密码
 a| 
`vserver cifs domain password change`



 a| 
为SMB服务器的计算机帐户计划自动密码更改
 a| 
`vserver cifs domain password schedule modify`



 a| 
为SMB服务器添加NetBIOS别名
 a| 
`vserver cifs add-netbios-aliases`



 a| 
删除SMB服务器的NetBIOS别名
 a| 
`vserver cifs remove-netbios-aliases`

|===
有关的详细信息 `vserver cifs`，请参见link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+cifs["ONTAP 命令参考"^]。

.相关信息
link:local-users-groups-when-deleting-servers-concept.html["删除SMB服务器时本地用户和组会发生什么情况"]
