---
permalink: smb-admin/commands-manage-ntfs-smb.html 
sidebar: sidebar 
keywords: ontap, command, managing, manage, security, descriptor, create, modify, delete, display, information, commands for managing ntfs security descriptors 
summary: '使用 ONTAP 命令在 DACL 和 SACL 中创建、修改、删除和显示有关 NTFS 安全描述符和访问控制条目 (ACE) 的信息。您还可以使用 ONTAP 命令管理 SMB 安全策略、策略任务和策略作业。' 
---
= 用于管理 NTFS 和 SMB 安全策略和访问控制条目的 ONTAP 命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用 ONTAP 命令在 DACL 和 SACL 中创建、修改、删除和显示有关 NTFS 安全描述符和访问控制条目 (ACE) 的信息。您还可以使用 ONTAP 命令管理 SMB 安全策略、策略任务和策略作业。



[[ontap-commands-for-managing-ntfs-security-descriptors-on-smb-servers]]
== 用于管理 SMB 服务器上的 NTFS 安全描述符的 ONTAP 命令

您可以使用特定的 ONTAP 命令来管理安全描述符。您可以创建，修改，删除和显示有关安全描述符的信息。

|===
| 如果您要 ... | 使用此命令 ... 


 a| 
创建 NTFS 安全描述符
 a| 
`vserver security file-directory ntfs create`



 a| 
修改现有 NTFS 安全描述符
 a| 
`vserver security file-directory ntfs modify`



 a| 
显示有关现有 NTFS 安全描述符的信息
 a| 
`vserver security file-directory ntfs show`



 a| 
删除 NTFS 安全描述符
 a| 
`vserver security file-directory ntfs delete`

|===
有关的详细信息 `vserver security file-directory ntfs`，请参见link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+security+file-directory+ntfs["ONTAP 命令参考"^]。



[[ontap-commands-for-managing-ntfs-dacl-access-control-entries-on-smb-servers]]
== 用于管理 SMB 服务器上的 NTFS DACL 访问控制条目的 ONTAP 命令

您可以使用特定的 ONTAP 命令来管理 DACL 访问控制条目（ ACE ）。您可以随时将 ACE 添加到 NTFS DACL 中。您还可以通过修改，删除和显示有关 DACL 中 ACE 的信息来管理现有 NTFS DACL 。

|===
| 如果您要 ... | 使用此命令 ... 


 a| 
创建 ACE 并将其添加到 NTFS DACL 中
 a| 
`vserver security file-directory ntfs dacl add`



 a| 
修改 NTFS DACL 中的现有 ACE
 a| 
`vserver security file-directory ntfs dacl modify`



 a| 
显示有关 NTFS DACL 中现有 ACE 的信息
 a| 
`vserver security file-directory ntfs dacl show`



 a| 
从 NTFS DACL 中删除现有 ACE
 a| 
`vserver security file-directory ntfs dacl remove`

|===
有关的详细信息 `vserver security file-directory ntfs dacl`，请参见link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+security+file-directory+ntfs+dacl["ONTAP 命令参考"^]。



[[ontap-commands-for-managing-ntfs-sacl-access-control-entries-on-smb-servers]]
== 用于管理 SMB 服务器上的 NTFS SACL 访问控制条目的 ONTAP 命令

您可以使用特定的ONTAP命令来管理SACL访问控制条目(Access Control entries、ACE)。您可以随时将 ACE 添加到 NTFS SACL 。您还可以通过修改，删除和显示有关 SACL 中 ACE 的信息来管理现有 NTFS SACL 。

|===
| 如果您要 ... | 使用此命令 ... 


 a| 
创建 ACE 并将其添加到 NTFS SACL
 a| 
`vserver security file-directory ntfs sacl add`



 a| 
修改 NTFS SACL 中的现有 ACE
 a| 
`vserver security file-directory ntfs sacl modify`



 a| 
显示有关 NTFS SACL 中现有 ACE 的信息
 a| 
`vserver security file-directory ntfs sacl show`



 a| 
从 NTFS SACL 中删除现有 ACE
 a| 
`vserver security file-directory ntfs sacl remove`

|===
有关的详细信息 `vserver security file-directory ntfs sacl`，请参见link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+security+file-directory+ntfs+sacl["ONTAP 命令参考"^]。



[[ontap-commands-for-managing-smb-security-policies]]
== 用于管理 SMB 安全策略的 ONTAP 命令

您可以使用特定的 ONTAP 命令来管理安全策略。您可以显示有关策略的信息，也可以删除策略。您不能修改安全策略。

|===
| 如果您要 ... | 使用此命令 ... 


 a| 
创建安全策略
 a| 
`vserver security file-directory policy create`



 a| 
显示有关安全策略的信息
 a| 
`vserver security file-directory policy show`



 a| 
删除安全策略
 a| 
`vserver security file-directory policy delete`

|===
有关的详细信息 `vserver security file-directory policy`，请参见link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+security+file-directory+policy["ONTAP 命令参考"^]。



[[ontap-commands-for-managing-smb-security-policy-tasks]]
== 用于管理 SMB 安全策略任务的 ONTAP 命令

您可以使用 ONTAP 命令添加，修改，删除和显示有关安全策略任务的信息。

|===
| 如果您要 ... | 使用此命令 ... 


 a| 
添加安全策略任务
 a| 
`vserver security file-directory policy task add`



 a| 
修改安全策略任务
 a| 
`vserver security file-directory policy task modify`



 a| 
显示有关安全策略任务的信息
 a| 
`vserver security file-directory policy task show`



 a| 
删除安全策略任务
 a| 
`vserver security file-directory policy task remove`

|===
有关的详细信息 `vserver security file-directory policy task`，请参见link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+security+file-directory+policy+task["ONTAP 命令参考"^]。



[[ontap-commands-for-managing-smb-security-policy-jobs]]
== 用于管理 SMB 安全策略作业的 ONTAP 命令

您可以使用 ONTAP 命令暂停，恢复，停止和显示有关安全策略作业的信息。

|===
| 如果您要 ... | 使用此命令 ... 


 a| 
暂停安全策略作业
 a| 
`vserver security file-directory job pause ‑vserver vserver_name -id integer`



 a| 
恢复安全策略作业
 a| 
`vserver security file-directory job resume ‑vserver vserver_name -id integer`



 a| 
显示有关安全策略作业的信息
 a| 
`vserver security file-directory job show ‑vserver vserver_name` 您可以使用此命令确定作业的作业ID。



 a| 
停止安全策略作业
 a| 
`vserver security file-directory job stop ‑vserver vserver_name -id integer`

|===
有关的详细信息 `vserver security file-directory job`，请参见link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+security+file-directory+job["ONTAP 命令参考"^]。
