---
permalink: smb-admin/commands-manage-servers-reference.html 
sidebar: sidebar 
keywords: command, creating, create, display, modify, stop, start, deleting, delete 
summary: 您需要了解用于创建，显示，修改，停止，启动， 和删除 CIFS 服务器。此外，还可以使用命令重置和重新发现服务器，更改或重置计算机帐户密码，计划更改计算机帐户密码以及添加或删除 NetBIOS 别名。 
---
= 用于管理 CIFS 服务器的命令
:icons: font
:imagesdir: ../media/


[role="lead"]
您需要了解用于创建，显示，修改，停止，启动， 和删除 CIFS 服务器。此外，还可以使用命令重置和重新发现服务器，更改或重置计算机帐户密码，计划更改计算机帐户密码以及添加或删除 NetBIOS 别名。

|===
| 如果您要 ... | 使用此命令 ... 


 a| 
创建 CIFS 服务器
 a| 
`Vserver cifs create`



 a| 
显示有关 CIFS 服务器的信息
 a| 
`vserver cifs show`



 a| 
修改 CIFS 服务器
 a| 
`Vserver cifs modify`



 a| 
将 CIFS 服务器移动到另一个域
 a| 
`Vserver cifs modify`



 a| 
停止 CIFS 服务器
 a| 
`Vserver cifs stop`



 a| 
启动 CIFS 服务器
 a| 
`Vserver cifs start`



 a| 
删除 CIFS 服务器
 a| 
`Vserver cifs delete`



 a| 
重置并重新发现 CIFS 服务器的服务器
 a| 
`Vserver cifs domain discovered-servers reset-servers`



 a| 
更改 CIFS 服务器的计算机帐户密码
 a| 
`Vserver CIFS 域密码更改`



 a| 
重置 CIFS 服务器的计算机帐户密码
 a| 
`Vserver CIFS 域密码更改`



 a| 
为 CIFS 服务器的计算机帐户计划自动密码更改
 a| 
`vserver cifs domain password schedule modify`



 a| 
为 CIFS 服务器添加 NetBIOS 别名
 a| 
`Vserver cifs add-netbios-aliases`



 a| 
删除 CIFS 服务器的 NetBIOS 别名
 a| 
`Vserver cifs remove-netbios-aliases`

|===
有关详细信息，请参见每个命令的手册页。

* 相关信息 *

xref:local-users-groups-when-deleting-servers-concept.adoc[删除 CIFS 服务器时本地用户和组会发生什么情况]
