---
permalink: smb-admin/configure-required-encryption-concept.html 
sidebar: sidebar 
keywords: smb, encryption, data, transfer, security, enhancement, enable, disable, server, configure, desire, share-by-share, basis, property, setting, configure, configure required smb encryption on smb servers for data transfer over smb 
summary: 通过 SMB 进行数据传输的 SMB 加密是一种安全增强功能，您可以在 SMB 服务器上启用或禁用此功能。您还可以通过共享属性设置在共享基础上配置所需的 SMB 加密设置。 
---
= 了解ONTAP SMB加密
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过 SMB 进行数据传输的 SMB 加密是一种安全增强功能，您可以在 SMB 服务器上启用或禁用此功能。您还可以通过共享属性设置在共享基础上配置所需的 SMB 加密设置。

默认情况下、在Storage Virtual Machine (SVM)上创建SMB服务器时、SMB加密处于禁用状态。您必须启用 SMB 加密才能利用 SMB 加密提供的增强安全性。

要创建加密的 SMB 会话， SMB 客户端必须支持 SMB 加密。从 Windows Server 2012 和 Windows 8 开始的 Windows 客户端支持 SMB 加密。

SVM 上的 SMB 加密通过两种设置控制：

* 在SVM上启用此功能的SMB服务器安全选项
* 一种SMB共享属性、用于基于共享配置SMB加密设置


您可以决定是否要求加密以访问 SVM 上的所有数据，或者要求 SMB 加密以仅访问所选共享中的数据。 `encrypt-data` 共享属性需要 SMB 加密才能访问共享。从 ONTAP 9.11.1 开始， `allow-unencrypted-access` 共享属性允许 SMB2 客户端在启用  `encrypt-data` 时无需加密即可访问共享，而 SMB3 客户端则继续使用加密。

SVM 级别设置取代共享级别设置。

有效的 SMB 加密配置取决于这两种设置的组合，下表对此进行了介绍：

|===
| 已启用 SMB 服务器 SMB 加密 | 已启用共享加密数据设置 | 共享允许未加密访问设置已启用 | 服务器端加密行为 


 a| 
true
 a| 
false
 a| 
false
 a| 
已为 SVM 中的所有共享启用服务器级别加密。使用此配置时，整个 SMB 会话都会进行加密。



 a| 
true
 a| 
true
 a| 
false
 a| 
无论共享级别加密如何， SVM 中的所有共享都会启用服务器级别加密。使用此配置时，整个 SMB 会话都会进行加密。



 a| 
false
 a| 
true
 a| 
false
 a| 
已为特定共享启用共享级别加密。SMB3 客户端使用加密，但 SMB2 客户端可以在没有加密的情况下访问共享，因为 `allow-unencrypted-access`属性已启用。



 a| 
false
 a| 
false
 a| 
false
 a| 
未启用加密。



 a| 
false
 a| 
false
 a| 
true
 a| 
未启用任何加密。除非启用了  `encrypt-data`，否则  `allow-unencrypted-access` 属性无效。

|===
不支持加密的SMB客户端无法连接到需要加密的SMB服务器或共享。

对加密设置所做的更改将对新连接生效。现有连接不受影响。


NOTE: 从 ONTAP 9.11.1 开始支持 `allow-unencrypted-access`属性。


NOTE: SVM 级 SMB 加密将覆盖共享级设置。
