---
permalink: smb-admin/configure-metadata-cache-smb.html 
sidebar: sidebar 
keywords: enable, smb, metadata, cache, store, path, file, attribute, data, performance, client, workload, how smb metadata caching works 
summary: 启用后， SMB 元数据缓存会将路径和文件属性数据存储一段有限的时间。这样可以提高具有常见工作负载的 SMB 1.0 客户端的 SMB 性能。 
---
= 为 SMB 共享配置元数据缓存
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过元数据缓存， SMB 1.0 客户端上的文件属性缓存可以更快地访问文件和文件夹属性。您可以基于每个共享启用或禁用属性缓存。如果启用了元数据缓存，您还可以为缓存条目配置生存时间。如果客户端通过 SMB 2.x 或 SMB 3.0 连接到共享，则无需配置元数据缓存。

启用后， SMB 元数据缓存会将路径和文件属性数据存储一段有限的时间。这样可以提高具有常见工作负载的 SMB 1.0 客户端的 SMB 性能。

对于某些任务， SMB 会创建大量流量，其中可能包括对路径和文件元数据的多个相同查询。您可以改用 SMB 元数据缓存从缓存中提取信息，从而减少冗余查询的数量并提高 SMB 1.0 客户端的性能。

[NOTE]
====
元数据缓存虽然不太可能为 SMB 1.0 客户端提供过时的信息。如果您的环境无法承担此风险，则不应启用此功能。

====


== 启用 ONTAP SMB 元数据缓存

您可以通过启用 SMB 元数据缓存来提高 SMB 1.0 客户端的 SMB 性能。默认情况下， SMB 元数据缓存处于禁用状态。

.步骤
. 在新的或现有共享上启用 SMB 元数据缓存：
+
** 创建新共享时启用 SMB 元数据缓存：
+
[source, cli]
----
vserver cifs share create -vserver <SVM_name> -share-name <share_name> -path <path> -share-properties attributecache
----
** 在现有共享上启用 SMB 元数据缓存：
+
[source, cli]
----
vserver cifs share properties add -vserver <SVM_name> -share-name <share_name> -share-properties attributecache
----






== 配置 ONTAP SMB 元数据缓存条目的生命周期

您可以配置 SMB 元数据缓存条目的生命周期，以优化环境中的 SMB 元数据缓存性能。默认值为10秒。

.开始之前
您必须已启用 SMB 元数据缓存功能。如果未启用 SMB 元数据缓存，则不会使用 SMB 缓存 TTL 设置。

.步骤
. 在新的或现有共享上配置 SMB 元数据缓存条目的生存期：
+
** 创建新共享时配置 SMB 元数据缓存条目的生存期：
+
[source, cli]
----
vserver cifs share create -vserver <SVM_name> -share-name <share_name> -path <path> -attribute-cache-ttl [integerh][integerm][integers]
----
** 在现有共享上配置 SMB 元数据缓存条目的生存期：
+
[source, cli]
----
vserver cifs share modify -vserver <SVM_name> -share-name <share_name> -attribute-cache-ttl [integerh][integerm][integers]
----




您可以在创建或修改共享时指定其他共享配置选项和属性。有关的详细信息 `vserver cifs share`，请参见link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+cifs+share["ONTAP 命令参考"^]。
