---
permalink: smb-admin/configure-guest-unix-user-task.html 
sidebar: sidebar 
keywords: configuring, configure, guest, unix, user, untrusted, domain, map, connect, cifs, server, configure the guest unix user 
summary: 配置子系统 UNIX 用户选项意味着，从不可信域登录的用户将映射到子系统 UNIX 用户，并可连接到 CIFS 服务器。或者，如果您希望对来自不可信域的用户进行身份验证失败，则不应配置子系统 UNIX 用户。默认情况下，不允许来自不可信域的用户连接到 CIFS 服务器（未配置来宾 UNIX 帐户）。 
---
= 配置子系统 UNIX 用户
:icons: font
:imagesdir: ../media/


[role="lead"]
配置子系统 UNIX 用户选项意味着，从不可信域登录的用户将映射到子系统 UNIX 用户，并可连接到 CIFS 服务器。或者，如果您希望对来自不可信域的用户进行身份验证失败，则不应配置子系统 UNIX 用户。默认情况下，不允许来自不可信域的用户连接到 CIFS 服务器（未配置来宾 UNIX 帐户）。

配置子系统 UNIX 帐户时，应记住以下几点：

* 如果 CIFS 服务器无法根据主域，受信任域或本地数据库的域控制器对用户进行身份验证，并且启用了此选项，则 CIFS 服务器会将该用户视为来宾用户，并将该用户映射到指定的 UNIX 用户。
* 如果此选项设置为空字符串，则会禁用子系统 UNIX 用户。
* 您必须创建一个 UNIX 用户，以用作其中一个 Storage Virtual Machine （ SVM ）名称服务数据库中的子系统 UNIX 用户。
* 以来宾用户身份登录的用户会自动成为 CIFS 服务器上 BUILTIN\guests 组的成员。
* "homedirs-public" 选项仅适用于经过身份验证的用户。以来宾用户身份登录的用户没有主目录，无法访问其他用户的主目录。


.步骤
. 执行以下操作之一：
+
|===
| 如果您要 ... | 输入 ... 


 a| 
配置子系统 UNIX 用户
 a| 
`vserver cifs options modify -guest-unix-user _unix_name_`



 a| 
禁用子系统 UNIX 用户
 a| 
`vserver cifs options modify -guest-unix-user ""`

|===
+
`vserver cifs options modify -guest-unix-user pcuser`

. 验证是否已正确配置子系统 UNIX 用户： `vserver cifs options show -vserver _vserver_name_`
+
在以下示例中， SVM vs1 上的默认 UNIX 用户和子系统 UNIX 用户均配置为使用 UNIX 用户 "`pcuser` " ：

+
`vserver cifs options show -vserver vs1`

+
[listing]
----

Vserver: vs1

  Client Session Timeout : 900
  Default Unix Group     : -
  Default Unix User      : pcuser
  Guest Unix User        : pcuser
  Read Grants Exec       : disabled
  Read Only Delete       : disabled
  WINS Servers           : -
----

