---
permalink: smb-admin/create-branchcache-enabled-share-task.html 
sidebar: sidebar 
keywords: enable, branchcache, smb, create, share, setting, property, create a bracnhcache-enabled smb share 
summary: 通过设置 BranchCache 共享属性，您可以在创建共享时在 SMB 共享上启用 BranchCache 。 
---
= 创建启用 BranchCache 的 ONTAP SMB 共享
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过设置创建共享时、您可以在SMB共享上启用anchCache `branchcache` 共享属性。

.关于此任务
* 如果在 SMB 共享上启用了 BranchCache ，则该共享必须将脱机文件配置设置为手动缓存。
+
这是创建共享时的默认设置。

* 您还可以在创建启用了 BranchCache 的共享时指定其他可选共享参数。
* 您可以设置 `branchcache` 属性、即使未在Storage Virtual Machine (SVM)上配置和启用了anchCache也是如此。
+
但是，如果您希望共享提供缓存的内容，则必须在 SVM 上配置并启用 BranchCache 。

* 因为使用时不会应用于共享的默认共享属性 `-share-properties` 参数、则除了之外、您还必须指定要应用于共享的所有其他共享属性 `branchcache` 共享属性。
* 有关的详细信息 `vserver cifs share create`，请参见link:https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-share-create.html["ONTAP 命令参考"^]。


.步骤
. 创建启用了anchCache的SMB共享：+
`vserver cifs share create -vserver _vserver_name_ -share-name _share_name_ -path _path_ -share-properties branchcache[,...]`
. 使用验证是否已在SMB共享上设置了anchCache共享属性 `vserver cifs share show` 命令：


.示例
以下命令将使用路径创建一个名为`data`的已启用了anchCache的SMB共享 `/data` 在SVM VS1上。默认情况下、脱机文件设置设置为 `manual`：

[listing]
----
cluster1::> vserver cifs share create -vserver vs1 -share-name data -path /data -share-properties branchcache,oplocks,browsable,changenotify

cluster1::> vserver cifs share show -vserver vs1 -share-name data
                      Vserver: vs1
                        Share: data
     CIFS Server NetBIOS Name: VS1
                         Path: /data
             Share Properties: branchcache
                               oplocks
                               browsable
                               changenotify
           Symlink Properties: enable
      File Mode Creation Mask: -
 Directory Mode Creation Mask: -
                Share Comment: -
                    Share ACL: Everyone / Full Control
File Attribute Cache Lifetime: -
                  Volume Name: data
                Offline Files: manual
Vscan File-Operations Profile: standard
----
.相关信息
xref:disable-branchcache-single-share-task.adoc[在单个共享上禁用 BranchCache]
