---
permalink: smb-admin/create-share-access-control-lists-task.html 
sidebar: sidebar 
keywords: configuring, configure, permission, share, creating, create, control, list, acl, smb, enable, level, access, user, group, create smb share access control lists 
summary: '通过为SMB共享创建访问控制列表(ACL)来配置共享权限允许您控制用户和组对共享的访问级别。' 
---
= 创建ONTAP SMB共享访问控制列表
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过为 SMB 共享创建访问控制列表（ ACL ）来配置共享权限，可以控制用户和组对共享的访问级别。

.关于此任务
您可以使用本地或域 Windows 用户或组名称或 UNIX 用户或组名称来配置共享级 ACL 。

在创建新ACL之前、应删除默认共享ACL `Everyone / Full Control`，这会带来安全风险。

在工作组模式下，本地域名为 SMB 服务器名称。

.步骤
. 删除默认共享ACL：`vserver cIFs share access-control delete -vserver <vserver_name>-share <share_name>-user-or-group Everyone`
. 配置新 ACL ：
+
|===
| 如果要使用配置 ACL ，请使用 ... | 输入命令 ... 


 a| 
Windows 用户
 a| 
`vserver cifs share access-control create -vserver <vserver_name> -share <share_name> -user-group-type windows -user-or-group <Windows_domain_name\user_name> -permission <access_right>`



 a| 
Windows 组
 a| 
`vserver cifs share access-control create -vserver <vserver_name> -share <share_name> -user-group-type windows -user-or-group <Windows_domain_name\group_name> -permission <access_right>`



 a| 
UNIX 用户
 a| 
`vserver cifs share access-control create -vserver <vserver_name> -share <share_name> -user-group-type <unix-user> -user-or-group <UNIX_user_name> -permission <access_right>`



 a| 
UNIX 组
 a| 
`vserver cifs share access-control create -vserver <vserver_name> -share <share_name> -user-group-type <unix-group> -user-or-group <UNIX_group_name> -permission <access_right>`

|===
. 使用验证应用于共享的ACL是否正确 `vserver cifs share access-control show` 命令：


.示例
以下命令提供 `Change` 在"`Svs1.example.com``s```"SVM：

[listing]
----
cluster1::> vserver cifs share access-control create -vserver vs1.example.com -share sales -user-or-group "DOMAIN\Sales Team" -permission Change

cluster1::> vserver cifs share access-control show -vserver vs1.example.com
                 Share       User/Group              User/Group  Access
Vserver          Name        Name                    Type        Permission
---------------- ----------- --------------------    ---------   -----------
vs1.example.com  c$          BUILTIN\Administrators  windows     Full_Control
vs1.example.com  sales       DOMAIN\Sales Team     windows     Change
----
以下命令会为 `Read`vs2.example.com SVM上的"enging"共享提供"enging" UNIX组的权限：

[listing]
----
cluster1::> vserver cifs share access-control create -vserver vs2.example.com -share eng -user-group-type unix-group -user-or-group  engineering -permission Read

cluster1::> vserver cifs share access-control show -vserver vs2.example.com
                 Share       User/Group               User/Group  Access
Vserver          Name        Name                     Type        Permission
---------------- ----------- -------------------      ----------- -----------
vs2.example.com  c$          BUILTIN\Administrators   windows     Full_Control
vs2.example.com  eng         engineering              unix-group  Read
----
以下命令会为 `Change` `Full_Control`"VS1" SVM上的"datavol5"共享向本地Windows组"老虎 小组"和本地Windows用户"Sue Chang"授予权限：

[listing]
----
cluster1::> vserver cifs share access-control create -vserver vs1 -share datavol5 -user-group-type windows -user-or-group "Tiger Team" -permission Change

cluster1::> vserver cifs share access-control create -vserver vs1 -share datavol5 -user-group-type windows -user-or-group "Sue Chang" -permission Full_Control

cluster1::> vserver cifs share access-control show -vserver vs1
               Share       User/Group                  User/Group  Access
Vserver        Name        Name                        Type        Permission
-------------- ----------- --------------------------- ----------- -----------
vs1            c$          BUILTIN\Administrators      windows     Full_Control
vs1            datavol5    Tiger Team         windows     Change
vs1            datavol5    Sue Chang          windows     Full_Control
----