---
permalink: smb-admin/delete-branchcache-config-task.html 
sidebar: sidebar 
keywords: command, deleting, delete, branchcache, service, storage, virtual, machine, svm, exist, hash, delete the branchcache configuration 
summary: 用于删除存储虚拟机上 BranchCache 服务的命令因要删除或保留现有哈希而异。 
---
= 删除 ONTAP SMB 共享上的 BranchCache 配置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果先前已配置 BranchCache ，但不希望 Storage Virtual Machine （ SVM ）继续提供缓存的内容，则可以删除 CIFS 服务器上的 BranchCache 配置。您必须了解删除配置时会发生什么情况。

删除配置时， ONTAP 会从集群中删除该 SVM 的配置信息并停止 BranchCache 服务。您可以选择 ONTAP 是否应删除 SVM 上的哈希存储。

删除 BranchCache 配置不会中断已启用 BranchCache 的客户端的访问。此后，当启用了 BranchCache 的客户端请求有关已缓存内容的现有 SMB 连接的元数据信息时， ONTAP 将做出响应并显示 Microsoft 定义的错误，这将导致客户端发送第二个请求，请求实际内容。在响应内容请求时， CIFS 服务器会发送存储在 SVM 上的实际内容

删除 BranchCache 配置后， SMB 共享不会公布 BranchCache 功能。要访问以前未使用新 SMB 连接缓存的内容，客户端会发出正常的读取 SMB 请求。

用于删除 Storage Virtual Machine （ SVM ）上的 BranchCache 服务的命令会有所不同，具体取决于您是要删除还是保留现有哈希。

.步骤
. 运行相应的命令：
+
|===
| 如果您要 ... | 然后输入以下内容 ... 


 a| 
删除 BranchCache 配置并删除现有哈希
 a| 
`vserver cifs branchcache delete -vserver _vserver_name_ -flush-hashes true`



 a| 
删除 BranchCache 配置，但保留现有哈希
 a| 
`vserver cifs branchcache delete -vserver _vserver_name_ -flush-hashes false`

|===


.示例
以下示例将删除 SVM vs1 上的 BranchCache 配置并删除所有现有哈希：

[listing]
----
cluster1::> vserver cifs branchcache delete -vserver vs1 -flush-hashes true
----