---
permalink: smb-admin/determine-snapshot-copies-available-task.html 
sidebar: sidebar 
keywords: view, snapshot, copies, copy, previous, version, enable, policy, applied, apply, contain, share, previous, version, access, determine whether snapshot copies are available for previous versions use 
summary: 只有当已启用的 Snapshot 策略应用于包含共享的卷，并且卷配置允许访问 Snapshot 副本时，才能从先前版本选项卡查看 Snapshot 副本。在帮助用户访问先前版本时，确定 Snapshot 副本可用性非常有用。 
---
= 确定先前版本是否可以使用 Snapshot 副本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
只有当已启用的 Snapshot 策略应用于包含共享的卷，并且卷配置允许访问 Snapshot 副本时，才能从先前版本选项卡查看 Snapshot 副本。在帮助用户访问先前版本时，确定 Snapshot 副本可用性非常有用。

.步骤
. 确定共享数据所在的卷是否已启用自动 Snapshot 副本，以及客户端是否有权访问 Snapshot 目录： `volume show -vserver vserver-name -volume volume-name -fields vserver ， volume ， snapdir-access ， snapshot-policy ， snapshot-count`
+
输出将显示与卷关联的 Snapshot 策略，是否启用了客户端 Snapshot 目录访问以及可用 Snapshot 副本的数量。

. 确定是否已启用关联的 Snapshot 策略： `volume snapshot policy show -policy policy-name`
. 列出可用的 Snapshot 副本： `volume snapshot show -volume volume_name`
+
有关配置和管理 Snapshot 策略和 Snapshot 计划的详细信息，请参见 link:../data-protection/index.html["数据保护"]。



.示例
以下示例显示了与名为 `data1` 的卷关联的 Snapshot 策略的信息，该卷包含 " `data1` " 上的共享数据和可用 Snapshot 副本。

[listing]
----
cluster1::> volume show -vserver vs1 -volume data1 -fields vserver,volume,snapshot-policy,snapdir-access,snapshot-count
vserver  volume snapdir-access snapshot-policy snapshot-count
-------- ------ -------------- --------------- --------------
vs1      data1  true           default         10

cluster1::> volume snapshot policy show -policy default
Vserver: cluster1
                   Number of Is
Policy Name        Schedules Enabled Comment
------------------ --------- ------- ----------------------------------
default                    3 true    Default policy with hourly, daily & weekly schedules.
    Schedule         Count     Prefix                 SnapMirror Label
    ---------------- -----     ---------------------- -------------------
    hourly               6     hourly                 -
    daily                2     daily                  daily
    weekly               2     weekly                 weekly

cluster1::> volume snapshot show -volume data1
                                                             ---Blocks---
Vserver  Volume  Snapshot                  State        Size Total% Used%
-------- ------- ------------------------- -------- -------- ------ -----
vs1      data1
                 weekly.2012-12-16_0015    valid       408KB     0%    1%
                 daily.2012-12-22_0010     valid       420KB     0%    1%
                 daily.2012-12-23_0010     valid       192KB     0%    0%
                 weekly.2012-12-23_0015    valid       360KB     0%    1%
                 hourly.2012-12-23_1405    valid       196KB     0%    0%
                 hourly.2012-12-23_1505    valid       196KB     0%    0%
                 hourly.2012-12-23_1605    valid       212KB     0%    0%
                 hourly.2012-12-23_1705    valid       136KB     0%    0%
                 hourly.2012-12-23_1805    valid       200KB     0%    0%
                 hourly.2012-12-23_1905    valid       184KB     0%    0%
----
.相关信息
xref:create-snapshot-config-previous-versions-access-task.adoc[创建 Snapshot 配置以启用先前版本的访问]

link:../data-protection/index.html["数据保护"]
