---
permalink: smb-admin/determine-snapshot-copies-available-task.html 
sidebar: sidebar 
keywords: view, snapshot, copies, copy, previous, version, enable, policy, applied, apply, contain, share, previous, version, access, determine whether snapshot copies are available for previous versions use 
summary: 只有当已启用的快照策略应用于包含共享的卷且卷配置允许访问快照时、才能从先前版本选项卡查看快照。在帮助用户访问先前版本时、确定快照可用性非常有用。 
---
= 确定 ONTAP SMB 快照是否可供先前版本使用
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
只有当已启用的快照策略应用于包含共享的卷且卷配置允许访问快照时、才能从先前版本选项卡查看快照。在帮助用户访问先前版本时、确定快照可用性非常有用。

.步骤
. 确定共享数据所在的卷是否已启用自动快照、以及客户端是否有权访问快照目录： `volume show -vserver vserver-name -volume volume-name -fields vserver,volume,snapdir-access,snapshot-policy,snapshot-count`
+
输出将显示与卷关联的快照策略、是否已启用客户端快照目录访问以及可用快照的数量。

. 确定是否已启用关联的Snapshot策略： `volume snapshot policy show -policy policy-name`
. 列出可用快照： `volume snapshot show -volume volume_name`
+
有关配置和管理快照策略和快照计划的详细信息，请参见link:../data-protection/index.html["数据保护"]。



.示例
以下示例显示了与名为`data1`的卷关联的快照策略的信息、该卷包含`data1`上的共享数据和可用快照。

[listing]
----
cluster1::> volume show -vserver vs1 -volume data1 -fields vserver,volume,snapshot-policy,snapdir-access,snapshot-count
vserver  volume snapdir-access snapshot-policy snapshot-count
-------- ------ -------------- --------------- --------------
vs1      data1  true           default         10

cluster1::> volume snapshot policy show -policy default
Vserver: cluster1
                   Number of Is
Policy Name        Schedules Enabled Comment
------------------ --------- ------- ----------------------------------
default                    3 true    Default policy with hourly, daily & weekly schedules.
    Schedule         Count     Prefix                 SnapMirror Label
    ---------------- -----     ---------------------- -------------------
    hourly               6     hourly                 -
    daily                2     daily                  daily
    weekly               2     weekly                 weekly

cluster1::> volume snapshot show -volume data1
                                                             ---Blocks---
Vserver  Volume  Snapshot                  State        Size Total% Used%
-------- ------- ------------------------- -------- -------- ------ -----
vs1      data1
                 weekly.2012-12-16_0015    valid       408KB     0%    1%
                 daily.2012-12-22_0010     valid       420KB     0%    1%
                 daily.2012-12-23_0010     valid       192KB     0%    0%
                 weekly.2012-12-23_0015    valid       360KB     0%    1%
                 hourly.2012-12-23_1405    valid       196KB     0%    0%
                 hourly.2012-12-23_1505    valid       196KB     0%    0%
                 hourly.2012-12-23_1605    valid       212KB     0%    0%
                 hourly.2012-12-23_1705    valid       136KB     0%    0%
                 hourly.2012-12-23_1805    valid       200KB     0%    0%
                 hourly.2012-12-23_1905    valid       184KB     0%    0%
----
.相关信息
xref:create-snapshot-config-previous-versions-access-task.adoc[创建快照配置以启用先前版本访问]

link:../data-protection/index.html["数据保护"]
