---
permalink: smb-admin/disallow-users-groups-bypass-directory-traverse-task.html 
sidebar: sidebar 
keywords: user, traverse, directories, directory, path, file, permission, sechangenotifyprivilege, privilege, local, smb, group, storage, virtual, machine, svm, disallow users or groups from bypassing directory traverse checking 
summary: 如果您不希望用户遍历路径中的所有目录以访问某个文件，因为该用户对遍历的目录没有权限，则可以从 Storage Virtual Machine （ SVM ）上的本地 SMB 用户或组中删除 SeChangeNotifyPrivilege 权限。 
---
= 禁止用户或组绕过目录遍历检查
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您不希望用户遍历路径中的所有目录以访问某个文件，因为该用户对遍历的目录没有权限，则可以从 Storage Virtual Machine （ SVM ）上的本地 SMB 用户或组中删除 `SeChangeNotifyPrivilege` 权限。

要从中删除权限的本地或域用户或组必须已存在。

从域用户或组中删除权限时， ONTAP 可能会通过联系域控制器来验证域用户或组。如果 ONTAP 无法与域控制器联系，则此命令可能会失败。

.步骤
. 禁止绕过遍历检查： `vserver cifs users-and-groups privilege remove-privilege -vserver _vserver_name_ -user-or-group-name _name_ -privileges SeChangeNotifyPrivilege`
+
命令会从您使用 ` -user-or-group-name _name_` 参数值指定的本地或域用户或组中删除 `SeChangeNotifyPrivilege` 权限。

. 验证指定的用户或组是否已禁用绕过遍历检查： `vserver cifs users-and-groups privilege show -vserver _vserver_name_ ‑user-or-group-name _name_`


以下命令禁止属于 "`example\eng` " 组的用户绕过目录遍历检查：

[listing]
----
cluster1::> vserver cifs users-and-groups privilege show -vserver vs1
Vserver   User or Group Name    Privileges
--------- --------------------- -----------------------
vs1       EXAMPLE\eng           SeChangeNotifyPrivilege

cluster1::> vserver cifs users-and-groups privilege remove-privilege -vserver vs1 -user-or-group-name EXAMPLE\eng -privileges SeChangeNotifyPrivilege

cluster1::> vserver cifs users-and-groups privilege show -vserver vs1
Vserver   User or Group Name    Privileges
--------- --------------------- -----------------------
vs1       EXAMPLE\eng           -
----
* 相关信息 *

xref:allow-users-groups-bypass-directory-traverse-task.adoc[允许用户或组绕过目录遍历检查]
