---
permalink: smb-admin/display-nfsv4-audit-policies-flexvol-volumes-task.html 
sidebar: sidebar 
keywords: display, information, nfsv4, audit, policies, policy, flexvol, volume, ontap, cli, security, style, permission, applied, apply, system, access, control, lists, sacl, result, validate, security, display information about nfsv4 audit policies on flexvol volumes using cli 
summary: 您可以使用 ONTAP 命令行界面显示有关 FlexVol 卷上 NFSv4 审核策略的信息，包括什么是安全模式和有效安全模式，应用了哪些权限以及有关系统访问控制列表（ SACL ）的信息。您可以使用结果验证安全配置或对审核问题进行故障排除。 
---
= 使用命令行界面显示有关 FlexVol 卷上 NFSv4 审核策略的信息
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 ONTAP 命令行界面显示有关 FlexVol 卷上 NFSv4 审核策略的信息，包括什么是安全模式和有效安全模式，应用了哪些权限以及有关系统访问控制列表（ SACL ）的信息。您可以使用结果验证安全配置或对审核问题进行故障排除。

.关于此任务
您必须提供 Storage Virtual Machine （ SVM ）的名称以及要显示其审核信息的文件或目录的路径。您可以摘要形式或详细列表形式显示输出。

* UNIX 安全模式卷和 qtree 仅对审核策略使用 NFSv4 SACL 。
* 混合安全模式卷中采用 UNIX 安全模式的文件和目录可以应用 NFSv4 审核策略。
+
混合安全模式卷和 qtree 可以包含一些使用 UNIX 文件权限的文件和目录，模式位或 NFSv4 ACL ，以及一些使用 NTFS 文件权限的文件和目录。

* 混合安全模式卷的顶层可以具有 UNIX 或 NTFS 有效安全性，并且可能包含也可能不包含 NFSv4 SACL 。
* 只有采用 NTFS 或 NFSv4 安全模式的文件和文件夹才会显示 ACL 输出。
+
对于使用 UNIX 安全性且仅应用模式位权限（无 NFSv4 ACL ）的文件和文件夹，此字段为空。

* ACL 输出中的所有者和组输出字段仅适用于 NTFS 安全描述符。
* 由于即使卷根或 qtree 的有效安全模式为 UNIX ，也可以在混合安全模式卷或 qtree 上配置存储级别访问防护安全性， 配置了存储级别访问防护的卷或 qtree 路径的输出可能会同时显示常规 NFSv4 文件和目录 SACL 以及存储级别访问防护 NTFS SACL 。
* 由于如果在 SVM 上配置了 CIFS 服务器，则 UNIX 卷或 qtree 支持存储级别访问防护安全性，因此输出可能包含应用于在 ` 路径` 参数中指定的卷或 qtree 的存储级别访问防护安全性的信息。


.步骤
. 使用所需的详细信息级别显示文件和目录安全设置：
+
|===
| 要显示信息的项 | 输入以下命令 ... 


 a| 
摘要形式
 a| 
`vserver security file-directory show -vserver vserver_name -path path`



 a| 
扩展了详细信息
 a| 
`vserver security file-directory show -vserver vserver_name -path path -expand-mask true`

|===


.示例
以下示例显示了 SVM vs1 中路径 ` /lab` 的安全信息。此 UNIX 安全模式路径具有 NFSv4 SACL 。

[listing]
----
cluster::> vserver security file-directory show -vserver vs1 -path /lab

                Vserver: vs1
              File Path: /lab
      File Inode Number: 288
         Security Style: unix
        Effective Style: unix
         DOS Attributes: 11
 DOS Attributes in Text: ----D--R
Expanded Dos Attributes: -
           Unix User Id: 0
          Unix Group Id: 0
         Unix Mode Bits: 0
 Unix Mode Bits in Text: ---------
                   ACLs: NFSV4 Security Descriptor
                         Control:0x8014
                         SACL - ACEs
                           SUCCESSFUL-S-1-520-0-0xf01ff-SA
                           FAILED-S-1-520-0-0xf01ff-FA
                         DACL - ACEs
                           ALLOW-S-1-520-1-0xf01ff
----