---
permalink: smb-admin/display-dynamic-access-control-security-task.html 
sidebar: sidebar 
keywords: display, information, dynamic, access, control, dac, security, ntfs, volume, data, effective, security, mix, security-stle, volume, conditional, ace, resource, central, access, policy, display information about dynamic access control security 
summary: 您可以显示 NTFS 卷上的动态访问控制（ DAC ）安全性信息，以及混合安全模式卷上使用 NTFS 有效安全性的数据信息。其中包括有关条件 ACE ，资源 ACE 和中央访问策略 ACE 的信息。您可以使用结果验证安全配置或对文件访问问题进行故障排除。 
---
= 显示有关动态访问控制安全性的信息
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以显示 NTFS 卷上的动态访问控制（ DAC ）安全性信息，以及混合安全模式卷上使用 NTFS 有效安全性的数据信息。其中包括有关条件 ACE ，资源 ACE 和中央访问策略 ACE 的信息。您可以使用结果验证安全配置或对文件访问问题进行故障排除。

您必须提供 Storage Virtual Machine （ SVM ）的名称以及要显示其文件或文件夹安全信息的数据的路径。您可以摘要形式或详细列表形式显示输出。

.步骤
. 使用所需的详细信息级别显示文件和目录安全设置：
+
|===
| 要显示信息的项 | 输入以下命令 ... 


 a| 
摘要形式
 a| 
`vserver security file-directory show -vserver vserver_name -path path`



 a| 
扩展了详细信息
 a| 
`vserver security file-directory show -vserver vserver_name -path path -expand-mask true`



 a| 
其中输出显示有组和用户 SID
 a| 
`vserver security file-directory show -vserver vserver_name -path path -lookup-names false`



 a| 
关于十六进制位掩码转换为文本格式的文件和目录的文件和目录安全性
 a| 
`vserver security file-directory show -vserver vserver_name -path path -text-mask true`

|===


以下示例显示了有关 SVM vs1 中路径 ` /vol1` 的动态访问控制安全信息：

[listing]
----
cluster1::> vserver security file-directory show -vserver vs1 -path /vol1
                           Vserver: vs1
                         File Path: /vol1
                 File Inode Number: 112
                    Security Style: mixed
                   Effective Style: ntfs
                    DOS Attributes: 10
            DOS Attributes in Text: ----D---
            Expanded Dos Attribute: -
                      Unix User Id: 0
                     Unix Group Id: 1
                    Unix Mode Bits: 777
            Unix Mode Bits in Text: rwxrwxrwx
                              ACLs: NTFS Security Descriptor
                                    Control:0xbf14
                                    Owner:CIFS1\Administrator
                                    Group:CIFS1\Domain Admins
                                    SACL - ACEs
                                       ALL-Everyone-0xf01ff-OI|CI|SA|FA
                                       RESOURCE ATTRIBUTE-Everyone-0x0
                                         ("Department_MS",TS,0x10020,"Finance")
                                       POLICY ID-All resources - No Write-0x0-OI|CI
                                    DACL - ACEs
                                       ALLOW-CIFS1\Administrator-0x1f01ff-OI|CI
                                       ALLOW-Everyone-0x1f01ff-OI|CI
                                       ALLOW CALLBACK-DAC\user1-0x1200a9-OI|CI
                                         ((@User.department==@Resource.Department_MS&&@Resource.Impact_MS>1000)&&@Device.department==@Resource.Department_MS)
----
* 相关信息 *

xref:display-gpo-config-task.adoc[显示有关 GPO 配置的信息]

xref:display-central-access-policies-task.adoc[显示有关中央访问策略的信息]

xref:display-central-access-policy-rules-task.adoc[显示有关中央访问策略规则的信息]
