---
permalink: smb-admin/dynamic-home-directories-concept.html 
sidebar: sidebar 
keywords: ontap, home, directories, directory, configure, smb, share, map, base, connect, set, variable, creating, create, separate, share, user, define, home, relationship, entry, point, svm, how ontap enables dynamic home directories 
summary: 通过 ONTAP 主目录，您可以配置一个 SMB 共享，该共享根据连接到它的用户和一组变量映射到不同的目录。您可以使用一些主目录参数配置一个共享，以定义入口点（该共享）与主目录（ SVM 上的目录）之间的用户关系，而不是为每个用户创建单独的共享。 
---
= ONTAP 如何启用动态主目录
:icons: font
:imagesdir: ../media/


[role="lead"]
通过 ONTAP 主目录，您可以配置一个 SMB 共享，该共享根据连接到它的用户和一组变量映射到不同的目录。您可以使用一些主目录参数配置一个共享，以定义入口点（共享）与主目录（ SVM 上的目录）之间的用户关系，而不是为每个用户创建单独的共享。

以来宾用户身份登录的用户没有主目录，无法访问其他用户的主目录。可通过四个变量确定用户映射到目录的方式：

* * 共享名称 *
+
这是您创建的共享的名称，用户将连接到该共享。您必须为此共享设置主目录属性。

+
共享名称可以使用以下动态名称：

+
** ` %w` （用户的 Windows 用户名）
** ` %d` （用户的 Windows 域名）
** ` %u` （用户映射的 UNIX 用户名）要使共享名称在所有主目录中都是唯一的，共享名称必须包含 ` %w` 或 ` %u` 变量。共享名称可以同时包含 ` %d` 和 ` %w` 变量（例如， ` %d` /` %w` ），也可以包含静态部分和可变部分（例如 home_`` %w`` ）。


* * 共享路径 *
+
此路径是由共享定义的相对路径，因此与某个共享名称关联，并附加到每个搜索路径中，以便从 SVM 的根目录生成用户的整个主目录路径。它可以是静态的（例如， `home` ），动态的（例如， ` %w` ）或两者的组合（例如， `eng/%w` ）。

* * 搜索路径 *
+
这是从 SVM 根目录开始的一组绝对路径，您可以指定这些绝对路径来指示 ONTAP 搜索主目录。您可以使用 `vserver cifs home-directory search-path add` 命令指定一个或多个搜索路径。如果指定了多个搜索路径，则 ONTAP 将按指定顺序尝试这些路径，直到找到有效路径为止。

* * 目录 *
+
这是您为用户创建的用户主目录。目录名称通常是用户的名称。您必须在搜索路径定义的一个目录中创建主目录。



例如，请考虑以下设置：

* 用户： John Smith
* 用户域： acme
* 用户名： jsmith
* SVM 名称： vs1
* 主目录共享名称 1 ： home_`` %w`` - 共享路径： ` %w`
* 主目录共享名称 2 ： ` %w` - 共享路径： ` %d/%w`
* 搜索路径 1 ： ` /vol0home/home`
* 搜索路径 2 ： ` /vol1home/home`
* 搜索路径 3 ： ` /vol2home/home`
* 主目录： ` /vol1home/home/jsmith`


场景 1 ：用户连接到 ` \\vs1\home_jsmith` 。这与第一个主目录共享名称匹配，并生成相对路径 `jsmith` 。现在， ONTAP 会通过按顺序检查每个搜索路径来搜索名为 `jsmith` 的目录：

* ` /vol0home/home/jsmith` 不存在；继续搜索路径 2 。
* ` /vol1home/home/jsmith` 存在；因此，不会检查搜索路径 3 ；用户现在已连接到其主目录。


场景 2 ：用户连接到 ` \\vs1\jsmith` 。这与第二个主目录共享名称匹配，并生成相对路径 `acme/jsmith` 。现在， ONTAP 会通过按顺序检查每个搜索路径来搜索名为 `acme/jsmith` 的目录：

* ` /vol0home/home/acme/jsmith` 不存在；继续搜索路径 2 。
* ` /vol1home/home/acme/jsmith` 不存在；继续搜索路径 3 。
* ` /vol2home/home/acme/jsmith` 不存在；主目录不存在；因此连接失败。

