---
permalink: smb-admin/enable-disable-oplocks-existing-shares-task.html 
sidebar: sidebar 
keywords: oplock, enable, smb, share, storage, virtual, machine, svm, default, circumstance, disable, alternative, enable or disable oplocks on existing smb shares 
summary: 默认情况下， Storage Virtual Machine （ SVM ）上的 SMB 共享上会启用机会锁。在某些情况下，您可能需要禁用机会锁；或者，如果先前已在共享上禁用机会锁，则可能需要重新启用机会锁。 
---
= 在现有ONTAP SMB共享上启用或禁用操作锁定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
默认情况下， Storage Virtual Machine （ SVM ）上的 SMB 共享上会启用机会锁。在某些情况下，您可能需要禁用机会锁；或者，如果先前已在共享上禁用机会锁，则可能需要重新启用机会锁。

.关于此任务
如果在包含共享的卷上启用了机会锁，但禁用了该共享的机会锁共享属性，则会为该共享禁用机会锁。在共享上禁用机会锁优先于在卷上启用机会锁。在共享上禁用机会锁会同时禁用机会锁和租用机会锁。您可以随时在现有共享上启用或禁用机会锁。

.步骤
. 执行适用的操作：
+
|===
| 如果您要 ... | 那么 ... 


 a| 
通过修改现有共享在共享上启用机会锁
 a| 
输入以下命令： `vserver cifs share properties add -vserver _vserver_name_ -share-name share_name -share-properties oplocks`

[NOTE]
====
您可以使用逗号分隔列表指定要添加的其他共享属性。

====
新添加的属性将附加到现有共享属性列表中。先前指定的任何共享属性仍有效。



 a| 
通过修改现有共享禁用共享上的机会锁
 a| 
输入以下命令： `vserver cifs share properties remove -vserver _vserver_name_ -share-name _share_name_ -share-properties oplocks`

[NOTE]
====
您可以使用逗号分隔列表指定要删除的其他共享属性。

====
您删除的共享属性将从现有共享属性列表中删除；但是，先前配置的未删除的共享属性仍有效。

|===


.示例
以下命令为 Storage Virtual Machine （ SVM ，以前称为 Vserver ） vs1 上名为 "`Engineering` " 的共享启用机会锁：

[listing]
----
cluster1::> vserver cifs share properties add -vserver vs1 -share-name Engineering -share-properties oplocks

cluster1::> vserver cifs share properties show
Vserver          Share            Properties
---------------- ---------------- -----------------
vs1              Engineering      oplocks
                                  browsable
                                  changenotify
                                  showsnapshot
----
以下命令会对 SVM vs1 上名为 "`Engineering` " 的共享禁用机会锁：

[listing]
----
cluster1::> vserver cifs share properties remove -vserver vs1 -share-name Engineering -share-properties oplocks

cluster1::> vserver cifs share properties show
Vserver          Share            Properties
---------------- ---------------- -----------------
vs1              Engineering      browsable
                                  changenotify
                                  showsnapshot
----
.相关信息
xref:enable-disable-oplocks-when-creating-shares-task.adoc[创建 SMB 共享时启用或禁用机会锁]

xref:monitor-oplock-status-task.adoc[监控机会锁状态]

xref:add-remove-share-properties-existing-share-task.adoc[在现有 SMB 共享上添加或删除共享属性]
