---
permalink: smb-admin/enable-disable-password-complexity-local-users-task.html 
sidebar: sidebar 
keywords: password, complex, enhance, security, local, smb, user, storage, virtual, machine, svm, reenable, enable, disable, enable or disable required password complexity for local smb users 
summary: 所需的密码复杂性可增强 Storage Virtual Machine （ SVM ）上本地 SMB 用户的安全性。默认情况下，所需的密码复杂度功能处于启用状态。您可以随时将其禁用并重新启用。 
---
= 为本地 SMB 用户启用或禁用所需的密码复杂度
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
所需的密码复杂性可增强 Storage Virtual Machine （ SVM ）上本地 SMB 用户的安全性。默认情况下，所需的密码复杂度功能处于启用状态。您可以随时将其禁用并重新启用。

.开始之前
必须在 CIFS 服务器上启用本地用户，本地组和本地用户身份验证。

[NOTE]
.关于此任务
====
在工作组模式下，不得对 CIFS 服务器使用 `vserver cifs security modify` 命令，因为某些选项无效。

====
.步骤
. 执行以下操作之一：
+
|===
| 本地 SMB 用户所需的密码复杂度 | 输入命令 ... 


 a| 
enabled
 a| 
`vserver cifs security modify -vserver _vserver_name_ -is-password-complexity-required true`



 a| 
已禁用
 a| 
`vserver cifs security modify -vserver _vserver_name_ -is-password-complexity-required false`

|===
. 验证所需密码复杂性的安全设置： `vserver cifs security show -vserver _vserver_name_`


.示例
以下示例显示为 SVM vs1 的本地 SMB 用户启用了所需的密码复杂度：

[listing]
----
cluster1::> vserver cifs security modify -vserver vs1 -is-password-complexity-required true

cluster1::> vserver cifs security show -vserver vs1 -fields is-password-complexity-required
vserver is-password-complexity-required
------- -------------------------------
vs1     true
----
.相关信息
xref:display-server-security-settings-task.adoc[显示有关 CIFS 服务器安全设置的信息]

xref:local-users-groups-concepts-concept.adoc[使用本地用户和组进行身份验证和授权]

xref:requirements-local-user-passwords-concept.adoc[本地用户密码的要求]

xref:change-local-user-account-passwords-task.adoc[更改本地用户帐户密码]
