---
permalink: smb-admin/enable-client-access-unix-symbolic-links-concept.html 
sidebar: sidebar 
keywords: smybol, link, file, create, unix, environment, reference, directory, client, access, redirect, target, absolute, widelinks, local, file, system, how ontap enables you to provide smb client access to unix symbolic links 
summary: 符号链接是在 UNIX 环境中创建的文件，其中包含对其他文件或目录的引用。如果客户端访问符号链接，则会将客户端重定向到该符号链接所引用的目标文件或目录。ONTAP 支持相对符号链接和绝对符号链接，包括 Widelink （与本地文件系统外部目标的绝对链接）。 
---
= 如何使用 ONTAP 为 SMB 客户端提供对 UNIX 符号链接的访问权限
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
符号链接是在 UNIX 环境中创建的文件，其中包含对其他文件或目录的引用。如果客户端访问符号链接，则会将客户端重定向到该符号链接所引用的目标文件或目录。ONTAP 支持相对符号链接和绝对符号链接，包括 Widelink （与本地文件系统外部目标的绝对链接）。

通过 ONTAP ， SMB 客户端可以访问在 SVM 上配置的 UNIX 符号链接。此功能是可选的、您可以使用为每个共享配置此功能 `-symlink-properties` 的选项 `vserver cifs share create` 命令、并使用以下设置之一：

* 已启用，具有读 / 写访问权限
* 启用，具有只读访问权限
* 通过隐藏 SMB 客户端的符号链接来禁用
* 已禁用，但无法从 SMB 客户端访问符号链接


如果在共享上启用符号链接，则相对符号链接无需进一步配置即可正常工作。

如果在共享上启用符号链接，则绝对符号链接不会立即生效。您必须先在符号链接的 UNIX 路径与目标 SMB 路径之间创建映射。创建绝对符号链接映射时，您可以指定它是本地链接还是 _widelink_ ； Widelink 可以是指向其他存储设备上的文件系统的链接，也可以是指向同一 ONTAP 系统上不同 SVM 中托管的文件系统的链接。创建 Widelink 时，它必须包含客户端要遵循的信息；也就是说，您可以为客户端创建重新解析点以发现目录接合点。如果创建指向本地共享以外的文件或目录的绝对符号链接，但将位置设置为本地，则 ONTAP 将禁止访问目标。

[NOTE]
====
如果客户端尝试删除本地符号链接（绝对或相对），则只会删除符号链接，而不会删除目标文件或目录。但是，如果客户端尝试删除 Widelink ，则可能会删除 Widelink 所引用的实际目标文件或目录。ONTAP 无法对此进行控制，因为客户端可以明确打开 SVM 外部的目标文件或目录并将其删除。

====
* * 重新解析点和 ONTAP 文件系统服务 *
+
重新解析点 _ 是一个 NTFS 文件系统对象，可以选择将其与文件一起存储在卷上。重新解析点使 SMB 客户端能够在使用 NTFS 模式的卷时接收增强或扩展的文件系统服务。重新解析点由用于标识重新解析点类型的标准标记以及可供 SMB 客户端检索以供客户端进一步处理的重新解析点内容组成。在可用于扩展文件系统功能的对象类型中， ONTAP 使用重新解析点标记实现对 NTFS 符号链接和目录接合点的支持。无法理解重新解析点内容的 SMB 客户端只需忽略它，而不提供重新解析点可能启用的扩展文件系统服务。

* * 对符号链接的目录接合点和 ONTAP 支持 *
+
目录接合点是指文件系统目录结构中的位置，可以是指存储文件的备用位置，可以是位于不同路径（符号链接）上，也可以是位于单独的存储设备（ Widelink ）上。ONTAP SMB 服务器将目录接合点作为重新解析点向 Windows 客户端公开，从而使具有功能的客户端能够在遍历目录接合点时从 ONTAP 获取重新解析点内容。因此，它们可以导航并连接到不同的路径或存储设备，就像它们属于同一文件系统一样。

* * 使用重新解析点选项启用 Widelink 支持 *
+
。 `-is-use-junctions-as-reparse-points-enabled` 选项在ONTAP 9中默认处于启用状态。并非所有 SMB 客户端都支持 Widelink ，因此，启用信息的选项可按协议版本进行配置，从而允许管理员同时支持受支持和不受支持的 SMB 客户端。在ONTAP 9.2及更高版本中、必须启用选项 `-widelink-as-reparse-point-versions` 对于使用widelink访问共享的每个客户端协议、默认值为smb1。在早期版本中，仅报告使用默认 SMB1 访问的 Widelink ，而使用 SMB2 或 SMB3 的系统无法访问 Widelink 。



有关详细信息，请参见 Microsoft NTFS 文档。

https://docs.microsoft.com/en-us/windows/win32/fileio/reparse-points["Microsoft 文档：重新解析点"]
