---
permalink: smb-admin/improve-microsoft-remote-copy-performance-concept.html 
sidebar: sidebar 
keywords: microsoft, offload, data, transfer, odx, copy, offload, enable, direct, compatible, computer, improve microsoft remote copy performance 
summary: Microsoft 卸载数据传输（ Offloaded Data Transfer ， ODX ）也称为副本卸载，支持在兼容存储设备内部或之间直接传输数据，而无需通过主机计算机传输数据。 
---
= 改进 Microsoft 远程复制性能概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Microsoft 卸载数据传输（ Offloaded Data Transfer ， ODX ）也称为 _copy ofload_ ，可在兼容存储设备内部或之间直接传输数据，而无需通过主机计算机传输数据。

ONTAP 支持对 SMB 和 SAN 协议使用 ODX 。源可以是 CIFS 服务器或 LUN ，目标可以是 CIFS 服务器或 LUN 。

在非 ODX 文件传输中，数据将从源读取，并通过网络传输到客户端计算机。客户端计算机通过网络将数据传输回目标。总之，客户端计算机从源读取数据并将其写入目标。使用 ODX 文件传输时，数据会直接从源复制到目标。

由于 ODX 卸载副本是直接在源存储和目标存储之间执行的，因此具有显著的性能优势。实现的性能优势包括：源和目标之间的复制时间更短，客户端上的资源利用率（ CPU ，内存）更低，网络 I/O 带宽利用率更低。

对于 SMB 环境，只有当客户端和存储服务器都支持 SMB 3.0 和 ODX 功能时，此功能才可用。对于 SAN 环境，只有当客户端和存储服务器都支持 ODX 功能时，此功能才可用。支持 ODX 且启用了 ODX 的客户端计算机在移动或复制文件时会自动透明地使用卸载文件传输。无论您是通过 Windows 资源管理器拖放文件还是使用命令行文件复制命令，还是客户端应用程序启动文件复制请求，系统都会使用 ODX 。

.相关信息
xref:improve-client-response-node-referrals-concept.adoc[通过为 SMB 自动节点转介提供自动位置来缩短客户端响应时间]

link:../smb-hyper-v-sql/index.html["Microsoft Hyper-V 和 SQL Server 的 SMB 配置"]
