---
permalink: smb-admin/improve-client-response-node-referrals-concept.html 
sidebar: sidebar 
keywords: auto, location, smb, automatic, node, referral, increase, client, performance, storage, virtual, machine, svm, request, host, response, improve, improve client response time by providing smb automatic node referrals with auto location 
summary: 自动定位使用 SMB 自动节点转介来提高 Storage Virtual Machine （ SVM ）上的 SMB 客户端性能。自动节点转介会自动将请求客户端重定向到托管数据所在卷的节点 SVM 上的 LIF ，从而缩短客户端响应时间。 
---
= 通过提供 SMB 自动节点转介和自动位置概述来缩短客户端响应时间
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
自动定位使用 SMB 自动节点转介来提高 Storage Virtual Machine （ SVM ）上的 SMB 客户端性能。自动节点转介会自动将请求客户端重定向到托管数据所在卷的节点 SVM 上的 LIF ，从而缩短客户端响应时间。

当 SMB 客户端连接到 SVM 上托管的 SMB 共享时，它可能会使用不拥有所请求数据的节点上的 LIF 进行连接。客户端连接到的节点使用集群网络访问另一个节点拥有的数据。如果 SMB 连接使用位于包含请求数据的节点上的 LIF ，则客户端的响应速度会更快：

* ONTAP 通过使用 Microsoft DFS 转介来提供此功能，以通知 SMB 客户端命名空间中的请求文件或文件夹托管在其他位置。
+
当节点确定包含数据的节点上存在 SVM LIF 时，它会进行转介。

* IPv4 和 IPv6 LIF IP 地址支持自动节点转介。
* 转介是根据客户端所连接的共享的根位置进行的。
* 转介发生在 SMB 协商期间。
+
在建立连接之前进行转介。在 ONTAP 将 SMB 客户端转介到目标节点后，将建立连接，并且客户端将从该点通过转介的 LIF 路径访问数据。这样，客户端可以更快地访问数据，并避免额外的集群通信。

+
[NOTE]
====
如果共享跨越多个接合点，而某些接合点指向其他节点上包含的卷，则共享中的数据将分布在多个节点上。由于 ONTAP 提供的转介是共享根的本地转介，因此 ONTAP 必须使用集群网络检索这些非本地卷中包含的数据。使用这种类型的命名空间架构时，自动节点转介可能不会带来显著的性能优势。

====


如果托管数据的节点没有可用的 LIF ，则 ONTAP 将使用客户端选择的 LIF 建立连接。SMB 客户端打开文件后，它将继续通过相同的转介连接访问该文件。

如果由于任何原因 CIFS 服务器无法进行转介，则 SMB 服务不会中断。此时将建立 SMB 连接，就好像未启用自动节点转介一样。

.相关信息
xref:improve-microsoft-remote-copy-performance-concept.adoc[提高 Microsoft 远程复制性能]
