---
permalink: smb-admin/manage-ntfs-security-audit-policies-slag-concept.html 
sidebar: sidebar 
keywords: manage, ntfs, file, security, ntfs, audit, policies, policy, storage-level, access, guard, storage, virtual, machine, svm, cli, manage ntfs file security, ntfs audit policies, and storage-level access guard on svms using the cli 
summary: 您可以使用命令行界面管理 Storage Virtual Machine （ SVM ）上的 NTFS 文件安全性， NTFS 审核策略和存储级别访问防护。 
---
= 用于管理 SMB NTFS 文件安全、NTFS 审计策略和存储级别访问防护的 ONTAP 命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用命令行界面管理 Storage Virtual Machine （ SVM ）上的 NTFS 文件安全性， NTFS 审核策略和存储级别访问防护。

您可以从 SMB 客户端或使用命令行界面管理 NTFS 文件安全性和审核策略。但是，使用命令行界面配置文件安全性和审核策略后，无需使用远程客户端来管理文件安全性。使用 CLI 可以显著缩短使用一个命令对多个文件和文件夹应用安全性所需的时间。

您可以配置存储级别访问防护，这是 ONTAP 应用于 SVM 卷的另一层安全保护。存储级别访问防护适用场景从所有 NAS 协议访问应用了存储级别访问防护的存储对象。

只能通过 ONTAP 命令行界面配置和管理存储级别访问防护。您不能从 SMB 客户端管理存储级别访问防护设置。此外，如果您从 NFS 或 SMB 客户端查看文件或目录的安全设置，则不会看到存储级别访问防护安全性。即使是系统（ Windows 或 UNIX ）管理员也无法从客户端撤消存储级别访问防护安全性。因此，存储级别访问防护为数据访问提供了额外的安全层，该层由存储管理员独立设置和管理。


NOTE: 即使存储级别访问防护仅支持 NTFS 访问权限，但如果 UNIX 用户映射到拥有该卷的 SVM 上的 Windows 用户，则 ONTAP 可以对通过 NFS 访问应用了存储级别访问防护的卷上的数据执行安全检查。



== NTFS 安全模式卷

NTFS 安全模式卷和 qtree 中包含的所有文件和文件夹都具有 NTFS 有效安全性。您可以使用 `vserver security file-directory` 命令系列、用于在NTFS安全模式卷上实施以下类型的安全性：

* 卷中包含的文件和文件夹的文件权限和审核策略
* 卷上的存储级别访问防护安全性




== 混合安全模式卷

混合安全模式卷和 qtree 可以包含一些具有 UNIX 有效安全性并使用 UNIX 文件权限（模式位或 NFSv4.x ACL 和 NFSv4.x 审核策略）的文件和文件夹，以及一些具有 NTFS 有效安全性并使用 NTFS 文件权限和审核策略的文件和文件夹。您可以使用 `vserver security file-directory` 用于将以下类型的安全性应用于混合安全模式数据的命令系列：

* 混合卷或 qtree 中采用 NTFS 有效安全模式的文件和文件夹的文件权限和审核策略
* 对采用 NTFS 和 UNIX 有效安全模式的卷的存储级别访问防护




== UNIX安全模式卷

UNIX 安全模式卷和 qtree 包含具有 UNIX 有效安全性（模式位或 NFSv4.x ACL ）的文件和文件夹。如果要使用、必须牢记以下几点 `vserver security file-directory` 用于在UNIX安全模式卷上实施安全性的命令系列：

* 。 `vserver security file-directory` 命令系列不能用于管理UNIX安全模式卷和qtrees上的UNIX文件安全性和审核策略。
* 您可以使用 `vserver security file-directory` 命令系列、用于在UNIX安全模式卷上配置存储级别访问防护、前提是带有目标卷的SVM包含CIFS服务器。


.相关信息
xref:display-file-security-audit-policies-concept.adoc[显示有关文件安全性和审核策略的信息]

xref:create-ntfs-security-descriptor-file-task.adoc[使用命令行界面在 NTFS 文件和文件夹上配置和应用文件安全性]

xref:configure-apply-audit-policies-ntfs-files-folders-task.adoc[使用命令行界面配置审核策略并将其应用于 NTFS 文件和文件夹]

xref:secure-file-access-storage-level-access-guard-concept.adoc[使用存储级别访问防护确保文件访问安全]
