---
permalink: smb-admin/manage-local-groups.html 
sidebar: sidebar 
keywords: modify, exist, local, group, description, exist, local, group, renaming, rename, modify local groups 
summary: 您可以通过更改现有本地组的问题描述或重命名组来修改现有本地组。 
---
= 管理本地 ONTAP SMB 组
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以通过更新本地组说明或重命名来更改本地组。您还可以查看群集或特定存储虚拟机 (SVM) 上的所有本地组，并查看谁属于每个组。此信息可帮助您解决 SVM 上的文件访问和用户权限问题。

[cols="2,4a"]
|===
| 如果您要 ... | 使用命令 ... 


 a| 
显示集群上的所有本地组
 a| 
`vserver cifs users-and-groups local-group show`



 a| 
在 SVM 上显示所有本地组
 a| 
`vserver cifs users-and-groups local-group show -vserver <SVM_name>`



 a| 
显示集群上所有本地组的成员
 a| 
`vserver cifs users-and-groups local-group show-members`



 a| 
显示 SVM 上所有本地组的成员
 a| 
`vserver cifs users-and-groups local-group show-members -vserver <SVM_name>`



 a| 
修改本地组问题描述
 a| 
`vserver cifs users-and-groups local-group modify -vserver <SVM_name> -group-name <group_name> -description text`

如果描述包含空格，则必须用双引号括起来。



 a| 
重命名本地组
 a| 
`vserver cifs users-and-groups local-group rename -vserver <SVM_name> -group-name <group_name> -new-group-name <new_group_name>`

|===
.命令示例
[%collapsible]
====
.示例
以下示例将本地组 "`CIFS_SERVER\engineering` " 重命名为 "`CIFS_SERVER\engineering_new` " ：

[listing]
----
cluster1::> vserver cifs users-and-groups local-group rename -vserver vs1 -group-name CIFS_SERVER\engineering -new-group-name CIFS_SERVER\engineering_new
----
以下示例修改本地组 "`CIFS_SERVER\engineering` " 的问题描述：

[listing]
----
cluster1::> vserver cifs users-and-groups local-group modify -vserver vs1 -group-name CIFS_SERVER\engineering -description "New Description"
----
.示例
以下示例显示了有关 SVM vs1 上所有本地组的信息：

[listing]
----
cluster1::> vserver cifs users-and-groups local-group show -vserver vs1
Vserver  Group Name                  Description
-------- --------------------------- ----------------------------
vs1      BUILTIN\Administrators      Built-in Administrators group
vs1      BUILTIN\Backup Operators    Backup Operators group
vs1      BUILTIN\Power Users         Restricted administrative privileges
vs1      BUILTIN\Users               All users
vs1      CIFS_SERVER\engineering
vs1      CIFS_SERVER\sales
----
.示例
以下示例显示了有关 SVM vs1 上所有本地组的成员的信息：

[listing]
----
cluster1::> vserver cifs users-and-groups local-group show-members -vserver vs1
Vserver   Group Name                   Members
--------- ---------------------------- ------------------------
vs1       BUILTIN\Administrators       CIFS_SERVER\Administrator
                                       AD_DOMAIN\Domain Admins
                                       AD_DOMAIN\dom_grp1
          BUILTIN\Users                AD_DOMAIN\Domain Users
                                       AD_DOMAIN\dom_usr1
          CIFS_SERVER\engineering      CIFS_SERVER\james
----
====


== 删除本地 ONTAP SMB 组

如果不再需要本地组来确定与该 SVM 关联的数据的访问权限，或者不再需要将 SVM 用户权限（特权）分配给组成员，则可以从 Storage Virtual Machine （ SVM ）中删除该本地组。

.关于此任务
删除本地组时，请记住以下几点：

* 文件系统未更改。
+
不会调整引用此组的文件和目录上的 Windows 安全描述符。

* 如果该组不存在，则会返回错误。
* 不能删除特殊的 _Everyone 组。
* 无法删除 _BUILTIN\Administrators _ _BUILTIN\Users_ 等内置组。


.步骤
. 通过在 SVM 上显示本地组列表来确定要删除的本地组的名称：
+
[source, cli]
----
vserver cifs users-and-groups local-group show -vserver <SVM_name>
----
. 删除本地组：
+
[source, cli]
----
vserver cifs users-and-groups local-group delete -vserver <SVM_name> -group-name <group_name>
----
. 验证组已删除：
+
[source, cli]
----
vserver cifs users-and-groups local-group show -vserver <SVM_name>
----


.命令示例
[%collapsible]
====
以下示例将删除与 SVM vs1 关联的本地组 "`CIFS_SERVER\sales` " ：

[listing]
----
cluster1::> vserver cifs users-and-groups local-group show -vserver vs1
Vserver   Group Name                   Description
--------- ---------------------------- ----------------------------
vs1       BUILTIN\Administrators       Built-in Administrators group
vs1       BUILTIN\Backup Operators     Backup Operators group
vs1       BUILTIN\Power Users          Restricted administrative privileges
vs1       BUILTIN\Users                All users
vs1       CIFS_SERVER\engineering
vs1       CIFS_SERVER\sales

cluster1::> vserver cifs users-and-groups local-group delete -vserver vs1 -group-name CIFS_SERVER\sales

cluster1::> vserver cifs users-and-groups local-group show -vserver vs1
Vserver   Group Name                   Description
--------- ---------------------------- ----------------------------
vs1       BUILTIN\Administrators       Built-in Administrators group
vs1       BUILTIN\Backup Operators     Backup Operators group
vs1       BUILTIN\Power Users          Restricted administrative privileges
vs1       BUILTIN\Users                All users
vs1       CIFS_SERVER\engineering
----
====


== 向本地 ONTAP SMB 组添加成员

您可以通过添加本地用户、域用户或域组来管理本地组成员身份。如果您希望根据放置在组上的访问控制来控制对数据的访问，或者如果您希望用户具有与该组相关联的权限，则此功能非常有用。

.关于此任务
* 您不能将用户添加到特殊的 _Everyone 组。
* 本地组必须存在，然后才能向其中添加用户。
* 用户必须存在，然后才能将其添加到本地组。
* 您不能将本地组添加到其他本地组。
* 要将域用户或组添加到本地组， Data ONTAP 必须能够将此名称解析为 SID 。


.步骤
. 在组中添加成员：
+
[source, cli]
----
vserver cifs users-and-groups local-group add-members -vserver _vserver_name_ -group-name _group_name_ -member-names name[,...]
----


您可以指定要添加到指定本地组的本地用户，域用户或域组的逗号分隔列表。

.命令示例
[%collapsible]
====
以下示例将本地用户 `SMB_SERVER\sue` 和域组`AD_DOM\DOM_eng` 添加到 SVM vs1 上的本地组 `SMB_SERVER\engineering` 中：

[listing]
----
cluster1::> vserver cifs users-and-groups local-group add-members -vserver vs1 -group-name SMB_SERVER\engineering -member-names SMB_SERVER\sue,AD_DOMAIN\dom_eng
----
====


== 从本地 ONTAP SMB 组中删除成员

您可以通过删除本地用户、域用户或域组来管理本地组成员身份。如果您希望根据放置在组上的访问控制来控制对数据的访问，或者如果您希望用户具有与该组相关联的权限，则此功能非常有用。

.关于此任务
* 您不能从特殊的 _Everyone _ 组中删除成员。
* 要从中删除成员的组必须存在。
* ONTAP 必须能够将要从组中删除的成员的名称解析为相应的 SID 。


.步骤
. 从组中删除成员：
+
[source, cli]
----
vserver cifs users-and-groups local-group remove-members -vserver _vserver_name_ -group-name _group_name_ -member-names name[,...]
----


您可以指定要从指定本地组中删除的本地用户，域用户或域组的逗号分隔列表。

.命令示例
[%collapsible]
====
以下示例将从 SVM vs1 上的本地组 `SMB_SERVER\engineering` 中删除本地用户 `SMB_SERVER\sue` 和 `SMB_SERVER\James` ：

[listing]
----
cluster1::> vserver cifs users-and-groups local-group remove-members -vserver vs1 -group-name SMB_SERVER\engineering -member-names SMB_SERVER\sue,SMB_SERVER\james
----
====


== 更新本地数据库中的 ONTAP SMB 域用户和组名称

您可以将域用户和组添加到 CIFS 服务器的本地组。这些域对象会注册到集群上的本地数据库中。如果重命名域对象，则必须手动更新本地数据库。

.关于此任务
您必须指定要更新域名的 Storage Virtual Machine （ SVM ）的名称。

.步骤
. 将权限级别设置为高级：
+
[source, cli]
----
set -privilege advanced
----
. 更新与 Storage Virtual Machine 关联的域用户和组的名称：
+
[source, cli]
----
vserver cifs users-and-groups update-names -vserver <SVM_name>
----
. 显示成功更新和更新失败的域用户和组：
+
[source, cli]
----
vserver cifs users-and-groups update-names -vserver <SVM_name> -display-failed-only false|true
----
. 如果要取消有关更新的所有状态信息，请使用以下命令：
+
[source, cli]
----
vserver cifs users-and-groups update-names -vserver <SVM_name> -suppress-all-output true
----
. 返回到管理权限级别：
+
[source, cli]
----
set -privilege admin
----


.命令示例
[%collapsible]
====
以下示例将更新与 Storage Virtual Machine （ SVM ，以前称为 Vserver ） vs1 关联的域用户和组的名称。对于上次更新，需要更新一组依赖名称：

[listing]
----
cluster1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them
only when directed to do so by technical support personnel.
Do you wish to continue? (y or n): y

cluster1::*> vserver cifs users-and-groups update-names -vserver vs1

   Vserver:           vs1
   SID:               S-1-5-21-123456789-234565432-987654321-12345
   Domain:            EXAMPLE1
   Out-of-date Name:  dom_user1
   Updated Name:      dom_user2
   Status:            Successfully updated

   Vserver:           vs1
   SID:               S-1-5-21-123456789-234565432-987654322-23456
   Domain:            EXAMPLE2
   Out-of-date Name:  dom_user1
   Updated Name:      dom_user2
   Status:            Successfully updated

   Vserver:           vs1
   SID:               S-1-5-21-123456789-234565432-987654321-123456
   Domain:            EXAMPLE1
   Out-of-date Name:  dom_user3
   Updated Name:      dom_user4
   Status:            Successfully updated; also updated SID "S-1-5-21-123456789-234565432-987654321-123457"
                      to name "dom_user5"; also updated SID "S-1-5-21-123456789-234565432-987654321-123458"
                      to name "dom_user6"; also updated SID "S-1-5-21-123456789-234565432-987654321-123459"
                      to name "dom_user7"; also updated SID "S-1-5-21-123456789-234565432-987654321-123460"
                      to name "dom_user8"

The command completed successfully. 7 Active Directory objects have been updated.

cluster1::*> set -privilege admin
----
====
.相关信息
有关的详细信息 `vserver cifs`，请参见link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+cifs["ONTAP 命令参考"^]。
