---
permalink: smb-admin/modify-server-kerberos-security-settings-task.html 
sidebar: sidebar 
keywords: modify, cifs, server, kerberos, security, setting, clock, slew, time, ticket, lifetime, renewal, modify the cifs server kerberos security ticket settings 
summary: 您可以修改某些 CIFS 服务器 Kerberos 安全设置，包括允许的最大 Kerberos 时钟转换时间， Kerberos 票证生命周期以及票证续订天数。 
---
= 修改 CIFS 服务器 Kerberos 安全设置
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以修改某些 CIFS 服务器 Kerberos 安全设置，包括允许的最大 Kerberos 时钟转换时间， Kerberos 票证生命周期以及票证续订天数。

使用 `vserver cifs security modify` 命令修改 CIFS 服务器 Kerberos 设置仅会修改使用 ` -vserver` 参数指定的单个 Storage Virtual Machine （ SVM ）上的设置。您可以使用 Active Directory 组策略对象（ GPO ）集中管理属于同一 Active Directory 域的集群上所有 SVM 的 Kerberos 安全设置。

.步骤
. 执行以下一项或多项操作：
+
|===
| 如果您要 ... | 输入 ... 


 a| 
指定允许的最大 Kerberos 时钟偏差时间（以分钟为单位）
 a| 
`vserver cifs security modify -vserver _vserver_name_ -kerberos-clock-skew _intege_in_minutes_` 默认设置为 5 分钟。



 a| 
以小时为单位指定 Kerberos 票证的生命周期
 a| 
`vserver cifs security modify -vserver _vserver_name_ -kerberos-ticket-age intege_in_hours` 默认设置为 10 小时。



 a| 
指定最大票证续订天数
 a| 
`vserver cifs security modify -vserver _vserver_name_ -kerberos-renew-age _intege_in_days_` 默认设置为 7 天。



 a| 
指定 KDC 上的套接字超时，超过此超时后，所有 KDC 都将标记为不可访问
 a| 
`vserver cifs security modify -vserver _vserver_name_ -kerberos-kw-timeout _intege_in_seconds_` 默认设置为 3 秒。

|===
. 验证 Kerberos 安全设置： `vserver cifs security show -vserver _vserver_name_`


以下示例对 Kerberos 安全性进行了以下更改：对于 SVM vs1 ， `Kerberos 时钟间隔` 设置为 `3` 分钟， `Kerberos 票证期限` 设置为 `8` 小时：

[listing]
----
cluster1::> vserver cifs security modify -vserver vs1 -kerberos-clock-skew 3 -kerberos-ticket-age 8

cluster1::> vserver cifs security show -vserver vs1

Vserver: vs1

                    Kerberos Clock Skew:                   3 minutes
                    Kerberos Ticket Age:                   8 hours
                   Kerberos Renewal Age:                   7 days
                   Kerberos KDC Timeout:                   3 seconds
                    Is Signing Required:               false
        Is Password Complexity Required:                true
   Use start_tls For AD LDAP connection:               false
              Is AES Encryption Enabled:               false
                 LM Compatibility Level:  lm-ntlm-ntlmv2-krb
             Is SMB Encryption Required:               false
----
xref:display-server-security-settings-task.adoc[显示有关 CIFS 服务器安全设置的信息]

xref:supported-gpos-concept.adoc[支持的 GPO]

xref:applying-group-policy-objects-concept.adoc[将组策略对象应用于 CIFS 服务器]
