---
permalink: smb-admin/modify-servers-task.html 
sidebar: sidebar 
keywords: move, smb, server, workgroup, active, directory, domain, vserver, cifs, modify, command, modify smb servers 
summary: 您可以使用 vserver cifs modify 命令将 SMB 服务器从工作组移动到 Active Directory 域，从工作组移动到另一个工作组，或者从 Active Directory 域移动到工作组。 
---
= 修改 SMB 服务器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用将SMB服务器从工作组移动到Active Directory域、从工作组移动到另一个工作组或从Active Directory域移动到工作组 `vserver cifs modify` 命令：

.关于此任务
您还可以修改 SMB 服务器的其他属性，例如 SMB 服务器名称和管理状态。有关详细信息，请参见手册页。

.选项
* 将 SMB 服务器从工作组移动到 Active Directory 域：
+
.. 将SMB服务器的管理状态设置为 `down`。
+
[listing]
----
Cluster1::>vserver cifs modify -vserver vs1 -status-admin down
----
.. 将SMB服务器从工作组移动到Active Directory域： `vsserver cifs modify -vserver _vserver_name_ -domain _domain_name_`
+
[listing]
----
Cluster1::>vserver cifs modify -vserver vs1 -domain example.com
----
+
要为SMB服务器创建Active Directory计算机帐户、您必须提供具有足够权限的Windows帐户的名称和密码、以便向添加计算机 `ou=_example_ ou` 中的容器 `_example_`.com域。

+
从 ONTAP 9.7 开始，您的 AD 管理员可以为您提供 keytab 文件的 URI ，而不是为您提供特权 Windows 帐户的名称和密码。收到此URI后、请将其包含在中 `-keytab-uri` 参数 `vserver cifs` 命令



* 将 SMB 服务器从一个工作组移动到另一个工作组：
+
.. 将SMB服务器的管理状态设置为 `down`。
+
[listing]
----
Cluster1::>vserver cifs modify -vserver vs1 -status-admin down
----
.. 修改SMB服务器的工作组： `vserver cifs modify -vserver _vserver_name_ -workgroup _new_workgroup_name_`
+
[listing]
----
Cluster1::>vserver cifs modify -vserver vs1 -workgroup workgroup2
----


* 将 SMB 服务器从 Active Directory 域移动到工作组：
+
.. 将SMB服务器的管理状态设置为 `down`。
+
[listing]
----
Cluster1::>vserver cifs modify -vserver vs1 -status-admin down
----
.. 将SMB服务器从Active Directory域移动到工作组： `vserver cifs modify -vserver _vserver_name_ -workgroup _workgroup_name_`
+
[listing]
----
cluster1::> vserver cifs modify -vserver vs1 -workgroup workgroup1
----
+
[NOTE]
====
要进入工作组模式，系统必须禁用所有基于域的功能并自动删除其配置，包括持续可用的共享，卷影副本和 AES 。但是，域配置的共享 ACL （例如 EXAMPLE.COM\userName" ）将无法正常工作，但 ONTAP 无法删除。命令完成后，使用外部工具尽快删除这些共享 ACL 。如果已启用 AES ，则可能会要求您提供具有足够权限的 Windows 帐户的名称和密码，以便在 example.com 域中禁用它。

====
+
*** 使用的相应参数修改其他属性 `vserver cifs modify` 命令：





