---
permalink: smb-admin/monitor-signed-session-statistics-task.html 
sidebar: sidebar 
keywords: monitor, smb, session, statistic, establish, sign, monitor smb signed session statistics 
summary: 您可以监控 SMB 会话统计信息，并确定哪些已建立的会话已签名，哪些未签名。 
---
= 监控ONTAP SMB签名会话统计信息
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以监控 SMB 会话统计信息，并确定哪些已建立的会话已签名，哪些未签名。

.关于此任务
。 `statistics` 命令可在高级权限级别提供 `signed_sessions` 可用于监控已签名SMB会话数的计数器。。 `signed_sessions` 计数器可用于以下统计信息对象：

* `cifs` 用于监控所有SMB会话的SMB签名。
* `smb1` 用于监控SMB 1.0会话的SMB签名。
* `smb2` 用于监控SMB 2.x和SMB 3.0会话的SMB签名。
+
SMB 3.0统计信息包括在的输出中 `smb2` 对象。



如果要将已签名会话数与会话总数进行比较、可以比较的输出 `signed_sessions` 计数器与的输出 `established_sessions` 计数器。

您必须先启动统计信息样本收集，然后才能查看生成的数据。如果不停止数据收集，您可以查看样本中的数据。停止数据收集可提供一个固定样本。如果不停止数据收集，则可以获取更新后的数据，以便与先前的查询进行比较。此比较可帮助您确定趋势。

.步骤
. 将权限级别设置为高级：+
`set -privilege advanced`
. 开始数据收集：+
`statistics start -object {cifs|smb1|smb2} -instance instance -sample-id _sample_ID_ [-node _node_name_]`
+
如果未指定 `-sample-id` 参数时、该命令将为您生成示例标识符、并将此示例定义为命令行界面会话的默认示例。的值 `-sample-id` 是文本字符串。如果您在同一命令行界面会话期间运行此命令、但未指定 `-sample-id` 参数、则此命令将覆盖先前的默认样本。

+
您也可以指定要收集统计信息的节点。如果未指定节点，则此示例将收集集群中所有节点的统计信息。

. 使用 `statistics stop` 命令停止收集样本数据。
. 查看 SMB 签名统计信息：
+
|===
| 要查看的信息 | 输入 ... 


 a| 
已签名的会话
 a| 
`show -sample-id sample_ID -counter signed_sessions|_node_name_ [-node _node_name_]`



 a| 
已签名的会话和已建立的会话
 a| 
`show -sample-id _sample_ID_ -counter signed_sessions|established_sessions|_node_name_ [-node node_name]`

|===
+
如果要仅显示单个节点的信息、请指定可选 `-node` 参数。

. 返回到管理权限级别：+
`set -privilege admin`


.示例
[%collapsible]
====
以下示例显示了如何监控 Storage Virtual Machine （ SVM ） vs1 上的 SMB 2.x 和 SMB 3.0 签名统计信息。

以下命令将移至高级权限级别：

[listing]
----
cluster1::> set -privilege advanced

Warning: These advanced commands are potentially dangerous; use them only when directed to do so by support personnel.
Do you want to continue? {y|n}: y
----
以下命令将开始收集新样本的数据：

[listing]
----
cluster1::*> statistics start -object smb2 -sample-id smbsigning_sample -vserver vs1
Statistics collection is being started for Sample-id: smbsigning_sample
----
以下命令将停止收集样本的数据：

[listing]
----
cluster1::*> statistics stop -sample-id smbsigning_sample
Statistics collection is being stopped for Sample-id: smbsigning_sample
----
以下命令按示例中的节点显示已签名的 SMB 会话和已建立的 SMB 会话：

[listing]
----
cluster1::*> statistics show -sample-id smbsigning_sample -counter signed_sessions|established_sessions|node_name

Object: smb2
Instance: vs1
Start-time: 2/6/2013 01:00:00
End-time: 2/6/2013 01:03:04
Cluster: cluster1

    Counter                                              Value
    -------------------------------- -------------------------
    established_sessions                                     0
    node_name                                           node1
    signed_sessions                                          0
    established_sessions                                     1
    node_name                                           node2
    signed_sessions                                          1
    established_sessions                                     0
    node_name                                           node3
    signed_sessions                                          0
    established_sessions                                     0
    node_name                                           node4
    signed_sessions                                          0
----
以下命令显示样本中 node2 的已签名 SMB 会话：

[listing]
----
cluster1::*> statistics show -sample-id smbsigning_sample -counter signed_sessions|node_name -node node2

Object: smb2
Instance: vs1
Start-time: 2/6/2013 01:00:00
End-time: 2/6/2013 01:22:43
Cluster: cluster1

    Counter                                              Value
    -------------------------------- -------------------------
    node_name                                            node2
    signed_sessions                                          1
----
以下命令将移回管理权限级别：

[listing]
----
cluster1::*> set -privilege admin
----
====
.相关信息
xref:determine-sessions-signed-task.adoc[确定 SMB 会话是否已签名]

link:../performance-admin/index.html["性能监控和管理概述"]
