---
permalink: smb-admin/monitor-encryption-statistics-task.html 
sidebar: sidebar 
keywords: monitor, smb, encryption, statistics, determine, establish, session, share, connection, encrypt, monitor smb encryption statistics 
summary: 您可以监控 SMB 加密统计信息，并确定哪些已建立的会话和共享连接已加密，哪些未加密。 
---
= 监控ONTAP SMB加密统计信息
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以监控 SMB 加密统计信息，并确定哪些已建立的会话和共享连接已加密，哪些未加密。

.关于此任务
。 `statistics` 高级权限级别的命令提供了以下计数器、您可以使用这些计数器监控加密的SMB会话和共享连接的数量：

|===
| 计数器名称 | 说明 


 a| 
`encrypted_sessions`
 a| 
提供加密的 SMB 3.0 会话的数量



 a| 
`encrypted_share_connections`
 a| 
提供发生树连接的加密共享的数量



 a| 
`rejected_unencrypted_sessions`
 a| 
提供因缺少客户端加密功能而拒绝的会话设置数量



 a| 
`rejected_unencrypted_shares`
 a| 
提供因缺少客户端加密功能而拒绝的共享映射的数量

|===
这些计数器可用于以下统计信息对象：

* `cifs` 用于监控所有SMB 3.0会话的SMB加密。
+
SMB 3.0统计信息包括在的输出中 `cifs` 对象。    如果要将加密会话数与会话总数进行比较、可以比较的输出 `encrypted_sessions` 计数器与的输出 `established_sessions` 计数器。

+
如果要将加密共享连接数与共享连接总数进行比较、则可以比较的输出 `encrypted_share_connections` 计数器与的输出 `connected_shares` 计数器。

* `rejected_unencrypted_sessions` 提供尝试建立需要从不支持SMB加密的客户端加密的SMB会话的次数。
* `rejected_unencrypted_shares` 提供尝试连接到需要从不支持SMB加密的客户端加密的SMB共享的次数。


您必须先启动统计信息样本收集，然后才能查看生成的数据。如果不停止数据收集，您可以查看样本中的数据。停止数据收集可提供一个固定样本。如果不停止数据收集，则可以获取更新后的数据，以便与先前的查询进行比较。此比较可帮助您确定趋势。

.步骤
. 将权限级别设置为高级：+
`set -privilege advanced`
. 开始数据收集：+
`statistics start -object {cifs|smb1|smb2} -instance _instance_ -sample-id _sample_ID_ [-node _node_name_]`
+
如果未指定 `-sample-id` 参数时、该命令将为您生成示例标识符、并将此示例定义为命令行界面会话的默认示例。的值 `-sample-id` 是文本字符串。如果您在同一命令行界面会话期间运行此命令、但未指定 `-sample-id` 参数、则此命令将覆盖先前的默认样本。

+
您也可以指定要收集统计信息的节点。如果未指定节点，则此示例将收集集群中所有节点的统计信息。

+
有关的详细信息 `statistics start`，请参见link:https://docs.netapp.com/us-en/ontap-cli/statistics-start.html["ONTAP 命令参考"^]。

. 使用 `statistics stop` 命令停止收集样本数据。
+
详细了解 `statistics stop`在link:https://docs.netapp.com/us-en/ontap-cli/statistics-stop.html["ONTAP 命令参考"^] 。

. 查看 SMB 加密统计信息：
+
|===
| 要查看的信息 | 输入 ... 


 a| 
加密会话
 a| 
`show -sample-id _sample_ID_ -counter encrypted_sessions|_node_name_ [-node _node_name_]`



 a| 
已加密会话和已建立的会话
 a| 
`show -sample-id _sample_ID_ -counter encrypted_sessions|established_sessions|_node_name_ [-node _node_name_]`



 a| 
加密的共享连接
 a| 
`show -sample-id _sample_ID_ -counter encrypted_share_connections|_node_name_ [-node _node_name_]`



 a| 
加密的共享连接和连接的共享
 a| 
`show -sample-id _sample_ID_ -counter encrypted_share_connections|connected_shares|_node_name_ [-node _node_name_]`



 a| 
拒绝的未加密会话
 a| 
`show -sample-id _sample_ID_ -counter rejected_unencrypted_sessions|_node_name_ [-node _node_name_]`



 a| 
拒绝未加密的共享连接
 a| 
`show -sample-id _sample_ID_ -counter rejected_unencrypted_share|_node_name_ [-node _node_name_]`

|===
+
如果要仅显示单个节点的信息、请指定可选 `-node` 参数。

+
有关的详细信息 `statistics show`，请参见link:https://docs.netapp.com/us-en/ontap-cli/statistics-show.html["ONTAP 命令参考"^]。

. 返回到管理权限级别：+
`set -privilege admin`


.示例
[%collapsible]
====
以下示例显示了如何监控 Storage Virtual Machine （ SVM ） vs1 上的 SMB 3.0 加密统计信息。

以下命令将移至高级权限级别：

[listing]
----
cluster1::> set -privilege advanced

Warning: These advanced commands are potentially dangerous; use them only when directed to do so by support personnel.
Do you want to continue? {y|n}: y
----
以下命令将开始收集新样本的数据：

[listing]
----
cluster1::*> statistics start -object cifs -sample-id smbencryption_sample -vserver vs1
Statistics collection is being started for Sample-id: smbencryption_sample
----
以下命令将停止收集该样本的数据：

[listing]
----
cluster1::*> statistics stop -sample-id smbencryption_sample
Statistics collection is being stopped for Sample-id: smbencryption_sample
----
以下命令显示样本中节点的加密 SMB 会话和已建立的 SMB 会话：

[listing]
----
cluster2::*> statistics show -object cifs -counter established_sessions|encrypted_sessions|node_name –node node_name

Object: cifs
Instance: [proto_ctx:003]
Start-time: 4/12/2016 11:17:45
End-time: 4/12/2016 11:21:45
Scope: vsim2

    Counter                               Value
    ----------------------------  ----------------------
    established_sessions                     1
    encrypted_sessions                       1

2 entries were displayed
----
以下命令显示样本中节点拒绝的未加密 SMB 会话的数量：

[listing]
----
clus-2::*> statistics show -object cifs -counter rejected_unencrypted_sessions –node node_name

Object: cifs
Instance: [proto_ctx:003]
Start-time: 4/12/2016 11:17:45
End-time: 4/12/2016 11:21:51
Scope: vsim2

    Counter                                    Value
    ----------------------------    ----------------------
    rejected_unencrypted_sessions                1

1 entry was displayed.
----
以下命令显示样本中节点的已连接 SMB 共享和加密 SMB 共享的数量：

[listing]
----
clus-2::*> statistics show -object cifs -counter connected_shares|encrypted_share_connections|node_name –node node_name

Object: cifs
Instance: [proto_ctx:003]
Start-time: 4/12/2016 10:41:38
End-time: 4/12/2016 10:41:43
Scope: vsim2

    Counter                                     Value
    ----------------------------    ----------------------
    connected_shares                              2
    encrypted_share_connections                   1

2 entries were displayed.
----
以下命令显示样本中节点拒绝的未加密 SMB 共享连接的数量：

[listing]
----
clus-2::*> statistics show -object cifs -counter rejected_unencrypted_shares –node node_name

Object: cifs
Instance: [proto_ctx:003]
Start-time: 4/12/2016 10:41:38
End-time: 4/12/2016 10:42:06
Scope: vsim2

    Counter                                     Value
    --------------------------------    ----------------------
    rejected_unencrypted_shares                   1

1 entry was displayed.
----
====
.相关信息
* xref:determine-statistics-objects-counters-available-task.adoc[确定服务器上可用的统计数据、对象和计数器]
* link:../performance-admin/index.html["性能监控和管理概述"]

