---
permalink: smb-admin/monitor-oplock-status-task.html 
sidebar: sidebar 
keywords: monitor, display, information, oplock, status, file, state, leasing, lease, determine, manual, monitor oplock status 
summary: 您可以监控和显示有关机会锁状态的信息。您可以使用此信息确定哪些文件具有机会锁，机会锁级别和机会锁状态级别是什么，以及是否使用机会锁租赁。您还可以确定有关可能需要手动中断的锁定的信息。 
---
= 监控ONTAP SMB操作锁定状态
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以监控和显示有关机会锁状态的信息。您可以使用此信息确定哪些文件具有机会锁，机会锁级别和机会锁状态级别是什么，以及是否使用机会锁租赁。您还可以确定有关可能需要手动中断的锁定的信息。

.关于此任务
您可以摘要或详细列表形式显示有关所有机会锁的信息。您还可以使用可选参数显示有关较小一部分现有锁定的信息。例如，您可以指定输出仅返回使用指定客户端 IP 地址或指定路径锁定的。

您可以显示有关传统机会锁和租用机会锁的以下信息：

* 建立机会锁的 SVM ，节点，卷和 LIF
* 锁定 UUID
* 具有机会锁的客户端的 IP 地址
* 建立机会锁的路径
* 锁定协议（ SMB ）和类型（ oplock ）
* 锁定状态
* 机会锁级别
* 连接状态和 SMB 到期时间
* 如果已授予租用机会锁，请打开组 ID


有关的详细信息 `vserver oplocks show`，请参见link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+oplocks+show["ONTAP 命令参考"^]。

.步骤
. 使用显示oplock状态 `vserver locks show` 命令：


.示例
以下命令显示有关所有锁定的默认信息。显示的文件上的oplock将授予 `read-batch` oplock级别：

[listing]
----
cluster1::> vserver locks show

Vserver: vs0
Volume   Object Path        LIF         Protocol  Lock Type   Client
-------- ------------------ ----------- --------- ----------- ----------
vol1     /vol1/notes.txt    node1_data1
                                        cifs      share-level 192.168.1.5
         Sharelock Mode: read_write-deny_delete
                                                  op-lock     192.168.1.5
         Oplock Level: read-batch
----
以下示例显示了有关路径为的文件锁定的更多详细信息 `/data2/data2_2/intro.pptx`。使用为文件授予租用机会锁 `batch` IP地址为的客户端的机会锁级别 `10.3.1.3`：

[NOTE]
====
显示详细信息时，命令会为机会锁和共享锁定信息提供单独的输出。此示例仅显示 oplock 部分的输出。

====
[listing]
----
cluster1::> vserver lock show -instance -path /data2/data2_2/intro.pptx

                   Vserver: vs1
                    Volume: data2_2
         Logical Interface: lif2
               Object Path: /data2/data2_2/intro.pptx
                 Lock UUID: ff1cbf29-bfef-4d91-ae06-062bf69212c3
             Lock Protocol: cifs
                 Lock Type: op-lock
   Node Holding Lock State: node3
                Lock State: granted
  Bytelock Starting Offset: -
    Number of Bytes Locked: -
     Bytelock is Mandatory: -
     Bytelock is Exclusive: -
     Bytelock is Superlock: -
          Bytelock is Soft: -
              Oplock Level: batch
   Shared Lock Access Mode: -
       Shared Lock is Soft: -
           Delegation Type: -
            Client Address: 10.3.1.3
             SMB Open Type: -
         SMB Connect State: connected
SMB Expiration Time (Secs): -
         SMB Open Group ID: 78a90c59d45ae211998100059a3c7a00a007f70da0f8ffffcd445b0300000000
----
.相关信息
xref:enable-disable-oplocks-when-creating-shares-task.adoc[创建 SMB 共享时启用或禁用机会锁]

xref:enable-disable-oplocks-existing-shares-task.adoc[在现有 SMB 共享上启用或禁用机会锁]

xref:commands-oplocks-volumes-qtrees-reference.adoc[用于在 SMB 卷和 qtree 上启用或禁用 oplock 的命令]
