---
permalink: smb-admin/monitor-encryption-statistics-task.html 
sidebar: sidebar 
keywords: monitor, smb, encryption, statistics, determine, establish, session, share, connection, encrypt, monitor smb encryption statistics 
summary: 您可以监控 SMB 加密统计信息，并确定哪些已建立的会话和共享连接已加密，哪些未加密。 
---
= 监控 SMB 加密统计信息
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以监控 SMB 加密统计信息，并确定哪些已建立的会话和共享连接已加密，哪些未加密。

在高级权限级别使用 `statictics` 命令可提供以下计数器，您可以使用这些计数器监控加密的 SMB 会话和共享连接的数量：

|===
| 计数器名称 | 说明 


 a| 
`encrypted_sessions`
 a| 
提供加密的 SMB 3.0 会话的数量



 a| 
`encrypted_share_connections`
 a| 
提供发生树连接的加密共享的数量



 a| 
`resfed_unencryptioned_sessions`
 a| 
提供因缺少客户端加密功能而拒绝的会话设置数量



 a| 
`resfed_unencryptioned_shares`
 a| 
提供因缺少客户端加密功能而拒绝的共享映射的数量

|===
这些计数器可用于以下统计信息对象：

* 使用 `CIFS` 可以监控所有 SMB 3.0 会话的 SMB 加密。
+
[NOTE]
====
SMB 3.0 统计信息包含在 `CIFS` 对象的输出中。如果要将加密会话数与会话总数进行比较，可以将 `encrypted_sessions` 计数器的输出与 `established_sessions` 计数器的输出进行比较。

 If you want to compare the number of encrypted share connections to the total number of share connections, you can compare output for the `encrypted_share_connections` counter with the output for the `connected_shares` counter.
====
* `refoded_unencryptioned_sessions` 提供尝试建立需要从不支持 SMB 加密的客户端进行加密的 SMB 会话的次数。
* `refoded_unencryptioned_shares` 提供尝试连接到需要从不支持 SMB 加密的客户端进行加密的 SMB 共享的次数。


您必须先启动统计信息样本收集，然后才能查看生成的数据。如果不停止数据收集，您可以查看样本中的数据。停止数据收集可提供一个固定样本。如果不停止数据收集，则可以获取更新后的数据，以便与先前的查询进行比较。此比较可帮助您确定趋势。

link:../performance-admin/index.html["性能管理"]

.步骤
. 将权限级别设置为 advanced ： `set -privilege advanced`
. 开始数据收集： `satictics start -object ｛ cifs|smb1_smb2 ｝ -instance _instance_ -sample-id _sample_ID_ [-node _node_name_]`
+
如果未指定 ` -sample-id` 参数，则该命令将为您生成一个示例标识符，并将此示例定义为 CLI 会话的默认示例。` -sample-id` 的值为文本字符串。如果您在同一命令行界面会话期间运行此命令，但未指定 ` -sample-id` 参数，则此命令将覆盖先前的默认样本。

+
您也可以指定要收集统计信息的节点。如果未指定节点，则此示例将收集集群中所有节点的统计信息。

. 使用 `satictics stop` 命令停止收集样本数据。
. 查看 SMB 加密统计信息：
+
|===
| 要查看的信息 | 输入 ... 


 a| 
加密会话
 a| 
`s如何使用 -sample-id _sample_ID_ -counter encrypted_sessions|_node_name_ [-node _node_name_]`



 a| 
已加密会话和已建立的会话
 a| 
`s如何使用 -sample-id _sample_ID_ -counter encrypted_sessions|established_sessions|_node_name_ [-node _node_name_]`



 a| 
加密的共享连接
 a| 
`s如何使用 -sample-id _sample_ID_ -counter encrypted_share_connections|_node_name_ [-node _node_name_]`



 a| 
加密的共享连接和连接的共享
 a| 
`s如何使用 -sample-id _sample_ID_ -counter encrypted_share_connections|connected_shares_node_name_ [-node _node_name_]`



 a| 
拒绝的未加密会话
 a| 
`s-sample-id _sample_ID_ -counter rejected_unencrypted_sessions|_node_name_ [-node _node_name_]`



 a| 
拒绝未加密的共享连接
 a| 
`s-sample-id _sample_ID_ -counter rejected_unencrypted_share_node_name_ [-node _node_name_]`

|===
+
如果要仅显示单个节点的信息，请指定可选的 ` 节点` 参数。

. 返回到管理权限级别： `set -privilege admin`


以下示例显示了如何监控 Storage Virtual Machine （ SVM ） vs1 上的 SMB 3.0 加密统计信息。

以下命令将移至高级权限级别：

[listing]
----
cluster1::> set -privilege advanced

Warning: These advanced commands are potentially dangerous; use them only when directed to do so by support personnel.
Do you want to continue? {y|n}: y
----
以下命令将开始收集新样本的数据：

[listing]
----
cluster1::*> statistics start -object cifs -sample-id smbencryption_sample -vserver vs1
Statistics collection is being started for Sample-id: smbencryption_sample
----
以下命令将停止收集该样本的数据：

[listing]
----
cluster1::*> statistics stop -sample-id smbencryption_sample
Statistics collection is being stopped for Sample-id: smbencryption_sample
----
以下命令显示样本中节点的加密 SMB 会话和已建立的 SMB 会话：

[listing]
----
cluster2::*> statistics show -object cifs -counter established_sessions|encrypted_sessions|node_name –node node_name

Object: cifs
Instance: [proto_ctx:003]
Start-time: 4/12/2016 11:17:45
End-time: 4/12/2016 11:21:45
Scope: vsim2

    Counter                               Value
    ----------------------------  ----------------------
    established_sessions                     1
    encrypted_sessions                       1

2 entries were displayed
----
以下命令显示样本中节点拒绝的未加密 SMB 会话的数量：

[listing]
----
clus-2::*> statistics show -object cifs -counter rejected_unencrypted_sessions –node node_name

Object: cifs
Instance: [proto_ctx:003]
Start-time: 4/12/2016 11:17:45
End-time: 4/12/2016 11:21:51
Scope: vsim2

    Counter                                    Value
    ----------------------------    ----------------------
    rejected_unencrypted_sessions                1

1 entry was displayed.
----
以下命令显示样本中节点的已连接 SMB 共享和加密 SMB 共享的数量：

[listing]
----
clus-2::*> statistics show -object cifs -counter connected_shares|encrypted_share_connections|node_name –node node_name

Object: cifs
Instance: [proto_ctx:003]
Start-time: 4/12/2016 10:41:38
End-time: 4/12/2016 10:41:43
Scope: vsim2

    Counter                                     Value
    ----------------------------    ----------------------
    connected_shares                              2
    encrypted_share_connections                   1

2 entries were displayed.
----
以下命令显示样本中节点拒绝的未加密 SMB 共享连接的数量：

[listing]
----
clus-2::*> statistics show -object cifs -counter rejected_unencrypted_shares –node node_name

Object: cifs
Instance: [proto_ctx:003]
Start-time: 4/12/2016 10:41:38
End-time: 4/12/2016 10:42:06
Scope: vsim2

    Counter                                     Value
    --------------------------------    ----------------------
    rejected_unencrypted_shares                   1

1 entry was displayed.
----
xref:determine-statistics-objects-counters-available-task.adoc[确定可用的统计信息对象和计数器]

link:../performance-config/index.html["性能监控快速设置"]
