---
permalink: smb-admin/previous-versions-view-manage-snapshot-data-task.html 
sidebar: sidebar 
keywords: windows, client, machine, previous, version, tab, properties, restore, data, store, snapshot, copies, copy, storage, virtual, machine, svm, administrator, use the previous versions tab to view and manage snapshot copy data 
summary: Windows 客户端计算机上的用户可以使用 Windows 属性窗口中的先前版本选项卡还原 Snapshot 副本中存储的数据，而无需让 Storage Virtual Machine （ SVM ）管理员参与。 
---
= 使用先前版本选项卡查看和管理 Snapshot 副本数据
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Windows 客户端计算机上的用户可以使用 Windows 属性窗口中的先前版本选项卡还原 Snapshot 副本中存储的数据，而无需让 Storage Virtual Machine （ SVM ）管理员参与。

只有当管理员已在包含共享的卷上启用 Snapshot 副本，并且管理员将共享配置为显示 Snapshot 副本时，才能使用先前版本选项卡查看和管理 SVM 上存储的数据的 Snapshot 副本中的数据。

.步骤
. 在 Windows 资源管理器中，显示存储在 CIFS 服务器上的数据的映射驱动器内容。
. 右键单击映射的网络驱动器中要查看或管理其 Snapshot 副本的文件或文件夹。
. 单击 * 属性 * 。
+
此时将显示选定文件或文件夹的属性。

. 单击 * 先前版本 * 选项卡。
+
选定文件或文件夹的可用 Snapshot 副本列表将显示在文件夹版本：框中。列出的 Snapshot 副本由 Snapshot 副本名称前缀和创建时间戳标识。

. 在 * 文件夹版本： * 框中，右键单击要管理的文件或文件夹的副本。
. 执行相应的操作：
+
|===
| 如果您要 ... | 执行以下操作 ... 


 a| 
查看该 Snapshot 副本中的数据
 a| 
单击 * 打开 * 。



 a| 
从该 Snapshot 副本创建一份数据副本
 a| 
单击 * 复制 * 。

|===
+
Snapshot 副本中的数据为只读。如果要修改 " 先前版本 " 选项卡中列出的文件和文件夹，必须将要修改的文件和文件夹的副本保存到可写位置，并对这些副本进行修改。

. 管理完 Snapshot 数据后，单击 * 确定 * 以关闭 * 属性 * 对话框。
+
有关使用先前版本选项卡查看和管理 Snapshot 数据的详细信息，请参阅 Microsoft TechNet 库。



http://technet.microsoft.com/en-us/library/["Microsoft TechNet 库： technet.microsoft.com/en-us/library/"]
