---
permalink: smb-admin/update-domain-user-group-names-local-databases-task.html 
sidebar: sidebar 
keywords: add, domain, users, groups, cifs, server, local, register, database, manual, update, update domain user and group names in local databases 
summary: 您可以将域用户和组添加到 CIFS 服务器的本地组。这些域对象会注册到集群上的本地数据库中。如果重命名域对象，则必须手动更新本地数据库。 
---
= 更新本地数据库中的域用户和组名称
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以将域用户和组添加到 CIFS 服务器的本地组。这些域对象会注册到集群上的本地数据库中。如果重命名域对象，则必须手动更新本地数据库。

.关于此任务
您必须指定要更新域名的 Storage Virtual Machine （ SVM ）的名称。

.步骤
. 将权限级别设置为高级： `set -privilege advanced`
. 执行相应的操作：
+
|===
| 要更新域用户和组以及 ... | 使用此命令 ... 


 a| 
显示成功更新和无法更新的域用户和组
 a| 
`vserver cifs users-and-groups update-names -vserver _vserver_name_`



 a| 
显示已成功更新的域用户和组
 a| 
`vserver cifs users-and-groups update-names -vserver _vserver_name_ -display-failed-only false`



 a| 
仅显示无法更新的域用户和组
 a| 
`vserver cifs users-and-groups update-names -vserver _vserver_name_ -display-failed-only true`



 a| 
禁止有关更新的所有状态信息
 a| 
`vserver cifs users-and-groups update-names -vserver _vserver_name_ -suppress-all-output true`

|===
. 返回到管理权限级别： `set -privilege admin`


.示例
以下示例将更新与 Storage Virtual Machine （ SVM ，以前称为 Vserver ） vs1 关联的域用户和组的名称。对于上次更新，需要更新一组依赖名称：

[listing]
----
cluster1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them
only when directed to do so by technical support personnel.
Do you wish to continue? (y or n): y

cluster1::*> vserver cifs users-and-groups update-names -vserver vs1

   Vserver:           vs1
   SID:               S-1-5-21-123456789-234565432-987654321-12345
   Domain:            EXAMPLE1
   Out-of-date Name:  dom_user1
   Updated Name:      dom_user2
   Status:            Successfully updated

   Vserver:           vs1
   SID:               S-1-5-21-123456789-234565432-987654322-23456
   Domain:            EXAMPLE2
   Out-of-date Name:  dom_user1
   Updated Name:      dom_user2
   Status:            Successfully updated

   Vserver:           vs1
   SID:               S-1-5-21-123456789-234565432-987654321-123456
   Domain:            EXAMPLE1
   Out-of-date Name:  dom_user3
   Updated Name:      dom_user4
   Status:            Successfully updated; also updated SID "S-1-5-21-123456789-234565432-987654321-123457"
                      to name "dom_user5"; also updated SID "S-1-5-21-123456789-234565432-987654321-123458"
                      to name "dom_user6"; also updated SID "S-1-5-21-123456789-234565432-987654321-123459"
                      to name "dom_user7"; also updated SID "S-1-5-21-123456789-234565432-987654321-123460"
                      to name "dom_user8"

The command completed successfully. 7 Active Directory objects have been updated.

cluster1::*> set -privilege admin
----