---
permalink: mediator/host-maintenance-task.html 
sidebar: sidebar 
keywords: mediator, maintain, host, maintenance, package update, kernal upgrade, change hostname, change IP, self-signed certificate, self signed certificate 
summary: 为了获得最佳性能、应定期维护ONTAP 调解器的主机OD。 
---
= 维护ONTAP调解器的主机操作系统
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
为了获得最佳性能、您应定期维护ONTAP 调解器的主机操作系统。



== 重新启动主机

当集群运行状况良好时、重新启动主机。当 ONTAP 调解器处于离线状态时，集群可能无法正确应对故障。如果需要重新启动、建议使用服务窗口。

ONTAP 调解器将在重新启动期间自动恢复、并将重新输入先前使用ONTAP 集群配置的关系。



== 主机软件包更新

可以安全地更新任何库或yum软件包(内核除外)、但可能需要重新启动才能生效。   如果需要重新启动、建议使用服务窗口。

如果安装 `yum-utils` 软件包、请使用 `needs-restarting` 用于检测任何软件包更改是否需要重新启动的命令。

如果更新了任何ONTAP 调解器依赖关系、则应重新启动、因为它们不会立即对正在运行的进程生效。



== 主机操作系统次要内核升级

必须为正在使用的内核编译SCST。  要更新操作系统、需要维护窗口。

.步骤
执行以下步骤升级主机操作系统内核。

. 停止 ONTAP 调解器。
. 卸载SCST软件包。  (SCST不提供升级机制。)
. 升级操作系统并重新启动。
. 重新安装SCST软件包。
. 重新启用 ONTAP 调解器。




== 主机更改为主机名或IP

.关于此任务
* 在安装了 ONTAP Mediator 的 Linux 主机上执行此任务。
* 仅当安装 ONTAP 调解器后，由于主机的主机名或 IP 地址发生更改而导致生成的自签名证书已过时时，您才可以执行此任务。
* 在临时自签名证书被可信的第三方证书替换后、您不能使用此任务重新生成证书。  如果没有自签名证书、则发生原因此操作步骤将失败。


.步骤
要为当前主机重新生成新的临时自签名证书、请执行以下步骤：

. 重新启动 ONTAP 调解器：
+
`./make_self_signed_certs.sh overwrite`

+
[listing]
----
[root@xyz000123456 ~]# cd /opt/netapp/lib/ontap_mediator/ontap_mediator/server_config
[root@xyz000123456 server_config]# ./make_self_signed_certs.sh overwrite

Adding Subject Alternative Names to the self-signed server certificate
#
# OpenSSL example configuration file.
Generating self-signed certificates
Generating RSA private key, 4096 bit long modulus (2 primes)
..................................................................................................................................................................++++
........................................................++++
e is 65537 (0x010001)
Generating a RSA private key
................................................++++
.............................................................................................................................................++++
writing new private key to 'ontap_mediator_server.key'
-----
Signature ok
subject=C = US, ST = California, L = San Jose, O = "NetApp, Inc.", OU = ONTAP Core Software, CN = ONTAP Mediator, emailAddress = support@netapp.com
Getting CA Private Key

[root@xyz000123456 server_config]# systemctl restart ontap_mediator
----

