---
permalink: mediator/index.html 
sidebar: sidebar 
keywords: ontap mediator service, install requirements, mediator requirements 
summary: 要安装 ONTAP 调解器服务，必须确保满足所有前提条件，获取安装包并在主机上运行安装程序。 
---
= 安装或升级 ONTAP 调解器服务
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
要安装 ONTAP 调解器服务，必须确保满足所有前提条件，获取安装包并在主机上运行安装程序。此操作步骤用于安装或升级现有安装。

.关于此任务
* 从ONTAP 9.7开始、您可以使用任何版本的ONTAP 调解器来监控MetroCluster IP配置。
* 从ONTAP 9.8开始、您可以使用任何版本的ONTAP 调解器来监控SM-BC关系。


您必须满足以下前提条件。

[cols="30,70"]
|===


| 调解器版本 | 支持的 Linux 版本 


 a| 
1.5
 a| 
* Red Hat Enterprise Linux：7.6、7.7、7.8、7.9、8.1、 8.2、8.3、8.4、8.5
* CentOS ： 7.6 ， 7.7 ， 7.8 ， 7.9




 a| 
1.4.
 a| 
* Red Hat Enterprise Linux：7.6、7.7、7.8、7.9、8.1、 8.2、8.3、8.4、8.5
* CentOS ： 7.6 ， 7.7 ， 7.8 ， 7.9




 a| 
1.3
 a| 
* Red Hat Enterprise Linux：7.6、7.7、7.8、7.9、8.1、 8.2、8.3
* CentOS ： 7.6 ， 7.7 ， 7.8 ， 7.9




 a| 
1.2
 a| 
* Red Hat Enterprise Linux：7.6、7.7、7.8、8.1
* CentOS ： 7.6 ， 7.7 ， 7.8


|===

NOTE: 内核版本必须与操作系统版本匹配。

* 64 位物理安装或虚拟机
* 8 GB RAM
* 用户： root 访问权限




== 依次升级主机操作系统和调解器

下表提供了从 RHEL/CentOS 7.6 升级到更高版本 RHEL/CentOS 以及升级调解器版本的升级准则。

[cols="20,20,60"]
|===


| 目标 Linux 版本 | 目标调解器版本 | 升级说明 


 a| 
* Red Hat Enterprise Linux：7.6、7.7、7.8、8.1
* CentOS ： 7.6 ， 7.7 ， 7.8

 a| 
1.2
 a| 
* 必须按以下顺序执行升级：
+
.. 从 RHEL/CentOS 版本升级操作系统。
.. 重新启动主机以应用内核模块更改。
.. 将调解器从先前版本升级到当前版本。


* 对于 MetroCluster ：
+
.. storage iscsi-initiator show 命令将报告升级期间与调解器服务的连接已关闭。
.. ONTAP 操作系统将生成以下 EMS 事件：
+
... cf.mccip.med.auso.stDisabled
... 重新启用自动计划外切换时显示 cf.mccip.med.auso.stEnabled








 a| 
* Red Hat Enterprise Linux：7.6、7.7、7.8、7.9、8.1、 8.2、8.3
* CentOS ： 7.6 ， 7.7 ， 7.8 ， 7.9

 a| 
1.3
 a| 
. 从 RHEL/CentOS 版本升级操作系统。
. 重新启动主机以应用内核模块更改。
. 将调解器从先前版本升级到当前版本。




 a| 
* Red Hat Enterprise Linux：7.6、7.7、7.8、7.9、8.1、 8.2、8.3、8.4、8.5
* CentOS ： 7.6 ， 7.7 ， 7.8 ， 7.9

 a| 
1.4.
 a| 
. 从 RHEL/CentOS 版本升级操作系统。
. 重新启动主机以应用内核模块更改。
. 将调解器从先前版本升级到当前版本。




 a| 
* Red Hat Enterprise Linux：7.6、7.7、7.8、7.9、8.1、 8.2、8.3、8.4、8.5
* CentOS ： 7.6 ， 7.7 ， 7.8 ， 7.9

 a| 
1.5
 a| 
. 从 RHEL/CentOS 版本升级操作系统。
. 重新启动主机以应用内核模块更改。如果不重新启动主机、则会显示一条错误消息、提示您执行重新启动。
. 将调解器从先前版本升级到当前版本。


|===
下面列出了在系统上安装 Red Hat Enterprise Linux 或 CentOS 以及关联存储库的最佳实践。以不同方式安装或配置的系统可能需要执行其他步骤。

* 您必须根据 Red Hat 最佳实践安装 Red Hat Enterprise Linux 或 CentOS 。由于CentOS 8.x版本支持生命周期终结、因此不建议使用兼容版本的CentOS 8.x。
* 在 Red Hat Enterprise Linux 或 CentOS 上安装 ONTAP 调解器服务时，系统必须能够访问相应的存储库，以便安装程序可以访问和安装所有必需的软件依赖项。
* 要使 yum 安装程序在 Red Hat Enterprise Linux 存储库中查找相关软件，您必须在 Red Hat Enterprise Linux 安装期间或之后使用有效的 Red Hat 订阅注册系统。
+
有关 Red Hat 订阅管理器的信息，请参见 Red Hat 文档。

* 必须未使用以下端口，这些端口可用于调解器：
+
** 31784
** 3260


* 如果使用第三方防火墙：请参见 link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_mediator_requirements.html#firewall-requirements-for-ontap-mediator["ONTAP 调解器的防火墙要求"^]
* 如果Linux主机所在位置无法访问Internet、则必须确保所需的软件包在本地存储库中可用。
+
如果您在 Linux 环境中使用链路聚合控制协议（ Link Aggregation Control Protocol ， LACP ），则必须正确配置内核，并确保 `sysctl net.IPv4.conf.all.arp_ignore` 设置为 "2" 。

+
ONTAP 调解器服务需要以下软件包：

+
[cols="25,35,40"]
|===


| 所有 RHEL/CentOS 版本 | 适用于 RHEL/CentOS 7.x 的其他软件包 | 适用于 RHEL 8.x 的其他软件包 


 a| 
** OpenSSL
** OpenSSL 开发
** 内核开发
** GCC
** libselinux-utils
** 创建
** RedHat-lsb-core
** patch
** bzip 2
** python36
** python36- devel
** Perl 数据 - Dumper
** Perl 扩展程序 -MakeMaker
** python3-pip

 a| 
** policycoreutils-python
** python36 pip

 a| 
** elfutils-libelf-devel
** policycoreutils-python 实用程序


|===


调解器安装包是一个自解压压缩 tar 文件，其中包括：

* 一个 RPM 文件，其中包含无法从受支持版本的存储库获取的所有依赖项。
* 安装脚本。


建议使用有效的 SSL 认证，如本操作步骤中所述。



== 启用对存储库的访问

|===


| 操作系统 | 您必须提供对这些存储库的访问权限 ... 


 a| 
RHEL 7.x
 a| 
rhel-7-server-optional -rpms



 a| 
CentOS 7.x
 a| 
C7.6.1810 —基本存储库



 a| 
RHEL 8.x
 a| 
* rhel-8-for-x86_64 — basos-rpms
* rhel-8-for-x86_64 — AppStream — rpms


|===
启用对上述存储库的访问，以便调解器可以在安装过程中访问所需的软件包。请根据您的操作系统使用以下操作步骤。

* 适用于的操作步骤 ,RHEL 7.x 操作系统
* 适用于的操作步骤 ,RHEL 8.x 操作系统
* 适用于的操作步骤 ,CentOS 7.x 操作系统




=== 适用于 RHEL 7.x 操作系统的操作步骤

如果您的操作系统为 * RHEL 7.x* ：

.步骤
. 订阅所需的存储库：
+
`ssubscription-manager repos-enable rhel-7-server-optional-rpms`

+
以下示例显示了此命令的执行情况：

+
[listing]
----
[root@localhost ~]# subscription-manager repos --enable rhel-7-server-optional-rpms
Repository 'rhel-7-server-optional-rpms' is enabled for this system.
----
. 运行 `yum repolist` 命令。
+
以下示例显示了此命令的执行情况。列表中应显示 rhel-7-server-optional -rpms 存储库。

+
[listing]
----
[root@localhost ~]# yum repolist
Loaded plugins: product-id, search-disabled-repos, subscription-manager
rhel-7-server-optional-rpms | 3.2 kB  00:00:00
rhel-7-server-rpms | 3.5 kB  00:00:00
(1/3): rhel-7-server-optional-rpms/7Server/x86_64/group                                               |  26 kB  00:00:00
(2/3): rhel-7-server-optional-rpms/7Server/x86_64/updateinfo                                          | 2.5 MB  00:00:00
(3/3): rhel-7-server-optional-rpms/7Server/x86_64/primary_db                                          | 8.3 MB  00:00:01
repo id                                      repo name                                             status
rhel-7-server-optional-rpms/7Server/x86_64   Red Hat Enterprise Linux 7 Server - Optional (RPMs)   19,447
rhel-7-server-rpms/7Server/x86_64            Red Hat Enterprise Linux 7 Server (RPMs)              26,758
repolist: 46,205
[root@localhost ~]#
----




=== 适用于 RHEL 8.x 操作系统的操作步骤

如果您的操作系统为 * RHEL 8.x * ：

.步骤
. 订阅所需的存储库：
+
`ssubscription-manager repos-enable rhel-8-for-x86_64 basos-rpms`

+
`ssubscription-manager repos-enable rhel-8-for-x86_64 -AppStream -rpms`

+
以下示例显示了此命令的执行情况：

+
[listing]
----
[root@localhost ~]# subscription-manager repos --enable rhel-8-for-x86_64-baseos-rpms
[root@localhost ~]# subscription-manager repos --enable rhel-8-for-x86_64-appstream-rpms
Repository 'rhel-8-for-x86_64-baseos-rpms' is enabled for this system.
Repository 'rhel-8-for-x86_64-appstream-rpms' is enabled for this system.
----
. 运行 `yum repolist` 命令。
+
新订阅的存储库应显示在列表中。





=== 适用于 CentOS 7.x 操作系统的操作步骤

如果您的操作系统为 * CentOS 7.x * ：


NOTE: 以下示例显示了适用于CentOS 7.6的存储库、可能无法用于其他CentOS版本。使用适用于您的CentOS版本的基础存储库。

.步骤
. 添加 C7.6.1810 —基本存储库。C7.6.1810 —基础存储库包含 ONTAP 调解器所需的 kernel-devel 软件包。
. 将以下行添加到 /etc/yum.repos.d/Centos-vault.repo.
+
[listing]
----
[C7.6.1810-base]
name=CentOS-7.6.1810 - Base
baseurl=http://vault.centos.org/7.6.1810/os/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
enabled=1
----
. 运行 `yum repolist` 命令。
+
以下示例显示了此命令的执行情况。CentOS-7.6.1810 —基本存储库应显示在列表中。

+
[listing]
----
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: distro.ibiblio.org
 * extras: distro.ibiblio.org
 * updates: ewr.edge.kernel.org
C7.6.1810-base                                                   | 3.6 kB  00:00:00
(1/2): C7.6.1810-base/x86_64/group_gz                            | 166 kB  00:00:00
(2/2): C7.6.1810-base/x86_64/primary_db                          | 6.0 MB  00:00:04
repo id                                           repo name                                                                                                    status
C7.6.1810-base/x86_64                             CentOS-7.6.1810 - Base                                                                                       10,019
base/7/x86_64                                     CentOS-7 - Base                                                                                              10,097
extras/7/x86_64                                   CentOS-7 - Extras                                                                                               307
updates/7/x86_64                                  CentOS-7 - Updates                                                                                            1,010
repolist: 21,433
[root@localhost ~]#
----




== 下载调解器安装包

.步骤
. 从 ONTAP 调解器页面下载调解器安装包。
+
https://mysupport.netapp.com/site/products/all/details/ontap-mediator/downloads-tab["ONTAP 调解器下载页面"^]

. 确认调解器安装包位于当前工作目录中：
+
`ls`

+
[listing]
----
[root@mediator-host ~]#ls
ontap-mediator-1.5.0.tgz
----
+

NOTE: 对于ONTAP 调解器1.4及更早版本、安装程序名为 `ontap-mediator`。

+
如果您所在位置无法访问 Internet ，则必须确保安装程序能够访问所需的软件包。

. 如有必要，请将调解器安装包从下载目录移至 Linux 调解器主机上的安装目录。
. 解压缩安装程序包： `tar xvfz ontap-mediator-1.5.0.tgz`
+
[listing]
----
[root@scs000099753 ~]# tar xvfz ontap-mediator-1.5.0.tgz
ontap-mediator-1.5.0/
ontap-mediator-1.5.0/ONTAP-Mediator-production.pub
ontap-mediator-1.5.0/tsa-prod-chain-ONTAP-Mediator.pem
ontap-mediator-1.5.0/tsa-prod-ONTAP-Mediator.pem
ontap-mediator-1.5.0/csc-prod-ONTAP-Mediator.pem
ontap-mediator-1.5.0/csc-prod-chain-ONTAP-Mediator.pem
ontap-mediator-1.5.0/ontap-mediator-1.5.0
ontap-mediator-1.5.0/ontap-mediator-1.5.0.sig.tsr
ontap-mediator-1.5.0/ontap-mediator-1.5.0.tsr
ontap-mediator-1.5.0/ontap-mediator-1.5.0.sig

----




== 验证ONTAP 调解器代码签名

在安装调解器安装包之前、您应验证ONTAP 调解器代码签名。

在验证调解器代码签名之前、您的系统必须满足以下要求。

* OpenSSL 1.0.2到3.0版、用于基本验证
* 适用于时间戳颁发机构(TSA)操作的OpenSSL 1.1.0或更高版本
* 用于OCSP验证的公有 Internet访问



NOTE: 下载包中包含以下文件：

* `ONTAP-Mediator-development.pub` 用于验证签名的公有 密钥
* `csc-prod-chain-ONTAP-Mediator.pem` |公有 认证CA信任链
* `csc-prod-ONTAP-Mediator.pem` 用于生成密钥的证书
* `ontap-mediator-1.5.0` 我们提供了1.5.0版的产品安装可执行文件
* `ontap-mediator-1.5.0.sig` 我们使用CSC-prod密钥对安装程序签名SHA-256进行哈希、然后使用RSA签名
* `ontap-mediator-1.5.0.sig.tsr` | OCSCP用于安装程序签名的撤消请求
* `tsa-prod-ONTAP-Mediator.pem` |用于此TSR.的公有 证书
* `tsa-prod-chain-ONTAP-Mediator.pem` |用于此TSR.的公有 证书CA链


.步骤
. 对执行撤消检查 `csc-prod-ONTAP-Mediator.pem` 使用联机证书状态协议(OCSP)。
+
.. 查找用于注册证书的OCSP URL、因为开发人员证书可能不提供URI。
+
[listing]
----
openssl x509 -noout -ocsp_uri -in csc-prod-chain-ONTAP-Mediator.pem
----
.. 生成证书的OCSP请求。
+
[listing]
----
openssl ocsp -issuer csc-prod-chain-ONTAP-Mediator.pem -CAfile csc-prod-chain-ONTAP-Mediator.pem -cert csc-prod-ONTAP-Mediator.pem  -reqout req.der
----
.. 连接到OCSP Manager以发送OCSP请求： `openssl`
+
[listing]
----
openssl ocsp -issuer csc-prod-chain-ONTAP-Mediator.pem -CAfile csc-prod-chain-ONTAP-Mediator.pem -cert csc-prod-ONTAP-Mediator.pem  -url ${ocsp_uri} -resp_text -respout resp.der
----


. 验证CSC的信任链以及本地主机的到期日期： `openssl verify`
+

NOTE: 。 `openssl` 路径中的版本必须有效 `cert.pem` (非自签名)。

+
[listing]
----
openssl verify -untrusted csc-prod-chain-ONTAP-Mediator.pem -CApath ${OPENSSLDIR} csc-prod-ONTAP-Mediator.pem  # Failure action: The Code-Signature-Check certificate has expired or is invalid. Download a newer version of the ONTAP Mediator.
openssl verify -untrusted tsa-prod-chain-ONTAP-Mediator.pem -CApath ${OPENSSLDIR} tsa-prod-ONTAP-Mediator.pem  # Failure action: The Time-Stamp certificate has expired or is invalid. Download a newer version of the ONTAP Mediator.
----
. 验证 `ontap-mediator-1.5.0.sig.tsr` 和 `ontap-mediator-1.5.0.tsr` 使用关联证书的文件： `openssl ts -verify`
+

NOTE: `.tsr` 文件包含与安装程序关联的时间戳响应以及代码签名。处理过程会确认时间戳具有来自TSA的有效签名、并且您的输入文件未更改。此验证将在您的计算机上本地执行。独立地、无需访问TSA服务器。

+
[listing]
----
openssl ts -verify -data ontap-mediator-1.5.0.sig -in ontap-mediator-1.5.0.sig.tsr -CAfile tsa-prod-chain-ONTAP-Mediator.pem -untrusted tsa-prod-ONTAP-Mediator.pem
openssl ts -verify -data ontap-mediator-1.5.0 -in ontap-mediator-1.5.0.tsr -CAfile tsa-prod-chain-ONTAP-Mediator.pem -untrusted tsa-prod-ONTAP-Mediator.pem
----
. 根据密钥验证签名：  `openssl -dgst -verify`
+
[listing]
----
openssl dgst -sha256 -verify ONTAP-Mediator-production.pub -signature ontap-mediator-1.5.0.sig ontap-mediator-1.5.0
----


.验证ONTAP 调解器代码签名示例(控制台输出)
[%collapsible]
====
[listing]
----
[root@scspa2695423001 ontap-mediator-1.5.0]# pwd
/root/ontap-mediator-1.5.0
[root@scspa2695423001 ontap-mediator-1.5.0]# ls -l
total 63660
-r--r--r-- 1 root root     8582 Oct 19 15:02 csc-prod-chain-ONTAP-Mediator.pem
-r--r--r-- 1 root root     2373 Oct 19 15:02 csc-prod-ONTAP-Mediator.pem
-r-xr-xr-- 1 root root 65132818 Oct 20 15:17 ontap-mediator-1.5.0
-rw-r--r-- 1 root root      384 Oct 20 15:17 ontap-mediator-1.5.0.sig
-rw-r--r-- 1 root root     5437 Oct 20 15:17 ontap-mediator-1.5.0.sig.tsr
-rw-r--r-- 1 root root     5436 Oct 20 15:17 ontap-mediator-1.5.0.tsr
-r--r--r-- 1 root root      625 Oct 19 15:02 ONTAP-Mediator-production.pub
-r--r--r-- 1 root root     3323 Oct 19 15:02 tsa-prod-chain-ONTAP-Mediator.pem
-r--r--r-- 1 root root     1740 Oct 19 15:02 tsa-prod-ONTAP-Mediator.pem
[root@scspa2695423001 ontap-mediator-1.5.0]#
[root@scspa2695423001 ontap-mediator-1.5.0]# /root/verify_ontap_mediator_signatures.sh
++ openssl version -d
++ cut -d '"' -f2
+ OPENSSLDIR=/etc/pki/tls
+ openssl version
OpenSSL 1.1.1k  FIPS 25 Mar 2021
++ openssl x509 -noout -ocsp_uri -in csc-prod-chain-ONTAP-Mediator.pem
+ ocsp_uri=http://ocsp.entrust.net
+ echo http://ocsp.entrust.net
http://ocsp.entrust.net
+ openssl ocsp -issuer csc-prod-chain-ONTAP-Mediator.pem -CAfile csc-prod-chain-ONTAP-Mediator.pem -cert csc-prod-ONTAP-Mediator.pem -reqout req.der
+ openssl ocsp -issuer csc-prod-chain-ONTAP-Mediator.pem -CAfile csc-prod-chain-ONTAP-Mediator.pem -cert csc-prod-ONTAP-Mediator.pem -url http://ocsp.entrust.net -resp_text -respout resp.der
OCSP Response Data:
    OCSP Response Status: successful (0x0)
    Response Type: Basic OCSP Response
    Version: 1 (0x0)
    Responder Id: C = US, O = "Entrust, Inc.", CN = Entrust Extended Validation Code Signing CA - EVCS2
    Produced At: Oct 28 05:01:00 2022 GMT
    Responses:
    Certificate ID:
      Hash Algorithm: sha1
      Issuer Name Hash: 69FA640329AB84E27220FE0927647B8194B91F2A
      Issuer Key Hash: CE894F8251AA15A28462CA312361D261FBF8FE78
      Serial Number: 511A542B57522AEB7295A640DC6200E5
    Cert Status: good
    This Update: Oct 28 05:00:00 2022 GMT
    Next Update: Nov  4 04:59:59 2022 GMT

    Signature Algorithm: sha512WithRSAEncryption
         3c:1d:49:b0:93:62:37:3e:c7:38:e3:9f:9f:62:82:73:ed:f4:
         ea:00:6b:f1:01:cd:79:57:92:f1:9d:5d:85:9b:60:59:f8:6c:
         e6:f4:50:51:f3:4c:8a:51:dd:50:68:16:8f:20:24:7e:39:b0:
         44:94:8d:b0:61:da:b9:08:36:74:2d:44:55:62:fb:92:be:4a:
         e7:6c:8c:49:dd:0c:fd:d8:ce:20:08:0d:0f:5a:29:a3:19:03:
         9f:d3:df:41:f4:89:0f:73:18:3f:ac:bb:a7:a3:96:7d:c5:70:
         4c:57:cd:17:17:c6:8a:60:d1:37:c9:2d:81:07:2a:d7:a6:02:
         ee:ce:88:16:22:db:e3:43:64:1e:9b:0d:4d:31:66:fa:ab:a5:
         52:99:94:4a:4a:d0:52:c5:34:f5:18:c7:15:5b:ce:74:c2:fc:
         61:ea:55:aa:f1:2f:82:a3:6a:95:8d:7e:2b:38:49:4f:bf:b1:
         68:7b:1b:24:8b:1f:4d:c5:77:f0:71:af:9c:34:c8:7a:82:50:
         09:a2:19:6e:c6:30:4f:da:a2:79:08:f9:d0:ff:85:d9:2a:84:
         cf:0c:aa:75:8f:72:c9:a7:a2:83:e8:8b:cf:ed:0c:69:75:b6:
         2a:7b:6b:58:99:01:d8:34:ad:e1:89:25:27:1b:fa:d9:6d:32:
         97:3a:0b:0a:8e:a3:9e:e3:f4:e0:d6:1a:c9:b5:14:8c:3e:54:
         3b:37:17:1a:93:44:84:8b:4a:87:97:1e:76:43:3e:d3:ec:8b:
         7e:56:4a:3f:01:31:c0:e5:58:fb:50:ce:6f:b1:e7:35:f9:b7:
         a3:ef:6b:3b:21:95:37:a6:5b:8f:f0:15:18:36:65:89:a1:9c:
         9b:69:00:b4:b1:65:6a:bc:11:2d:d4:9b:b4:97:cc:cb:7a:0c:
         16:11:c1:75:58:7e:13:ab:56:3c:3f:93:5b:95:24:c6:54:52:
         1f:86:a9:16:ce:d9:ea:8b:3a:f3:4f:c4:8f:ad:de:e8:3e:3c:
         d2:51:51:ad:33:7f:d8:c5:33:24:26:f1:2d:9d:0e:9f:55:d0:
         68:bf:af:bd:68:4a:40:08:bc:92:a0:62:54:7d:16:7b:36:29:
         15:b1:cd:58:8e:fb:4a:f2:3e:94:8b:fe:56:95:cc:24:32:af:
         5f:71:99:18:ed:0c:64:94:f7:54:48:87:48:d0:6d:b3:42:04:
         96:03:73:a2:8e:8a:6a:b2:af:ee:56:19:a1:c6:35:12:59:ad:
         19:6a:fe:e0:f1:27:cc:96:4e:f0:4f:fb:6a:bd:ce:05:2c:aa:
         79:7c:df:02:5c:ca:53:7d:60:12:88:7c:ce:15:c7:d4:02:27:
         c1:ab:cf:71:30:1e:14:ba
WARNING: no nonce in response
Response verify OK
csc-prod-ONTAP-Mediator.pem: good
        This Update: Oct 28 05:00:00 2022 GMT
        Next Update: Nov  4 04:59:59 2022 GMT
+ openssl verify -untrusted csc-prod-chain-ONTAP-Mediator.pem -CApath /etc/pki/tls csc-prod-ONTAP-Mediator.pem
csc-prod-ONTAP-Mediator.pem: OK
+ openssl verify -untrusted tsa-prod-chain-ONTAP-Mediator.pem -CApath /etc/pki/tls tsa-prod-ONTAP-Mediator.pem
tsa-prod-ONTAP-Mediator.pem: OK
+ openssl ts -verify -data ontap-mediator-1.5.0.sig -in ontap-mediator-1.5.0.sig.tsr -CAfile tsa-prod-chain-ONTAP-Mediator.pem -untrusted tsa-prod-ONTAP-Mediator.pem
Using configuration from /etc/pki/tls/openssl.cnf
Verification: OK
+ openssl ts -verify -data ontap-mediator-1.5.0 -in ontap-mediator-1.5.0.tsr -CAfile tsa-prod-chain-ONTAP-Mediator.pem -untrusted tsa-prod-ONTAP-Mediator.pem
Using configuration from /etc/pki/tls/openssl.cnf
Verification: OK
+ openssl dgst -sha256 -verify ONTAP-Mediator-production.pub -signature ontap-mediator-1.5.0.sig ontap-mediator-1.5.0
Verified OK
[root@scspa2695423001 ontap-mediator-1.5.0]#

----
====


== 安装 ONTAP 调解器安装包

.关于此任务
* 从ONTAP 调解器1.4开始、安全启动机制在UEFI系统上启用。启用安全启动后、您必须执行其他步骤、以便在安装后注册安全密钥：
+
** 按照README文件中的说明进行操作：`/opt/netapp/lib/ontap_medier/ontap_medier/scST_mod_keys/README.module-signing`对SCST内核模块进行签名。
** 找到所需密钥：`/opt/netapp/lib/ontap_medier/ontap_medier/scST_mod_keys`


+

NOTE: 安装后、系统输出中还会提供README文件和密钥位置。



.步骤
. 运行安装程序并根据需要响应提示： `./ontap-mediator-1.5.0/ontap-mediator-1.5.0 -y`
+
[listing]
----
[root@scs000099753 ~]# ./ontap-mediator-1.5.0/ontap-mediator-1.5.0 -y
----
+
安装过程将继续创建所需的帐户并安装所需的软件包。如果主机上安装了先前版本的调解器，系统将提示您确认是否要升级。



.ONTAP 调解器1.5安装示例(控制台输出)
[%collapsible]
====
[listing]
----
[root@scs000099753 ~]# ./ontap-mediator-1.5.0/ontap-mediator-1.5.0 -y
ONTAP Mediator: Self Extracting Installer


+ Extracting the ONTAP Mediator installation/upgrade archive
+ Performing the ONTAP Mediator run-time code signature check
   Using openssl from the path: /usr/bin/openssl configured for CApath:/etc/pki/tls

+ Unpacking the ONTAP Mediator installer
ONTAP Mediator requires two user accounts. One for the service (netapp), and one for use by ONTAP to the mediator API (mediatoradmin).
Using default account names: netapp + mediatoradmin

Enter ONTAP Mediator user account (mediatoradmin) password:

Re-Enter ONTAP Mediator user account (mediatoradmin) password:

+ Checking if SELinux is in enforcing mode


+ Checking for default Linux firewall
success
success
success


###############################################################
Preparing for installation of ONTAP Mediator packages.


+ Installing required packages.


Last metadata expiration check: 0:25:24 ago on Fri 21 Oct 2022 04:00:13 PM EDT.
Package openssl-1:1.1.1k-4.el8.x86_64 is already installed.
Package gcc-8.4.1-1.el8.x86_64 is already installed.
Package python36-3.6.8-2.module+el8.1.0+3334+5cb623d7.x86_64 is already installed.
Package libselinux-utils-2.9-5.el8.x86_64 is already installed.
Package perl-Data-Dumper-2.167-399.el8.x86_64 is already installed.
Package efibootmgr-16-1.el8.x86_64 is already installed.
Package mokutil-1:0.3.0-11.el8.x86_64 is already installed.
Package python3-pip-9.0.3-19.el8.noarch is already installed.
Package policycoreutils-python-utils-2.9-14.el8.noarch is already installed.
Dependencies resolved.
========================================================================================================================================================================================
 Package                                       Architecture            Version                                                  Repository                                         Size
========================================================================================================================================================================================
Installing:
 bzip2                                         x86_64                  1.0.6-26.el8                                             rhel-8-for-x86_64-baseos-rpms                      60 k
 elfutils-libelf-devel                         x86_64                  0.186-1.el8                                              rhel-8-for-x86_64-baseos-rpms                      60 k
 kernel-devel                                  x86_64                  4.18.0-348.el8                                           rhel-8-for-x86_64-baseos-rpms                      20 M
 make                                          x86_64                  1:4.2.1-11.el8                                           rhel-8-for-x86_64-baseos-rpms                     498 k
 openssl-devel                                 x86_64                  1:1.1.1k-7.el8_6                                         rhel-8-for-x86_64-baseos-rpms                     2.3 M
 patch                                         x86_64                  2.7.6-11.el8                                             rhel-8-for-x86_64-baseos-rpms                     138 k
 perl-ExtUtils-MakeMaker                       noarch                  1:7.34-1.el8                                             rhel-8-for-x86_64-appstream-rpms                  301 k
 python36-devel                                x86_64                  3.6.8-38.module+el8.5.0+12207+5c5719bc                   rhel-8-for-x86_64-appstream-rpms                   17 k
 redhat-lsb-core                               x86_64                  4.1-47.el8                                               rhel-8-for-x86_64-appstream-rpms                   45 k
Upgrading:
 cpp                                           x86_64                  8.5.0-10.1.el8_6                                         rhel-8-for-x86_64-appstream-rpms                   10 M
 elfutils-libelf                               x86_64                  0.186-1.el8                                              rhel-8-for-x86_64-baseos-rpms                     229 k
 elfutils-libs                                 x86_64                  0.186-1.el8                                              rhel-8-for-x86_64-baseos-rpms                     295 k
 gcc                                           x86_64                  8.5.0-10.1.el8_6                                         rhel-8-for-x86_64-appstream-rpms                   23 M
 libgcc                                        x86_64                  8.5.0-10.1.el8_6                                         rhel-8-for-x86_64-baseos-rpms                      80 k
 libgomp                                       x86_64                  8.5.0-10.1.el8_6                                         rhel-8-for-x86_64-baseos-rpms                     207 k
 libsemanage                                   x86_64                  2.9-8.el8                                                rhel-8-for-x86_64-baseos-rpms                     168 k
 mokutil                                       x86_64                  1:0.3.0-11.el8_6.1                                       rhel-8-for-x86_64-baseos-rpms                      46 k
 openssl                                       x86_64                  1:1.1.1k-7.el8_6                                         rhel-8-for-x86_64-baseos-rpms                     709 k
 openssl-libs                                  x86_64                  1:1.1.1k-7.el8_6                                         rhel-8-for-x86_64-baseos-rpms                     1.5 M
 platform-python-pip                           noarch                  9.0.3-22.el8                                             rhel-8-for-x86_64-baseos-rpms                     1.6 M
 policycoreutils                               x86_64                  2.9-19.el8                                               rhel-8-for-x86_64-baseos-rpms                     374 k
 policycoreutils-python-utils                  noarch                  2.9-19.el8                                               rhel-8-for-x86_64-baseos-rpms                     253 k
 python3-libsemanage                           x86_64                  2.9-8.el8                                                rhel-8-for-x86_64-baseos-rpms                     128 k
 python3-pip                                   noarch                  9.0.3-22.el8                                             rhel-8-for-x86_64-appstream-rpms                   20 k
 python3-policycoreutils                       noarch                  2.9-19.el8                                               rhel-8-for-x86_64-baseos-rpms                     2.2 M
 python36                                      x86_64                  3.6.8-38.module+el8.5.0+12207+5c5719bc                   rhel-8-for-x86_64-appstream-rpms                   19 k
Installing dependencies:
 annobin                                       x86_64                  10.29-3.el8                                              rhel-8-for-x86_64-appstream-rpms                  117 k
 at                                            x86_64                  3.1.20-11.el8                                            rhel-8-for-x86_64-baseos-rpms                      81 k
 bc                                            x86_64                  1.07.1-5.el8                                             rhel-8-for-x86_64-baseos-rpms                     129 k
 cups-client                                   x86_64                  1:2.2.6-38.el8                                           rhel-8-for-x86_64-appstream-rpms                  169 k
 dwz                                           x86_64                  0.12-10.el8                                              rhel-8-for-x86_64-appstream-rpms                  109 k
 ed                                            x86_64                  1.14.2-4.el8                                             rhel-8-for-x86_64-baseos-rpms                      82 k
 efi-srpm-macros                               noarch                  3-3.el8                                                  rhel-8-for-x86_64-appstream-rpms                   22 k
 esmtp                                         x86_64                  1.2-15.el8                                               EPEL-8                                             57 k
 ghc-srpm-macros                               noarch                  1.4.2-7.el8                                              rhel-8-for-x86_64-appstream-rpms                  9.4 k
 go-srpm-macros                                noarch                  2-17.el8                                                 rhel-8-for-x86_64-appstream-rpms                   13 k
 keyutils-libs-devel                           x86_64                  1.5.10-6.el8                                             rhel-8-for-x86_64-baseos-rpms                      48 k
 krb5-devel                                    x86_64                  1.18.2-14.el8                                            rhel-8-for-x86_64-baseos-rpms                     560 k
 libcom_err-devel                              x86_64                  1.45.6-2.el8                                             rhel-8-for-x86_64-baseos-rpms                      38 k
 libesmtp                                      x86_64                  1.0.6-18.el8                                             EPEL-8                                             70 k
 libkadm5                                      x86_64                  1.18.2-14.el8                                            rhel-8-for-x86_64-baseos-rpms                     187 k
 liblockfile                                   x86_64                  1.14-1.el8                                               rhel-8-for-x86_64-appstream-rpms                   32 k
 libselinux-devel                              x86_64                  2.9-5.el8                                                rhel-8-for-x86_64-baseos-rpms                     200 k
 libsepol-devel                                x86_64                  2.9-3.el8                                                rhel-8-for-x86_64-baseos-rpms                      87 k
 libverto-devel                                x86_64                  0.3.0-5.el8                                              rhel-8-for-x86_64-baseos-rpms                      18 k
 m4                                            x86_64                  1.4.18-7.el8                                             rhel-8-for-x86_64-baseos-rpms                     223 k
 mailx                                         x86_64                  12.5-29.el8                                              rhel-8-for-x86_64-baseos-rpms                     257 k
 ncurses-compat-libs                           x86_64                  6.1-9.20180224.el8                                       rhel-8-for-x86_64-baseos-rpms                     328 k
 ocaml-srpm-macros                             noarch                  5-4.el8                                                  rhel-8-for-x86_64-appstream-rpms                  9.5 k
 openblas-srpm-macros                          noarch                  2-2.el8                                                  rhel-8-for-x86_64-appstream-rpms                  8.0 k
 pcre2-devel                                   x86_64                  10.32-2.el8                                              rhel-8-for-x86_64-baseos-rpms                     605 k
 pcre2-utf16                                   x86_64                  10.32-2.el8                                              rhel-8-for-x86_64-baseos-rpms                     229 k
 pcre2-utf32                                   x86_64                  10.32-2.el8                                              rhel-8-for-x86_64-baseos-rpms                     220 k
 perl-CPAN-Meta-YAML                           noarch                  0.018-397.el8                                            rhel-8-for-x86_64-appstream-rpms                   34 k
 perl-ExtUtils-Command                         noarch                  1:7.34-1.el8                                             rhel-8-for-x86_64-appstream-rpms                   19 k
 perl-ExtUtils-Install                         noarch                  2.14-4.el8                                               rhel-8-for-x86_64-appstream-rpms                   46 k
 perl-ExtUtils-Manifest                        noarch                  1.70-395.el8                                             rhel-8-for-x86_64-appstream-rpms                   37 k
 perl-ExtUtils-ParseXS                         noarch                  1:3.35-2.el8                                             rhel-8-for-x86_64-appstream-rpms                   83 k
 perl-JSON-PP                                  noarch                  1:2.97.001-3.el8                                         rhel-8-for-x86_64-appstream-rpms                   68 k
 perl-Math-BigInt                              noarch                  1:1.9998.11-7.el8                                        rhel-8-for-x86_64-baseos-rpms                     196 k
 perl-Math-Complex                             noarch                  1.59-421.el8                                             rhel-8-for-x86_64-baseos-rpms                     109 k
 perl-Test-Harness                             noarch                  1:3.42-1.el8                                             rhel-8-for-x86_64-appstream-rpms                  279 k
 perl-devel                                    x86_64                  4:5.26.3-419.el8_4.1                                     rhel-8-for-x86_64-appstream-rpms                  599 k
 perl-srpm-macros                              noarch                  1-25.el8                                                 rhel-8-for-x86_64-appstream-rpms                   11 k
 perl-version                                  x86_64                  6:0.99.24-1.el8                                          rhel-8-for-x86_64-appstream-rpms                   67 k
 platform-python-devel                         x86_64                  3.6.8-41.el8                                             rhel-8-for-x86_64-appstream-rpms                  249 k
 python-rpm-macros                             noarch                  3-41.el8                                                 rhel-8-for-x86_64-appstream-rpms                   15 k
 python-srpm-macros                            noarch                  3-41.el8                                                 rhel-8-for-x86_64-appstream-rpms                   15 k
 python3-pyparsing                             noarch                  2.1.10-7.el8                                             rhel-8-for-x86_64-baseos-rpms                     142 k
 python3-rpm-generators                        noarch                  5-7.el8                                                  rhel-8-for-x86_64-appstream-rpms                   25 k
 python3-rpm-macros                            noarch                  3-41.el8                                                 rhel-8-for-x86_64-appstream-rpms                   14 k
 qt5-srpm-macros                               noarch                  5.15.2-1.el8                                             rhel-8-for-x86_64-appstream-rpms                   11 k
 redhat-lsb-submod-security                    x86_64                  4.1-47.el8                                               rhel-8-for-x86_64-appstream-rpms                   22 k
 redhat-rpm-config                             noarch                  125-1.el8                                                rhel-8-for-x86_64-appstream-rpms                   87 k
 rust-srpm-macros                              noarch                  5-2.el8                                                  rhel-8-for-x86_64-appstream-rpms                  9.3 k
 spax                                          x86_64                  1.5.3-13.el8                                             rhel-8-for-x86_64-baseos-rpms                     217 k
 systemtap-sdt-devel                           x86_64                  4.6-4.el8                                                rhel-8-for-x86_64-appstream-rpms                   86 k
 time                                          x86_64                  1.9-3.el8                                                rhel-8-for-x86_64-baseos-rpms                      54 k
 unzip                                         x86_64                  6.0-46.el8                                               rhel-8-for-x86_64-baseos-rpms                     196 k
 util-linux-user                               x86_64                  2.32.1-28.el8                                            rhel-8-for-x86_64-baseos-rpms                     100 k
 zip                                           x86_64                  3.0-23.el8                                               rhel-8-for-x86_64-baseos-rpms                     270 k
 zlib-devel                                    x86_64                  1.2.11-17.el8                                            rhel-8-for-x86_64-baseos-rpms                      58 k
Installing weak dependencies:
 perl-CPAN-Meta                                noarch                  2.150010-396.el8                                         rhel-8-for-x86_64-appstream-rpms                  191 k
 perl-CPAN-Meta-Requirements                   noarch                  2.140-396.el8                                            rhel-8-for-x86_64-appstream-rpms                   37 k
 perl-Encode-Locale                            noarch                  1.05-10.module+el8.3.0+6498+9eecfe51                     rhel-8-for-x86_64-appstream-rpms                   22 k
 perl-Time-HiRes                               x86_64                  4:1.9758-2.el8                                           rhel-8-for-x86_64-appstream-rpms                   61 k

Transaction Summary
========================================================================================================================================================================================
Install  69 Packages
Upgrade  17 Packages

Total download size: 72 M
Is this ok [y/N]: y
Downloading Packages:
(1/86): perl-ExtUtils-Install-2.14-4.el8.noarch.rpm                                                                                                     735 kB/s |  46 kB     00:00
(2/86): libesmtp-1.0.6-18.el8.x86_64.rpm                                                                                                                1.0 MB/s |  70 kB     00:00
(3/86): esmtp-1.2-15.el8.x86_64.rpm                                                                                                                     747 kB/s |  57 kB     00:00
(4/86): rust-srpm-macros-5-2.el8.noarch.rpm                                                                                                             308 kB/s | 9.3 kB     00:00
(5/86): perl-ExtUtils-Manifest-1.70-395.el8.noarch.rpm                                                                                                  781 kB/s |  37 kB     00:00
(6/86): perl-CPAN-Meta-2.150010-396.el8.noarch.rpm                                                                                                      2.7 MB/s | 191 kB     00:00
(7/86): ocaml-srpm-macros-5-4.el8.noarch.rpm                                                                                                            214 kB/s | 9.5 kB     00:00
(8/86): perl-JSON-PP-2.97.001-3.el8.noarch.rpm                                                                                                          1.2 MB/s |  68 kB     00:00
(9/86): perl-ExtUtils-MakeMaker-7.34-1.el8.noarch.rpm                                                                                                   5.8 MB/s | 301 kB     00:00
(10/86): ghc-srpm-macros-1.4.2-7.el8.noarch.rpm                                                                                                         317 kB/s | 9.4 kB     00:00
(11/86): perl-Test-Harness-3.42-1.el8.noarch.rpm                                                                                                        4.5 MB/s | 279 kB     00:00
(12/86): perl-ExtUtils-Command-7.34-1.el8.noarch.rpm                                                                                                    520 kB/s |  19 kB     00:00

...
                                                                                                         15 MB/s | 1.5 MB     00:00
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                    35 MB/s |  72 MB     00:02
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                1/1
  Running scriptlet: openssl-libs-1:1.1.1k-7.el8_6.x86_64                                                                                                                           1/1
  Upgrading        : openssl-libs-1:1.1.1k-7.el8_6.x86_64                                                                                                                         1/103
  Running scriptlet: openssl-libs-1:1.1.1k-7.el8_6.x86_64                                                                                                                         1/103
  Upgrading        : libgcc-8.5.0-10.1.el8_6.x86_64                                                                                                                               2/103
  Running scriptlet: libgcc-8.5.0-10.1.el8_6.x86_64                                                                                                                               2/103
  Upgrading        : elfutils-libelf-0.186-1.el8.x86_64                                                                                                                           3/103
  Installing       : perl-version-6:0.99.24-1.el8.x86_64                                                                                                                          4/103
  Installing       : perl-CPAN-Meta-Requirements-2.140-396.el8.noarch                                                                                                             5/103
  Upgrading        : libsemanage-2.9-8.el8.x86_64                                                                                                                                 6/103
  Installing       : zlib-devel-1.2.11-17.el8.x86_64                                                                                                                              7/103
  Installing       : python-srpm-macros-3-41.el8.noarch                                                                                                                           8/103
  Installing       : python-rpm-macros-3-41.el8.noarch                                                                                                                            9/103
  Installing       : python3-rpm-macros-3-41.el8.noarch                                                                                                                          10/103
  Installing       : perl-Time-HiRes-4:1.9758-2.el8.x86_64                                                                                                                       11/103
  Installing       : perl-ExtUtils-ParseXS-1:3.35-2.el8.noarch                                                                                                                   12/103
  Installing       : perl-Test-Harness-1:3.42-1.el8.noarch                                                                                                                       13/103
  Upgrading        : python3-libsemanage-2.9-8.el8.x86_64                                                                                                                        14/103
  Upgrading        : policycoreutils-2.9-19.el8.x86_64                                                                                                                           15/103
  Running scriptlet: policycoreutils-2.9-19.el8.x86_64                                                                                                                           15/103
  Upgrading        : python3-policycoreutils-2.9-19.el8.noarch                                                                                                                   16/103
  Installing       : dwz-0.12-10.el8.x86_64                                                                                                                                      17/103
  Installing       : ncurses-compat-libs-6.1-9.20180224.el8.x86_64                                                                                                               18/103
  Installing       : libesmtp-1.0.6-18.el8.x86_64                                                                                                                                19/103
  Installing       : mailx-12.5-29.el8.x86_64                                                                                                                                    20/103
  Installing       : libkadm5-1.18.2-14.el8.x86_64                                                                                                                               21/103
  Upgrading        : libgomp-8.5.0-10.1.el8_6.x86_64                                                                                                                             22/103
  Running scriptlet: libgomp-8.5.0-10.1.el8_6.x86_64                                                                                                                             22/103
  Upgrading        : platform-python-pip-9.0.3-22.el8.noarch                                                                                                                     23/103
  Upgrading        : python3-pip-9.0.3-22.el8.noarch                                                                                                                             24/103
  Upgrading        : python36-3.6.8-38.module+el8.5.0+12207+5c5719bc.x86_64                                                                                                      25/103
  Running scriptlet: python36-3.6.8-38.module+el8.5.0+12207+5c5719bc.x86_64                                                                                                      25/103
  Upgrading        : cpp-8.5.0-10.1.el8_6.x86_64                                                                                                                                 26/103
  Running scriptlet: cpp-8.5.0-10.1.el8_6.x86_64                                                                                                                                 26/103
  Upgrading        : gcc-8.5.0-10.1.el8_6.x86_64                                                                                                                                 27/103
  Running scriptlet: gcc-8.5.0-10.1.el8_6.x86_64                                                                                                                                 27/103
  Installing       : annobin-10.29-3.el8.x86_64                                                                                                                                  28/103
  Installing       : unzip-6.0-46.el8.x86_64                                                                                                                                     29/103
  Installing       : zip-3.0-23.el8.x86_64                                                                                                                                       30/103
  Installing       : perl-Math-Complex-1.59-421.el8.noarch                                                                                                                       31/103
  Installing       : perl-Math-BigInt-1:1.9998.11-7.el8.noarch                                                                                                                   32/103
  Installing       : perl-JSON-PP-1:2.97.001-3.el8.noarch                                                                                                                        33/103
  Installing       : make-1:4.2.1-11.el8.x86_64                                                                                                                                  34/103
  Running scriptlet: make-1:4.2.1-11.el8.x86_64                                                                                                                                  34/103
  Installing       : libcom_err-devel-1.45.6-2.el8.x86_64                                                                                                                        35/103
  Installing       : util-linux-user-2.32.1-28.el8.x86_64                                                                                                                        36/103
  Installing       : libsepol-devel-2.9-3.el8.x86_64                                                                                                                             37/103
  Installing       : pcre2-utf32-10.32-2.el8.x86_64                                                                                                                              38/103
  Installing       : pcre2-utf16-10.32-2.el8.x86_64                                                                                                                              39/103
  Installing       : pcre2-devel-10.32-2.el8.x86_64                                                                                                                              40/103
  Installing       : libselinux-devel-2.9-5.el8.x86_64                                                                                                                           41/103
  Installing       : patch-2.7.6-11.el8.x86_64                                                                                                                                   42/103
  Installing       : python3-pyparsing-2.1.10-7.el8.noarch                                                                                                                       43/103
  Installing       : systemtap-sdt-devel-4.6-4.el8.x86_64                                                                                                                        44/103
  Installing       : spax-1.5.3-13.el8.x86_64                                                                                                                                    45/103
  Running scriptlet: spax-1.5.3-13.el8.x86_64                                                                                                                                    45/103
  Installing       : m4-1.4.18-7.el8.x86_64                                                                                                                                      46/103
  Running scriptlet: m4-1.4.18-7.el8.x86_64                                                                                                                                      46/103
  Installing       : libverto-devel-0.3.0-5.el8.x86_64                                                                                                                           47/103
  Installing       : bc-1.07.1-5.el8.x86_64                                                                                                                                      48/103
  Running scriptlet: bc-1.07.1-5.el8.x86_64                                                                                                                                      48/103
  Installing       : at-3.1.20-11.el8.x86_64                                                                                                                                     49/103
  Running scriptlet: at-3.1.20-11.el8.x86_64                                                                                                                                     49/103
  Installing       : keyutils-libs-devel-1.5.10-6.el8.x86_64                                                                                                                     50/103
  Installing       : krb5-devel-1.18.2-14.el8.x86_64                                                                                                                             51/103
  Installing       : time-1.9-3.el8.x86_64                                                                                                                                       52/103
  Running scriptlet: time-1.9-3.el8.x86_64                                                                                                                                       52/103

  Upgrading        : policycoreutils-python-utils-2.9-19.el8.noarch                                                                                                              80/103
  Installing       : elfutils-libelf-devel-0.186-1.el8.x86_64                                                                                                                    81/103
  Upgrading        : elfutils-libs-0.186-1.el8.x86_64                                                                                                                            82/103
  Upgrading        : mokutil-1:0.3.0-11.el8_6.1.x86_64                                                                                                                           83/103
  Upgrading        : openssl-1:1.1.1k-7.el8_6.x86_64                                                                                                                             84/103
  Installing       : kernel-devel-4.18.0-348.el8.x86_64                                                                                                                          85/103
  Running scriptlet: kernel-devel-4.18.0-348.el8.x86_64

  ...
                                                                                                                       85/103
  Installing       : bzip2-1.0.6-26.el8.x86_64                                                                                                                                   86/103
  Cleanup          : policycoreutils-python-utils-2.9-14.el8.noarch                                                                                                              87/103
  Cleanup          : python3-policycoreutils-2.9-14.el8.noarch                                                                                                                   88/103
  Cleanup          : python36-3.6.8-2.module+el8.1.0+3334+5cb623d7.x86_64                                                                                                        89/103
  Running scriptlet: python36-3.6.8-2.module+el8.1.0+3334+5cb623d7.x86_64                                                                                                        89/103
  Cleanup          : elfutils-libs-0.185-1.el8.x86_64                                                                                                                            90/103
  Cleanup          : openssl-1:1.1.1k-4.el8.x86_64                                                                                                                               91/103
  Cleanup          : python3-libsemanage-2.9-6.el8.x86_64                                                                                                                        92/103
  Running scriptlet: gcc-8.4.1-1.el8.x86_64                                                                                                                                      93/103
  Cleanup          : gcc-8.4.1-1.el8.x86_64                                                                                                                                      93/103
  Running scriptlet: policycoreutils-2.9-14.el8.x86_64                                                                                                                           94/103
  Cleanup          : policycoreutils-2.9-14.el8.x86_64                                                                                                                           94/103
  Cleanup          : mokutil-1:0.3.0-11.el8.x86_64                                                                                                                               95/103
  Cleanup          : python3-pip-9.0.3-19.el8.noarch                                                                                                                             96/103
  Cleanup          : platform-python-pip-9.0.3-19.el8.noarch                                                                                                                     97/103
  Cleanup          : openssl-libs-1:1.1.1k-4.el8.x86_64                                                                                                                          98/103
  Running scriptlet: openssl-libs-1:1.1.1k-4.el8.x86_64                                                                                                                          98/103
  Cleanup          : libsemanage-2.9-6.el8.x86_64                                                                                                                                99/103
  Running scriptlet: cpp-8.4.1-1.el8.x86_64                                                                                                                                     100/103
  Cleanup          : cpp-8.4.1-1.el8.x86_64                                                                                                                                     100/103
  Cleanup          : libgcc-8.5.0-3.el8.x86_64                                                                                                                                  101/103
  Running scriptlet: libgcc-8.5.0-3.el8.x86_64                                                                                                                                  101/103
  Running scriptlet: libgomp-8.4.1-1.el8.x86_64                                                                                                                                 102/103
  Cleanup          : libgomp-8.4.1-1.el8.x86_64                                                                                                                                 102/103
  Running scriptlet: libgomp-8.4.1-1.el8.x86_64                                                                                                                                 102/103
  Cleanup          : elfutils-libelf-0.185-1.el8.x86_64                                                                                                                         103/103
  Running scriptlet: elfutils-libelf-0.185-1.el8.x86_64                                                                                                                         103/103
  Verifying        : esmtp-1.2-15.el8.x86_64                                                                                                                                      1/103
  Verifying        : libesmtp-1.0.6-18.el8.x86_64

  ...

Upgraded:
  cpp-8.5.0-10.1.el8_6.x86_64                              elfutils-libelf-0.186-1.el8.x86_64     elfutils-libs-0.186-1.el8.x86_64          gcc-8.5.0-10.1.el8_6.x86_64
  libgcc-8.5.0-10.1.el8_6.x86_64                           libgomp-8.5.0-10.1.el8_6.x86_64        libsemanage-2.9-8.el8.x86_64              mokutil-1:0.3.0-11.el8_6.1.x86_64
  openssl-1:1.1.1k-7.el8_6.x86_64                          openssl-libs-1:1.1.1k-7.el8_6.x86_64   platform-python-pip-9.0.3-22.el8.noarch   policycoreutils-2.9-19.el8.x86_64
  policycoreutils-python-utils-2.9-19.el8.noarch           python3-libsemanage-2.9-8.el8.x86_64   python3-pip-9.0.3-22.el8.noarch           python3-policycoreutils-2.9-19.el8.noarch
  python36-3.6.8-38.module+el8.5.0+12207+5c5719bc.x86_64
Installed:
  annobin-10.29-3.el8.x86_64                                        at-3.1.20-11.el8.x86_64                             bc-1.07.1-5.el8.x86_64
  bzip2-1.0.6-26.el8.x86_64                                         cups-client-1:2.2.6-38.el8.x86_64                   dwz-0.12-10.el8.x86_64
  ed-1.14.2-4.el8.x86_64                                            efi-srpm-macros-3-3.el8.noarch                      elfutils-libelf-devel-0.186-1.el8.x86_64
  esmtp-1.2-15.el8.x86_64                                           ghc-srpm-macros-1.4.2-7.el8.noarch                  go-srpm-macros-2-17.el8.noarch
  kernel-devel-4.18.0-348.el8.x86_64                                keyutils-libs-devel-1.5.10-6.el8.x86_64             krb5-devel-1.18.2-14.el8.x86_64
  libcom_err-devel-1.45.6-2.el8.x86_64                              libesmtp-1.0.6-18.el8.x86_64                        libkadm5-1.18.2-14.el8.x86_64
  liblockfile-1.14-1.el8.x86_64                                     libselinux-devel-2.9-5.el8.x86_64                   libsepol-devel-2.9-3.el8.x86_64
  libverto-devel-0.3.0-5.el8.x86_64                                 m4-1.4.18-7.el8.x86_64                              mailx-12.5-29.el8.x86_64
  make-1:4.2.1-11.el8.x86_64                                        ncurses-compat-libs-6.1-9.20180224.el8.x86_64       ocaml-srpm-macros-5-4.el8.noarch
  openblas-srpm-macros-2-2.el8.noarch                               openssl-devel-1:1.1.1k-7.el8_6.x86_64               patch-2.7.6-11.el8.x86_64
  pcre2-devel-10.32-2.el8.x86_64                                    pcre2-utf16-10.32-2.el8.x86_64                      pcre2-utf32-10.32-2.el8.x86_64
  perl-CPAN-Meta-2.150010-396.el8.noarch                            perl-CPAN-Meta-Requirements-2.140-396.el8.noarch    perl-CPAN-Meta-YAML-0.018-397.el8.noarch
  perl-Encode-Locale-1.05-10.module+el8.3.0+6498+9eecfe51.noarch    perl-ExtUtils-Command-1:7.34-1.el8.noarch           perl-ExtUtils-Install-2.14-4.el8.noarch
  perl-ExtUtils-MakeMaker-1:7.34-1.el8.noarch                       perl-ExtUtils-Manifest-1.70-395.el8.noarch          perl-ExtUtils-ParseXS-1:3.35-2.el8.noarch
  perl-JSON-PP-1:2.97.001-3.el8.noarch                              perl-Math-BigInt-1:1.9998.11-7.el8.noarch           perl-Math-Complex-1.59-421.el8.noarch
  perl-Test-Harness-1:3.42-1.el8.noarch                             perl-Time-HiRes-4:1.9758-2.el8.x86_64               perl-devel-4:5.26.3-419.el8_4.1.x86_64
  perl-srpm-macros-1-25.el8.noarch                                  perl-version-6:0.99.24-1.el8.x86_64                 platform-python-devel-3.6.8-41.el8.x86_64
  python-rpm-macros-3-41.el8.noarch                                 python-srpm-macros-3-41.el8.noarch                  python3-pyparsing-2.1.10-7.el8.noarch
  python3-rpm-generators-5-7.el8.noarch                             python3-rpm-macros-3-41.el8.noarch                  python36-devel-3.6.8-38.module+el8.5.0+12207+5c5719bc.x86_64
  qt5-srpm-macros-5.15.2-1.el8.noarch                               redhat-lsb-core-4.1-47.el8.x86_64                   redhat-lsb-submod-security-4.1-47.el8.x86_64
  redhat-rpm-config-125-1.el8.noarch                                rust-srpm-macros-5-2.el8.noarch                     spax-1.5.3-13.el8.x86_64
  systemtap-sdt-devel-4.6-4.el8.x86_64                              time-1.9-3.el8.x86_64                               unzip-6.0-46.el8.x86_64
  util-linux-user-2.32.1-28.el8.x86_64                              zip-3.0-23.el8.x86_64                               zlib-devel-1.2.11-17.el8.x86_64

Complete!
OS package installations finished
+ Installing ONTAP Mediator. (Log: /tmp/ontap_mediator.JixKGP/ontap-mediator-1.5.0/ontap-mediator-1.5.0/install_20221021155929.log)
    This step will take several minutes. Use the log file to view progress.
    Sudoer config verified
    ONTAP Mediator rsyslog and logging rotation enabled
+ Install successful. (Moving log to /opt/netapp/lib/ontap_mediator/log/install_20221021155929.log)
+ WARNING: This system supports UEFI
           Secure Boot (SB) is currently disabled on this system.
           If SB is enabled in the future, SCST will not work unless the following action is taken:
           Using the keys in /opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys follow
           instructions in /opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/README.module-signing
           to sign the SCST kernel module. Note that reboot will be needed.
     SCST will not start automatically when Secure Boot is enabled and not configured properly.
+ Note: ONTAP Mediator uses a kernel module compiled specifically for the current
        OS. Using 'yum update' to upgrade the kernel might cause service interruption.
    For more information, see /opt/netapp/lib/ontap_mediator/README
[root@scs000099753 ~]# cat /etc/redhat-release
Red Hat Enterprise Linux release 8.5 (Ootpa)
[root@scs000099753 ~]#

----
====


== 验证安装。

.步骤
. 运行以下命令以查看ONTAP 调解器服务的状态：
+
.. run：`systemctl status ontap_mediator`
+
[listing]
----
[root@scspr1915530002 ~]# systemctl status ontap_mediator

 ontap_mediator.service - ONTAP Mediator
Loaded: loaded (/etc/systemd/system/ontap_mediator.service; enabled; vendor preset: disabled)
Active: active (running) since Mon 2022-04-18 10:41:49 EDT; 1 weeks 0 days ago
Process: 286710 ExecStop=/bin/kill -s INT $MAINPID (code=exited, status=0/SUCCESS)
Main PID: 286712 (uwsgi)
Status: "uWSGI is ready"
Tasks: 3 (limit: 49473)
Memory: 139.2M
CGroup: /system.slice/ontap_mediator.service
      ├─286712 /opt/netapp/lib/ontap_mediator/pyenv/bin/uwsgi --ini /opt/netapp/lib/ontap_mediator/uwsgi/ontap_mediator.ini
      ├─286716 /opt/netapp/lib/ontap_mediator/pyenv/bin/uwsgi --ini /opt/netapp/lib/ontap_mediator/uwsgi/ontap_mediator.ini
      └─286717 /opt/netapp/lib/ontap_mediator/pyenv/bin/uwsgi --ini /opt/netapp/lib/ontap_mediator/uwsgi/ontap_mediator.ini

[root@scspr1915530002 ~]#
----
.. run：`systemctl status medier-scst`
+
[listing]
----
[root@scspr1915530002 ~]# systemctl status mediator-scst
   Loaded: loaded (/etc/systemd/system/mediator-scst.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2022-04-18 10:41:47 EDT; 1 weeks 0 days ago
  Process: 286595 ExecStart=/etc/init.d/scst start (code=exited, status=0/SUCCESS)
 Main PID: 286662 (iscsi-scstd)
    Tasks: 1 (limit: 49473)
   Memory: 1.2M
   CGroup: /system.slice/mediator-scst.service
           └─286662 /usr/local/sbin/iscsi-scstd

[root@scspr1915530002 ~]#
----


. 确认ONTAP 调解器服务正在使用的端口：`netstat`
+
[listing]
----
[root@scspr1905507001 ~]# netstat -anlt | grep -E '3260|31784'

         tcp   0   0 0.0.0.0:31784   0.0.0.0:*      LISTEN

         tcp   0   0 0.0.0.0:3260    0.0.0.0:*      LISTEN

         tcp6  0   0 :::3260         :::*           LISTEN
----




== 结果

此时， ONTAP 调解器服务已安装并正在运行。要使用调解器功能，必须在 ONTAP 存储系统中执行进一步配置：

* 要在 MetroCluster IP 配置中使用 ONTAP 调解器服务，请参见 link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html["从 MetroCluster IP 配置配置 ONTAP 调解器服务"^]
* 要使用 SnapMirror 业务连续性，请参见 link:https://docs.netapp.com/us-en/ontap/smbc/smbc_install_confirm_ontap_cluster.html["安装 ONTAP 调解器服务并确认 ONTAP 集群配置"^]

