---
permalink: mediator/mediator-overview-concept.html 
sidebar: sidebar 
keywords: ontap mediator, install requirements, mediator requirements 
summary: ONTAP 调解器为ONTAP 功能提供了多种功能。 
---
= 了解ONTAP调解器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
本文档指的是ONTAP Mediator 的本地版本。有关ONTAP Cloud Mediator（从ONTAP 9.17.1 开始提供）的信息，请参阅link:../snapmirror-active-sync/index.html["SnapMirror主动同步文档"] 。

ONTAP 调解器为 ONTAP 功能提供了多种功能：

* 为HA元数据提供永久性隔离存储。
* 用作控制器可用性的ping代理。
* 提供同步节点运行状况查询功能、以帮助确定仲裁。


ONTAP 调解器提供两项额外的 systemctl 服务：

* *`ontap_mediator.service`*
+
维护用于管理 ONTAP 关系的 REST API 服务器。

* *`mediator-scst.service`*
+
控制iSCSI模块(SCST)的启动和关闭。





[[tools-provided-for-the-system-administrator]]
== 为系统管理员提供的工具

为系统管理员提供的工具：

* *`/usr/local/bin/mediator_change_password`*
+
提供当前API用户名和密码后、设置新的API密码。

* *`/usr/local/bin/mediator_change_user`*
+
提供当前API用户名和密码后、设置新的API用户名。

* *`/usr/local/bin/mediator_generate_support_bundle`*
+
生成一个本地tgz文件、其中包含与NetApp客户支持进行通信所需的所有有用支持信息。  其中包括应用程序配置、日志和一些系统信息。  捆绑包会在本地磁盘上生成、可以根据需要手动传输。  存储位置：/opt/NetApp/data/support_Bund具/

* *`/usr/local/bin/uninstall_ontap_mediator`*
+
删除ONTAP 调解器软件包和SCST内核模块。这包括所有配置、日志和邮箱数据。

* *`/usr/local/bin/mediator_unlock_user`*
+
如果达到身份验证重试限制、则解除对API用户帐户的锁定。此功能用于防止暴力密码派生。它会提示用户输入正确的用户名和密码。

* *`/usr/local/bin/mediator_add_user`*
+
(仅支持)用于在安装时添加API用户。





[[scst-and-kernel-updates]]
== SCST 和内核更新

ONTAP Mediator 使用 SCST 为 MetroCluster IP 配置中的通信提供 iSCSI。SCST 包是在安装过程中编译的内核模块。更新内核后，可能需要重新安装 SCST。或者，卸载 ONTAP Mediator，然后重新安装并重新配置 ONTAP 关系。请参阅 link:https://scst.sourceforge.net/["SCST：适用于 Linux 的通用 SCSI 目标子系统"^] 以了解有关 SCST 的更多信息。


NOTE: 您应该在 ONTAP 维护窗口中协调对服务器操作系统内核的任何更新。



[[support-for-https-and-iscsi]]
== 支持 HTTPS 和 iSCSI

从 ONTAP Mediator 1.12 开始，您可以配置使用 HTTPS 或 iSCSI 监控 MetroCluster IP 配置的 ONTAP Mediator。您可以选择安装支持 iSCSI 和 HTTPS 或仅支持 HTTPS 的 ONTAP Mediator。如果安装 ONTAP Mediator 时仅支持 HTTPS，则未安装 SCST 包。有关详细信息，请参见 link:index.html#https-iscsi-installation["适用于 ONTAP Mediator 的 HTTPS 和 iSCSI 安装选项"]。
