---
permalink: mediator/upgrade-host-os-mediator-task.html 
sidebar: sidebar 
keywords: mediator, new, release, update, install, 
summary: 在安装过程中、您需要先升级主机操作系统、然后再升级ONTAP 调解器。 
---
= 升级主机操作系统和ONTAP调解器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
要将适用于ONTAP 调解器的主机操作系统升级到更高版本、必须先卸载ONTAP 调解器。

.关于此任务
使用leapp-upgrade工具将适用于ONTAP 的主机操作系统调解器升级到更高的主要版本(例如、从7.x升级到8.x)时、 您必须卸载ONTAP 调解器、因为该工具会尝试检测已向系统注册的存储库中安装的任何RPM的新版本。

由于.rpm文件是作为ONTAP 调解器安装程序的一部分安装的、因此会包含在该搜索中。但是、由于.rpm文件是作为安装程序的一部分解压缩的、并且未从注册的存储库下载、因此无法找到升级。在这种情况下、leapp-upgrade工具将卸载该软件包。

为了保留用于分类支持案例的日志文件，您应该在升级操作系统之前备份这些文件，并在重新安装 ONTAP Mediator 软件包后恢复它们。安装 ONTAPMediator 后，需要重新连接连接到该软件包的 ONTAP 集群。


NOTE: 应按顺序执行以下步骤。重新安装 ONTAP Mediator 后，应立即停止 ontap_mediator，替换日志文件，然后重新启动它。这样做是为了确保日志不会丢失。

.步骤
. 备份日志文件。
+
....
[rootmediator-host ~]# tar -czf ontap_mediator_file_backup.tgz -C /opt/netapp/lib/ontap_mediator ./log ./ontap_mediator/server_config/ontap_mediator.user_config.yaml
[rootmediator-host ~]# tar -tf ontap_mediator_file_backup.tgz
./log/
./log/ontap_mediator.log
./log/scstadmin.log
./log/ontap_mediator_stdout.log
./log/ontap_mediator_requests.log
./log/install_20230419134611.log
./log/scst.log
./log/ontap_mediator_syslog.log
./ontap_mediator/server_config/ontap_mediator.user_config.yaml
[rootmediator-host ~]#
....
. 使用leapp-upgrade工具执行升级。
+
....
[rootmediator-host ~]# leapp preupgrade --target 8.4
  ..<snip upgrade checks>..
  ..<fix issues found>..
[rootmediator-host ~]# leapp upgrade --target 8.4
  ..<snip upgrade>..
[rootmediator-host ~]# cat /etc/os-release | head -2
NAME="Red Hat Enterprise Linux"
VERSION="8.4 (Ootpa)"
[rootmediator-host ~]#
....
. 重新安装ONTAP 调解器。
+

NOTE: 重新安装ONTAP 调解器后立即执行其余步骤、以防止日志文件丢失。

+
....
[rootmediator-host ~]# ontap-mediator-1.10/ontap-mediator-1.10

ONTAP Mediator: Self Extracting Installer

  ..<snip installation>..
[rootmediator-host ~]#
....
. 停止 ontap_mediator。
+
....
[rootmediator-host ~]# systemctl stop ontap_mediator
[rootmediator-host ~]#
....
. 替换日志文件。
+
....
[rootmediator-host ~]# tar -xf ontap_mediator_log_backup.tgz -C /opt/netapp/lib/ontap_mediator
[rootmediator-host ~]#
....
. 启动 ontap_mediator。
+
....
[rootmediator-host ~]# systemctl start ontap_mediator
[rootmediator-host ~]#
....
. 将所有ONTAP 集群重新连接到升级后的ONTAP 调解器
+
.适用于基于IP的MetroCluster 的操作步骤
[%collapsible]
====
....
siteA::> metrocluster configuration-settings mediator show
Mediator IP     Port    Node                    Configuration Connection
                                                Status        Status
--------------- ------- ----------------------- ------------- -----------
172.31.40.122
                31784   siteA-node2             true          false
                        siteA-node1             true          false
                        siteB-node2             true          false
                        siteB-node2             true          false
siteA::> metrocluster configuration-settings mediator remove
Removing the mediator and disabling Automatic Unplanned Switchover. It may take a few minutes to complete.
Please enter the username for the mediator: mediatoradmin
Please enter the password for the mediator:
Confirm the mediator password:
Automatic Unplanned Switchover is disabled for all nodes...
Removing mediator mailboxes...
Successfully removed the mediator.

siteA::> metrocluster configuration-settings mediator add -mediator-address 172.31.40.122
Adding the mediator and enabling Automatic Unplanned Switchover. It may take a few minutes to complete.
Please enter the username for the mediator: mediatoradmin
Please enter the password for the mediator:
Confirm the mediator password:
Successfully added the mediator.

siteA::> metrocluster configuration-settings mediator show
Mediator IP     Port    Node                    Configuration Connection
                                                Status        Status
--------------- ------- ----------------------- ------------- -----------
172.31.40.122
                31784   siteA-node2             true          true
                        siteA-node1             true          true
                        siteB-node2             true          true
                        siteB-node2             true          true
siteA::>
....
====
+
.用于SnapMirror活动同步的操作步骤
[%collapsible]
====
对于SnapMirror主动同步、如果您在/opt/NetApp目录之外安装了TLS证书、则不需要重新安装它。如果您使用的是默认生成的自签名证书、或者将自定义证书放在/opt/NetApp目录中、则应将其备份并还原。

....
peer1::> snapmirror mediator show
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
172.31.49.237    peer2            unreachable       true

peer1::> snapmirror mediator remove -mediator-address 172.31.49.237 -peer-cluster peer2

Info: [Job 39] 'mediator remove' job queued

peer1::> job show -id 39
                            Owning
Job ID Name                 Vserver    Node           State
------ -------------------- ---------- -------------- ----------
39     mediator remove      peer1      peer1-node1    Success
     Description: Removing entry in mediator

peer1::> security certificate show -common-name ONTAPMediatorCA
Vserver    Serial Number   Certificate Name                       Type
---------- --------------- -------------------------------------- ------------
peer1
        4A790360081F41145E14C5D7CE721DC6C210007F
                        ONTAPMediatorCA                        server-ca
    Certificate Authority: ONTAP Mediator CA
        Expiration Date: Mon Apr 17 10:27:54 2073

peer1::> security certificate delete -common-name ONTAPMediatorCA *
1 entry was deleted.

 peer1::> security certificate install -type server-ca -vserver peer1

Please enter Certificate: Press <Enter> when done
  ..<snip ONTAP Mediator CA public key>..

You should keep a copy of the CA-signed digital certificate for future reference.

The installed certificate's CA and serial number for reference:
CA: ONTAP Mediator CA
serial: 44786524464C5113D5EC966779D3002135EA4254

The certificate's generated name for reference: ONTAPMediatorCA

peer2::> security certificate delete -common-name ONTAPMediatorCA *
1 entry was deleted.

peer2::> security certificate install -type server-ca -vserver peer2

 Please enter Certificate: Press <Enter> when done
..<snip ONTAP Mediator CA public key>..


You should keep a copy of the CA-signed digital certificate for future reference.

The installed certificate's CA and serial number for reference:
CA: ONTAP Mediator CA
serial: 44786524464C5113D5EC966779D3002135EA4254

The certificate's generated name for reference: ONTAPMediatorCA

peer1::> snapmirror mediator add -mediator-address 172.31.49.237 -peer-cluster peer2 -username mediatoradmin

Notice: Enter the mediator password.

Enter the password:
Enter the password again:

Info: [Job: 43] 'mediator add' job queued

peer1::> job show -id 43
                            Owning
Job ID Name                 Vserver    Node           State
------ -------------------- ---------- -------------- ----------
43     mediator add         peer1      peer1-node2    Success
    Description: Creating a mediator entry

peer1::> snapmirror mediator show
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
172.31.49.237    peer2            connected         true

peer1::>

....
====


.相关信息
* link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-delete.html["安全证书删除"^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-install.html["安全证书安装"^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-show.html["security certificate show"^]

