---
sidebar: sidebar 
permalink: data-protection/cloud-backup-using-cbs-task.html 
keywords: cloud, data, backup, back up, storage, volume, lun, connector, secret key, access key, bluexp back and recovery service, Cloud Backup service, CBS, restore data, protect volumes, ipspace, storagegrid, storage grid, archive, archival, archiving, cost, calculator, glacier, deep archive 
summary: 从 ONTAP 9.19.1 开始，System Manager 不再支持使用 NetApp Backup and Recovery 服务在云中备份数据。相反，您必须使用 NetApp Console 配置 NetApp Backup and Recovery 服务，并创建到云目标的 SnapMirror 关系。 
---
= 使用NetApp Backup and Recovery 备份数据
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
从 ONTAP 9.19.1 开始，System Manager 不再支持使用 NetApp Backup and Recovery 服务在云中备份数据。相反，您必须使用 NetApp Console 配置 NetApp Backup and Recovery 服务，并创建到云目标的 SnapMirror 关系。

备份和恢复支持FlexVol读写卷和数据保护 (DP) 卷。从ONTAP 9.12.1 开始，备份和恢复支持FlexGroup卷和SnapLock卷。

详细了解link:https://docs.netapp.com/us-en/data-services-backup-recovery/index.html["NetApp备份和恢复"^] 。

.开始之前
您应执行以下过程以在 NetApp Console 中建立帐户。对于服务帐户，需要将角色创建为"Account Admin"。

. link:https://docs.netapp.com/us-en/console-setup-admin/task-logging-in.html["在NetApp控制台中创建帐户"^] 。
. link:https://docs.netapp.com/us-en/console-setup-admin/concept-connectors.html["在NetApp控制台中创建控制台代理"^]与以下云提供商之一合作：
+
** Microsoft Azure
** Amazon Web Services （ AWS ）
** Google Cloud Platform （ GCP ）
** StorageGRID (ONTAP 9.10.1)
+

NOTE: 从ONTAP 9.10.1 开始，您可以选择StorageGRID作为云备份提供商，但前提是NetApp Console 部署在本地。控制台代理必须安装在本地，并可通过NetApp控制台软件即服务 (SaaS) 应用程序使用。



. link:https://docs.netapp.com/us-en/data-services-backup-recovery/concept-backup-to-cloud.html["在NetApp控制台中订阅NetApp备份和恢复"^]（需要适当的许可证）。
. link:https://docs.netapp.com/us-en/console-setup-admin/concept-identity-and-access-management.html["使用NetApp控制台生成访问密钥和密钥"^] 。




== 使用 NetApp Console 和 NetApp Backup and Recovery 来管理 ONTAP 备份

从 ONTAP 9.19.1 开始，System Manager 不再支持 NetApp Backup and Recovery。有关将 NetApp Backup and Recovery 与 NetApp Console 配合使用的更多信息，请参见 link:https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-backup-manage.html["使用 NetApp Backup and Recovery 管理 ONTAP 系统的备份"^]。



== 从备份文件还原数据

只有在使用NetApp控制台时，您才可以执行备份管理操作，例如还原数据、更新关系和删除关系。请参阅link:https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-backup-manage.html["从备份文件还原数据"^]了解更多信息。
