---
permalink: data-protection/convert-volume-svm-replication-task.html 
sidebar: sidebar 
keywords: convert, volume, replication, relationships, svm 
summary: 您可以将卷之间的复制关系转换为卷所属的 Storage Virtual Machine （ SVM ）之间的复制关系，但前提是要复制源上的每个卷（根卷除外）。 并且源上的每个卷（包括根卷）与目标上的卷具有相同的名称。 
---
= 将ONTAP SnapMirror卷灾难恢复关系转换为SVM灾难恢复关系
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以将卷之间的复制关系转换为卷所属的 Storage Virtual Machine （ SVM ）之间的复制关系，但前提是要复制源上的每个卷（根卷除外）。 并且源上的每个卷（包括根卷）与目标上的卷具有相同的名称。

.关于此任务
如果需要、请在SnapMirror关系空闲时使用 `volume rename`命令重命名目标卷。有关的详细信息 `volume rename`，请参见link:https://docs.netapp.com/us-en/ontap-cli/volume-rename.html["ONTAP 命令参考"^]。

.步骤
. 从目标 SVM 或目标集群运行以下命令，以重新同步源卷和目标卷：
+
`snapmirror resync -source-path <SVM:volume> -destination-path <SVM:volume> -type DP|XDP -policy <policy>`

+
有关的详细信息 `snapmirror resync`，请参见link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-resync.html["ONTAP 命令参考"^]。

+
[NOTE]
====
虽然重新同步不需要基线传输，但它可能非常耗时。您可能希望在非高峰时段运行重新同步。

====
+
以下示例将重新同步源卷之间的关系 `volA` 开启 `svm1` 和目标卷 `volA` 开启 `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror resync -source-path svm1:volA -destination-path svm_backup:volA
----
. 在源和目标 SVM 之间创建 SVM 复制关系，如中所述 link:replicate-entire-svm-config-task.html["复制 SVM 配置"]。
+
您必须使用 `-identity-preserve true` 的选项 `snapmirror create` 命令。

. 停止目标 SVM ：
+
`vserver stop -vserver _SVM_`

+
有关的详细信息 `vserver stop`，请参见link:https://docs.netapp.com/us-en/ontap-cli/vserver-stop.html["ONTAP 命令参考"^]。

+
以下示例将停止目标SVM `svm_backup`：

+
[listing]
----
cluster_dst::> vserver stop svm_backup
----
. 从目标 SVM 或目标集群运行以下命令，以重新同步源和目标 SVM ：
+
`snapmirror resync -source-path <SVM>: -destination-path <SVM>: -type DP|XDP -policy <policy>`

+
有关的详细信息 `snapmirror resync`，请参见link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-resync.html["ONTAP 命令参考"^]。

+
[NOTE]
====
您必须在中的SVM名称后面输入冒号(：) `-source-path` 和 `-destination-path` 选项请参见以下示例。

虽然重新同步不需要基线传输，但它可能非常耗时。您可能希望在非高峰时段运行重新同步。

====
+
以下示例将重新同步源SVM之间的关系 `svm1` 和目标SVM `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror resync -source-path svm1: -destination-path svm_backup:
----


.相关信息
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["SnapMirror 创建"^]

