---
permalink: data-protection/convert-snapmirror-version-flexible-task.html 
sidebar: sidebar 
keywords: convert, exist, dp-type, relationship, xdp 
summary: 您可以轻松地将现有 DP 类型关系转换为 XDP ，以利用版本灵活的 SnapMirror 。 
---
= 将现有的ONTAP SnapMirror DP类型关系转换为XDP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果要升级到ONTAP 9.12.1或更高版本、则必须在升级之前将DP类型关系转换为XDP。ONTAP 9.12.1及更高版本不支持DP类型关系。您可以轻松地将现有 DP 类型关系转换为 XDP ，以利用版本灵活的 SnapMirror 。

在升级到ONTAP 9.12.1之前、必须先将现有DP类型关系转换为XDP、然后才能升级到ONTAP 9.12.1及更高版本。

.关于此任务
* SnapMirror 不会自动将现有的 DP 类型关系转换为 XDP 。要转换此关系，您需要中断并删除现有关系，创建新的 XDP 关系并重新同步此关系。
* 在规划转换时，您应了解 XDP SnapMirror 关系的后台准备和数据仓库阶段可能需要很长时间。在较长的一段时间内， SnapMirror 关系报告状态 " 正在准备 " 的情况并不少见。


[NOTE]
====
将 SnapMirror 关系类型从 DP 转换为 XDP 后，自动调整大小和空间保证等空间相关设置将不再复制到目标。

====
.步骤
. 在目标集群中、确保SnapMirror关系类型为DP、镜像状态为SnapMirrored、关系状态为Idle且关系运行状况良好：
+
[source, cli]
----
snapmirror show -destination-path <SVM:volume>
----
+
以下示例显示了的输出 `snapmirror show` 命令：

+
[listing]
----
cluster_dst::>snapmirror show -destination-path svm_backup:volA_dst

Source Path: svm1:volA
Destination Path: svm_backup:volA_dst
Relationship Type: DP
SnapMirror Schedule: -
Tries Limit: -
Throttle (KB/sec): unlimited
Mirror State: Snapmirrored
Relationship Status: Idle
Transfer Snapshot: -
Snapshot Progress: -
Total Progress: -
Snapshot Checkpoint: -
Newest Snapshot: snapmirror.10af643c-32d1-11e3-954b-123478563412_2147484682.2014-06-27_100026
Newest Snapshot Timestamp: 06/27 10:00:55
Exported Snapshot: snapmirror.10af643c-32d1-11e3-954b-123478563412_2147484682.2014-06-27_100026
Exported Snapshot Timestamp: 06/27 10:00:55
Healthy: true
----
+
[NOTE]
====
您可能会发现保留一份命令输出副本以跟踪现有关系设置会很有帮助 `snapmirror show`。有关的详细信息 `snapmirror show`，请参见link:https://docs.netapp.com/us-en/ontap-cli//snapmirror-show.html["ONTAP 命令参考"^]。

====
. 从源卷和目标卷中、确保两个卷都具有一个通用快照：
+
[source, cli]
----
volume snapshot show -vserver <SVM> -volume <volume>
----
+
以下示例显示了 `volume snapshot show` 源卷和目标卷的输出：

+
[listing]
----
cluster_src:> volume snapshot show -vserver vsm1 -volume volA
---Blocks---
Vserver Volume Snapshot State Size Total% Used%
-------- ------- ------------------------------- -------- -------- ------ -----
svm1 volA
weekly.2014-06-09_0736 valid 76KB 0% 28%
weekly.2014-06-16_1305 valid 80KB 0% 29%
daily.2014-06-26_0842 valid 76KB 0% 28%
hourly.2014-06-26_1205 valid 72KB 0% 27%
hourly.2014-06-26_1305 valid 72KB 0% 27%
hourly.2014-06-26_1405 valid 76KB 0% 28%
hourly.2014-06-26_1505 valid 72KB 0% 27%
hourly.2014-06-26_1605 valid 72KB 0% 27%
daily.2014-06-27_0921 valid 60KB 0% 24%
hourly.2014-06-27_0921 valid 76KB 0% 28%
snapmirror.10af643c-32d1-11e3-954b-123478563412_2147484682.2014-06-27_100026
valid 44KB 0% 19%
11 entries were displayed.


cluster_dest:> volume snapshot show -vserver svm_backup -volume volA_dst
---Blocks---
Vserver Volume Snapshot State Size Total% Used%
-------- ------- ------------------------------- -------- -------- ------ -----
svm_backup volA_dst
weekly.2014-06-09_0736 valid 76KB 0% 30%
weekly.2014-06-16_1305 valid 80KB 0% 31%
daily.2014-06-26_0842 valid 76KB 0% 30%
hourly.2014-06-26_1205 valid 72KB 0% 29%
hourly.2014-06-26_1305 valid 72KB 0% 29%
hourly.2014-06-26_1405 valid 76KB 0% 30%
hourly.2014-06-26_1505 valid 72KB 0% 29%
hourly.2014-06-26_1605 valid 72KB 0% 29%
daily.2014-06-27_0921 valid 60KB 0% 25%
hourly.2014-06-27_0921 valid 76KB 0% 30%
snapmirror.10af643c-32d1-11e3-954b-123478563412_2147484682.2014-06-27_100026
----
. 要确保计划的更新不会在转换期间运行、请暂停现有的DP类型关系：
+
[source, cli]
----
snapmirror quiesce -source-path <SVM:volume> -destination-path <SVM:volume>
----
+
[NOTE]
====
您必须从目标 SVM 或目标集群运行此命令。

====
+
以下示例将使源卷之间的关系处于静音状态 `volA` 开启 `svm1` 和目标卷 `volA_dst` 开启 `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror quiesce -destination-path svm_backup:volA_dst
----
+
有关的详细信息 `snapmirror quiesce`，请参见link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-quiesce.html["ONTAP 命令参考"^]。

. 中断现有的 DP 类型关系：
+
[source, cli]
----
snapmirror break -destination-path <SVM:volume>
----
+
[NOTE]
====
您必须从目标 SVM 或目标集群运行此命令。

====
+
以下示例将中断源卷之间的关系 `volA` 开启 `svm1` 和目标卷 `volA_dst` 开启 `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror break -destination-path svm_backup:volA_dst
----
+
有关的详细信息 `snapmirror break`，请参见link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-break.html["ONTAP 命令参考"^]。

. 如果在目标卷上启用了快照自动删除、请将其禁用：
+
[source, cli]
----
volume snapshot autodelete modify -vserver _SVM_ -volume _volume_ -enabled false
----
+
以下示例将在目标卷上禁用Snapshot自动删除 `volA_dst`：

+
[listing]
----
cluster_dst::> volume snapshot autodelete modify -vserver svm_backup -volume volA_dst -enabled false
----
. 删除现有 DP 类型关系：
+
[source, cli]
----
snapmirror delete -destination-path <SVM:volume>
----
+
有关的详细信息 `snapmirror-delete`，请参见link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-delete.html["ONTAP 命令参考"^]。

+
[NOTE]
====
您必须从目标 SVM 或目标集群运行此命令。

====
+
以下示例将删除源卷之间的关系 `volA` 开启 `svm1` 和目标卷 `volA_dst` 开启 `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror delete -destination-path svm_backup:volA_dst
----
. 释放源上的初始SVM灾难恢复关系：
+
[source, cli]
----
snapmirror release -destination-path <SVM:volume> -relationship-info-only true
----
+
有关的详细信息 `snapmirror release`，请参见link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-release.html["ONTAP 命令参考"^]。

+
以下示例将释放SVM灾难恢复关系：

+
[listing]
----
cluster_src::> snapmirror release -destination-path svm_backup:volA_dst -relationship-info-only true
----
. 您可以使用中保留的输出 `snapmirror show` 用于创建新XDP类型关系的命令：
+
[source, cli]
----
snapmirror create -source-path <SVM:volume> -destination-path <SVM:volume>  -type XDP -schedule <schedule> -policy <policy>
----
+
新关系必须使用相同的源卷和目标卷。有关此过程中所述命令的更多信息，请参见link:https://docs.netapp.com/us-en/ontap-cli/["ONTAP 命令参考"^]。

+
[NOTE]
====
您必须从目标 SVM 或目标集群运行此命令。

====
+
以下示例将在源卷之间创建SnapMirror灾难恢复关系 `volA` 开启 `svm1` 和目标卷 `volA_dst` 开启 `svm_backup` 使用默认值 `MirrorAllSnapshots` 策略：

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1:volA -destination-path svm_backup:volA_dst
-type XDP -schedule my_daily -policy MirrorAllSnapshots
----
. 重新同步源卷和目标卷：
+
[source, cli]
----
snapmirror resync -source-path <SVM:volume> -destination-path <SVM:volume>
----
+
为了缩短重新同步时间、您可以使用 `-quick-resync`选项、但您应注意、存储效率节省的空间可能会丢失。有关的详细信息 `snapmirror resync`，请参见link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-resync.html#parameters.html["ONTAP 命令参考"^]。

+
[NOTE]
====
您必须从目标 SVM 或目标集群运行此命令。虽然重新同步不需要基线传输，但它可能非常耗时。您可能希望在非高峰时段运行重新同步。

====
+
以下示例将重新同步源卷之间的关系 `volA` 开启 `svm1` 和目标卷 `volA_dst` 开启 `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror resync -source-path svm1:volA -destination-path svm_backup:volA_dst
----
. 如果您禁用了快照自动删除、请重新启用它：
+
[source, cli]
----
volume snapshot autodelete modify -vserver <SVM> -volume <volume> -enabled true
----


.完成后
. 使用 `snapmirror show` 命令以验证是否已创建SnapMirror关系。
. SnapMirror XDP目标卷开始按照SnapMirror策略的定义更新快照后、使用源集群中的命令输出 `snapmirror list-destinations`显示新的SnapMirror XDP关系。


.有关DP类型关系的其他信息
从ONTAP 9.3开始、XDP模式为默认模式、在命令行或新脚本或现有脚本中调用的任何DP模式都将自动转换为XDP模式。

现有关系不受影响。如果某个关系的类型已经是 DP ，则它将继续为 DP 类型。从ONTAP 9.5开始、如果未指定数据保护模式或将XDP模式指定为关系类型、则默认策略为镜像和存储。下表显示了预期行为。

[cols="3*"]
|===


| 指定项 | 类型为 ... | 默认策略（如果未指定策略）为 ... 


 a| 
数据
 a| 
XDP
 a| 
MirrorAllSnapshots （ SnapMirror 灾难恢复）



 a| 
无
 a| 
XDP
 a| 
MirrorAndVault （统一复制）



 a| 
XDP
 a| 
XDP
 a| 
MirrorAndVault （统一复制）

|===
如表所示、在不同情况下分配给XDP的默认策略可确保转换保持与先前类型的功能等效。当然，您可以根据需要使用不同的策略，包括用于统一复制的策略：

[cols="3*"]
|===


| 指定项 | 策略是 ... | 结果是 ... 


 a| 
数据
 a| 
MirrorAllSnapshots
 a| 
SnapMirror 灾难恢复



 a| 
XDPDefault
 a| 
SnapVault



 a| 
MirrorAndVault
 a| 
统一复制



 a| 
XDP
 a| 
MirrorAllSnapshots
 a| 
SnapMirror 灾难恢复



 a| 
XDPDefault
 a| 
SnapVault



 a| 
MirrorAndVault
 a| 
统一复制

|===
转换的唯一例外情况如下：

* 在 ONTAP 9.3 及更早版本中， SVM 数据保护关系仍默认为 DP 模式。
+
从 ONTAP 9.4 开始， SVM 数据保护关系默认为 XDP 模式。

* 根卷负载共享数据保护关系仍默认为 DP 模式。
* 在 ONTAP 9.4 及更早版本中， SnapLock 数据保护关系仍默认为 DP 模式。
+
从 ONTAP 9.5 开始， SnapLock 数据保护关系默认为 XDP 模式。

* 如果设置了以下集群范围选项，则显式调用 DP 仍会默认为 DP 模式：
+
[listing]
----
options replication.create_data_protection_rels.enable on
----
+
如果不显式调用 DP ，则会忽略此选项。



.相关信息
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["SnapMirror 创建"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-delete.html["SnapMirror删除"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-quiesce.html["SnapMirror 静默"^]

