---
permalink: data-protection/convert-snapmirror-version-flexible-task.html 
sidebar: sidebar 
keywords: convert, exist, dp-type, relationship, xdp 
summary: 您可以轻松地将现有 DP 类型关系转换为 XDP ，以利用版本灵活的 SnapMirror 。 
---
= 将现有 DP 类型关系转换为 XDP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以轻松地将现有 DP 类型关系转换为 XDP ，以利用版本灵活的 SnapMirror 。

.关于此任务
* 如果要升级到ONTAP 9.12.1或更高版本、则必须在升级之前将DP类型关系转换为XDP。ONTAP 9.12.1及更高版本不支持DP类型关系。
* SnapMirror 不会自动将现有的 DP 类型关系转换为 XDP 。要转换此关系，您需要中断并删除现有关系，创建新的 XDP 关系并重新同步此关系。有关背景信息，请参见 link:version-flexible-snapmirror-default-concept.html["XDP 取代 DP 作为 SnapMirror 默认设置"]。
* 在规划转换时，您应了解 XDP SnapMirror 关系的后台准备和数据仓库阶段可能需要很长时间。在较长的一段时间内， SnapMirror 关系报告状态 " 正在准备 " 的情况并不少见。


[NOTE]
====
将 SnapMirror 关系类型从 DP 转换为 XDP 后，自动调整大小和空间保证等空间相关设置将不再复制到目标。

====
.步骤
. 在目标集群中、确保SnapMirror关系类型为DP、镜像状态为SnapMirrored、关系状态为Idle且关系运行状况良好：
+
`snapmirror show -destination-path _SVM:volume_|_cluster://SVM/volume_`

+
以下示例显示了的输出 `snapmirror show` 命令：

+
[listing]
----
cluster_dst::>snapmirror show -destination-path svm_backup:volA_dst

Source Path: svm1:volA
Destination Path: svm_backup:volA_dst
Relationship Type: DP
SnapMirror Schedule: -
Tries Limit: -
Throttle (KB/sec): unlimited
Mirror State: Snapmirrored
Relationship Status: Idle
Transfer Snapshot: -
Snapshot Progress: -
Total Progress: -
Snapshot Checkpoint: -
Newest Snapshot: snapmirror.10af643c-32d1-11e3-954b-123478563412_2147484682.2014-06-27_100026
Newest Snapshot Timestamp: 06/27 10:00:55
Exported Snapshot: snapmirror.10af643c-32d1-11e3-954b-123478563412_2147484682.2014-06-27_100026
Exported Snapshot Timestamp: 06/27 10:00:55
Healthy: true
----
+
[NOTE]
====
您可能会发现保留的副本很有用 `snapmirror show` 用于跟踪现有关系设置的命令输出。

====
. 在源卷和目标卷中、确保两个卷都具有通用Snapshot副本：
+
`volume snapshot show -vserver _SVM_ -volume _volume_`

+
以下示例显示了 `volume snapshot show` 源卷和目标卷的输出：

+
[listing]
----
cluster_src:> volume snapshot show -vserver vsm1 -volume volA
---Blocks---
Vserver Volume Snapshot State Size Total% Used%
-------- ------- ------------------------------- -------- -------- ------ -----
svm1 volA
weekly.2014-06-09_0736 valid 76KB 0% 28%
weekly.2014-06-16_1305 valid 80KB 0% 29%
daily.2014-06-26_0842 valid 76KB 0% 28%
hourly.2014-06-26_1205 valid 72KB 0% 27%
hourly.2014-06-26_1305 valid 72KB 0% 27%
hourly.2014-06-26_1405 valid 76KB 0% 28%
hourly.2014-06-26_1505 valid 72KB 0% 27%
hourly.2014-06-26_1605 valid 72KB 0% 27%
daily.2014-06-27_0921 valid 60KB 0% 24%
hourly.2014-06-27_0921 valid 76KB 0% 28%
snapmirror.10af643c-32d1-11e3-954b-123478563412_2147484682.2014-06-27_100026
valid 44KB 0% 19%
11 entries were displayed.


cluster_dest:> volume snapshot show -vserver svm_backup -volume volA_dst
---Blocks---
Vserver Volume Snapshot State Size Total% Used%
-------- ------- ------------------------------- -------- -------- ------ -----
svm_backup volA_dst
weekly.2014-06-09_0736 valid 76KB 0% 30%
weekly.2014-06-16_1305 valid 80KB 0% 31%
daily.2014-06-26_0842 valid 76KB 0% 30%
hourly.2014-06-26_1205 valid 72KB 0% 29%
hourly.2014-06-26_1305 valid 72KB 0% 29%
hourly.2014-06-26_1405 valid 76KB 0% 30%
hourly.2014-06-26_1505 valid 72KB 0% 29%
hourly.2014-06-26_1605 valid 72KB 0% 29%
daily.2014-06-27_0921 valid 60KB 0% 25%
hourly.2014-06-27_0921 valid 76KB 0% 30%
snapmirror.10af643c-32d1-11e3-954b-123478563412_2147484682.2014-06-27_100026
----
. 要确保计划的更新不会在转换期间运行、请暂停现有的DP类型关系：
+
`snapmirror quiesce -source-path _SVM:volume_|_cluster://SVM/volume_, ... -destination-path _SVM:volume_|_cluster://SVM/volume_, ...`

+
有关完整的命令语法，请参见手册页。

+
[NOTE]
====
您必须从目标 SVM 或目标集群运行此命令。

====
+
以下示例将使源卷之间的关系处于静音状态 `volA` 开启 `svm1` 和目标卷 `volA_dst` 开启 `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror quiesce -destination-path svm_backup:volA_dst
----
. 中断现有的 DP 类型关系：
+
`snapmirror break -destination-path _SVM:volume_|_cluster://SVM/volume_, ...`

+
有关完整的命令语法，请参见手册页。

+
[NOTE]
====
您必须从目标 SVM 或目标集群运行此命令。

====
+
以下示例将中断源卷之间的关系 `volA` 开启 `svm1` 和目标卷 `volA_dst` 开启 `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror break -destination-path svm_backup:volA_dst
----
. 如果在目标卷上启用了Snapshot副本自动删除、请将其禁用：
+
`volume snapshot autodelete modify -vserver _SVM_ -volume _volume_ -enabled false`

+
以下示例将在目标卷上禁用Snapshot副本自动删除 `volA_dst`：

+
[listing]
----
cluster_dst::> volume snapshot autodelete modify -vserver svm_backup -volume volA_dst -enabled false
----
. 删除现有 DP 类型关系：
+
`snapmirror delete -destination-path _SVM:volume_|_cluster://SVM/volume_, ...`

+
有关完整的命令语法，请参见手册页。

+
[NOTE]
====
您必须从目标 SVM 或目标集群运行此命令。

====
+
以下示例将删除源卷之间的关系 `volA` 开启 `svm1` 和目标卷 `volA_dst` 开启 `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror delete -destination-path svm_backup:volA_dst
----
. 您可以使用中保留的输出 `snapmirror show` 用于创建新XDP类型关系的命令：
+
`snapmirror create -source-path _SVM:volume_|_cluster://SVM/volume_, ... -destination-path _SVM:volume_|_cluster://SVM/volume_, ... -type XDP -schedule _schedule_ -policy _policy_`

+
新关系必须使用相同的源卷和目标卷。有关完整的命令语法，请参见手册页。

+
[NOTE]
====
您必须从目标 SVM 或目标集群运行此命令。

====
+
以下示例将在源卷之间创建SnapMirror灾难恢复关系 `volA` 开启 `svm1` 和目标卷 `volA_dst` 开启 `svm_backup` 使用默认值 `MirrorAllSnapshots` 策略：

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1:volA -destination-path svm_backup:volA_dst
-type XDP -schedule my_daily -policy MirrorAllSnapshots
----
. 重新同步源卷和目标卷：
+
`snapmirror resync -source-path _SVM:volume_|_cluster://SVM/volume_, ... -destination-path _SVM:volume_|_cluster://SVM/volume_, ...`

+
要缩短重新同步时间、您可以使用 `-quick-resync` 选项、但您应注意、存储效率节省可能会丢失。有关完整的命令语法、请参见手册页： link:https://docs.netapp.com/us-en/ontap-cli-9131/snapmirror-resync.html#parameters.html["snapmirror resync命令"]。

+
[NOTE]
====
您必须从目标 SVM 或目标集群运行此命令。虽然重新同步不需要基线传输，但它可能非常耗时。您可能希望在非高峰时段运行重新同步。

====
+
以下示例将重新同步源卷之间的关系 `volA` 开启 `svm1` 和目标卷 `volA_dst` 开启 `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror resync -source-path svm1:volA -destination-path svm_backup:volA_dst
----
. 如果您禁用了Snapshot副本自动删除、请重新启用它：
+
`volume snapshot autodelete modify -vserver _SVM_ -volume _volume_ -enabled true`



.完成后
. 使用 `snapmirror show` 命令以验证是否已创建SnapMirror关系。有关完整的命令语法，请参见手册页。
. 一旦SnapMirror XDP目标卷开始按照SnapMirror策略的定义更新Snapshot副本、您就可以使用的输出 `snapmirror list-destinations` 命令以显示新的SnapMirror XDP关系。

