---
permalink: data-protection/create-replication-relationship-task.html 
sidebar: sidebar 
keywords: create, replication, relationship 
summary: 主存储中的源卷与二级存储中的目标卷之间的关系称为数据保护关系。您可以使用 snapmirror create 命令创建 SnapMirror 灾难恢复， SnapVault 或统一复制数据保护关系。 
---
= 创建复制关系
:icons: font
:imagesdir: ../media/


[role="lead"]
主存储中的源卷与二级存储中的目标卷之间的关系称为 _data protection relationship 。 _ 您可以使用 `snapmirror create` 命令创建 SnapMirror DR ， SnapVault 或统一复制数据保护关系。

.您需要什么？ #8217 ；将需要什么
* 源和目标集群以及 SVM 必须建立对等关系。
+
https://docs.netapp.com/us-en/ontap-sm-classic/peering/index.html["集群和 SVM 对等"]

* 目标卷上的语言必须与源卷上的语言相同。


在 ONTAP 9.3 之前，在 DP 模式下调用的 SnapMirror 和在 XDP 模式下调用的 SnapMirror 使用不同的复制引擎，对版本依赖性采用不同的方法：

* 在 DP 模式下调用的 SnapMirror 使用了一个 _version-dependent _ 复制引擎，其中，主存储和二级存储上的 ONTAP 版本必须相同：
+
[listing]
----
cluster_dst::>  snapmirror create -type DP -source-path ... -destination-path ...
----
* 在 XDP 模式下调用的 SnapMirror 使用 _version-flexible 复制引擎，该引擎支持主存储和二级存储上的不同 ONTAP 版本：
+
[listing]
----
cluster_dst::>  snapmirror create -type XDP -source-path ... -destination-path ...
----


随着性能的提高，版本灵活的 SnapMirror 的显著优势大于使用版本相关模式获得的复制吞吐量的轻微优势。因此，从 ONTAP 9.3 开始， XDP 模式已成为新的默认模式，在命令行或新脚本或现有脚本中调用的任何 DP 模式都会自动转换为 XDP 模式。

现有关系不受影响。如果某个关系的类型已经是 DP ，则它将继续为 DP 类型。下表显示了您可能会遇到的行为。

[cols="3*"]
|===
| 指定项 | 类型为 ... | 默认策略（如果未指定策略）为 ... 


 a| 
数据
 a| 
XDP
 a| 
MirrorAllSnapshots （ SnapMirror 灾难恢复）



 a| 
无
 a| 
XDP
 a| 
MirrorAllSnapshots （ SnapMirror 灾难恢复）



 a| 
XDP
 a| 
XDP
 a| 
XDPDefault （ SnapVault ）

|===
另请参见下面操作步骤中的示例。

转换的唯一例外情况如下：

* SVM 数据保护关系仍默认为 DP 模式。
+
显式指定 XDP 以使用默认的 `MirrorAllSnapshots` 策略获取 XDP 模式。

* 负载共享数据保护关系仍默认为 DP 模式。
* SnapLock 数据保护关系仍默认为 DP 模式。
* 如果设置了以下集群范围选项，则显式调用 DP 仍会默认为 DP 模式：
+
[listing]
----
options replication.create_data_protection_rels.enable on
----
+
如果不显式调用 DP ，则会忽略此选项。



在 ONTAP 9.3 及更早版本中，目标卷最多可包含 251 个 Snapshot 副本。在 ONTAP 9.4 及更高版本中，目标卷最多可以包含 1019 个 Snapshot 副本。

从 ONTAP 9.5 开始，支持 SnapMirror 同步关系。

.步骤
. 从目标集群中，创建复制关系：
+
`snapmirror create -source-path _SVM ： volume_|_cluster ： //svm/volume_ ， ... -destination-path _svm ： volume_|_cluster ： //svm/volume_ ， ... -type dp_xdp -schedule _schedule_ -policy _policy_`

+
有关完整的命令语法，请参见手册页。

+
[NOTE]
====
创建 SnapMirror 同步关系时， `schedule` 参数不适用。

====
+
以下示例将使用默认的 `MirrorLatest` 策略创建 SnapMirror 灾难恢复关系：

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1:volA -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy MirrorLatest
----
+
以下示例将使用默认 `XDPDefault` 策略创建 SnapVault 关系：

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1:volA -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy XDPDefault
----
+
以下示例将使用默认的 `MirrorAndVault` 策略创建统一复制关系：

+
[listing]
----
cluster_dst:> snapmirror create -source-path svm1:volA -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy MirrorAndVault
----
+
以下示例将使用自定义 `my_unified` 策略创建统一复制关系：

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1:volA -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy my_unified
----
+
以下示例将使用默认的 `Sync` 策略创建 SnapMirror 同步关系：

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1:volA -destination-path svm_backup:volA_dst -type XDP -policy Sync
----
+
以下示例将使用默认的 `StrictSync` 策略创建 SnapMirror 同步关系：

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1:volA -destination-path svm_backup:volA_dst -type XDP -policy StrictSync
----
+
以下示例将创建 SnapMirror 灾难恢复关系。在 DP 类型自动转换为 XDP 且未指定任何策略的情况下，此策略默认为 `MirrorAllSnapshots` 策略：

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1:volA -destination-path svm_backup:volA_dst -type DP -schedule my_daily
----
+
以下示例将创建 SnapMirror 灾难恢复关系。在未指定任何类型或策略的情况下，此策略将默认为 `MirrorAllSnapshots` 策略：

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1:volA -destination-path svm_backup:volA_dst -schedule my_daily
----
+
以下示例将创建 SnapMirror 灾难恢复关系。如果未指定任何策略，则此策略默认为 `XDPDefault` 策略：

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1:volA -destination-path svm_backup:volA_dst -type XDP -schedule my_daily
----
+
以下示例将使用预定义策略 `SnapCenterSync` 创建 SnapMirror 同步关系：

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1:volA -destination-path svm_backup:volA_dst -type XDP -policy SnapCenterSync
----
+
[NOTE]
====
预定义策略 `SnapCenterSync` 的类型为 `Sync` 。此策略会复制使用 `snapmirror-label` "app_consistent" 创建的任何 Snapshot 副本。

====


使用 `snapmirror show` 命令验证是否已创建 SnapMirror 关系。有关完整的命令语法，请参见手册页。
