---
permalink: data-protection/create-load-sharing-mirror-task.html 
sidebar: sidebar 
keywords: create, initialize, load-sharing, mirror, relationship 
summary: 您应为集群中的每个根卷创建负载共享镜像（ LSM ）。您可以在包含根卷的节点以外的任何节点上创建 LSM ，例如 HA 对中的配对节点，或者最好在其他 HA 对中创建。对于双节点集群，您应在具有根卷的节点的配对节点上创建 LSM 。 
---
= 创建并初始化负载共享镜像关系
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您应为集群中提供 NAS 数据的每个 SVM 根卷创建负载共享镜像（ LSM ）。对于包含两个或更多HA对的集群、您应考虑为SVM根卷创建负载共享镜像、以确保在发生这种情况时客户端仍可访问命名空间
HA对的两个节点都发生故障。负载共享镜像不适用于包含单个HA对的集群。

.关于此任务
如果在同一节点上创建 LSM ，并且该节点不可用，则表示发生单点故障，并且没有第二个副本，以确保客户端仍可访问数据。但是，如果在包含根卷的节点以外的节点上创建 LSM ，或者在其他 HA 对上创建 LSM ，则在发生中断时仍可访问您的数据。

例如，在根卷位于三个节点上的四节点集群中：

* 对于 HA 1 节点 1 上的根卷，在 HA 2 节点 1 或 HA 2 节点 2 上创建 LSM 。
* 对于 HA 1 节点 2 上的根卷，在 HA 2 节点 1 或 HA 2 节点 2 上创建 LSM 。
* 对于 HA 2 节点 1 上的根卷，在 HA 1 节点 1 或 HA 1 节点 2 上创建 LSM 。


.步骤
. 为 LSM 创建目标卷：
+
在运行此命令之前、必须将尖括号中的变量替换为所需的值。

+
[source, cli]
----
volume create -vserver <SVM> -volume <volume> -aggregate <aggregate> -type DP -size <size>
----
+
目标卷的大小应等于或大于根卷。

+
最佳做法是、为根卷和目标卷命名时使用后缀、例如 `_root` 和 `_m1`。

+
有关完整的命令语法，请参见手册页。

+
以下示例将为根卷创建负载共享镜像卷 `svm1_root` 在中 `cluster_src`：

+
[listing]
----
cluster_src:> volume create -vserver svm1 -volume svm1_m1 -aggregate aggr_1 -size 1gb -state online -type DP
----
. link:create-replication-job-schedule-task.html["创建复制作业计划"]。
. 在 SVM 根卷和 LSM 的目标卷之间创建负载共享镜像关系：
+
在运行此命令之前、必须将尖括号中的变量替换为所需的值。

+
[source, cli]
----
snapmirror create -source-path <SVM:volume> -destination-path <SVM:volume> -type LS -schedule <schedule>
----
+
有关完整的命令语法，请参见手册页。

+
以下示例将在根卷之间创建负载共享镜像关系 `svm1_root` 和负载共享镜像卷 `svm1_m1`：

+
[listing]
----
cluster_src::> snapmirror create -source-path svm1:svm1_root -destination-path svm1:svm1_m1 -type LS -schedule hourly
----
+
负载共享镜像的类型属性将从更改为 `DP` to `LS`。

. 初始化负载共享镜像：
+
在运行此命令之前、必须将尖括号中的变量替换为所需的值。

+
[source, cli]
----
snapmirror initialize-ls-set -source-path <SVM:volume>
----
+
初始化可能非常耗时。您可能希望在非高峰时段运行基线传输。

+
有关完整的命令语法，请参见手册页。

+
以下示例将初始化根卷的负载共享镜像 `svm1_root`：

+
[listing]
----
cluster_src::> snapmirror initialize-ls-set -source-path svm1:svm1_root
----

