---
permalink: data-protection/create-smb-server-task.html 
sidebar: sidebar 
keywords: cifs, create, smb, server 
summary: 如果源 SVM 具有 SMB 配置，并且您选择将 identity-preserve 设置为 false ，则必须为目标 SVM 创建 SMB 服务器。某些SMB配置需要SMB服务器、例如、在初始化SnapMirror关系期间共享。 
---
= 为DR关系中的ONTAP SnapMirror目标SVM创建SMB服务器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果源SVM具有SMB配置、而您选择将设置 `identity-preserve`为、则必须为 `false`目标SVM创建SMB服务器。某些SMB配置需要SMB服务器、例如、在初始化SnapMirror关系期间共享。

.步骤
. 使用命令启动目标SVM `vserver start`。
+
[listing]
----
destination_cluster::> vserver start -vserver dvs1
[Job 30] Job succeeded: DONE
----
+
有关的详细信息 `vserver start`，请参见link:https://docs.netapp.com/us-en/ontap-cli/vserver-start.html["ONTAP 命令参考"^]。

. 验证目标SVM是否位于中 `running` 状态和子类型为 `dp-destination` 使用 `vserver show` 命令：
+
[listing]
----
destination_cluster::> vserver show
                                   Admin      Operational Root
Vserver  Type    Subtype           State      State       Volume     Aggregate
-------- ------- ----------       ---------- ----------- ---------- ----------
dvs1     data    dp-destination    running    running       -         -
----
+
有关的详细信息 `vserver show`，请参见link:https://docs.netapp.com/us-en/ontap-cli/vserver-show.html["ONTAP 命令参考"^]。

. 使用创建LIF `network interface create` 命令：
+
[listing]
----
destination_cluster::>network interface create -vserver dvs1 -lif NAS1 -role data -data-protocol cifs -home-node destination_cluster-01 -home-port a0a-101  -address 192.0.2.128 -netmask 255.255.255.128
----
+
有关的详细信息 `network interface create`，请参见link:https://docs.netapp.com/us-en/ontap-cli/network-interface-create.html["ONTAP 命令参考"^]。

. 使用创建路由 `network route create` 命令：
+
[listing]
----
destination_cluster::>network route create -vserver dvs1 -destination 0.0.0.0/0
-gateway 192.0.2.1
----
+
link:../networking/networking_reference.html["网络管理"]

+
有关的详细信息 `network route create`，请参见link:https://docs.netapp.com/us-en/ontap-cli/network-route-create.html["ONTAP 命令参考"^]。

. 使用配置DNS `vserver services dns create` 命令：
+
[listing]
----
destination_cluster::>vserver services dns create -domains mydomain.example.com -vserver
dvs1 -name-servers 192.0.2.128 -state enabled
----
+
有关的详细信息 `vserver services dns create`，请参见link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+services+dns+create["ONTAP 命令参考"^]。

. 使用添加首选域控制器 `vserver cifs domain preferred-dc add` 命令：
+
[listing]
----
destination_cluster::>vserver cifs domain preferred-dc add -vserver dvs1 -preferred-dc
192.0.2.128 -domain mydomain.example.com
----
+
有关的详细信息 `vserver cifs domain preferred-dc add`，请参见link:https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-domain-preferred-dc-add.html["ONTAP 命令参考"^]。

. 使用创建SMB服务器 `vserver cifs create` 命令：
+
[listing]
----
destination_cluster::>vserver cifs create -vserver dvs1 -domain mydomain.example.com
-cifs-server CIFS1
----
+
有关的详细信息 `vserver cifs create`，请参见link:https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-create.html["ONTAP 命令参考"^]。

. 使用停止目标SVM `vserver stop` 命令：
+
[listing]
----
destination_cluster::> vserver stop -vserver dvs1
[Job 46] Job succeeded: DONE
----
+
有关的详细信息 `vserver stop`，请参见link:https://docs.netapp.com/us-en/ontap-cli/vserver-stop.html["ONTAP 命令参考"^]。


