---
permalink: data-protection/define-rule-policy-task.html 
sidebar: sidebar 
keywords: define, rule, policy, data protection 
summary: '对于策略类型为"vault"或"mirrir-vault"的自定义策略、必须至少定义一个规则来确定初始化和更新期间传输的快照。您还可以为策略类型为 " 存储 " 或 " 镜像 - 存储 " 的默认策略定义规则。' 
---
= 使用ONTAP为策略定义规则
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
对于策略类型为或 `mirror-vault`的自定义 `vault`策略、您必须至少定义一个规则来确定初始化和更新期间传输的快照。您还可以为策略类型为或 `mirror-vault`的默认策略定义规则 `vault`。

.关于此任务
策略类型为或 `mirror-vault`的每个策略都 `vault`必须具有一条规则、用于指定要复制哪些快照。例如，规则 `bi-monthly`指示只应复制分配了SnapMirror标签的快照 `bi-monthly`。在源上配置快照策略时、可以指定SnapMirror标签。

每个策略类型都与一个或多个系统定义的规则相关联。指定策略类型时，系统会自动为策略分配这些规则。下表显示了系统定义的规则。

[cols="3*"]
|===


| 系统定义的规则 | 用于策略类型 | 结果 


 a| 
sm_created
 a| 
异步镜像，镜像存储，同步， StrictSync
 a| 
SnapMirror创建的快照将在初始化和更新时传输。



 a| 
all_source_snapshots
 a| 
异步镜像
 a| 
源上的新快照将在初始化和更新时传输。



 a| 
每天
 a| 
存储，镜像存储
 a| 
初始化和更新时会传输源上标有SnapMirror标签的新快照 `daily`。



 a| 
每周
 a| 
存储，镜像存储
 a| 
初始化和更新时会传输源上标有SnapMirror标签的新快照 `weekly`。



 a| 
每月
 a| 
镜像存储
 a| 
初始化和更新时会传输源上标有SnapMirror标签的新快照 `monthly`。



 a| 
应用程序一致
 a| 
Sync ， StrictSync
 a| 
源上具有SnapMirror标签的快照 `app_consistent`会同步复制到目标。从ONTAP 9.7开始支持。

|===
除了 "`async-mirror` " 策略类型之外，您还可以根据需要为默认或自定义策略指定其他规则。例如：

* 对于默认 `MirrorAndVault`策略、您可以创建一个名为的规则 `bi-monthly`、以匹配源上具有SnapMirror标签的快照 `bi-monthly`。
* 对于策略类型为的自定义策略 `mirror-vault`、您可以创建一个名为的规则 `bi-weekly`、以匹配源上具有SnapMirror标签的快照 `bi-weekly`。


.步骤
. 为策略定义规则：
+
`snapmirror policy add-rule -vserver _SVM_ -policy _policy_for_rule_ -snapmirror-label _snapmirror-label_ -keep _retention_count_`

+
有关的详细信息 `snapmirror policy add-rule`，请参见link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-add-rule.html["ONTAP 命令参考"^]。

+
以下示例将添加一个SnapMirror标签为的规则 `bi-monthly` 设置为默认值 `MirrorAndVault` 策略：

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy MirrorAndVault -snapmirror-label bi-monthly -keep 6
----
+
以下示例将添加一个SnapMirror标签为的规则 `bi-weekly` 自定义 `my_snapvault` 策略：

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy my_snapvault -snapmirror-label bi-weekly -keep 26
----
+
以下示例将添加一个SnapMirror标签为的规则 `app_consistent` 自定义 `Sync` 策略：

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy Sync -snapmirror-label app_consistent -keep 1
----
+
然后、您可以从与此SnapMirror标签匹配的源集群复制快照：

+
[listing]
----
cluster_src::> snapshot create -vserver vs1 -volume vol1 -snapshot snapshot1 -snapmirror-label app_consistent
----

