---
permalink: data-protection/delete-volume-replication-relationship-task.html 
sidebar: sidebar 
keywords: delete, volume, replication, relationship, replicate, synchronous, snapmirror, quiese, pause 
summary: 您可以使用 snapmirror delete 和 snapmirror release 命令删除卷复制关系。然后，您可以手动删除不需要的目标卷。 
---
= 删除与ONTAP的卷复制关系
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `snapmirror delete` 和 `snapmirror release` 用于删除卷复制关系的命令。然后，您可以手动删除不需要的目标卷。

.关于此任务
 `snapmirror release`命令将从源中删除SnapMirror创建的任何快照。您可以使用 `-relationship-info-only`选项保留快照。

.步骤
. 暂停复制关系：
+
`snapmirror quiesce -destination-path <SVM:volume>|<cluster://SVM/volume>`

+
[listing]
----
cluster_dst::> snapmirror quiesce -destination-path svm_backup:volA_dst
----
+
有关的详细信息 `snapmirror quiesce`，请参见link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-quiesce.html["ONTAP 命令参考"^]。

. (可选)如果您要求目标卷为读/写卷、请中断复制关系。如果您计划删除目标卷或不需要对卷进行读/写、则可以跳过此步骤：
+
`snapmirror break -source-path <SVM:volume>|<cluster://SVM/volume>, …​ -destination-path <SVM:volume>|<cluster://SVM/volume>, …​`

+
[listing]
----
cluster_dst::> snapmirror break -source-path svm1:volA -destination-path svm_backup:volA_dst
----
+
有关的详细信息 `snapmirror break`，请参见link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-break.html["ONTAP 命令参考"^]。

. 删除复制关系：
+
`snapmirror delete -source-path <SVM:volume>|<cluster://SVM/volume>, ... -destination-path <SVM:volume>|<cluster://SVM/volume>, ...`

+
[NOTE]
====
您必须从目标集群或目标 SVM 运行此命令。

====
+
以下示例将删除源卷之间的关系 `volA` 开启 `svm1` 和目标卷 `volA_dst` 开启 `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror delete -source-path svm1:volA -destination-path svm_backup:volA_dst
----
+
有关的详细信息 `snapmirror delete`，请参见link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-delete.html["ONTAP 命令参考"^]。

. 从源 SVM 释放复制关系信息：
+
`snapmirror release -source-path <SVM:volume>|<cluster://SVM/volume>, ... -destination-path <SVM:volume>|<cluster://SVM/volume>, ...`

+
[NOTE]
====
您必须从源集群或源 SVM 运行此命令。

====
+
以下示例将从源SVM释放指定复制关系的信息 `svm1`：

+
[listing]
----
cluster_src::> snapmirror release -source-path svm1:volA -destination-path svm_backup:volA_dst
----
+
有关的详细信息 `snapmirror release`，请参见link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-release.html["ONTAP 命令参考"^]。


