---
permalink: data-protection/delete-svm-replication-relationship-task.html 
sidebar: sidebar 
keywords: delete, svm, replication, relationship 
summary: 您可以使用 snapmirror delete 和 snapmirror release 命令删除 SVM 复制关系。然后，您可以手动删除不需要的目标卷。 
---
= 删除ONTAP SVM复制关系
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `snapmirror delete` 和 `snapmirror release` 用于删除SVM复制关系的命令。然后，您可以手动删除不需要的目标卷。

.关于此任务
。 `snapmirror release` 命令将从源中删除SnapMirror创建的任何Snapshot副本。您可以使用 `-relationship-info-only` 选项以保留Snapshot副本。

有关的详细信息 `snapmirror release`，请参见link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-release.html["ONTAP 命令参考"^]。

.步骤
. 从目标 SVM 或目标集群运行以下命令以中断复制关系：
+
`snapmirror break -source-path _SVM_: -destination-path _SVM_:`

+
[NOTE]
====
您必须在中的SVM名称后面输入冒号(：) `-source-path` 和 `-destination-path` 选项请参见以下示例。

====
+
以下示例将中断源SVM之间的关系 `svm1` 和目标SVM `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror break -source-path svm1: -destination-path svm_backup:
----
. 从目标 SVM 或目标集群运行以下命令以删除复制关系：
+
`snapmirror delete -source-path _SVM_: -destination-path _SVM_:`

+
[NOTE]
====
您必须在中的SVM名称后面输入冒号(：) `-source-path` 和 `-destination-path` 选项请参见以下示例。

====
+
以下示例将删除源SVM之间的关系 `svm1` 和目标SVM `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror delete -source-path svm1: -destination-path svm_backup:
----
. 从源集群或源 SVM 运行以下命令，以从源 SVM 释放复制关系信息：
+
`snapmirror release -source-path _SVM_: -destination-path _SVM_:`

+
[NOTE]
====
您必须在中的SVM名称后面输入冒号(：) `-source-path` 和 `-destination-path` 选项请参见以下示例。

====
+
以下示例将从源SVM释放指定复制关系的信息 `svm1`：

+
[listing]
----
cluster_src::> snapmirror release -source-path svm1: -destination-path svm_backup:
----

