---
permalink: data-protection/delete-volume-replication-relationship-task.html 
sidebar: sidebar 
keywords: delete, volume, replication, relationship, replicate, synchronous, snapmirror, quiese, pause 
summary: 您可以使用 snapmirror delete 和 snapmirror release 命令删除卷复制关系。然后，您可以手动删除不需要的目标卷。 
---
= 删除卷复制关系
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `snapmirror delete` 和 `snapmirror release` 命令删除卷复制关系。然后，您可以手动删除不需要的目标卷。

使用 `snapmirror release` 命令可从源中删除 SnapMirror 创建的任何 Snapshot 副本。您可以使用 ` -relationship-info-only` 选项保留 Snapshot 副本。

.步骤
. 暂停复制关系：
+
`snapmirror quiesce -destination-path _svm ： volume_|_cluster ： //svm/volume_`

+
[listing]
----
cluster_dst::> snapmirror quiesce -destination-path svm_backup:volA_dst
----
. 中断复制关系：
+
`snapmirror break -source-path SVM ： volume| cluster ： //svm/ volume ，…​ -destination-path SVM ： volume| cluster ： //svm/ volume ，…​`

+
[listing]
----
cluster_dst::> snapmirror break -source-path svm1:volA -destination-path svm_backup:volA_dst
----
. 删除复制关系：
+
`snapmirror delete -source-path _SVM ： volume_|_cluster ： //svm/volume_ ， ... -destination-path _sVM ： volume_|_cluster ： //svm/volume_ ， ...`

+
有关完整的命令语法，请参见手册页。

+
[NOTE]
====
您必须从目标集群或目标 SVM 运行此命令。

====
+
以下示例将删除源卷 `vola` on `svm1` 与目标卷 `vola_dst` on `svm_backup` 之间的关系：

+
[listing]
----
cluster_dst::> snapmirror delete -source-path svm1:volA -destination-path svm_backup:volA_dst
----
. 从源 SVM 释放复制关系信息：
+
`snapmirror release -source-path _svm ： volume___cluster ： //svm/volume_ ， ... -destination-path _sVM ： volume_|_cluster ： //svm/volume_ ， ...`

+
有关完整的命令语法，请参见手册页。

+
[NOTE]
====
您必须从源集群或源 SVM 运行此命令。

====
+
以下示例将从源 SVM `svm1` 释放指定复制关系的信息：

+
[listing]
----
cluster_src::> snapmirror release -source-path svm1:volA -destination-path svm_backup:volA_dst
----

