---
permalink: data-protection/dpo-systems-feature-enhancements-reference.html 
sidebar: sidebar 
keywords: dpo, systems, feature, enhancements, snapmirror, dp optimized, optimised, backoff, back off, deduplication, deduplicate, snapshot blocks, donors, compact, flexvol, license 
summary: 从 ONTAP 9.6 开始，安装 DP_Optimized （ DPO ）许可证后，支持的最大 FlexVol 卷数将增加。从ONTAP 9.4开始、具有DPO许可证的系统支持SnapMirror回退、跨卷后台重复数据删除、使用Snapshot块作为源以及数据缩减。 
---
= DPO 系统功能增强功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
从 ONTAP 9.6 开始，安装 DP_Optimized （ DPO ）许可证后，支持的最大 FlexVol 卷数将增加。从ONTAP 9.4开始、具有DPO许可证的系统支持SnapMirror回退、跨卷后台重复数据删除、使用Snapshot块作为源以及数据缩减。

从 ONTAP 9.6 开始，二级系统或数据保护系统上支持的最大 FlexVol 卷数已增加，使您可以将每个节点的 FlexVol 卷扩展到 2 ， 500 个，或者在故障转移模式下最多扩展到 5 ， 000 个。可通过启用FlexVol卷的增加 link:https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-licensing-concept.html#data-protection-optimized-license["DP_Optimized(DPO)许可证"]。答 link:https://docs.netapp.com/us-en/ontap/system-admin/manage-license-task.html#view-details-about-a-license["SnapMirror 许可证"] 源节点和目标节点上仍然需要。

从 ONTAP 9.4 开始，对 DPO 系统进行了以下增强功能：

* SnapMirror 回退：在 DPO 系统中，复制流量的优先级与客户端工作负载的优先级相同。
+
默认情况下， DPO 系统会禁用 SnapMirror 回退。

* 卷后台重复数据删除和跨卷后台重复数据删除：在 DPO 系统中启用卷后台重复数据删除和跨卷后台重复数据删除。
+
您可以运行 `storage aggregate efficiency cross-volume-dedupe start -aggregate _aggregate_name_ -scan-old-data true` 命令删除现有数据的重复数据。最佳做法是在非高峰时段运行命令，以减少对性能的影响。

* 通过使用 Snapshot 块作为源来提高节省量：活动文件系统中不可用但捕获在 Snapshot 副本中的数据块将用作卷重复数据删除的源。
+
新数据可以与捕获在 Snapshot 副本中的数据进行重复数据删除，从而也可以有效地共享 Snapshot 块。增加的源空间可节省更多空间，尤其是在卷包含大量 Snapshot 副本时。

* 数据缩减：默认情况下， DPO 卷会启用数据缩减。

