---
permalink: data-protection/exclude-lifs-svm-replication-task.html 
sidebar: sidebar 
keywords: lifs, network, settings, svm, replication 
summary: 如果源 SVM 和目标 SVM 位于不同子网中，则可以使用 snapmirror policy create 命令的 -discard-configs network 选项从 SVM 复制中排除 LIF 和相关网络设置。 
---
= 从 SVM 复制中排除 LIF 和相关网络设置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果源和目标SVM位于不同子网中、则可以使用 `-discard-configs network` 的选项 `snapmirror policy create` 用于从SVM复制中排除LIP和相关网络设置的命令。

.您需要的内容
源和目标集群以及 SVM 必须建立对等关系。

有关详细信息，请参见 link:../peering/create-cluster-relationship-93-later-task.html["创建集群对等关系"] 和 link:../peering/create-intercluster-svm-peer-relationship-93-later-task.html["创建 SVM 集群间对等关系"]。

.关于此任务
。 `-identity-preserve` 的选项 `snapmirror create` 命令必须设置为 `true` 创建SVM复制关系时。

有关完整的命令语法，请参见手册页。

.步骤
. 创建目标 SVM ：
+
`vserver create -vserver _SVM_ -subtype dp-destination`

+
SVM 名称在源集群和目标集群中必须是唯一的。

+
以下示例将创建一个名为的目标SVM `svm_backup`：

+
[listing]
----
cluster_dst:> vserver create -vserver svm_backup -subtype dp-destination
----
. 在目标集群中、使用创建SVM对等关系 `vserver peer create` 命令：
+
有关详细信息，请参见 link:../peering/create-intercluster-svm-peer-relationship-93-later-task.html["创建 SVM 集群间对等关系"]。

. 创建作业计划：
+
`job schedule cron create -name _job_name_ -month _month_ -dayofweek _day_of_week_ -day _day_of_month_ -hour _hour_ -minute _minute_`

+
适用于 `-month`， `-dayofweek`，和 `-hour`，您可以指定 `all` 以分别每月、每周的某一天和每小时运行此作业。

+
[NOTE]
====
SVM SnapMirror关系中FlexVol 卷支持的最小计划(RPO)为15分钟。SVM SnapMirror关系中FlexGroup 卷支持的最小计划(RPO)为30分钟。

====
+
以下示例将创建一个名为的作业计划 `my_weekly` 在星期六凌晨3：00运行：

+
[listing]
----
cluster_dst::> job schedule cron create -name my_weekly -dayofweek "Saturday" -hour 3 -minute 0
----
. 创建自定义复制策略：
+
`snapmirror policy create -vserver _SVM_ -policy _policy_ -type async-mirror|vault|mirror-vault -comment _comment_ -tries transfer_tries -transfer-priority low|normal -is-network-compression-enabled true|false -discard-configs network`

+
有关完整的命令语法，请参见手册页。

+
以下示例将为 SnapMirror 灾难恢复创建一个自定义复制策略，该策略会排除 LIF ：

+
[listing]
----
cluster_dst::> snapmirror policy create -vserver svm1 -policy DR_exclude_LIFs -type async-mirror -discard-configs network
----
+
以下示例将为统一复制创建一个自定义复制策略，该策略会排除 LIF ：

+
[listing]
----
cluster_dst::> snapmirror policy create -vserver svm1 -policy unified_exclude_LIFs -type mirror-vault -discard-configs network
----
+
[NOTE]
====
请考虑在源集群上创建相同的自定义SnapMirror策略、以供将来进行故障转移和故障恢复时使用。

====
. 从目标 SVM 或目标集群运行以下命令以创建复制关系：
+
`snapmirror create -source-path _SVM_: -destination-path _SVM_: -type DP|XDP -schedule _schedule_ -policy _policy_ -identity-preserve true|false -discard-configs true|false`

+
[NOTE]
====
您必须在中的SVM名称后面输入冒号(：) `-source-path` 和 `-destination-path` 选项请参见以下示例：

====
+
以下示例将创建一个 SnapMirror 灾难恢复关系，此关系会排除 LIF ：

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1: -destination-path svm_backup: -type XDP -schedule my_weekly -policy DR_exclude_LIFs -identity-preserve true
----
+
以下示例将创建一个 SnapMirror 统一复制关系，此关系会排除 LIF ：

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1: -destination-path svm_backup: -type XDP -schedule my_weekly -policy unified_exclude_LIFs -identity-preserve true -discard-configs true
----
. 停止目标 SVM ：
+
`vserver stop`

+
`_SVM name_`

+
以下示例将停止名为svm_backup的目标SVM：

+
[listing]
----
cluster_dst::> vserver stop -vserver svm_backup
----
. 从目标 SVM 或目标集群初始化复制关系：
+
`snapmirror initialize -source-path _SVM_: -destination-path _SVM_:`

+
有关完整的命令语法，请参见手册页。

+
以下示例将初始化源、 `svm1` 和目标、 `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror initialize -source-path svm1: -destination-path svm_backup:
----


.完成后
您必须在目标 SVM 上配置网络和协议，以便在发生灾难时进行数据访问。
