---
permalink: data-protection/manage-storage-efficiency-task.html 
sidebar: sidebar 
keywords: snapmirror, efficiency, manage, storage, snap mirror, compression, compress, postprocess, post-process, update relationship, volume 
summary: 要使用SnapMirror在源卷和目标卷之间保持存储效率、您需要在目标卷上禁用后处理压缩 
---
= 管理ONTAP SnapMirror卷上的存储效率
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
除非在目标卷上启用了后处理数据压缩、否则SnapMirror会保留源卷和目标卷上的存储效率。在这种情况下、目标卷上的所有存储效率都将丢失。要更正此问题、您需要在目标卷上禁用后处理压缩、手动更新此关系、然后重新启用存储效率。

.关于此任务
您可以使用 `volume efficiency show`命令确定是否已在卷上启用效率。有关的详细信息 `volume efficiency show`，请参见link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-show.html["ONTAP 命令参考"^]。

您可以通过查看 SnapMirror 审核日志并找到传输问题描述来检查 SnapMirror 是否保持存储效率。如果传输说明显示 `transfer_desc=Logical Transfer with Storage Efficiency`、则表示SnapMirror正在保持存储效率。如果传输说明显示 `transfer_desc=Logical Transfer`、则表示SnapMirror不会保持存储效率。例如：

[listing]
----
Fri May 22 02:13:02 CDT 2020 ScheduledUpdate[May 22 02:12:00]:cc0fbc29-b665-11e5-a626-00a09860c273 Operation-Uuid=39fbcf48-550a-4282-a906-df35632c73a1 Group=none Operation-Cookie=0 action=End source=<sourcepath> destination=<destpath> status=Success bytes_transferred=117080571 network_compression_ratio=1.0:1 transfer_desc=Logical Transfer - Optimized Directory Mode
----
.开始之前
* 源和目标集群以及 SVM 必须建立对等关系。
+
https://docs.netapp.com/us-en/ontap-system-manager-classic/peering/index.html["集群和 SVM 对等"^]

* 您必须在目标卷上禁用后处理压缩。
* 使用存储进行逻辑传输：从ONTAP 9.3开始、不再需要手动更新即可重新启用存储效率。如果 SnapMirror 检测到已禁用后处理压缩，则会在下次计划更新时自动重新启用存储效率。源和目标都必须运行 ONTAP 9.3 。
* 从 ONTAP 9.3 开始，在将目标卷设为可写后， AFF 系统对存储效率设置的管理方式与 FAS 系统不同：
+
** 在使用命令将目标卷设置为可写后 `snapmirror break`、卷上的缓存策略会自动设置为"`auto`"(默认设置)。有关的详细信息 `snapmirror break`，请参见link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-break.html["ONTAP 命令参考"^]。
+
[NOTE]
====
此行为仅适用于 FlexVol 卷，不适用于 FlexGroup 卷。

====
** 重新同步时，缓存策略会自动设置为 "`none` " ，并且无论您的原始设置如何，重复数据删除和实时压缩都会自动禁用。您必须根据需要手动修改这些设置。




[NOTE]
====
启用存储效率后手动更新可能会非常耗时。您可能希望在非高峰时段运行此操作。

====
.步骤
. 更新复制关系并重新启用存储效率：
+
[source, cli]
----
snapmirror update -source-path <SVM:volume>|<cluster://SVM/volume>, ... -destination-path <SVM:volume>|<cluster://SVM/volume>, ... -enable-storage-efficiency true
----
+
有关的详细信息 `snapmirror update`，请参见link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-update.html["ONTAP 命令参考"^]。

+
[NOTE]
====
您必须从目标 SVM 或目标集群运行此命令。如果源和目标上不存在通用快照、则命令将失败。使用 `snapmirror initialize` 重新初始化此关系。

====
+
以下示例将更新源卷之间的关系 `volA` 开启 `svm1` 和目标卷 `volA_dst` 开启 `svm_backup`并重新启用存储效率：

+
[listing]
----
cluster_dst::> snapmirror update -source-path svm1:volA -destination-path svm_backup:volA_dst -enable-storage-efficiency true
----

