---
permalink: data-protection/preserve-snapshot-copy-primary-source-volume-task.html 
sidebar: sidebar 
keywords: ensure, snapshot, copy, mirror-vault, deployment 
summary: 您可以使用SnapMirror快照所有者create命令在镜像-存储部署中的二级系统上保留带标签的快照。这样可确保存在用于更新存储关系的通用快照。 
---
= 使用ONTAP确保在镜像-存储部署中创建通用快照
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `snapmirror snapshot-owner create`命令在镜像-存储部署中的二级系统上保留带标签的快照。这样可确保存在用于更新存储关系的通用快照。有关的详细信息 `snapmirror snapshot-owner create`，请参见link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-snapshot-owner-create.html["ONTAP 命令参考"^]。

.关于此任务
如果您使用组合镜像-存储扇出或级联部署、则应注意、如果源卷和目标卷上不存在通用快照、更新将失败。

对于镜像-存储扇出或级联部署中的镜像关系来说、这绝不是问题、因为SnapMirror始终会在执行更新之前创建源卷的快照。

但是、存储关系可能存在此问题、因为SnapMirror不会在更新存储关系时创建源卷的快照。您需要使用 `snapmirror snapshot-owner create`来确保存储关系的源和目标上至少有一个通用快照。

.步骤
. 在源卷上、为要保留的带标签快照分配一个所有者：
+
`snapmirror snapshot-owner create -vserver <SVM> -volume <volume> -snapshot <snapshot> -owner <owner>`

+
以下示例将分配 `ApplicationA`为快照的所有者 `snap1`：

+
[listing]
----
clust1::> snapmirror snapshot-owner create -vserver vs1 -volume vol1
-snapshot snap1 -owner ApplicationA
----
. 更新镜像关系，如中所述 link:update-replication-relationship-manual-task.html["手动更新复制关系"]。
+
或者，您也可以等待按计划更新镜像关系。

. 将带标签的快照传输到存储目标：
+
`snapmirror update -source-path <SVM:volume>|<cluster://SVM/volume>, ... -destination-path <SVM:volume>|<cluster://SVM/volume>, ... -source-snapshot snapshot`

+
有关的详细信息 `snapmirror update`，请参见link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-update.html["ONTAP 命令参考"^]。

+
以下示例将传输 `snap1`快照::
+
--
[listing]
----
clust1::> snapmirror update -vserver vs1 -volume vol1
-source-snapshot snap1
----
更新存储关系时、带标签的快照将保留。

--


. 在源卷上、从带标签的快照中删除所有者：
+
`snapmirror snapshot-owner delete -vserver _SVM_ -volume _volume_ -snapshot _snapshot_ -owner _owner_`

+
以下示例将删除 `ApplicationA`作为快照的所有者 `snap1`：

+
[listing]
----
clust1::> snapmirror snapshot-owner delete -vserver vs1 -volume vol1
-snapshot snap1 -owner ApplicationA
----
+
有关的详细信息 `snapmirror snapshot-owner delete`，请参见link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-snapshot-owner-delete.html["ONTAP 命令参考"^]。


