---
permalink: data-protection/preserve-snapshot-copy-primary-source-volume-task.html 
sidebar: sidebar 
keywords: ensure, snapshot, copy, mirror-vault, deployment 
summary: 您可以使用 snapmirror snapshot-owner create 命令在镜像 - 存储部署中的二级系统上保留带标签的 Snapshot 副本。这样可确保存在用于更新存储关系的通用 Snapshot 副本。 
---
= 确保在镜像 - 存储部署中使用通用 Snapshot 副本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `snapmirror snapshot-owner create` 命令以在镜像-存储部署中的二级系统上保留带标签的Snapshot副本。这样可确保存在用于更新存储关系的通用 Snapshot 副本。

.关于此任务
如果您使用组合镜像 - 存储扇出或级联部署，则应记住，如果源卷和目标卷上不存在通用 Snapshot 副本，则更新将失败。

在镜像 - 存储扇出或级联部署中，这绝不是镜像关系的问题描述，因为 SnapMirror 始终会在执行更新之前创建源卷的 Snapshot 副本。

但是，它可能是存储关系的问题描述，因为 SnapMirror 在更新存储关系时不会创建源卷的 Snapshot 副本。您需要使用 `snapmirror snapshot-owner create` 确保存储关系的源和目标上至少有一个通用Snapshot副本。

.步骤
. 在源卷上，为要保留的带标签 Snapshot 副本分配一个所有者：
+
`snapmirror snapshot-owner create -vserver _SVM_ -volume _volume_ -snapshot _snapshot_ -owner _owner_`

+
以下示例将分配 `ApplicationA` 作为的所有者 `snap1` Snapshot副本：

+
[listing]
----
clust1::> snapmirror snapshot-owner create -vserver vs1 -volume vol1
-snapshot snap1 -owner ApplicationA
----
. 更新镜像关系，如中所述 link:update-replication-relationship-manual-task.html["手动更新复制关系"]。
+
或者，您也可以等待按计划更新镜像关系。

. 将带标签的 Snapshot 副本传输到存储目标：
+
`snapmirror update -source-path _SVM:volume_|_cluster://SVM/volume_, ... -destination-path _SVM:volume_|_cluster://SVM/volume_, ... -source-snapshot snapshot`

+
有关完整的命令语法，请参见手册页。

+
以下示例将传输 `snap1` Snapshot 副本::
+
--
[listing]
----
clust1::> snapmirror update -vserver vs1 -volume vol1
-source-snapshot snap1
----
更新存储关系时，标记的 Snapshot 副本将保留下来。

--


. 在源卷上，从标记的 Snapshot 副本中删除所有者：
+
`snapmirror snapshot-owner delete -vserver _SVM_ -volume _volume_ -snapshot _snapshot_ -owner _owner_`

+
以下示例将删除 `ApplicationA` 作为的所有者 `snap1` Snapshot副本：

+
[listing]
----
clust1::> snapmirror snapshot-owner delete -vserver vs1 -volume vol1
-snapshot snap1 -owner ApplicationA
----

