---
permalink: data-protection/reactivate-original-source-volume-task.html 
sidebar: sidebar 
keywords: reactivate, original, source, volume 
summary: 当您不再需要从目标提供数据时，可以在源卷和目标卷之间重新建立初始数据保护关系。 
---
= 重新激活初始ONTAP SnapMirror源卷
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
当您不再需要从目标提供数据时，可以在源卷和目标卷之间重新建立初始数据保护关系。

.关于此任务
* 以下操作步骤假定原始源卷中的基线完好无损。如果基线不完好，则必须在执行操作步骤之前创建并初始化提供数据的卷与原始源卷之间的关系。
* XDP SnapMirror 关系的后台准备和数据仓库阶段可能需要很长时间。在较长的一段时间内， SnapMirror 关系报告状态 " 正在准备 " 的情况并不少见。


.步骤
. 反转原始数据保护关系：
+
`snapmirror resync -source-path _SVM:volume_ -destination-path _SVM:volume_`

+
有关的详细信息 `snapmirror resync`，请参见link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-resync.html["ONTAP 命令参考"^]。

+
[NOTE]
====
您必须从原始源SVM或原始源集群运行此命令。虽然重新同步不需要基线传输，但它可能非常耗时。您可能希望在非高峰时段运行重新同步。如果源和目标上不存在通用快照、则命令将失败。使用 `snapmirror initialize` 重新初始化此关系。有关的详细信息 `snapmirror initialize`，请参见link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-initialize.html["ONTAP 命令参考"^]。

====
+
以下示例将反转初始源卷之间的关系： `volA` 开启 `svm1`和提供数据的卷、 `volA_dst` 开启 `svm_backup`：

+
[listing]
----
cluster_src::> snapmirror resync -source-path svm_backup:volA_dst -destination-path svm1:volA
----
. 准备好重新建立对原始源的数据访问后、停止对原始目标卷的访问。要执行此操作、一种方法是停止原始目标SVM：
+
`vserver stop -vserver _SVM_`

+
[NOTE]
====
您必须从原始目标SVM或原始目标集群运行此命令。此命令将停止用户对整个原始目标SVM的访问。您可能希望使用其他方法停止对原始目标卷的访问。

====
+
以下示例将停止初始目标SVM：

+
[listing]
----
cluster_dst::> vserver stop svm_backup
----
+
有关的详细信息 `vserver stop`，请参见link:https://docs.netapp.com/us-en/ontap-cli/vserver-stop.html["ONTAP 命令参考"^]。

. 更新已反转的关系：
+
`snapmirror update -source-path _SVM:volume_ -destination-path _SVM:volume_`

+
[NOTE]
====
您必须从原始源SVM或原始源集群运行此命令。

====
+
以下示例将更新提供数据的卷之间的关系、 `volA_dst` 开启 `svm_backup`和原始源卷、 `volA` 开启 `svm1`：

+
[listing]
----
cluster_src::> snapmirror update -source-path svm_backup:volA_dst -destination-path svm1:volA
----
+
有关的详细信息 `snapmirror update`，请参见link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-update.html["ONTAP 命令参考"^]。

. 从初始源SVM或初始源集群停止已反转关系的计划传输：
+
`snapmirror quiesce -source-path _SVM:volume_ -destination-path _SVM:volume_`

+
[NOTE]
====
您必须从原始源SVM或原始源集群运行此命令。

====
+
以下示例将停止初始目标卷之间的计划传输、 `volA_dst` 开启 `svm_backup`和原始源卷、 `volA` 开启 `svm1`：

+
[listing]
----
cluster_src::> snapmirror quiesce -source-path svm_backup:volA_dst -destination-path svm1:volA
----
+
有关的详细信息 `snapmirror quiesce`，请参见link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-quiesce.html["ONTAP 命令参考"^]。

. 当最终更新完成且关系状态指示"已暂停"时、从原始源SVM或原始源集群运行以下命令以中断已反转的关系：
+
`snapmirror break -source-path _SVM:volume_ -destination-path _SVM:volume_`

+
[NOTE]
====
您必须从原始源SVM或源集群运行此命令。

====
+
以下示例将中断初始目标卷之间的关系、 `volA_dst` 开启 `svm_backup`和原始源卷、 `volA` 开启 `svm1`：

+
[listing]
----
cluster_scr::> snapmirror break -source-path svm_backup:volA_dst -destination-path svm1:volA
----
+
有关的详细信息 `snapmirror break`，请参见link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-break.html["ONTAP 命令参考"^]。

. 从原始源SVM或原始源集群中、删除已反转的数据保护关系：
+
`snapmirror delete -source-path _SVM:volume_ -destination-path _SVM:volume_`

+
[NOTE]
====
您必须从原始源SVM或原始源集群运行此命令。

====
+
以下示例将删除初始源卷之间的已反转关系： `volA` 开启 `svm1`和提供数据的卷、 `volA_dst` 开启 `svm_backup`：

+
[listing]
----
cluster_src::> snapmirror delete -source-path svm_backup:volA_dst -destination-path svm1:volA
----
+
有关的详细信息 `snapmirror delete`，请参见link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-delete.html["ONTAP 命令参考"^]。

. 从初始目标SVM或初始目标集群释放已反转的关系。
+
`snapmirror release -source-path _SVM:volume_ -destination-path _SVM:volume_`

+
[NOTE]
====
您必须从原始目标SVM或原始目标集群运行此命令。

====
+
以下示例将释放初始目标卷之间的已反转关系、 `volA_dst` 开启 `svm_backup`和原始源卷、 `volA` 开启 `svm1`：

+
[listing]
----
cluster_dst::> snapmirror release -source-path svm_backup:volA_dst -destination-path svm1:volA
----
+
有关的详细信息 `snapmirror release`，请参见link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-release.html["ONTAP 命令参考"^]。

. 从原始目标重新建立初始数据保护关系：
+
`snapmirror resync -source-path _SVM:volume_ -destination-path _SVM:volume_`

+
以下示例将重新建立初始源卷之间的关系、 `volA` 开启 `svm1`和初始目标卷、 `volA_dst` 开启 `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror resync -source-path svm1:volA -destination-path svm_backup:volA_dst
----
+
有关的详细信息 `snapmirror resync`，请参见link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-resync.html["ONTAP 命令参考"^]。

. 如果需要、启动初始目标SVM：
+
`vserver start -vserver _SVM_`

+
以下示例将启动初始目标SVM：

+
[listing]
----
cluster_dst::> vserver start svm_backup
----
+
有关的详细信息 `vserver start`，请参见link:https://docs.netapp.com/us-en/ontap-cli/vserver-start.html["ONTAP 命令参考"^]。



.完成后
使用 `snapmirror show` 命令以验证是否已创建SnapMirror关系。

有关的详细信息 `snapmirror show`，请参见link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-show.html["ONTAP 命令参考"^]。
