---
permalink: data-protection/reactivate-original-source-svm-task.html 
sidebar: sidebar 
keywords: reactivate, original, source, svm, quick resync, resynchronize, reverse resync 
summary: 当您不再需要从目标提供数据时，可以在源和目标 SVM 之间重新建立初始数据保护关系。在卷复制方面，操作步骤与操作步骤大致相同，但有一个例外。在重新激活源 SVM 之前，必须停止目标 SVM 。 
---
= 重新激活原始源 SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
当您不再需要从目标提供数据时，可以在源和目标 SVM 之间重新建立初始数据保护关系。在卷复制方面，操作步骤与操作步骤大致相同，但有一个例外。在重新激活源 SVM 之前，必须停止目标 SVM 。

.您需要的内容
如果在提供目标卷数据时增加了目标卷的大小，则在重新激活源卷之前，应手动增加原始源卷上的最大自动大小，以确保其可以充分增长。

link:destination-volume-grows-automatically-concept.html["目标卷自动增长时"]

.关于此任务
从ONTAP 9.11.1开始、您可以在执行SVM DR关系的反向重新同步时、使用`snapmirror resync`命令的`-quast-resync true`选项来缩短灾难恢复演练期间的重新同步时间。快速重新同步可以绕过数据仓库重建和还原操作、从而缩短恢复生产所需的时间。


NOTE: 快速重新同步不会保留目标卷的存储效率。启用快速重新同步可能会增加目标卷使用的卷空间。

此操作步骤假定原始源卷中的基线完好无损。如果基线不完好，则必须在执行操作步骤之前创建并初始化提供数据的卷与原始源卷之间的关系。

有关命令的完整命令语法，请参见手册页。

.步骤
. 从原始源 SVM 或原始源集群中，使用与原始 SVM DR 关系相同的配置，策略和身份保留设置创建反向 SVM DR 关系：
+
`snapmirror create -source-path SVM ： -destination-path SVM ：`

+
[NOTE]
====
您必须在 ` 源路径` 和 ` 目标路径` 选项中的 SVM 名称后面输入冒号（：）。请参见以下示例。

====
+
以下示例将在提供数据的 SVM `svm_backup` 和原始源 SVM `svm1` 之间创建关系：

+
[listing]
----
cluster_src::> snapmirror create -source-path svm_backup: -destination-path svm1:
----
. 从原始源 SVM 或原始源集群运行以下命令以反转数据保护关系：
+
`snapmirror resync -source-path _svm_ ： -destination-path _svm_ ：`

+
[NOTE]
====
您必须在 ` 源路径` 和 ` 目标路径` 选项中的 SVM 名称后面输入冒号（：）。请参见以下示例。

====
+
虽然重新同步不需要基线传输，但它可能非常耗时。您可能希望在非高峰时段运行重新同步。

+
[NOTE]
====
如果源和目标上不存在通用 Snapshot 副本，则此命令将失败。使用 `snapmirror initialize` 重新初始化此关系。

====
+
以下示例将反转原始源 SVM `svm1` 与要提供数据的 SVM `svm_backup` 之间的关系：

+
[listing]
----
cluster_src::> snapmirror resync -source-path svm_backup: -destination-path svm1:
----
+
使用-quick重新同步选项的示例：

+
[listing]
----
cluster_src::> snapmirror resync -source-path svm_backup: -destination-path svm1: -quick-resync true
----
. 准备好重新建立对原始源 SVM 的数据访问后，请停止原始目标 SVM 以断开当前连接到原始目标 SVM 的所有客户端。
+
`vserver stop -vserver _svm_`

+
以下示例将停止当前正在提供数据的原始目标 SVM ：

+
[listing]
----
cluster_dst::> vserver stop svm_backup
----
. 使用 `vserver show` 命令验证原始目标 SVM 是否处于 stopped 状态。
+
[listing]
----
cluster_dst::> vserver show
                                  Admin      Operational Root
Vserver        Type    Subtype    State      State       Volume     Aggregate
--------       ------- ---------- ---------- ----------- ---------- ----------
svm_backup     data    default    stopped    stopped     rv         aggr1
----
. 从初始源 SVM 或初始源集群运行以下命令，对已反转的关系执行最终更新，以便将所有更改从初始目标 SVM 传输到初始源 SVM ：
+
`snapmirror update -source-path _svm_ ： -destination-path _svm_ ：`

+
[NOTE]
====
您必须在 ` 源路径` 和 ` 目标路径` 选项中的 SVM 名称后面输入冒号（：）。请参见以下示例。

====
+
以下示例更新了要提供数据的初始目标 SVM `svm_backup` 和初始源 SVM `svm1` 之间的关系：

+
[listing]
----
cluster_src::> snapmirror update -source-path svm_backup: -destination-path svm1:
----
. 从初始源 SVM 或初始源集群运行以下命令，以停止已反转关系的计划传输：
+
`snapmirror quiesce -source-path _svm_ ： -destination-path _svm_ ：`

+
[NOTE]
====
您必须在 ` 源路径` 和 ` 目标路径` 选项中的 SVM 名称后面输入冒号（：）。请参见以下示例。

====
+
以下示例将停止正在提供数据的 SVM `svm_backup` 和原始 SVM `svm1` 之间的计划传输：

+
[listing]
----
cluster_src::> snapmirror quiesce -source-path svm_backup: -destination-path svm1:
----
. 当最终更新完成且关系状态指示 " 已暂停 " 时，从原始源 SVM 或原始源集群运行以下命令以中断已反转的关系：
+
`snapmirror break -source-path _svm_ ： -destination-path _svm_ ：`

+
[NOTE]
====
您必须在 ` 源路径` 和 ` 目标路径` 选项中的 SVM 名称后面输入冒号（：）。请参见以下示例。

====
+
以下示例将中断提供数据的初始目标 SVM `svm_backup` 和初始源 SVM `svm1` 之间的关系：

+
[listing]
----
cluster_src::> snapmirror break -source-path svm_backup: -destination-path svm1:
----
. 如果原始源 SVM 先前已停止，请从原始源集群启动原始源 SVM ：
+
`vserver start -vserver _svm_`

+
以下示例将启动初始源 SVM ：

+
[listing]
----
cluster_src::> vserver start svm1
----
. 从初始目标 SVM 或初始目标集群重新建立初始数据保护关系：
+
`snapmirror resync -source-path _svm_ ： -destination-path _svm_ ：`

+
[NOTE]
====
您必须在 ` 源路径` 和 ` 目标路径` 选项中的 SVM 名称后面输入冒号（：）。请参见以下示例。

====
+
以下示例将重新建立初始源 SVM `svm1` 和初始目标 SVM `svm_backup` 之间的关系：

+
[listing]
----
cluster_dst::> snapmirror resync -source-path svm1: -destination-path svm_backup:
----
. 从原始源 SVM 或原始源集群运行以下命令，以删除已反转的数据保护关系：
+
`snapmirror delete -source-path _svm_ ： -destination-path _svm_ ：`

+
[NOTE]
====
您必须在 ` 源路径` 和 ` 目标路径` 选项中的 SVM 名称后面输入冒号（：）。请参见以下示例。

====
+
以下示例将删除初始目标 SVM `svm_backup` 和初始源 SVM `svm1` 之间的已反转关系：

+
[listing]
----
cluster_src::> snapmirror delete -source-path svm_backup: -destination-path svm1:
----
. 从原始目标 SVM 或原始目标集群释放反转的数据保护关系：
+
`snapmirror release -source-path SVM ： -destination-path SVM ：`

+
[NOTE]
====
您必须在 ` 源路径` 和 ` 目标路径` 选项中的 SVM 名称后面输入冒号（：）。请参见以下示例。

====
+
以下示例将释放初始目标 SVM SVM_backup 和初始源 SVM `svm1` 之间的反转关系

+
[listing]
----
cluster_dst::> snapmirror release -source-path svm_backup: -destination-path svm1:
----


.完成后
使用 `snapmirror show` 命令验证是否已创建 SnapMirror 关系。有关完整的命令语法，请参见手册页。
