---
permalink: data-protection/reactivate-original-source-volume-task.html 
sidebar: sidebar 
keywords: reactivate, original, source, volume 
summary: 当您不再需要从目标提供数据时，可以在源卷和目标卷之间重新建立初始数据保护关系。 
---
= 重新激活原始源卷
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
当您不再需要从目标提供数据时，可以在源卷和目标卷之间重新建立初始数据保护关系。

.关于此任务
* 以下操作步骤假定原始源卷中的基线完好无损。如果基线不完好，则必须在执行操作步骤之前创建并初始化提供数据的卷与原始源卷之间的关系。
* XDP SnapMirror 关系的后台准备和数据仓库阶段可能需要很长时间。在较长的一段时间内， SnapMirror 关系报告状态 " 正在准备 " 的情况并不少见。


.步骤
. 删除原始数据保护关系：
+
`snapmirror delete -source-path _SVM ： volume_|_cluster ： //svm/volume_ ， ... -destination-path _sVM ： volume_|_cluster ： //svm/volume_ ， ...`

+
有关完整的命令语法，请参见手册页。

+
您必须从目标 SVM 或目标集群运行此命令。

+
以下示例将删除原始源卷 `volA` on `svm1` 与您提供数据的卷 `vola_dst` on `svm_backup` 之间的关系：

+
[listing]
----
cluster_dst::> snapmirror delete -source-path svm1:volA -destination-path svm_backup:volA_dst
----
. 反转原始数据保护关系：
+
`snapmirror resync -source-path _SVM ： volume_|_cluster ： //svm/volume_ ， ... -destination-path _sVM ： volume_|_cluster ： //svm/volume_ ， ...`

+
有关完整的命令语法，请参见手册页。

+
您必须从目标 SVM 或目标集群运行此命令。虽然重新同步不需要基线传输，但它可能非常耗时。您可能希望在非高峰时段运行重新同步。

+
以下示例将反转原始源卷 `volA` on `svm1` 和您提供数据的卷 `vola_dst` on `svm_backup` 之间的关系：

+
[listing]
----
cluster_dst::> snapmirror resync -source-path svm_backup:volA_dst -destination-path svm1:volA
----
. 停止已反转关系的源 SVM ：
+
`vserver stop -vserver _svm_`

+
有关完整的命令语法，请参见手册页。

+
以下示例将停止已反转关系的源 SVM ：

+
[listing]
----
cluster_src::> vserver stop svm_backup
----
. 更新已反转的关系：
+
`snapmirror update -source-path _svm ： volume_|_cluster ： //svm/volume_ ， ... -destination-path _sVM ： volume_|_cluster ： //svm/volume_ ， ...`

+
有关完整的命令语法，请参见手册页。

+
[NOTE]
====
您必须从目标 SVM 或目标集群运行此命令。如果源和目标上不存在通用 Snapshot 副本，则此命令将失败。使用 `snapmirror initialize` 重新初始化此关系。

====
+
以下示例更新了提供数据的卷 `vola_dst` on `svm_backup` 和原始源卷 `vola` on `svm1` 之间的关系：

+
[listing]
----
cluster_dst::> snapmirror update -source-path svm_backup:volA_dst -destination-path svm1:volA
----
. 停止已反转关系的计划传输：
+
`snapmirror quiesce -source-path _SVM ： volume_|_cluster ： //svm/volume_ ， ... -destination-path _sVM ： volume_|_cluster ： //svm/volume_ ， ...`

+
有关完整的命令语法，请参见手册页。

+
[NOTE]
====
您必须从目标 SVM 或目标集群运行此命令。

====
+
以下示例将停止从 `vola_dst` on `svm_backup` 提供数据的卷与原始源卷 `vola` on `svm1` 之间的计划传输：

+
[listing]
----
cluster_dst::> snapmirror quiesce -source-path svm_backup:volA_dst -destination-path svm1:volA
----
. 停止已反转关系的正在进行的传输：
+
`snapmirror abort -source-path _svm ： volume_|_cluster ： //svm/volume_ ， ... -destination-path _sVM ： volume_|_cluster ： //svm/volume_ ， ...`

+
有关完整的命令语法，请参见手册页。

+
[NOTE]
====
您必须从目标 SVM 或目标集群运行此命令。

====
+
以下示例将停止正在提供数据的卷 `vola_dst` on `svm_backup` 和原始源卷 `vola` on `svm1` 之间的当前传输：

+
[listing]
----
cluster_dst::> snapmirror abort -source-path svm_backup:volA_dst -destination-path svm1:volA
----
. 中断已反转的关系：
+
`snapmirror break -source-path _svm ： volume_|_cluster ： //svm/volume_ ， ... -destination-path _sVM ： volume_|_cluster ： //svm/volume_ ， ...`

+
有关完整的命令语法，请参见手册页。

+
[NOTE]
====
您必须从目标 SVM 或目标集群运行此命令。

====
+
以下示例将中断提供数据的卷 `vola_dst` on `svm_backup` 和原始源卷 `vola` on `svm1` 之间的关系：

+
[listing]
----
cluster_dst::> snapmirror break -source-path svm_backup:volA_dst -destination-path svm1:volA
----
. 启动初始源 SVM ：
+
`vserver start -vserver _svm_`

+
有关完整的命令语法，请参见手册页。

+
以下示例将启动初始源 SVM ：

+
[listing]
----
cluster_dst::> vserver start svm1
----
. 删除已反转的数据保护关系：
+
`snapmirror delete -source-path _SVM ： volume_|_cluster ： //svm/volume_ ， ... -destination-path _sVM ： volume_|_cluster ： //svm/volume_ ， ...`

+
有关完整的命令语法，请参见手册页。

+
您必须从已反转关系的源 SVM 或源集群运行此命令。

+
以下示例将删除原始源卷 `volA` on `svm1` 与您提供数据的卷 `vola_dst` on `svm_backup` 之间的反转关系：

+
[listing]
----
cluster_src::> snapmirror delete -source-path svm_backup:volA_dst -destination-path svm1:volA
----
. 重新建立原始数据保护关系：
+
`snapmirror resync -source-path _SVM ： volume_|_cluster ： //svm/volume_ ， ... -destination-path _sVM ： volume_|_cluster ： //svm/volume_ ， ...`

+
有关完整的命令语法，请参见手册页。

+
以下示例将在初始源卷 `volA` on `svm1` 和初始目标卷 `vola_dst` on `svm_backup` 之间重新建立关系：

+
[listing]
----
cluster_dst::> snapmirror resync -source-path svm1:volA -destination-path svm_backup:volA_dst
----


使用 `snapmirror show` 命令验证是否已创建 SnapMirror 关系。有关完整的命令语法，请参见手册页。
