---
permalink: data-protection/replicate-entire-svm-config-task.html 
sidebar: sidebar 
keywords: replicate, entire, svm, storage vm, disaster, protection, configuration, snapmirror, snap mirror, replication, mirror vault policy, snapshot 
summary: '您可以创建SVM灾难恢复(SVM DR)关系、以便将一个SVM配置复制到另一个SVM配置。如果主站点发生灾难、您可以快速激活目标SVM。' 
---
= 复制整个ONTAP SVM配置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以创建SVM灾难恢复(SVM DR)关系、以便将一个SVM配置复制到另一个SVM配置。如果主站点发生灾难、您可以快速激活目标SVM。

.开始之前
源和目标集群以及 SVM 必须建立对等关系。
有关详细信息，请参见 link:../peering/create-cluster-relationship-93-later-task.html["创建集群对等关系"] 和 link:../peering/create-intercluster-svm-peer-relationship-93-later-task.html["创建 SVM 集群间对等关系"]。

有关此过程中所述命令的更多信息，请参见link:https://docs.netapp.com/us-en/ontap-cli/["ONTAP 命令参考"^]。

.关于此任务
此工作流假定您已在使用默认策略或自定义复制策略。

从ONTAP 9.9.1开始、当您使用镜像存储策略时、您可以在源和目标SVM上创建不同的快照策略、并且目标上的快照不会被源上的快照覆盖。有关详细信息，请参见 link:snapmirror-svm-replication-concept.html["了解 SnapMirror SVM 复制"]。

从目标完成此操作步骤。如果您需要创建新的保护策略、例如、当源Storage VM配置了SMB时、应创建此策略并使用*身份保留*选项。有关详细信息，请参见 link:create-custom-replication-policy-concept.html["创建自定义数据保护策略"]。

.步骤
您可以从System Manager或ONTAP命令行界面执行此任务。

[role="tabbed-block"]
====
.System Manager
--
. 在目标集群上，单击 * 保护 > 关系 * 。
. 在*关系*下，单击*保护*并选择* Storage VM (DR)*。
. 选择一个保护策略。如果创建了自定义保护策略，请将其选中，然后选择要复制的源集群和 Storage VM 。您也可以通过输入新的 Storage VM 名称来创建新的目标 Storage VM 。
. 如果需要、可更改目标设置以覆盖身份保留、并包括或排除网络接口和协议。
. 单击 * 保存 * 。


--
.命令行界面
--
. 创建目标 SVM ：
+
[source, cli]
----
vserver create -vserver <SVM_name> -subtype dp-destination
----
+
SVM 名称在源集群和目标集群中必须是唯一的。

+
以下示例将创建一个名为的目标SVM `svm_backup`：

+
[listing]
----
cluster_dst:> vserver create -vserver svm_backup -subtype dp-destination
----
+
有关的详细信息 `vserver create`，请参见link:https://docs.netapp.com/us-en/ontap-cli/vserver-create.html["ONTAP 命令参考"^]。

. 在目标集群中、使用创建SVM对等关系 `vserver peer create` 命令：
+
有关详细信息，请参见 link:../peering/create-intercluster-svm-peer-relationship-93-later-task.html["创建 SVM 集群间对等关系"]。

+
有关的详细信息 `vserver peer create`，请参见link:https://docs.netapp.com/us-en/ontap-cli/vserver-peer-create.html["ONTAP 命令参考"^]。

. 创建复制作业计划
+
[source, cli]
----
job schedule cron create -name <job_name> -month <month> -dayofweek <day_of_week> -day <day_of_month> -hour <hour> -minute <minute>
----
+
适用于 `-month`， `-dayofweek`，和 `-hour`，您可以指定 `all` 以分别每月、每周的某一天和每小时运行此作业。

+

NOTE: SVM SnapMirror关系中FlexVol 卷支持的最小计划(RPO)为15分钟。SVM SnapMirror关系中FlexGroup 卷支持的最小计划(RPO)为30分钟。

+
以下示例将创建一个名为的作业计划 `my_weekly` 在星期六凌晨3：00运行：

+
[listing]
----
cluster_dst::> job schedule cron create -name my_weekly -dayofweek saturday -hour 3 -minute 0
----
+
有关的详细信息 `job schedule cron create`，请参见link:https://docs.netapp.com/us-en/ontap-cli/job-schedule-cron-create.html["ONTAP 命令参考"^]。

. 从目标 SVM 或目标集群创建复制关系：
+
[source, cli]
----
snapmirror create -source-path <SVM_name>: -destination-path <SVM_name>: -type <DP|XDP> -schedule <schedule> -policy <policy> -identity-preserve true
----
+

NOTE: 您必须在中的SVM名称后面输入冒号(：) `-source-path` 和 `-destination-path` 选项

+
以下示例将使用默认值创建SnapMirror灾难恢复关系 `MirrorAllSnapshots` 策略：

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1: -destination-path svm_backup: -type XDP -schedule my_daily -policy MirrorAllSnapshots -identity-preserve true
----
+
以下示例将使用默认值创建统一复制关系 `MirrorAndVault` 策略：

+
[listing]
----
cluster_dst:> snapmirror create -source-path svm1: -destination-path svm_backup: -type XDP -schedule my_daily -policy MirrorAndVault -identity-preserve true
----
+
假设您创建了一个策略类型为的自定义策略 `async-mirror`下例将创建SnapMirror灾难恢复关系：

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1: -destination-path svm_backup: -type XDP -schedule my_daily -policy my_mirrored -identity-preserve true
----
+
假设您创建了一个策略类型为的自定义策略 `mirror-vault`，以下示例将创建统一复制关系：

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1: -destination-path svm_backup: -type XDP -schedule my_daily -policy my_unified -identity-preserve true
----
+
有关的详细信息 `snapmirror create`，请参见link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["ONTAP 命令参考"^]。

. 停止目标 SVM ：
+
[source, cli]
----
vserver stop -vserver <SVM_name>
----
+
以下示例将停止名为svm_backup的目标SVM：

+
[listing]
----
cluster_dst::> vserver stop -vserver svm_backup
----
+
有关的详细信息 `vserver stop`，请参见link:https://docs.netapp.com/us-en/ontap-cli/vserver-stop.html["ONTAP 命令参考"^]。

. 从目标 SVM 或目标集群初始化 SVM 复制关系：
+
[source, cli]
----
snapmirror initialize -source-path <SVM_name>: -destination-path <SVM_name>:
----
+

NOTE: 您必须在中的SVM名称后面输入冒号(：) `-source-path` 和 `-destination-path` 选项

+
以下示例将初始化源SVM之间的关系、 `svm1`和目标SVM、 `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror initialize -source-path svm1: -destination-path svm_backup:
----
+
有关的详细信息 `snapmirror initialize`，请参见link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-initialize.html["ONTAP 命令参考"^]。



--
====