---
permalink: data-protection/restore-volume-snapvault-backup-task.html 
sidebar: sidebar 
keywords: restore, content, volume, snapmirror, destination, snap mirror, snapshot, vault, snapvault, read-write, incremental 
summary: 您可以从 SnapMirror 目标卷中的 Snapshot 副本还原整个卷的内容。您可以将卷的内容还原到原始源卷或其他卷。 
---
= 从 SnapMirror 目标还原卷的内容
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以从 SnapMirror 目标卷中的 Snapshot 副本还原整个卷的内容。您可以将卷的内容还原到原始源卷或其他卷。

.关于此任务
还原操作的目标卷必须为以下卷之一：

* 读写卷，在这种情况下，如果源卷和目标卷具有通用 Snapshot 副本（通常情况下，还原到原始源卷时）， SnapMirror 将执行 _incremental restore" 。
+
[NOTE]
====
如果没有通用 Snapshot 副本，则此命令将失败。您不能将卷的内容还原到空的读写卷。

====
* 空数据保护卷，在这种情况下， SnapMirror 会执行 _baseline restore" ，其中指定的 Snapshot 副本及其引用的所有数据块都会传输到源卷。


还原卷的内容会造成系统中断。还原操作正在运行时、SnapVault主卷上不能运行SMB流量。

如果还原操作的目标卷已启用数据压缩，而源卷未启用数据压缩，请在目标卷上禁用数据压缩。还原操作完成后，您需要重新启用数据压缩。

在执行还原之前，为目标卷定义的任何配额规则都将被停用。您可以使用 `volume quota modify` 命令以在还原操作完成后重新激活配额规则。

.步骤
. 列出目标卷中的 Snapshot 副本：
+
`volume snapshot show -vserver _SVM_ -volume _volume_`

+
有关完整的命令语法，请参见手册页。

+
以下示例显示了上的Snapshot副本 `vserverB:secondary1` 目标：

+
[listing]
----

cluster_dst::> volume snapshot show -vserver vserverB -volume secondary1

Vserver     Volume      Snapshot                State    Size  Total% Used%
-------     ------      ---------- ----------- ------   -----  ------ -----
vserverB    secondary1  hourly.2013-01-25_0005  valid   224KB     0%    0%
                        daily.2013-01-25_0010   valid   92KB      0%    0%
                        hourly.2013-01-25_0105  valid   228KB     0%    0%
                        hourly.2013-01-25_0205  valid   236KB     0%    0%
                        hourly.2013-01-25_0305  valid   244KB     0%    0%
                        hourly.2013-01-25_0405  valid   244KB     0%    0%
                        hourly.2013-01-25_0505  valid   244KB     0%    0%

7 entries were displayed.
----
. 从 SnapMirror 目标卷中的 Snapshot 副本还原卷的内容：
+
`snapmirror restore -source-path _SVM:volume_|_cluster://SVM/volume_, ... -destination-path _SVM:volume_|_cluster://SVM/volume_, ... -source-snapshot _snapshot_`

+
有关完整的命令语法，请参见手册页。

+
[NOTE]
====
您必须从目标 SVM 或目标集群运行此命令。

====
+
以下命令将还原初始源卷的内容 `primary1` 从Snapshot副本 `daily.2013-01-25_0010` 在初始目标卷中 `secondary1`：

+
[listing]
----
cluster_dst::> snapmirror restore -source-path vserverB:secondary1 -destination-path vserverA:primary1 -source-snapshot daily.2013-01-25_0010

Warning: All data newer than Snapshot copy daily.2013-01-25_0010 on volume vserverA:primary1 will be deleted.

Do you want to continue? {y|n}: y

[Job 34] Job is queued: snapmirror restore from source vserverB:secondary1 for the snapshot daily.2013-01-25_0010.
----
. 重新挂载已还原的卷并重新启动使用该卷的所有应用程序。




== 在 ONTAP 中执行此操作的其他方法

[cols="2"]
|===
| 要执行以下任务，请执行以下操作 ... | 查看此内容 ... 


| 重新设计的 System Manager （适用于 ONTAP 9.7 及更高版本） | link:https://docs.netapp.com/us-en/ontap/task_dp_restore_from_vault.html["从早期的 Snapshot 副本还原卷"^] 


| System Manager 经典版（适用于 ONTAP 9.7 及更早版本） | link:https://docs.netapp.com/us-en/ontap-sm-classic/volume-restore-snapvault/index.html["使用 SnapVault 还原卷概述"^] 
|===