---
permalink: data-protection/snapmirror-licensing-concept.html 
sidebar: sidebar 
keywords: snapmirror, licensing, snapvault, vault, mirror, relationship, replication, backup, back up, disaster recovery, dr 
summary: SnapMirror许可证支持保险库和镜像关系以及ONTAP复制，适用于备份和灾难恢复用例。 
---
= 了解ONTAP SnapMirror许可
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
从 ONTAP 9.3 开始，简化了在 ONTAP 实例之间复制的许可。在 ONTAP 9 版本中， SnapMirror 许可证既支持存储关系，也支持镜像关系。在备份和灾难恢复使用情形下、您可以使用SnapMirror许可证来支持ONTAP复制。

在ONTAP 9.3版之前、需要单独的SnapVault许可证来配置ONTAP实例之间的_vault_关系、在这种情况下、DP实例可以保留更多的快照来支持保留时间更长的备份用例、而在ONTAP实例之间配置_镜像_关系则需要SnapMirror许可证、其中每个ONTAP实例都将保留相同数量的快照(即镜像_映像)来支持灾难恢复用例、以便可以进行集群故障转移。ONTAP 8.x和9.x版本仍会继续使用和支持SnapMirror和SnapVault许可证。

虽然SnapVault许可证仍可继续运行、并且ONTAP 8.x和9.x版本均支持此许可证、但SnapMirror许可证可用于替代SnapVault许可证、并可用于镜像和存储配置。

对于 ONTAP 异步复制，从 ONTAP 9.3 开始，使用一个统一复制引擎来配置扩展数据保护模式（ Extended Data Protection Mode ， XDP ）策略，其中可以为镜像策略，存储策略或镜像 - 存储策略配置 SnapMirror 许可证。源集群和目标集群都需要 SnapMirror 许可证。如果已安装 SnapVault 许可证，则不需要 SnapMirror 许可证。SnapMirror异步永久许可证包含在新AFF和FAS系统上安装的ONTAP One软件套件中。

数据保护配置限制可通过多种因素来确定，包括您的 ONTAP 版本，硬件平台和安装的许可证。有关详细信息，请参见 https://hwu.netapp.com/["Hardware Universe"^]。



== SnapMirror同步许可证

从ONTAP 9。5开始、支持SnapMirror同步关系。要创建SnapMirror同步关系、您需要以下许可证：

* 源集群和目标集群都需要SnapMirror同步许可证。
+
SnapMirror同步许可证是的一部分link:../system-admin/manage-licenses-concept.html["ONTAP One许可证套件"]。

+
如果您的系统是在2019年6月之前随超值包或闪存包一起购买的，则可以从NetApp支持站点下载NetApp主密钥以获取所需的SnapMirror同步许可证： https://mysupport.netapp.com/NOW/knowledge/docs/olio/guides/master_lickey/["主许可证密钥"^]。

* 源集群和目标集群都需要 SnapMirror 许可证。




== SnapMirror云许可证

从ONTAP 9.8开始、SnapMirror云许可证可将快照从ONTAP实例异步复制到对象存储端点。可以使用内部对象存储以及 S3 和 S3 兼容的公有云对象存储服务来配置复制目标。支持从ONTAP系统到经过预先认证的对象存储目标的SnapMirror云关系。

SnapMirror云不能作为独立许可证提供。每个ONTAP 集群只需要一个许可证。除了SnapMirror云许可证之外、还需要SnapMirror异步许可证。

要创建SnapMirror云关系、您需要以下许可证：

* SnapMirror许可证和SnapMirror云许可证、用于直接复制到对象存储端点。
* 在配置多策略复制工作流(例如、磁盘到磁盘到云)时、所有ONTAP实例都需要SnapMirror许可证、而只有直接复制到对象存储端点的源集群才需要SnapMirror云许可证。


从ONTAP 9.9.1开始，您可以link:cloud-backup-with-snapmirror-task.html["使用System Manager进行SnapMirror云复制"]。

NetApp网站上发布了授权的SnapMirror云第三方应用程序列表。



== 数据保护优化许可证

不再销售数据保护优化型(Data Protection Optimized[DPO])许可证、当前平台不支持DPO；但是、如果您在受支持的平台上安装了DPO许可证、NetApp将继续提供支持、直到该平台终止提供为止。

DPO不随ONTAP One许可证包提供、如果系统上安装了ONTAP One许可证、则无法升级到DPO许可证包。

有关支持的平台的信息、请参见 https://hwu.netapp.com/["Hardware Universe"^]。
