---
permalink: data-protection/snapmirror-unified-replication-concept.html 
sidebar: sidebar 
keywords: snapmirror, unified, replication 
summary: SnapMirror 统一复制允许您在同一目标卷上配置灾难恢复和归档。如果需要统一复制，则可以减少所需的二级存储容量，限制基线传输数以及减少网络流量。 
---
= 了解ONTAP SnapMirror统一复制
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用 snapmirror _unified replication ，您可以在同一目标卷上配置灾难恢复和归档。如果需要统一复制，则可以减少所需的二级存储容量，限制基线传输数以及减少网络流量。



== 如何初始化统一数据保护关系

与 SnapMirror 一样，统一数据保护会在您首次调用时执行基线传输。此关系的 SnapMirror 策略用于定义基线内容以及任何更新。

默认统一数据保护策略下的基线传输 `MirrorAndVault`会创建源卷的快照、然后将该副本及其引用的数据块传输到目标卷。与存储归档一样、统一数据保护不会在基线中包含较早的快照。



== 如何更新统一数据保护关系

在策略下的每次更新时 `MirrorAndVault`、SnapMirror都会为源卷创建一个快照、并传输该快照以及自上次更新以来创建的任何快照、前提是它们的标签与快照策略规则中定义的标签匹配。在策略命令的 `MirrorAndVault`以下输出中 `snapmirror policy show`、请注意以下几点：

* `Create Snapshot`为"`true`"、表示 `MirrorAndVault`在SnapMirror更新关系时创建快照。
* `MirrorAndVault`具有规则"`sm_created`"、"`daily`"和"`Weekly`"、表示当SnapMirror更新关系时、SnapMirror创建的快照以及源上具有匹配标签的快照都会传输。


[listing]
----
cluster_dst::> snapmirror policy show -policy MirrorAndVault -instance

                     Vserver: vs0
      SnapMirror Policy Name: MirrorAndVault
      SnapMirror Policy Type: mirror-vault
                Policy Owner: cluster-admin
                 Tries Limit: 8
           Transfer Priority: normal
   Ignore accesstime Enabled: false
     Transfer Restartability: always
 Network Compression Enabled: false
             Create Snapshot: true
                     Comment: A unified SnapMirror synchronous and SnapVault policy for
                              mirroring the latest file system and daily and weekly snapshots.
       Total Number of Rules: 3
                  Total Keep: 59
                       Rules: SnapMirror Label     Keep  Preserve Warn Schedule Prefix
                              ----------------     ----  -------- ---- -------- ------
                              sm_created              1  false       0 -        -
                              daily                   7  false       0 -        -
                              weekly                 52  false       0 -        -
----


== Unified7year 策略

预配置 `Unified7year`策略的工作方式与完全相同 `MirrorAndVault`，只是第四条规则传输每月快照并将其保留七年。

[listing]
----

                       Rules: SnapMirror Label     Keep  Preserve Warn Schedule Prefix
                              ----------------     ----  -------- ---- -------- ------
                              sm_created              1  false       0 -        -
                              daily                   7  false       0 -        -
                              weekly                 52  false       0 -        -
                              monthly                84  false       0 -        -
----


== 防止可能的数据损坏

统一复制会将基线传输的内容限制为初始化时由SnapMirror创建的快照。每次更新时、SnapMirror都会为源创建另一个快照、并传输该快照以及标签与快照策略规则中定义的标签匹配的任何新快照。

您可以通过在目标上创建上次传输的快照的副本来防止更新后的快照可能损坏。无论源上的保留规则如何、都会保留此"`local copy`"、这样、即使最初通过SnapMirror传输的快照在源上不再可用、也可以在目标上获得其副本。



== 何时使用统一数据复制

您需要权衡维护完整镜像的优势与统一复制在减少二级存储数量，限制基线传输数量以及减少网络流量方面的优势。

确定统一复制是否合适的关键因素是活动文件系统的更改率。例如、传统镜像可能更适合存放数据库事务日志的每小时快照的卷。
