---
permalink: data-protection/version-flexible-snapmirror-default-concept.html 
sidebar: sidebar 
keywords: xdp, replace, dp, snapmirror, default, snap mirror, data protection, replication, replicate, snap lock, snaplock 
summary: 从 ONTAP 9.3 开始， SnapMirror 扩展数据保护（ XDP ）模式将取代 SnapMirror 数据保护（ DP ）模式作为 SnapMirror 默认设置。 
---
= XDP 取代 DP 作为 SnapMirror 默认设置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
从 ONTAP 9.3 开始， SnapMirror 扩展数据保护（ XDP ）模式将取代 SnapMirror 数据保护（ DP ）模式作为 SnapMirror 默认设置。

在升级到ONTAP 9.12.1之前、必须先将现有DP类型关系转换为XDP、然后才能升级到ONTAP 9.12.1及更高版本。有关详细信息，请参见 link:convert-snapmirror-version-flexible-task.html["将现有 DP 类型关系转换为 XDP"]。

在 ONTAP 9.3 之前，在 DP 模式下调用的 SnapMirror 和在 XDP 模式下调用的 SnapMirror 使用不同的复制引擎，对版本依赖性采用不同的方法：

* 在 DP 模式下调用的 SnapMirror 使用了一个 _version-dependent _ 复制引擎，其中，主存储和二级存储上的 ONTAP 版本必须相同：
+
[listing]
----
cluster_dst::>  snapmirror create -type DP -source-path ... -destination-path ...
----
* 在 XDP 模式下调用的 SnapMirror 使用 _version-flexible 复制引擎，该引擎支持主存储和二级存储上的不同 ONTAP 版本：
+
[listing]
----
cluster_dst::>  snapmirror create -type XDP -source-path ... -destination-path ...
----


随着性能的提高，版本灵活的 SnapMirror 的显著优势大于使用版本相关模式获得的复制吞吐量的轻微优势。因此，从 ONTAP 9.3 开始， XDP 模式已成为新的默认模式，在命令行或新脚本或现有脚本中调用的任何 DP 模式都会自动转换为 XDP 模式。

现有关系不受影响。如果某个关系的类型已经是 DP ，则它将继续为 DP 类型。从 ONTAP 9.5 开始，如果未指定数据保护模式或将 XDP 模式指定为关系类型，则 MirrorAndVault 将成为新的默认策略。下表显示了您可能会遇到的行为。

[cols="3*"]
|===


| 指定项 | 类型为 ... | 默认策略（如果未指定策略）为 ... 


 a| 
数据
 a| 
XDP
 a| 
MirrorAllSnapshots （ SnapMirror 灾难恢复）



 a| 
无
 a| 
XDP
 a| 
MirrorAndVault （统一复制）



 a| 
XDP
 a| 
XDP
 a| 
MirrorAndVault （统一复制）

|===
如表所示，在不同情况下分配给 XDP 的默认策略可确保转换保持旧类型的功能等效。当然，您可以根据需要使用不同的策略，包括用于统一复制的策略：

[cols="3*"]
|===


| 指定项 | 策略是 ... | 结果是 ... 


 a| 
数据
 a| 
MirrorAllSnapshots
 a| 
SnapMirror 灾难恢复



 a| 
XDPDefault
 a| 
SnapVault



 a| 
MirrorAndVault
 a| 
统一复制



 a| 
XDP
 a| 
MirrorAllSnapshots
 a| 
SnapMirror 灾难恢复



 a| 
XDPDefault
 a| 
SnapVault



 a| 
MirrorAndVault
 a| 
统一复制

|===
转换的唯一例外情况如下：

* 在 ONTAP 9.3 及更早版本中， SVM 数据保护关系仍默认为 DP 模式。
+
从 ONTAP 9.4 开始， SVM 数据保护关系默认为 XDP 模式。

* 根卷负载共享数据保护关系仍默认为 DP 模式。
* 在 ONTAP 9.4 及更早版本中， SnapLock 数据保护关系仍默认为 DP 模式。
+
从 ONTAP 9.5 开始， SnapLock 数据保护关系默认为 XDP 模式。

* 如果设置了以下集群范围选项，则显式调用 DP 仍会默认为 DP 模式：
+
[listing]
----
options replication.create_data_protection_rels.enable on
----
+
如果不显式调用 DP ，则会忽略此选项。


