---
permalink: release-notes/whats-new-9151.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, 9.15.1' 
summary: 了解ONTAP 9.151中提供的新功能。 
---
= ONTAP 9.15.1.中的新增功能
:allow-uri-read: 


[role="lead"]
了解ONTAP 9.151中提供的新功能。

有关最新ONTAP 9版本中的已知问题、限制和升级注意事项的详细信息、请参阅 https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["《 ONTAP 9 发行说明》"^]。您必须使用NetApp帐户登录或创建帐户才能访问发行说明。

了解新增功能和增强功能 https://docs.netapp.com/us-en/ontap-metrocluster/releasenotes/mcc-new-features.html["ONTAP MetroCluster功能"^]。

了解的新增和增强支持 https://docs.netapp.com/us-en/ontap-systems/whats-new.html["FAS、ASA和AFF平台以及支持的交换机"^]。

了解的更新 https://docs.netapp.com/us-en/ontap-automation/whats_new.html["ONTAP REST API"^]。

要升级到最新版本的ONTAP、请参见 link:../upgrade/prepare.html["准备升级ONTAP"]。



== 数据保护

[cols="30%,70%"]
|===
| 更新 | Description 


 a| 
xref:../snapmirror-active-sync/index.html[SnapMirror主动同步支持对称主动/主动部署]
 a| 
SnapMirror主动同步(以前称为SnapMirror业务连续性)现在支持对称主动/主动部署、从而可以通过双向同步复制从受保护LUN的两个副本执行读写I/O操作。



 a| 
增加了使用SnapMirror异步的一致性组中卷的限制
 a| 
现在、使用SnapMirror异步保护的一致性组最多可支持一致性组中的80个卷。



 a| 
xref:../consistency-groups/configure-task.html[支持对一致性组执行REST API和命令行界面操作的管理权限级别]
 a| 
现在、在管理权限级别支持对一致性组执行命令行界面和REST API操作。



 a| 
xref:../concepts/ontap-and-vmware.html[使用Windows Server故障转移集群为VMware虚拟卷保留永久性预留空间]
 a| 
ONTAP目前支持VMware虚拟卷(vvol)以及传统LUN的永久性预留。从ONTAP 9.15.1开始、您还可以为VVOV创建永久性预留。适用于VMware vSphere 9的ONTAP工具支持此功能。只有Windows Server故障转移集群(WSFC)(一组集群模式Windows虚拟机)才支持此功能。

|===


== 安全性

[cols="30%,70%"]
|===
| 更新 | Description 


 a| 
xref:../nas-audit/create-persistent-stores.html[简化了FPolicy持久存储的创建和配置]
 a| 
您可以使用创建FPolicy持久存储、并同时自动创建和配置其卷 `persistent-store create` 命令：

增强型 `persistent-store create` 命令还允许使用autosize-mode参数、该参数允许卷根据已用空间量增大或减小大小。



 a| 
xref:../nfs-rdma/index.html[使用RDMA支持NFS3]
 a| 
基于RDMA的NFS配置现在支持NFSv3。



 a| 
xref:../nas-audit/supported-file-operation-filter-fpolicy-nfsv4-concept.html[FPolicy支持NFS 4.1协议]
 a| 
FPolicy支持NFS 4.1协议。



 a| 
xref:../nas-audit/plan-fpolicy-external-engine-config-concept.html[针对FPolicy的Protobuf引擎格式支持]
 a| 
Protobuf是Google用于串行化结构化数据的语言中立机制。与XML相比、它更小、更快速、更简单、这有助于提高FPolicy性能。

您可以使用protobuf外部引擎格式。设置为protobuf时、通知消息将使用Google Protobuf以二进制格式进行编码。在将外部引擎格式设置为protobuf之前、请确保FPolicy服务器也支持protobuf反序列化。



 a| 
xref:../authentication/dynamic-authorization-overview.html[SSH连接的动态授权]
 a| 
ONTAP 9.15.1提供了动态授权的初始框架、通过使您能够为管理员用户分配安全信任得分、并在其活动看起来可疑时通过额外的授权检查对其进行质询、从而为ONTAP系统的管理提供增强的安全性。  您可以在以数据为中心的零信任安全架构中使用动态授权。



 a| 
支持使用TLS 1.3进行S3存储、FlexCache和集群对等加密
 a| 
自ONTAP 9.11.1起、支持使用TLS 1.3进行管理访问、但现在ONTAP 9.151支持使用TLS 1.3进行S3存储、FlexCache和集群对等加密。在9.15.1版本中、FabricPool、Microsoft Azure Page Blobs存储和SnapMirror云等某些应用程序仍仅限于使用TLS 1.2。



 a| 
xref:../nfs-admin/tls-nfs-strong-security-concept.html[NFS连接支持TLS]
 a| 
基于TLS的NFS在ONTAP 9.151中提供公开预览版。作为预览选项、ONTAP 9.15.1中的生产工作负载不支持基于TLS的NFS。

基于TLS的NFS可为从存储设备到客户端的数据提供传输中加密。TLS比Kerberos更新、更方便、配置和管理更简单。



 a| 
xref:../multi-admin-verify/index.html#rule-protected-commands[经过扩展、可用于多管理员验证的一组受规则保护的符合条件的命令]
 a| 
管理员可以创建多管理员验证规则、以保护集群配置、LUN删除、系统配置、IPsec和SAML的安全配置、卷快照操作、Vserver配置以及其他命令。



 a| 
xref:../system-admin/requirements-autosupport-reference.html[使用SMTP和TLS传送AutoSupport消息]
 a| 
虽然建议将AutoSupport消息传输到NetApp是HTTPS、但也可以使用未加密的SMTP。借助ONTAP 9.15.1,客户现在可以选择将TLS与SMTP结合使用。SMTPS协议通过加密电子邮件流量以及可选的电子邮件服务器凭据来建立安全传输通道。使用显式TLS、因此在创建TCP连接后激活TLS。如果将消息副本发送到本地电子邮件地址、则会使用相同的配置。

|===


== 存储效率

[cols="30%,70%"]
|===
| 更新 | Description 


 a| 
xref:../volumes/determine-space-usage-volume-aggregate-concept.html[对卷空间指标报告进行的更改]
 a| 
引入了两个新计数器、它们仅显示正在使用的元数据。此外、还对一些现有计数器进行了调整、以删除元数据并仅显示用户数据。这些更改共同提供了一个更清晰的视图、可显示这两种数据类型的指标。客户可以使用这些计数器从总计中对元数据进行折扣、并仅考虑实际用户数据、从而实施更准确的成本分摊模型。

|===


== 存储资源管理增强功能

[cols="30%,70%"]
|===
| 更新 | Description 


 a| 
xref:../flexcache/flexcache-writeback-enable-task.html[FlexCache回写支持]
 a| 
如果在缓存卷上启用了回写、则写入请求会发送到本地缓存、而不是原始卷、从而提高边缘计算环境和写入量繁重的工作负载缓存的性能。



 a| 
xref:../task_nas_file_system_analytics_enable.html[文件系统分析的性能增强]
 a| 
在启用文件系统分析时、ONTAP强制要求卷的5-8%的容量必须可用、以缓解卷和文件系统分析的潜在性能问题。



 a| 
FlexClone卷加密密钥
 a| 
系统会为FlexClone卷分配一个独立于FlexVol卷(主机)加密密钥的专用加密密钥。

|===


== System Manager

[cols="30%,70%"]
|===
| 更新 | Description 


 a| 
xref:../snaplock/commit-snapshot-copies-worm-concept.html[System Manager支持配置SnapLock存储关系]
 a| 
如果源和目标都运行ONTAP 9.15.1或更高版本、则可以使用System Manager配置SnapLock存储关系。



 a| 
xref:../task_cp_dashboard_tour.html[System Manager信息板的性能增强功能]
 a| 
System Manager信息板的"运行状况"、"容量"、"网络"和"性能"视图中提供了更完整的说明、包括性能指标增强功能、可帮助您识别延迟或性能问题并对其进行故障排除。

|===


== 升级

[cols="30%,70%"]
|===
| 更新 | Description 


 a| 
xref:../upgrade/automated-upgrade-task.html[支持在自动无中断升级期间将LIF迁移到HA配对节点]
 a| 
如果在自动无中断升级期间向另一批处理组迁移LIF失败、则LIF将迁移到同一批处理组中的HA配对节点。

|===