---
permalink: fabricpool/commands-manage-aggregates-reference.html 
sidebar: sidebar 
keywords: commands, managing, aggregates, fabricpool 
summary: 您可以使用 storage aggregate object-store 命令管理 FabricPool 的对象存储。您可以使用 storage aggregate 命令管理 FabricPool 的聚合。您可以使用 volume 命令管理 FabricPool 的卷。 
---
= 用于使用 FabricPool 管理聚合的命令
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `storage aggregate object-store` 命令来管理 FabricPool 的对象存储。您可以使用 `storage aggregate` 命令管理 FabricPool 的聚合。您可以使用 `volume` 命令管理 FabricPool 的卷。

|===


| 如果您要 ... | 使用以下命令： 


 a| 
定义对象存储的配置，以便 ONTAP 可以访问它
 a| 
`s存储聚合对象存储配置 create`



 a| 
修改对象存储配置属性
 a| 
`s存储聚合对象存储配置修改`



 a| 
重命名现有对象存储配置
 a| 
`s存储聚合对象存储配置重命名`



 a| 
删除对象存储的配置
 a| 
`s存储聚合对象存储配置 delete`



 a| 
显示对象存储配置列表
 a| 
`storage aggregate object-store config show`



 a| 
将另一个对象存储作为镜像附加到新的或现有的 FabricPool
 a| 
`storage aggregate object-store mirror` with the ` -aggregate` and ` -name` parameter in the admin privilege level



 a| 
从现有 FabricPool 镜像中删除对象存储镜像
 a| 
`storage aggregate object-store unmirror` with the ` -aggregate` and ` -name` parameter in the admin privilege level



 a| 
监控 FabricPool 镜像重新同步状态
 a| 
`storage aggregate object-store show-resync-status`



 a| 
显示 FabricPool 镜像详细信息
 a| 
`storage aggregate object-store show`



 a| 
提升对象存储镜像以替换 FabricPool 镜像配置中的主对象存储
 a| 
`storage aggregate object-store modify` ，并在管理权限级别使用 ` -aggregate` 参数



 a| 
在不将对象存储附加到聚合的情况下测试对象存储的延迟和性能
 a| 
`storage aggregate object-store profiler start` ，并在高级权限级别使用 ` -object-store-name` 和 ` -node` 参数



 a| 
监控对象存储配置程序状态
 a| 
`storage aggregate object-store profiler show` ，并在高级权限级别使用 ` -object-store-name` 和 ` -node` 参数



 a| 
在对象存储配置程序正在运行时中止它
 a| 
`storage aggregate object-store profiler abort` ，并在高级权限级别使用 ` -object-store-name` 和 ` -node` 参数



 a| 
将对象存储附加到聚合以使用 FabricPool
 a| 
`s存储聚合对象存储连接`



 a| 
将对象存储附加到包含 FlexGroup 卷的聚合以使用 FabricPool
 a| 
`storage aggregate object-store attach` 带有 `allow-flexgroup` `true`



 a| 
显示附加到启用了 FabricPool 的聚合的对象存储的详细信息
 a| 
`storage aggregate object-store show`



 a| 
显示分层扫描使用的聚合填充度阈值
 a| 
`storage aggregate object-store show` 并在高级权限级别使用 ` 字段 tiering-fullness-threshold` 参数



 a| 
显示附加到启用了 FabricPool 的聚合的对象存储的空间利用率
 a| 
`s存储聚合对象存储 show-space`



 a| 
在不用于 FabricPool 的聚合上启用非活动数据报告
 a| 
`storage aggregate modify` with the ` -is-inactive-data-reporting-enabled` `true` parameter



 a| 
显示是否在聚合上启用非活动数据报告
 a| 
`storage aggregate show` 带有 ` 字段 is-inactive-data-reporting-enabled` 参数



 a| 
显示有关聚合中冷用户数据量的信息
 a| 
`storage aggregate show-space` 带有 ` 字段 performance-tier-inactive-user-data ， performance-tier-inactive-user-data-percent` 参数



 a| 
为 FabricPool 创建卷，包括指定以下内容：

* 分层策略
* 分层最小冷却期（适用于 `snapshot-only` 或 `auto` 分层策略）

 a| 
`volume create`

* 您可以使用 ` -tiering-policy` 参数指定分层策略。
* 您可以在高级权限级别中使用 ` -tiering-minimum-cooling-days` 参数来指定分层最小冷却期。




 a| 
修改 FabricPool 的卷，包括修改以下内容：

* 分层策略
* 分层最小冷却期（适用于 `snapshot-only` 或 `auto` 分层策略）

 a| 
`volume modify`

* 您可以使用 ` -tiering-policy` 参数指定分层策略。
* 您可以在高级权限级别中使用 ` -tiering-minimum-cooling-days` 参数来指定分层最小冷却期。




 a| 
显示与卷相关的 FabricPool 信息，包括以下内容：

* 分层最小冷却期
* 冷用户数据量

 a| 
`volume show`

* 您可以在高级权限级别中使用 ` 字段 tiering-minimum-cooling-days` 参数来显示分层最小冷却期。
* 您可以使用 ` 字段 performance-tier-inactive-user-data ， performance-tier-inactive-user-data-percent` 参数来显示冷用户数据量。




 a| 
将卷移入或移出 FabricPool
 a| 
`volume move start` 您可以使用 ` -tiering-policy` 可选参数指定卷的分层策略。



 a| 
修改 FabricPool 回收未引用空间的阈值（碎片整理阈值）
 a| 
`storage aggregate object-store modify` 并在高级权限级别使用 ` -unresort-space-threshold` 参数



 a| 
修改分层扫描开始分层 FabricPool 数据之前聚合达到的填充百分比阈值

FabricPool 会继续将冷数据分层到云层，直到本地层容量达到 98% 为止。
 a| 
`storage aggregate object-store modify` 并在高级权限级别使用 ` -tiering-fullness-threshold` 参数



 a| 
显示回收 FabricPool 的未引用空间的阈值
 a| 
`storage aggregate object-store show` 或 `storage aggregate object-store show-space` 命令，并在高级权限级别使用 ` -un回收 空间阈值` 参数

|===