---
permalink: fabricpool/modify-tiering-policy-cooling-period-task.html 
sidebar: sidebar 
keywords: managing, storage, tiering, modifying, volume, tiering, policy, tiering, minimum, cooling period 
summary: 您可以更改卷的分层策略，以控制数据在变为非活动（冷）时是否移动到云层。对于采用仅快照或自动分层策略的卷，您还可以指定用户数据在移至云层之前必须保持非活动状态的分层最小冷却期。 
---
= 修改ONTAP卷的层策略和最短冷却期
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以更改卷的分层策略，以控制数据在变为非活动状态（ _c冷 _ ）时是否移动到云层。用于具有的卷 `snapshot-only` 或 `auto` 分层策略中、您还可以指定用户数据在移至云层之前必须保持非活动状态的分层最小冷却期。

.您需要的内容
将卷更改为 `auto` 要执行层策略或修改层最小冷却期、需要使用ONTAP 9.4或更高版本。

.关于此任务
更改卷的分层策略仅会更改卷的后续分层行为。它不会追溯性地将数据移至云层。

更改分层策略可能会影响数据变冷并移至云层所需的时间。

link:tiering-policies-concept.html#what-happens-when-you-modify-the-tiering-policy-of-a-volume-in-fabricpool["在 FabricPool 中修改卷的分层策略时会发生什么情况"]

.步骤
. 使用修改现有卷的层策略 `volume modify` 命令 `-tiering-policy` 参数：
+
您可以指定以下分层策略之一：

+
** `snapshot-only` (默认)
** `auto`
** `all`
** `none`
+
link:tiering-policies-concept.html#types-of-fabricpool-tiering-policies["FabricPool 分层策略的类型"]



. 如果卷使用 `snapshot-only` 或 `auto` 分层策略如果要修改分层最小冷却期、请使用 `volume modify` 命令 `-tiering-minimum-cooling-days` 高级权限级别中的可选参数。
+
您可以为分层最小冷却天数指定一个介于 2 到 183 之间的值。如果您使用的 ONTAP 版本早于 9.8 ，则可以为分层最小冷却天数指定一个介于 2 到 63 之间的值。



.修改卷分层策略和分层最小冷却期的示例
以下示例将SVM"`VS1`"中的卷"`myvol`"的分层策略更改为 `auto` 分层最小冷却期为45天：

[listing]
----
cluster1::> volume modify -vserver vs1 -volume myvol
-tiering-policy auto -tiering-minimum-cooling-days 45
----