---
permalink: fabricpool/move-volume-task.html 
sidebar: sidebar 
keywords: aggregate, local tier, moving, volume, fabricpool, fabric pool, tiering, policy, policies, block, capacity, cold data, 
summary: '请务必了解卷移动如何与FabricPool配合使用、因为在本地层、附加云层和卷(卷分层策略)上进行的更改会对功能产生重大影响。' 
---
= 将卷移动到启用了FabricPool的ONTAP本地层
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
link:../volumes/move-volume-task.html["卷移动"]通过、ONTAP可以无系统地将卷从一个本地层(源)移动到另一个本地层(目标)。执行卷移动的原因有多种、但最常见的原因是硬件生命周期管理、集群扩展和负载平衡。

请务必了解卷移动如何与FabricPool配合使用、因为在本地层、附加云层和卷(卷分层策略)上进行的更改会对功能产生重大影响。


NOTE: 在ONTAP 9.7之前的版本中、System Manager会使用术语_AGREL_来描述_local ti层_。无论您的ONTAP版本如何、ONTAP命令行界面都使用术语_AGREL_。要了解有关本地层的更多信息，请参见link:../disks-aggregates/index.html["磁盘和本地层"]。



== 目标本地层

如果卷移动的目标本地层未附加云层、则存储在云层上的源卷上的数据将写入目标本地层上的本地层。

从ONTAP 9.8开始、启用卷后link:determine-data-inactive-reporting-task.html["非活动数据报告"]、FabricPool将使用卷的热图立即将冷数据排队、以便在冷数据写入目标本地层后立即开始分层。

在ONTAP 9.8之前的版本中、将卷移至另一本地层会重置本地层上的块的非活动期限。例如、如果某个卷使用自动卷分层策略、并且数据位于本地层上、并且此卷已处于非活动状态20天、但尚未分层、则在卷移动后、此数据的温度将重置为0天。



== 优化的卷移动

从ONTAP 9.6开始、如果卷移动的目标本地层使用与源本地层相同的分段、则存储在该分段中的源卷上的数据不会移回本地层。分层数据始终处于空闲状态、只需要将热数据从一个本地层移动到另一个本地层。经过优化的卷移动可显著提高网络效率。

未经优化的卷移动会产生额外的网络和计算流量(读取/获取和写入/放置)、从而增加对ONTAP集群和对象存储的需求、并可能在分层到公共对象存储时增加成本。

[NOTE]
====
某些配置与优化的卷移动不兼容：

* 在卷移动期间更改层策略
* 源和目标本地层使用不同的加密密钥
* FlexClone 卷
* FlexClone父卷
* MetroCluster (在ONTAP 9.8及更高版本中支持优化的卷移动)
* 未同步FabricPool镜像分段


====
如果卷移动的目标本地层附加了云层、则存储在云层上的源卷上的数据会首先写入到目标本地层上的本地层。然后、如果此方法适用于卷的分层策略、则此策略将写入目标本地层上的云层。

首先将数据写入本地层可提高卷移动的性能并减少转换时间。如果在执行卷移动时未指定卷分层策略、则目标卷将使用源卷的分层策略。

如果在执行卷移动时指定了其他分层策略、则会使用指定的分层策略创建目标卷、并且卷移动不会进行优化。



=== 卷元数据

无论卷移动是否经过优化、ONTAP都会存储有关所有数据(包括本地数据和分层数据)位置的信息。将卷从一个本地层移至另一个本地层时、也需要将此信息移至目标本地层。此元数据始终保留在本地层中、但根据分层数据量、这可能会导致卷移动过程所需时间超过预期完成时间。

例如、300 TB的优化卷移动意味着300 TB的冷数据无需从一个本地层移动到另一个本地层(或触发300 TB的读取和300 TB的写入到对象存储)。但这确实意味着需要将与300 TB数据(本示例中为~15 TB数据)关联的元数据写入目标本地层。

请务必了解、命令报告的"吞吐量" `volume move show`并不表示从云层移动数据的吞吐量、而是表示本地更新的元数据的吞吐量。


NOTE: 在SVM DR关系中、源卷和目标卷必须使用相同的分层策略。

.步骤
. 使用 `volume move start`命令将卷从源本地层移动到目标本地层。


.移动卷的示例
以下示例将名为SVM的 `vs1`卷 `myvol2`移至 `dest_FabricPool`启用了FabricPool的本地层。

[listing]
----
cluster1::> volume move start -vserver vs1 -volume myvol2
-destination-aggregate dest_FabricPool
----