---
permalink: fabricpool/setup-ontap-s3-cloud-tier-task.html 
sidebar: sidebar 
keywords: tr-4814, fabricpool, setting up, ontap s3, cloud tier, local tier, tiering, storage tiering, storage tier, lif 
summary: 如果您运行的是 ONTAP 9.8 或更高版本，则可以将 ONTAP S3 设置为 FabricPool 的云层。 
---
= 将ONTAP S3设置为FabricPool云层
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您运行的是 ONTAP 9.8 或更高版本，则可以将 ONTAP S3 设置为 FabricPool 的云层。

.开始之前
* 您必须在远程集群上拥有 ONTAP S3 服务器名称及其关联 LIF 的 IP 地址。
+

NOTE: 客户端应用程序会使用服务器名称作为完全限定域名(FQDN)。在ONTAP之外、确认DNS记录指向正在使用的SVM数据LUN。

* 本地集群上必须存在<<create-lif,集群内的lifs>>。
+
如果配置了本地集群分层、则会将本地层(在ONTAP命令行界面中也称为存储聚合)附加到本地分段。FabricPool使用集群lifs传输集群内流量。

+

NOTE: 如果集群LIF资源饱和、可能会导致性能下降。为避免这种情况、NetApp建议在分层到本地分段时使用四节点或更多节点集群、同时使用一个HA对(用于本地层)和一个HA对(用于本地分段)。建议不要分层到单个HA对上的本地分段。

* 要使用ONTAP S3启用远程FabricPool容量(云)分层、您必须link:../s3-config/create-intercluster-lifs-remote-fabricpool-tiering-task.html["配置集群间生命周期"]在FabricPool客户端和对象存储服务器上link:../s3-config/create-data-lifs-task.html["配置数据生命周期"]。


.关于此任务
在 ONTAP 9.8 及更高版本中，已为 ONTAP S3 服务器启用负载平衡。当服务器的主机名解析为多个 IP 地址时， ONTAP 将使用返回的所有 IP 地址（最多 16 个 IP 地址）建立客户端连接。建立连接后， IP 地址将以轮循方式进行选取。



[[set-up-the-ontap-s3-cloud-tier-for-fabricpool]]
== 为 FabricPool 设置 ONTAP S3 云层

.步骤
您可以使用ONTAP System Manager或ONTAP 命令行界面将ONTAP S3设置为FabricPool 的云层。

[role="tabbed-block"]
====
.System Manager
--
. 单击*存储>层>添加云层*、然后选择ONTAP S3作为对象存储提供程序。
. 填写请求的信息。
. 如果要创建云镜像，请单击 * 添加为 FabricPool 镜像 * 。


FabricPool 镜像为您提供了一种无缝替换数据存储的方法，它有助于确保数据在发生灾难时可用。

--
.命令行界面
--
. 将 S3 服务器和 LIF 的条目添加到 DNS 服务器。
+
|===


| 选项 | Description 


 a| 
* 如果使用外部 DNS 服务器 *
 a| 
将 S3 服务器名称和 IP 地址提供给 DNS 服务器管理员。



 a| 
* 如果使用本地系统的 DNS 主机表 *
 a| 
输入以下命令：

[listing]
----
dns host create -vserver <svm_name> -address ip_address -hostname <s3_server_name>
----
|===
. 使用指定ONTAP S3配置信息 `storage aggregate object-store config create` 命令 `-provider-type` `ONTAP_S3` 参数。
+
** 。 `storage aggregate object-store config create` 如果本地ONTAP系统无法使用提供的信息访问ONTAP S3服务器、则命令将失败。
** 您可以使用 `-access-key` 用于指定用于授权ONTAP S3服务器请求的访问密钥的参数。
** 您可以使用 `-secret-password` 用于指定用于向ONTAP S3服务器发出身份验证请求的密码(机密访问密钥)的参数。
** 如果更改了 ONTAP S3 服务器密码，则应立即更新本地 ONTAP 系统中存储的相应密码。
+
这样可以无中断地访问 ONTAP S3 对象存储中的数据。

** 将参数设置 `-is-certificate-validation-enabled`为 `false`对ONTAP S3禁用证书检查。(`-is-certificate-validation-enabled true`建议的最佳做法是使用第三方证书颁发机构颁发的签名证书。


+
[listing]
----
cluster1::> storage aggregate object-store config create
-object-store-name myS3 -provider-type ONTAP_S3 -server myS3server
-container-name myS3container -access-key myS3key
-secret-password myS3pass
----
. 使用显示并验证ONTAP S3配置信息 `storage aggregate object-store config show` 命令：
+
。 `storage aggregate object-store config modify` 命令用于修改 `ONTAP_S3` FabricPool的配置信息。



--
====


[[change-the-ontap-s3-fqdn-for-fabricpool-tiering]]
== 更改用于 FabricPool 分层的 ONTAP S3 FQDN

当您需要对包含 FQDN 更新的网络进行更改时，应更改用于 FabricPool 分层的 ONTAP S3 FQDN，以避免网络中断。

.步骤
. 关闭 FabricPool 层的证书验证：
+
`storage aggregate object-store config modify -object-store-name <object store> -is-certificate-validation-enabled false`

. 更改 ONTAP S3 服务器的 FQDN：
+
`vserver object-store-server modify -vserver <vserver> -object-store-server <new fqdn>`

. （可选）如果需要证书验证并且主机名已更改，link:../s3-config/create-install-ca-certificate-svm-task.html["续订证书"]。
. 使用新的 FQDN 更新 FabricPool 层：
+
`storage aggregate object-store config modify -object-store-name <object_store_name> -server <new fqdn>`

. 确认 FabricPool 层中的所有对象存储及其镜像（如有）均可用：
+
`storage aggregate object-store show -fields object-store-availability,mirror-type,is-mirror-degraded`

+
有关详细信息，请参见link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-show.html#description["存储聚合对象存储显示"^]。

. 对任何其他对象存储重复这些步骤。
. 如果您在 ONTAP S3 服务器上续订了证书，并在 FabricPool 层上续订了证书，请重新启用证书验证：
+
`storage aggregate object-store config modify -object-store-name <object store> -is-certificate-validation-enabled true`



[[create-lif]]
.相关信息
* link:../smb-config/create-lif-task.html["为SMB创建LIF"]
* link:../nfs-config/create-lif-task.html["为NFS创建LIF"]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-config-create.html["存储聚合对象存储配置创建"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-object-store-config-modify.html["存储聚合对象存储配置修改"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-config-show.html["存储聚合对象存储配置显示"^]

