---
permalink: fabricpool/setup-aws-s3-cloud-tier-task.html 
sidebar: sidebar 
keywords: setting up, aws, s3, cloud tier 
summary: '如果您运行的是ONTAP 9.2或更高版本、则可以将Amazon S3设置为FabricPool的云层。如果您运行的是ONTAP 9.5或更高版本、则可以为FabricPool设置亚马逊商业云服务(C2S)。' 
---
= 将Amazon S3设置为云层
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您运行的是ONTAP 9.2或更高版本、则可以将Amazon S3设置为FabricPool的云层。如果您运行的是ONTAP 9.5或更高版本、则可以为FabricPool设置亚马逊商业云服务(C2S)。

.将Amazon S3与FabricPool结合使用的注意事项
* 在向Amazon S3进行层存储时、需要提供link:https://bluexp.netapp.com/cloud-tiering["XP Bluetiering许可证"]。
* 建议ONTAP用于连接到Amazon S3对象服务器的LIF使用10 Gbps端口。
* 在 AFF 和 FAS 系统以及 ONTAP Select 上， FabricPool 支持以下 Amazon S3 存储类：
+
** Amazon S3 标准版
** Amazon S3 Standard —不常访问（ Standard — IA ）
** Amazon S3 一个区域 - 不常访问（一个区域 - IA ）
** Amazon S3 智能分层
** Amazon Commercial Cloud Services
** 从ONTAP 9.11.1开始、Amazon S3 Glacier"即时恢复"(FabricPool不支持Glacier"灵活恢复"或"Glacier"深度归档)
+
https://aws.amazon.com/s3/storage-classes/["Amazon Web Services文档：Amazon S3存储类"]



+
有关未列出的存储类的信息，请联系您的销售代表。

* 在 Cloud Volumes ONTAP 上， FabricPool 支持从 Amazon Elastic Block Store （ EBS ）的通用 SSD （ GP2 ）和吞吐量优化 HDD （ st1 ）卷分层。


.步骤
. 使用指定Amazon S3配置信息 `storage aggregate object-store config create` 命令 `-provider-type` `AWS_S3` 参数。
+
** 您可以使用 `-auth-type` `CAP` 用于获取C2S访问凭据的参数。
+
使用时 `-auth-type` `CAP` 参数、则必须使用 `-cap-url` 用于指定为C2S访问请求临时凭据的完整URL的参数。

** 。 `storage aggregate object-store config create` 如果ONTAP无法使用提供的信息访问Amazon S3、则命令将失败。
** 您可以使用 `-access-key` 用于指定用于授权Amazon S3对象存储请求的访问密钥的参数。
** 您可以使用 `-secret-password` 用于指定用于向Amazon S3对象存储发出身份验证请求的密码(机密访问密钥)的参数。
** 如果更改了Amazon S3密码、则应立即更新存储在ONTAP中的相应密码。
+
这样、ONTAP便可无中断地访问Amazon S3中的数据。

+
[listing]
----
cluster1::> storage aggregate object-store config create
-object-store-name my_aws_store -provider-type AWS_S3
-server s3.amazonaws.com -container-name my-aws-bucket
-access-key DXJRXHPXHYXA9X31X3JX
----
+
[listing]
----
cluster1::> storage aggregate object-store config create -object-store-name my_c2s_store -provider-type AWS_S3 -auth-type CAP -cap-url https://123.45.67.89/api/v1/credentials?agency=XYZ&mission=TESTACCT&role=S3FULLACCESS -server my-c2s-s3server-fqdn -container my-c2s-s3-bucket
----


. 使用显示并验证Amazon S3配置信息 `storage aggregate object-store config show` 命令：
+
。 `storage aggregate object-store config modify` 命令用于修改FabricPool的Amazon S3配置信息。


