---
permalink: fabricpool/setup-aws-s3-cloud-tier-task.html 
sidebar: sidebar 
keywords: setting up, aws, s3, cloud tier 
summary: 如果您运行的是 ONTAP 9.2 或更高版本，则可以将 AWS S3 设置为 FabricPool 的云层。如果您运行的是 ONTAP 9.5 或更高版本，则可以为 FabricPool 设置 AWS 商用云服务（ C2S ）。 
---
= 将 AWS S3 设置为云层
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您运行的是 ONTAP 9.2 或更高版本，则可以将 AWS S3 设置为 FabricPool 的云层。如果您运行的是 ONTAP 9.5 或更高版本，则可以为 FabricPool 设置 AWS 商用云服务（ C2S ）。

.将AWS S3与FabricPool 结合使用的注意事项
* 您可能需要 FabricPool 许可证。
+
** 新订购的 AFF 系统附带了 10 TB 的可用容量，可用于使用 FabricPool 。
+
如果您需要在 AFF 系统上添加容量，在非 AFF 系统上使用 AWS S3 或从现有集群升级，则需要 FabricPool 许可证。

+
如果您是首次为现有集群订购 FabricPool ，则可以获得具有 10 TB 可用容量的 FabricPool 许可证。



* 建议ONTAP 用于连接到AWS S3对象服务器的LIF使用10 Gbps端口。
* 在 AFF 和 FAS 系统以及 ONTAP Select 上， FabricPool 支持以下 Amazon S3 存储类：
+
** Amazon S3 标准版
** Amazon S3 Standard —不常访问（ Standard — IA ）
** Amazon S3 一个区域 - 不常访问（一个区域 - IA ）
** Amazon S3 智能分层
** Amazon Commercial Cloud Services
+
https://["Amazon Web Services （ AWS ）文档： Amazon S3 存储类"]



+
有关未列出的存储类的信息，请联系您的销售代表。

* 在 Cloud Volumes ONTAP 上， FabricPool 支持从 Amazon Elastic Block Store （ EBS ）的通用 SSD （ GP2 ）和吞吐量优化 HDD （ st1 ）卷分层。


.步骤
. 使用 `storage aggregate object-store config create` 命令和 ` provider-type` `AWS_S3` 参数指定 AWS S3 配置信息。
+
** 您可以使用 ` -auth-type` `cap` 参数获取 C2S 访问的凭据。
+
使用 ` -auth-type` `cap` 参数时，必须使用 ` -cap-url` 参数指定完整 URL 以请求 C2S 访问的临时凭据。

** 如果 ONTAP 无法使用提供的信息访问 AWS S3 ，则 `storage aggregate object-store config create` 命令将失败。
** 您可以使用 ` -access-key` 参数指定用于授权 AWS S3 对象存储请求的访问密钥。
** 您可以使用 ` -secret-password` 参数指定用于对 AWS S3 对象存储的请求进行身份验证的密码（机密访问密钥）。
** 如果更改了 AWS S3 密码，则应立即更新存储在 ONTAP 中的相应密码。
+
这样， ONTAP 就可以无中断地访问 AWS S3 中的数据。

+
[listing]
----
cluster1::> storage aggregate object-store config create
-object-store-name my_aws_store -provider-type AWS_S3
-server s3.amazonaws.com -container-name my-aws-bucket
-access-key DXJRXHPXHYXA9X31X3JX
----
+
[listing]
----
cluster1::> storage aggregate object-store config create -object-store-name my_c2s_store -provider-type AWS_S3 -auth-type CAP -cap-url https://123.45.67.89/api/v1/credentials?agency=XYZ&mission=TESTACCT&role=S3FULLACCESS -server my-c2s-s3server-fqdn -container my-c2s-s3-bucket
----


. 使用 `storage aggregate object-store config show` 命令显示并验证 AWS S3 配置信息。
+
使用 `storage aggregate object-store config modify` 命令可以修改 FabricPool 的 AWS S3 配置信息。


