---
permalink: fabricpool/setup-alibaba-object-storage-cloud-tier-task.html 
sidebar: sidebar 
keywords: setting, up, alibaba cloud object, storage, cloud tier 
summary: 如果您运行的是 ONTAP 9.6 或更高版本，则可以将阿里云对象存储设置为 FabricPool 的云层。 
---
= 将阿里云对象存储设置为云层
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您运行的是 ONTAP 9.6 或更高版本，则可以将阿里云对象存储设置为 FabricPool 的云层。

.将阿里云对象存储与FabricPool 结合使用的注意事项
* 您可能需要 FabricPool 许可证。
+
新订购的 AFF 系统附带了 10 TB 的可用容量，可用于使用 FabricPool 。如果您需要在 AFF 系统上添加容量，在非 AFF 系统上使用阿里云对象存储或从现有集群升级，则需要 FabricPool 许可证。

* 在 AFF 和 FAS 系统以及 ONTAP Select 上， FabricPool 支持以下阿里对象存储服务类：
+
** 阿里对象存储服务标准
** Alibaba 对象存储服务不常访问
+
https://www.alibabacloud.com/help/doc-detail/51374.htm["阿里云：存储类简介"]





有关未列出的存储类的信息，请与 NetApp 销售代表联系。

.步骤
. 使用指定阿里云对象存储配置信息 `storage aggregate object-store config create` 命令 `-provider-type` `AliCloud` 参数。
+
** 。 `storage aggregate object-store config create` 如果ONTAP无法使用提供的信息访问阿里云对象存储、则命令将失败。
** 您可以使用 `-access-key` 用于指定用于授权阿里云对象存储请求的访问密钥的参数。
** 如果更改了 Alibaba 云对象存储密码，则应立即更新存储在 ONTAP 中的相应密码。
+
这样， ONTAP 就可以无中断地访问阿里云对象存储中的数据。



+
[listing]
----
storage aggregate object-store config create my_ali_oss_store_1
-provider-type AliCloud -server oss-us-east-1.aliyuncs.com
-container-name my-ali-oss-bucket -access-key DXJRXHPXHYXA9X31X3JX
----
. 使用显示并验证阿里云对象存储配置信息 `storage aggregate object-store config show` 命令：
+
。 `storage aggregate object-store config modify` 命令用于修改FabricPool的阿里云对象存储配置信息。


