---
permalink: fabricpool/setup-azure-blob-storage-cloud-tier-task.html 
sidebar: sidebar 
keywords: setting up, azure blob storage, cloud, cloud tier 
summary: 如果您运行的是 ONTAP 9.4 或更高版本，则可以将适用于云的 Azure Blob Storage 设置为 FabricPool 的云层。 
---
= 将适用于云的 Azure Blob Storage 设置为云层
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您运行的是 ONTAP 9.4 或更高版本，则可以将适用于云的 Azure Blob Storage 设置为 FabricPool 的云层。

.将Microsoft Azure Blob Storage与FabricPool 结合使用的注意事项
* 您可能需要 FabricPool 许可证。
+
新订购的 AFF 系统附带了 10 TB 的可用容量，可用于使用 FabricPool 。如果您需要在 AFF 系统上添加容量，在非 AFF 系统上使用 Azure Blob Storage 或从现有集群升级，则需要 FabricPool 许可证。

+
如果您是首次为现有集群订购 FabricPool ，则可以获得具有 10 TB 可用容量的 FabricPool 许可证。

* 如果将 Azure Blob Storage 与 Cloud Volumes ONTAP 结合使用，则不需要 FabricPool 许可证。
* 建议ONTAP 用于连接到Azure Blob存储对象服务器的LIF使用10 Gbps端口。
* FabricPool 目前不支持 Azure 堆栈，它是内部 Azure 服务。
* 在 Microsoft Azure Blob Storage 的帐户级别， FabricPool 仅支持热存储层和冷存储层。
+
FabricPool 不支持 Blob 级别的分层。它也不支持分层到 Azure 的归档存储层。



.关于此任务
FabricPool 目前不支持 Azure 堆栈，它是内部 Azure 服务。

.步骤
. 使用指定Azure Blb存储配置信息 `storage aggregate object-store config create` 命令 `-provider-type` `Azure_Cloud` 参数。
+
** 。 `storage aggregate object-store config create` 如果ONTAP无法使用提供的信息访问Azure Blb存储、则命令将失败。
** 您可以使用 `-azure-account` 用于指定Azure Blb Storage帐户的参数。
** 您可以使用 `-azure-private-key` 用于指定用于向Azure Blb Storage发出身份验证请求的访问密钥的参数。
** 如果更改了 Azure Blob Storage 密码，则应立即更新存储在 ONTAP 中的相应密码。
+
这样， ONTAP 就可以无中断地访问 Azure Blob 存储中的数据。



+
[listing]
----
cluster1::> storage aggregate object-store config create
-object-store-name MyAzure -provider-type Azure_Cloud
-server blob.core.windows.net -container-name myAzureContainer
-azure-account myAzureAcct -azure-private-key myAzureKey
----
. 使用显示并验证Azure Blb存储配置信息 `storage aggregate object-store config show` 命令：
+
。 `storage aggregate object-store config modify` 命令用于修改FabricPool的Azure Blb存储配置信息。


