---
permalink: fabricpool/setup-ibm-object-storage-cloud-tier-task.html 
sidebar: sidebar 
keywords: setting up, ibm cloud, object storage, cloud tier 
summary: 如果您运行的是 ONTAP 9.5 或更高版本，则可以将 IBM 云对象存储设置为 FabricPool 的云层。 
---
= 将 IBM Cloud Object Storage 设置为云层
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您运行的是 ONTAP 9.5 或更高版本，则可以将 IBM 云对象存储设置为 FabricPool 的云层。

.将IBM云对象存储与FabricPool 结合使用的注意事项
* link:https://bluexp.netapp.com/cloud-tiering["XP Bluetiering许可证"]在向IBM Cloud Object Storage进行层存储时、需要。
* 建议ONTAP 用于连接到IBM云对象服务器的LIF使用10 Gbps端口。


.步骤
. 使用指定IBM Cloud Object Storage配置信息 `storage aggregate object-store config create` 命令 `-provider-type` `IBM_COS` 参数。
+
** 。 `storage aggregate object-store config create` 如果ONTAP无法使用提供的信息访问IBM云对象存储、则命令将失败。
** 您可以使用 `-access-key` 用于指定用于授权IBM Cloud Object Storage对象存储请求的访问密钥的参数。
** 您可以使用 `-secret-password` 用于指定用于对IBM Cloud Object Storage对象存储的身份验证请求的密码(机密访问密钥)的参数。
** 如果更改了 IBM 云对象存储密码，则应立即更新存储在 ONTAP 中的相应密码。
+
这样， ONTAP 就可以无中断地访问 IBM 云对象存储中的数据。



+
[listing]
----
storage aggregate object-store config create
-object-store-name MyIBM -provider-type IBM_COS
-server s3.us-east.objectstorage.softlayer.net
-container-name my-ibm-cos-bucket -access-key DXJRXHPXHYXA9X31X3JX
----
. 使用显示并验证IBM Cloud Object Storage配置信息 `storage aggregate object-store config show` 命令：
+
。 `storage aggregate object-store config modify` 命令用于修改FabricPool的IBM云对象存储配置信息。


