---
permalink: fabricpool/setup-storagegrid-cloud-tier-task.html 
sidebar: sidebar 
keywords: setting up, storagegrid, cloud tier 
summary: 如果您运行的是 ONTAP 9.2 或更高版本，则可以将 StorageGRID 设置为 FabricPool 的云层。 
---
= 指定 StorageGRID 配置信息
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您运行的是 ONTAP 9.2 或更高版本，则可以将 StorageGRID 设置为 FabricPool 的云层。在对 SAN 协议访问的数据进行分层时， NetApp 建议使用私有云，例如 StorageGRID ，因为需要考虑连接问题。

在 ONTAP 9.8 及更高版本中，已为 StorageGRID 启用负载平衡。当服务器的主机名解析为多个 IP 地址时， ONTAP 将使用返回的所有 IP 地址（最多 16 个 IP 地址）建立客户端连接。建立连接后， IP 地址将以轮循方式进行选取。

.步骤
. 使用 `storage aggregate object-store config create` 命令和 ` provider-type` `SGWS` 参数指定 StorageGRID 配置信息。
+
** 如果 ONTAP 无法使用提供的信息访问 StorageGRID ，则 `storage aggregate object-store config create` 命令将失败。
** 您可以使用 ` -access-key` 参数指定用于授权 StorageGRID 对象存储请求的访问密钥。
** 您可以使用 ` -secret-password` 参数指定用于对 StorageGRID 对象存储的请求进行身份验证的密码（机密访问密钥）。
** 如果更改了 StorageGRID 密码，则应立即更新 ONTAP 中存储的相应密码。
+
这样， ONTAP 就可以无中断地访问 StorageGRID 中的数据。

** 将 ` -is-certificate-validation-enabled` 参数设置为 `false` 会禁用 StorageGRID 的证书检查。


+
[listing]
----
cluster1::> storage aggregate object-store config create
-object-store-name mySGWS -provider-type SGWS -server mySGWSserver
-container-name mySGWScontainer -access-key mySGWSkey
-secret-password mySGWSpass
----
. 使用 `storage aggregate object-store config show` 命令显示并验证 StorageGRID 配置信息。
+
使用 `storage aggregate object-store config modify` 命令可以修改 FabricPool 的 StorageGRID 配置信息。


