---
permalink: nfs-config/additional-information-reference.html 
sidebar: sidebar 
keywords: additional, information, nfs, configuration, networking, san protocol, root volume, protection 
summary: 成功测试 NFS 客户端访问后，您可以执行其他 NFS 配置或添加 SAN 访问。协议访问完成后，您应保护 Storage Virtual Machine （ SVM ）的根卷。 
---
= 从何处查找追加信息
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
成功测试 NFS 客户端访问后，您可以执行其他 NFS 配置或添加 SAN 访问。协议访问完成后，您应保护 Storage Virtual Machine （ SVM ）的根卷。



== NFS 配置

您可以使用以下信息和技术报告进一步配置 NFS 访问：

* link:../nfs-admin/index.html["NFS 管理"]
+
介绍如何使用 NFS 配置和管理文件访问。

* http://["NetApp 技术报告 4067 ：《 NFS 最佳实践和实施指南》"^]
+
可作为 NFSv3 和 NFSv4 操作指南，简要介绍 ONTAP 操作系统，重点介绍 NFSv4 。

* http://["NetApp 技术报告 4073 ：《安全统一身份验证》"]
+
介绍如何将 ONTAP 配置为与基于 UNIX 的 Kerberos 版本 5 （ krb5 ）服务器结合使用以进行 NFS 存储身份验证，并将 Windows Server Active Directory （ AD ）配置为 KDC 和轻量级目录访问协议（ LDAP ）身份提供程序。

* http://["NetApp 技术报告 3580 ：《 NFSv4 增强功能和最佳实践指南： Data ONTAP 实施》"]
+
介绍在连接到运行 ONTAP 的系统的 AIX ， Linux 或 Solaris 客户端上实施 NFSv4 组件时应遵循的最佳实践。





== 网络配置

您可以使用以下信息和技术报告进一步配置网络功能和名称服务：

* link:../nfs-admin/index.html["NFS 管理"]
+
介绍如何配置和管理 ONTAP 网络。

* http://["NetApp 技术报告 4182 ：《集群模式 Data ONTAP 配置的以太网存储设计注意事项和最佳实践》"]
+
介绍 ONTAP 网络配置的实施，并提供常见网络部署场景和最佳实践建议。

* https://["NetApp 技术报告 4668 ：《名称服务最佳实践指南》"^]
+
介绍如何配置 LDAP ， NIS ， DNS 和本地文件配置以进行身份验证。





== SAN 协议配置

如果要提供或修改对新 SVM 的 SAN 访问，可以使用 FC 或 iSCSI 配置信息，此信息可用于多个主机操作系统。



== 根卷保护

在 SVM 上配置协议后，您应确保其根卷受到保护：

* link:../data-protection/index.html["数据保护"]
+
介绍如何创建负载共享镜像以保护 SVM 根卷，这是适用于已启用 NAS 的 SVM 的 NetApp 最佳实践。此外，还介绍如何通过从负载共享镜像提升 SVM 根卷来快速从卷故障或丢失中恢复。


