---
permalink: nfs-config/comparison-exports-7-mode-concept.html 
sidebar: sidebar 
keywords: comparison, exports, 7-mode ontap 
summary: ONTAP 中的导出定义和使用方式与 7- 模式环境中不同。 
---
= 了解 7-模式和 ONTAP NFS 导出的比较
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 中的导出定义和使用方式与 7- 模式环境中不同。

|===


| 不同之处 | 7- 模式 | ONTAP 


 a| 
如何定义导出
 a| 
导出在中进行定义 `/etc/exports` 文件
 a| 
导出可通过在 SVM 中创建导出策略来定义。一个 SVM 可以包含多个导出策略。



 a| 
导出范围
 a| 
* 导出将应用于指定的文件路径或 qtree 。
* 您必须在中创建单独的条目 `/etc/exports` 对于每个文件路径或qtree。
* 只有在中定义导出后、这些导出才会持久保留 `/etc/exports` 文件

 a| 
* 导出策略适用于整个卷，包括卷中包含的所有文件路径和 qtree 。
* 如果需要，可以将导出策略应用于多个卷。
* 所有导出策略都会在系统重新启动后保持不变。




 a| 
隔离（为特定客户端指定对相同资源的不同访问权限）
 a| 
要为特定客户端提供对单个导出资源的不同访问权限、必须在中列出每个客户端及其允许的访问权限 `/etc/exports` 文件
 a| 
导出策略由多个单独的导出规则组成。每个导出规则都定义资源的特定访问权限，并列出具有这些权限的客户端。要为特定客户端指定不同的访问权限，您必须为每组特定访问权限创建一个导出规则，列出具有这些权限的客户端，然后将这些规则添加到导出策略中。



 a| 
名称别名
 a| 
定义导出时，您可以选择使导出名称与文件路径名称不同。您应使用 `-actual` 参数 `/etc/exports` 文件
 a| 
您可以选择使导出卷的名称与实际卷名称不同。为此、您必须在SVM命名空间中使用自定义接合路径名称挂载卷。


NOTE: 默认情况下，卷会使用其卷名称进行挂载。要自定义卷的接合路径名称，您需要将其卸载，重命名并重新挂载。

|===