---
permalink: nfs-config/configure-name-service-switch-table-task.html 
sidebar: sidebar 
keywords: configue, name, service, switch, table 
summary: 您必须正确配置名称服务切换表，以使 ONTAP 能够查询本地或外部名称服务以检索主机，用户，组，网络组或名称映射信息。 
---
= 配置 ONTAP NFS 名称服务切换表
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须正确配置名称服务切换表，以使 ONTAP 能够查询本地或外部名称服务以检索主机，用户，组，网络组或名称映射信息。

.开始之前
您必须已根据环境情况确定要用于主机，用户，组，网络组或名称映射的名称服务。

如果您计划使用网络组，则网络组中指定的所有 IPv6 地址都必须按照 RFC 5952 中的说明进行缩短和压缩。

.关于此任务
请勿包含未使用的信息源。例如、如果您的环境未使用NIS、请勿指定 `-sources nis` 选项

.步骤
. 将必要的条目添加到名称服务切换表：
+
`vserver services name-service ns-switch create -vserver _vserver_name_ -database _database_name_ -sources _source_names_`

. 验证名称服务切换表是否包含所需顺序的预期条目：
+
`vserver services name-service ns-switch show -vserver _vserver_name_`

+
如果要进行任何更正、必须使用 `vserver services name-service ns-switch modify` 或 `vserver services name-service ns-switch delete` 命令



.示例
以下示例将在名称服务切换表中为 SVM vs1 创建一个新条目，以便使用本地网络组文件和外部 NIS 服务器按此顺序查找网络组信息：

[listing]
----
cluster::> vserver services name-service ns-switch create -vserver vs1 -database netgroup -sources files,nis
----
.完成后
* 您必须配置为 SVM 指定的名称服务以提供数据访问。
* 如果您删除了 SVM 的任何名称服务，则还必须将其从名称服务切换表中删除。
+
如果无法从名称服务切换表中删除名称服务，则客户端对存储系统的访问可能无法按预期工作。


