---
permalink: nfs-config/load-local-unix-users-uri-task.html 
sidebar: sidebar 
keywords: load, local, unix, users, uri 
summary: 除了在 SVM 中手动创建单个本地 UNIX 用户之外，您还可以通过统一资源标识符（ Uniform Resource Identifier ， URI ）（ Vserver services name-service unix-user load-from-uri ）将本地 UNIX 用户列表加载到 SVM 中来简化此任务。 
---
= 从 URI 加载本地 UNIX 用户
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
除了在SVM中手动创建单个本地UNIX用户之外、您还可以通过统一资源标识符(URI)将本地UNIX用户列表加载到SVM中、从而简化此任务。 (`vserver services name-service unix-user load-from-uri`）。

.步骤
. 创建一个包含要加载的本地 UNIX 用户列表的文件。
+
文件必须包含UNIX中的用户信息 `/etc/passwd` 格式：

+
`_user_name: password: user_ID: group_ID: full_name_`

+
命令将丢弃的值 `_password_` 字段以及后面字段的值 `_full_name_` 字段 (`_home_directory_` 和 `_shell_`）。

+
支持的最大文件大小为 2.5 MB 。

. 验证此列表是否不包含任何重复信息。
+
如果此列表包含重复条目，则加载此列表将失败并显示错误消息。

. 将文件复制到服务器。
+
存储系统必须可通过 HTTP ， HTTPS ， FTP 或 FTPS 访问此服务器。

. 确定文件的 URI 。
+
此 URI 是您为存储系统提供的地址，用于指示文件的位置。

. 从 URI 将包含本地 UNIX 用户列表的文件加载到 SVM 中：
+
`vserver services name-service unix-user load-from-uri -vserver _vserver_name_ -uri {ftp|http|ftps|https}://_uri_ -overwrite {true|false}`

+
`-overwrite` {`true` `false`}指定是否覆盖条目。默认值为 `false`。



.示例
以下命令将从URI加载本地UNIX用户列表 `+ftp://ftp.example.com/passwd+` 到名为VS1的SVM中。SVM 上的现有用户不会被 URI 中的信息覆盖。

[listing]
----
node::> vserver services name-service unix-user load-from-uri -vserver vs1
-uri ftp://ftp.example.com/passwd -overwrite false
----