---
permalink: nfs-config/verify-permissions-kerberos-config-task.html 
sidebar: sidebar 
keywords: verify, permissions, kerberos, configuration 
summary: Kerberos 要求为 SVM 根卷以及本地用户和组设置某些 UNIX 权限。 
---
= 验证 Kerberos 配置的权限
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Kerberos 要求为 SVM 根卷以及本地用户和组设置某些 UNIX 权限。

.步骤
. 显示 SVM 根卷上的相关权限：
+
`volume show -volume _root_vol_name_-fields user ， group ， unix-permissions`

+
SVM 的根卷必须具有以下配置：

+
|===
| 名称 | 正在设置 ... 


 a| 
UID
 a| 
root 或 ID 0



 a| 
GID
 a| 
root 或 ID 0



 a| 
UNIX 权限
 a| 
755

|===
+
如果未显示这些值，请使用 `volume modify` 命令对其进行更新。

. 显示本地 UNIX 用户：
+
`vserver services name-service unix-user show -vserver _vserver_name_`

+
SVM 必须配置以下 UNIX 用户：

+
|===
| 用户名 | 用户 ID | 主组 ID | comment 


 a| 
NFS
 a| 
500
 a| 
0
 a| 
GSS 初始化阶段需要此项。

NFS 客户端用户 SPN 的第一个组件用作用户。

如果 NFS 客户端用户的 SPN 存在 Kerberos-UNIX 名称映射，则不需要 NFS 用户。



 a| 
root
 a| 
0
 a| 
0
 a| 
挂载时需要。

|===
+
如果未显示这些值，您可以使用 `vserver services name-service unix-user modify` 命令对其进行更新。

. 显示本地 UNIX 组：
+
`vserver services name-service unix-group show -vserver _vserver_ _name`

+
SVM 必须配置以下 UNIX 组：

+
|===
| 组名称 | 组 ID 


 a| 
守护进程
 a| 
1.



 a| 
root
 a| 
0

|===
+
如果未显示这些值，您可以使用 `vserver services name-service unix-group modify` 命令对其进行更新。


