---
permalink: system-admin/access-cluster-telnet-task.html 
sidebar: sidebar 
keywords: access, cluster, telnet, administrative, tasks, disbale, default 
summary: 您可以通过问题描述向集群发送 Telnet 请求来执行管理任务。默认情况下， Telnet 处于禁用状态。 
---
= 使用 Telnet 访问集群
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以通过问题描述向集群发送 Telnet 请求来执行管理任务。默认情况下， Telnet 处于禁用状态。

.您需要的内容
在使用 Telnet 访问集群之前，必须满足以下条件：

* 您必须拥有一个集群本地用户帐户，该帐户必须配置为使用 Telnet 作为访问方法。
+
`ssecurity login` 命令的 ` 应用程序` 参数用于指定用户帐户的访问方法。有关详细信息，请参见 `ssecurity login` 手册页。

* 必须已在集群或节点管理 LIF 使用的管理防火墙策略中启用 Telnet ，以便 Telnet 请求可以通过防火墙。
+
默认情况下， Telnet 处于禁用状态。带有 ` -service telnet` 参数的 `ssystem services firewall policy show` 命令可显示是否已在防火墙策略中启用 Telnet 。有关详细信息，请参见 `ssystem services firewall policy` 手册页。

* 如果使用 IPv6 连接，则必须已在集群上配置并启用 IPv6 ，并且防火墙策略必须已配置 IPv6 地址。
+
`network options ipv6 show` 命令可显示是否已启用 IPv6 。`sservices firewall policy show` 命令可显示防火墙策略。



.关于此任务
* Telnet 不是一种安全协议。
+
您应考虑使用 SSH 访问集群。SSH 可提供安全的远程 shell 和交互式网络会话。

* ONTAP 最多支持每个节点 50 个并发 Telnet 会话。
+
如果集群管理 LIF 驻留在节点上，则它与节点管理 LIF 共享此限制。

+
如果传入连接的速率高于每秒 10 次，则此服务将暂时禁用 60 秒。

* 如果要从 Windows 主机访问 ONTAP 命令行界面，可以使用 PuTTY 等第三方实用程序。


.步骤
. 在管理主机中，输入以下命令：
+
` * telnet _hostname_or_IP_*`

+
` hostname_or_IP_` 是集群管理 LIF 或节点管理 LIF 的主机名或 IP 地址。建议使用集群管理 LIF 。您可以使用 IPv4 或 IPv6 地址。



.Telnet请求示例
以下示例显示了已设置 Telnet 访问权限的用户 "`Joe` " 如何通过问题描述请求访问集群管理 LIF 为 10.72.137.28 的集群：

[listing]
----
admin_host$ telnet 10.72.137.28
Data ONTAP
login: joe
Password:
cluster1::>
----