---
permalink: system-admin/access-cluster-rsh-task.html 
sidebar: sidebar 
keywords: access, cluster, rsh, cluster, administrative, task, secure, protocol, service, policy, lif, firewall, role 
summary: 您可以通过问题描述向集群发送 RSH 请求来执行管理任务。RSH 不是安全协议，默认情况下处于禁用状态。 
---
= 使用RSH请求访问ONTAP集群
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以通过问题描述向集群发送 RSH 请求来执行管理任务。RSH 不是安全协议，默认情况下处于禁用状态。

Telnet和RSH不是安全协议；您应考虑使用SSH访问集群。SSH 可提供安全的远程 shell 和交互式网络会话。有关详细信息，请参阅 link:./access-cluster-ssh-task.html["使用SSH访问集群"]。

.开始之前
在使用 RSH 访问集群之前，必须满足以下条件：

* 您必须拥有一个集群本地用户帐户，该帐户必须配置为使用 RSH 作为访问方法。
+
 `-application`命令的参数 `security login`用于指定用户帐户的访问方法。有关的详细信息 `security login`，请参见link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+login["ONTAP 命令参考"^]。



.关于此任务
* ONTAP 最多支持每个节点 50 个并发 RSH 会话。
+
如果集群管理 LIF 驻留在节点上，则它与节点管理 LIF 共享此限制。

+
如果传入连接的速率高于每秒 10 次，则此服务将暂时禁用 60 秒。

* rsh命令需要高级权限。


[role="tabbed-block"]
====
.ONTAP 9．10.1或更高版本
--
.步骤
. 确认RSH安全协议已启用：
+
`security protocol show`

+
.. 如果已启用RSH安全协议、请继续执行下一步。
.. 如果未启用RSH安全协议、请使用以下命令启用它：
+
`security protocol modify -application rsh -enabled true`



. 确认此 `management-rsh-server` 服务位于管理生命周期管理中：
+
`network interface show -services management-rsh-server`

+
.. 如果存在此 `management-rsh-server` 服务、请继续执行下一步。
.. 如果此 `management-rsh-server` 服务不存在、请使用以下命令进行添加：
+
`network interface service-policy add-service -vserver cluster1 -policy default-management -service management-rsh-server`





--
.ONTAP 9.9 或更早版本
--
.开始之前
在使用 RSH 访问集群之前，必须满足以下条件：

* 集群或节点管理 LIF 使用的管理防火墙策略必须已启用 RSH ，以便 RSH 请求可以通过防火墙。
+
默认情况下、RSH处于禁用状态。带有 `-service rsh`参数的system services防火墙策略show命令用于显示是否已在防火墙策略中启用RSH。有关的详细信息 `system services firewall policy`，请参见link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=system+services+firewall+policy["ONTAP 命令参考"^]。

* 如果使用 IPv6 连接，则必须已在集群上配置并启用 IPv6 ，并且防火墙策略必须已配置 IPv6 地址。
+
 `network options ipv6 show`命令用于显示是否已启用IPv6。 `system services firewall policy show`命令可显示防火墙策略。



.步骤
. 在管理主机中，输入以下命令：
+
`rsh hostname_or_IP -l username:passwordcommand`

+
`hostname_or_IP`是集群管理LIF或节点管理LIF的主机名或IP地址。建议使用集群管理 LIF 。您可以使用 IPv4 或 IPv6 地址。

+
`command`是要通过RSH执行的命令。



--
====
.RSH请求示例
以下示例显示了已设置RSH访问权限的用户"`Joe`"如何通过问题描述处理RSH请求来运行 `cluster show` 命令：

[listing]
----

admin_host$ rsh 10.72.137.28 -l joe:password cluster show

Node                  Health  Eligibility
--------------------- ------- ------------
node1                 true    true
node2                 true    true
2 entries were displayed.

admin_host$
----