---
permalink: system-admin/access-cluster-telnet-task.html 
sidebar: sidebar 
keywords: access, cluster, telnet, administrative, tasks, disbale, default 
summary: 您可以通过问题描述向集群发送 Telnet 请求来执行管理任务。默认情况下， Telnet 处于禁用状态。 
---
= 使用 Telnet 访问集群
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以通过问题描述向集群发送 Telnet 请求来执行管理任务。默认情况下， Telnet 处于禁用状态。

.您需要的内容
在使用 Telnet 访问集群之前，必须满足以下条件：

* 您必须拥有一个集群本地用户帐户，该帐户必须配置为使用 Telnet 作为访问方法。
+
。 `-application` 的参数 `security login` 命令用于指定用户帐户的访问方法。有关详细信息，请参见 `security login` 手册页。



.关于此任务
* Telnet 不是一种安全协议。
+
您应考虑使用 SSH 访问集群。SSH 可提供安全的远程 shell 和交互式网络会话。

* ONTAP 最多支持每个节点 50 个并发 Telnet 会话。
+
如果集群管理 LIF 驻留在节点上，则它与节点管理 LIF 共享此限制。

+
如果传入连接的速率高于每秒 10 次，则此服务将暂时禁用 60 秒。

* 如果要从 Windows 主机访问 ONTAP 命令行界面，可以使用 PuTTY 等第三方实用程序。
* rsh命令需要高级权限。


.步骤
. 确认已启用Telnet安全协议：
+
`security protocol show`

+
.. 如果已启用Telnet安全协议、请继续执行下一步。
.. 如果未启用Telnet安全协议、请使用以下命令启用它：
+
`security protocol modify -application telnet -enabled true`



. 确认此 `management-telnet-server` 服务位于管理生命周期管理中：
+
`network interface show -services management-telnet-server`

+
.. 如果存在此 `management-telnet-server` 服务、请继续执行下一步。
.. 如果此 `management-telnet-server` 服务不存在、请使用以下命令进行添加：
+
`network interface service-policy add-service -vserver cluster1 -policy default-management -service management-telnet-server`





.Telnet请求示例
以下示例显示了已设置 Telnet 访问权限的用户 "`Joe` " 如何通过问题描述请求访问集群管理 LIF 为 10.72.137.28 的集群：

[listing]
----
admin_host$ telnet 10.72.137.28
Data ONTAP
login: joe
Password:
cluster1::>
----