---
permalink: system-admin/accessg-node-log-core-dump-mib-files-task.html 
sidebar: sidebar 
keywords: service, processor, infrastructure, spi, web, service, node, log, core, dump, mib, file, browser 
summary: 默认情况下，服务处理器基础架构（ Service Processor Infrastructure ， SPI ） Web 服务处于启用状态，以使 Web 浏览器能够访问集群中节点的日志，核心转储和 MIB 文件。即使节点关闭，只要节点由其配对节点接管，这些文件仍可访问。 
---
= 使用Web浏览器访问ONTAP节点日志、核心转储和MIB文件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
服务处理器基础架构 (`spi`)默认情况下、Web服务处于启用状态、以便通过Web浏览器访问集群中节点的日志、核心转储和MIB文件。即使节点关闭，只要节点由其配对节点接管，这些文件仍可访问。

.您需要的内容
* 集群管理 LIF 必须已启动。
+
您可以使用集群或节点的管理LIF来访问 `spi` Web服务。但是，建议使用集群管理 LIF 。

+
。 `network interface show` 命令可显示集群中所有的生命周期的状态。

* 您必须使用本地用户帐户访问 `spi` 不支持Web服务、域用户帐户。
* 如果您的用户帐户没有"`admin`"角色(该角色有权访问 `spi` Web服务)、则必须为您的访问控制角色授予对的访问权限 `spi` Web服务。
+
。 `vserver services web access show` 命令可显示为哪些角色授予了对哪些Web服务的访问权限。

* 如果您未使用"`admin`"用户帐户(其中包括 `http` 访问方法)、则必须使用设置您的用户帐户 `http` 访问方法。
+
。 `security login show` 命令显示用户帐户的访问和登录方法及其访问控制角色。

* 如果要使用 HTTPS 进行安全 Web 访问，则必须启用 SSL 并安装数字证书。
+
。 `system services web show` 命令可显示集群级别的Web协议引擎配置。



.关于此任务
。 `spi` 默认情况下、Web服务处于启用状态、可以手动禁用此服务 (`vserver services web modify -vserver * -name spi -enabled false`）。

将为"`admin`"角色授予对的访问权限 `spi` Web服务、并且可以手动禁用访问 (`services web access delete -vserver _cluster_name_ -name spi -role admin`）。

.步骤
. 将Web浏览器指向 `spi` 以下格式之一的Web服务URL：
+
** `http://_cluster-mgmt-LIF_/spi/`
** `https://_cluster-mgmt-LIF_/spi/`
+
`cluster-mgmt-LIF` 是集群管理LIF的IP地址。



. 当浏览器出现提示时，输入您的用户帐户和密码。
+
在您的帐户通过身份验证后、浏览器将显示指向的链接 `/mroot/etc/log/`， `/mroot/etc/crash/`，和 `/mroot/etc/mib/` 集群中每个节点的目录。


