---
permalink: system-admin/accounts-access-sp-concept.html 
sidebar: sidebar 
keywords: account, access, sp, cluster, user, cli, node 
summary: 尝试访问 SP 时，系统会提示您提供凭据。使用 service-processor 应用程序类型创建的集群用户帐户可以访问集群中任何节点上的 SP CLI 。SP 用户帐户通过 ONTAP 进行管理，并通过密码进行身份验证。从ONTAP 9.1.1开始、SP用户帐户必须具有管理员角色。 
---
= 可访问 SP 的帐户
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
尝试访问 SP 时，系统会提示您提供凭据。使用创建的集群用户帐户 `service-processor` 应用程序类型可以在集群的任何节点上访问SP命令行界面。SP 用户帐户通过 ONTAP 进行管理，并通过密码进行身份验证。从ONTAP 9.9.1开始、SP用户帐户必须具有 `admin` 角色。

用于访问 SP 的用户帐户通过 ONTAP 而不是 SP 命令行界面进行管理。如果使用创建了集群用户帐户、则该帐户可以访问SP `-application` 的参数 `security login create` 命令设置为 `service-processor` 和 `-authmethod` 参数设置为 `password`。SP 仅支持密码身份验证。

您必须指定 `-role` 参数。

* 在ONTAP 9.9.1及更高版本中、您必须指定 `admin` 。 `-role` 参数、以及对帐户进行的任何修改都需要 `admin` 角色。出于安全原因、不再允许使用其他角色。
+
** 如果要升级到ONTAP 9.9.1或更高版本、请参见 link:../upgrade/sp-user-accounts-change-concept.html["可访问服务处理器的用户帐户的更改"]。
** 如果要还原到ONTAP 9.8或更早版本、请参见 link:../revert/verify-sp-user-accounts-task.html["验证可访问服务处理器的用户帐户"]。


* 在ONTAP 9.8及更早版本中、任何角色都可以访问SP、但 `admin` 建议使用。


默认情况下、名为"`admin`"的集群用户帐户包含 `service-processor` 应用程序类型、并可访问SP。

ONTAP 会阻止您使用为系统预留的名称（例如 "`root` " 和 "`naroot` " ）创建用户帐户。您不能使用系统预留名称来访问集群或 SP 。

您可以使用显示当前SP用户帐户 `-application service-processor` 的参数 `security login show` 命令：
