---
permalink: system-admin/add-nodes-cluster-concept.html 
sidebar: sidebar 
keywords: add, node, cluster, create, expand 
summary: 创建集群后，您可以通过向其添加节点来对其进行扩展。一次只能添加一个节点。 
---
= 向ONTAP集群添加节点
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
创建集群后，您可以通过向其添加节点来对其进行扩展。一次只能添加一个节点。

.开始之前
* 如果要向多节点集群添加节点，则集群中的所有现有节点都必须运行状况良好(由指示 `cluster show`)。有关的详细信息 `cluster show`，请参见link:https://docs.netapp.com/us-en/ontap-cli/cluster-show.html["ONTAP 命令参考"^]。
* 如果要向双节点无交换机集群添加节点、则必须使用NetApp支持的集群交换机将双节点无交换机集群转换为交换机连接集群。
+
只有双节点集群才支持无交换机集群功能。

* 如果要向单节点集群添加第二个节点，则必须已安装第二个节点，并且已配置集群网络。
* 如果集群已启用SP自动配置、则为SP指定的子网必须具有可用资源、以允许加入节点使用指定子网自动配置SP。
* 您必须已为新节点的节点管理 LIF 收集以下信息：
+
** Port
** IP 地址
** 网络掩码
** 默认网关




.关于此任务
节点的数量必须为偶数，才能形成 HA 对。开始向集群添加节点后，必须完成此过程。节点必须是集群的一部分，然后才能开始添加另一个节点。

.步骤
. 打开要添加到集群中的节点的电源。
+
节点将启动，节点设置向导将在控制台上启动。

+
[listing]
----
Welcome to node setup.

You can enter the following commands at any time:
  "help" or "?" - if you want to have a question clarified,
  "back" - if you want to change previously answered questions, and
  "exit" or "quit" - if you want to quit the setup wizard.
     Any changes you made before quitting will be saved.

To accept a default or omit a question, do not enter a value.

Enter the node management interface port [e0M]:
----
. 退出节点设置向导： `exit`
+
节点设置向导将退出，并显示登录提示，警告您尚未完成设置任务。

+
有关的详细信息 `exit`，请参见link:https://docs.netapp.com/us-en/ontap-cli/exit.html["ONTAP 命令参考"^]。

. 使用登录到管理员帐户 `admin` 用户名。
. 启动集群设置向导：
+
`*cluster setup*`

+
[listing]
----
::> cluster setup

Welcome to the cluster setup wizard.

You can enter the following commands at any time:
 "help" or "?" - if you want to have a question clarified,
 "back" - if you want to change previously answered questions, and
 "exit" or "quit" - if you want to quit the cluster setup wizard.
 Any changes you made before quitting will be saved.

You can return to cluster setup at any time by typing "cluster setup".
To accept a default or omit a question, do not enter a value....

Use your web browser to complete cluster setup by accessing
https://<node_mgmt_or_e0M_IP_address>

Otherwise, press Enter to complete cluster setup using the
command line interface:
----
+
[NOTE]
====
有关使用设置GUI设置集群的详细信息、请参见link:https://docs.netapp.com/us-en/ontap/task_admin_add_nodes_to_cluster.html["System Manager"]联机帮助。有关的详细信息 `cluster setup`，请参见link:https://docs.netapp.com/us-en/ontap-cli/cluster-setup.html["ONTAP 命令参考"^]。

====
. 按 Enter 键以使用命令行界面完成此任务。当系统提示您创建新集群或加入现有集群时、输入 `*join*`。
+
[listing]
----
Do you want to create a new cluster or join an existing cluster? {create, join}:
join
----
+
如果新节点上运行的ONTAP版本与现有集群上运行的版本不同、则系统会报告 `System checks Error: Cluster join operation cannot be performed at this time` 错误。这是预期行为。要继续、请运行 `add-node -allow-mixed-version-join new_node_name` 命令。

. 按照提示设置节点并将其加入集群：
+
** 要接受提示的默认值，请按 Enter 键。
** 要为提示输入您自己的值，请输入相应值，然后按 Enter 键。


. 对要添加的每个其他节点重复上述步骤。


.完成后
向集群添加节点后，您应为每个 HA 对启用存储故障转移。

.相关信息
link:../upgrade/concept_mixed_version_requirements.html#mixed-version-clusters-supported-for-ontap-software-upgrades["混合版本ONTAP集群"]
