---
permalink: system-admin/autosupport-creates-sends-event-messages-concept.html 
sidebar: sidebar 
keywords: autosupport, event, triggered, messages, ems, data, example 
summary: AutoSupport 会在 EMS 处理触发事件时创建事件触发的 AutoSupport 消息。事件触发的 AutoSupport 消息会提醒收件人需要采取更正操作的问题，并且仅包含与问题相关的信息。您可以自定义要包含的内容以及接收消息的人员。 
---
= AutoSupport 如何创建和发送事件触发的消息
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport 会在 EMS 处理触发事件时创建事件触发的 AutoSupport 消息。事件触发的 AutoSupport 消息会提醒收件人需要采取更正操作的问题，并且仅包含与问题相关的信息。您可以自定义要包含的内容以及接收消息的人员。

AutoSupport 使用以下过程创建和发送事件触发的 AutoSupport 消息：

. 当 EMS 处理触发事件时， EMS 会向 AutoSupport 发送一个请求。
+
触发器事件是指具有AutoSupport目标且名称以开头的EMS事件 `callhome.` 前缀。

. AutoSupport 会创建事件触发的 AutoSupport 消息。
+
AutoSupport 从与触发器关联的子系统收集基本信息和故障排除信息，以创建一条仅包含与触发器事件相关信息的消息。

+
每个触发器都会关联一组默认子系统。但是、您可以选择使用将其他子系统与触发器关联 `system node autosupport trigger modify` 命令：

. AutoSupport会将事件触发的AutoSupport消息发送给定义的收件人 `system node autosupport modify` 命令 `-to`， `-noteto`， `-partner-address`，和 `-support` parameters
+
您可以使用启用和禁用特定触发器的AutoSupport消息传送 `system node autosupport trigger modify` 命令 `-to` 和 `-noteto` parameters



.为特定事件发送的数据示例
。 `storage shelf PSU failed` EMS事件触发一条消息、其中包含Mandatory、Log Files、Storage、RAID、HA、 平台和网络子系统以及来自强制、日志文件和存储子系统的故障排除数据。

您决定在为响应未来的请求而发送的任何AutoSupport消息中包含有关NFS的数据 `storage shelf PSU failed` 事件。输入以下命令可为启用NFS故障排除级别的数据 `callhome.shlf.ps.fault` 事件：

[listing]
----

        cluster1::\>
        system node autosupport trigger modify -node node1 -autosupport-message shlf.ps.fault -troubleshooting-additional nfs
----
请注意、 `callhome.` 前缀将从中删除 `callhome.shlf.ps.fault` 事件 `system node autosupport trigger` 命令、或者在命令行界面中由AutoSupport和EMS事件引用时。
