---
permalink: system-admin/commands-manage-core-dumps-reference.html 
sidebar: sidebar 
keywords: command, manage, core, dump, coredump, config, files, node, application, report 
summary: 您可以使用 system node coredump config 命令管理核心转储的配置，使用 system node coredump 命令管理核心转储文件，使用 system node coredump reports 命令管理应用程序核心报告。 
---
= 用于管理核心转储的命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `ssystem node coredump config` 命令管理核心转储的配置，使用 `ssystem node coredump` 命令管理核心转储文件，使用 `ssystem node coredump reports` 命令管理应用程序核心报告。

|===
| 如果您要 ... | 使用此命令 ... 


 a| 
配置核心转储
 a| 
`ssystem node coredump config modify`



 a| 
显示核心转储的配置设置
 a| 
`ssystem node coredump config show`



 a| 
显示有关核心转储的基本信息
 a| 
`ssystem node coredump show`



 a| 
重新启动节点时手动触发核心转储
 a| 
`ssystem node reboot` 并使用 ` dump` 和 ` skip-lif-migration` 参数



 a| 
关闭节点时手动触发核心转储
 a| 
`ssystem node halt` 以及 ` -dump` 和 ` -skip-lif-migration` 参数



 a| 
保存指定的核心转储
 a| 
`s系统节点核心转储保存`



 a| 
保存指定节点上所有未保存的核心转储
 a| 
`ssystem node coredump save-all`



 a| 
生成包含您指定的核心转储文件的 AutoSupport 消息并发送此消息
 a| 
`s系统节点 AutoSupport invoke-core-upload`

[NOTE]
====
` -uri` 可选参数指定 AutoSupport 消息的备用目标。

====


 a| 
显示有关核心转储的状态信息
 a| 
`s系统节点核心转储状态`



 a| 
删除指定的核心转储
 a| 
`s系统节点核心转储删除`



 a| 
删除节点上所有未保存的核心转储或所有已保存的核心文件
 a| 
`ssystem node coredump delete-all`



 a| 
显示应用程序核心转储报告
 a| 
`s系统节点核心转储报告显示`



 a| 
删除应用程序核心转储报告
 a| 
`s系统节点核心转储报告 delete`

|===
.相关信息
http://["ONTAP 9命令"^]
