---
permalink: system-admin/commands-manage-jobs-reference.html 
sidebar: sidebar 
keywords: command, manage, jobs, queue, cluster, resources 
summary: 作业将置于作业队列中，并在资源可用时在后台运行。如果作业占用的集群资源过多，您可以将其停止或暂停，直到对集群的需求减少为止。您还可以监控和重新启动作业。 
---
= 用于管理作业的命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
作业将置于作业队列中，并在资源可用时在后台运行。如果作业占用的集群资源过多，您可以将其停止或暂停，直到对集群的需求减少为止。您还可以监控和重新启动作业。

当您输入用于调用作业的命令时，通常该命令会通知您作业已排队，然后返回到命令行界面命令提示符。但是，某些命令会报告作业进度，并且在作业完成之前不会返回到命令行界面命令提示符。在这些情况下，您可以按 Ctrl-C 将作业移至后台。

|===
| 如果您要 ... | 使用此命令 ... 


 a| 
显示有关所有作业的信息
 a| 
`作业显示`



 a| 
按节点显示有关作业的信息
 a| 
`作业显示 bynode`



 a| 
显示有关集群附属作业的信息
 a| 
`job show-cluster`



 a| 
显示有关已完成作业的信息
 a| 
`作业显示已完成`



 a| 
显示有关作业历史记录的信息
 a| 
`作业历史记录显示`

集群中每个节点最多可存储 25 ， 000 个作业记录。因此，尝试显示完整的作业历史记录可能需要很长时间。为了避免可能出现的长时间等待，您应按节点， Storage Virtual Machine （ SVM ）或记录 ID 显示作业。



 a| 
显示私有作业的列表
 a| 
`job private show` （高级权限级别）



 a| 
显示有关已完成的私有作业的信息
 a| 
`job private show-completed` （高级权限级别）



 a| 
显示有关作业管理器初始化状态的信息
 a| 
`job initstate show` （高级权限级别）



 a| 
监控作业进度
 a| 
`作业监视进度`



 a| 
监控专用作业的进度
 a| 
`job private watch-progress` （高级权限级别）



 a| 
暂停作业
 a| 
`作业暂停`



 a| 
暂停私有作业
 a| 
`作业私有暂停` （高级权限级别）



 a| 
恢复暂停的作业
 a| 
`作业恢复`



 a| 
恢复暂停的私有作业
 a| 
`作业私有恢复` （高级权限级别）



 a| 
停止作业
 a| 
`作业停止`



 a| 
停止私有作业
 a| 
`作业私有停止` （高级权限级别）



 a| 
删除作业
 a| 
`作业删除`



 a| 
删除私有作业
 a| 
`作业私有删除` （高级权限级别）



 a| 
解除集群附属作业与拥有该作业的不可用节点的关联，以便其他节点可以接管该作业的所有权
 a| 
`作业取消声明` （高级权限级别）

|===
[NOTE]
====
您可以使用 `event log show` 命令确定已完成作业的结果。

====
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9 命令"]
