---
permalink: system-admin/commands-manage-config-backup-files-reference.html 
sidebar: sidebar 
keywords: command, manage, configuration, backup, file 
summary: 您可以使用 system configuration backup 命令管理集群和节点配置备份文件。 
---
= 用于管理节点配置备份文件的ONTAP命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `system configuration backup` 用于管理集群和节点配置备份文件的命令。

这些命令可在高级权限级别下使用。

|===
| 如果您要 ... | 使用此命令 ... 


 a| 
创建新的节点或集群配置备份文件
 a| 
`system configuration backup create`



 a| 
将配置备份文件从一个节点复制到集群中的另一个节点
 a| 
`system configuration backup copy`



 a| 
将配置备份文件从集群中的节点上传到远程 URL（FTP、HTTP、HTTPS 或 FTPS）
 a| 
`system configuration backup upload`

在远程URL中使用HTTPS时、请使用 `-validate-certification` 用于启用或禁用数字证书验证的选项。默认情况下，证书验证处于禁用状态。

[NOTE]
====
您要上传配置备份文件的 Web 服务器必须启用 HTTP 的 PUT 操作和 HTTPS 的 POST 操作。您可能需要在某些网络服务器上安装附加模块。有关更多信息，请参阅 Web 服务器的文档。支持的 URL 格式因ONTAP版本而异。了解有关系统配置命令的更多信息 https://docs.netapp.com/us-en/ontap-cli/["ONTAP 命令参考"^]。

====


 a| 
将配置备份文件从远程 URL 下载到集群中的某个节点，如果指定了此备份文件，请验证此数字证书
 a| 
`system configuration backup download`

在远程URL中使用HTTPS时、请使用 `-validate-certification` 用于启用或禁用数字证书验证的选项。默认情况下，证书验证处于禁用状态。



 a| 
重命名集群中某个节点上的配置备份文件
 a| 
`system configuration backup rename`



 a| 
查看集群中一个或多个节点的节点和集群配置备份文件
 a| 
`system configuration backup show`



 a| 
删除节点上的配置备份文件
 a| 
`system configuration backup delete`

[NOTE]
====
此命令仅删除指定节点上的配置备份文件。如果配置备份文件也位于集群中的其他节点上，则该文件仍保留在这些节点上。

====
|===
.相关信息
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=system+configuration+backup["系统配置备份"^]

