---
permalink: system-admin/commands-manage-system-time-reference.html 
sidebar: sidebar 
keywords: command, manage, cluster, time, ntp, server, date, ntp, time, manually 
summary: 您可以使用 cluster time-service ntp server 命令管理集群的 NTP 服务器。您可以使用 cluster date 命令手动管理集群时间。 
---
= 用于管理集群时间的命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `cluster time-service ntp server` 用于管理集群的NTP服务器的命令。您可以使用 `cluster date` 用于手动管理集群时间的命令。

从 ONTAP 9.5 开始，您可以为 NTP 服务器配置对称身份验证。

使用以下命令可以管理集群的 NTP 服务器：

|===
| 如果您要 ... | 使用此命令 ... 


 a| 
将集群与外部 NTP 服务器关联，而不进行对称身份验证
 a| 
`cluster time-service ntp server create -server server_name`



 a| 
将集群与 ONTAP 9.5 或更高版本中可用的对称身份验证的外部 NTP 服务器相关联
 a| 
`cluster time-service ntp server create -server server_ip_address -key-id key_id`

[NOTE]
====
。 `key_id` 必须引用配置有"`cluster time-service ntr key"的现有共享密钥。

====


 a| 
为现有 NTP 服务器启用对称身份验证可以通过添加所需的密钥 ID 来修改现有 NTP 服务器以启用身份验证。

适用于 ONTAP 9.5 或更高版本
 a| 
`cluster time-service ntp server modify -server server_name -key-id key_id`



 a| 
禁用对称身份验证
 a| 
`cluster time-service ntp server modify -server server_name -is-authentication-enabled false`



 a| 
配置共享 NTP 密钥
 a| 
`cluster time-service ntp key create -id shared_key_id -type shared_key_type -value shared_key_value`

[NOTE]
====
共享密钥由 ID 引用。节点和 NTP 服务器上的 ID ，类型和值必须相同

====


 a| 
显示有关与集群关联的 NTP 服务器的信息
 a| 
`cluster time-service ntp server show`



 a| 
修改与集群关联的外部 NTP 服务器的配置
 a| 
`cluster time-service ntp server modify`



 a| 
断开 NTP 服务器与集群的关联
 a| 
`cluster time-service ntp server delete`



 a| 
通过清除所有外部 NTP 服务器与集群的关联来重置配置
 a| 
`cluster time-service ntp server reset`

[NOTE]
====
此命令需要高级权限级别。

====
|===
使用以下命令可以手动管理集群时间：

|===
| 如果您要 ... | 使用此命令 ... 


 a| 
设置或修改时区，日期和时间
 a| 
`cluster date modify`



 a| 
显示集群的时区，日期和时间设置
 a| 
`cluster date show`

|===
.相关信息
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9命令"^]
