---
permalink: system-admin/commands-manage-autosupport-reference.html 
sidebar: sidebar 
keywords: command, manage, autosupport, node, message, send, resend, cancel, configure, display, information 
summary: 您可以使用 system node AutoSupport 命令更改或查看 AutoSupport 配置，显示有关先前 AutoSupport 消息的信息以及发送，重新发送或取消 AutoSupport 消息。 
---
= 用于管理 AutoSupport 的命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `ssystem node AutoSupport` 命令更改或查看 AutoSupport 配置，显示有关先前 AutoSupport 消息的信息以及发送，重新发送或取消 AutoSupport 消息。



== 配置 AutoSupport

|===
| 如果您要 ... | 使用此命令 ... 


 a| 
控制是否发送任何 AutoSupport 消息
 a| 
`s带有 ` -state` 参数的系统节点 AutoSupport modify`



 a| 
控制是否将 AutoSupport 消息发送给技术支持
 a| 
`s带有 ` -support` 参数的 system node AutoSupport modify`



 a| 
设置 AutoSupport 或修改 AutoSupport 的配置
 a| 
`s系统节点 AutoSupport modify`



 a| 
启用和禁用针对单个触发事件向内部支持组织发送 AutoSupport 消息的功能，并指定要包含在针对单个触发事件发送的消息中的其他子系统报告
 a| 
`s系统节点 AutoSupport trigger modify`

|===


== 显示有关 AutoSupport 配置的信息

|===
| 如果您要 ... | 使用此命令 ... 


 a| 
显示 AutoSupport 配置
 a| 
`ssystem node AutoSupport show` 带有 ` -node` 参数



 a| 
查看接收 AutoSupport 消息的所有地址和 URL 的摘要
 a| 
`s系统节点 AutoSupport 目标显示`



 a| 
显示针对单个触发事件向内部支持组织发送的 AutoSupport 消息
 a| 
`ssystem node AutoSupport trigger show`



 a| 
显示 AutoSupport 配置的状态以及向各种目标的传输
 a| 
`ssystem node AutoSupport check show`



 a| 
显示 AutoSupport 配置的详细状态以及向各种目标的传输
 a| 
`s系统节点 AutoSupport check show-details`

|===


== 显示有关以往 AutoSupport 消息的信息

|===
| 如果您要 ... | 使用此命令 ... 


 a| 
显示有关 50 个最新 AutoSupport 消息中一个或多个消息的信息
 a| 
`s系统节点 AutoSupport 历史记录显示`



 a| 
显示有关为将核心转储或性能归档文件上传到技术支持站点或指定 URI 而生成的最新 AutoSupport 消息的信息
 a| 
`s系统节点 AutoSupport history show-upload-details`



 a| 
查看 AutoSupport 消息中的信息，包括为此消息收集的每个文件的名称和大小以及任何错误
 a| 
`ssystem node AutoSupport manifest show`

|===


== 发送，重新发送或取消 AutoSupport 消息

|===
| 如果您要 ... | 使用此命令 ... 


 a| 
重新传输本地存储的 AutoSupport 消息，此消息由其 AutoSupport 序列号标识

[NOTE]
====
如果您重新传输 AutoSupport 消息，并且支持部门已收到该消息，则支持系统不会创建重复的案例。另一方面，如果支持人员未收到此消息，则 AutoSupport 系统将分析此消息并在必要时创建案例。

==== a| 
`s系统节点 AutoSupport 历史记录重新传输`



 a| 
生成并发送 AutoSupport 消息，例如，用于测试目的
 a| 
`s系统节点 AutoSupport 调用`

[NOTE]
====
使用 ` -force` 参数发送消息，即使 AutoSupport 已禁用也是如此。使用 ` -uri` 参数将消息发送到您指定的目标，而不是配置的目标。

====


 a| 
取消 AutoSupport 消息
 a| 
`s系统节点 AutoSupport 历史记录取消`

|===
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9命令"^]
