---
permalink: system-admin/commands-manage-job-schedules-reference.html 
sidebar: sidebar 
keywords: command, manage, job, schedule, volume, snapshot, copy, cron, interval 
summary: 可以将许多任务（例如卷 Snapshot 副本）配置为按指定计划运行。在特定时间运行的计划称为 cron 计划（类似于 UNIX cron 计划）。按间隔运行的计划称为间隔计划。您可以使用 job schedule 命令管理作业计划。 
---
= 用于管理作业计划的命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
许多任务(例如卷Snapshot副本)都可以配置为按指定的计划运行。在特定时间运行的计划称为_cron_计划(类似于UNIX `cron` 计划)。按间隔运行的计划称为 _interval_ schedules 。您可以使用 `job schedule` 用于管理作业计划的命令。

作业计划不会根据对集群日期和时间的手动更改进行调整。这些作业将根据创建作业的当前集群时间或最近运行的作业时间计划运行。因此、如果手动更改集群日期或时间、则应使用 `job show` 和 `job history show` 用于验证所有计划作业是否已按您的要求排队并完成的命令。

如果集群是 MetroCluster 配置的一部分，则两个集群上的作业计划必须相同。因此，如果您创建，修改或删除作业计划，则必须在远程集群上执行相同的操作。

|===
| 如果您要 ... | 使用此命令 ... 


 a| 
显示有关所有计划的信息
 a| 
`job schedule show`



 a| 
按计划显示作业列表
 a| 
`job schedule show-jobs`



 a| 
显示有关 cron 计划的信息
 a| 
`job schedule cron show`



 a| 
显示有关间隔计划的信息
 a| 
`job schedule interval show`



 a| 
创建 cron 计划^1^
 a| 
`job schedule cron create`



 a| 
创建间隔计划
 a| 
`job schedule interval create`

必须至少指定以下参数之一： `-days`， `-hours`， `-minutes`或 `-seconds`。



 a| 
修改 cron 计划
 a| 
`job schedule cron modify`



 a| 
修改间隔计划
 a| 
`job schedule interval modify`



 a| 
删除计划
 a| 
`job schedule delete`



 a| 
删除 cron 计划
 a| 
`job schedule cron delete`



 a| 
删除间隔计划
 a| 
`job schedule interval delete`

|===
^1^从ONTAP 9.10.1开始、使用创建作业计划时 `job schedule cron create` 命令、则可以在作业计划中包含Vserver。

.相关信息
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9命令"^]
