---
permalink: system-admin/commands-manage-node-remotely-reference.html 
sidebar: sidebar 
keywords: command, manage, node, remotely, sp, cli, cluster 
summary: 您可以通过访问节点的 SP 并运行 SP 命令行界面命令来执行节点管理任务来远程管理节点。对于几个常用的远程节点管理任务，您还可以从集群中的另一个节点使用 ONTAP 命令。某些 SP 命令是特定于平台的，可能在您的平台上不可用。 
---
= 用于远程管理节点的命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以通过访问节点的 SP 并运行 SP 命令行界面命令来执行节点管理任务来远程管理节点。对于几个常用的远程节点管理任务，您还可以从集群中的另一个节点使用 ONTAP 命令。某些 SP 命令是特定于平台的，可能在您的平台上不可用。

|===
| 如果您要 ... | 使用此 SP 命令 ... | 使用此BMC命令 | 或此 ONTAP 命令 ... 


 a| 
显示指定 SP 命令的可用 SP 命令或子命令
 a| 
`help` [`command`]
 a| 
 a| 



 a| 
显示 SP 命令行界面的当前权限级别
 a| 
`priv show`
 a| 
 a| 



 a| 
设置访问 SP 命令行界面的指定模式的权限级别
 a| 
`priv set` {`admin` 我们可以为您提供 `advanced` 我们可以为您提供 `diag`｝
 a| 
 a| 



 a| 
显示系统日期和时间
 a| 
`date`
 a| 
 a| 
`date`



 a| 
显示 SP 记录的事件
 a| 
`events` {`all` 我们可以为您提供 `info` 我们可以为您提供 `newest` `number` 我们可以为您提供 `oldest number` 我们可以为您提供 `search keyword`｝
 a| 
 a| 



 a| 
显示 SP 状态和网络配置信息
 a| 
`sp status` [`-v` 我们可以为您提供 `-d`]

。 `-v` 选项以详细格式显示SP统计信息。。 `-d` 选项会将SP调试日志添加到显示内容中。
 a| 
`bmc status` [`-v` 我们可以为您提供 `-d`]

。 `-v` 选项以详细格式显示SP统计信息。。 `-d` 选项会将SP调试日志添加到显示内容中。
 a| 
`system service-processor show`



 a| 
显示 SP 已运行的时间长度以及运行队列中过去 1 分钟， 5 分钟和 15 分钟的平均作业数
 a| 
`sp uptime`
 a| 
`bmc uptime`
 a| 



 a| 
显示系统控制台日志
 a| 
`system log`
 a| 
 a| 



 a| 
显示 SP 日志归档或归档中的文件
 a| 
`sp log history show` [`-archive` {`latest` 我们可以为您提供{`all` 我们可以为您提供 `archive-name`}] [`-dump` {`all` 我们可以为您提供 `file-name`}]
 a| 
`bmc log history show` [`-archive` {`latest` 我们可以为您提供{`all` 我们可以为您提供 `archive-name`}] [`-dump` {`all` 我们可以为您提供 `file-name`}]
 a| 



 a| 
显示节点控制器的电源状态
 a| 
`system power status`
 a| 
 a| 
`system node power show`



 a| 
显示电池信息
 a| 
`system battery show`
 a| 
 a| 



 a| 
显示扩展器传感器的 ACP 信息或状态
 a| 
`system acp` [`show` 我们可以为您提供 `sensors show`]
 a| 
 a| 



 a| 
列出所有系统 FRU 及其 ID
 a| 
`system fru list`
 a| 
 a| 



 a| 
显示指定 FRU 的产品信息
 a| 
`system fru show` `fru_id`
 a| 
 a| 



 a| 
显示 FRU 数据历史记录日志
 a| 
`system fru log show` （高级权限级别）
 a| 
 a| 



 a| 
显示环境传感器的状态，包括其状态和当前值
 a| 
`system sensors` 或 `system sensors show`
 a| 
 a| 
`system node environment sensors show`



 a| 
显示指定传感器的状态和详细信息
 a| 
`system sensors get` `sensor_name`

您可以获取 `sensor_name` 使用 `system sensors` 或 `system sensors show` 命令：
 a| 
 a| 



 a| 
显示 SP 固件版本信息
 a| 
`version`
 a| 
 a| 
`system service-processor image show`



 a| 
显示 SP 命令历史记录
 a| 
`sp log audit` （高级权限级别）
 a| 
`bmc log audit`
 a| 



 a| 
显示 SP 调试信息
 a| 
`sp log debug` （高级权限级别）
 a| 
`bmc log debug` （高级权限级别）
 a| 



 a| 
显示 SP 消息文件
 a| 
`sp log messages` （高级权限级别）
 a| 
`bmc log messages` （高级权限级别）
 a| 



 a| 
显示用于收集 watchdog 重置事件的系统取证信息的设置，显示在 watchdog 重置事件期间收集的系统取证信息，或者清除收集的系统取证信息
 a| 
`system forensics` [`show` 我们可以为您提供 `log dump` 我们可以为您提供 `log clear`]
 a| 
 a| 



 a| 
登录到系统控制台
 a| 
`system console`
 a| 
 a| 
`system node run-console`



 a| 
您应按 Ctrl-D 退出系统控制台会话。



 a| 
打开或关闭节点，或者执行重新启动（关闭电源，然后重新打开）
 a| 
`system power` `on`
 a| 
 a| 
`system node power on` （高级权限级别）



 a| 
`system power` `off`
 a| 
 a| 



 a| 
`system power` `cycle`
 a| 
 a| 



 a| 
备用电源保持打开，以使 SP 保持运行，而不会中断。在重新启动期间，在重新打开电源之前会短暂暂停。

[NOTE]
====
使用这些命令关闭节点或对节点重新加电可能发生原因会导致节点异常关闭(也称为_dirty shutdown _)、并且不能替代使用ONTAP正常关闭 `system node halt` 命令：

====


 a| 
创建核心转储并重置节点
 a| 
`system core` [`-f`]

。 `-f` 选项用于强制创建核心转储并重置节点。
 a| 
 a| 
`system node coredump trigger`

（高级权限级别）



 a| 
这些命令的效果与按节点上的不可屏蔽中断（ NMI ）按钮相同，它会导致节点异常关闭，并在暂停节点时强制转储核心文件。当节点上的ONTAP挂起或不响应等命令时、这些命令很有用 `system node shutdown`。生成的核心转储文件将显示在的输出中 `system node coredump show` 命令：只要节点的输入电源不中断， SP 就会保持运行。



 a| 
使用可选指定的 BIOS 固件映像（主，备份或当前）重新启动节点，以从节点启动设备映像损坏等问题中恢复
 a| 
`system reset` {`primary` 我们可以为您提供 `backup` 我们可以为您提供 `current`｝
 a| 
 a| 
`system node reset` 使用 `-firmware` {`primary` 我们可以为您提供 `backup` 我们可以为您提供 `current`}参数(高级权限级别)

`system node reset`



 a| 
[NOTE]
====
此操作会导致节点异常关闭。

====
如果未指定 BIOS 固件映像，则会使用当前映像进行重新启动。只要节点的输入电源不中断， SP 就会保持运行。



 a| 
显示电池固件自动更新的状态，或者在下次 SP 启动时启用或禁用电池固件自动更新
 a| 
`system battery auto_update` [`status` 我们可以为您提供 `enable` 我们可以为您提供 `disable`]

（高级权限级别）
 a| 
 a| 



 a| 
将当前电池固件映像与指定的固件映像进行比较
 a| 
`system battery verify` [`image_URL`]

（高级权限级别）

条件 `image_URL` 未指定、则使用默认电池固件映像进行比较。
 a| 
 a| 



 a| 
从指定位置的映像更新电池固件
 a| 
`system battery flash` `image_URL`

（高级权限级别）

如果电池固件自动升级过程因某种原因失败，请使用此命令。
 a| 
 a| 



 a| 
使用指定位置的映像更新 SP 固件
 a| 
`sp update` `image_URL image_URL` 不得超过200个字符。
 a| 
`bmc update` `image_URL image_URL` 不得超过200个字符。
 a| 
`system service-processor image update`



 a| 
重新启动 SP
 a| 
`sp reboot`
 a| 
 a| 
`system service-processor reboot-sp`



 a| 
擦除 NVRAM 闪存内容
 a| 
`system nvram flash clear` （高级权限级别）

控制器电源关闭时、无法启动此命令 (`system power off`）。
 a| 
 a| 



 a| 
退出 SP 命令行界面
 a| 
`exit`
 a| 
 a| 

|===