---
permalink: system-admin/configure-sp-bmc-network-manually-task.html 
sidebar: sidebar 
keywords: configure, sp, bmc, network, manually, ip, address 
summary: 如果没有为 SP 设置自动网络配置，则必须手动配置节点的 SP 网络，才能使用 IP 地址访问 SP 。 
---
= 手动配置ONTAP SP或BMC网络
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您没有为 SP 设置自动网络配置，则必须手动配置节点的 SP 网络，才能使用 IP 地址访问 SP 。

.开始之前
如果要对 SP 使用 IPv6 连接，则必须已为 ONTAP 配置并启用 IPv6 。。 `network options ipv6` 命令用于管理ONTAP的IPv6设置。

[NOTE]
====
此任务会同时对 SP 和 BMC 执行适用场景。

====
您可以将 SP 配置为使用 IPv4 ， IPv6 或同时使用这两者。SP IPv4 配置支持静态寻址和 DHCP 寻址，而 SP IPv6 配置仅支持静态寻址。

如果已设置SP自动网络配置、则无需手动为各个节点和配置SP网络 `system service-processor network modify` 命令仅用于启用或禁用SP网络接口。

.步骤
. 使用为节点配置SP网络 `system service-processor network modify` 命令：
+
** 。 `-address-family` 参数用于指定要修改SP的IPv4配置还是IPv6配置。
** 。 `-enable` 参数用于启用指定IP地址系列的网络接口。
** 。 `-dhcp` 参数用于指定是使用DHCP服务器中的网络配置还是使用您提供的网络地址。
+
您可以通过设置启用DHCP `-dhcp` to `v4`)。您不能为 IPv6 配置启用 DHCP 。

** 。 `-ip-address` 参数用于指定SP的公共IP地址。
+
如果尝试使用分配给子网的地址手动配置 SP 网络，则会显示一条警告消息。忽略警告并继续手动分配地址可能会导致分配重复的地址。

** 。 `-netmask` 参数用于指定SP的网络掩码(如果使用IPv4)。
** 。 `-prefix-length` 参数用于指定SP子网掩码的网络前缀长度(如果使用IPv6)。
** 。 `-gateway` 参数用于指定SP的网关IP地址。


. 重复步骤 1 ，为集群中的其余节点配置 SP 网络。
. 使用显示SP网络配置并验证SP设置状态 `system service-processor network show` 命令 `–instance` 或 `–field setup-status` parameters
+
节点的 SP 设置状态可以是以下状态之一：

+
** `not-setup` ——未配置
** `succeeded` --配置成功
** `in-progress` 配置正在进行中
** `failed` --配置失败




.配置SP网络的示例
以下示例将节点的 SP 配置为使用 IPv4 ，启用 SP 并显示 SP 网络配置以验证设置：

[listing]
----

cluster1::> system service-processor network modify -node local
-address-family IPv4 -enable true -ip-address 192.168.123.98
-netmask 255.255.255.0 -gateway 192.168.123.1

cluster1::> system service-processor network show -instance -node local

                               Node: node1
                       Address Type: IPv4
                  Interface Enabled: true
                     Type of Device: SP
                             Status: online
                        Link Status: up
                        DHCP Status: none
                         IP Address: 192.168.123.98
                        MAC Address: ab:cd:ef:fe:ed:02
                            Netmask: 255.255.255.0
       Prefix Length of Subnet Mask: -
         Router Assigned IP Address: -
              Link Local IP Address: -
                 Gateway IP Address: 192.168.123.1
                  Time Last Updated: Thu Apr 10 17:02:13 UTC 2014
                        Subnet Name: -
Enable IPv6 Router Assigned Address: -
            SP Network Setup Status: succeeded
    SP Network Setup Failure Reason: -

1 entries were displayed.

cluster1::>
----