---
permalink: system-admin/configure-saml-authentication-task.html 
sidebar: sidebar 
keywords: tdp, ldap, identity, provider, saml, security, assertion, markup, lanaguage, active, directory 
summary: 从 ONTAP 9.3 开始，您可以为 Web 服务配置安全断言标记语言（ SAML ）身份验证。配置并启用 SAML 身份验证后，用户将通过外部身份提供程序（ Identity Provider ， IdP ）进行身份验证，而不是 Active Directory 和 LDAP 等目录服务提供程序进行身份验证。 
---
= 配置 SAML 身份验证
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
从 ONTAP 9.3 开始，您可以为 Web 服务配置安全断言标记语言（ SAML ）身份验证。配置并启用 SAML 身份验证后，用户将通过外部身份提供程序（ Identity Provider ， IdP ）进行身份验证，而不是 Active Directory 和 LDAP 等目录服务提供程序进行身份验证。

.您需要的内容
* 您必须已为 SAML 身份验证配置 IdP 。
* 您必须具有 IdP URI 。


.关于此任务
* SAML身份验证仅适用于 `http` 和 `ontapi` 应用程序。
+
。 `http` 和 `ontapi` 应用程序由以下Web服务使用：服务处理器基础架构、ONTAP API或System Manager。

* SAML 身份验证仅适用于访问管理 SVM 。


.步骤
. 创建 SAML 配置，以便 ONTAP 可以访问 IdP 元数据：
+
`*security saml-sp create -idp-uri _idp_uri_ -sp-host _ontap_host_name_*`

+
`idp_uri` 是可从中下载IdP元数据的IdP主机的FTP或HTTP地址。

+
`ontap_host_name` 是SAML服务提供程序主机的主机名或IP地址、此处为ONTAP系统。默认情况下，使用集群管理 LIF 的 IP 地址。

+
您可以选择提供 ONTAP 服务器证书信息。默认情况下，使用 ONTAP Web 服务器证书信息。

+
[listing]
----
cluster_12::> security saml-sp create -idp-uri https://scspr0235321001.gdl.englab.netapp.com/idp/shibboleth -verify-metadata-server false

Warning: This restarts the web server. Any HTTP/S connections that are active
         will be disrupted.
Do you want to continue? {y|n}: y
[Job 179] Job succeeded: Access the SAML SP metadata using the URL:
https://10.63.56.150/saml-sp/Metadata

Configure the IdP and Data ONTAP users for the same directory server domain to ensure that users are the same for different authentication methods. See the "security login show" command for the Data ONTAP user configuration.
----
+
此时将显示用于访问 ONTAP 主机元数据的 URL 。

. 在 IdP 主机中，使用 ONTAP 主机元数据配置 IdP 。
+
有关配置 IdP 的详细信息，请参见 IdP 文档。

. 启用 SAML 配置：
+
`*security saml-sp modify -is-enabled true*`

+
访问的任何现有用户 `http` 或 `ontapi` 系统会自动为应用程序配置SAML身份验证。

. 如果要为创建用户 `http` 或 `ontapi` 应用程序在配置SAML后、指定SAML作为新用户的身份验证方法。
+
.. 使用SAML身份验证为新用户创建登录方法：
+
`*security login create -user-or-group-name _user_name_ -application [http | ontapi] -authentication-method saml -vserver _svm_name_*`
+
[listing]
----
cluster_12::> security login create -user-or-group-name admin1 -application http -authentication-method saml -vserver  cluster_12
----
.. 验证是否已创建此用户条目：
+
`*security login show*`

+
[listing]
----
cluster_12::> security login show

Vserver: cluster_12
                                                                 Second
User/Group                 Authentication                 Acct   Authentication
Name           Application Method        Role Name        Locked Method
-------------- ----------- ------------- ---------------- ------ --------------
admin          console     password      admin            no     none
admin          http        password      admin            no     none
admin          http        saml          admin            -      none
admin          ontapi      password      admin            no     none
admin          ontapi      saml          admin            -      none
admin          service-processor
                           password      admin            no     none
admin          ssh         password      admin            no     none
admin1         http        password      backup           no     none
**admin1         http        saml          backup           -      none**
----




.相关信息
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9命令"^]
