---
permalink: system-admin/configure-access-web-services-task.html 
sidebar: sidebar 
keywords: configure, access, web, services, http, https, svm 
summary: 通过配置对 Web 服务的访问，授权用户可以使用 HTTP 或 HTTPS 访问集群或 Storage Virtual Machine （ SVM ）上的服务内容。 
---
= 配置对ONTAP Web 服务的访问
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过配置对 Web 服务的访问，授权用户可以使用 HTTP 或 HTTPS 访问集群或 Storage Virtual Machine （ SVM ）上的服务内容。

.步骤
. 如果启用了防火墙，请确保已在防火墙策略中为用于 Web 服务的 LIF 设置 HTTP 或 HTTPS 访问：
+
[NOTE]
====
您可以使用检查是否已启用防火墙 `system services firewall show` 命令：

====
+
.. 要验证是否已在防火墙策略中设置HTTP或HTTPS、请使用 `system services firewall policy show` 命令：
+
您可以设置 `-service` 的参数 `system services firewall policy create` 命令 `http` 或 `https` 以启用支持Web访问的策略。

.. 要验证支持HTTP或HTTPS的防火墙策略是否与提供Web服务的LIF关联、请使用 `network interface show` 命令 `-firewall-policy` 参数。
+
有关的详细信息 `network interface show`，请参见link:https://docs.netapp.com/us-en/ontap-cli/network-interface-show.html["ONTAP 命令参考"^]。

+
您可以使用 `network interface modify` 命令 `-firewall-policy` 用于使LIF的防火墙策略生效的参数。

+
有关的详细信息 `network interface modify`，请参见link:https://docs.netapp.com/us-en/ontap-cli/network-interface-modify.html["ONTAP 命令参考"^]。



. 要配置集群级别的Web协议引擎并使Web服务内容可访问、请使用 `system services web modify` 命令：
. 如果您计划使用安全Web服务(HTTPS)、请使用为集群或SVM启用SSL并提供数字证书信息 `security ssl modify` 命令：
+
有关的详细信息 `security ssl modify`，请参见link:https://docs.netapp.com/us-en/ontap-cli/security-ssl-modify.html["ONTAP 命令参考"^]。

. 要为集群或SVM启用Web服务、请使用 `vserver services web modify` 命令：
+
必须对要为集群或 SVM 启用的每个服务重复此步骤。

. 要授权某个角色访问集群或SVM上的Web服务、请使用 `vserver services web access create` 命令：
+
您授予访问权限的角色必须已存在。您可以使用显示现有角色 `security login role show` 命令或使用创建新角色 `security login role create` 命令：

+
有关和的 `security login role create`详细信息 `security login role show`，请参见link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+login+role["ONTAP 命令参考"^]。

. 对于已授权访问Web服务的角色、请检查的输出、确保为其用户配置了正确的访问方法 `security login show` 命令：
+
以访问ONTAP API Web服务  `ontapi`)、则必须为用户配置 `ontapi` 访问方法。要访问所有其他Web服务、必须为用户配置 `http` 访问方法。

+
有关的详细信息 `security login show`，请参见link:https://docs.netapp.com/us-en/ontap-cli/security-login-show.html["ONTAP 命令参考"^]。

+
[NOTE]
====
您可以使用 `security login create`命令为用户添加访问方法。有关的详细信息 `security login create`，请参见link:https://docs.netapp.com/us-en/ontap-cli/security-login-create.html["ONTAP 命令参考"^]。

====

