---
permalink: system-admin/create-banner-task.html 
sidebar: sidebar 
keywords: create, banner, svm, access, cluster, ssh, session 
summary: 您可以创建横幅、以便向尝试通过控制台或SSH会话访问集群或SVM的用户显示消息。 
---
= 创建ONTAP登录横幅
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以创建一个横幅，向尝试访问集群或 SVM 的用户显示一条消息。在提示用户进行身份验证之前，控制台会话（仅限集群访问）或 SSH 会话（适用于集群或 SVM 访问）会显示此横幅。

.步骤
. 使用 `security login banner modify` 用于为集群或SVM创建横幅的命令：
+
|===
| 如果您要 ... | 那么 ... 


 a| 
指定单行消息
 a| 
使用 `-message`""[.code]``<text>``参数指定文本。



 a| 
在消息中包括换行符（也称为行尾）
 a| 
在不使用的情况下使用命令 `-message` 或 `-uri` 用于启动交互模式以编辑横幅的参数。



 a| 
从某个位置上传要用于横幅的内容
 a| 
使用 `-uri` 用于指定内容的FTP或HTTP位置的参数。

|===
+
横幅的最大大小为 2 ， 048 字节，包括换行符。

+
使用创建的横幅 `-uri` 参数是静态的。它不会自动刷新以反映源内容的后续更改。

+
为集群创建的横幅也会显示所有没有现有横幅的 SVM 。此后为 SVM 创建的任何横幅都会覆盖该 SVM 的集群级别横幅。指定 `-message` 参数、双引号内含连字符 (`"-"`)将SVM重置为使用集群级别的横幅。

. 通过使用显示横幅来验证是否已创建此横幅 `security login banner show` 命令：
+
指定 `-message` 带有空字符串的参数 (`""`)显示无内容的横幅。

+
指定 `-message` 带的参数 `"-"` 显示未配置横幅的所有(管理或数据) SVM。



.创建横幅的示例
以下示例使用非交互模式为 "`cluster1` " 集群创建横幅：

[listing]
----
cluster1::> security login banner modify -message "Authorized users only!"

cluster1::>
----
以下示例将使用交互模式为SVM创建横幅 `svm1`：

[listing]
----
cluster1::> security login banner modify -vserver svm1

Enter the message of the day for Vserver "svm1".
Max size: 2048. Enter a blank line to terminate input. Press Ctrl-C to abort.
0        1         2         3         4         5         6         7         8
12345678901234567890123456789012345678901234567890123456789012345678901234567890
The svm1 SVM is reserved for authorized users only!


cluster1::>
----
以下示例显示了已创建的横幅：

[listing]
----
cluster1::> security login banner show
Vserver: cluster1
Message
-----------------------------------------------------------------------------
Authorized users only!

Vserver: svm1
Message
-----------------------------------------------------------------------------
The svm1 SVM is reserved for authorized users only!

2 entries were displayed.

cluster1::>
----
.相关信息
xref:manage-banner-reference.adoc[管理横幅]
