---
permalink: system-admin/download-nlf-task.html 
sidebar: sidebar 
keywords: install, license, convert, download, add, record, software, entitlement, keys, codes, cluster, administrator, nlf 
summary: 如果您的系统运行的是ONTAP 9.10.1或更高版本、则可以通过从NetApp 支持站点 下载适用于ONTAP One或ONTAP Core的NLF来升级现有系统上的许可证文件或28个字符的许可证密钥。 
---
= 从NetApp 支持站点 下载NetApp许可证文件(NLG)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您的系统运行的是ONTAP 9.10.1或更高版本、则可以通过从NetApp 支持站点 下载适用于ONTAP One或ONTAP Core的NLF来升级现有系统上的捆绑包许可证文件。


NOTE: ONTAP One不附带SnapMirror云和S3 SnapMirror许可证。它们是ONTAP One兼容性包的一部分、如果您有ONTAP One和、可以免费获取 https://review.docs.netapp.com/us-en/ontap_lenida-ontap-licensing-jira1366/data-protection/install-snapmirror-cloud-license-task.html["单独申请"]。

.步骤
对于具有现有NetApp许可证文件包的系统以及运行ONTAP 9.10.1及更高版本的系统上具有28个字符的许可证密钥且已转换为NetApp许可证文件的系统、您可以下载ONTAP One许可证文件。您还可以付费将系统从ONTAP Base升级到ONTAP One。

[role="tabbed-block"]
====
.升级现有NLG
--
. 请联系您的NetApp销售团队并请求要升级或转换的许可证文件包(例如、将ONTAP基础版升级到ONTAP One、或将核心包和数据保护包升级到ONTAP One)。
+
处理您的申请后、您将收到一封来自netappsw@netapp.com NetApp的电子邮件、主题为"SO#[SO编号]"、该电子邮件将包含一个PDF附件、其中包含您的许可证序列号。

. 登录到 link:https://mysupport.netapp.com/site/["NetApp 支持站点"^]。
. 选择*系统>软件许可证*。
. 从菜单中选择*Serial Number*，输入您收到的序列号，然后单击*New Search*。
. 找到要转换的许可证包。
. 单击每个许可证包的*获取NetApp许可证文件*，然后下载可用的NLFS。
. link:https://review.docs.netapp.com/us-en/ontap_lenida-ontap-licensing-jira1366/system-admin/install-license-task.html["安装"] ONTAP One文件。


--
.升级从许可证密钥转换而来的NLL
--
. 登录到 link:https://mysupport.netapp.com/site/["NetApp 支持站点"^]。
. 选择*系统>软件许可证*。
. 从菜单中选择*Serial Number*，输入系统序列号，然后单击*New Search*。
. 找到要转换的许可证，然后在*资格*列中单击*检查*。
. 在*检查资格表*中，单击*生成9.10.x及更高版本的许可证*。
. 关闭*检查资格表*。
+
您需要至少等待2小时、才能生成许可证。

. 重复步骤1至3。
. 找到ONTAP One许可证，单击*获取NetApp许可证文件*，然后选择交付方式。
. link:https://review.docs.netapp.com/us-en/ontap_lenida-ontap-licensing-jira1366/system-admin/install-license-task.html["安装"] ONTAP One文件。


--
====