---
permalink: system-admin/health-monitors-concept.html 
sidebar: sidebar 
keywords: available, cluster, health, monitors, errors, detect, events, alerts, delete 
summary: 有多个运行状况监控器可监控集群的不同部分。运行状况监控器可以检测事件，向您发送警报以及在清除事件后删除事件，从而帮助您从 ONTAP 系统中的错误中恢复。 
---
= 了解可用的ONTAP集群运行状况监控器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
有多个运行状况监控器可监控集群的不同部分。运行状况监控器可以检测事件，向您发送警报以及在清除事件后删除事件，从而帮助您从 ONTAP 系统中的错误中恢复。

|===
| 运行状况监控器名称（标识符） | 子系统名称（标识符） | 目的 


 a| 
以太网交换机
 a| 
交换机（交换机运行状况）
 a| 
ONTAP以太网交换机运行状况监控器(CSHM)可监控集群和存储网络交换机的状态、同时收集日志以供分析。默认情况下、CSHM通过SNMPv2c每5分钟轮询一次每个交换机、以便使用有关可支持性、监控状态、温度传感器、CPU利用率、接口配置和连接、集群交换机冗余以及风扇和电源操作的信息更新资源表。此外、如果已配置、CSHM每小时通过SSH/SCP收集一次日志、这些日志将通过AutoSupport发送以供进一步分析。根据请求、CSHM还可以使用SSH/SCP执行更详细的技术支持日志收集。

有关详细信息、请参见 link:https://docs.netapp.com/us-en/ontap-systems-switches/switch-cshm/config-overview.html["交换机运行状况监控"^] 。



 a| 
MetroCluster 网络结构
 a| 
交换机
 a| 
监控 MetroCluster 配置后端网络结构拓扑并检测错误配置，例如布线和分区不正确以及 ISL 故障。



 a| 
MetroCluster 运行状况
 a| 
互连， RAID 和存储
 a| 
监控 FC-VI 适配器， FC 启动程序适配器，左后聚合和磁盘以及集群间端口



 a| 
节点连接（节点连接）
 a| 
CIFS 无中断运行（ CIFS-NDO ）
 a| 
监控 SMB 连接，确保 Hyper-V 应用程序无中断运行。



 a| 
存储（ SAS 连接）
 a| 
监控节点级别的磁盘架，磁盘和适配器，以查看适当的路径和连接。



 a| 
系统
 a| 
不适用
 a| 
聚合来自其他运行状况监控器的信息。



 a| 
系统连接（ system-connect ）
 a| 
存储（ SAS 连接）
 a| 
监控集群级别的磁盘架，以获取指向两个 HA 集群节点的适当路径。

|===