---
permalink: system-admin/keyboard-shortcuts-edit-cli-commands-reference.html 
sidebar: sidebar 
keywords: keyboard, shortcuts, edit, cli, commands, unix, tcsh, shell, emacs, editor, active 
summary: 当前命令提示符处的命令为活动命令。使用快捷键可以快速编辑活动命令。这些快捷键类似于 UNIX tcsh shell 和 Emacs 编辑器的快捷键。 
---
= 用于编辑 CLI 命令的快捷键
:icons: font
:imagesdir: ../media/


[role="lead"]
当前命令提示符处的命令为活动命令。使用快捷键可以快速编辑活动命令。这些快捷键类似于 UNIX tcsh shell 和 Emacs 编辑器的快捷键。

下表列出了用于编辑命令行界面命令的快捷键。"`Ctrl-` " 表示您在按住 Ctrl 键的同时键入其后指定的字符。"`Esc-` " 表示按下并释放 Esc 键，然后键入其后指定的字符。

|===
| 如果您要 ... | 使用以下快捷键 ... 


 a| 
将光标移回一个字符
 a| 
Ctrl-B



 a| 
后退箭头



 a| 
将光标前移一个字符
 a| 
Ctrl-F



 a| 
向前箭头



 a| 
将光标移回一个词
 a| 
ESP-B



 a| 
将光标前移一个词
 a| 
ESP-F



 a| 
将光标移动到行首
 a| 
Ctrl-A



 a| 
将光标移动到行尾
 a| 
Ctrl-E



 a| 
删除从行首到光标的命令行内容，并将其保存在剪切缓冲区中。剪切缓冲区的作用类似于临时内存，类似于某些程序中的 _clipboard_ 。
 a| 
Ctrl-U



 a| 
删除从光标到行尾的命令行内容，并将其保存在剪切缓冲区中
 a| 
Ctrl-K



 a| 
删除从光标到以下词尾的命令行内容，并将其保存在剪切缓冲区中
 a| 
ESP-D



 a| 
删除光标前面的词，并将其保存在剪切缓冲区中
 a| 
Ctrl-W



 a| 
Yank the content of the cut buffer ， and push it into the command line at the cursor
 a| 
Ctrl-Y



 a| 
删除光标前面的字符
 a| 
Ctrl-H



 a| 
退格



 a| 
删除光标所在的字符
 a| 
Ctrl-D



 a| 
清除此行
 a| 
Ctrl-C



 a| 
清除屏幕
 a| 
Ctrl-L



 a| 
将命令行的当前内容替换为历史记录列表上的上一条目。

每次重复键盘快捷键时，历史记录光标都会移至上一条。
 a| 
Ctrl-P



 a| 
ESP-P



 a| 
向上箭头



 a| 
将命令行的当前内容替换为历史记录列表中的下一个条目。每次重复键盘快捷键时，历史记录光标都会移动到下一个条目。
 a| 
Ctrl-N



 a| 
Esc-N



 a| 
向下箭头



 a| 
从当前编辑位置展开部分输入的命令或列出有效输入
 a| 
选项卡



 a| 
Ctrl-I



 a| 
显示上下文相关帮助
 a| 
？



 a| 
转义问号的特殊映射（ "` ？` " ） 字符。例如，要在命令的参数中输入问号，请按 Esc ，然后按 "` ？` " 字符。
 a| 
Esc- ？



 a| 
启动 TTY 输出
 a| 
Ctrl-Q



 a| 
停止 TTY 输出
 a| 
Ctrl-S

|===