---
permalink: system-admin/license-types-licensed-method-concept.html 
sidebar: sidebar 
keywords: license, types, method, cluster, manage, install, add, nlf 
summary: 了解许可证类型和许可方法有助于管理集群中的许可证。 
---
= 许可证类型和许可方法
:icons: font
:imagesdir: ../media/


[role="lead"]
了解许可证类型和许可方法有助于管理集群中的许可证。



== 许可证类型

一个许可证包可以在集群中安装以下一种或多种许可证类型。system license show` 命令可显示软件包的已安装许可证类型。 `s

* 标准许可证（`license` ）
+
标准许可证是节点锁定许可证。它是为具有特定系统序列号（也称为 _controller 序列号）的节点颁发的。标准许可证仅对具有匹配序列号的节点有效。

+
安装标准的节点锁定许可证后，节点将有权使用许可功能。要使集群能够使用许可功能，必须至少为一个节点授予使用此功能的许可。在无权使用许可功能的节点上使用此功能可能不合规。

* 站点许可证（ `site` ）
+
站点许可证不与特定系统序列号绑定。安装站点许可证时，集群中的所有节点均有权使用许可的功能。system license show` 命令可在集群序列号下显示站点许可证。 `s

+
如果您的集群具有站点许可证，而您从集群中删除了某个节点，则该节点将不会再拥有站点许可证，并且不再有权使用许可的功能。如果向具有站点许可证的集群添加节点，则该节点将自动获得使用站点许可证授予的功能的权限。

* 评估许可证（ `demo` ）
+
评估版许可证是一种临时许可证，它会在一段时间后过期（由 `ssystem license show` 命令指示）。您可以通过它尝试某些软件功能，而无需购买授权。它是一个集群范围的许可证，不与节点的特定序列号绑定。

+
如果您的集群具有某个软件包的评估许可证，而您从集群中删除了某个节点，则该节点不会附带此评估许可证。





== 许可方法

可以为软件包同时安装集群范围许可证（ `site` 或 `demo` 类型）和节点锁定许可证（ `license` 类型）。因此，已安装的软件包在集群中可以具有多种许可证类型。但是，对于集群，一个软件包只有一个 _licensed method 。`ssystem license status show` 命令的 `licensed method` 字段显示了软件包所使用的授权。命令将按如下所示确定许可方法：

* 如果某个许可证包在集群中仅安装了一种许可证类型，则已安装的许可证类型为许可方法。
* 如果某个软件包未在集群中安装任何许可证，则许可方法为 `none` 。
* 如果某个许可证包在集群中安装了多种许可证类型，则许可方法将按以下许可证类型的优先级顺序确定— `site` ， `license` 和 `demo` 。
+
例如：

+
** 如果某个许可证包具有站点许可证，标准许可证和评估许可证，则集群中该许可证包的许可方法为 `site` 。
** 如果某个许可证包具有标准许可证和评估许可证，则集群中该许可证包的许可方法为 `license` 。
** 如果某个许可证包只有评估许可证，则集群中该许可证包的许可方法为 `demo` 。



