---
permalink: system-admin/manage-licenses-concept.html 
sidebar: sidebar 
keywords: manage, license, ontap one, enable, add, record, software, entitlement, keys, codes, risk, usage, cluster, administrator, nlf 
summary: '许可证是一个或多个软件授权的记录。从ONTAP 9.10.1开始、所有许可证均以NetApp许可证文件(NLG)的形式提供、NLG是一个支持多项功能的文件。  从2023年5月开始、所有AFF系统(A系列和C系列)和FAS系统均随ONTAP One软件套件或ONTAP基础软件套件一起销售；从2023年6月开始、所有ASA系统均随ONTAP One for SAN一起销售。' 
---
= ONTAP许可概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
许可证是一个或多个软件授权的记录。从ONTAP 9.10.1开始、所有许可证均以NetApp许可证文件(NLG)的形式提供、NLG是一个支持多项功能的文件。  从2023年5月开始、所有AFF系统(A系列和C系列)和FAS系统均随ONTAP One软件套件或ONTAP基础软件套件一起销售；从2023年6月开始、所有ASA系统均随ONTAP One for SAN一起销售。每个软件套件都作为一个NLL提供、以替代ONTAP 9.10.1中首次推出的单独NLL捆绑包。



== ONTAP One附带的许可证

ONTAP One包含所有可用的许可功能。它包含以前的Core捆绑包、数据保护捆绑包、安全与合规性捆绑包、混合云捆绑包和加密捆绑包的内容组合、如表所示。加密在受限国家/地区不可用。

|===


| 以前的捆绑包名称 | 包括ONTAP密钥 


.5+| 核心包 | FlexClone 


| SnapRestore 


| NFS、SMB、S3 


| FC、iSCSI 


| NVMe-oF 


.3+| 安全性与合规性包 | 自主勒索软件保护 


| MTKM 


| SnapLock 


.3+| 数据保护包 | SnapMirror (异步、同步、业务连续性) 


| SnapCenter 


| 适用于NetApp目标的SnapMirror S3 


.2+| 混合云捆绑包 | SnapMirror云 


| 适用于非NetApp目标的SnapMirror S3 


.2+| 加密包 | NetApp 卷加密 


| 可信平台模块 
|===


== ONTAP One不提供许可证

ONTAP One不包括NetApp的任何云交付服务、包括以下服务：

* BlueXP层
* Cloud Insights
* BlueXP备份
* 数据监管




== 适用于现有系统的ONTAP One

如果您的现有系统当前受NetApp支持、但尚未升级到ONTAP One、则这些系统上的现有许可证仍然有效、并继续按预期工作。例如、如果已在现有系统上安装了SnapMirror许可证、则无需升级到ONTAP One即可获得新的SnapMirror许可证。但是、如果现有系统上未安装SnapMirror许可证、则获取该许可证的唯一方法是升级到ONTAP One、但需额外付费。

从2023年6月开始、使用28个字符许可证密钥的ONTAP系统也可以 link:https://kb.netapp.com/onprem/ontap/os/How_to_get_an_ONTAP_One_license_when_the_system_has_28_character_keys["升级到ONTAP One或ONTAP基本兼容包"]。



== ONTAP Base附带的许可证

ONTAP Base是一个可选软件套件、可替代适用于ONTAP系统的ONTAP One。它适用于不需要数据保护技术(如SnapMirror和SnapCenter)以及安全功能(如自动防软件)的特定使用情形、例如专用测试或开发环境的非生产系统。无法向ONTAP Base添加其他许可证。如果您需要SnapMirror等其他许可证、则必须升级到ONTAP One。

|===


| 以前的捆绑包名称 | 包括ONTAP密钥 


.5+| 核心包 | FlexClone 


| SnapRestore 


| NFS、SMB、S3 


| FC、iSCSI 


| NVMe-oF 


.2+| 加密包 | NetApp 卷加密 


| 可信平台模块 
|===


== ONTAP One for SAN附带的许可证

适用于SAN的ONTAP One可用于ASA A系列和C系列系统。这是唯一可用于SAN的软件套件。ONTAP One for SAN包含以下许可证：

|===


| 包括ONTAP密钥 


| FlexClone 


| SnapRestore 


| FC、iSCSI 


| NVMe-oF 


| MTKM 


| SnapLock 


| SnapMirror (异步、同步、业务连续性) 


| SnapCenter 


| SnapMirror云 


| NetApp 卷加密 


| 可信平台模块 
|===


== 其他许可证交付方法

在 ONTAP 8.2 到 ONTAP 9.1.1 中，许可证密钥以 28 个字符串的形式提供，每个 ONTAP 功能有一个密钥。如果您使用的是ONTAP 8.2到ONTAP 9.9.1、则可以使用ONTAP命令行界面安装许可证密钥。

[NOTE]
====
ONTAP 9.10.1支持使用System Manager或命令行界面安装28个字符的许可证密钥。但是、如果为某个功能安装了NLL许可证、则不能在同一功能的NetApp许可证文件上安装28个字符的许可证密钥。有关使用System Manager安装NLFS或许可证密钥的信息、请参阅 link:https://docs.netapp.com/us-en/ontap/system-admin/install-license-task.html["安装ONTAP许可证"]。

====
.相关信息
https://kb.netapp.com/onprem/ontap/os/How_to_get_an_ONTAP_One_license_when_the_system_has_NLFs_already["如何在系统已具有NLFS时获取ONTAP One许可证"]

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_verify_Data_ONTAP_Software_Entitlements_and_related_License_Keys_using_the_Support_Site["如何使用支持站点验证ONTAP软件授权和相关许可证密钥"^]

http://mysupport.netapp.com/licensing/ontapentitlementriskstatus["NetApp：ONTAP授权风险状态"^]
