---
permalink: system-admin/manage-node-root-volumes-aggregates-task.html 
sidebar: sidebar 
keywords: node, governing, root, volume, aggregate, files, special, directories, free, space, full, delete, file, core, dump 
summary: 节点的根卷是指出厂时或由设置软件安装的 FlexVol 卷。 
---
= 管理节点根卷和根聚合
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
节点的根卷是指出厂时或由设置软件安装的 FlexVol 卷。它是为系统文件，日志文件和核心文件预留的。目录名称为 `/mroot`，只能由技术支持通过systemshell访问。节点根卷的最小大小取决于平台型号。



== 节点根卷和根聚合的规则概述

节点的根卷包含该节点的特殊目录和文件。根聚合包含根卷。节点的根卷和根聚合需要遵循一些规则。

* 以下规则用于控制节点的根卷：
+
** 除非技术支持指示您这样做，否则请勿修改根卷的配置或内容。
** 请勿将用户数据存储在根卷中。
+
将用户数据存储在根卷中会增加 HA 对中节点之间的存储交还时间。

** 您可以将根卷移动到另一个聚合。  请参见 <<relocate-root>>。


* 根聚合仅专用于节点的根卷。
+
ONTAP 会阻止您在根聚合中创建其他卷。



https://hwu.netapp.com["NetApp Hardware Universe"^]



== 释放节点根卷上的空间

当节点的根卷已满或接近已满时、会显示一条警告消息。当节点的根卷已满时、该节点无法正常运行。您可以通过删除核心转储文件、数据包跟踪文件和根卷快照来释放节点根卷上的空间。

.步骤
. 显示节点的核心转储文件及其名称：
+
`system node coredump show`

. 从节点中删除不需要的核心转储文件：
+
`system node coredump delete`

. 访问 nodeshell ：
+
`*system node run -node _nodename_*`

+
`_nodename_` 是要释放其根卷空间的节点的名称。

. 从 nodeshell 切换到 nodeshell 高级权限级别：
+
`*priv set advanced*`

. 通过 nodeshell 显示和删除节点的数据包跟踪文件：
+
.. 显示节点根卷中的所有文件：
+
`*ls /etc*`

.. 如果有任何数据包跟踪文件 (`*.trc`)、请逐个删除它们：
+
`*rm /etc/log/packet_traces/_file_name.trc_*`



. 通过nokeshell确定并删除节点的根卷快照：
+
.. 确定根卷名称：
+
`*vol status*`

+
的`Options`(选项`)列中的单词"`root "表示根卷 `vol status` 命令输出。

+
在以下示例中、根卷为 `vol0`：

+
[listing]
----
node1*> vol status

         Volume State           Status            Options
           vol0 online          raid_dp, flex     root, nvfail=on
                                64-bit
----
.. 显示根卷快照：
+
`snap list root_vol_name`

.. 删除不需要的根卷快照：
+
`snap delete root_vol_namesnapshot_name`



. 退出 nodeshell 并返回到 clustershell ：
+
`*exit*`





== 将根卷重新定位到新聚合

根替换操作步骤可将当前根聚合迁移到另一组磁盘，而不会造成中断。

.关于此任务
要重新定位根卷，必须启用存储故障转移。您可以使用 `storage failover modify -node _nodename_ -enable true` 命令以启用故障转移。

在以下情况下，您可以将根卷的位置更改为新聚合：

* 根聚合不在您首选的磁盘上时
* 重新排列连接到节点的磁盘时
* 在执行 EOS 磁盘架的磁盘架更换时


.步骤
. 将权限级别设置为高级：
+
`*set privilege advanced*`

. 重新定位根聚合：
+
`*system node migrate-root -node _nodename_ -disklist _disklist_ -raid-type _raid-type_*`

+
** * 节点 *
+
指定拥有要迁移的根聚合的节点。

** * 磁盘列表 *
+
指定要在其中创建新根聚合的磁盘的列表。所有磁盘都必须为备用磁盘，并归同一节点所有。所需的最小磁盘数取决于 RAID 类型。

** * — RAID 类型 *
+
指定根聚合的 RAID 类型。默认值为 `raid-dp`。



. 监控作业进度：
+
`*job show -id _jobid_ -instance*`



.结果
如果所有预检均成功，则该命令将启动根卷更换作业并退出。希望节点重新启动。
