---
permalink: system-admin/manage-licenses-concept.html 
sidebar: sidebar 
keywords: manage, license, enable, add, record, software, entitlement, keys, codes, risk, usage, cluster, administrator, nlf 
summary: 许可证是一个或多个软件授权的记录。在 ONTAP 8.2 到 ONTAP 9.1.1 中，许可证以 28 个字符串的形式提供，每个 ONTAP 功能有一个密钥。ONTAP 9.2 中引入了一种新的许可证格式，称为 NetApp 许可证文件（ NLF ），该格式仅适用于集群范围的功能，例如 FabricPool 。 
---
= 管理许可证概述（仅限集群管理员）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
许可证是一个或多个软件授权的记录。在 ONTAP 8.2 到 ONTAP 9.1.1 中，许可证密钥以 28 个字符串的形式提供，每个 ONTAP 功能有一个密钥。ONTAP 9.2 中引入了一种新的许可证密钥格式，称为 NetApp 许可证文件（ NLF ），该格式仅适用于集群范围的功能，例如 FabricPool 。

从 ONTAP 9.10.1 开始，所有许可证均以 NLFS 的形式提供。根据您的购买情况， nlf 许可证可以启用一个或多个 ONTAP 功能。您可以通过搜索系统（控制器）序列号从 NetApp 支持站点检索 NLF 许可证。

您可以在 NetApp 支持站点的 * 我的支持 * > * 软件许可证 * 下找到初始或附加软件订单的许可证（需要登录）。如果您无法从 " 软件许可证 " 页面找到许可证密钥，请联系您的销售或支持代表。

使用 ONTAP ，您可以通过以下方式管理功能许可证：

* 显示有关已安装许可证的信息（ `ssystem license show` ）
* 在集群上显示需要许可证的软件包及其当前许可证状态（ `ssystem license status show` ）
* 从您指定序列号的集群或节点中删除许可证（ `ssystem license delete` ）
* 显示或删除已过期或未使用的许可证（ `s系统许可证清理` ）


通过 ONTAP ，您可以通过以下方式监控功能使用情况和许可证授权风险：

* 按节点显示集群中功能使用情况的摘要（ `ssystem feature-usage show-summary` ）
+
此摘要包含计数器信息，例如使用某个功能的周数以及上次使用该功能的日期和时间。

* 按节点和每周显示集群中的功能使用状态（ `ssystem feature-usage show-history` ）
+
功能使用状态可以是 `not-used` ， `configured` 或 `in-use` 。如果使用情况信息不可用，则状态将显示 `not-available` 。

* 显示每个许可证包的许可证授权风险状态（ `ssystem license entitlement-risk show` ）
+
风险状态可以是 `low` ， `medium` ， `high` ， `unlicensed` 或 `unknown` 。风险状态也会显示在 AutoSupport 消息中。许可证授权风险不适用于基本许可证包。

+
许可证授权风险会使用多种因素进行评估，这些因素可能包括但不限于以下因素：

+
** 每个软件包的许可状态
** 每个许可证的类型，到期状态以及整个集群中许可证的统一性
** 与许可证包关联的功能的使用如果评估过程确定集群存在许可证授权风险，则命令输出还会建议更正操作。




[NOTE]
====
注意： ONTAP 9.10.1 还支持使用 System Manager 或命令行界面使用 28 个字符的许可证密钥。但是，如果为某个功能安装了 NLF 许可证，则不能为同一功能安装 28 个字符的许可证密钥。有关使用 System Manager 安装 NLFS 或许可证密钥的信息，请参见 " 启用新功能 " 。

====
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/What_are_Data_ONTAP_8.2_and_8.3_licensing_overview_and_references%3F["什么是 Data ONTAP 8.2 和 8.3 许可概述和参考？"]

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_verify_Data_ONTAP_Software_Entitlements_and_related_License_Keys_using_the_Support_Site["如何使用支持站点验证 Data ONTAP 软件授权和相关许可证密钥"]

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/FAQ%3A_Licensing_updates_in_Data_ONTAP_9.2["常见问题解答： Data ONTAP 9.2 中的许可更新"]

http://mysupport.netapp.com/licensing/ontapentitlementriskstatus["NetApp ： Data ONTAP 授权风险状态"]
