---
permalink: system-admin/manage-cli-sessions.html 
sidebar: sidebar 
keywords: record, cli, script, start, stop, session 
summary: 您可以将命令行界面会话记录到具有指定名称和大小限制的文件中，然后将此文件上传到 FTP 或 HTTP 目标。 
---
= 在ONTAP中管理命令行界面会话
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以将命令行界面会话记录到具有指定名称和大小限制的文件中，然后将此文件上传到 FTP 或 HTTP 目标。您还可以显示或删除先前记录了命令行界面会话的文件。



== 记录 CLI 会话

当您停止录制或结束 CLI 会话时，或者当文件达到指定的大小限制时， CLI 会话记录将结束。默认文件大小限制为 1 MB 。最大文件大小限制为 2 GB 。

记录命令行界面会话非常有用，例如，如果您正在对问题描述进行故障排除并希望保存详细信息，或者您希望在特定时间点创建永久的空间使用量记录。

.步骤
. 开始将当前命令行界面会话记录到文件中：
+
[source, cli]
----
system script start
----
+
有关的详细信息 `system script start`，请参见link:https://docs.netapp.com/us-en/ontap-cli/system-script-start.html["ONTAP 命令参考"^]。

+
ONTAP 将开始将命令行界面会话记录到指定文件中。

. 继续进行命令行界面会话。
. 完成后、停止记录会话：
+
[source, cli]
----
system script stop
----
+
有关的详细信息 `system script stop`，请参见link:https://docs.netapp.com/us-en/ontap-cli/system-script-stop.html["ONTAP 命令参考"^]。

+
ONTAP 将停止记录命令行界面会话。





== 用于管理 CLI 会话记录的命令

您可以使用 `system script` 用于管理CLI会话记录的命令。

|===
| 如果您要 ... | 使用此命令 ... 


 a| 
开始将当前命令行界面会话记录到指定文件中
 a| 
`system script start`



 a| 
停止记录当前命令行界面会话
 a| 
`system script stop`



 a| 
显示有关 CLI 会话记录的信息
 a| 
`system script show`



 a| 
将命令行界面会话记录上传到 FTP 或 HTTP 目标
 a| 
`system script upload`



 a| 
删除 CLI 会话记录
 a| 
`system script delete`

|===
.相关信息
link:../concepts/manual-pages.html["ONTAP 命令参考"]



== 用于管理 CLI 会话自动超时期限的命令

超时值用于指定 CLI 会话在自动终止之前保持空闲多长时间。CLI 超时值为集群范围。也就是说，集群中的每个节点都使用相同的 CLI 超时值。

默认情况下， CLI 会话的自动超时期限为 30 分钟。

您可以使用 `system timeout` 用于管理CLI会话自动超时期限的命令。

|===
| 如果您要 ... | 使用此命令 ... 


 a| 
显示 CLI 会话的自动超时期限
 a| 
`system timeout show`



 a| 
修改 CLI 会话的自动超时期限
 a| 
`system timeout modify`

|===
.相关信息
link:../concepts/manual-pages.html["ONTAP 命令参考"]
