---
permalink: system-admin/manage-access-web-services-concept.html 
sidebar: sidebar 
keywords: 'manage, access, web, service, http, https, cluster, administrator, web, protocol, engine, ssl, role, api, ontapi, disco, supdiag, sysmgr, fw, bmc, docs, "docs_api", fud, ontapmsg, portal, rest, saml, backup, back up, security, csrf' 
summary: Web 服务是用户可以使用 HTTP 或 HTTPS 访问的应用程序。集群管理员可以设置 Web 协议引擎，配置 SSL ，启用 Web 服务以及使某个角色的用户能够访问 Web 服务。 
---
= 管理对 Web 服务概述的访问
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Web 服务是用户可以使用 HTTP 或 HTTPS 访问的应用程序。集群管理员可以设置 Web 协议引擎，配置 SSL ，启用 Web 服务以及使某个角色的用户能够访问 Web 服务。

从 ONTAP 9.6 开始，支持以下 Web 服务：

* 服务处理器基础架构 (`spi`）
+
此服务使节点的日志，核心转储和 MIB 文件可通过集群管理 LIF 或节点管理 LIF 进行 HTTP 或 HTTPS 访问。默认设置为 `enabled`。

+
在请求访问节点的日志文件或核心转储文件时、 `spi` Web服务会自动创建从一个节点到文件所在的另一节点根卷的挂载点。您无需手动创建挂载点。` 。

* ONTAP API (`ontapi`）
+
通过此服务，您可以运行 ONTAP API ，以便使用远程程序执行管理功能。默认设置为 `enabled`。

+
某些外部管理工具可能需要此服务。例如，如果您使用 System Manager ，则应保持此服务处于启用状态。

* Data ONTAP发现 (`disco`）
+
通过此服务，机下管理应用程序可以发现网络中的集群。默认设置为 `enabled`。

* 支持诊断 (`supdiag`）
+
此服务可控制对系统上特权环境的访问，以协助分析和解决问题。默认设置为 `disabled`。只有在技术支持的指导下，才应启用此服务。

* System Manager (`sysmgr`）
+
此服务用于控制 ONTAP 附带的 System Manager 的可用性。默认设置为 `enabled`。此服务仅在集群上受支持。

* 固件基板管理控制器(BMC)更新 (`FW_BMC`）
+
通过此服务，您可以下载 BMC 固件文件。默认设置为 `enabled`。

* ONTAP 文档 (`docs`）
+
通过此服务可以访问 ONTAP 文档。默认设置为 `enabled`。

* ONTAP REST API (`docs_api`）
+
通过此服务，您可以访问 ONTAP RESTful API 文档。默认设置为 `enabled`。

* 文件上传和下载 (`fud`）
+
此服务提供文件上传和下载。默认设置为 `enabled`。

* ONTAP消息传送 (`ontapmsg`）
+
此服务支持发布和订阅界面，允许您订阅事件。默认设置为 `enabled`。

* ONTAP门户 (`portal`）
+
此服务将网关实施到虚拟服务器中。默认设置为 `enabled`。

* ONTAP restful界面 (`rest`）
+
此服务支持 RESTful 接口，用于远程管理集群基础架构的所有要素。默认设置为 `enabled`。

* 安全断言标记语言(SAML)服务提供程序支持 (`saml`）
+
此服务可提供支持 SAML 服务提供程序的资源。默认设置为 `enabled`。

* SAML服务提供程序 (`saml-sp`）
+
此服务可为服务提供商提供 SP 元数据和断言使用者服务等服务。默认设置为 `enabled`。



从 ONTAP 9.7 开始，支持以下附加服务：

* 配置备份文件 (`backups`）
+
使用此服务可以下载配置备份文件。默认设置为 `enabled`。

* ONTAP安全性 (`security`）
+
此服务支持 CSRF 令牌管理以增强身份验证。默认设置为 `enabled`。


