---
permalink: system-admin/manage-jobs-schedules.html 
sidebar: sidebar 
keywords: job, categories, server, cluster, affiliated, private, commands, managing, show jobs, job schedule, stop a job, delete a job, pause a job, display private jobs, modify, cron, interval, delete, interval schedule, manage jobs and schedule, manage jobs, manage schedule 
summary: 作业将置于作业队列中，并在资源可用时在后台运行。如果作业占用的集群资源过多，您可以将其停止或暂停，直到对集群的需求减少为止。您还可以监控和重新启动作业。 
---
= 管理作业和计划
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


作业将置于作业队列中，并在资源可用时在后台运行。如果作业占用的集群资源过多，您可以将其停止或暂停，直到对集群的需求减少为止。您还可以监控和重新启动作业。



== 作业类别

您可以管理三类作业：服务器附属作业，集群附属作业和私有作业。

作业可以属于以下任一类别：

* * 服务器附属作业 *
+
管理框架会将这些作业排入要运行的特定节点的队列。

* * 集群附属作业 *
+
管理框架会将这些作业排入要运行的集群中的任何节点的队列。

* * 私有作业 *
+
这些作业是特定于节点的，不使用复制的数据库（ RDB ）或任何其他集群机制。用于管理私有作业的命令需要高级权限级别或更高权限级别。





== 用于管理作业的命令

当您输入用于调用作业的命令时，通常该命令会通知您作业已排队，然后返回到命令行界面命令提示符。但是，某些命令会报告作业进度，并且在作业完成之前不会返回到命令行界面命令提示符。在这些情况下，您可以按 Ctrl-C 将作业移至后台。

|===
| 如果您要 ... | 使用此命令 ... 


 a| 
显示有关所有作业的信息
 a| 
`job show`



 a| 
按节点显示有关作业的信息
 a| 
`job show bynode`



 a| 
显示有关集群附属作业的信息
 a| 
`job show-cluster`



 a| 
显示有关已完成作业的信息
 a| 
`job show-completed`



 a| 
显示有关作业历史记录的信息
 a| 
`job history show`

集群中每个节点最多可存储 25 ， 000 个作业记录。因此，尝试显示完整的作业历史记录可能需要很长时间。为了避免可能出现的长时间等待，您应按节点， Storage Virtual Machine （ SVM ）或记录 ID 显示作业。



 a| 
显示私有作业的列表
 a| 
`job private show` （高级权限级别）



 a| 
显示有关已完成的私有作业的信息
 a| 
`job private show-completed` （高级权限级别）



 a| 
显示有关作业管理器初始化状态的信息
 a| 
`job initstate show` （高级权限级别）



 a| 
监控作业进度
 a| 
`job watch-progress`



 a| 
监控专用作业的进度
 a| 
`job private watch-progress` （高级权限级别）



 a| 
暂停作业
 a| 
`job pause`



 a| 
暂停私有作业
 a| 
`job private pause` （高级权限级别）



 a| 
恢复暂停的作业
 a| 
`job resume`



 a| 
恢复暂停的私有作业
 a| 
`job private resume` （高级权限级别）



 a| 
停止作业
 a| 
`job stop`



 a| 
停止私有作业
 a| 
`job private stop` （高级权限级别）



 a| 
删除作业
 a| 
`job delete`



 a| 
删除私有作业
 a| 
`job private delete` （高级权限级别）



 a| 
解除集群附属作业与拥有该作业的不可用节点的关联，以便其他节点可以接管该作业的所有权
 a| 
`job unclaim` （高级权限级别）

|===
[NOTE]
====
您可以使用 `event log show` 命令以确定已完成作业的结果。

====
.相关信息
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9命令"^]



== 用于管理作业计划的命令

许多任务(例如卷Snapshot副本)都可以配置为按指定的计划运行。在特定时间运行的计划称为_cron_计划(类似于UNIX `cron` 计划)。按间隔运行的计划称为 _interval_ schedules 。您可以使用 `job schedule` 用于管理作业计划的命令。

作业计划不会根据对集群日期和时间的手动更改进行调整。这些作业将根据创建作业的当前集群时间或最近运行的作业时间计划运行。因此、如果手动更改集群日期或时间、则应使用 `job show` 和 `job history show` 用于验证所有计划作业是否已按您的要求排队并完成的命令。

如果集群是 MetroCluster 配置的一部分，则两个集群上的作业计划必须相同。因此，如果您创建，修改或删除作业计划，则必须在远程集群上执行相同的操作。

|===
| 如果您要 ... | 使用此命令 ... 


 a| 
显示有关所有计划的信息
 a| 
`job schedule show`



 a| 
按计划显示作业列表
 a| 
`job schedule show-jobs`



 a| 
显示有关 cron 计划的信息
 a| 
`job schedule cron show`



 a| 
显示有关间隔计划的信息
 a| 
`job schedule interval show`



 a| 
创建 cron 计划
 a| 
`job schedule cron create`

从ONTAP 9.10.1开始、您可以在作业计划中包含SVM。



 a| 
创建间隔计划
 a| 
`job schedule interval create`

必须至少指定以下参数之一： `-days`， `-hours`， `-minutes`或 `-seconds`。



 a| 
修改 cron 计划
 a| 
`job schedule cron modify`



 a| 
修改间隔计划
 a| 
`job schedule interval modify`



 a| 
删除计划
 a| 
`job schedule delete`



 a| 
删除 cron 计划
 a| 
`job schedule cron delete`



 a| 
删除间隔计划
 a| 
`job schedule interval delete`

|===
.相关信息
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9命令"^]
