---
permalink: system-admin/methods-manage-sp-bmc-firmware-updates-concept.html 
sidebar: sidebar 
keywords: methods, manage, sp, bmc, firmware, update, image, baseline, download 
summary: ONTAP 包含一个称为基线映像的 SP 固件映像。如果随后有新版本的 SP 固件可用，您可以选择下载该固件并将 SP 固件更新到下载的版本，而无需升级 ONTAP 版本。 
---
= 管理 SP/BMC 固件更新的方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 包含一个称为 _baseline image_ 的 SP 固件映像。如果随后有新版本的 SP 固件可用，您可以选择下载该固件并将 SP 固件更新到下载的版本，而无需升级 ONTAP 版本。

[NOTE]
====
本主题将同时对 SP 和 BMC 进行适用场景。

====
ONTAP 提供了以下管理 SP 固件更新的方法：

* 默认情况下， SP 自动更新功能处于启用状态，允许在以下情况下自动更新 SP 固件：
+
** 升级到新版本的 ONTAP 时
+
ONTAP 升级过程会自动包括 SP 固件更新，前提是与 ONTAP 捆绑的 SP 固件版本比节点上运行的 SP 版本更新。

+
[NOTE]
====
ONTAP 检测到 SP 自动更新失败，并触发更正操作以重试 SP 自动更新，最多三次。如果三次重试均失败，您应联系技术支持。

====
** 从 NetApp 支持站点下载 SP 固件版本且下载的版本高于 SP 当前运行的版本时
** 降级或还原到早期版本的 ONTAP 时
+
SP 固件会自动更新到您还原或降级到的 ONTAP 版本所支持的最新兼容版本。不需要手动更新 SP 固件。



+
您可以使用 `ssystem service-processor image modify` 命令禁用 SP 自动更新功能。但是，建议您保持启用此功能。禁用此功能可能会导致 ONTAP 映像和 SP 固件映像之间的组合不是最佳组合或不符合要求。

* 通过 ONTAP ，您可以手动触发 SP 更新，并使用 `ssystem service-processor image update` 命令指定应如何进行更新。
+
您可以指定以下选项：

+
** 要使用的 SP 固件包（` -package` ）
+
您可以通过指定软件包文件名将 SP 固件更新为已下载的软件包。高级 `ssystem image package show` 命令可显示节点上可用的所有软件包文件（包括 SP 固件包的文件）。

** 是否使用基线 SP 固件包进行 SP 更新（` -baseline` ）
+
您可以将 SP 固件更新为与当前运行的 ONTAP 版本捆绑在一起的基线版本。



+
[NOTE]
====
如果您使用一些更高级的更新选项或参数，则可能会临时清除 BMC 的配置设置。重新启动后， ONTAP 可能需要长达 10 分钟的时间来还原 BMC 配置。

====
* 使用 ONTAP ，您可以使用 `ssystem service-processor image update-progress show` 命令显示从 ONTAP 触发的最新 SP 固件更新的状态。


更新 SP 固件时，与 SP 的任何现有连接将终止。无论是自动触发还是手动触发 SP 固件更新，都是如此。

https://mysupport.netapp.com/site/downloads/firmware/system-firmware-diagnostics["NetApp 下载：系统固件和诊断"]
