---
permalink: system-admin/ontap-commands-bmc-management-reference.html 
sidebar: sidebar 
keywords: ontap, command, bmc, management, baseboard, controller 
summary: 基板管理控制器（ BMC ）支持这些 ONTAP 命令。 
---
= 用于 BMC 管理的 ONTAP 命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
基板管理控制器（ BMC ）支持这些 ONTAP 命令。

BMC 使用的某些命令与服务处理器（ Service Processor ， SP ）相同。BMC 支持以下 SP 命令。

|===
| 如果您要 ... | 使用此命令 ... 


 a| 
显示 BMC 信息
 a| 
`*system service-processor show*`



 a| 
显示 / 修改 BMC 网络配置
 a| 
`*system service-processor network show/modify*`



 a| 
重置 BMC
 a| 
`*system service-processor reboot-sp*`



 a| 
显示 / 修改当前安装的 BMC 固件映像的详细信息
 a| 
`*system service-processor image show/modify*`



 a| 
更新 BMC 固件
 a| 
`*system service-processor image update*`



 a| 
显示最新 BMC 固件更新的状态
 a| 
`*system service-processor image update-progress show*`



 a| 
为 BMC 启用自动网络配置，以便在指定子网上使用 IPv4 或 IPv6 地址
 a| 
`*system service-processor network auto-configuration enable*`



 a| 
在为 BMC 指定的子网上禁用 IPv4 或 IPv6 地址的自动网络配置
 a| 
`*system service-processor network auto-configuration disable*`



 a| 
显示 BMC 自动网络配置
 a| 
`*system service-processor network auto-configuration show*`

|===
对于 BMC 固件不支持的命令，将返回以下错误消息。

[listing]
----
::> Error: Command not supported on this platform.
----
.相关信息
* link:https://docs.netapp.com/us-en/ontap-cli/["ONTAP 命令参考"^]

