---
permalink: system-admin/positional-parameters-concept.html 
sidebar: sidebar 
keywords: understand, positional, parameters, cli, command, input, query 
summary: 您可以利用 ONTAP 命令行界面的定位参数功能来提高命令输入的效率。您可以查询命令以确定该命令的定位参数。 
---
= 在命令输入中使用ONTAP命令行界面定位参数
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以利用 ONTAP 命令行界面的定位参数功能来提高命令输入的效率。您可以查询命令以确定该命令的定位参数。



== 什么是定位参数

* 定位参数是一个参数，不需要在指定参数值之前指定参数名称。
* 只要定位参数与同一命令中的其他定位参数保持相对顺序、就可以在命令输入中将其与非定位参数相结合、如中所示 `*_command_name ?_*` 输出。
* 定位参数可以是命令的必需或可选参数。
* 一个参数可以是一个命令的定位参数，而不是另一个命令的定位参数。


[NOTE]
====
建议不要在脚本中使用定位参数功能，尤其是当定位参数是命令的可选参数或在其前面列出了可选参数时。

====


== 确定定位参数

您可以在中标识定位参数 `*_command_name ?_*` 命令输出。定位参数的参数名称包含方括号，格式如下：

* [`_-parameter_name_`] `_parameter_value_` 显示了必需的定位参数。
* [[`_-parameter_name_`] `_parameter_value_`]显示了一个定位的可选参数。


例如、当在中显示为以下内容时 `*_command_name ?_*` 输出中、参数是其所在命令的定位参数：

* `[-lif] <lif-name>`
* `[[-lif] <lif-name>]`


但是，如果显示为以下内容，则该参数是其所在命令的非定位参数：

* `-lif <lif-name>`
* `[-lif <lif-name>]`




== 使用定位参数的示例

在以下示例中、 `*_volume create ?_*` 输出显示三个参数是命令的定位参数： `-volume`， `-aggregate`，和 `-size`。

[listing]
----
cluster1::> volume create ?
   -vserver <vserver name>                Vserver Name
   [-volume] <volume name>                Volume Name
   [-aggregate] <aggregate name>          Aggregate Name
  [[-size] {<integer>[KB|MB|GB|TB|PB]}]   Volume Size
  [ -state {online|restricted|offline|force-online|force-offline|mixed} ]
                                          Volume State (default: online)
  [ -type {RW|DP|DC} ]                    Volume Type (default: RW)
  [ -policy <text> ]                      Export Policy
  [ -user <user name> ]                   User ID
  ...
  [ -space-guarantee|-s {none|volume} ]   Space Guarantee Style (default: volume)
  [ -percent-snapshot-space <percent> ]   Space Reserved for Snapshot Copies
  ...
----
在以下示例中、 `volume create` 在未利用定位参数功能的情况下指定命令：

`cluster1::> volume create -vserver svm1 -volume vol1 -aggregate *aggr1 -size 1g* -percent-snapshot-space 0`

以下示例使用定位参数功能来提高命令输入的效率。定位参数与中的非定位参数交错 `volume create` 命令和定位参数值的指定不带参数名称。定位参数的指定顺序与所示的顺序相同 `*volume create ?*` 输出。即的值 `-volume` 在的指定之前指定 `-aggregate`，依次指定 `-size`。

`cluster1::> volume create *vol2* *aggr1* *1g* -vserver svm1 -percent-snapshot-space 0`

`cluster1::> volume create -vserver svm1 *vol3* -snapshot-policy default *aggr1* -nvfail off *1g* -space-guarantee none`
