---
permalink: system-admin/remove-nodes-cluster-concept.html 
sidebar: sidebar 
keywords: remove, node, cluster, failover, partner, erase, inaccessible 
summary: 您可以从集群中删除不需要的节点，一次删除一个节点。删除节点后，您还必须删除其故障转移配对节点。如果要删除某个节点，则其数据将无法访问或擦除。 
---
= 从ONTAP集群中删除节点
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以从集群中删除不需要的节点，一次删除一个节点。删除节点后，您还必须删除其故障转移配对节点。如果要删除某个节点，则其数据将无法访问或擦除。

.开始之前
从集群中移除节点之前，必须满足以下条件：

* 集群中一半以上的节点必须运行状况良好。
* 所有数据、卷和非根聚合都必须从节点中迁移或删除。
+
** 必须已清空节点上要删除的所有数据。这可能包括link:../encryption-at-rest/secure-purge-data-encrypted-volume-concept.html["清除加密卷中的数据"]。
** 所有非根卷均已 link:../volumes/move-volume-task.html["已移动"] 来自节点所拥有的聚合。
** 所有非根聚合均已 link:../disks-aggregates/commands-manage-aggregates-reference.html["已删除"] 从节点。


* 已从此节点中重新定位或删除所有的Bifs和VLAN。
+
** 数据 LIF 已经过 link:../networking/delete_a_lif.html["已删除"] 或 link:../networking/migrate_a_lif.html["已重新定位"] 从节点。
** 集群管理 LIF 已启用 link:../networking/migrate_a_lif.html["已重新定位"] 已更改节点和主端口。
** 已将所有集群间的link:../networking/delete_a_lif.html["已删除"]删除集群间 LIF 时，将显示一条警告，可以忽略此警告。
** 节点上的所有 VLAN 均已 link:../networking/configure_vlans_over_physical_ports.html#delete-a-vlan["已删除"]。


* 此节点未加入任何故障转移关系。
+
** 存储故障转移已完成 link:../high-availability/ha_commands_for_enabling_and_disabling_storage_failover.html["已禁用"] 。
** 所有 LIF 故障转移规则均已完成 link:../networking/commands_for_managing_failover_groups_and_policies.html["已修改"] 删除节点上的端口。


* 如果节点拥有联邦信息处理标准（ FIPS ）磁盘或自加密磁盘（ SED ）， link:../encryption-at-rest/return-seds-unprotected-mode-task.html["磁盘加密已删除"] 将磁盘返回到未受保护的模式。
+
** 您可能还需要 link:../encryption-at-rest/sanitize-fips-drive-sed-task.html["清理 FIPS 驱动器或 SED"]。


* 如果要删除的节点上存在LUN、则应link:../san-admin/modify-slm-reporting-nodes-task.html["修改选择性LUN映射(SLM)报告节点列表"]在删除此节点之前进行操作。
+
如果不从SLM报告节点列表中删除节点及其HA配对节点、则即使包含LUN的卷已移至另一个节点、对该节点上先前LUN的访问也可能会丢失。



建议问题描述 您发送一条 AutoSupport 消息，以通知 NetApp 技术支持正在删除节点。


IMPORTANT: 在自动ONTAP升级过程中，请勿执行、 `cluster unjoin`和 `node rename`等操作 `cluster remove-node`。

.关于此任务
* 如果您运行的是混合版本的集群，则可以使用从 ONTAP 9.3 开始的高级权限命令之一删除最后一个低版本节点：
+
** ONTAP 9.3： `cluster unjoin -skip-last-low-version-node-check`
** ONTAP 9.4及更高版本： `cluster remove-node -skip-last-low-version-node-check`


* 如果从四节点集群中删除两个节点，则会在其余两个节点上自动启用集群 HA。


[NOTE]
====
在从集群中删除节点之前，必须使用户无法访问来自连接到该节点的所有磁盘的所有系统和用户数据。

如果从群集中错误地删除了节点，请联系 NetApp 支持人员以获得有关恢复选项的帮助。

====
[[disable-ha]]
.步骤
. 将权限级别更改为高级：
+
[source, cli]
----
set -privilege advanced
----
. 识别集群中具有 epsilon 的节点：
+
[source, cli]
----
cluster show
----
+
在以下示例中，"node0" 当前持有 epsilon：

+
[listing]
----
cluster::*>
Node                 Health  Eligibility  Epsilon
-------------------- ------- ------------ ------------
node0                true    true         true
node1                true    true         false
node2                true    true         false
node3                true    true         false
----
. [[epsilon-true]]如果您要删除的节点包含 epsilon：
+
.. 从要删除的节点中移动 epsilon：
+
[source, cli]
----
cluster modify -node <name_of_node_to_be_removed> -epsilon false
----
.. 将 epsilon 移至未移除的节点：
+
[source, cli]
----
cluster modify -node <node_name> -epsilon true
----


. 确定当前主节点：
+
[source, cli]
----
cluster ring show
----
+
主节点是存放、、 `vldb` `vifmgr`、 `bcomd`和 `crs`等进程的节点 `mgmt`。

. 如果您要删除的节点是当前主节点，请启用集群中的另一个节点被选为主节点：
+
.. 使当前主节点不符合加入集群的条件：
+
[source, cli]
----
cluster modify -node <node_name> -eligibility false
----
+
在恢复资格之前，节点被标记为不健康。当主节点变得不合格时，剩余的节点之一由集群仲裁选举为新的主节点。

+
[NOTE]
====
如果要在 HA 对中的第一个节点上执行此步骤，则应仅将该节点标记为不合格。请勿修改 HA 合作伙伴的状态。

如果选择合作伙伴节点作为新的主节点，则需要在使其不合格之前验证它是否保持 epsilon。如果合作伙伴节点持有 epsilon，则需要将 epsilon 移动到保留在集群中的其他节点，然后才能使其不合格。在重复这些步骤以删除合作伙伴节点时，请执行此操作。

====
.. 使上一个主节点有资格重新加入集群：
+
[source, cli]
----
cluster modify -node <node_name> -eligibility true
----


. 登录到未从群集中删除的节点上的远程节点管理 LIF 或群集管理 LIF。
. 从集群中删除节点：
+
|===
| 对于此 ONTAP 版本 ... | 使用此命令 ... 


 a| 
ONTAP 9.3
 a| 
[source, cli]
----
cluster unjoin
----


 a| 
ONTAP 9.4及更高版本
 a| 
具有节点名称：

[source, cli]
----
cluster remove-node -node <node_name>
----
使用节点IP：

[source, cli]
----
cluster remove-node -cluster_ip <node_ip>
----
|===
+
如果您使用的是混合版本集群、并且要删除最后一个较低版本的节点、请使用 `-skip-last-low-version-node-check` 参数。

+
系统会通知您以下信息：

+
** 您还必须从集群中删除节点的故障转移配对节点。
** 删除节点后，在其重新加入集群之前，必须使用引导菜单选项 *(4) Clean configuration and initialize all disks* 或选项 *(9) Configure Advanced Drive Partitioning* 来清除节点的配置并初始化所有磁盘。
+
如果在删除节点之前必须解决某些条件，则会生成一条失败消息。例如，此消息可能指示节点具有必须删除的共享资源，或者节点采用必须禁用的集群 HA 配置或存储故障转移配置。

+
如果节点是仲裁主节点，则集群将暂时丢失，然后返回仲裁状态。此仲裁丢失是临时的，不会影响任何数据操作。



. 如果失败消息指示错误情况、请解决这些情况并重新运行 `cluster remove-node` 或 `cluster unjoin` 命令：
+
从集群中成功删除后，节点会自动重新启动。

. 如果要重新利用节点，请擦除节点配置并初始化所有磁盘：
+
.. 在启动过程中，当系统提示时，按 Ctrl-C 显示启动菜单。
.. 选择启动菜单选项 *(4) Clean configuration and initialize all disks*。


. [[return-admin]]返回管理员权限级别：
+
[source, cli]
----
set -privilege admin
----
. 重复步骤 <<disable-ha,1.>> 到 <<return-admin,9>> 以从集群中删除故障转移合作伙伴。


.相关信息
* link:https://docs.netapp.com/us-en/ontap-cli/cluster-remove-node.html["cluster remove-node"^]

