---
permalink: system-admin/remov-nodes-cluster-concept.html 
sidebar: sidebar 
keywords: remove, node, cluster, failover, partner, erase, inaccessible 
summary: 您可以从集群中删除不需要的节点，一次删除一个节点。删除节点后，您还必须删除其故障转移配对节点。如果要删除某个节点，则其数据将无法访问或擦除。 
---
= 从集群中删除节点
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以从集群中删除不需要的节点，一次删除一个节点。删除节点后，您还必须删除其故障转移配对节点。如果要删除某个节点，则其数据将无法访问或擦除。

.您需要什么？ #8217 ；将需要什么
* 集群中一半以上的节点必须运行状况良好。
* 必须已清空节点上要删除的所有数据。
* 必须已删除所有集群间 LIF 。
+
[NOTE]
====
删除集群间 LIF 时，将显示一条警告，可以忽略此警告。

在自动 ONTAP 升级过程中，您不能执行 `cluster remove-node` ， `cluster unjoin` 和 `node rename` 等操作。

====


如果您运行的是混合版本的集群，则可以使用从 ONTAP 9.3 开始的高级权限命令之一删除最后一个低版本节点：

* ONTAP 9.3 ： `cluster unjoin -skip-last-low-version-node-check`
* ONTAP 9.4 及更高版本： `cluster remove-node -skip-last-low-version-node-check`


[NOTE]
====
在从集群中删除节点之前，您必须使用户无法访问连接到此节点的磁盘中的所有系统和用户数据。从集群中删除节点后，如果需要将此节点重新加入同一集群，请联系技术支持以获得有关还原数据的帮助。

====
.步骤
. 将权限级别更改为高级：
+
` * 设置 -privilege advanced*`

. 如果在集群上启用了存储加密，并且自加密磁盘（ SED ）正在运行，则必须将 data-id-key 设置为 0x0 。
+
.. 将 data-id-key 设置为 0x0 ：
+
` * 存储加密磁盘修改 -disk \_disk_path_name_\] -data-key-id 0x0*`

.. 可选：如果启用了存储加密且 SED 在联邦信息处理标准（ FIPS ）合规模式下运行，则除了设置 data-id-key 之外，还必须禁用 FIPS 合规模式。
+
这样，在将节点从集群中删除后，便可对连接到此节点的磁盘进行清理和重新利用。

+
*** 显示当前处于 FIPS 兼容模式的 SED ：
+
` * 存储加密磁盘 show -fips*`

*** 禁用 FIPS 合规模式：
+
` * 存储加密磁盘修改磁盘 [_disk_path_name_]-fips-key-id 0x0*`

*** 验证修改后的 SED 是否不再处于 FIPS 合规模式：
+
` * 存储加密磁盘 show -fips*`





. 如果要删除的节点是当前主节点，请将此主节点的集群资格更改为 `false` ，以使集群中的另一个节点能够被选为主节点：
+
` * 集群修改–资格 false *`

+
主节点是指包含 " `mGMT` " ， "`VLDB` " ， "`vifmgr` " ， "`bcomd` " 和 "`crs` " 等进程的节点。`cluster ring show` advanced 命令可显示当前主节点。

+
[listing]
----
cluster::*> cluster modify -node node1 -eligibility false
----
. 从集群中删除节点。
+
|===
| 对于此 ONTAP 版本 ... | 使用此命令 ... 


 a| 
ONTAP 9.3
 a| 
` * 集群取消加入 *`



 a| 
ONTAP 9.4 及更高版本
 a| 
` * 集群删除节点 *`

|===
+
如果您使用的是混合版本集群，并且要删除最后一个较低版本的节点，请在这些命令中使用 ` skip-last-low-version-node-check` 参数。

+
系统会通知您以下信息：

+
** 您还必须从集群中删除节点的故障转移配对节点。
** 删除节点后，在节点重新加入集群之前，您必须使用启动菜单选项（ 4 ） Clean configuration and initialize all disks 或选项（ 9 ） Configure Advanced Drive Partitioning 以擦除节点的配置并初始化所有磁盘。
+
如果在删除节点之前必须解决某些条件，则会生成一条失败消息。例如，此消息可能指示节点具有必须删除的共享资源，或者节点采用必须禁用的集群 HA 配置或存储故障转移配置。

+
如果节点是仲裁主节点，则集群将暂时丢失，然后返回仲裁状态。此仲裁丢失是临时的，不会影响任何数据操作。



. 如果失败消息指示出现错误情况，请解决这些情况，然后重新运行 `cluster remove-node` 或 `cluster unjoin` 命令。
+
成功从集群中删除节点后，此节点将自动重新启动。

. 如果要重新利用节点，请擦除节点配置并初始化所有磁盘：
+
.. 在启动过程中，当系统提示时，按 Ctrl-C 显示启动菜单。
.. 选择启动菜单选项 * （ 4 ） Clean configuration and initialize all disks* 。


. 返回到管理员权限级别：
+
` * 设置 -privilege admin*`

. 重复上述步骤，从集群中删除故障转移配对节点。


如果您将节点删除为使用单节点集群，则应修改集群端口以提供数据流量，方法是将集群端口修改为数据端口，然后在数据端口上创建数据 LIF 。
