---
permalink: system-admin/setup-autosupport-task.html 
sidebar: sidebar 
keywords: autosupport, set up autosupport, technical support, internal support organization, AutoSupport messages, AutoSupport configuration, AutoSupport OnDemand, HTTPS, SMTP, email, proxy, mail host, DNS, TLS, AutoSupport history, AutoSupport check 
summary: 配置ONTAP集群、以便向NetApp技术支持传送AutoSupport消息并向内部支持组织发送电子邮件副本。 
---
= 设置 AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以配置ONTAP集群、以便向NetApp技术支持传送AutoSupport消息、并向内部支持组织发送电子邮件副本。在此过程中、您还可以先对配置进行测试、然后再在生产环境中使用它。

.关于此任务
从ONTAP 9.5开始、您可以同时为集群中的所有节点启用和配置AutoSupport。当新节点加入集群时、该节点会自动继承相同的AutoSupport配置。为此、请查看CLI命令的范围 `system node autosupport modify` 是集群级别的。。 `-node` 为了向后兼容、保留了命令选项、但会将其忽略。


NOTE: 在ONTAP 9.4及更早版本中、命令 `system node autosupport modify` 特定于每个节点。如果集群运行的是ONTAP 9.4或更早版本、则需要在集群中的每个节点上启用和配置AutoSupport。

.开始之前
将AutoSupport消息传送到NetApp时、建议使用HTTPS (HTTP与TLS)传输配置。此选项可提供最强大的功能和最佳的安全性。

请查看 link:requirements-autosupport-reference.html["准备使用AutoSupport"] 了解有关配置ONTAP集群之前的详细信息。

.步骤
. 确保已启用 AutoSupport ：
+
[listing]
----
system node autosupport modify -state enable
----
. 如果您希望NetApp技术支持接收AutoSupport消息、请使用以下命令：
+
[listing]
----
system node autosupport modify -support enable
----
+
如果要使 AutoSupport 能够与 AutoSupport OnDemand 配合使用，或者要将核心转储和性能归档文件等大型文件上传到技术支持或指定 URL ，则必须启用此选项。

+

NOTE: 默认情况下、AutoSupport OnDemand处于启用状态、如果配置为使用HTTPS传输协议向技术支持发送消息、则该功能正常运行。

. 如果您启用了NetApp技术支持以接收AutoSupport消息、请指定用于这些消息的传输协议。
+
您可以从以下选项中进行选择：

+
|===


| 如果您要 ... | 然后设置的以下参数 `system node autosupport modify` 命令... 


 a| 
使用默认 HTTPS 协议
 a| 
.. 设置 `-transport` to `https`。
.. 如果使用代理、请设置 `-proxy-url` 代理的URL。
此配置支持与 AutoSupport OnDemand 通信以及上传大型文件。




 a| 
使用 SMTP
 a| 
设置 `-transport` to `smtp`。

此配置不支持 AutoSupport OnDemand 或上传大型文件。

|===
. 如果您希望内部支持组织或支持合作伙伴接收 AutoSupport 消息，请执行以下操作：
+
.. 通过设置的以下参数、确定组织中的收件人 `system node autosupport modify` 命令：
+
|===


| 设置此参数 ... | 目标位置 ... 


 a| 
`-to`
 a| 
您的内部支持组织中最多五个将接收关键 AutoSupport 消息的电子邮件地址或分发列表，以逗号分隔



 a| 
`-noteto`
 a| 
您的内部支持组织中最多有五个以逗号分隔的单个电子邮件地址或分发列表，这些地址或分发列表将接收专为手机和其他移动设备设计的关键 AutoSupport 消息的简略版本



 a| 
`-partner-address`
 a| 
您的支持合作伙伴组织中最多五个以逗号分隔的单个电子邮件地址或分发列表，这些电子邮件地址或分发列表将接收所有 AutoSupport 消息

|===
.. 通过使用列出目标来检查是否已正确配置地址 `system node autosupport destinations show` 命令：


. 如果您在上一步中为内部支持组织配置了收件人地址、或者为发送给技术支持的消息选择了SMTP传输、请通过设置命令的以下参数来配置SMTP `system node autosupport modify`：
+
** 设置 `-mail-hosts` 发送到一个或多个邮件主机、以逗号分隔。
+
最多可以设置五个。

+
您可以通过在邮件主机名后面指定冒号和端口号来为每个邮件主机配置端口值：例如、 `mymailhost.example.com:5678`，其中5678是邮件主机的端口。

** 设置 `-from` 发送AutoSupport消息的电子邮件地址。


. 配置 DNS 。
. (可选)如果要更改特定设置、请添加命令选项：
+
|===


| 如果要执行此操作 ... | 然后设置的以下参数 `system node autosupport modify` 命令... 


 a| 
通过删除，屏蔽或对消息中的敏感数据进行编码来隐藏私有数据
 a| 
设置 `-remove-private-data` to `true`。如果您从进行了更改 `false` to `true`，所有AutoSupport历史记录和所有关联文件都将被删除。



 a| 
停止在定期 AutoSupport 消息中发送性能数据
 a| 
设置 `-perf` to `false`。

|===
. 如果您使用SMTP向NetApp传送AutoSupport消息、则可以选择启用TLS以提高安全性。
+
.. 显示可用于新参数的值：
+
[listing]
----
cluster1::> system node autosupport modify -smtp-encryption ?
----
.. 为SMTP消息传送启用TLS：
+
[listing]
----
cluster1::> system node autosupport modify -smtp-encryption start_tls
----
.. 显示当前配置：
+
[listing]
----
cluster1::> system node autosupport show -fields smtp-encryption
----


. 使用检查整体配置 `system node autosupport show` 命令 `-node` 参数。
. 使用验证AutoSupport操作 `system node autosupport check show` 命令：
+
如果报告任何问题、请使用 `system node autosupport check show-details` 命令以查看详细信息。

. 测试是否正在发送和接收 AutoSupport 消息：
+
.. 使用 `system node autosupport invoke` 命令 `-type` 参数设置为 `test`：
+
[listing]
----
cluster1::> system node autosupport invoke -type test -node node1
----
.. 确认 NetApp 正在接收您的 AutoSupport 消息：
+
[listing]
----
system node autosupport history show -node local
----
+
最新传出AutoSupport消息的状态最终应更改为 `sent-successful` 所有适当的协议目标。

.. (可选)通过检查为配置的任何地址的电子邮件来确认AutoSupport消息正在发送到您的内部支持组织或您的支持合作伙伴 `-to`， `-noteto`或 `-partner-address`  的参数 `system node autosupport modify` 命令：




.相关信息
* link:../system-admin/requirements-autosupport-reference.html["准备使用AutoSupport"]

