---
permalink: system-admin/start-stop-storage-system-concept.html 
sidebar: sidebar 
keywords: start, stop, node, cli, ontap, troubleshoot, sp, reboot, system, boot, compactflash, shut down, shutdown,  unresponsive, shut, down, node, unresponsive, support, personnel, direct, troubleshoot 
summary: 出于维护或故障排除原因，您可能需要启动或停止节点。您可以从 ONTAP 命令行界面，启动环境提示符或 SP 命令行界面执行此操作。 
---
= 启动或停止节点概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
出于维护或故障排除原因，您可能需要启动或停止节点。您可以从 ONTAP 命令行界面，启动环境提示符或 SP 命令行界面执行此操作。

使用SP命令行界面命令 `system power off` 或 `system power cycle` 要关闭或重新启动某个节点、可能会对该节点进行发生原因以不当方式关闭(也称为_dirty shutdown _)、并且不能替代使用ONTAP正常关闭 `system node halt` 命令：



== 在系统提示符处重新启动节点

您可以从系统提示符处以正常模式重新启动节点。节点已配置为从 PC CompactFlash 卡等启动设备启动。

.步骤
. 如果集群包含四个或更多节点，请验证要重新启动的节点是否未持有 epsilon ：
+
.. 将权限级别设置为高级：
+
`*set -privilege advanced*`

.. 确定哪个节点持有 epsilon ：
+
`*cluster show*`

+
以下示例显示 "`node1` " 持有 epsilon ：

+
[listing]
----
cluster1::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          true
node2                true    true          false
node3                true    true          false
node4                true    true          false
4 entries were displayed.
----
.. 如果要重新启动的节点持有 epsilon ，则从节点中删除 epsilon ：
+
`*cluster modify -node _node_name_ -epsilon false*`

.. 将 epsilon 分配给将保持正常运行的其他节点：
+
`*cluster modify -node _node_name_ -epsilon true*`

.. 返回到管理权限级别：
+
`*set -privilege admin*`



. 使用 `system node reboot` 命令以重新启动节点。
+
如果未指定 `-skip-lif-migration` 参数、则此命令会尝试在重新启动之前将数据和集群管理生命周期同步迁移到另一个节点。如果 LIF 迁移失败或超时，重新启动过程将中止， ONTAP 将显示一个错误，指示 LIF 迁移失败。

+
[listing]
----
cluster1::> system node reboot -node node1 -reason "software upgrade"
----
+
节点将开始重新启动过程。此时将显示 ONTAP 登录提示，指示重新启动过程已完成。





== 在启动环境提示符处启动 ONTAP

您可以在节点的启动环境提示符处启动 ONTAP 的当前版本或备份版本。

.步骤
. 使用从存储系统提示符处访问启动环境提示符 `system node halt` 命令：
+
存储系统控制台将显示启动环境提示符。

. 在启动环境提示符处，输入以下命令之一：
+
|===
| 要启动 ... | 输入 ... 


 a| 
ONTAP 的当前版本
 a| 
`boot_ontap`



 a| 
启动设备中的 ONTAP 主映像
 a| 
`boot_primary`



 a| 
启动设备中的 ONTAP 备份映像
 a| 
`boot_backup`

|===
+
如果您不确定要使用哪个映像、应使用 `boot_ontap` 在第一个实例中。





== 关闭节点

如果节点无响应，或者支持人员指示您在进行故障排除时关闭节点，您可以关闭节点。

.步骤
. 如果集群包含四个或更多节点，请验证要关闭的节点是否未持有 epsilon ：
+
.. 将权限级别设置为高级：
+
`*set -privilege advanced*`

.. 确定哪个节点持有 epsilon ：
+
`*cluster show*`

+
以下示例显示 "`node1` " 持有 epsilon ：

+
[listing]
----
cluster1::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          true
node2                true    true          false
node3                true    true          false
node4                true    true          false
4 entries were displayed.
----
.. 如果要关闭的节点持有 epsilon ，则从节点中删除 epsilon ：
+
`*cluster modify -node _node_name_ -epsilon false*`

.. 将 epsilon 分配给将保持正常运行的其他节点：
+
`*cluster modify -node _node_name_ -epsilon true*`

.. 返回到管理权限级别：
+
`*set -privilege admin*`



. 使用 `system node halt` 命令以关闭节点。
+
如果未指定 `-skip-lif-migration` 参数、则此命令会在关闭之前尝试将数据和集群管理的生命周期同步迁移到另一个节点。如果 LIF 迁移失败或超时，则关闭过程将中止，而 ONTAP 将显示一个错误以指示 LIF 迁移失败。

+
您可以同时使用两个手动触发核心转储并在关闭时触发 `-dump` 参数。

+
以下示例将关闭名为 "`node1` " 的节点以进行硬件维护：

+
[listing]
----
cluster1::> system node halt -node node1 -reason 'hardware maintenance'
----

