---
permalink: system-admin/troubleshoot-web-access-problems-concept.html 
sidebar: sidebar 
keywords: troubleshoot, web, services, access, problems, lif, firewall, policy, protocol, engin, digital, certificate, user, access, authorization 
summary: 配置错误发生发生原因 Web 服务访问问题。您可以通过确保 LIF ，防火墙策略， Web 协议引擎， Web 服务，数字证书， 和用户访问授权均已正确配置。 
---
= 对 Web 服务访问问题进行故障排除
:icons: font
:imagesdir: ../media/


[role="lead"]
配置错误发生发生原因 Web 服务访问问题。您可以通过确保 LIF ，防火墙策略， Web 协议引擎， Web 服务，数字证书， 和用户访问授权均已正确配置。

下表可帮助您确定并解决 Web 服务配置错误：

|===
| 此访问问题 ... | 由于此配置错误而发生 ... | 要解决此错误 ... 


 a| 
在尝试访问 Web 服务时， Web 浏览器会返回 `Unable to connect` 或 `failure to establish a connection` 错误。
 a| 
您的 LIF 可能配置不正确。
 a| 
确保您可以对提供 Web 服务的 LIF 执行 ping 操作。

[NOTE]
====
您可以使用 `network ping` 命令对 LIF 执行 ping 操作。有关网络配置的信息，请参见 _Network Management Guide_ 。

====


 a| 
防火墙配置可能不正确。
 a| 
确保防火墙策略已设置为支持 HTTP 或 HTTPS ，并且已将此策略分配给提供 Web 服务的 LIF 。

[NOTE]
====
您可以使用 `ssystem services firewall policy` 命令管理防火墙策略。您可以使用带有 ` -firewall-policy` 参数的 `network interface modify` 命令将策略与 LIF 关联。

====


 a| 
您的 Web 协议引擎可能已禁用。
 a| 
确保已启用 Web 协议引擎，以便可以访问 Web 服务。

[NOTE]
====
您可以使用 `ssystem services web` 命令来管理集群的 Web 协议引擎。

====


 a| 
尝试访问 Web 服务时， Web 浏览器返回 `not found` 错误。
 a| 
此 Web 服务可能已禁用。
 a| 
确保已分别启用要允许访问的每个 Web 服务。

[NOTE]
====
您可以使用 `vserver services web modify` 命令启用 Web 服务以进行访问。

====


 a| 
Web 浏览器无法使用用户的帐户名称和密码登录到 Web 服务。
 a| 
无法对用户进行身份验证，访问方法不正确或用户无权访问 Web 服务。
 a| 
确保用户帐户存在，并使用正确的访问方法和身份验证方法进行配置。此外，确保用户的角色已获得访问 Web 服务的授权。

[NOTE]
====
您可以使用 `ssecurity login` 命令管理用户帐户及其访问方法和身份验证方法。访问 ONTAP API Web 服务需要使用 `ontapi` 访问方法。访问所有其他 Web 服务需要使用 `http` 访问方法。您可以使用 `vserver services web access` 命令管理角色对 Web 服务的访问。

====


 a| 
您使用 HTTPS 连接到 Web 服务，而 Web 浏览器指示您的连接已中断。
 a| 
您可能未在提供 Web 服务的集群或 Storage Virtual Machine （ SVM ）上启用 SSL 。
 a| 
确保集群或 SVM 已启用 SSL ，并且数字证书有效。

[NOTE]
====
您可以使用 `security ssl` 命令管理 HTTP 服务器的 SSL 配置，并使用 `security certificate show` 命令显示数字证书信息。

====


 a| 
您使用 HTTPS 连接到 Web 服务，并且 Web 浏览器指示此连接不可信。
 a| 
您可能正在使用自签名数字证书。
 a| 
确保与集群或 SVM 关联的数字证书已由可信 CA 签名。

[NOTE]
====
您可以使用 `security certificate generate-csr` 命令生成数字证书签名请求，并使用 `security certificate install` 命令安装 CA 签名的数字证书。您可以使用 `security ssl` 命令管理提供 Web 服务的集群或 SVM 的 SSL 配置。

====
|===