---
permalink: system-admin/troubleshoot-autosupport-delivery-smtp-task.html 
sidebar: sidebar 
keywords: troubleshoot, autosupport, deliver, system, smtp, settings, resolve, problem 
summary: 如果系统无法通过 SMTP 传送 AutoSupport 消息，您可以检查多项设置来解决此问题。 
---
= 对通过SMTP传送ONTAP AutoSupport消息进行故障排除
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果系统无法通过 SMTP 传送 AutoSupport 消息，您可以检查多项设置来解决此问题。

.您需要的内容
您应已确认基本网络连接和 DNS 查找：

* 您的节点管理 LIF 必须处于运行和管理状态。
* 您必须能够从集群管理 LIF （而不是任何节点上的 LIF ）对同一子网上运行正常的主机执行 ping 操作。
* 您必须能够从集群管理 LIF 对子网以外正在运行的主机执行 ping 操作。
* 您必须能够使用主机的名称（而不是 IP 地址）从集群管理 LIF 对子网外正常运行的主机执行 ping 操作。


.关于此任务
如果您已确定 AutoSupport 可以生成消息，但无法通过 SMTP 传送消息，则可以执行以下步骤。

如果您遇到错误或无法完成此操作步骤中的某个步骤，请先确定并解决此问题，然后再继续执行下一步。

除非另有说明，否则所有命令均在 ONTAP 命令行界面中输入。

.步骤
. 验证节点管理 LIF 的状态：
+
`*network interface show -home-node local -role node-mgmt -fields vserver,lif,status-oper,status-admin,address,role*`

+
 `status-oper`和 `status-admin`字段应返回 `up`。有关的详细信息 `up`，请参见link:https://docs.netapp.com/us-en/ontap-cli/up.html["ONTAP 命令参考"^]。

. 记录 SVM 名称， LIF 名称和 LIF IP 地址，以供日后使用。
. 确保已启用并正确配置 DNS ：
+
`*vserver services name-service dns show*`

. 显示配置为由 AutoSupport 使用的所有服务器：
+
`*system node autosupport show -fields mail-hosts*`

+
记录显示的所有服务器名称。

. 对于上一步显示的每个服务器、和 `support.netapp.com`下，确保节点可以访问服务器或URL：
+
`*network traceroute -node local -destination _server_name_*`

+
如果其中任何一条路由无法正常运行，请使用大多数第三方网络客户端上的 "`traceroute` " 或 "`tracert` " 实用程序，尝试从与集群位于同一子网上且正常运行的主机执行相同的路由。这有助于您确定问题描述是位于网络配置还是集群配置中。

. 登录到指定为邮件主机的主机，并确保它可以处理 SMTP 请求：
+
`*netstat -aAn|grep 25*`

+
`25` 是侦听器SMTP端口号。

+
此时将显示类似于以下文本的消息：

+
[listing]
----
ff64878c tcp        0      0  *.25    *.*    LISTEN.
----
. 从其他某个主机上，使用邮件主机的 SMTP 端口打开 Telnet 会话：
+
`*telnet _mailhost_ 25*`

+
此时将显示类似于以下文本的消息：

+
[listing]
----

220 filer.yourco.com Sendmail 4.1/SMI-4.1 ready at Thu, 30 Nov 2014 10:49:04 PST
----
. 在 telnet 提示符处，确保可以从邮件主机中继消息：
+
`*HELO _domain_name_*`

+
`*MAIL FROM: _your_email_address_*`

+
`*RCPT TO: \autosupport@netapp.com*`

+
`domain_name` 是网络的域名。

+
如果返回一个错误，指出中继被拒绝，则邮件主机上不会启用中继。请与系统管理员联系。

. 在 telnet 提示符处，发送一条测试消息：
+
`*DATA*`

+
`*SUBJECT: TESTING*`
`*THIS IS A TEST*`

+
`*.*`

+
[NOTE]
====
请确保在一行中单独输入最后一个句点（ . ）。句点向邮件主机指示消息已完成。

====
+
如果返回错误，则表示未正确配置邮件主机。请与系统管理员联系。

. 从 ONTAP 命令行界面，将 AutoSupport 测试消息发送到您有权访问的可信电子邮件地址：
+
`*system node autosupport invoke -node local -type test*`

. 查找尝试的序列号：
+
`*system node autosupport history show -node local -destination smtp*`

+
根据时间戳查找尝试的序列号。这可能是最近一次尝试。

. 显示测试消息尝试的错误：
+
`*system node autosupport history show -node local -seq-num seq_num -fields error*`

+
如果显示的错误为 `Login denied`，则SMTP服务器不接受来自集群管理LIF的发送请求。如果您不想更改为使用 HTTPS 作为传输协议，请与站点网络管理员联系，以配置 SMTP 网关以处理此问题描述。

+
如果此测试成功，但发送到 mailto ： autosupport@netapp.com 的同一消息未成功，请确保在所有 SMTP 邮件主机上启用 SMTP 中继，或者使用 HTTPS 作为传输协议。

+
如果即使将消息发送到本地管理的电子邮件帐户也不成功，请确认 SMTP 服务器已配置为转发具有以下两个特征的附件：

+
** "`7z` " 后缀
** "`application/x-7x-compressed` " MIME 类型。



