---
permalink: system-admin/troubleshoot-web-access-problems-concept.html 
sidebar: sidebar 
keywords: troubleshoot, web, services, access, problems, lif, firewall, policy, protocol, engin, digital, certificate, user, access, authorization 
summary: 配置错误发生发生原因 Web 服务访问问题。您可以通过确保 LIF ，防火墙策略， Web 协议引擎， Web 服务，数字证书， 和用户访问授权均已正确配置。 
---
= 对 Web 服务访问问题进行故障排除
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
配置错误发生发生原因 Web 服务访问问题。您可以通过确保 LIF ，防火墙策略， Web 协议引擎， Web 服务，数字证书， 和用户访问授权均已正确配置。

下表可帮助您确定并解决 Web 服务配置错误：

|===
| 此访问问题 ... | 由于此配置错误而发生 ... | 要解决此错误 ... 


 a| 
您的Web浏览器将返回 `unable to connect` 或 `failure to establish a connection` 尝试访问Web服务时出错。
 a| 
您的 LIF 可能配置不正确。
 a| 
确保您可以对提供 Web 服务的 LIF 执行 ping 操作。

[NOTE]
====
您可以使用 `network ping`命令对LIF执行ping操作。

====


 a| 
防火墙配置可能不正确。
 a| 
确保防火墙策略已设置为支持 HTTP 或 HTTPS ，并且已将此策略分配给提供 Web 服务的 LIF 。

[NOTE]
====
您可以使用 `system services firewall policy` 用于管理防火墙策略的命令。您可以使用 `network interface modify` 命令 `-firewall-policy` 用于将策略与LIF关联的参数。

====


 a| 
您的 Web 协议引擎可能已禁用。
 a| 
确保已启用 Web 协议引擎，以便可以访问 Web 服务。

[NOTE]
====
您可以使用 `system services web` 用于管理集群的Web协议引擎的命令。

====


 a| 
您的Web浏览器将返回 `not found` 尝试访问Web服务时出错。
 a| 
此 Web 服务可能已禁用。
 a| 
确保已分别启用要允许访问的每个 Web 服务。

[NOTE]
====
您可以使用 `vserver services web modify` 命令以启用Web服务以进行访问。

====


 a| 
Web 浏览器无法使用用户的帐户名称和密码登录到 Web 服务。
 a| 
无法对用户进行身份验证，访问方法不正确或用户无权访问 Web 服务。
 a| 
确保用户帐户存在，并使用正确的访问方法和身份验证方法进行配置。此外，确保用户的角色已获得访问 Web 服务的授权。

[NOTE]
====
您可以使用 `security login` 用于管理用户帐户及其访问方法和身份验证方法的命令。访问ONTAP API Web服务需要 `ontapi` 访问方法。访问所有其他Web服务需要 `http` 访问方法。您可以使用 `vserver services web access` 用于管理角色对Web服务的访问权限的命令。

====


 a| 
您使用 HTTPS 连接到 Web 服务，而 Web 浏览器指示您的连接已中断。
 a| 
您可能未在提供 Web 服务的集群或 Storage Virtual Machine （ SVM ）上启用 SSL 。
 a| 
确保集群或 SVM 已启用 SSL ，并且数字证书有效。

[NOTE]
====
您可以使用 `security ssl` 用于管理HTTP服务器和的SSL配置的命令 `security certificate show` 用于显示数字证书信息的命令。

====


 a| 
您使用 HTTPS 连接到 Web 服务，并且 Web 浏览器指示此连接不可信。
 a| 
您可能正在使用自签名数字证书。
 a| 
确保与集群或 SVM 关联的数字证书已由可信 CA 签名。

[NOTE]
====
您可以使用 `security certificate generate-csr` 命令以生成数字证书签名请求和 `security certificate install` 用于安装CA签名数字证书的命令。您可以使用 `security ssl` 用于管理提供Web服务的集群或SVM的SSL配置的命令。

====
|===
.相关信息
* link:https://kb.netapp.com/on-prem/ontap/da/NAS/NAS-KBs/What_are_Best_Practices_for_Network_Configuration_for_ONTAP["ONTAP网络配置的最佳实践是什么？"^]
* link:https://docs.netapp.com/us-en/ontap-cli/network-ping.html["网络 ping"^]
* link:https://docs.netapp.com/us-en/ontap-cli/network-interface-modify.html["network interface modify"]
* link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-generate-csr.html["安全证书generate-csr"^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-install.html["安全证书安装"^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-show.html["security certificate show"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+ssl["安全 SSL"^]

