---
permalink: system-admin/types-autosupport-messages-reference.html 
sidebar: sidebar 
keywords: active, iq, active iq, digital advisor, autosupport, messages, content, support, subsystems 
summary: AutoSupport 消息包含有关受支持子系统的状态信息。了解AutoSupport消息包含哪些内容可以帮助您解读或响应通过电子邮件收到的消息或在数字顾问网站上查看到的消息。 
---
= AutoSupport 消息的类型及其内容
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport 消息包含有关受支持子系统的状态信息。了解AutoSupport消息包含哪些内容可以帮助您解读或响应通过电子邮件收到的消息或在数字顾问网站上查看到的消息。

|===
| 消息类型 | 消息包含的数据类型 


 a| 
事件触发
 a| 
包含有关发生事件的特定子系统的上下文相关数据的文件



 a| 
每天
 a| 
日志文件



 a| 
性能
 a| 
在过去 24 小时内采样的性能数据



 a| 
每周
 a| 
配置和状态数据



 a| 
由触发 `system node autosupport invoke` 命令
 a| 
取决于中指定的值 `-type` 参数：

* `test` 发送用户触发的消息、其中包含一些基本数据。
+
此外、此消息还会使用触发从技术支持到任何指定电子邮件地址的自动电子邮件响应 `-to` 选项、以便您可以确认正在接收AutoSupport消息。

* `performance` 发送性能数据。
* `all` 发送一条用户触发的消息、其中包含一组与每周消息类似的完整数据、包括每个子系统的故障排除数据。
+
技术支持通常会请求此消息。





 a| 
由触发 `system node autosupport invoke-core-upload` 命令
 a| 
节点的核心转储文件



 a| 
由触发 `system node autosupport invoke-performance-archive` 命令
 a| 
指定时间段内的性能归档文件



 a| 
由 AutoSupport OnDemand 触发
 a| 
AutoSupport OnDemand 可以请求新消息或过去的消息：

* 根据AutoSupport收集的类型、新消息可以是 `test`， `all`或 `performance`。
* 过去的消息取决于重新发送的消息类型。


AutoSupport OnDemand可以请求新消息，并将以下文件上传到NetApp支持站点 http://mysupport.netapp.com/["mysupport.netapp.com"^]：

* 核心转储
* 性能归档


|===