---
permalink: system-admin/when-where-autosupport-messages-sent-concept.html 
sidebar: sidebar 
keywords: active, iq, digital advisor, active iq, autosupport, messages, email, manual, scheduled, event, triggered 
summary: AutoSupport 会根据消息类型将消息发送给不同的收件人。了解AutoSupport何时发送消息以及发送到何处、可以帮助您了解通过电子邮件接收的消息或在数字顾问网站上查看的消息。 
---
= 了解ONTAP AutoSupport消息的发送时间和位置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport 会根据消息类型将消息发送给不同的收件人。了解AutoSupport何时发送消息以及发送到何处、可以帮助您了解通过电子邮件接收的消息或在数字顾问网站上查看的消息。

除非另有说明、否则下表中的设置是的参数 `system node autosupport modify` 命令：



== 事件触发的消息

当系统上发生需要采取更正操作的事件时， AutoSupport 会自动发送事件触发的消息。

|===
| 发送消息时 | 消息的发送位置 


 a| 
AutoSupport 对 EMS 中的触发事件做出响应
 a| 
中指定的地址 `-to` 和 `-noteto`。（仅发送影响服务的严重事件。）

中指定的地址 `-partner-address`

技术支持、IF `-support` 设置为 `enable`

|===


== 已计划消息

AutoSupport 会定期自动发送多条消息。

|===
| 发送消息时 | 消息的发送位置 


 a| 
每天（默认情况下，在午夜 12 ： 00 之间发送和凌晨 1 ： 00作为日志消息）
 a| 
中指定的地址 `-partner-address`

技术支持、IF `-support` 设置为 `enable`



 a| 
每天（默认情况下，在午夜 12 ： 00 之间发送和凌晨 1 ： 00作为性能消息) `-perf` 参数设置为 `true`
 a| 
在 -partner-address` 中指定的地址

技术支持、IF `-support` 设置为 `enable`



 a| 
每周（默认情况下，在星期日中午 12 ： 00 之间发送和凌晨 1 ： 00 ）
 a| 
中指定的地址 `-partner-address`

技术支持、IF `-support` 设置为 `enable`

|===


== 手动触发的消息

您可以手动启动或重新发送 AutoSupport 消息。

|===
| 发送消息时 | 消息的发送位置 


 a| 
您可以使用手动启动消息 `system node autosupport invoke` 命令
 a| 
如果使用指定了URI `-uri` 中的参数 `system node autosupport invoke` 命令、则会将消息发送到该URI。

条件 `-uri` 如果省略、则会将消息发送到中指定的地址 `-to` 和 `-partner-address`。如果出现这种情况、此消息还会发送给技术支持 `-support` 设置为 `enable`。



 a| 
您可以使用手动启动消息 `system node autosupport invoke-core-upload` 命令
 a| 
如果使用指定了URI `-uri` 中的参数 `system node autosupport invoke-core-upload` 命令时、消息将发送到此URI、而核心转储文件将上传到此URI。

条件 `-uri` 在中省略 `system node autosupport invoke-core-upload` 命令中、消息将发送到技术支持、核心转储文件将上传到技术支持站点。

这两种情况都需要这样做 `-support` 设置为 `enable` 和 `-transport` 设置为 `https` 或 `http`。

由于核心转储文件非常大、因此不会将消息发送到中指定的地址 `-to` 和 `-partner-addresses` parameters



 a| 
您可以使用手动启动消息 `system node autosupport invoke-performance-archive` 命令
 a| 
如果使用指定了URI `-uri` 中的参数 `system node autosupport invoke-performance-archive` 命令时、消息将发送到此URI、性能归档文件将上传到此URI。

条件 `-uri` 在中省略 `system node autosupport invoke-performance-archive`，消息将发送至技术支持，性能归档文件将上传到技术支持站点。

这两种情况都需要这样做 `-support` 设置为 `enable` 和 `-transport` 设置为 `https` 或 `http`。

由于性能归档文件非常大、因此不会将消息发送到中指定的地址 `-to` 和 `-partner-addresses` parameters



 a| 
您可以使用手动重新发送过去的消息 `system node autosupport history retransmit` 命令
 a| 
仅限您在中指定的URI `-uri` 的参数 `system node autosupport history retransmit` 命令

|===


== 技术支持触发的消息

技术支持可以使用 AutoSupport 按需功能从 AutoSupport 请求消息。

|===
| 发送消息时 | 消息的发送位置 


 a| 
AutoSupport 获取生成新 AutoSupport 消息的传送指令时
 a| 
中指定的地址 `-partner-address`

技术支持、IF `-support` 设置为 `enable` 和 `-transport` 设置为 `https`



 a| 
AutoSupport 获取重新发送过去 AutoSupport 消息的传送指令时
 a| 
技术支持、IF `-support` 设置为 `enable` 和 `-transport` 设置为 `https`



 a| 
当 AutoSupport 获取生成新 AutoSupport 消息以上传核心转储或性能归档文件的传送指令时
 a| 
技术支持、IF `-support` 设置为 `enable` 和 `-transport` 设置为 `https`。核心转储或性能归档文件将上传到技术支持站点。

|===