---
permalink: authentication/configure-ldap-server-access-task.html 
sidebar: sidebar 
keywords: configure, ldap, server access 
summary: 您必须先配置对 SVM 的 LDAP 服务器访问，然后 LDAP 帐户才能访问 SVM 。您可以使用 vserver services name-service ldap client create 命令在 SVM 上创建 LDAP 客户端配置。然后，您可以使用 vserver services name-service ldap create 命令将 LDAP 客户端配置与 SVM 相关联。 
---
= 配置 LDAP 服务器访问
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须先配置对 SVM 的 LDAP 服务器访问，然后 LDAP 帐户才能访问 SVM 。您可以使用 `vserver services name-service ldap client create` 命令在 SVM 上创建 LDAP 客户端配置。然后，您可以使用 `vserver services name-service ldap create` 命令将 LDAP 客户端配置与 SVM 相关联。

.您需要什么？ #8217 ；将需要什么
* 您必须已安装 link:install-ca-signed-server-digital-certificate-task.html["CA 签名的服务器数字证书"] 在 SVM 上。
* 要执行此任务，您必须是集群或 SVM 管理员。


大多数 LDAP 服务器都可以使用 ONTAP 提供的默认模式：

* MS-AD-BIS （大多数 Windows 2012 及更高版本 AD 服务器的首选架构）
* AD-IDMU （ Windows 2008 ， Windows 2012 及更高版本的 AD 服务器）
* AD-SFU （ Windows 2003 及更早版本的 AD 服务器）
* RFC-2307 （ UNIX LDAP 服务器）


除非另有要求，否则最好使用默认模式。如果是，您可以通过复制默认模式并修改副本来创建自己的模式。有关详细信息，请参见以下文档。

* link:../nfs-config/index.html["NFS 配置"]
* https://www.netapp.com/pdf.html?item=/media/19423-tr-4835.pdf["NetApp 技术报告 4835 ：《如何在 ONTAP 中配置 LDAP 》"]


.步骤
. 在 SVM 上创建 LDAP 客户端配置： `vserver services name-service ldap client create -vserver svm_name -client-config client_configuration -servers ldap_server_IPs -schema -use-start-tls true_false`
+
[NOTE]
====
仅支持使用启动 TLS 访问数据 SVM 。不支持访问管理 SVM 。

====
+
有关完整的命令语法，请参见 link:config-worksheets-reference.html["工作表"]。

+
以下命令会在 SVM``engData`` 上创建一个名为 `corp` 的 LDAP 客户端配置。客户端使用 IP 地址 `172.160.0.100` 和 `172.16.0.101` 匿名绑定到 LDAP 服务器。客户端使用 `RFC-2307` 架构进行 LDAP 查询。客户端与服务器之间的通信使用 Start TLS 进行加密。

+
[listing]
----
cluster1::>vserver services name-service ldap client create
-vserver engData -client-config corp -servers 172.16.0.100,172.16.0.101 -schema RFC-2307 -use-start-tls true
----
+
[NOTE]
====
从 ONTAP 9.2 开始，字段 ` -ldap-servers` 将取代字段 ` -servers` 。此新字段可以使用 LDAP 服务器的主机名或 IP 地址。

====
. 将 LDAP 客户端配置与 SVM 关联： `vserver services name-service ldap create -vserver svm_name -client-config client_configuration -client-enabled true_false`
+
有关完整的命令语法，请参见 link:config-worksheets-reference.html["工作表"]。

+
以下命令会将 LDAP 客户端配置 `corp` 与 SVM``engData`` 关联，并在 SVM 上启用 LDAP 客户端。

+
[listing]
----
cluster1::>vserver services name-service ldap create -vserver engData -client-config corp -client-enabled true
----
+
[NOTE]
====
从 ONTAP 9.2 开始， `vserver services name-service ldap create` 命令将执行自动配置验证，如果 ONTAP 无法与名称服务器联系，则会报告错误消息。

====
. 使用 vserver services name-service ldap check 命令验证名称服务器的状态。
+
以下命令将验证 SVM vs0 上的 LDAP 服务器。

+
[listing]
----
cluster1::> vserver services name-service ldap check -vserver vs0

| Vserver: vs0                                                |
| Client Configuration Name: c1                               |
| LDAP Status: up                                             |
| LDAP Status Details: Successfully connected to LDAP server "10.11.12.13".                                              |
----
+
从 ONTAP 9.2 开始，可以使用 name service check 命令。


