---
permalink: authentication/define-custom-roles-task.html 
sidebar: sidebar 
keywords: define, custom roles 
summary: 您可以使用 security login role create 命令定义自定义角色。您可以根据需要多次执行此命令，以实现要与角色关联的功能的精确组合。 
---
= 为ONTAP管理员定义自定义角色
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `security login role create`命令定义自定义角色。您可以根据需要多次执行此命令，以实现要与角色关联的功能的精确组合。

.关于此任务
* 角色（无论是预定义的还是自定义的）可以授予或拒绝对 ONTAP 命令或命令目录的访问权限。
+
命令目录 (`volume`(例如)是一组相关命令和命令子目录。除非本操作步骤中所述，否则授予或拒绝对命令目录的访问权限将授予或拒绝对该目录及其子目录中的每个命令的访问权限。

* 特定命令访问或子目录访问将覆盖父目录访问。
+
如果使用命令目录定义角色，然后为某个特定命令或父目录的子目录再次定义不同的访问级别，则为该命令或子目录指定的访问级别将覆盖父级的访问级别。




NOTE: 您不能为SVM管理员分配一个角色来访问仅对可用的命令或命令目录 `admin` 群集管理员--例如 `security` 命令目录。

.开始之前
您必须是集群管理员才能执行此任务。

.步骤
. 定义自定义角色：
+
`security login role create -vserver SVM_name -role role -cmddirname command_or_directory_name -access access_level -query query`

+
以下命令用于授予 `vol_role` 对中命令的角色完全访问权限 `volume` 命令目录以及对中命令的只读访问权限 `volume snapshot` 子目录。

+
[listing]
----
cluster1::>security login role create -role vol_role -cmddirname "volume" -access all

cluster1::>security login role create -role vol_role -cmddirname "volume snapshot" -access readonly
----
+
以下命令用于授予 `SVM_storage` 对中的命令的只读角色访问权限 `storage` 命令目录、无法访问中的命令 `storage encryption` 子目录、以及对的完全访问权限 `storage aggregate plex offline` 非内在命令。

+
[listing]
----
cluster1::>security login role create -role SVM_storage -cmddirname "storage" -access readonly

cluster1::>security login role create -role SVM_storage -cmddirname "storage encryption" -access none

cluster1::>security login role create -role SVM_storage -cmddirname "storage aggregate plex offline" -access all
----
+
有关的详细信息 `security login role create`，请参见link:https://docs.netapp.com/us-en/ontap-cli/security-login-role-create.html["ONTAP 命令参考"^]。



.相关信息
* link:https://docs.netapp.com/us-en/ontap-cli/security-login-role-create.html["创建安全登录角色"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-plex-offline.html["存储聚合丛脱机"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=storage+encryption["存储加密"^]

