---
permalink: authentication/enable-ssl-certificate-accounts-task.html 
sidebar: sidebar 
keywords: enable, ssl certificate, accounts, security login create 
summary: 您可以使用 security login create 命令使管理员帐户能够使用 SSL 证书访问管理员或数据 SVM 。 
---
= 启用 SSL 证书帐户
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `security login create` 命令以使管理员帐户能够使用SSL证书访问管理员或数据SVM。

.关于此任务
* 您必须先安装 CA 签名的服务器数字证书，帐户才能访问 SVM 。
+
xref:install-server-certificate-cluster-svm-ssl-server-task.adoc[生成并安装 CA 签名的服务器证书]

+
您可以在启用帐户访问之前或之后执行此任务。

* 如果您不确定要分配给登录帐户的访问控制角色、可以稍后使用添加此角色 `security login modify` 命令：
+
xref:modify-role-assigned-administrator-task.adoc[修改分配给管理员的角色]




NOTE: 对于集群管理员帐户、支持通过证书身份验证 `http`， `ontapi`，和 `rest` 应用程序。对于SVM管理员帐户、只有支持使用证书身份验证 `ontapi` 和 `rest` 应用程序。

.步骤
. 允许本地管理员帐户使用 SSL 证书访问 SVM ：
+
`security login create -vserver SVM_name -user-or-group-name user_or_group_name -application application -authmethod authentication_method -role role -comment comment`

+
有关完整的命令语法，请参见 link:https://docs.netapp.com/us-en/ontap/concepts/manual-pages.html["按版本显示 ONTAP 手册页"]。

+
以下命令将启用SVM管理员帐户 `svmadmin2` 使用默认值 `vsadmin` 访问SVM的角色``engData2`` 使用SSL数字证书。

+
[listing]
----
cluster1::>security login create -vserver engData2 -user-or-group-name svmadmin2 -application ontapi -authmethod cert
----


.完成后
如果您尚未安装 CA 签名的服务器数字证书，则必须先安装此证书，然后帐户才能访问 SVM 。

xref:install-server-certificate-cluster-svm-ssl-server-task.adoc[生成并安装 CA 签名的服务器证书]
