---
permalink: authentication/setup-ssh-multifactor-authentication-task.html 
sidebar: sidebar 
keywords: enable, ssh, multifactor authentication, mfa, hardware authentication device 
summary: 从 ONTAP 9.3 开始，您可以使用 security login create 命令来增强安全性，方法是要求管理员使用 SSH 公有密钥和用户密码登录到管理员或数据 SVM 。 
---
= 启用 SSH 多因素身份验证（ MFA ）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
从ONTAP 9.3开始、您可以使用 `security login create` 命令以增强安全性、方法是要求管理员使用SSH公有 密钥和用户密码登录到管理员或数据SVM。

从ONTAP 9.12.1开始、您可以使用FID02 (快速身份联机)或个人身份验证(PIV)身份验证标准对SSH客户端MFA使用优键硬件身份验证设备。

了解更多信息 link:https://www.netapp.com/pdf.html?item=/media/17055-tr4647pdf.pdf["ONTAP 9中的多因素身份验证(TR-4647)"^]。

您必须是集群管理员才能执行此任务。

.关于此任务
* 您必须先将公有密钥与帐户关联，然后帐户才能访问 SVM 。
+
link:manage-public-key-authentication-concept.html["将公有密钥与用户帐户关联"]

+
您可以在启用帐户访问之前或之后执行此任务。

* 如果您不确定要分配给登录帐户的访问控制角色，可以稍后使用 `ssecurity login modify` 命令添加此角色。
+
link:modify-role-assigned-administrator-task.html["修改分配给管理员的角色"]

* 用户始终通过公有密钥身份验证进行身份验证，然后进行密码身份验证。


.步骤
. 需要本地管理员帐户才能使用 SSH MFA 访问 SVM ：
+
`ssecurity login create -vserver _svm_ -user-or-group-name _user_name_ -application ssh -authentication-method password_publickey -role admin -second-authentication-method password_publickey`

+
以下命令要求具有预定义 `admin` 角色的 SVM 管理员帐户 `admin2` 使用 SSH 公有密钥和用户密码登录到 SVM``engData1`` ：

+
[listing]
----
cluster-1::> security login create -vserver engData1 -user-or-group-name admin2 -application ssh -authentication-method publickey -role admin -second-authentication-method password

Please enter a password for user 'admin2':
Please enter it again:
Warning: To use public-key authentication, you must create a public key for user "admin2".
----


如果您尚未将公有密钥与管理员帐户关联，则必须先将其关联，然后该帐户才能访问 SVM 。

link:manage-public-key-authentication-concept.html["将公有密钥与用户帐户关联"]
